### ISSUE TITLE
Leap 15

### ISSUE THREAD

**Issue by dragon2611** [uyuni-project/uyuni#1068]
Is there any estimate on when Leap 15 will be supported, as 42.3 is scheduled to go EOL at the end of the month.

I'm ok with installing on 42.3 initially as a test but I wouldn't want to deploy on 42.3 if I could avoid it.

**Comment by juliogonzalez** [comment]
Hi @dragon2611,

I sent the following announcement yesterday to the [Uyuni mailing lists](https://www.uyuni-project.org/contact.html#ml) (I encourage you to join):

> Hello,
> 
> In preparation for the next release of Uyuni, we switched the base OS for 
> Master (the development version) Server and Proxy to openSUSE Leap 15.1
> 
> https://www.uyuni-project.org/devel-version.html is now updated showing this.
> 
> For new installations, please use the new repositories.
> 
> For older installations remember that updating is not supported, but if you 
> still want to try, replace the repositories at /etc/zypper/repos.d and adjust 
> your synced repositories the server.
> 
> Please remember that Uyuni Master is intended for development and testing, and 
> not for production.
> 
> We cannot still give you an exact date for release of the next version, but we 
> expect to have it ready in the next two to four weeks, and it will have big 
> new features such as support for Ubuntu clients, monitoring with prometheus 
> and grafana and much more.
> 
> Stay tuned!

**Comment by juliogonzalez** [comment]
We have now support for Leap 15.0 and 15.1, so closing the issue.
