### ISSUE TITLE
Centos 7 bootstrap on Dev Release

### ISSUE THREAD

**Issue by dragon2611** [uyuni-project/uyuni#1077]
Centos 7 Fails to bootstrap out of the box with 4.0RC1 (Dev release) installed on Leap 15.1

It seems that you need epel-release on the centos machine for the salt minion to install

Also /etc/salt/minion.d doesn't appear to get created, creating the directory manually seems to fix the issue

**Comment by dragon2611** [comment]
I suspect I've messed something up as although it claims to have bootstrapped successfully it looks like the centos machine is missing the module to list packages.

**Comment by dragon2611** [comment]
It looks like the version of Salt you are supposed to use with uyuni is not installable on C7

> [root@test-c7 ~]# yum update
> Loaded plugins: fastestmirror, susemanagerplugin
> Loading mirror speeds from cached hostfile
>  * epel: mirrors.coreix.net
> susemanager:centos7x                                     | 1.5 kB     00:00
> susemanager:centos7x/primary                               | 6.8 MB   00:00
> susemanager:centos7x                                                                                                                23799/23799
> Resolving Dependencies
> --> Running transaction check
> ---> Package hwdata.x86_64 0:0.252-9.1.el7 will be updated
> ---> Package hwdata.noarch 0:0.314-3.1 will be an update
> ---> Package salt.noarch 0:2015.5.10-2.el7 will be updated
> ---> Package salt.x86_64 0:2018.3.0-33.1 will be an update
> --> Processing Dependency: python2-salt = 2018.3.0-33.1 for package: salt-2018.3.0-33.1.x86_64
> ---> Package salt-minion.noarch 0:2015.5.10-2.el7 will be updated
> ---> Package salt-minion.x86_64 0:2018.3.0-33.1 will be an update
> --> Running transaction check
> ---> Package python2-salt.x86_64 0:2018.3.0-33.1 will be installed
> --> Processing Dependency: python-msgpack-python > 0.3 for package: python2-salt-2018.3.0-33.1.x86_64
> --> Processing Dependency: python-tornado >= 4.2.1 for package: python2-salt-2018.3.0-33.1.x86_64
> --> Processing Dependency: python-pyzmq >= 2.2.0 for package: python2-salt-2018.3.0-33.1.x86_64
> Package python-zmq-14.5.0-400.3.1.develHead.x86_64 is obsoleted by python2-zmq-14.7.0-8.el7.x86_64 which is already installed
> --> Processing Dependency: python-pycrypto >= 2.6.1 for package: python2-salt-2018.3.0-33.1.x86_64
> --> Processing Dependency: python-futures >= 2.0 for package: python2-salt-2018.3.0-33.1.x86_64
> --> Processing Dependency: python-psutil for package: python2-salt-2018.3.0-33.1.x86_64
> --> Running transaction check
> ---> Package python-msgpack-python.x86_64 0:0.4.6-2.1 will be installed
> ---> Package python-pycrypto.x86_64 0:2.6.1-2.1 will be installed
> ---> Package python-tornado.x86_64 0:4.2.1-4.el7 will be installed
> ---> Package python2-futures.noarch 0:3.1.1-5.el7 will be installed
> ---> Package python2-psutil.x86_64 0:2.2.1-5.el7 will be installed
> ---> Package python2-salt.x86_64 0:2018.3.0-33.1 will be installed
> --> Processing Dependency: python-pyzmq >= 2.2.0 for package: python2-salt-2018.3.0-33.1.x86_64
> Package python-zmq-14.5.0-400.3.1.develHead.x86_64 is obsoleted by python2-zmq-14.7.0-8.el7.x86_64 which is already installed
> --> Finished Dependency Resolution
> Error: Package: python2-salt-2018.3.0-33.1.x86_64 (susemanager:centos7x)
>            Requires: python-pyzmq >= 2.2.0
>            Available: python-zmq-14.5.0-400.3.1.develHead.x86_64 (susemanager:centos7x)
>                python-pyzmq = 14.5.0-400.3.1.develHead
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
> [root@test-c7 ~]#

**Comment by juliogonzalez** [comment]
It seems to me you are using an outdated version of the packages.

Salt for CentOS7 is 2019.2.0 since a month ago (https://build.opensuse.org/package/view_file/systemsmanagement:Uyuni:Master:CentOS7-Uyuni-Client-Tools/salt/salt.spec?expand=1  https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/CentOS7-Uyuni-Client-Tools/CentOS_7/x86_64/)

Maybe you need to resync your client tools repositories on the server, and then recreate bootstrap repositories.

BTW: It seems to me you are directly managing the test VM and adding repositories there. Don't do that: you need to bootstrap the VM with one of the available methods, and at that point Uyuni will take care of managing the repositories.

**Comment by dragon2611** [comment]
Seems I accidentally synced the stable repo, that said it still doesn't want to re-install the salt minion

`[root@test-c7 ~]# yum install salt-minion
Loaded plugins: fastestmirror, susemanagerplugin
Determining fastest mirrors
susemanager:centos7x                                                                                                                                                                                                  | 1.5 kB  00:00:00
(1/2): susemanager:centos7x/group                                                                                                                                                                                     | 893 kB  00:00:00
(2/2): susemanager:centos7x/primary                                                                                                                                                                                   | 6.8 MB  00:00:00
susemanager:centos7x                                                                                                                                                                                                             23896/23896
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.x86_64 0:2019.2.0-18.1 will be installed
--> Processing Dependency: salt = 2019.2.0-18.1 for package: salt-minion-2019.2.0-18.1.x86_64
--> Running transaction check
---> Package salt.x86_64 0:2019.2.0-18.1 will be installed
--> Processing Dependency: python2-salt = 2019.2.0-18.1 for package: salt-2019.2.0-18.1.x86_64
--> Running transaction check
---> Package python2-salt.x86_64 0:2019.2.0-18.1 will be installed
--> Processing Dependency: python-msgpack-python > 0.3 for package: python2-salt-2019.2.0-18.1.x86_64
--> Processing Dependency: python-tornado >= 4.2.1 for package: python2-salt-2019.2.0-18.1.x86_64
--> Processing Dependency: python-pyzmq >= 2.2.0 for package: python2-salt-2019.2.0-18.1.x86_64
Package python-zmq is obsoleted by python2-zmq, but obsoleting package does not provide for requirements
--> Processing Dependency: python-pycrypto >= 2.6.1 for package: python2-salt-2019.2.0-18.1.x86_64
--> Processing Dependency: python-futures >= 2.0 for package: python2-salt-2019.2.0-18.1.x86_64
--> Processing Dependency: python-psutil for package: python2-salt-2019.2.0-18.1.x86_64
--> Running transaction check
---> Package python-msgpack-python.x86_64 0:0.4.6-2.4 will be installed
---> Package python-pycrypto.x86_64 0:2.6.1-2.4 will be installed
---> Package python-tornado.x86_64 0:4.2.1-4.el7 will be installed
---> Package python2-futures.noarch 0:3.1.1-5.el7 will be installed
---> Package python2-psutil.x86_64 0:2.2.1-5.el7 will be installed
---> Package python2-salt.x86_64 0:2019.2.0-18.1 will be installed
--> Processing Dependency: python-pyzmq >= 2.2.0 for package: python2-salt-2019.2.0-18.1.x86_64
Package python-zmq is obsoleted by python2-zmq, but obsoleting package does not provide for requirements
--> Finished Dependency Resolution
Error: Package: python2-salt-2019.2.0-18.1.x86_64 (susemanager:centos7x)
           Requires: python-pyzmq >= 2.2.0
           Available: python-zmq-14.5.0-3.4.x86_64 (susemanager:centos7x)
               python-pyzmq = 14.5.0-3.4
           Available: python-zmq-14.5.0-400.3.1.develHead.x86_64 (susemanager:centos7x)
               python-pyzmq = 14.5.0-400.3.1.develHead
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@test-c7 ~]#
`

**Comment by juliogonzalez** [comment]
What happens if you just use a new VM and you try to bootstrap from the WebUI, instead of installing the minion manually?

Just in case, remember to create an activation key, assign there the channel(s) you have for CentOS7 and the channel(s) you have for the client tools for CentOS7. Then use that activation key to bootstrap.

**Comment by dragon2611** [comment]
If I run bootstrap on a brand new c7 machine.

> service_|-salt-minion_|-salt-minion_|-running(retcode=2): One or more requisite failed: bootstrap./etc/salt/minion_id, bootstrap.salt-minion-package, bootstrap./etc/salt/pki/minion/minion.pub, bootstrap./etc/salt/pki/minion/minion.pem, bootstrap./etc/salt/minion.d/susemanager.conf file_|-/etc/salt/minion_id_|-/etc/salt/minion_id_|-managed(retcode=2): One or more requisite failed: bootstrap.salt-minion-package file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): One or more requisite failed: bootstrap.salt-minion-package file_|-/etc/salt/pki/minion/minion.pem_|-/etc/salt/pki/minion/minion.pem_|-managed(retcode=2): One or more requisite failed: bootstrap.salt-minion-package file_|-/etc/salt/pki/minion/minion.pub_|-/etc/salt/pki/minion/minion.pub_|-managed(retcode=2): One or more requisite failed: bootstrap.salt-minion-package pkg_|-salt-minion-package_|-salt-minion_|-installed(retcode=2): Error occurred installing package(s). Additional info follows: errors: - Running scope as unit run-13710.scope. Loaded plugins: fastestmirror Loading mirror speeds from cached hostfile * base: mirror.sov.uk.goscomb.net * extras: centos.serverspace.co.uk * updates: mirrors.coreix.net No package salt-minion available. Error: Nothing to do

**Comment by dragon2611** [comment]
If I manually add the tools repo then it can bootstrap, otherwise it's a catch 22 in that it can't install salt until it adds the uyuni server/proxy but it won't add the uyuni server's channel until it's further on the in the bootstrap process.

For Clarity it's this that I added to the yum repo's


> [systemsmanagement_Uyuni_Master_CentOS7-Uyuni-Client-Tools]
name=systemsmanagement:Uyuni:Master:CentOS7-Uyuni-Client-Tools (CentOS_7)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/CentOS7-Uyuni-Client-Tools/CentOS_7/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/CentOS7-Uyuni-Client-Tools/CentOS_7/repodata/repomd.xml.key
enabled=1

However this will leave you with problems because although salt has installed you now have a package update you cannot install

> [root@c7 ~]# yum upgrade
Loaded plugins: fastestmirror, susemanagerplugin, yumnotify
Determining fastest mirrors
susemanager:centos7x                                                                                                                                                                                                  | 1.5 kB  00:00:00
(1/2): susemanager:centos7x/group                                                                                                                                                                                     | 893 kB  00:00:00
(2/2): susemanager:centos7x/primary                                                                                                                                                                                   | 6.8 MB  00:00:00
susemanager:centos7x                                                                                                                                                                                                             23896/23896
Resolving Dependencies
--> Running transaction check
---> Package hwdata.x86_64 0:0.252-9.1.el7 will be updated
---> Package hwdata.noarch 0:0.314-3.4 will be an update
---> Package python-psutil.x86_64 0:1.2.1-0.10.4 will be obsoleted
---> Package python-zmq.x86_64 0:14.5.0-3.4 will be obsoleted
--> Processing Dependency: python-pyzmq >= 2.2.0 for package: python2-salt-2019.2.0-18.1.x86_64
---> Package python2-psutil.x86_64 0:2.2.1-5.el7 will be obsoleting
---> Package python2-zmq.x86_64 0:14.7.0-8.el7 will be obsoleting
---> Package zeromq.x86_64 0:4.0.5-1.4 will be updated
--> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.5.0-400.3.1.develHead.x86_64
---> Package zeromq.x86_64 0:4.1.4-6.el7 will be an update
--> Processing Dependency: libpgm-5.2.so.0()(64bit) for package: zeromq-4.1.4-6.el7.x86_64
--> Processing Dependency: libsodium.so.23()(64bit) for package: zeromq-4.1.4-6.el7.x86_64
--> Running transaction check
---> Package libsodium.x86_64 0:1.0.17-1.el7 will be installed
---> Package openpgm.x86_64 0:5.2.122-2.el7 will be installed
---> Package python-zmq.x86_64 0:14.5.0-3.4 will be updated
---> Package python-zmq.x86_64 0:14.5.0-400.3.1.develHead will be an update
--> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.5.0-400.3.1.develHead.x86_64
---> Package zeromq.x86_64 0:4.0.5-1.4 will be updated
--> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.5.0-400.3.1.develHead.x86_64
Removing python-zmq.x86_64 0:14.5.0-400.3.1.develHead - u due to obsoletes from python2-zmq.x86_64 0:14.7.0-8.el7 - u
susemanager:centos7x/filelists                                                                                                                                                                                        |  19 MB  00:00:00
--> Restarting Dependency Resolution with new changes.
--> Running transaction check
---> Package python-zmq.x86_64 0:14.5.0-400.3.1.develHead will be an update
--> Processing Dependency: python-pyzmq >= 2.2.0 for package: python2-salt-2019.2.0-18.1.x86_64
---> Package zeromq.x86_64 0:4.0.5-1.4 will be updated
--> Finished Dependency Resolution
Error: Package: python-zmq-14.5.0-400.3.1.develHead.x86_64 (susemanager:centos7x)
           Requires: libzmq.so.4()(64bit)
           Removing: zeromq-4.0.5-1.4.x86_64 (@systemsmanagement_Uyuni_Master_CentOS7-Uyuni-Client-Tools)
               libzmq.so.4()(64bit)
           Updated By: zeromq-4.1.4-6.el7.x86_64 (susemanager:centos7x)
              ~libzmq.so.5()(64bit)
           Available: zeromq-4.0.5-400.1.1.develHead.x86_64 (susemanager:centos7x)
               libzmq.so.4()(64bit)
Error: Package: python2-salt-2019.2.0-18.1.x86_64 (@systemsmanagement_Uyuni_Master_CentOS7-Uyuni-Client-Tools)
           Requires: python-pyzmq >= 2.2.0
           Removing: python-zmq-14.5.0-3.4.x86_64 (@systemsmanagement_Uyuni_Master_CentOS7-Uyuni-Client-Tools)
               python-pyzmq = 14.5.0-3.4
           Obsoleted By: python2-zmq-14.7.0-8.el7.x86_64 (susemanager:centos7x)
               Not found
           Updated By: python-zmq-14.5.0-400.3.1.develHead.x86_64 (susemanager:centos7x)
               python-pyzmq = 14.5.0-400.3.1.develHead
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

The problem is essentially with python-zmq 

My channel contains Centos Base, Centos Extras, EPEL, Docker-CE, and the Uyuni Client Tools C7 repository from the Dev version.

**Comment by juliogonzalez** [comment]
Thanks a lot for all the research.

I will try to give it a try soon and see what we can do about this. Maybe we will need to adapt the SPEC for salt a little. 

On paper the only zeromq supported version is the one from CentOS7/RHEL7, but of course I think EPEL is important enough to keep salt installable when the repository is present.

**Comment by juliogonzalez** [comment]
@brejoc I will initially assign this to myself, to research how we could fix the problem.

If we finally need to change the SPEC somehow, I will ping you and we'll add someone from your squad as assignee.

**Comment by juliogonzalez** [comment]
Adding some related info from the list:

https://github.com/saltstack/salt/issues/34575

```
--> Processing Dependency: python-pyzmq >= 2.2.0 for package:
python2-salt-2019.2.0-18.1.x86_64
---> Package python2-zmq.x86_64 0:14.7.0-8.el7 will be obsoleting
--> Processing Dependency: libzmq.so.5()(64bit) for package:
python2-zmq-14.7.0-8.el7.x86_64
--> Finished Dependency Resolution
Error: Package: python2-salt-2019.2.0-18.1.x86_64
(@susemanager:centos7-uyuni-client)
           Requires: python-pyzmq >= 2.2.0
           Removing: python-zmq-14.5.0-3.4.x86_64
(@susemanager:centos7-uyuni-client)
               python-pyzmq = 14.5.0-3.4
           Obsoleted By: python2-zmq-14.7.0-8.el7.x86_64
(susemanager:centos7-epel)
               Not found
Error: Package: python2-zmq-14.7.0-8.el7.x86_64 (susemanager:centos7-epel)
           Requires: libzmq.so.5()(64bit)
 You could try using --skip-broken to work around the problem

Package python-pyzmq >= 2.2.0 not exists on CentOS.
```

**Comment by dragon2611** [comment]
@juliogonzalez blocking python-zmq* and zeromq* from syncing from EPEL with a filter and then removing them from the channel may work as a work around for now.

**Comment by juliogonzalez** [comment]
Right, that's a valid workaround until we can find a fix.

On paper neither Uyuni or SUSE Manager will support third party repositories, but IMHO EPEL is somehow different (let's say it's... almost mandatory in most cases), so I think we can make an exception and see what we can do.

Sadly I could not handle it yet, but I hope I will eventually have a look in the upcoming weeks.

**Comment by juliogonzalez** [comment]
Something that got list, but AFAIK we discussed this since last time.

@brejoc we didn't come to any conclusion, am I right?

**Comment by paususe** [comment]
This was actually a bug in EPEL and they fixed it a while ago:

- https://bugzilla.redhat.com/show_bug.cgi?id=1789889
- https://src.fedoraproject.org/rpms/python-zmq/pull-request/6

(notwithstanding that we alread providedy a workaround on our own packaging)

**Comment by brejoc** [comment]
Yes, it was actually us that fixed this in the EPEL package. Please let me know if you still run into problems.
