### ISSUE TITLE
Fedora 31 will use zstd compression for RPM payloads, Uyuni can't handle them

### ISSUE THREAD

**Issue by Conan-Kudo** [uyuni-project/uyuni#1108]
Fedora is considering to use `zstd` for rpm:
https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression

At this time, there's no SUSE Linux release with support for zstd payloads. It will hopefully land in Tumbleweed soon, as `Base:System/rpm` just got it turned on yesterday (no SR created yet).

zstd compression support has been enabled in Fedora since Fedora 28, so now it's just for using it as the payload.

**Comment by juliogonzalez** [comment]
Good to know. Thanks!

Most probably we'll need to add it to Uyuni directly, until the Base OS (Leap 15.2? 15.3?) can handle it.

**Comment by Conan-Kudo** [comment]
This change has been accepted and will be implemented as part of Fedora 31, so we definitely need to prepare for it.

**Comment by juliogonzalez** [comment]
Schedule for Fedora 31: https://fedoraproject.org/wiki/Releases/31/Schedule

I will check with openSUSE Maintenace team how to add packages to Leap, but I am pretty sure we'll need to build the package directly at Uyuni.

**Comment by Conan-Kudo** [comment]
@juliogonzalez Leap 15.1 already includes zstd, the rpm and deltarpm packages just don't have zstd support.

As for createrepo_c, the version in SUSE distributions is crippled and can't create repositories for deltarpms. :(

**Comment by joesusecom** [comment]
Has one of you already reached out to the openSUSE team to investigate whether there are any plans for moving to zstd as well? In any case we should make sure that we have this in place to support future Fedora versions. But this could potentially have a very positive impact on build times in OBS and for container build pipelines. While the final compression of a built RPM may take longer, uncompressing packages for the build environment faster would probably over-compensate that. Same for containers built from existing RPMs.

**Comment by Conan-Kudo** [comment]
@joesusecom Fedora's consideration of this has sparked a discussion in openSUSE, but it can't proceed any further until my SR to enable zstd in Factory actually makes it into Factory: https://build.opensuse.org/request/show/709948

**Comment by Conan-Kudo** [comment]
Unfortunately, the `build` package is holding up the `openSUSE:Factory:Staging:A` is holding up my SR from landing... :(

**Comment by juliogonzalez** [comment]
@Conan-Kudo I see https://build.opensuse.org/request/show/709948 is accepted now.

But it's not part of Leap 15.2 or SLE15SP2. Should I submit it, as I did for `createrepo_c`?

**Comment by Conan-Kudo** [comment]
@juliogonzalez I believe you'll need to make an SR in IBS to SLE 15 SP2 and then things should move from there.

**Comment by juliogonzalez** [comment]
Right, same as I did for `createrepo_c`. Will do it now.

**Comment by juliogonzalez** [comment]
Mmmmm, this could prove more problematic than I expected.

For the moment both `rpm` and `python-rpm` are failing for SLE15SP2:

`rpm`:
```
nothing provides pkgconfig(libzstd)
```
`python-rpm`:
```
nothing provides pkgconfig(libzstd)
```
Seems to me I will need to submit something else. Researching what exactly.

**Comment by juliogonzalez** [comment]
Most probably https://build.opensuse.org/package/view_file/openSUSE:Factory/zstd/zstd.spec?expand=1

**Comment by juliogonzalez** [comment]
Well, zstd gets the package to build for all architectures, except x86_64 and s390x, but I suspect this has something to do with a rebuild going on:

Error is: `nothing provides rpm-config-SUSE needed by rpm`

Will have another look tomorrow.

**Comment by juliogonzalez** [comment]
@Conan-Kudo it seems that package is at [openSUSE:Factory](https://build.opensuse.org/package/view_file/openSUSE:Factory/rpm-config-SUSE/rpm-config-SUSE.changes?expand=1) but not at SLE15SP2... and I am failing to understand why.

I could, of course, try a submission of `rpm-config-SUSE` as well, but it's strange it's not at SLE15SP2 as it seems the package is at openSUSE:Factory for at least one year, according to the revisions.

What's that package about and why is it needed?

**Comment by juliogonzalez** [comment]
Mmmmm, if I added `rpm-config-SUSE` to my internal project, then it fails with:
```
nothing provides librpm.so.8()(64bit) needed by rpmlint-mini, nothing provides librpmio.so.8()(64bit) needed by rpmlint-mini, nothing provides librpmbuild.so.8()(64bit) needed by rpmlint-mini, nothing provides librpmsign.so.8()(64bit) needed by rpmlint-mini
```
Is it me, or we have a circular dependency here?

**Comment by Conan-Kudo** [comment]
Shortly after SLE 15 branched from Factory, the SUSE vendor configuration was split out of RPM (... mostly) into a new package `rpm-config-SUSE`. Over time, more of the SUSE-specific stuff will move from RPM from `rpm-config-SUSE`.

For SUSE Linux 15 products, you'll need to craft a specific SR against `rpm` in SLE 15. Branch `rpm` in IBS and make the changes there...

**Comment by juliogonzalez** [comment]
I already branched rpm at `IBS` and I am having such problems.

> For SUSE Linux 15 products, you'll need to craft a specific SR against rpm in SLE 15.

Not sure what you mean. Submitting a previous revision of `rpm` package instead of the most recent one?

https://build.opensuse.org/package/revisions/openSUSE:Factory/rpm <-- rev 272 for example?

**Comment by juliogonzalez** [comment]
Strange... I now removed `rpm` and `rpm-config-SUSE` from my internal project... and zstd builds, including `x86_64` and `s390x`.

Weird, maybe something changed during the weekend at the SLE15SP2 codestream.

**Comment by Conan-Kudo** [comment]
This is what you need to do internally: https://build.opensuse.org/package/rdiff/home:Pharaoh_Atem:branches:SUSE:SLE-15-SP2:GA/rpm?linkrev=base&rev=2

**Comment by juliogonzalez** [comment]
Ok, so this change itself is NOT at `openSUSE:Factory` as I expected. That's why I had problems.

Or better said, at `openSUSE:Factory` we have:
```--enable-zstd \```

But we don't have
```BuildRequires:  libzstd-devel```

How is it that we miss the `BuildRequires` at `openSUSE:Factory` is it provided by any other package?

**Comment by Conan-Kudo** [comment]
In the Factory package, it's being pulled in by the `BuildRequires: pkgconfig(libzstd)` line.

**Comment by juliogonzalez** [comment]
ACK. I just wanted to understand.

As for the SLE15SP2 submission, so far it's building fine on my branch. I will start with the submission soon.

**Comment by juliogonzalez** [comment]
Submission done. I added an explanation of why we needed and why the change is not at Factory. If we are lucky, they will accept it, but I am not sure when exactly it will get into Leap 15.2.

**Comment by juliogonzalez** [comment]
In the end, the submission I done was revoked (there was another one adding the support for Leap > 15.0, but I requested to add it for SLE15SP2 as well).

It's on Staging, so hopefully it will get approved soon, and that will create a SR for Leap 15.2

**Comment by juliogonzalez** [comment]
Mmmm, checking where the SR is, as I still can't see the change at https://build.opensuse.org/package/view_file/openSUSE:Leap:15.2/rpm/rpm.changes?expand=1

**Comment by juliogonzalez** [comment]
Ok, it was accepted at SLE15SP2, and there's already a SR pending approval for Leap 15.2: https://build.opensuse.org/request/show/787013 :-)

**Comment by sbluhm** [comment]
Can this issue be closed?

**Comment by juliogonzalez** [comment]
I see this at the `rpm` package for Leap 15.3:
```
* jue ene 16 2020 mls@suse.de
- Backport more ndb fixes from upstram
  modified patch: ndb-backport.diff
- Build with zstd support in openSUSE Leap 15
  and SLE-15-SP2 [bnc#1162668]

```
So I'd say we can close this card already.

@Conan-Kudo?

**Comment by Conan-Kudo** [comment]
I assume we should be in good shape now.
