### ISSUE TITLE
System reboot scheduled by admin failed (uyuni trying to reboot remote host)

### ISSUE THREAD

**Issue by svagml** [uyuni-project/uyuni#1124]
Hello,

Uyuni version 4.0.1

New to Uyuni.  I have it installed with one centos7 server as a client/minion.  Remote execution and single package deployment seems to work, but scheduling a reboot, "Package List Refresh scheduled by (none)", and "Subscribe channels scheduled by admin" works. 

The client returned the following for the reboot request:
"ERROR executing \u0027system.reboot\u0027: The following keyword arguments are not valid: at_time\u003d3"

On the client, under /var/log/messages
Jun 19 22:36:41 localhost salt-minion: [ERROR   ] Problem executing 'system.reboot': The following keyword arguments are not valid: at_time=3

I found this from google:
https://github.com/saltstack/salt/issues/50730

Although, my salt skills are lacking, so not sure where to proceed.  I'll try adding an opensuse leap server to see if I have the same problem. 

Thanks!

**Comment by joesusecom** [comment]
Which Salt packages are you using on the CentOS system? Chances are that this is already fixed in the ones SUSE maintains.

**Comment by svagml** [comment]
I fixed the reboot issue by removing the system, deleting the channel, adding the channel via the command line vs. the GUI, removing salt, add salt's official repo, installing salt-minion from said repo.  Not sure what version it was, but now it's:

[centos@tf-centos-test-1 ~]$ sudo salt-minion --version
/usr/lib/python2.7/site-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
salt-minion 2019.2.0 (Fluorine)

**Comment by srbarrios** [comment]
We don't reproduce this issue anymore in latest Uyuni version. I will close the card, please if you reproduce it again, feel free to re-open. Thanks!
