### ISSUE TITLE
Use meaningful names for variables

### ISSUE THREAD

**Issue by MalloZup** [uyuni-project/uyuni#114]
At moment we have Variable like this:

https://github.com/uyuni-project/uyuni/blob/master/testsuite/features/step_definitions/navigation_steps.rb#L219

It would be better to have meaningful names that show their usage

Example:

https://github.com/uyuni-project/uyuni/blob/master/testsuite/features/step_definitions/navigation_steps.rb#L246

should be like `text` or `command`.

This are just some few examples

**Comment by srbarrios** [comment]
On test suite code scope, I think we can say this card can be closed.
