### ISSUE TITLE
uyuni refuses to sync deb repo

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni#1163]
It seems that uyuni (recently reinstalled from scratch) refuses to download any packages from a freshly added debian repo.
Here is the output I got:
uyuni:/var/log/rhn/reposync # /usr/bin/spacewalk-repo-sync -c ubuntu-18-main-x86_64 --type deb --non-interactive -vvvvvv
2019-07-14 12:18:14,475 urlgrabber version  = 3.9.1
2019-07-14 12:18:14,475 trans function "_"  = <function _ at 0x7fdb6a324230>
12:18:15 ======================================
12:18:15 | Channel: ubuntu-18-main-x86_64
12:18:15 ======================================
12:18:15 Sync of channel started.
12:18:16 Repo URL: http://bg.archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64/
12:18:16     Packages in repo:              6391
12:18:16     No new packages to sync.
12:18:16 
12:18:16   Patches in repo: 0.
12:18:16 Sync completed.
12:18:16 Total time: 0:00:01

Removing the leading 'http://' (I was thinking about issue #1095) doesn't work as we got a traceback about the protocol. So this one is not related to #1095 .

**Comment by ajcody** [comment]
I hit this with SUMA 4, but doing the setup and sync attempt in the web UI. I ended up getting ubuntu sync'ed by the CLI with the following:
spacewalk-report channels | grep -i ubun 
and then for each match
spacewalk-repo-sync --channel ubuntu-bionic-main-18.04 
13:43:05 ====================================== 
13:43:05 | Channel: ubuntu-bionic-main-18.04 
13:43:05 ====================================== 
13:43:05 Sync of channel started. 
13:43:08 Repo URL: http://archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64/
13:43:08 Packages in repo: 6391 
13:43:58 Packages already synced: 0 
13:43:58 Packages to sync: 6391 
13:43:59 New packages to download: 6391 
13:43:59 Downloading packages: 
13:43:59 Downloading total 6391 files from 1 queues. 
13:43:59 1/6391 : accountsservice_0.6.45-1ubuntu1_amd64.deb 
13:43:59 2/6391 : acpi-support_0.142_amd64.deb
[cut]
Importing packages: |##################################################| 100.0% 
14:01:23 
14:01:23 Linking packages to the channel. 
14:01:29 1000 packages linked 
14:01:35 2000 packages linked 
14:01:42 3000 packages linked 
14:01:49 4000 packages linked 
14:01:57 5000 packages linked 
14:02:06 6000 packages linked 
14:02:11 6391 packages linked 
14:02:12 
14:02:12 Patches in repo: 0. 
14:02:12 Sync completed. 
14:02:12 Total time: 0:19:06

REF Suse Support Ticket 101248747251

**Comment by hunter86bg** [comment]
Thanks for the feedback.
As Uyuni has a newer version, I will give it a try and provide feedback if the issue  is still valid.

**Comment by hunter86bg** [comment]
In last version -> 4.0.2  Ubuntu repos sync properly.
I'm closing this issue - as  it's fixed.
