### ISSUE TITLE
Centos 7 Repo sync reports failed (Dev Release)

### ISSUE THREAD

**Issue by dragon2611** [uyuni-project/uyuni#1165]
Not really sure how to get more debug on this one,

I often see the channel sync for the Centos 7 channels report failed in the UI within seconds of starting the sync. 

However actually the sync is still running in the background and appears to complete successfully.

`Error	Channel sync failed	Error syncing the channel: Centos7	18/07/2019 11:38:04		
	Info	Channel sync finished	Channel Centos7 sync completed	18/07/2019 11:38:04`

**Comment by Shirocco88** [comment]
@dragon2611 :
does this issue still exist in uyuni-2021.06 ?

**Comment by dragon2611** [comment]
I'm afraid I don't know as I'm no longer responsible for that infrastructure nor do I still have access to it.

**Comment by Shirocco88** [comment]
@dragon2611 : could you please close this issue;
if another user having the same problem, this issue can be reopened.
