### ISSUE TITLE
spacewalk-java in Uyuni requires access to SUSE private Ivy repository

### ISSUE THREAD

**Issue by paususe** [uyuni-project/uyuni#1181]
See:

https://github.com/uyuni-project/uyuni/blob/master/java/buildconf/ivy/ivyconf.xml#L5
`
  <artifact pattern="http://ramrod.mgr.suse.de/ivy/master/[artifact]-[revision].[ext]" />`

**Comment by renner** [comment]
In the meantime we merged #1139, so I guess this one can be closed.
