### ISSUE TITLE
Documentation bug on website

### ISSUE THREAD

**Issue by simeon-harwood** [uyuni-project/uyuni#1182]
Hi,
Just had a look at the uyuni web site and there looks to be a documentation bug with a link to the repo. On the following page: -
https://www.uyuni-project.org/stable-version.html

I think: - 
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-4.0-POOL-x86_64-Media1/ uyuni-server-stable

should read: -
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Proxy-4.0-Media1/

**Comment by simeon-harwood** [comment]
Sorry, correction. This should read: -
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-4.0-Media1/

**Comment by juliogonzalez** [comment]
The site now reads:
```
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/ uyuni-server-stable
```
As we removed 4.0 from the URL.

I can confirm https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/ works, so this should be fine now :-)
