### ISSUE TITLE
cobbler sync to proxy fails

### ISSUE THREAD

**Issue by megamaced** [uyuni-project/uyuni#1200]
Hi,

I am running latest Uyuni from Master

Went through configure-tftpsync.sh wizard on proxy

Ran configure-tftpsync.sh PROXY on Uyuni server

Ran cobbler sync on Uyuni server and get lots of these errors:

```
uploading /srv/tftpboot/grub/x86_64-efi/xzio.mod to all known proxies. Timeout: 15
uploading /srv/tftpboot/grub/x86_64-efi/xzio.mod to proxy proxyserver.domain.co.uk as xzio.mod
uploading to proxy proxyserver.domain.co.uk failed: 'Request' object has no attribute 'get_data'
Push failed
```

**Comment by SchoolGuy** [comment]
@megamaced There should be a logfile of cobbler under `/var/log/cobbler/cobbler.log`. If you could provide the snippet from around the time where you tried your `cobbler sync`.

**Comment by megamaced** [comment]
@SchoolGuy 

```Tue Jul 30 10:08:20 2019 - DEBUG | REMOTE CLI Authorized; user(?)
Tue Jul 30 10:08:20 2019 - INFO | REMOTE start_task(Sync); event_id(2019-07-30_100820_sync); user(?)
Tue Jul 30 10:08:21 2019 - INFO | sync
Tue Jul 30 10:08:26 2019 - DEBUG | get_items; ['profile']
Tue Jul 30 10:08:26 2019 - DEBUG | done with get_items; ['profile']
Tue Jul 30 10:08:26 2019 - DEBUG | get_items; ['distro']
Tue Jul 30 10:08:26 2019 - DEBUG | done with get_items; ['distro']
Tue Jul 30 10:08:26 2019 - DEBUG | get_items; ['mgmtclass']
Tue Jul 30 10:08:26 2019 - DEBUG | done with get_items; ['mgmtclass']```

**Comment by SchoolGuy** [comment]
@megamaced Is this the complete log of cobbler sync? No Python-Stacktrace?

**Comment by megamaced** [comment]
I ran cobbler sync and that was the only thing that was logged in /var/log/cobbler/cobbler.log

**Comment by megamaced** [comment]
@SchoolGuy Is this a temporary workaround?

```UYUNIMASTER:~ rsync -av /srv/tftpboot PROXY:/srv/tftpboot```

**Comment by SchoolGuy** [comment]
@megamaced I am not sure but I suspect that you would need to change on the proxy the config files which are placed on the proxy after the `rsync`. Depending on the size of your setup this may be an impossible task (if it is small it may be possible although).

**Comment by juliogonzalez** [comment]
@SchoolGuy is there any code change we need?

FMPOV there's something wrong at the python code. Maybe @brejoc should have a look.

**Comment by SchoolGuy** [comment]
@juliogonzalez I didn't look at it because I have enough on my plate. Internally this is already in the Squad of Jochen.

**Comment by partingc** [comment]
Seeing the same issue, note that apache logs on the proxy don't even show an attempt to connect for me

**Comment by brejoc** [comment]
I did a `cobbler sync` to a proxy the other day and everything worked. Did you follow the setup instructions and execute the corresponding scripts on the master **and** the proxy?

**Comment by megamaced** [comment]
Cobbler sync still broken in 2020.01. Log attached

After the upgrade I reran configure-tftpsync.sh on server and proxy


[cobbler.log](https://github.com/uyuni-project/uyuni/files/4160214/cobbler.log)

**Comment by sundowner69** [comment]
Not sure but I think it is related to the MultipartPostHandler.py script from the susemanager-tftpsync package. Looks like the script is still python2 bound. It uses request.get_data() which is deprecated in python 3.6. If you call its __main__ part with python3 it throws an exception...
Can you please check and confirm?

**Comment by mcalmer** [comment]
We still find from time to time places which do not work with python3.

@meaksh what is your take on this? https://github.com/uyuni-project/uyuni/blob/master/tftpsync/susemanager-tftpsync/MultipartPostHandler.py
