### ISSUE TITLE
Windows Salt client support

### ISSUE THREAD

**Issue by ajcody** [uyuni-project/uyuni#1228]
References: https://docs.saltstack.com/en/latest/topics/installation/windows.html

Would like to see basic salt functionality and management within Uyuni/SUMA for Windows clients. 

#Support Ticket 101249308831
Looking for any information regarding Windows salt clients and integration with Uyuni/SUMA4.

Even if it's an unsupported client from Suse Support, I would like to know if the "theory" is that it should work and any things to note. For example, the salt binary would have to come from Salt directly and that Suse has no plans to package their own binary to provide better compatibility with Uyuni/SUMA4. Or maybe, recommendations on though one might use the salt win binary, here's what files to copy to the Windows client to provide tighter integration for SUMA. And so forth....

**Comment by ajcody** [comment]
You can bind a windows 2000 salt client to the Uyuni salt-master. Just can't figure out a way to get the windows client showing up in the Uyuni web UI under systems. It is listed in the Salt > Keys. Not sure if it's just a matter of tweaking the windows minion configuration files.

Client Install
Reference Documentation: https://docs.saltstack.com/en/latest/topics/installation/windows.html 

Client Install Example (Output)
Installed on my 64bit laptop: Python3 AMD64: Salt-Minion-2019.2.0-AMD64-Setup.exe


salt-master:/srv # salt-key -L
Accepted Keys:
centos-01.localhost.local
suse-01.localhost.local
ubuntu-01.localhost.local
yoga900.localhost.local
Denied Keys:
Unaccepted Keys:
Rejected Keys:

salt-master:/srv # salt '*' test.ping
suse-01.localhost.local:
    True
centos-01.localhost.local:
    True
ubuntu-01.localhost.local:
    True
yoga900.localhost.local:
    True

salt-master:/srv # salt yoga900.localhost.local grains.items
yoga900.localhost.local:
    ----------
    SSDs:
        - \\.\PhysicalDrive0
[cut]

Windows Package Management
Reference Documentation: https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html 

Example Setup of Salt Server for Windows Management
Setting up the salt-master to management windows packages.

salt-master:/srv # zypper install git
[cut]

salt-master:/srv # mkdir /srv/salt/win

salt-master:/srv # chown -R salt:salt /srv/salt/win

salt-master:/srv # salt-run winrepo.update_git_repos

https://github.com/saltstack/salt-winrepo-ng.git:
    /srv/salt/win/repo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo

Inventory on my personal laptop

salt-master:/srv # salt -G 'os:windows' pkg.refresh_db
yoga900.localhost.local:
    ----------
    failed:
        0
    success:
        285
    total:
        285

salt-master:/srv # salt -G 'os:windows' pkg.list_pkgs
yoga900.localhost.local:
    ----------
    7-Zip 18.00 beta (x64):
        18.00 beta
[cut]

salt-master:/srv # salt yoga900.localhost.local pkg.list_available firefox
yoga900.localhost.local:
    - 29.0.1
    - 30.0
[cut]

The software definition files for older minions (salt-winrepo) and new minions (salt-winrepo-ng).

salt-master:/srv/salt/win # ls
repo  repo-ng

salt-master:/srv/salt/win # ls -1 repo/salt-winrepo/ | wc -l
328

salt-master:/srv/salt/win # ls -1 repo-ng/salt-winrepo-ng/ | wc -l
293
salt-master:/srv/salt/win # salt-run winrepo.update_git_repos
[WARNING ] /usr/lib/python3.6/site-packages/salt/grains/core.py:2827: DeprecationWarning: This server_id is computed nor by Adler32 neither by CRC32. Please use "server_id_use_crc" option and define algorithm youprefer (default "Adler32"). The server_id will be computed withAdler32 by default.

https://github.com/saltstack/salt-winrepo-ng.git:
    /srv/salt/win/repo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo

Installing chocalety  via salt on my windows 2000 laptop.

salt-master:/srv/salt/win # salt yoga900.localhost.local pkg.install 'chocolatey'
yoga900.localhost.local:
    ----------
    chocolatey:
        ----------
        new:
            0.10.11
        old:
Please see the documentation on salt and chocalety  . There's other ways to install/deploy chocalety other than what I did in the above example.

Here's a query via the chocolatey binary that I installed on my windows laptop via the chocolatey salt module.

salt-master:/srv/salt/win # salt yoga900.localhost.local chocolatey.list_windowsfeatures
yoga900.localhost.local:
    Chocolatey v0.10.11
    Deployment Image Servicing and Management tool
    Version: 10.0.18362.1
    Image Version: 10.0.18362.267
    Features listing for package : Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.18362.1
    ------------------------------------------- | --------
    Feature Name                                | State
    ------------------------------------------- | --------
    Printing-PrintToPDFServices-Features        | Enabled
[cut]

**Comment by ajcody** [comment]
Another Suse Support Ticket created also on this: SR 101250308681

**Comment by paususe** [comment]
I'll be working on this in my Hackweek next month:
https://hackweek.suse.com/20/projects/uyuni-slash-suse-manager-windows-client-support

**Comment by sbluhm** [comment]
Duplicate: #1937

**Comment by mcalmer** [comment]
I will close  this as we have a duplicate. The references will help to find also this issue when we should work on the other.
