### ISSUE TITLE
Duplicate package in Ubuntu

### ISSUE THREAD

**Issue by vampywiz17** [uyuni-project/uyuni#1240]
Hello there,

I try to update a ubuntu system, but some packages can not able to do it, because it say that a missing dependency. this packages is same version tha installed it, but different name.

Like this:

Latest Package                              |                         Installed Package
gcc-8-base-8-20180414-1ubuntu2.amd64-deb | gcc-8-base-8.3.0-6ubuntu1~18.04.1.amd64-deb

How to solve/fix this problem?

**Comment by vampywiz17** [comment]
This is my problem : 

https://www.redhat.com/archives/spacewalk-list/2018-December/msg00002.html

**Comment by paususe** [comment]
It's partially fixed (namely, the current fix should cove the packages you reported) now in master with https://github.com/uyuni-project/uyuni/commit/02da29ed1fd8e185a6ab8f10c6d555a96a7bf72f

A full fix should land soon in master.

**Comment by juliogonzalez** [comment]
@paususe wasn't this fixed already? Can we close?
