### ISSUE TITLE
Filter with package version

### ISSUE THREAD

**Issue by vampywiz17** [uyuni-project/uyuni#1246]
Some big repositorys that store all versions of a specific program is a quite big and unneccesary to download all of them.

good example: https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/dists/bionic/main/binary-amd64/

It a lot of version of gitlab, but optimally it only need the latest one.

it possible somehow filter with the latest version?

I try to set "--latest" flag on sync menu and "spacewalk-repo-sync" command, but it not help at all, it try to download full repo.

The filter option work only with package name, not version.

**Comment by mcalmer** [comment]
The last time I tried, --latest was working. Even in the UI you have a checkbox for it.

@meaksh Do you remember if we tested this option after the re-write of the downloader part?

**Comment by meaksh** [comment]
The reason for this is clarified here:

https://github.com/uyuni-project/uyuni/blob/master/backend/satellite_tools/repo_plugins/deb_src.py#L254

The `--latest` filtering is delegated to the particular "reposync" plugin, and currently only `yum_src` plugin has it implemented. So it's not yet supported for Debian repositories.
