### ISSUE TITLE
mgr-create-bootstrap-repo cannot create repo for Ubuntu 18

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni#1249]
It seems that the channels created by spacewalk-common-channels for Ubuntu18 are as follows:
```
uyuni:~ # spacecmd -u admin softwarechannel_listbasechannels | grep ubuntu
INFO: Connected to https://uyuni.localdomain.com/rpc/api as admin
ubuntu-18.04-pool-amd64
ubuntu-18.04-pool-amd64-uyuni
```
While the mgr-create-bootstrap-repo is looking for:
```uyuni:/usr/share/susemanager # grep -A 4 ubuntu-18 mgr_bootstrap_data.py
    'ubuntu-18.04-amd64' : {
        'PDID' : [-1, 1918], 'PKGLIST' : PKGLISTUBUNTU1804,
        'DEST' : '/srv/www/htdocs/pub/repositories/ubuntu/18/4/bootstrap/',
        'TYPE' : 'deb'
    }
```
Shouldn't we have 2 entries in '/usr/share/susemanager/mgr_bootstrap_data.py' - one for LTSS and one for uyuni channel ?

**Comment by mcalmer** [comment]
I remember to add this channel was a last minute change. So maybe we forgot to adapt create bootstrap repo data.

**Comment by hunter86bg** [comment]
I know... It was in the release notes.
On the positive side, the channels  for Ubuntu sync properly and I can close the other issue.
