### ISSUE TITLE
Proxy install docs improvements.

### ISSUE THREAD

**Issue by dragon2611** [uyuni-project/uyuni#1263]
The Proxy install docs could ideally use some work,

The Documentation here seems to miss the step where you pull the uyuni-proxy pattern

I did 

`zypper in -t pattern uyuni_proxy` 

After configuring the channels (For LEAP 15.1 rather than SLES as suggested in the documentation) and only then did I have the confgure-proxy.sh script.

https://www.uyuni-project.org/uyuni-docs/uyuni/installation/proxy-registration.html
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/proxy-setup.html

Also 

https://www.uyuni-project.org/doc/4.0.2/release-notes-uyuni-proxy.html#_installing_the_proxy Contradicts the Docs linked earlier and I can't seem to locate any section in the web-ui to automate installing the proxy, nor is there an advanced topics manual for 4.02 (at least not that I can find)

**Comment by juliogonzalez** [comment]
Ping @keichwa, is this still relevant after the rewrite you did?

**Comment by keichwa** [comment]
On 2020-03-25 16:47, Julio González Gil wrote:
> Ping @keichwa, is this still relevant after the rewrite you did?

I think I covered all the rightly mentioned issues.  I'd say we
can close it.

-- 
Karl Eichwalder
