### ISSUE TITLE
Ubuntu 16.04 moans about i386

### ISSUE THREAD

**Issue by dragon2611** [uyuni-project/uyuni#1266]
Seems once bootstrapped Ubuntu 16.04 (X86_64) complains about lack of i386 arch in the repo's for some reason.

```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-main InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-uyuni-client-2 InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-main-universe InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-main-updates InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-16.04-pool-amd64 InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-main-security InRelease' doesn't support architecture 'i386'

```

**Comment by juliogonzalez** [comment]
@mbologna any news about this?

**Comment by mbologna** [comment]
> Seems once bootstrapped Ubuntu 16.04 (X86_64) complains about lack of i386 arch in the repo's for some reason.
> 
> ```
> N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-main InRelease' doesn't support architecture 'i386'
> N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-uyuni-client-2 InRelease' doesn't support architecture 'i386'
> N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-main-universe InRelease' doesn't support architecture 'i386'
> N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-main-updates InRelease' doesn't support architecture 'i386'
> N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-16.04-pool-amd64 InRelease' doesn't support architecture 'i386'
> N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni.mydomain:443/rhn/manager/download ubuntu-1604-amd64-main-security InRelease' doesn't support architecture 'i386'
> ```

Can you please provide more details?
What is the content of /etc/apt/sources.list/* ?

**Comment by Shirocco88** [comment]
see also #1962 

> The "N: Skipping acquire of configured file .... doesn't support architecture 'i386'" message can be easily mitigated by adding the "**arch=amd64**" tag for each of the channels configured inside the susemanager:channels.list apt configuration file


`deb [arch=amd64 trusted=yes] https://blabla@uyuni:443/rhn/manager/download ubuntu-18.04-pool-amd64-uyuni main`

channel.repo has to be addapted (add grain osarch):
https://github.com/uyuni-project/uyuni/blob/master/susemanager-utils/susemanager-sls/salt/channels/channels.repo
```
SNIP
% set os_arch={{ grains.get('osarch') }} %
SNIP
{%- if grains['os_family'] == 'Debian' %}
deb {{ '[trusted=yes arch={{ os_arch }}]' if not pillar.get('mgr_metadata_signing_enabled', false) else '[signed-by=/usr/share/keyrings/mgr-archive-keyring.gpg]' }} https://{{ args['token'] }}@{{ args['host'] }}:{{ args.get('port', 443)}}/rhn/manager/download {{ chan }} main
{%- else %}
SNIP
```

this as first idee (untested) to solve the problem.

**Comment by Shirocco88** [comment]
@Developers:
OS-Grains of systems with problems
````
Ubuntu-16.04:
    os:
        Ubuntu
    os_family:
        Debian
    osarch:
        amd64
    oscodename:
        xenial
    osfinger:
        Ubuntu-16.04
    osfullname:
        Ubuntu
    osmajorrelease:
        16
    osrelease:
        16.04
    osrelease_info:
        - 16
        - 4
````

**Comment by Shirocco88** [comment]
I've done further analysis;

This issue exist only on ubuntu systems with "foreign architectures"
# dpkg --print-foreign-architectures
i386

on ubuntu systems without "foreign-architectures" there is no problem;
# dpkg --print-foreign-architectures

**Comment by Shirocco88** [comment]
@dragon2611 : Ubuntu-16.04 is now EOL
and uyuni-2021.06 doesn't support Ubuntu-16.04, too

Can we close this issue ?

**Comment by dragon2611** [comment]
Go ahead.
