### ISSUE TITLE
 Package List Refresh - error (Ubuntu 18.04)

### ISSUE THREAD

**Issue by vampywiz17** [uyuni-project/uyuni#1285]
Hello there,

I try to use Ubuntu with Salt (not salt-ssh) A successful register the client, but i get "unexpected error" if i try to query package info.
I check client salt log, and i found this:

```
2019-08-14 11:55:45,544 [salt.state       :322 ][ERROR   ][7637] Module function pkg.info_installed threw an exception. Exception: The following keyword arguments are not valid: errors=
report, attr=arch,epoch,version,release,install_date_time_t
```
it possible that this one is the problem? (it only just a idea)

https://github.com/saltstack/salt/issues/50550

**Comment by vampywiz17** [comment]
OK, it working with Uyuni specific salt...:)

[https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/](url)

sorry the fail issue report.

**Comment by ZsBT** [comment]
> OK, it working with Uyuni specific salt...:)
> 
> [https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/](url)
> 
what do you mean by "Uyuni specific salt"?
I've got this problem with latest Uyuni and latest salt minion. According to current docs, the official salt is neccessary.
