### ISSUE TITLE
openSUSE Leap 15.1 Client Tools repository missing?

### ISSUE THREAD

**Issue by paususe** [uyuni-project/uyuni#1300]
There is no openSUSE Leap 15.1 Client Tools repository, only openSUSE Leap 15.0 Client Tools:
https://build.opensuse.org/project/show/systemsmanagement:Uyuni:Stable:openSUSE_Leap_15-Uyuni-Client-Tools

A link in the docs is also needed:
https://www.uyuni-project.org/pages/stable-version.html#proxysetup

**Comment by juliogonzalez** [comment]
We only have openSUSE Leap 15.0 for all 15.X versions, in the same way we only have SLE12 for all SLE12SPX versions as well.

Assigning to me, as we need to change the website (Client Tools section for both stable and devel).

I will review the doc itself, to see if we need something there.

**Comment by juliogonzalez** [comment]
spacewalk-common-channels already takes care of pointing two channels/repos to the same URL:

https://github.com/uyuni-project/uyuni/blob/master/utils/spacewalk-common-channels.ini#L828
https://github.com/uyuni-project/uyuni/blob/master/utils/spacewalk-common-channels.ini#L883

https://www.uyuni-project.org/pages/stable-version.html was also updated.

The doc also uses the correct channel.
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-proxy-registration.html

But @keichwa, why do we have also this? https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-proxy-uyuni.html A cleanup is missing, maybe? Assigning this issue to you, so you can review.

**Comment by keichwa** [comment]
@juliogonzalez I reviewed and I think it's fine.  Why do you think we do not need the Proxy Uyuni Installation section?

**Comment by juliogonzalez** [comment]
@keichwa I just got confused by the reference to `zypper in -t pattern uyuni_proxy` on the setup part.

Closing this issue, as nothing else is pending.

**Comment by keichwa** [comment]
On 2020-03-30 09:24, Julio González Gil wrote:
> @keichwa I just got confused by the reference to `zypper in -t pattern
> uyuni_proxy` on the setup part.
> 
> Closing this issue, as nothing else is pending.

Ok, thanks for checking, Julio!

-- 
Karl Eichwalder
