### ISSUE TITLE
spacewalk-proxy package is never built. Or is it?

### ISSUE THREAD

**Issue by paususe** [uyuni-project/uyuni#1303]
In spacewalk-proxy.spec, the description of the spacewalk-proxy package says:

_%description
This package is never built._

But it actually is built:
https://software.opensuse.org/package/spacewalk-proxy

What's wrong? Description? Packaging?

**Comment by mcalmer** [comment]
It is building, but `spacewalk-proxy` is only the name of the source package. All binary packages built from these sources have different names:
- spacewalk-proxy-management
- spacewalk-proxy-broker
- spacewalk-proxy-redirect
- spacewalk-proxy-common
- spacewalk-proxy-package-manager
- spacewalk-proxy-salt

They are all on the proxy media.

`%description` is for the source package and this never generate a binary package where a discription would be needed. So everything is ok.

**Comment by juliogonzalez** [comment]
Can we close this?
