### ISSUE TITLE
Failed "Hardware list refresh" event when bootstrapping Salt SSH minion

### ISSUE THREAD

**Issue by Bischoff** [uyuni-project/uyuni#1352]
Using an openSUSE 15.0 SSH Minion, the "Hardware list refresh" event is marked as "Failed" at the end of the bootstrap.

The problem goes away when I preinstall `dmidecode` package on the future Salt SSH minion before bootstrapping.

Most probably the hardware list refresh assumes that `dmidecode` is installed, but this package is not installed as part of the bootstrap sequence.

I don't see the problem on 4.0.

**Comment by srbarrios** [comment]
WOW! Thanks for that information, as I think we got the same issue in our internal QAM environment for other ssh minions.

**Comment by Bischoff** [comment]
As usually with issues with no team, it tends to get lost. Adding it to planning.

**Comment by Bischoff** [comment]
As this one year old uyuni issue seems to have got lost, I opened a bug instead: 

https://bugzilla.suse.com/show_bug.cgi?id=1178328
