### ISSUE TITLE
Debrand mgr-setup file

### ISSUE THREAD

**Issue by parlt91** [uyuni-project/uyuni#1354]
The `mgr-setup` file in `susemanager/bin` still contains some hard coded `SUSE Manager`.

For example: The script sets the default value of `default_mail_from` in `/etc/rhn/rhn.conf` which causes mails generated from uyuni to be sent from`SUSE Manager` name.
This name should rather be dependent on `product_name` set in `/usr/share/rhn/config-defaults/rhn.conf`
See #250 which contains an example.

**Comment by paususe** [comment]
MOTD also says "Welcome to SUSE Manager", another thing to fix

**Comment by wombelix** [comment]
I'm looking for a first issue to contribute and this one seem to be a good candidate.
Prior starting any activities, I just want to double check that I understood the requirements correctly.

So the idea is to look for `product_name` in `/usr/share/rhn/config-defaults/rhn.conf`, logic:
- If exist use given value (expected default: SUSE Manager)
- Else fallback to `SUSE Manager`

Then to replace all hard coded occurences of `SUSE Manager` (limited to actual visible output) in `susemanager/bin/mgr-setup` with the value of `product_name`?

> MOTD also says "Welcome to SUSE Manager", another thing to fix

@paususe do you refer to [this section in mgr-setup](https://github.com/uyuni-project/uyuni/blob/ccd15dfe775e0afda59edc771f9612092e04ece8/susemanager/bin/mgr-setup#L826)?

**Comment by wombelix** [comment]
Even though it didn't received a Feedback yet, I started working on it and created a PR to resolve this issue.
