### ISSUE TITLE
Incomplete doc for server setup

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#1559]
We have that information at https://www.uyuni-project.org/pages/stable-version.html and https://www.uyuni-project.org/pages/devel-version.html, but nowhere at https://www.uyuni-project.org/uyuni-docs/uyuni/installation/server-setup.html as far as I can tell.

Also it has two steps 1:

> 1 Log in to the Uyuni server and type yast2 susemanager_setup to begin the setup.
> 1 From the introduction screen select "SUSE Manager Setup" >  "Setup SUSE Manager from scratch and click Next to continue."

The second one should be step 2, and it's "Uyuni" and not "SUSE Manager".

> Synchronizing Products from SUSE Customer Center

This part is optional in Uyuni.

**Comment by keichwa** [comment]
I'd happily spend time on this.  As said previously, I'd create a dedicated Installation Guide for Uyuni (and thus also for SUMA).  Ifdef'ing or profiling within the files will not produce good results in this case.

**Comment by juliogonzalez** [comment]
Well, either we do that before next Uyuni release, either we add `if`s :-\

**Comment by keichwa** [comment]
sure :)  I think ifs within lists or procedures are not possible.  At least, not easily possible.  Sparkling '+' signs might make it work, but this usually is pure luck.  This the next tool chain update the world might look different.

**Comment by Loquacity** [comment]
> sure :) I think ifs within lists or procedures are not possible. At least, not easily possible. Sparkling '+' signs might make it work, but this usually is pure luck. This the next tool chain update the world might look different.

I think you would need to duplicate the procedure, and then if them separately. Even if you you can make it work with `+` it's gonna look nasty :confounded:

**Comment by keichwa** [comment]
cherry-picked from manager-4.0 for the next 4.0 MU.
