### ISSUE TITLE
Kickstart password - no escape for "$" character which causes errors to be reported

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni#1685]
Issue:
cobbler complains that it can't find a variable like '$E2Pn84eRO/d3ukUB' which is a part of the root user's password generated via:
Systems -> Autoinstallation -> Profiles -> System details -> Details -> New Root Password:/Verify New Root Password:
When visiting 'Autoinstallation Details' -> 'Advanced Options' the password in 'rootpw:' field contains multiple '$' characters (that's OK) , which should be escaped so cobbler/cheetah won't treat them as variables.

Escaping the '$' characters is OK, but an error message is printed out:
'This kickstart profile uses a different type of encryption by default than the root password is currently using. You must reset the root password to encrypt it with the new method.'

**Comment by mcalmer** [comment]
This bug is more than 2 years old. Please open a new issue if this can be reproduced with a current Uyuni version.
