### ISSUE TITLE
cobbler traceback when generating/viewing system's kickstart

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni#1686]
Issue is properly described and fixed at:
https://github.com/cobbler/cobbler/pull/2176

It affects latest stable Uyuni.

**Comment by sbluhm** [comment]
@hunter86bg , is this still relevant?

**Comment by hunter86bg** [comment]
Currently I can't test it. Let's close this one and reopen if it still affects Uyuni
