### ISSUE TITLE
Setup complete: wrong doc title

### ISSUE THREAD

**Issue by keichwa** [uyuni-project/uyuni#1763]
"Uyuni Install and Troubleshooting" does not exist.  I'd just say:

> For more information, see the "Uyuni Installation Guide" or click https://www.uyuni-project.org/.

![u](https://user-images.githubusercontent.com/1759421/71715182-d2d8cf00-2e10-11ea-914b-fa36386d2c5f.png)

**Comment by juliogonzalez** [comment]
@keichwa I'd say this is the same situation for SUSE Manager, right?

We don't have an "Installation and Troubleshooting guide" anymore.

If you confirm, I think I can quickly fix this one.

**Comment by keichwa** [comment]
I'm confirming, thanks!

**Comment by juliogonzalez** [comment]
@keichwa it seems this was fixed by @mantel at https://github.com/uyuni-project/uyuni/blame/master/susemanager/yast/susemanager_congratulate.rb#L37 as part of bsc#1154590, so closing :-)

**Comment by keichwa** [comment]
On 2020-03-24 17:44, Julio González Gil wrote:
> @keichwa it seems this was fixed by @mantel at
> https://github.com/uyuni-project/uyuni/blame/master/susemanager/yast/susemanager_congratulate.rb#L37
> as part of bsc#1154590, so closing :-)

Thank you, both of you!

-- 
Karl Eichwalder
