### ISSUE TITLE
permission issues

### ISSUE THREAD

**Issue by keichwa** [uyuni-project/uyuni#1764]
I installed from /Stable/images/repo/Uyuni-Server-4.0-POOL-x86_64-Media1 (default install as described in the Uyuni Install Guide).

1/
During setup, I see:
```
/var/lib/pgsql/.bash_profile: line 1: /usr/share/postgresql/bash_profile
: Permission denied                                                     │  
```
You probably wanted to copy the contents of `/usr/share/postgresql/bash_profile` to `/var/lib/pgsql/.bash_profile`, but just this file name ended up in `/var/lib/pgsql/.bash_profile`.

2/
New config files in `/var/lib/pgsql/data/` are owned by `root.root` instead of `postgres:postgres`:
```
-rw------- 1 postgres postgres  4354 Jan  3 09:43 pg_hba.2020-01-03-09-54-30.conf
-rw-r--r-- 1 root     root       296 Jan  3 09:54 pg_hba.conf
-rw------- 1 postgres postgres  4269 Jan  3 09:43 pg_hba.conf.bak
...
-rw------- 1 postgres postgres 22928 Jan  3 09:43 postgresql.2020-01-03-09-54-30.conf
-rw------- 1 postgres postgres    88 Jan  3 09:43 postgresql.auto.conf
-rw-r--r-- 1 root     root       801 Jan  3 09:54 postgresql.conf
```

**Comment by juliogonzalez** [comment]
@mantel this was a SLE/openSUSE issue at PostgreSQL package, right?

Can we close this?

**Comment by mantel** [comment]
Yes, we can close this one. The fixed for postgresql has already been released.
