### ISSUE TITLE
cobbler login failed

### ISSUE THREAD

**Issue by scheurer13** [uyuni-project/uyuni#1896]
Can´t do an autoinstall "create distribution" or sync cobbler with web gui

Uyuni release 2020.01 - OpenSUSE Leap 15.1

error tomcat log:
`10-Feb-2020 10:24:01.271 SEVERE [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5126] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [action] in context with path [/rhn] threw exception [java.lang.RuntimeException: com.redhat.rhn.manager.kickstart.cobbler.NoCobblerTokenException: We had an error trying to login.] with root cause
        redstone.xmlrpc.XmlRpcFault: <class 'cobbler.cexceptions.CX'>:'login failed (admin)'
`

error cobbler sync:
`Cobbler command failed: We had an error trying to login.`

cobbler sync with root no problem.

**Comment by paususe** [comment]
@mateiw 
Do you think this may have any relation with https://github.com/uyuni-project/uyuni/pull/1992 ?

**Comment by Bischoff** [comment]
Task to test this manually on beta 2: 
Already existing task to automate this test: #8844

**Comment by hustodemon** [comment]
@paususe It might be. We have a user who hit a similar issue, so let's see if the ajp configuration resolves the problem.

**Comment by mateiw** [comment]
@paususe `cobbler sync` generates the configuration for TFTP, DHCTP, etc. As far as I know it doesn't do any XML-RPC calls to Tomcat.
The Tomcat error seems to happen because there's something wrong with cobbler (`'login failed (admin)' `. 
So I don't think it's related to #1992.

**Comment by scheurer13** [comment]
This problems appear with an imported certificate. After recreate this with default no more problems. Thanks for help
