### ISSUE TITLE
[GSoC] Amazon Linux 2 support

### ISSUE THREAD

**Issue by paususe** [uyuni-project/uyuni#1936]
(This is a copy of https://github.com/openSUSE/mentoring/issues/132 to reach a wider audience. Uyuni has applied for Google Summer of Code as under the openSUSE umbrella: https://101.opensuse.org)
**Project Title:** Amazon Linux 2 support

**Description:** Uyuni supports many Linux clients (openSUSE, CentOS, SUSE Linux Enterprise, Red Hat Enterprise Linux, etc). Let's add one more: Amazon Linux 2. It is very similar to RHEL but with a twist: metadata is in sqlite format. Supporting it as a Salt client is enough, no need to implement the traditional stack.

**Deliverable:** Very similar to what supporting any other client means:
* Build openSUSE's Salt packages for Amazon Linux 2. It may very well be the case that the RHEL packages just work but at least testing is needed. - https://build.opensuse.org/package/show/systemsmanagement:saltstack:products:testing/salt
* Onboard (register) Amazon Linux clients as Salt minions
* Create bootstrap repository
* Add reposync support for sqlite format. Alternatives: a) download the sqlite files and convert them to XML (which is currently works) or b) add native support for sqlite.
* Generate and process patches and security information (CVE information from the Amazon Linux Security Advisories - https://alas.aws.amazon.com/ )

**Mentor:** @juliogonzalez

**Skills:** You will need to have a good understanding of Linux, and be comfortable with version control using git and GitHub. Some Sqlite, PostgreSQL, JSON, Python and Java (you will be mostly looking at existing code and adding new sub-cases to it). Familiarity with AWS, Amazon Linux and package management.

**Skill Level:** Medium

**Get started:**
* Getting started hacking Uyuni: http://bosdonnat.fr/slides/openSUSEAsiaSummit19/#/about
* Get a free tier account in AWS
* Read about Amazon Linux 2 and create a VM to play with it: https://aws.amazon.com/amazon-linux-2/ (you can also download and run it locally)
* Download an Uyuni Server VM and setup the Server - https://build.opensuse.org/package/binaries/home:pagarcia:Uyuni/Uyuni-2020.01-Server/Uyuni
* Hackweek project on adding support for more Linux distributions: https://hackweek.suse.com/19/projects/testing-gnu-slash-linux-distributions-on-uyuni
* Get familiar with the Uyuni source code and implement creation of the bootstrap repository. You can take a look at these commits as a reference:
https://github.com/uyuni-project/uyuni/commit/e5d4d29f3148af40882a1c726b56556f08ed41c2
https://github.com/uyuni-project/uyuni/commit/6da14873065befad4caff4e98a5f5481212fbb36
* Uyuni Wiki:
  * Introduction to Uyuni and systems management (presentation): https://github.com/uyuni-project/uyuni/wiki/Presentations
  * Development pages: https://github.com/uyuni-project/uyuni/wiki/

**Comment by juliogonzalez** [comment]
@paususe should we close this, maybe?

**Comment by Shirocco88** [comment]
@paususe : Can we close this issue ?
Uyuni-2021.05 supports Amazon Linux 2;
