### ISSUE TITLE
webpage typos

### ISSUE THREAD

**Issue by vmoutoussamy** [uyuni-project/uyuni#2044]
at the bottom right of https://www.uyuni-project.org/pages/contact.html, https://www.uyuni-project.org/pages/news.html and https://www.uyuni-project.org/pages/faq.html:
"Links of interes"

And at the bottom right of https://www.uyuni-project.org/, it's "Related links". 
So please use just one name, IMHO I would prefer to see "Related links" everywhere

**Comment by juliogonzalez** [comment]
@vmoutoussamy the correct place for the website issue is at https://github.com/uyuni-project/uyuni-project.github.io (you can create PRs as well).

Anyway, is something quick to fix, so I will go for it now.
