### ISSUE TITLE
Ubuntu repo sync shows as failed when no new packages are avaliable

### ISSUE THREAD

**Issue by EthanB11** [uyuni-project/uyuni#2087]
I am getting the following messages in the web interface for failing to sync a repo when it actually has no new updates.

Error | Channel sync failed | Error syncing the channel: Uyuni Client Tools for Ubuntu 18.04 AMD64 | 2020-04-01 02:40:03 CDT
-- | -- | -- | --

Looking at the logs there are just no new packages.

>2020/04/01 02:40:00 -05:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'ubuntu->1804-amd64-uyuni-client', '--type', 'deb', '--non-interactive']
>2020/04/01 02:40:00 -05:00 Sync of channel started.
>2020/04/01 02:40:02 -05:00 Repo URL: >https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804->Uyuni-Client-Tools/xUbuntu_18.04/
>2020/04/01 02:40:02 -05:00     Packages in repo:                20
>2020/04/01 02:40:02 -05:00     No new packages to sync.
>2020/04/01 02:40:02 -05:00 
>2020/04/01 02:40:02 -05:00   Patches in repo: 0.

This happens for all Ubuntu 1804 channels, Fedora 29 & 30 channels. These were all added using spacewalk-common-channels.

**Comment by EthanB11** [comment]
I am also getting a sync completed message.


Error | Channel sync failed | Error syncing the channel: Ubuntu 18.04 LTS AMD64 Base for Uyuni | 2020-04-01 07:01:14 CDT |   |  
-- | -- | -- | -- | -- | --
Info | Channel sync finished | Channel Ubuntu 18.04 LTS AMD64 Base for Uyuni sync completed | 2020-04-01 07:01:14 CDT

**Comment by paususe** [comment]
@mcalmer 
Do you know what's wrong here?

**Comment by csabaz** [comment]
Hi, I have the same problem.

```
Error	Channel sync failed	Error syncing the channel: Ubuntu 18.04 LTS AMD64 Main for Uyuni	2020-04-02 01:30:17 CEST		
Info	Channel sync finished	Channel Ubuntu 18.04 LTS AMD64 Main for Uyuni sync completed		2020-04-02 01:30:17 CEST
```	
	

 When I run it in terminal I receive the following error:

```
/usr/bin/spacewalk-repo-sync --channel ubuntu-1804-amd64-main-uyuni --type deb --non-interactive

12:36:31 ======================================
12:36:31 | Channel: ubuntu-1804-amd64-main-uyuni
12:36:31 ======================================
12:36:31 Sync of channel started.
12:36:32 Repo URL: http://archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64/
12:36:32     Packages in repo:              6391
12:36:44     No new packages to sync.
12:36:44 
12:36:44   Patches in repo: 0.
Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 269, in main
    elapsed_time, channel_ret_code = sync.sync()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 667, in sync
    if CFG.AUTO_GENERATE_BOOTSTRAP_REPO:
  File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnConfig.py", line 237, in __getattr__
    raise AttributeError(key)
AttributeError: AUTO_GENERATE_BOOTSTRAP_REPO

```
OS: openSUSE Leap 15.1
Uyuni release: 2020.03

**Comment by mcalmer** [comment]
The value is specified in /usr/share/rhn/config-defaults/rhn_server_susemanager.conf

Please call: `rpm -qf /usr/share/rhn/config-defaults/rhn_server_susemanager.conf`

**Comment by EthanB11** [comment]
foohost:~ # rpm -qf /usr/share/rhn/config-defaults/rhn_server_susemanager.conf
susemanager-tools-4.1.7-1.1.uyuni.x86_64

**Comment by mcalmer** [comment]
The last line of that file should be:
```
# automatically generate all bootstrap repos of synced products
auto_generate_bootstrap_repo = 1
```
This comes from that package.

**Comment by EthanB11** [comment]
foohost:~ # tail /usr/share/rhn/config-defaults/rhn_server_susemanager.conf
token_refresh_auto_deploy = true

# when re-generating bootstrap repos remove old content first
bootstrap_repo_flush = 1

# data module used for mgr-create-bootstrap-repo
bootstrap_repo_datamodule = mgr_bootstrap_data

# automatically generate all bootstrap repos of synced products
auto_generate_bootstrap_repo = 1

**Comment by mcalmer** [comment]
Magic. The value is there as you can see.

**Comment by mcalmer** [comment]
Seems we can reproduce it here as well. I will keep you updated when I find out the reason.
