### ISSUE TITLE
issue with re-registering server which was deleted without proper de-registration 

### ISSUE THREAD

**Issue by svgaikwad** [uyuni-project/uyuni#2113]
Hi Team,
              This set up in on aws we had to recreate servers for some reason.
              And server were deleted without proper de-registration.
              Now when we are trying to add the servers back from web ui bootstrapping it show has successfully added server but we don't see the server in list.
              Note : system id is changed.

Please help us out in fixing this issue

Thanks
Sachin v Gaikwad

**Comment by admd** [comment]
Hi @svgaikwad,

We will need more information than this. For the future, please always provide the logs alongside the problem description so we can help.

Thank you

**Comment by mcalmer** [comment]
For a proper re-registration you need to generate a re-registration key and configure it on the client. With salt configure a grain 

```
susemanager:
    management_key: re-1-.....
```

Maybe this feature was not available in Apr. but it is now with the latest Uyuni version.

**Comment by sbluhm** [comment]
@svgaikwad , is this issue still relevant?
