### ISSUE TITLE
Build and publish openSUSE Leap aarch64 packages for server

### ISSUE THREAD

**Issue by ggardet** [uyuni-project/uyuni#2130]
So far, only `x86_64` is supported for the server. Could we enable `aarch64`?
I can help to test on openSUSE `aarch64` systems, if needed.

**Comment by juliogonzalez** [comment]
Started working on this, will take me some time as we need to build everything, adapt product definitions etc.

Will ping as soon as there's something ready to be tested.

**Comment by juliogonzalez** [comment]
@ggardet I was able to generate Server and Proxy pool repositories, just the same we do for x86_64.

https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master/images/repo/Uyuni-Server-POOL-aarch64-Media1/
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master/images/repo/Uyuni-Proxy-POOL-aarch64-Media1/

Can you maybe give them a try?

Two important notes:
1. It could be that when you install you have some problems if the repositories are being republished.
2. There could be some missing dependencies on aarch64 that are required and we'd need to package and that could fail the setup, let us know if that's the case (I still didn't add the tests for the media installation).

**Comment by juliogonzalez** [comment]
Note for myself: despite the product images for aarch64, they are doing it at the x86_64 OBS repository, which should work but it's not really correct, I already pinged OBS people about it, as I think there's some magic they need to do to fix this.

**Comment by juliogonzalez** [comment]
Ping @ggardet ?

**Comment by ggardet** [comment]
I am unable to boot on `Uyuni-Server-DVD-aarch64-Build95.57-Media1.iso` or `Uyuni-Proxy-DVD-aarch64-Build95.1-Media1.iso`
You should probably build those images on `aarch64`.
**So, please enable build for `aarch64` in `images`.**

Moreover, https://build.opensuse.org/package/view_file/home:Guillaume_G:branches:systemsmanagement:Uyuni:Master/000product/_service:product_converter:Uyuni-Server-dvd5-DVD-aarch64.kiwi?expand=1 looks wrong:
```
    <architectures>
      <arch id="aarch64" name="dummy" fallback="noarch"/>
      <arch id="noarch" name="dummy" fallback="x86_64"/>
      <arch id="x86_64" name="dummy"/>
      <requiredarch ref="aarch64"/>
    </architectures>
```

Instead, it should be similar to Proxy ISO:
```
    <architectures>
      <arch id="aarch64" name="dummy" fallback="noarch"/>
      <arch id="noarch" name="dummy"/>
      <requiredarch ref="aarch64"/>
    </architectures>
```

**Comment by ggardet** [comment]
Please also review:
https://build.opensuse.org/request/show/832990
https://build.opensuse.org/request/show/832991
https://build.opensuse.org/request/show/832992
https://build.opensuse.org/request/show/832993

which are needed for aarch64.

**Comment by juliogonzalez** [comment]
@ggardet I am sorry, what do you mean with

> I am unable to boot on Uyuni-Server-DVD-aarch64-Build95.57-Media1.iso

?

Those images are not bootable. You need to install openSUSE Leap 15.2, and then add the repository on top, just as you would do for x86_64.

> For PXE images, you must use the right arch, here aarch64. So, please enable aarch64 in images_pxe.

I will give it a try, but IIRC they just don't build on any architecture that is not x86_64.

> Moreover, https://build.opensuse.org/package/view_file/home:Guillaume_G:branches:systemsmanagement:Uyuni:Master/000product/_service:product_converter:Uyuni-Server-dvd5-DVD-aarch64.kiwi?expand=1 looks wrong:

IIRC x86_64 is there because some packages don't build on non x86_64 architectures, and for those we have exportfilters. @mcalmer can you confirm?

**Comment by mcalmer** [comment]
Julio is right. The x86_64 is there for a reason. With kiwi we do not only create repos for the normal RPMs, we also create source media which should contain all the source rpms. Some packages build only on x86_64 and result in noarch binaries.
We use ExportFilter to copy the binaries to the other arch (e.g. aarch64). But this does not apply to src.rpm . To get the src.rpm for these packages on the media, we need this ugly trick and define x86_64 as last arch (even after noarch). 

You can test this with hibernate packages. The binaries should be on `Media1` as noarch packages, while you still can found the src.rpm on `Media2`.
With your change you cannot find the source packages on Media2.
As this is connetced to GPL requirements we cannot change it.

**Comment by ggardet** [comment]
Ah ok, I though it was a bootable ISO, sorry for the confusion.

**Comment by juliogonzalez** [comment]
Ok, god news, I was able to configure the images to make all packages for the Server and the Proxy installable.

This means that following https://www.uyuni-project.org/pages/devel-version.html using openSUSE Leap 15.2 `aarch64`, replacing x86_64 with aarch64 for the Uyuni repositories to be added, should do the trick and allow installing the Server.

@ggardet can you maybe give it a try?

**Comment by ggardet** [comment]
I tested it on a RPi4.
- Installation of packages from the repo: no problem
- I got a warning: `/usr/lib/susemanager/bin/mgr-setup: line 142: dig: command not found`, so a pattern is likely missing dep on `bind-utils`

I am able to create a new Organaziation and a new user. I will test further later, but so far, this is fine!

**Comment by ggardet** [comment]
> Thanks a lot @ggainey, this is already a very interesting feedback :-)

This is the wrong tag of people ;)

> Rather than the pattern, I'd say `mgr-setup` is missing a `bind-tools`. I will review it.
> 
> I am just curious: how did you perform the openSUSE instalaltion? JeOS? ISO? What pattern if you were using an ISO?

I just use the ready to boot RPi4 JeOS image + Uyuni `repo` for aarch64 + `zypper install`.

**Comment by juliogonzalez** [comment]
> This is the wrong tag of people ;)

Ouch!

> I just use the ready to boot RPi4 JeOS image + Uyuni repo for aarch64 https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master/images/repo/Uyuni-Server-POOL-aarch64-Media1/ + zypper install patterns-uyuni_server.

That's what I suspected. JeOS always do some cleanup for "unneeded" stuff so the installation footprint is enough, and maybe the cleanup is different architectures.

https://github.com/uyuni-project/uyuni/pull/3378 will fix this particular problem.

**Comment by ggardet** [comment]
Trying to add a new channel from CLI on server with `spacewalk-common-channels opensuse_leap15_2-aarch64` I get:
```
SUSE Manager username: guillaume
SUSE Manager password: 
Traceback (most recent call last):
  File "/usr/bin/spacewalk-common-channels", line 347, in <module>
    base_info['summary'], CHANNEL_ARCH[base_info['arch']],
KeyError: 'aarch64'
```

**Comment by juliogonzalez** [comment]
Mmmm, are you sure that's the right syntax?

I'd say it should be:
```
spacewalk-common-channels -a aarch64 opensuse_leap15_2
```

**Comment by ggardet** [comment]
> spacewalk-common-channels -a aarch64 opensuse_leap15_2

It returns `No channels matching your selection.`

**Comment by juliogonzalez** [comment]
Ah, my fault, sorry.

Now I remember that, yes, we used `opensuse_leap15_2-aarch64`.  The reason is that x86_64 and aarch64 use different paths, because aarch64 is still considered a port.

So your first command was right: `spacewalk-common-channels opensuse_leap15_2-aarch64`

The second one `spacewalk-common-channels opensuse_leap15_1` did not return an error because you added the channels, but for x86_64.

@mcalmer, could this becaused because we don't have `aarch64` at:
```
CHANNEL_ARCH = {
    'i386':         'channel-ia32',
    'ia64':         'channel-ia64',
    'sparc':        'channel-sparc',
    'sparc64':      'channel-sparc64',
    'alpha':        'channel-alpha',
    's390':         'channel-s390',
    's390x':        'channel-s390x',
    'iSeries':      'channel-iSeries',
    'pSeries':      'channel-pSeries',
    'x86_64':       'channel-x86_64',
    'ppc':          'channel-ppc',
    'ppc64':        'channel-ppc64',
    'ppc64le':      'channel-ppc64le',
    'amd64-deb':    'channel-amd64-deb',
    'ia32-deb':     'channel-ia32-deb',
    'ia64-deb':     'channel-ia64-deb',
    'sparc-deb':    'channel-sparc-deb',
    'alpha-deb':    'channel-alpha-deb',
    's390-deb':     'channel-s390-deb',
    'powerpc-deb':  'channel-powerpc-deb',
    'arm-deb':      'channel-arm-deb',
    'mips-deb':     'channel-mips-deb'

}
```
at `spacewalk-common-channels`?

What should we add there? `'aarch64': 'channel-aarch64'`?

**Comment by mcalmer** [comment]
From spacewalk/common/data/rhnChannelArch.sql
```
insert into rhnChannelArch (id, label, name, arch_type_id) values
(sequence_nextval('rhn_channel_arch_id_seq'), 'channel-aarch64', 'AArch64', lookup_arch_type('rpm'));
```

So, yes - it looks right.
CHANNEL_NAME_TO_ARCH dict has already `AArch64`. So no change required there.

**Comment by juliogonzalez** [comment]
So you mean that:
```
[opensuse_leap15_2-aarch64]
checksum = sha256
archs    = aarch64
name     = openSUSE Leap 15.2 (%(arch)s)
gpgkey_url = http://download.opensuse.org/ports/aarch64/distribution/leap/15.2/repo/oss/repodata/repomd.xml.key
gpgkey_id = 3DBDC284
gpgkey_fingerprint = 22C0 7BA5 3417 8CD0 2EFE  22AA B88B 2FD4 3DBD C284
repo_url = http://download.opensuse.org/ports/aarch64/distribution/leap/15.2/repo/oss/
dist_map_release = 15.2
```
Is incorrect, and we should have `aarchs = AArch64` :-?

**Comment by mcalmer** [comment]
> Side note: lower case `aarch64` looks better than `AArch64`.

This was not our decission. We got this naming from spacewalk already. Changing this is a nightmare and we better don't touch it.

**Comment by juliogonzalez** [comment]
@ggardet can you change `archs    = aarch64` to `archs    = AArch64` and try again?

If it works, I will send a PR to channge all the Leap aarch64 repositories.

**Comment by mcalmer** [comment]
> Is incorrect, and we should have `aarchs = AArch64` :-?

I can only suggest to try this out. Only than you know what is correct . But I think lowercase should work.

**Comment by mcalmer** [comment]
I think the important change is adding `'aarch64': 'channel-aarch64'` to the map.

**Comment by ggardet** [comment]
> @ggardet can you change `archs = aarch64` to `archs = AArch64` and try again?
> 
> If it works, I will send a PR to channge all the Leap aarch64 repositories.

Could you point to the file I need to update, please?

**Comment by juliogonzalez** [comment]
Ah, yes, sorry.

Create a copy of `/etc/rhn/spacewalk-common-channels.ini` somewhere and do the changes at this copy.

Then you can use it for `spacewalk-common-channels` with the `-c` or `--config` option.

I suggest you change all the Leap 15.2 aarch repositories, including those for the client tools.

**Comment by ggardet** [comment]
> Ah, yes, sorry.
> 
> Create a copy of `/etc/rhn/spacewalk-common-channels.ini` somewhere and do the changes at this copy.
> 
> Then you can use it for `spacewalk-common-channels` with the `-c` or `--config` option.
> 
> I suggest you change all the Leap 15.2 aarch repositories, including those for the client tools.

Here is what I did: 
* `sed -i 's/archs    = aarch64/archs    = AArch64/' spacewalk-common-channels.ini`
* `spacewalk-common-channels opensuse_leap15_2-aarch64 -c spacewalk-common-channels.ini` which returned:
```
SUSE Manager username: guillaume
SUSE Manager password: 
Traceback (most recent call last):
  File "/usr/bin/spacewalk-common-channels", line 347, in <module>
    base_info['summary'], CHANNEL_ARCH[base_info['arch']],
KeyError: 'AArch64'
```

**Comment by juliogonzalez** [comment]
So seems we really have a real bug, we'll need to have a look.

**Comment by juliogonzalez** [comment]
@ggardet try the fix at https://github.com/uyuni-project/uyuni/pull/3385/files

You need to change `/usr/bin/spacewalk-common-channels`, or just replace it with the file `spacewalk-common-channels` from that PR.

Fixed the issue for me.

**Comment by ggardet** [comment]
> @ggardet try the fix at https://github.com/uyuni-project/uyuni/pull/3385/files
> 
> You need to change `/usr/bin/spacewalk-common-channels`, or just replace it with the file `spacewalk-common-channels` from that PR.
> 
> Fixed the issue for me.

Indeed, this is the right fix and no need to update `spacewalk-common-channels.ini`

**Comment by ggardet** [comment]
I think we are in good shapes for this issue. I would suggest to close this ticket as soon as the doc is updated. And we can create new github issues, if/when problems show up. WDYT @juliogonzalez ?

**Comment by juliogonzalez** [comment]
Can I ask for a couple of extra test?

- Onboard any client with a OS supported by Uyuni, play a little with it
- Create a proxy, onboard a client via proxy, play a little with it.

If this works fine, I'd say we can close this ticket, announce "Uyuni Server/Proxy for aarch64" as beta, so people can start testing it from the Stable repositories, and after a couple of releases with no complains, we can mark it as "production ready".

What do you think?

**Comment by ggardet** [comment]
I am not an expert of Uyuni. ;)
I added a Leap 15.2 aarch64 client (via SSH) and it appears on the list of system. I managed to schedule and execute few tasks properly. My aarch64 board lacks some disk space for the sync of Leap 15.2 aarch64 channel, so I will need to upgrade it.

For the proxy part, I have no idea how to create and use a proxy.

**Comment by juliogonzalez** [comment]
> I am not an expert of Uyuni. ;)

Don't worry, ithis is nothing complicated.

A proxy is an Uyuni client with some extras: https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-proxy-registration.html and https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-proxy-setup.html (the idea is that you use proxy to onboard clients when your number of clients is so high that the server alone can't manage them, or when you have bandwidth constraints as the proxy also acts as a cache).

If you review the doc, you will see It's not really hard to configure. 

When it's done, you just need to register another client via proxy (doing a WebUI bootstrap you have a combo for that), and then it's just a matter of checking this new client works normally in terms of applying a highstate, running a salt command, or installing/removing/updating a package.

Do I understand you are also testing https://github.com/uyuni-project/uyuni/issues/2129 ?

If so, that's great! We could announce official support for Leap 15.2 aarch64 soon (could you quickly test if regular salt minions work as well? I understand you tested a ssh managed minion, which doesn't install a real salt minion)

**Comment by juliogonzalez** [comment]
@ggardet can you give it a try? :-)

**Comment by juliogonzalez** [comment]
Closing. Packages are published, and on paper things should install. The PXE image is only available for x86_64, yes, but that's what we do for SUSE Manager as well. It could get fixed later, but it's not requirement.

I will ask again the community to give it a try, and give us more feedback, as I did at the last Uyuni Community Hours :-)
