### ISSUE TITLE
ERROR: relation "rhnactionvirtpoolrefresh" does not exist after upgrade to 2020.04

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#2163]
Uyuni release 2020.03

I have tried to upgrade to Uyuni 2020.04 via `zypper upgrade`, however I have noticed the following SQL error after the upgrade on rhn_web_ui.log log:

```
2020-04-25 15:34:42,918 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42P01
2020-04-25 15:34:42,918 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: relation "rhnactionvirtpoolrefresh" does not exist
  Position: 2720
```

Knowing that in `schema/spacewalk/common/tables/rhnActionVirtDelete.sql` I can see that the table created is called `rhnActionVirtPoolRefresh`, could it be that there is somewhere a wrong reference to this table in lower case ?

**Comment by phibid** [comment]
Forgot to tell that the main symptom of this error, is an "Unexpected error" popup appearing on the Uyuni main page. Because of that the Uyuni Web UI is hardly usable.

**Comment by tsikkema24** [comment]
We are having the same issue after 2020.04 update. And get popup on homepage. 

ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: relation "rhnactionvirtpoolrefresh" does not exist

**Comment by juliogonzalez** [comment]
@cbosdo, I think this is the bug what should get fixed with 2020.05, and replied at 
https://lists.opensuse.org/uyuni-users/2020-04/msg00048.html

@phibid @tsikkema24 can you try to run the SQL script and see if it fixes your problem?

**Comment by tsikkema24** [comment]
where is the script file located?

**Comment by cbosdo** [comment]
indeed that is the same problem. I apologize for messing it up... please run the database upgrade scripts manually. As mentioned in the email, please run the following:

```sh
for sql in $(ls /etc/sysconfig/rhn/schema-upgrade/susemanager-schema-4.1.4-to-susemanager-schema-4.1.5/*{v,V}irt*); do
  spacewalk-sql $sql
done
```

**Comment by tsikkema24** [comment]
Looks like that did it for me. nothing in the logs yet and homepage loads without issue.

**Comment by rpasche** [comment]
Can confirm, that this error is gone with 2020.05.

**Comment by cbosdo** [comment]
thanks @rpasche for the feedback. Closing the issue then
