### ISSUE TITLE
Uyuni client repo for Ubuntu 20.04 is missing on download.opensuse.org

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#2263]
```ubuntu-2004-amd64-uyuni-client``` preloaded channel is proposed in ```spacewalk-common-channels```, however the repository is still not present in [https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/](url)

**Comment by paususe** [comment]
It's a known issue which we are working on.

Ubuntu is a Salt-only client
Ubuntu 20.04 only ships Python 3.8
No released version of Salt supports Python 3.8 yet

We have backported some Salt master branch patches to enable Salt 3000 with Python 3.8 and will make Salt 3000 available on Leap 15.1 soon.

If that takes longer than expected, then this will be supported in Uyuni 2020.07, which should be the first version of Uyuni running on Leap 15.2 (which already has Salt 3000).

If you just want to test Ubuntu 20.04, I suggest you install Uyuni Master on Leap 15.2 RC. You will need to add these two repositories:
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master/openSUSE_Leap_15.2/
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/Other/openSUSE_Leap_15.2/

**Comment by phibid** [comment]
Ok, thanks Pau.

I understand that this error I get while trying to register an Ubuntu 20.04 client through salt-ssh is coming from the unsupported 3.8 Python version by Salt then:

/var/tmp/.root_930115_salt/pyall/salt/utils/decorators/signature.py:30: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly inspect.formatargspec( Traceback (most recent call last): File "/var/tmp/.root_930115_salt/salt-call", line 27, in <module> salt_call() File "/var/tmp/.root_930115_salt/pyall/salt/scripts.py", line 426, in salt_call import salt.cli.call File "/var/tmp/.root_930115_salt/pyall/salt/cli/call.py", line 5, in <module> import salt.utils.parsers File "/var/tmp/.root_930115_salt/pyall/salt/utils/parsers.py", line 28, in <module> import salt.config as config File "/var/tmp/.root_930115_salt/pyall/salt/config/__init__.py", line 99, in <module> _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5 File "/var/tmp/.root_930115_salt/pyall/salt/config/__init__.py", line 88, in _gather_buffer_space import salt.grains.core File "/var/tmp/.root_930115_salt/pyall/salt/grains/core.py", line 44, in <module> from platform import _supported_dists ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib/python3.8/platform.py)
Host:

Regards,
Philippe.


Philippe Bidault | Unix Engineer

Getronics
________________________________
M. 34617301667 | E. Philippe.Bidault@Getronics.com | W. www.getronics.com

Getronics CMC Service Desk Iberia S.L -  VAT No:S.L.: B66686262.
Registered Office - Getronics CMC Service Desk Iberia S.L, C/Rosselloi, Porcel, 21 planta 11, 08016 Barcelona, Spain.

The information transmitted is intended only for use by the addressee and may contain confidential and/or privileged material. Any review, re-transmission, dissemination or other use of it, or the taking of any action in reliance upon this information by persons and/or entities other than the intended recipient is prohibited. If you received this in error, please inform the sender and/or addressee immediately and delete the material.  Thank you.
Legal disclaimer: http://www.getronics.com/legal/

**Comment by paususe** [comment]
@phibid that's right, it's due to missing Python 3.8 support in Salt 2019.2

**Comment by juliogonzalez** [comment]
Quick update: The Ubuntu 20.04 will be part of Uyuni 2020.07, that should go out in a few days. Stay tuned :-)

**Comment by Shirocco88** [comment]
Thanks to the Uyuni-Team!!!

Uyuni-Client-Tools for Ubuntu 20.04 are available:
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/

Maybe this issue can be closed.

**Comment by juliogonzalez** [comment]
Right https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/xUbuntu_20.04/ already has packages, and it should an exact clone of Master when we released, so it should work fine (as it was on Master when we did the tests.

@phibid can we close? Were you able to sync? If you were able but you had other issues, let's close this one and let's follow the problems in another one.

**Comment by phibid** [comment]
Yes, I guess that it can be closed now that Ubuntu 20.04 is supported on 2020.07.

However I can’t really confirm that this is working, not needed it anymore, we now use salt ssh-push method for client registration.


Philippe Bidault | Unix Engineer

Getronics
________________________________
M. 34617301667 | E. Philippe.Bidault@Getronics.com | W. www.getronics.com

Getronics CMC Service Desk Iberia S.L -  VAT No:S.L.: B66686262.
Registered Office - Getronics CMC Service Desk Iberia S.L, C/Rosselloi, Porcel, 21 planta 11, 08016 Barcelona, Spain.

The information transmitted is intended only for use by the addressee and may contain confidential and/or privileged material. Any review, re-transmission, dissemination or other use of it, or the taking of any action in reliance upon this information by persons and/or entities other than the intended recipient is prohibited. If you received this in error, please inform the sender and/or addressee immediately and delete the material.  Thank you.
Legal disclaimer: http://www.getronics.com/legal/
