### ISSUE TITLE
Package index checksum failure

### ISSUE THREAD

**Issue by brejoc** [uyuni-project/uyuni#2283]
2nd part of this issue: https://github.com/uyuni-project/uyuni/issues/2103

https://github.com/uyuni-project/uyuni/issues/2103#issuecomment-610546680
and
https://github.com/uyuni-project/uyuni/issues/2103#issuecomment-618796722

**Comment by mcalmer** [comment]
I think you want a 3rd issue for GPG checksum checking? Or do you have already one?

**Comment by paususe** [comment]
> I think you want a 3rd issue for GPG checksum checking? Or do you have already one?

We have this one:
https://github.com/SUSE/spacewalk/issues/9882

**Comment by mcalmer** [comment]
> > I think you want a 3rd issue for GPG checksum checking? Or do you have already one?
> 
> We have this one:
> [SUSE/spacewalk#9882](https://github.com/SUSE/spacewalk/issues/9882)

Exactly what we need
