### ISSUE TITLE
Adding a repo with zypper needs to be covered more fully in install guide

### ISSUE THREAD

**Issue by douglasawh** [uyuni-project/uyuni#2327]
In regards to https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-uyuni.html, specifically this section:

> 3. Add the repository for installing the Uyuni Server software as root:
> repo=repositories/systemsmanagement:/
> repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
> zypper ar https://download.opensuse.org/$repo uyuni-server-stable

This is three separate commands and for people not familiar with zypper it looks like nonsense.

I think this has been done so the text all fits nicely with the right sidebar, which I think is silly, but I understand the decision.

I think this can be resolved by simply changing it to the following (and then renumbering the rest):

> 
> 3. Set variables that will be used in creating the repo
> 
> repo=repositories/systemsmanagement:/
> repo=${repo}Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/
> 
> 4. Add the repository for installing the Uyuni Server software as root:
> zypper ar https://download.opensuse.org/$repo uyuni-server-stable

**Comment by juliogonzalez** [comment]
@Loquacity I think this one is for you. Can you handle it?
