### ISSUE TITLE
ULN plugin broken in 2020.06

### ISSUE THREAD

**Issue by scomcd** [uyuni-project/uyuni#2359]
When attempting to synchronise an Oracle ULN repository, the ULN plugin outputs the following error.

Command:
   # spacewalk-repo-sync --type uln --channel=ol7_x86_64_u8_base --url=uln:///ol7_x86_64_u8_base

Initial error:
  ModuleNotFoundError: No module named 'spacewalk.satellite_tools.ulnauth'

Added missing ulnauth.py from GitHub uyubu-projects satellite_tools:
   /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/ulnauth.py

Re-ran command, new error:

  10:16:54 ======================================
  10:16:54 | Channel: ol7_x86_64_u8_base
  10:16:54 ======================================
  10:16:54 Sync of channel started.
  Source_URL:  uln:/ol7_x86_64_u8_base
  10:16:54 Unexpected error: <class 'Exception'>
  10:16:54 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 509, in sync
      raise Exception("Unknown protocol in repo URL: %s" % url)
  Exception: Unknown protocol in repo URL: uln:/ol7_x86_64_u8_base

**Comment by meaksh** [comment]
Hey @scomcd , thanks for reporting the issue!

Which version of Uyuni are you running? We fixed the missing `ulnauth` file few months ago and should we included on latest Uyuni releases.

Btw, it seems you're passing a wrong ULN repository url, apparently `--url=uln:///ol7_x86_64_u8_base` is not a valid one.

Could you please try with a real ULN repository? Thanks!

**Comment by meaksh** [comment]
@scomcd I noticed you reported on the title that you're running Uyuni 2020.06 release.

In that case, if you upgraded from a previous Uyuni version, maybe the `spacewalk-backend` package didn't get upgraded because of this known issue on 2020.06: https://www.uyuni-project.org/doc/2020.06/release-notes-uyuni-server.html#_python3_psycopg2_and_backend_packages_not_being_updated

You should follow those instructions in order to get Uyunu 2020.06 fully upgraded, so the missing `ulnauth` file is there.

**Comment by scomcd** [comment]
Thankyou meaksh for the advice regarding the known issue. I have installed the python3-psycopg2 pkg and updated the backend as per the instructions.

I'm still confused as to what the correct URL for an Oracle ULN channel should be in Uyuni.
The format "uln:///channel_name" is what we use for our Oracle Spacewalk Server and works on that system.
It is also what Oracle specify in their spacewalk documentation:

(Oracle Spacewalk Documentation - https://docs.oracle.com/en/operating-systems/spacewalk/2.7/admin/crreposwc.html#crrepo
excerpt)
   For ULN, a Spacewalk repository specifies the URL of a ULN channel in the following format:
  uln:///ULN_channel_label
  You can obtain a list of available ULN channel labels by logging into ULN (https://linux.oracle.com) and then selecting the Channels tab.
  The URL must contain three forward slash (/) characters,

There is definitely an Oracle Channel named  ol7_x86_64_u8_base
(excerpt)
Oracle Linux 7 Update 8 installation media copy (x86_64) | ol7_x86_64_u8_base | All packages released for Oracle Linux 7 Update 8 (x86_64). No errata included
-- | -- | --

But it makes no difference which channel I configure for syncing, the uln:/// prefix is not accepted by Uyuni spacewalk.

**Comment by paususe** [comment]
@scomcd IIUC that Oracle Spacewalk documentation link is telling you how to create the channels with those names and the repositories specified in https://docs.oracle.com/en/operating-systems/spacewalk/2.7/admin/crreposwc.html#crrepo

E. g. they tell you how to create a channel called "ol6_x86_64_latest" which corresponds to the URL "https://yum.oracle.com/repo/OracleLinux/OL6/6/base/x86_64/"

In Uyuni, those channels are already predefined (we saved you that step), you just need to enable them with `spacewalk-common-channels` as described here:
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-oracle.html#_channel_and_repository_management

**Comment by scomcd** [comment]
Yes, we have already configured the Oracle Linux Public YUM channels  using 'spacewalk-common-channels' and use these for these for Non-Production Oracle systems.

But, as per the Oracle Documentation:  "ULN provides base and patch channels for each update of an Oracle Linux release. The Oracle Linux yum server does not provide separate patch channels. Instead, it provides a olN_latest repository that includes all of the packages for an entire release"

We were using these patch channels in our Oracle Spacewalk Server.
 I'm sure their functionality can be replicated using life cycles in Uyuni, but I have to ask. 
What is the point of having a ULN option in Uyuni, assertingthe plugin works, but then directing me to use spacewalk-common-channels?

**Comment by scomcd** [comment]
In addition to my previous comments, one of our Admins reminded me that we also need the ULN channels for ksplice and UEK pkgs as these are not available from the channels provided by spacewalk-comon-channels or public yum repositories.

**Comment by mcalmer** [comment]
@scomcd JFYI - we do not have credentials for ULN and cannot test it. So we develop in the dark and rely on you for testing and reporting. And you may know that we are short before a relase, so everybody is very busy here. So it may take some time until we can have a deeper look.

Any stack trace can help. So when you see one on the console or in the logs /var/log/rhn/reposync/<label>.log please paste it here. Thanks

**Comment by scomcd** [comment]
@mcalmer FYI, Thanks for the clarification.

 I have added all information I have been able to discern so far to this comment.
 Bear in mind I am not a python developer.


#---------------------------------------------------------------------------------------------#
Configured our Businesses Oracle ULN credentials in the uln.conf file:
#---------------------------------------------------------------------------------------------#
/etc/rhn/spacewalk-repo-sync/uln.conf


#---------------------------------------------------------------------------------------------#
Repo Creation result via Web interface method: 
#---------------------------------------------------------------------------------------------#

Repository Label: ol7_x86_64_u8_base
Repository URL:	uln:///ol7_x86_64_u8_base
Repository Type: uln

error: The given url is invalid. Please enter an url with valid syntax (e.g. specify the protocol).



#---------------------------------------------------------------------------------------------#
Command line method via spacecmd:
#---------------------------------------------------------------------------------------------#

spacecmd {SSM:0}> repo_create
Name: ol7_x86_64_u8_base
URL: uln:///ol7_x86_64_u8_base
Type: uln
SSL CA cert:
SSL Client cert:
SSL Client key:
ERROR: redstone.xmlrpc.XmlRpcFault: The given url is invalid. Please enter an url with valid syntax (e.g. specify the protocol).




#---------------------------------------------------------------------------------------------#
Run spacewalk command to sync repository - to try an ellicit more detail as to why uln fails:
#---------------------------------------------------------------------------------------------#


spacewalk-repo-sync --type uln --channel=ol7_x86_64_u8_base --url=uln:///ol7_x86_64_u8_base

# spacewalk-repo-sync --type uln --channel=ol7_x86_64_u8_base --url=uln:///ol7_x86_64_u8_base
09:37:16 ======================================
09:37:16 | Channel: ol7_x86_64_u8_base
09:37:16 ======================================
09:37:16 Sync of channel started.
09:37:16 Unexpected error: <class 'Exception'>
09:37:16 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 513, in sync
    raise Exception("Unknown protocol in repo URL: %s" % url)
Exception: Unknown protocol in repo URL: uln:/ol7_x86_64_u8_base

Generating bootstrap repos for all available products which had changes.
Nothing to do.
09:37:17 Total time: 0:00:00




#---------------------------------------------------------------------------------------------#
 Grep for code in reposync.py where error occurs with ULN url being truncated.
#---------------------------------------------------------------------------------------------#

dsreposrv1:~ # grep -A 10 -B 10 -n 'Unknown protocol in repo' /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py
503-            insecure = False
504-            if data['metadata_signed'] == 'N':
505-                insecure = True
506-
507-            plugin = None
508-            repo_type = data['repo_type']
509-
510-            for url in data['source_url']:
511-                try:
512-                    if '://' not in url:
513:                        raise Exception("Unknown protocol in repo URL: %s" % url)
514-
515-                    # If the repository uses a uln:// URL, switch to the ULN plugin, overriding the command-line
516-                    if url.startswith("uln://"):
517-                        repo_type = "uln"
518-
519-                    is_non_local_repo = (url.find("file:/") < 0)
520-                    self.repo_plugin = self.load_plugin(repo_type)
521-
522-                    if data['repo_label']:
523-                        repo_name = data['repo_label']



#---------------------------------------------------------------------------------------------#
Added some debug print statements to narrow down where source_url is being truncated:
#---------------------------------------------------------------------------------------------#

495     def sync(self, update_repodata=True):
 496         """Trigger a reposync"""
 497         failed_packages = 0
 498         sync_error = 0
 499         repo_checksum_type = 'sha1'
 500         start_time = datetime.now()
 501         for data in self.urls:
 502             print ("\nDebug Line 502 - Data SourceURL: ",data['source_url'],"\n")
 503             data['source_url'] = self.set_repo_credentials(data)
 504             print ("\nDebug Line 504 - Data SourceURL: ",data['source_url'],"\n")
 505             insecure = False
 506             if data['metadata_signed'] == 'N':
 507                 insecure = True



#---------------------------------------------------------------------------------------------#
Re-ran reposync command to try and identify where URL is being truncated.
#---------------------------------------------------------------------------------------------#

dsreposrv1:~ # spacewalk-repo-sync --type uln --channel=ol7_x86_64_u8_base --url=uln:///ol7_x86_64_u8_base
10:03:42 ======================================
10:03:42 | Channel: ol7_x86_64_u8_base
10:03:42 ======================================
10:03:42 Sync of channel started.

Debug Line 502 - Data SourceURL:  ['uln:///ol7_x86_64_u8_base']


Debug Line 504 - Data SourceURL:  ['uln:/ol7_x86_64_u8_base']

10:03:42 Unexpected error: <class 'Exception'>
10:03:42 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 515, in sync
    raise Exception("Unknown protocol in repo URL: %s" % url)
Exception: Unknown protocol in repo URL: uln:/ol7_x86_64_u8_base

Generating bootstrap repos for all available products which had changes.
Nothing to do.
10:03:42 Total time: 0:00:00



#---------------------------------------------------------------------------------------------#
 Function 'set_repo_credentials' which calls function  '_url_with_repo_credentials' appears to be 
 where the issue lies.
#---------------------------------------------------------------------------------------------#

1727     def set_repo_credentials(self, url_dict):
1728         """Set the credentials in the url_dict['source_url'] url list from the config file"""
1729         return [self._url_with_repo_credentials(url) for url in url_dict['source_url']]

**Comment by meaksh** [comment]
Hi @scomcd , thanks for your patience here!

I was taking a look here and I was able to get a fix for this problem when calling `spacewalk-repo-sync` from the command line: https://github.com/uyuni-project/uyuni/commit/996f7cd1c34fb567fa611e7d5342d30b088a09e4

With the above fix, and using some fake credentials since I don't have any real ones for ULN, and I was able to run reposync further until I got "invalid user / password" exception from ULN network:

```console
# spacewalk-repo-sync --type uln --channel=ol7_x86_64_u8_base --url=uln:///ol7_x86_64_u8_base
17:33:09 ======================================
17:33:09 | Channel: ol7_x86_64_u8_base
17:33:09 ======================================
17:33:09 Sync of channel started.
17:33:11 Unhandled error occurred: Authentication failure: token was not obtained. <Fault 60: 'Invalid username or password.'>
17:33:11 Unexpected error: <class 'spacewalk.satellite_tools.ulnauth.ULNTokenException'>
17:33:11 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 570, in sync
    client_key_file=client_key_file)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/uln_src.py", line 41, in __init__
    client_key_file=client_key_file)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 471, in __init__
    self._authenticate(url)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/uln_src.py", line 47, in _authenticate
    self.uln_token = self._uln_auth.authenticate(url)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/ulnauth.py", line 117, in authenticate
    raise ULNTokenException("Authentication failure: token was not obtained. {}".format(err_msg))
spacewalk.satellite_tools.ulnauth.ULNTokenException: Authentication failure: token was not obtained. <Fault 60: 'Invalid username or password.'>
```

@scomcd is there chance you can test the above fix and verify that it works? Thanks in advance!

The other issue about WebUI not accepting repository ULN URIs is still not fixed.

**Comment by scomcd** [comment]
Hi @meaksh 

Thanks for investigating this issue.
I have updated the file "/usr/lib/python3.6/site-packages/spacewalk/common/suseLib.py" with the modified
version you provided and run a new sync from the CLI.

# spacewalk-repo-sync --type uln --channel=ol7_x86_64_u9_base  --url=uln:///ol7_x86_64_u9_base
08:54:46 ======================================
08:54:46 | Channel: ol7_x86_64_u9_base
08:54:46 ======================================
08:54:46 Sync of channel started.
The download URL is: https://linux-update.oracle.com/XMLRPC/GET-REQ/ol7_x86_64_u9_base
Retrieving repository 'ol7_x86_64_u9_base' metadata .............................................................................................................[error]
Repository 'ol7_x86_64_u9_base' is invalid.
[ol7_x86_64_u9_base|plugin:spacewalk-uln-resolver?url=https://linux-update.oracle.com/XMLRPC/GET-REQ/ol7_x86_64_u9_base] Valid metadata not found at specified URL
History:
 - Unknown error reading from 'plugin:spacewalk-uln-resolver?url=https://linux-update.oracle.com/XMLRPC/GET-REQ/ol7_x86_64_u9_base'
 - Authentication failure: token was not obtained. URL must start with 'uln://'.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ol7_x86_64_u9_base' because of the above error.
Could not refresh the repositories because of errors.
08:54:50 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
08:54:50 Total time: 0:00:04
 

I have checked that our uln credentials are correct and that the require Oracle GPG keys have been imported.

Thank you again for your assistance.

**Comment by meaksh** [comment]
Hey @scomcd,
thank you for testing this and provide feedback! :+1:

I think we're close now to get this fixed! I've pushed an extra patch here: https://github.com/uyuni-project/uyuni/commit/343606f4167db60fc960d9b8cc345ffa5c069d4b

Having this extra patch applied together with the previous one you already applied I think it might do the magic! :smile: 

Could you give it a try? Thanks in advance!

**Comment by scomcd** [comment]
Hi @meaksh

I applied the patch to the backend/satellite_tools/repo_plugins/uln_src.py file and re-ran the 
spacewalk-repo-sync for a few of the Oracle 7 ULN channels.
The process now connects to the linux-update.oracle.com servers, but only some of the channels will
sync the correct number of packages.

As an example, the ol7 UEK6 channel has 68 packages when viewed via the Oracle Linux Web Interface, 
but Uyuni reports only 1 package is available via the Channel in the GUI.

When we review the reposync logs, we are seeing lots of package sync errors similar to the following example for the UEK6 channel. 

# /usr/bin/spacewalk-repo-sync --type uln --channel=ol7_x86_64_uekr6  --url=uln:///ol7_x86_64_UEKR6 
12:09:43 ======================================
12:09:43 | Channel: ol7_x86_64_uekr6
12:09:43 ======================================
12:09:43 Sync of channel started.
The download URL is: uln:///ol7_x86_64_UEKR6
Retrieving repository 'ol7_x86_64_uekr6' metadata ................................................................................................................[done]
Building repository 'ol7_x86_64_uekr6' cache .....................................................................................................................[done]
All repositories have been refreshed.
12:10:07 Repo URL: uln:///ol7_x86_64_UEKR6
12:10:07     Packages in repo:               174
12:10:07     Packages already synced:         20
12:10:07     Packages to sync:                67
12:10:07     New packages to download:        67
12:10:07   Downloading packages:
12:10:07 Downloading total 67 files from 1 queues.
12:10:07 ERROR: Download failed: getPackage/crash-7.2.7-1.0.1.el7.x86_64.rpm - [Errno 14] curl#37 - "Couldn't open file /root/getPackage/crash-7.2.7-1.0.1.el7.x86_64.rpm".
12:10:07     1/67 : crash-7.2.7-1.0.1.el7.x86_64.rpm (failed)
12:10:07 ERROR: Download failed: getPackage/btrfs-progs-devel-5.4.0-1.el7.x86_64.rpm - [Errno 14] curl#37 - "Couldn't open file /root/getPackage/btrfs-progs-devel-5.4.0-1.el7.x86_64.rpm".
12:10:07 ERROR: Download failed: getPackage/btrfs-progs-5.4.0-1.el7.x86_64.rpm - [Errno 14] curl#37 - "Couldn't open file /root/getPackage/btrfs-progs-5.4.0-1.el7.x86_64.rpm".
12:10:07 ERROR: Download failed: getPackage/crash-devel-7.2.7-1.0.1.el7.x86_64.rpm - [Errno 14] curl#37 - "Couldn't open file /root/getPackage/crash-devel-7.2.7-1.0.1.el7.x86_64.rpm".
12:10:07     2/67 : btrfs-progs-devel-5.4.0-1.el7.x86_64.rpm (failed)
12:10:07 ERROR: Download failed: getPackage/daxctl-devel-67-1.0.1.el7.x86_64.rpm - [Errno 14] curl#37 - "Couldn't open file /root/getPackage/daxctl-devel-67-1.0.1.el7.x86_64.rpm".


One more issue, the ULN sync will fail if I set an Internet proxy via the Uyuni GUI. 
Our Network Team have allowed direct access to the linux-update.oracle.com site so this is not necessary for ULN channels
but we typically have this enabled as a default for the other Uyuni provided channels. The other channels do not report any
issues synchronising if the Internet proxy setting is set, only the ULN channels do. 
The ULN sync errors shown above are direct/without a proxy being set.

 
Thank you for your assistance with this issue.

**Comment by meaksh** [comment]
@scomcd Thank you for the feedback!

I've pushed some more changes to the branch that would fix the remaining issues we have here:

- Errors at RPM downloading.
- HTTP Proxy not working with ULN.
- Allow creating custom `uln://` repositories via webUI.

I've also created a PR: https://github.com/uyuni-project/uyuni/pull/2830

In order to test the reposync part, let me summarize the files you need to patch according to the PR changes:

- /usr/lib/python3.6/site-packages/spacewalk/common/suseLib.py
- /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py
- /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/uln_src.py
- /usr/lib/zypp/plugins/urlresolver/spacewalk-uln-resolver

In case you're running Uyuni 2020.09, it's safe to take those particular files entirely from the PR.

In case you face any issue, please just let me know. Thanks a lot!

**Comment by scomcd** [comment]
Hi @meaksh

Yes, we are running Uyuni rel 2020.09
I've updated the following files as requested.

x •	/usr/lib/python3.6/site-packages/spacewalk/common/suseLib.py
x •	/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py
x •	/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/uln_src.py
x •	/usr/lib/zypp/plugins/urlresolver/spacewalk-uln-resolver


Unfortunately, we are still receiving errors when we run command line syncs of ULN channels.

# /usr/bin/spacewalk-repo-sync --type uln --channel=ol7_x86_64_uekr6 --url=uln:///ol7_x86_64_UEKR6
09:31:57 ======================================
09:31:57 | Channel: ol7_x86_64_uekr6
09:31:57 ======================================
09:31:57 Sync of channel started.
The download URL is: https://linux-update.oracle.com/XMLRPC/GET-REQ/ol7_x86_64_UEKR6/
Retrieving repository 'ol7_x86_64_uekr6' metadata ...............................................................................................................[error]
Repository 'ol7_x86_64_uekr6' is invalid.
[ol7_x86_64_uekr6|plugin:spacewalk-uln-resolver?url=uln:///ol7_x86_64_UEKR6/&] Valid metadata not found at specified URL
History:
 - Unknown error reading from 'plugin:spacewalk-uln-resolver?url=uln:///ol7_x86_64_UEKR6/&'
 - Receive: script died unexpectedly
 - [11-Resource temporarily unavailable]

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ol7_x86_64_uekr6' because of the above error.
Could not refresh the repositories because of errors.
09:32:01 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
09:32:01 Total time: 0:00:04
You have new mail in /var/spool/mail/root

(additional channel test)

# /usr/bin/spacewalk-repo-sync --type uln --channel=ol7_x86_64_ksplice --url=uln:///ol7_x86_64_ksplice
09:56:28 ======================================
09:56:28 | Channel: ol7_x86_64_ksplice
09:56:28 ======================================
09:56:28 Sync of channel started.
The download URL is: https://linux-update.oracle.com/XMLRPC/GET-REQ/ol7_x86_64_ksplice/
Retrieving repository 'ol7_x86_64_ksplice' metadata .............................................................................................................[error]
Repository 'ol7_x86_64_ksplice' is invalid.
[ol7_x86_64_ksplice|plugin:spacewalk-uln-resolver?url=uln:///ol7_x86_64_ksplice/&] Valid metadata not found at specified URL
History:
 - Unknown error reading from 'plugin:spacewalk-uln-resolver?url=uln:///ol7_x86_64_ksplice/&'
 - Receive: script died unexpectedly
 - [11-Resource temporarily unavailable]

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ol7_x86_64_ksplice' because of the above error.
Could not refresh the repositories because of errors.
09:56:33 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
09:56:33 Total time: 0:00:04


The errors being returned are consistent with or without a proxy set via the Uyuni GUI.


#------------------------------------------------------------------------------------------#
We tested creating a ULN repository via the GUI, but we still receive an error:
#------------------------------------------------------------------------------------------#

Create Channel/Repo Via GUI:

Repository Label*: ol7_x86_64_UEKR6
Repository URL*: uln:///ol7_x86_64_UEKR6
Repository Type*: uln
Has Signed Metadata: unchecked

Error:
The given url is invalid. Please enter an url with valid syntax (e.g. specify the protocol).


#------------------------------------------------------------------------------------------#
Diff comparisons - original and files modified by PR #2830 - 2020/11/12 AEDT
#------------------------------------------------------------------------------------------#

# diff /usr/lib/python3.6/site-packages/spacewalk/common/suseLib.py.orig  /usr/lib/python3.6/site-packages/spacewalk/common/suseLib.py

631c631
<     if u.scheme == 'file':
---
>     if u.scheme == 'file' or not u.hostname:
665d664
<

# diff /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/uln_src.py.orig /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/uln_src.py

36a37,39
>         # Make sure baseurl ends with / and urljoin will work correctly
>         if url[-1] != '/':
>             url += '/'
49,50c52,54
<         hostname, label = self._uln_auth.get_hostname(url)
<         print(("The download URL is: " + self.url))
---
>         hostname, label = self._uln_auth.get_hostname(self.url)
>         self._load_proxy_settings(hostname)
>         print(("The download URL is: " + self._uln_auth.url + "/XMLRPC/GET-REQ/" + label))
56a61,73
>
>     # Get download parameters for threaded downloader
>     def set_download_parameters(self, params, relative_path, target_file, checksum_type=None,
>                                 checksum_value=None, bytes_range=None):
>         yum_ContentSource.set_download_parameters(self,
>                                                   params=params,
>                                                   relative_path=relative_path,
>                                                   target_file=target_file,
>                                                   checksum_type=checksum_type,
>                                                   checksum_value=checksum_value,
>                                                   bytes_range=bytes_range)
>         hostname, label = self._uln_auth.get_hostname(self.url)
>         params['urls'] = [self._uln_auth.url + "/XMLRPC/GET-REQ/" + label]



# diff /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py.orig /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py

418c418
<         # read the proxy configuration in /etc/rhn/rhn.conf
---
>         # read configuration from /etc/rhn/rhn.conf
426,452c426,427
<         # Get the global HTTP Proxy settings from DB or per-repo
<         # settings on /etc/rhn/spacewalk-repo-sync/zypper.conf
<         if CFG.http_proxy:
<             self.proxy_url, self.proxy_user, self.proxy_pass = get_proxy(self.url)
<             self.proxy_hostname = self.proxy_url
<         elif os.path.isfile(REPOSYNC_ZYPPER_CONF):
<             zypper_cfg = configparser.ConfigParser()
<             zypper_cfg.read_file(open(REPOSYNC_ZYPPER_CONF))
<             section_name = None
<
<             if zypper_cfg.has_section(self.name):
<                 section_name = self.name
<             elif zypper_cfg.has_section(channel_label):
<                 section_name = channel_label
<             elif zypper_cfg.has_section('main'):
<                 section_name = 'main'
<
<             if section_name:
<                 if zypper_cfg.has_option(section_name, option='proxy'):
<                     self.proxy_hostname = zypper_cfg.get(section_name, option='proxy')
<                     self.proxy_url = "http://%s" % self.proxy_hostname
<
<                 if zypper_cfg.has_option(section_name, 'proxy_username'):
<                     self.proxy_user = zypper_cfg.get(section_name, 'proxy_username')
<
<                 if zypper_cfg.has_option(section_name, 'proxy_password'):
<                     self.proxy_pass = zypper_cfg.get(section_name, 'proxy_password')
---
>         # load proxy configuration based on the url
>         self._load_proxy_settings(self.url)
470a446
>         # perform authentication if implemented
493a470,505
>     def _load_proxy_settings(self, url):
>         # read the proxy configuration in /etc/rhn/rhn.conf
>         comp = CFG.getComponent()
>         initCFG('server.satellite')
>
>         # Get the global HTTP Proxy settings from DB or per-repo
>         # settings on /etc/rhn/spacewalk-repo-sync/zypper.conf
>         if CFG.http_proxy:
>             self.proxy_url, self.proxy_user, self.proxy_pass = get_proxy(url)
>             self.proxy_hostname = self.proxy_url
>         elif os.path.isfile(REPOSYNC_ZYPPER_CONF):
>             zypper_cfg = configparser.ConfigParser()
>             zypper_cfg.read_file(open(REPOSYNC_ZYPPER_CONF))
>             section_name = None
>
>             if zypper_cfg.has_section(self.name):
>                 section_name = self.name
>             elif zypper_cfg.has_section(channel_label):
>                 section_name = channel_label
>             elif zypper_cfg.has_section('main'):
>                 section_name = 'main'
>
>             if section_name:
>                 if zypper_cfg.has_option(section_name, option='proxy'):
>                     self.proxy_hostname = zypper_cfg.get(section_name, option='proxy')
>                     self.proxy_url = "http://%s" % self.proxy_hostname
>
>                 if zypper_cfg.has_option(section_name, 'proxy_username'):
>                     self.proxy_user = zypper_cfg.get(section_name, 'proxy_username')
>
>                 if zypper_cfg.has_option(section_name, 'proxy_password'):
>                     self.proxy_pass = zypper_cfg.get(section_name, 'proxy_password')
>
>         # set config component back to original
>         initCFG(comp)
>
571c583
<         zypp_repo_url = self._prep_zypp_repo_url(self.url)
---
>         zypp_repo_url = self._prep_zypp_repo_url(self.url, uln_repo)
621c633
<     def _prep_zypp_repo_url(self, url):
---
>     def _prep_zypp_repo_url(self, url, uln_repo):
652c664
<         if self.authtoken:
---
>         if self.authtoken or uln_repo:



# diff /usr/lib/zypp/plugins/urlresolver/spacewalk-uln-resolver.orig /usr/lib/zypp/plugins/urlresolver/spacewalk-uln-resolver

1c1
< #!/usr/bin/python3
---
> #!/usr/bin/env python
42c42
<         hostname, label = self._uln_auth.get_hostname(headers['url'])
---
>         hostname, label = self._uln_auth.get_hostname(headers.pop('url'))
43a44,45
>         if headers:
>            url += "?{}".format(urllib.parse.urlencode(headers))


Please let me know if you need additional information, and thanks for continuing to investigate this issue.

**Comment by meaksh** [comment]
@scomcd thanks again for the feedback! :+1:

I looked at the diff you pasted and I think the culprit here is the wrong "shebang" at "/usr/lib/zypp/plugins/urlresolver/spacewalk-uln-resolver". It was my fault not to indicate that you can take that file but need to keep the original shebang. 

So, according to the diff you pasted for "/usr/lib/zypp/plugins/urlresolver/spacewalk-uln-resolver", the following part has to be reverted:

```diff
1c1
< #!/usr/bin/python3
> #!/usr/bin/env python
```

You need to adapt the shebang on that file to `#!/usr/bin/python3`, so the only changes you would see on your diff for that file is exactly these: https://github.com/uyuni-project/uyuni/pull/2830/files#diff-0ea8589dfb595a66c150b1e1e14c4da8558b56d2ce85c9c6b83964e94bbf02a3

After restoring the shebang, I think reposync would be able to run.

BTW, in order to be able to create custom ULN repositories via the webUI, you would need to wait until next Uyuni release, since there is no easy way for a hotfix patch for the Java side that you can test.

**Comment by scomcd** [comment]
Hi @meaksh,

Thanks very much for that, my apologies, I should have noticed the discrepancy when I ran the diff's.
Happy to confirm the Oracle ULN repository synchronisation is working now from the command line.
We will be eagerly awaiting the next update with the fix for the GUI ULN issue.
Many thanks to you and your team for the effort you have put in to solve this issue.

**Comment by meaksh** [comment]
These are great news!

Thank a lot @scomcd for the collaboration here and the efforts on testing this! We really appreciate! :+1:
