### ISSUE TITLE
Use case for web bootstrap to support Spacewalk agent to Uyuni salt bootstrap ability

### ISSUE THREAD

**Issue by EthanB11** [uyuni-project/uyuni#2378]
# Additional Information

When I migrated from Spacewalk to Uyuni a few months ago I had to use all bootstrap scripts modified to remove the spacewalk client tools before I could register. The web would not work properly due to package conflicts. Also had issue with uuid from cloned vms.

## Version of Uyuni Server and Proxy (if used)
Currently on 2020.01.

## Details about issue

I added the following section to the bootstrap script to remove the old client tools and to reset the uuid of the machine since some were created from cloning. This was at least required on the EL clients (RedHat/Fedora/Centos). I'm pretty sure I ran the below commands manually for SLES too.

````
#
# MIGRATION SECTION BEGIN
#
# Only in place for migration
#
echo "Removing spacwalk-client"
rpm -e rhn-client-tools rhn-setup python2-rhn-client-tools rhn-check yum-rhn-plugin python2-rhn-setup  python2-rhn-check rhnsd python2-rhncfg python2-osad rhncfg osad rhncfg-client rhncfg-acti
ons python2-spacewalk-usix spacewalk-usix rhncfg-actions rhncfg-client python2-rhncfg-client python2-rhncfg-actions jabberpy osad python2-osa-common

echo "Cleaning yum cache"
yum clean all

# Rebuild uuid since vms were cloned and causes issue with registration.
rm -f /etc/machine-id
rm -f /var/lib/dbus/machine-id
dbus-uuidgen --ensure
systemd-machine-id-setup

#
# MIGRATION SECTION END
#
````

**Comment by ewenf-uindy** [comment]
Wouldn't changing the UUID break network cards if it is hard coded into them?

**Comment by EthanB11** [comment]
No, it's a machine UUID that is generated on install of the OS.

**Comment by juliogonzalez** [comment]
For now I can tell that we are going to document the problem and the fix on the Release notes (for Uyuni 2020.07), until we see if we can generate a fix.

**Comment by ewenf-uindy** [comment]
To update things, after some of my experimentation and chaos the removal list needs to be

rpm -e  rhncfg-management python2-rhncfg-management rhn-client-tools rhn-setup python2-rhn-client-tools rhn-check yum-rhn-plugin python2-rhn-setup  python2-rhn-check rhnsd py
thon2-rhncfg python2-osad rhncfg osad rhncfg-client rhncfg-actions python2-spacewalk-usix spacewalk-usix rhncfg-actions rhncfg-client python2-rhncfg-client python2-rhncfg-act
ions jabberpy osad python2-osa-common

that should clear everything out.

The services also need to be addressed

systemctl stop osad
systemctl stop rhnsd.timer

and then removed, but I am not sure where they live to remove them.

**Comment by mcalmer** [comment]
When you register the system using salt, we have a state which remove the traditional client tool.
I am unsure if there are conflicts, we we first install salt when the traditional stack is still installed and later remove the packages.

As we renamed the packages we might care only about the new names and the original spacewalk names might stay installed.
This is something we should check.

**Comment by mcalmer** [comment]
I think this was fixed already. Please open a new issue in case this can be reproduced with  a current version of Uyuni. Thanks.
