### ISSUE TITLE
Errata import CentOS7

### ISSUE THREAD

**Issue by pdv-systeme-sachsen** [uyuni-project/uyuni#2386]
Hi,

as stated in https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-centos.html, there will be it possible to get errata for CentOS7.
But it seems, that an API call is not valid.

Regards, Thomas

# Additional Information

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` 

Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : uyuni-server-stable                             
Name               : Uyuni-Server-release                            
Version            : 2020.06-78.2.uyuni                              
Arch               : x86_64                                          
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3                                         
Installierte Größe : 1,4 KiB                                         
Installiert        : Ja (automatisch)                                
Status             : aktuell                                         
Quellpaket         : Uyuni-Server-release-2020.06-78.2.uyuni.src     
Zusammenfassung    : Uyuni Server    

## Details about issue
# error message

INFO: Server is running API version 23
INFO: API version 23 is supported
INFO: Authentication successful
INFO: User has administrator access to this server
INFO: Loading errata XML
INFO: Loading Red Hat OVAL XML
INFO: Getting server inventory
INFO: Checking for unpublished errata
Fault returned from XML RPC Server, fault code -1: redstone.xmlrpc.XmlRpcFault: Could not find method: listUnpublishedErrata in class: com.redhat.rhn.frontend.xmlrpc.errata.ErrataHandler with params: [com.redhat.rhn.domain.user.legacy.UserImpl]

**Comment by pdv-systeme-sachsen** [comment]
@moio:
What exactly should I do?
In Uyuni documentation I cannot find any hints regarding licensing...

Thomas

**Comment by moio** [comment]
@pdv-systeme-sachsen at the moment, no action is required from you. I am going to prepare a pull request with a patch to cefs and I will ask you to review it. I hope to be able to do that soon, in the next few days. Thanks!

**Comment by pdv-systeme-sachsen** [comment]
ok, thanks

**Comment by moio** [comment]
This is expected to work now with latest Uyuni and cefs script

**Comment by pdv-systeme-sachsen** [comment]
I can confirm this. Last week I've installed latest Uyuni Release at one of our customers and it works as expected. Many Thanks for the great work. Does somebody know wether and when this will word for ubuntu too?

Regards, Thomas

**Comment by mcalmer** [comment]
closing

> Does somebody know wether and when this will word for ubuntu too?

Let's see if sombody comes with some code :-)
