### ISSUE TITLE
CentOS 8 unable to patch minions from Uyuni

### ISSUE THREAD

**Issue by an0nz** [uyuni-project/uyuni#2393]
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.06-78.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2020.06-78.2.uyuni.src

When applying patches or updates to CentOS 8 servers the below error is returned.

The issue seems to be related to this [commit](https://github.com/uyuni-project/uyuni/commit/e92811e668ff8f5a02ea8cda18357a7eb53aa695) as the fault can be resolved by changing line 23 in susemanager-utils/susemanager-sls/salt/channels/channels.repo to 
`{%- if grains['osmajorrelease'] >= 8 and args.get('cloned_nonmodular',false) %}`

None of my CentOS 8 servers return cloned_nonmodular from `salt-call pillar.get channels` which is likely why the issue is occurring. I am unsure if they should have that pillar or if it only appears under certain criteria, either way setting a default jinja value resolves the fault I just do not know if this is the correct permanent fix or not.

**Failed Package state**
```
{
   "file_|-mgrchannels_susemanagerplugin_dnf_|-/usr/lib/python3.6/site-packages/dnf-plugins/susemanagerplugin.py_|-managed":{
      "changes":{
      },
      "comment":"File /usr/lib/python3.6/site-packages/dnf-plugins/susemanagerplugin.py is in the correct state",
      "name":"/usr/lib/python3.6/site-packages/dnf-plugins/susemanagerplugin.py",
      "result":true,
      "__sls__":"channels",
      "__run_num__":0.0,
      "start_time":"14:34:18.789359",
      "duration":696.512,
      "__id__":"mgrchannels_susemanagerplugin_dnf"
   },
   "file_|-mgrchannels_susemanagerplugin_conf_dnf_|-/etc/dnf/plugins/susemanagerplugin.conf_|-managed":{
      "changes":{
      },
      "comment":"File /etc/dnf/plugins/susemanagerplugin.conf is in the correct state",
      "name":"/etc/dnf/plugins/susemanagerplugin.conf",
      "result":true,
      "__sls__":"channels",
      "__run_num__":1.0,
      "start_time":"14:34:19.486378",
      "duration":56.619,
      "__id__":"mgrchannels_susemanagerplugin_conf_dnf"
   },
   "file_|-mgrchannels_repo_|-/etc/yum.repos.d/susemanager:channels.repo_|-managed":{
      "changes":{

      },
      "comment":"Unable to manage file: Jinja variable 'dict object' has no attribute 'cloned_nonmodular'",
      "name":"/etc/yum.repos.d/susemanager:channels.repo",
      "result":false,
      "__sls__":"channels",
      "__run_num__":2.0,
      "start_time":"14:34:19.545233",
      "duration":138.281,
      "__id__":"mgrchannels_repo"
   },
   "cmd_|-mgrchannels_dnf_clean_all_|-/usr/bin/dnf clean all_|-run":{
      "changes":{
      },
      "result":false,
      "duration":0.021,
      "start_time":"14:34:19.687375",
      "comment":"One or more requisite failed: channels.mgrchannels_repo",
      "__run_num__":3.0,
      "__sls__":"channels"
   },
   "pkg_|-mgr_regular_patches_|-mgr_regular_patches_|-patch_installed":{
      "changes":{
      },
      "result":false,
      "duration":0.013,
      "start_time":"14:34:29.232482",
      "comment":"One or more requisite failed: channels.mgrchannels_repo",
      "__run_num__":4.0,
      "__sls__":"packages.patchinstall"
   }
}
```

**Comment by juliogonzalez** [comment]
@cbbayburt can you have a look a this tomorrow? Is this something that is going to be fixed when we release 2020.07?

**Comment by cbbayburt** [comment]
> I am unsure if they should have that pillar or if it only appears under certain criteria ..

@an0nz yes, the `cloned_nonmodular` pillar should be available in any case, so I believe this is a symptom of some other problem and I'm pretty sure if that pillar is missing, some others would be too.

What is your output from `salt-call pillar.get channels`?

**Comment by an0nz** [comment]
I have dug a bit deeper and my installation has only partially updated to 2020.06 with some packages stuck on 2020.01

Removing the Uyuni repo from Zypper and re-adding it as per the current versions install guide then using zypper dist-upgrade to change the supplier has resolved my problem
Our server has been updated from 4.0.2 through each subsequent release and some packages were stuck on 2020.01 whilst everything else was 2020.06, I am surprised that was the only issue we were experiencing.

@cbbayburt thanks for confirming the correct functionality we can close this issue.
