### ISSUE TITLE
Bootstrap not installing correctly on OL6 and Centos6

### ISSUE THREAD

**Issue by ewenf-uindy** [uyuni-project/uyuni#2420]
When I try to install the bootstrap client on Centos6 and OL6 boxes, the bootstrap fails and no client files are installed.  The Centos machine is at version 6.5 and the OL6 box is at 6.4.  It is using the Uyuni self signed cert.

**Version of Server**
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.06-78.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.06-78.2.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

**Error Message Recieved when installing bootstrap.sh**
```
UPDATING RHN_REGISTER/UP2DATE CONFIGURATION FILES
-------------------------------------------------
* downloading necessary files
client_config_update.py...
2020-07-14 09:52:25 URL:
http://uyuni.test.uindy.edu/pub/bootstrap/client_config_update.py
[6456/6456] -> "client_config_update.py" [1]
FINISHED --2020-07-14 09:52:25--
Downloaded: 1 files, 6.3K in 0s (12025 GB/s)
client-config-overrides.txt...
2020-07-14 09:52:25 URL:
http://uyuni.test.uindy.edu/pub/bootstrap/client-config-overrides.txt
[629/629] -> "client-config-overrides.txt" [1]
FINISHED --2020-07-14 09:52:25--
Downloaded: 1 files, 629 in 0s (1172 GB/s)

PREPARE GPG KEYS AND CORPORATE PUBLIC CA CERT
-------------------------------------------------

* importing organizational GPG keys
2020-07-14 09:52:25 URL:
http://uyuni.test.uindy.edu/pub/uyuni-gpg-pubkey-0d20833e.key [1126/1126]
-> "uyuni-gpg-pubkey-0d20833e.key" [1]
FINISHED --2020-07-14 09:52:25--
Downloaded: 1 files, 1.1K in 0s (2097 GB/s)

* configured not to use SSL: don't install corporate public CA cert

CLEANING UP OLD SUSE MANAGER REPOSITORIES
-------------------------------------------------

CHECKING THE REGISTRATION STACK
-------------------------------------------------
* check for necessary packages being installed...
* client codebase is oracle-6
package salt is not installed
package salt-minion is not installed
WARNING: cannot verify uyuni.test.uindy.edu’s certificate, issued by
“/C=US/ST=IN/L=Indy/O=Uindy/OU=Uindy/CN=uyuni.test.uindy.edu”:
Unable to locally verify the issuer’s authority.
2020-07-14 09:52:25 URL:
https://uyuni.test.uindy.edu/pub/repositories/oracle/6/bootstrap/repodata/repomd.xml
[2618/2618] -> "repomd.xml" [1]
FINISHED --2020-07-14 09:52:25--
Downloaded: 1 files, 2.6K in 0s (4876 GB/s)
adding client software repository at
https://uyuni.test.uindy.edu/pub/repositories/oracle/6/bootstrap
* going to install missing packages...
https://uyuni.test.uindy.edu/pub/repositories/oracle/6/bootstrap/repodata/repomd.xml:
[Errno 14] problem making ssl connection
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository:
susemanager:bootstrap. Please verify its path and try again
package salt is not installed
ERROR: Failed to install all missing packages.
```
**Bootstrap.sh**
```
ACTIVATION_KEYS=1-5edc4190f681b87e84e544b53dae84dd
ORG_GPG_KEY=

# can be edited, but probably correct:
CLIENT_OVERRIDES=client-config-overrides.txt
HOSTNAME=uyuni.test.uindy.edu

ORG_CA_CERT=rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm
ORG_CA_CERT_IS_RPM_YN=1

USING_SSL=1
USING_GPG=1

REGISTER_THIS_BOX=1

ALLOW_CONFIG_ACTIONS=1
ALLOW_REMOTE_COMMANDS=1

# this variable is only relevant for traditional clients and is ignored on salt minions
FULLY_UPDATE_THIS_BOX=0

# Set if you want to specify profilename for client systems.
# NOTE: Make sure it's set correctly if any external command is used.
#
# ex. PROFILENAME="foo.example.com"  # For specific client system
#     PROFILENAME=`hostname -s`      # Short hostname
#     PROFILENAME=`hostname -f`      # FQDN
PROFILENAME=""   # Empty by default to let it be set automatically.

# After registration, before updating the system (or at least the installer)
# disable all repos not provided by SUSE Manager.
DISABLE_LOCAL_REPOS=1

# Disable yasts automatic online update feature in case it is enabled
# on the client. Leaving automatic online update enabled, the client would
# continue to update himself independently from SUSE Manager requests.
DISABLE_YAST_AUTOMATIC_ONLINE_UPDATE=1

# SUSE Manager Specific settings:
#
# - Alternate location of the client tool repos providing the zypp-plugin-spacewalk
# and packges required for registration. Unless they are already installed on the
# client this repo is expected to provide them for SLE-10/SLE-11 based clients:
#   ${CLIENT_REPOS_ROOT}/sle/VERSION/PATCHLEVEL
# If empty, the SUSE Manager repositories provided at https://${HOSTNAME}/pub/repositories
# are used.
CLIENT_REPOS_ROOT=
```
**client-config**
```
enableProxy=0
enableProxyAuth=0
httpProxy=
noSSLServerURL=http://uyuni.test.uindy.edu/XMLRPC
proxyPassword=
proxyUser=
serverURL=https://uyuni.test.uindy.edu/XMLRPC
sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
useGPG=1
```

**Comment by juliogonzalez** [comment]
I am unable to reproduce this on CentOS 6.10 (which is the only CentOS6 version supported, even by CentOS itself), installed from `CentOS-6.10-x86_64-minimal.iso`

First time I run the bootstrap script (generated to bootstrap using salt), I get:

![image](https://user-images.githubusercontent.com/4226070/87665811-cd692380-c767-11ea-9033-26e14f906ed2.png)

Which is normal and expected.

If I run `/usr/bin/update-ca-trust force-enable` and then rerun the bootstrap script, all works as it should.

For CentOS6.5, installed using `CentOS-6.5-x86_64-minimal.iso`, the script just does not work as it tries to download `client_config_update.py` using HTTPS.

![image](https://user-images.githubusercontent.com/4226070/87667588-ec1ce980-c76a-11ea-9992-ae89a8948bda.png)

And if I disable SSL by changing `USING_SSL=1` to `USING_SSL=0`, then the bootstrap fails as it can't download the packages from the repository (as `https` is used).

Something tells me that things were changed on the bootstrap scripts that broke old CentOS6 versions. Keep in mind CentOS 6.5 is EoL and unmaintained since November 2014, so I strongly suggest you first update to 6.10 and then onboard.

**Comment by paususe** [comment]
I will invoke @mcalmer here :-)

**Comment by ewenf-uindy** [comment]
I do not get that.  I updated the box to 6.10, then installed the
epel-release and got
* downloading necessary files
  client_config_update.py...
WARNING: cannot verify uyuni.test.uindy.edu’s certificate, issued by
“/C=US/ST=IN/L=Indy/O=Uindy/OU=Uindy/CN=uyuni.test.uindy.edu”:
  Unable to locally verify the issuer’s authority.
2020-07-16 08:59:16 URL:
https://uyuni.test.uindy.edu/pub/bootstrap/client_config_update.py
[6456/6456] -> "client_config_update.py" [1]
FINISHED --2020-07-16 08:59:16--
Downloaded: 1 files, 6.3K in 0s (12025 GB/s)
  client-config-overrides.txt...
WARNING: cannot verify uyuni.test.uindy.edu’s certificate, issued by
“/C=US/ST=IN/L=Indy/O=Uindy/OU=Uindy/CN=uyuni.test.uindy.edu”:
  Unable to locally verify the issuer’s authority.
2020-07-16 08:59:16 URL:
https://uyuni.test.uindy.edu/pub/bootstrap/client-config-overrides.txt
[629/629] -> "client-config-overrides.txt" [1]
FINISHED --2020-07-16 08:59:16--
Downloaded: 1 files, 629 in 0s (1172 GB/s)

PREPARE GPG KEYS AND CORPORATE PUBLIC CA CERT
-------------------------------------------------

* importing organizational GPG keys
WARNING: cannot verify uyuni.test.uindy.edu’s certificate, issued by
“/C=US/ST=IN/L=Indy/O=Uindy/OU=Uindy/CN=uyuni.test.uindy.edu”:
  Unable to locally verify the issuer’s authority.
2020-07-16 08:59:16 URL:
https://uyuni.test.uindy.edu/pub/uyuni-gpg-pubkey-0d20833e.key [1126/1126]
-> "uyuni-gpg-pubkey-0d20833e.key" [1]
FINISHED --2020-07-16 08:59:16--
Downloaded: 1 files, 1.1K in 0s (2097 GB/s)

* attempting to install corporate public CA cert
ERROR: Dynamic CA-Trust > Updates are disabled. Enable Dynamic CA-Trust
Updates with '/usr/bin/update-ca-trust force-enable'
Finally, restart the onboarding sequence.

All i changed was the activation key and the gpg key in the bootstrap.
Updating all my cent6 boxes up to 6.10 is a no go due to software reasons.
WWe are in the process of changing them out, but the OL6 boxes will be
hanging around at least another year.
---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.

**Comment by ewenf-uindy** [comment]
Running the bootstrap for OL6 gets this.  It appears that salt needs to be
installed separately?  On the Centos6 front doing the
/usr/bin/update-ca-trust force-enable allowed for the install to complete
successfully.

UPDATING RHN_REGISTER/UP2DATE CONFIGURATION FILES
-------------------------------------------------
* downloading necessary files
  client_config_update.py...
WARNING: cannot verify uyuni.test.uindy.edu’s certificate, issued by
“/C=US/ST=IN/L=Indy/O=Uindy/OU=Uindy/CN=uyuni.test.uindy.edu”:
  Unable to locally verify the issuer’s authority.
2020-07-16 14:29:32 URL:
https://uyuni.test.uindy.edu/pub/bootstrap/client_config_update.py
[6456/6456] -> "client_config_update.py" [1]
FINISHED --2020-07-16 14:29:32--
Downloaded: 1 files, 6.3K in 0s (12025 GB/s)
  client-config-overrides.txt...
WARNING: cannot verify uyuni.test.uindy.edu’s certificate, issued by
“/C=US/ST=IN/L=Indy/O=Uindy/OU=Uindy/CN=uyuni.test.uindy.edu”:
  Unable to locally verify the issuer’s authority.
2020-07-16 14:29:32 URL:
https://uyuni.test.uindy.edu/pub/bootstrap/client-config-overrides.txt
[629/629] -> "client-config-overrides.txt" [1]
FINISHED --2020-07-16 14:29:32--
Downloaded: 1 files, 629 in 0s (1172 GB/s)

PREPARE GPG KEYS AND CORPORATE PUBLIC CA CERT
-------------------------------------------------
* no organizational GPG keys to import

* attempting to install corporate public CA cert
WARNING: cannot verify uyuni.test.uindy.edu’s certificate, issued by
“/C=US/ST=IN/L=Indy/O=Uindy/OU=Uindy/CN=uyuni.test.uindy.edu”:
  Unable to locally verify the issuer’s authority.
2020-07-16 14:29:32 URL:
https://uyuni.test.uindy.edu/pub/rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm
[13559/13559] -> "rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm" [1]
FINISHED --2020-07-16 14:29:32--
Downloaded: 1 files, 13K in 0s (25256 GB/s)
Preparing...                ###########################################
[100%]
   1:rhn-org-trusted-ssl-cer###########################################
[100%]

CLEANING UP OLD SUSE MANAGER REPOSITORIES
-------------------------------------------------

CHECKING THE REGISTRATION STACK
-------------------------------------------------
* check for necessary packages being installed...
* client codebase is oracle-6
package salt is not installed
package salt-minion is not installed
2020-07-16 14:29:33 URL:
https://uyuni.test.uindy.edu/pub/repositories/oracle/6/bootstrap/repodata/repomd.xml
[2618/2618] -> "repomd.xml" [1]
FINISHED --2020-07-16 14:29:33--
Downloaded: 1 files, 2.6K in 0s (4876 GB/s)
 adding client software repository at
https://uyuni.test.uindy.edu/pub/repositories/oracle/6/bootstrap
* going to install missing packages...
Loaded plugins: ulninfo
Setting up Install Process
susemanager:bootstrap

 | 2.6 kB     00:00
susemanager:bootstrap/primary_db

|  21 kB     00:00
No package salt available.
No package salt-minion available.
Error: Nothing to do
package salt is not installed
ERROR: Failed to install all missing packages.

---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.

**Comment by ewenf-uindy** [comment]
Centos6 only works on a fully updated box.  If not updated it reports that
it needs salt as well.

---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.

**Comment by mcalmer** [comment]
Hmm, salt should be available in the bootstrap repo. Did you add `oraclelinux6-uyuni-client` with spacewalk-common-channels?

**Comment by ewenf-uindy** [comment]
Yes.  I added both the centos6 and the ol6 channels.  I did not add the
devel but added the primary.

---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.

**Comment by juliogonzalez** [comment]
Did you run the bootstrap repository creation for both OL6 and CentOS6 after adding the channels?

**Comment by ewenf-uindy** [comment]
I've rebuilt the whole box since I logged this, so I can't tell you how it
will behave now.  Hust close this one and we'll see if it works better on
2020.7

---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.

**Comment by mcalmer** [comment]
@ewenf-uindy how is it going now with a newer version of uyuni?

**Comment by ewenf-uindy** [comment]
I have not had a chance to test this yet.  I will get back to you as soon
as possible.

---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.
