### ISSUE TITLE
software package search indexer not working after 'rhn-search cleanindex'

### ISSUE THREAD

**Issue by sejo23** [uyuni-project/uyuni#2436]
In GUI Sofftware -> Package Search are "No packages" for any searches.
"rhn-search cleanindex" dosn't help.
"spacecmd package_search" works fine.

# Additional Information

## Version of Uyuni Server and Proxy (if used)
2020.06-78.2.uyuni

## Details about issue
In GUI Sofftware -> Package Search are "No packages" for any searches.
In /var/log/rhn/search/rhn_search.log are errors:
ERROR - no segments* file found in org.apache.lucene.store.FSDirectory@/var/lib/rhn/search/indexes/package: files:

"rhn-search cleanindex" works without errors and deletes directories under /var/lib/rhn/search/indexes
But only in the directories  "errata", "hwdevice", "server", "serverCustomInfo", "snapshotTag" and "xccdfIdent" are indexes rebuildt. The directory "packages" stays empty.

In /var/log/rhn/search/rhn_search*.log are entires for all indexers except the package-indexer. No errors are logged.

**Comment by moio** [comment]
Can you please check `journalctl -u rhn-search` when you have reproduced the issue (naturally without the patch in #2513)?

Could it be you see an `OutOfMemoryException` in there?

Thanks for reporting!

**Comment by sejo23** [comment]
Good advice - I searched in wrong place!  In journal are OutOfMemoryExceptions:

Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]: [QuartzScheduler_Worker-8] ERROR org.quartz.core.JobRunShell - Job updateIndex.packages threw an unhandled Exception:
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]: java.lang.OutOfMemoryError: Java heap space
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]: [QuartzScheduler_Worker-8] ERROR org.quartz.core.ErrorLogger - Job (updateIndex.packages threw an exception.
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]: org.quartz.JobExecutionException: com.redhat.satellite.search.index.IndexingException: org.apache.lucene.store.LockObtainFailedException: Lock o>
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at com.redhat.satellite.search.scheduler.tasks.GenericIndexTask.execute(GenericIndexTask.java:94)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]: Caused by: com.redhat.satellite.search.index.IndexingException: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: Simple>
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at com.redhat.satellite.search.index.IndexManager.createIndex(IndexManager.java:247)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at com.redhat.satellite.search.scheduler.tasks.GenericIndexTask.execute(GenericIndexTask.java:65)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         ... 2 more
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]: Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: SimpleFSLock@/var/lib/rhn/search/indexes/hwdevice/write.lock
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at org.apache.lucene.store.Lock.obtain(Lock.java:85)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at org.apache.lucene.index.IndexWriter.init(IndexWriter.java:1070)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at org.apache.lucene.index.IndexWriter.init(IndexWriter.java:1050)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:765)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at com.redhat.satellite.search.index.IndexManager.getIndexWriter(IndexManager.java:391)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at com.redhat.satellite.search.index.IndexManager.createIndex(IndexManager.java:229)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         ... 3 more
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.OutOfMemoryError: Java heap space]
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]:         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Aug 20 14:31:46 rz-mg-lin301 rhn-search[4301]: Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by moio** [comment]
OK, in that case the advice would be to give the search daemon a bit more headroom, see: https://www.uyuni-project.org/uyuni-docs/uyuni/large-deployments/tuning.html#rhn-search-java-maxmemory

Now this experience shows the search daemon needs more memory not only when the number of clients increases, but also when the number of managed packages increases. So at the very minimum, the docs should reflect that. We might want to increase the default for all users as well.

@mcalmer: do you see it as the norm or the exception that users have more than 10k managed packages?

**Comment by mcalmer** [comment]
> Now this experience shows the search daemon needs more memory not only when the number of clients increases, but also when the number of managed packages increases. So at the very minimum, the docs should reflect that. We might want to increase the default for all users as well.
> 
> @mcalmer: do you see it as the norm or the exception that users have more than 10k managed packages?

For "uyuni" this is pretty normal as just mirroring openSUSE will give you &gt;30k packages.

While checking the docs and the reality it seems something changed in the config and is not reflected in the docs.
When we dropped the tanukiwrapper that default config changed

**Comment by mcalmer** [comment]
Btw: current max memory is 96 and the tuning guide say 512 as default.
Seems we need to do some work here.

**Comment by moio** [comment]
Right, #2643 opened
