### ISSUE TITLE
Tool like mgr-update-pkg-extra-tags to update *all* headers

### ISSUE THREAD

**Issue by rpasche** [uyuni-project/uyuni#2442]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.01-75.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 4.0-400.41.1.uyunimaster installed)
Source package : Uyuni-Server-release-2020.01-75.3.uyuni.src
Summary        : Uyuni Server 2020.01

## Details about issue
I just tried to install a software on a Debian system, which failed because of unfulfilled "pre-dependencies". These "Pre-Depends" were not listed within the `Packages` file. But I found other packages that have this header included.
Therefore, I deleted the package from Uyuni server and re-synced. This fixed the issue. The "Pre-Depends" header is now correctly included.

But chances are, that there might be more such packages already "parsed" that might also be missing some headers, that are currently ignored by the `mgr-update-pkg-extra-tags` tool. So requesting a fix to this tool to include an option to reparse *all* headers of a package.

Kind regards

**Comment by rpasche** [comment]
I just had again an issue with a package, where some headers are missing. In this case, it was `e2fsprogs=1.44.5-1+deb10u2`. See the versions and package information currently available. The information for `deb10u1` and `deb10u3` look fine. It's only `deb10u2` that is missing this information (for some reason). I think I can fix this by deleting this package from Uyuni and resync....but would be of interest, how this happened.

```
root@uyuni-apt-debug:~# apt-cache show e2fsprogs
Package: e2fsprogs
Version: 1.44.5-1+deb10u3
Architecture: amd64
Maintainer: Theodore Y. Ts'o <tytso@mit.edu>
Installed-Size: 1416
Suggests: gpart, parted, fuse2fs, e2fsck-static
Recommends: e2fsprogs-l10n
Pre-Depends: libblkid1 (>= 2.17.2), libc6 (>= 2.14), libcom-err2 (>= 1.43.9), libext2fs2 (= 1.44.5-1+deb10u3), libss2 (>= 1.38), libuuid1 (>= 2.16)
Filename: buster_main_main/getPackage/e2fsprogs_1.44.5-1+deb10u3.amd64-deb.deb
Size: 575592
SHA256: 3e6f9134334e16b818d81c84bbe3173fef55e4a1ea2b092b2482a2b4f089891c
Section: admin
Homepage: http://e2fsprogs.sourceforge.net
Priority: required
Important: yes
Multi-Arch: foreign
Description: ext2/ext3/ext4 file system utilities
 The ext2, ext3 and ext4 file systems are successors of the original ext
 ("extended") file system. They are the main file system types used for
 hard disks on Debian and other Linux systems.
 .
 This package contains programs for creating, checking, and maintaining
 ext2/3/4-based file systems.  It also includes the "badblocks" program,
 which can be used to scan for bad blocks on a disk or other storage device.
Description-md5: 92d0fdf684262bbfa702eaea3f50b97e

Package: e2fsprogs
Version: 1.44.5-1+deb10u2
Architecture: amd64
Maintainer: Theodore Y. Ts'o <tytso@mit.edu>
Installed-Size: 1416
Suggests: gpart, parted, fuse2fs, e2fsck-static
Recommends: e2fsprogs-l10n
Filename: buster_security_main/getPackage/e2fsprogs_1.44.5-1+deb10u2.amd64-deb.deb
Size: 575852
SHA256: 7b1454a6bb5927a2c262588904d507aaf9ba245b4f63f673b69005b7fd65721b
Section: admin
Homepage: http://e2fsprogs.sourceforge.net
Priority: required
Important: yes
Multi-Arch: foreign
Description: ext2/ext3/ext4 file system utilities
 The ext2, ext3 and ext4 file systems are successors of the original ext
 ("extended") file system. They are the main file system types used for
 hard disks on Debian and other Linux systems.
 .
 This package contains programs for creating, checking, and maintaining
 ext2/3/4-based file systems.  It also includes the "badblocks" program,
 which can be used to scan for bad blocks on a disk or other storage device.
Description-md5: 92d0fdf684262bbfa702eaea3f50b97e

Package: e2fsprogs
Status: install ok installed
Priority: required
Section: admin
Installed-Size: 1416
Maintainer: Theodore Y. Ts'o <tytso@mit.edu>
Architecture: amd64
Multi-Arch: foreign
Version: 1.44.5-1+deb10u1
Pre-Depends: libblkid1 (>= 2.17.2), libc6 (>= 2.14), libcom-err2 (>= 1.43.9), libext2fs2 (= 1.44.5-1+deb10u1), libss2 (>= 1.38), libuuid1 (>= 2.16)
Recommends: e2fsprogs-l10n
Suggests: gpart, parted, fuse2fs, e2fsck-static
Conffiles:
 /etc/mke2fs.conf 72b349d890a9b5cca06c7804cd0c8d1d
Description: ext2/ext3/ext4 file system utilities
 The ext2, ext3 and ext4 file systems are successors of the original ext
 ("extended") file system. They are the main file system types used for
 hard disks on Debian and other Linux systems.
 .
 This package contains programs for creating, checking, and maintaining
 ext2/3/4-based file systems.  It also includes the "badblocks" program,
 which can be used to scan for bad blocks on a disk or other storage device.
Description-md5: 92d0fdf684262bbfa702eaea3f50b97e
Homepage: http://e2fsprogs.sourceforge.net
Important: yes

root@uyuni-apt-debug:~#
```

And because package `deb10u2` is missing headers, trying to install it results in dependency errors.


```
root@uyuni-apt-debug:~# apt-get install e2fsprogs=1.44.5-1+deb10u2
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  gpart parted fuse2fs e2fsck-static
Recommended packages:
  e2fsprogs-l10n
The following packages will be upgraded:
  e2fsprogs
1 upgraded, 0 newly installed, 0 to remove and 146 not upgraded.
Need to get 576 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://uyuni.swr.ard:443/rhn/manager/download buster_security_main/main amd64 e2fsprogs amd64 1.44.5-1+deb10u2 [576 kB]
Fetched 576 kB in 0s (5,690 kB/s)
dpkg: regarding .../e2fsprogs_1.44.5-1+deb10u2_amd64.deb containing e2fsprogs, pre-dependency problem:
 e2fsprogs pre-depends on libext2fs2 (= 1.44.5-1+deb10u2)
  libext2fs2:amd64 is installed, but is version 1.44.5-1+deb10u1.

dpkg: error processing archive /var/cache/apt/archives/e2fsprogs_1.44.5-1+deb10u2_amd64.deb (--unpack):
 pre-dependency problem - not installing e2fsprogs
Errors were encountered while processing:
 /var/cache/apt/archives/e2fsprogs_1.44.5-1+deb10u2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@uyuni-apt-debug:~#
```

**Comment by rpasche** [comment]
As thought, removing the package and resynching it fixed the problem.

**Comment by paususe** [comment]
This was fixed a long time ago. Closing the issue.

**Comment by rpasche** [comment]
What is the name of that tool? I currently only know the way of fully deleting the package from uyuni and trigger a synchronization of the affected repos.

Thanks
Robert

⁣sent from my mobile device​


-------- Originale Nachricht --------
Von: Pau Garcia Quiles ***@***.***>
Gesendet: Fri Mar 12 14:18:51 GMT+01:00 2021
An: uyuni-project/uyuni ***@***.***>
Cc: Robert Paschedag ***@***.***>, Author ***@***.***>
Betreff: Re: [uyuni-project/uyuni] Tool like mgr-update-pkg-extra-tags to update *all* headers (#2442)

This was fixed a long time ago. Closing the issue.
