### ISSUE TITLE
smt-mirror: Checksum mismatch

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#2448]
Hello,

my local smt can not mirror the official uyuni repos:

 * uyuni-server-stable (https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/):
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/bind-formula-0.1.1573049925.b509ada-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/branch-network-formula-0.1.1583842676.2fc2fa6-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/caasp-management-node-formula-4.1.1-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/caasp-management-settings-formula-4.1.1-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/cpu-mitigations-formula-0.1-2.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/dhcpd-formula-0.1.1583829431.db6edda-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/grafana-formula-0.2.1-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/image-sync-formula-0.1.1588156049.952b58d-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/mgr-push-4.1.1-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/nutch-core-1.0.1-5.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/perl-Satcon-4.1.1-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/postgresql-jdbc-42.2.10-3.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/prometheus-exporters-formula-0.6-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/prometheus-formula-0.2.1-2.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/pxe-formula-0.1.1586937953.e458f5c-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/python3-gzipstream-4.1.1-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/python3-mgr-push-4.1.1-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/python3-susemanager-retail-1.0.1583842676.2fc2fa6-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/python3-urlgrabber-3.10.2.1py2_3-4.3.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/quartz-2.3.0-2.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/redstone-xmlrpc-1.1_20071120-0.10.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/salt-netapi-client-0.17.0-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/spacewalk-reports-4.1.2-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/spacewalk-search-4.1.2-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/spacewalk-setup-4.1.5-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/spacewalk-setup-jabberd-4.1.1-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/struts-1.2.9-162.34.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/supportutils-plugin-susemanager-4.1.3-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/susemanager-retail-tools-1.0.1583842676.2fc2fa6-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/system-lock-formula-0.2-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/uyuni-build-keys-2020.06-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/uyuni-build-keys-web-2020.06-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/virtual-host-gatherer-1.0.20-2.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/virtual-host-gatherer-Kubernetes-1.0.20-2.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/virtual-host-gatherer-VMware-1.0.20-2.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/virtual-host-gatherer-libcloud-1.0.20-2.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/virtualization-host-formula-0.4-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/noarch/yomi-formula-0.0.1+git.1587986719.9a9097a-1.1.uyuni.noarch.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/x86_64/golang-github-wrouesnel-postgres_exporter-0.4.7-4.3.uyuni.x86_64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/x86_64/openvpn-formula-0.1-2.1.uyuni.x86_64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/x86_64/py26-compat-msgpack-python-0.4.6-24.1.uyuni.x86_64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/x86_64/py26-compat-tornado-4.2.1-15.1.uyuni.x86_64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/x86_64/smdba-1.7.4-0.1.1.uyuni.x86_64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/x86_64/susemanager-tftpsync-4.1.3-1.1.uyuni.x86_64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/x86_64/uyuni-base-common-4.1.1-1.1.uyuni.x86_64.rpm': Checksum mismatch'
    - E '/srv/www/htdocs/repo/RPMMD/uyuni-server-stable/x86_64/uyuni-base-server-4.1.1-1.1.uyuni.x86_64.rpm': Checksum mismatch'

Is it a problem inside the official repository? have anyone the same problems?

Regards
Peter

**Comment by scomcd** [comment]
Hi Peter,
I'm not seeing the checksum error, but when trying to upgrade our Uyuni 2020.06 to 2020.07, I am receiving a few 
Digest verification errors before the upgrade process aborts.

Warning: Digest verification failed for file 'bind-formula-0.1.1573049925.b509ada-1.1.uyuni.noarch.rpm'
[/var/tmp/AP_0xv3j5up/noarch/bind-formula-0.1.1573049925.b509ada-1.1.uyuni.noarch.rpm]

Warning: Digest verification failed for file 'dhcpd-formula-0.1.1583829431.db6edda-1.1.uyuni.noarch.rpm'
[/var/tmp/AP_0xkHiSbQ/noarch/dhcpd-formula-0.1.1583829431.db6edda-1.1.uyuni.noarch.rpm]

Warning: Digest verification failed for file 'uyuni-build-keys-web-2020.06-1.1.uyuni.noarch.rpm'
[/var/tmp/AP_0x6OvtnK/noarch/uyuni-build-keys-web-2020.06-1.1.uyuni.noarch.rpm]

**Comment by sejo23** [comment]
Same problem when trying to  upgrade.:

Warning: Digest verification failed for file 'caasp-management-settings-formula-4.1.1-1.1.uyuni.noarch.rpm'
[/var/tmp/AP_0xqIW2qr/noarch/caasp-management-settings-formula-4.1.1-1.1.uyuni.noarch.rpm]

  expected b9339bfe2665337a48672dd26a5ea268c1bb6a60294eeb5c75b23dc6bc3eb226
  but got  5404312f8bc2433ac94ac9243b028014519bbb584c587595e90a48ef84f02eda

**Comment by sejo23** [comment]
For reason and work around see https://www.talkend.net/post/27638.html

**Comment by mcalmer** [comment]
I think we had some problems with the mirrors. Should be fixed in the meanwhile.
