### ISSUE TITLE
Wrong permission on file /etc/sysconfig/rhn/systemid after re-registration of proxy using rhnreg_ks utility

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#2471]
```
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.2 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2020.07-86.3.uyuni
```

After the upgrade of the Uyuni proxies from 2020.06 to 2020.07, the final step as described here https://www.uyuni-project.org/uyuni-docs/uyuni/upgrade/proxy-uyuni.html is to re-register the Uyuni proxies:

`Re-register with the reactivation key using the rhnreg_ks command-line utility. The system will be re-registered with the same id, history, and groups.`

However, this re-registration modify the permission of the file `/etc/sysconfig/rhn/systemid` which make it inoperable for the clients using this proxy.

Step to reproduce:

```
# ls -al /etc/sysconfig/rhn/systemid
-rw-r----- 1 root www 1347 Aug  3 17:55 /etc/sysconfig/rhn/systemid
# rhnreg_ks --activationkey=re-1-4bfdbcc542d271e35e546e8a37f1e98e --force
#  
# ls -al /etc/sysconfig/rhn/systemid
-rw------- 1 root root 1337 Aug  3 18:02 /etc/sysconfig/rhn/systemid
```

To solve the issue, just modify back the permissions as follow:

```
# chown root:www /etc/sysconfig/rhn/systemid && chmod 640 /etc/sysconfig/rhn/systemid
```

A restart of the proxy seems to be necessary (`spacewalk-proxy restart`) 

On the client, you will see errors of the type`[Errno 14] HTTP Error 500: Internal Server Error` when trying to update the packages.

On the proxy, the following errors are seen on the Apache error log file `/var/log/apache2/error.log`:

```
[Mon Aug 03 17:57:25.526401 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324] Exception Handler Information
[Mon Aug 03 17:57:25.526428 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324] Traceback (most recent call last):
[Mon Aug 03 17:57:25.526456 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]   File "/usr/share/rhn/proxy/apacheServer.py", line 62, in __call__
[Mon Aug 03 17:57:25.526485 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]     ret = f(req)
[Mon Aug 03 17:57:25.526512 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]   File "/usr/share/rhn/proxy/apacheHandler.py", line 361, in handler
[Mon Aug 03 17:57:25.526539 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]     handlerObj = rhnBroker.BrokerHandler(req)
[Mon Aug 03 17:57:25.526562 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]   File "/usr/share/rhn/proxy/broker/rhnBroker.py", line 117, in __init__
[Mon Aug 03 17:57:25.526583 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]     self.proxyAuth = proxy.rhnProxyAuth.get_proxy_auth(hostname)
[Mon Aug 03 17:57:25.526605 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]   File "/usr/share/rhn/proxy/rhnProxyAuth.py", line 59, in get_proxy_auth
[Mon Aug 03 17:57:25.526626 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]     __PROXY_AUTH = ProxyAuth(hostname)
[Mon Aug 03 17:57:25.526650 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]   File "/usr/share/rhn/proxy/rhnProxyAuth.py", line 79, in __init__
[Mon Aug 03 17:57:25.526671 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]     self.__processSystemid()
[Mon Aug 03 17:57:25.526692 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]   File "/usr/share/rhn/proxy/rhnProxyAuth.py", line 88, in __processSystemid
[Mon Aug 03 17:57:25.526717 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324]     _("SUSE Manager Proxy error (SUSE Manager Proxy systemid has wrong permissions?). "
[Mon Aug 03 17:57:25.526741 2020] [wsgi:error] [pid 4128] [client 10.XX.XX.XX:44324] spacewalk.common.rhnException.rhnFault: (1000, 'SUSE Manager Proxy error (SUSE Manager Proxy systemid has wrong permissions?). Please contact your system administrator.', 'SUSE Manager Proxy error.')
```

**Comment by paususe** [comment]
@chiaradiamarcelo could you please take a look?

**Comment by mcalmer** [comment]
I fear the procedure described in the docs is wrong.

A re-registration will change the permissions of the systemid and we have 2 places which "fix" it.
1. call configure-proxy.sh again
2. installation of spacewalk-proxy-broker (%post makes this chown)

And I wonder how this procedure should work when the proxy is a salt-minion.
Is the re-registration really needed?

**Comment by phibid** [comment]
In my case, I had to re-register the proxies, because packages were not refreshed, so seems mandatory.

**Comment by Shirocco88** [comment]
See also PR #3694 Ensure systemid file exists to indicate minion is managed by Uyuni

**Comment by Shirocco88** [comment]
@phibid :
any update to this issue ? or can we close this issue ?

**Comment by phibid** [comment]
I guess that we can close this issue as anyway traditional clients are not supported anymore.

**Comment by aaannz** [comment]
I agree with @mcalmer, documentation is wrong. There is no need to reregister proxy unless proxy is being replaced by different machine. And certainly not with `rhnreq_ks` utility.
If packages were not refreshed, maybe manual trigger of software refresh would help ( Server details -> Software -> Packages -> Update Package List)
