### ISSUE TITLE
[uyuni Proxy] package_mapping in /var/spool/rhn-proxy/list not created

### ISSUE THREAD

**Issue by StefanSa** [uyuni-project/uyuni#2473]
# Additional Information

have already created an rsync from master to proxy as with spacewalk, following these instructions.

https://github.com/spacewalkproject/spacewalk/wiki/proxy-precache

https://access.redhat.com/documentation/en-us/red_hat_satellite/5.8/html/proxy_installation_guide/sect-configuring_proxy_precaching

however, no `package_mapping` is created in `/var/spool/rhn-proxy/list`. We didn't see this problem in spacewalk.
That would be important that this would work, especially with regard to large packages such as gitlab.

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

```
Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : Uyuni Server Stable
Name               : Uyuni-Server-release
Version            : 2020.07-86.3.uyuni
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3
Installierte Größe : 1,4 KiB
Installiert        : Ja (automatisch)
Status             : aktuell
Quellpaket         : Uyuni-Server-release-2020.07-86.3.uyuni.src
Zusammenfassung    : Uyuni Server
Beschreibung       :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```
```
Informationen zu Paket Uyuni-Proxy-release:
-------------------------------------------
Repository         : Uyuni Proxy Stable for openSUSE Leap 15.2 (x86_64)
Name               : Uyuni-Proxy-release
Version            : 2020.07-86.3.uyuni
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3
Installierte Größe : 1,4 KiB
Installiert        : Ja (automatisch)
Status             : aktuell
Quellpaket         : Uyuni-Proxy-release-2020.07-86.3.uyuni.src
Zusammenfassung    : Uyuni Proxy
Beschreibung       :
    Uyuni Proxies extend large and/or geographically
    dispersed Uyuni environments to reduce load on the Uyuni
    Server, lower bandwidth needs, and provide faster local
    updates.
```

**Comment by juliogonzalez** [comment]
Since this is not documented at https://www.uyuni-project.org/uyuni-docs/uyuni my guess is that it was never "supported", and at some point some change on Uyuni broke this.

Still, I understand why this solution is needed. As @StefanSa explained, without this zypper exists with a timeout when downloading large packages, as they take a lot of time to sync from the server to the squid on the proxy.

Can someone have a look?

**Comment by StefanSa** [comment]
Hi there, @juliogonzalez
when can we expect implementation?
this is a really important feature for repo files larger than 100MB and there are quite a few of them.

thank you for this project and the work here.
StefanS

**Comment by juliogonzalez** [comment]
@paususe any opinion?

**Comment by paususe** [comment]
Shouldn't we rather make zypper check if data is being downloaded so that it goes not timeout?

@StefanSa could you please paste/attach the missing file so that we evaluate how complex would be to create it?

I find surprising this does not fail for SLES Expanded Support, where there are debug files of hundreds of megabytes in size :-?

**Comment by StefanSa** [comment]
@paususe 
Of course no problem.
[package_mapping gitlab_gitlab-ce -20200831033217.zip](https://github.com/uyuni-project/uyuni/files/5167934/package_mapping.gitlab_gitlab-ce.-20200831033217.zip)

**Comment by StefanSa** [comment]
@paususe @juliogonzalez 
any progress or idea how to solve the problem, or when can you expect a solution?
i am also surprised that no one noticed this before. without this option you cannot use the proxy with large repo files.

**Comment by StefanSa** [comment]
hi there,
Can this be forced please, this bug can e.g. this patch cannot be installed because it is larger than 100MB.
` openSUSE-2020-1962 - Security Advisory`

**Comment by mcalmer** [comment]
I tried to understand how this works. 

When you call on the proxy 
```
$> /usr/bin/rhn_package_manager -l -c <channel label>
```
it will connect to the server, get the package list, and create this cache file.
Than you go to the server, call:
```
$> rhn-satellite-exporter -d EXPORT/ -c <channel label>
```
send the `EXPORT` directory to the proxy and call there:
```
rhn_package_manager -L -c <channel label> --from-export EXPORT/
```
which copy the files from the `EXPORT` dir into `/var/spool/rhn-proxy/...`.

With the fixed from the attached PR this works fine.

There is only one small problem: No user has "manage" permissions for the vendor channels. I think in the satellite era, Red Hat shipped (?) these cache files and kept them up to date. We don't do this.

What should work: create clones from the vendor channels with CLM. These clones are custom channels and you can try to use this feature.

If you know a different way to create these mapping files for vendor channels, please tell us.
We didn't change anything on the permissions of vendor channels. So I think this was also not working in standard spacewalk.
(unless the vendor provide these mapping files)

**Comment by mcalmer** [comment]
Btw: there is always the possibility to increase the timeouts to get the standard proxy behavior working.
Check rhn.conf on proxy and server for timeout parameters.

**Comment by StefanSa** [comment]
@mcalmer 
Hi Michael,
i don't want to force a solution here, but it should be practical.
i think that i'm not alone with large repo files and proxy, how did you solve the problem only inrcrease timouts?
