### ISSUE TITLE
No file contents in "spacewalk-report config-files"

### ISSUE THREAD

**Issue by sejo23** [uyuni-project/uyuni#2484]
## Problem
In reports generated by "spacewalk-report config-files" and "spacewalk-report config-files" the field "contents" contains data like "<memory at 0x7ff49679c1c8>" instead of the file contents.

"spacecmd configchannel_export" or "configchannel_backup" write out the proper file contents.

## Version
This problem was found in version 2020/06 but is also in 2020.07-86.3.uyuni.

## Examples
~ # spacewalk-report config-files | head -n 5
org_id,channel_id,channel,channel_type,path,file_type,file_id,revision,is_binary,contents,delim_start,delim_end,username,groupname,filemode,symbolic_link,selinux_ctx
1,15,config-global-test,normal,/usr/local/bin/applycertboth.sh,file,46,1,N,<memory at 0x7fe8edc941c8>,{|,|},root,root,740,,
1,15,config-global-test,normal,/usr/local/bin/applycert.sh,file,45,1,N,<memory at 0x7fe8edc94288>,{|,|},root,root,740,,
1,15,config-global-test,normal,/usr/local/bin/chage_update.sh,file,110,1,N,<memory at 0x7fe8edc941c8>,{|,|},root,root,744,,
1,15,config-global-test,normal,/usr/local/bin/gencertreq.sh,file,44,1,N,<memory at 0x7fe8edc94288>,{|,|},root,root,740,,

~ # spacewalk-report config-files-latest | head -n 5
org_id,channel_id,channel,channel_type,path,file_type,file_id,revision,is_binary,contents,delim_start,delim_end,username,groupname,filemode,symbolic_link,selinux_ctx
1,15,config-global-test,normal,/usr/local/bin/applycertboth.sh,file,46,1,N,<memory at 0x7f5449fc71c8>,{|,|},root,root,740,,
1,15,config-global-test,normal,/usr/local/bin/applycert.sh,file,45,1,N,<memory at 0x7f5449fc7288>,{|,|},root,root,740,,
1,15,config-global-test,normal,/usr/local/bin/chage_update.sh,file,110,1,N,<memory at 0x7f5449fc71c8>,{|,|},root,root,744,,
1,15,config-global-test,normal,/usr/local/bin/gencertreq.sh,file,44,1,N,<memory at 0x7f5449fc7288>,{|,|},root,root,740,,

**Comment by meaksh** [comment]
Hey @sejo23, Thanks for reporting this issue! - this definitely sounds like a bug caused by migration to Python 3.

**Comment by paususe** [comment]
We are looking into this.

**Comment by vzhestkov** [comment]
PR created
