### ISSUE TITLE
Mail reports still show SUSE Manager at some places

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#250]
> Subject: Uyuni Patch Alert: SUSE-12-SP3-2018-2451 - Recommended update for branding-SLE
>￼ From:	" **SUSE Manager** (uyuni-server.suse.inet) " <root@suse.inet>
> To:	XXXXXXXXXXXXXXXXX
> Date:	25/10/18 12:29
> 
> Uyuni has determined that the following advisory is applicable to
> one or more of the systems you have registered:
> 
> Complete information about this patch can be found at the following location:
>      https://uyuni-server.suse.inet/rhn/errata/details/Details.do?eid=2590
> 
> Bug Fix Advisory - SUSE-12-SP3-2018-2451
> ------------------------------------------------------------------------------
> Summary:
> Recommended update for branding-SLE
> 
>   This update for branding-SLE fixes the following issues:
> 
> - Parse "\n" in plymouth theme text to new lines (bsc#1083702)
>  
> 
> ------------------------------------------------------------------------------
>     
> 
> 
> ---------------------
> Affected Systems List
> ---------------------
> This Patch Advisory may apply to the systems listed below. If you know that
> this patch does not apply to a system listed, it might be possible that the
> package profile for that server is out of date. In that case you should run
> 'up2date -p' (RHEL 4 and below) or 'rhn-profile-sync' (SLES, RHEL 5 and above)
> as root on the system in question to refresh your software profile.
>     
> 
> 
> There is 1 affected system registered in 'Overview' (only systems for
> which you have explicitly enabled Patch Alerts are shown).
>     
> 
> 
> Release    Arch       Profile Name
> ---------- ---------- ---------------------------------------------
> 12.3       x86_64     192.168.3.91
> 
> 
> You may address the issues outlined in this advisory in two ways:
> 
>      - select your server name by clicking on its name from the list
>        available at the following location, and then schedule a
>        patch update for it:
>            https://uyuni-server.suse.inet/rhn/systems/Overview.do
> 
>      - run the Update Agent on each affected server.
>     
> 
> 
> Changing Notification Preferences
> ---------------------------------
> To enable/disable your Patch Alert preferences globally please log in to Uyuni
> and navigate from "Overview" / "Your Account" to the "Preferences" tab.
> 
>         URL: https://uyuni-server.suse.inet/rhn/account/UserPreferences.do
> 
> You can also enable/disable notification on a per system basis by selecting an
> individual system from the "Systems List". From the individual system view
> click the "Details" tab.
> 
> --the **SUSE Manager** Team
> 
> Account Information:
>   Your **SUSE Manager** login:         admin
>   Your **SUSE Manager** email address: XXXXXXXXXXXXXXXXX

**Comment by wombelix** [comment]
As far i can see, most of it was addressed in the meantime, only pending topic seem to be the `email_footer`, which comes from DB Table `rhnTemplateString` and changes to that depend on https://github.com/uyuni-project/uyuni/issues/1368. So I'm not sure if this can still be considered as `good-first-issue` and therefore the label should be removed? Or even Closed and the Email Footer Debranding further processed in https://github.com/uyuni-project/uyuni/issues/1368 instead?

**Comment by mcalmer** [comment]
Seems this is using $PRODUCT_NAME which is set correctly. I think this is fixed already.
Please open a new issue if this can be reproduced with a current Uyuni Version.
