### ISSUE TITLE
No upgrade path to openSUSE-Leap-15.2-Pool for x86_64

### ISSUE THREAD

**Issue by EthanB11** [uyuni-project/uyuni#2517]
# Additional Information

Upgraded to 2020.07 and added Leap 15.2 via command line. Tried to upgrde systems on Leap 15.1, but you can neither change base channels nor do a SP migration.

## Version of Uyuni Server and Proxy (if used)
````
lm3:/usr/share/susemanager # zypper info Uyuni-Server-release
Retrieving repository 'Main Update Repository' metadata ..................................................................................................................................[done]
Building repository 'Main Update Repository' cache .......................................................................................................................................[done]
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.07-86.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2020.07-86.3.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
````

## Details about issue
![uyuni_leap_upgrade_issue_software](https://user-images.githubusercontent.com/34941092/91053817-05764880-e5e9-11ea-947c-00b9510ddd28.png)
![uyuni_leap_upgrade_issue_sp_migration](https://user-images.githubusercontent.com/34941092/91053819-060edf00-e5e9-11ea-86e5-04523a37c4fd.png)

**Comment by mcalmer** [comment]
The info about valid migration targets come from SCC. I asked for the reason why it is not setup like this. Could be business related. Will check.

**Comment by juliogonzalez** [comment]
@EthanB11 now I understand, so you are using openSUSE provided by SCC, and not the repositories provided by Uyuni that get added via `spacewalk-common-channel`.

That's why I didn't understand on Gitter.

**Comment by EthanB11** [comment]
@juliogonzalez  So even though Leap is free we should still not use the built-in channels from SUSE Manager? We should only use the SCC connection for SLES? Can this be explained further?

**Comment by juliogonzalez** [comment]
@EthanB11 AFAIK using the build-in channels (not from SUSE Manager, but provided by SCC or SUSE Customer Center) should work as well if you have access to them, no problem about that.

It's only that since you didn't mention it, I assumed that you were using openSUSE Leap via `spacewalk-common-channels`, and therefore I didn't understand why you mentioned that you couldn't change the channels :-)

**Comment by EthanB11** [comment]
Interesting as I can't select the non-OSS channels from SCC. I am syncing the `spacewalk-common-channel` right now which should allow me to work around the SCC channel issues.

**Comment by juliogonzalez** [comment]
@EthanB11 is this fixed by using `spacewalk-common-channels`

@mcalmer do you have any news?

**Comment by EthanB11** [comment]
Yes using the common uyuni channels worked, but I'm still interested in the expaination for the other one not working.

**Comment by mcalmer** [comment]
It was a business decision and that take time to change it. We are working on it.

**Comment by mcalmer** [comment]
Update: It seems we will get the SCC setup. Hopefully available in a few days

**Comment by mcalmer** [comment]
According to our SCC Team this upgrade path is now available. There maybe a cache in place, but you can try tomorrow if SP Migration offers you a migration from Leap 15.1 to 15.2 .

Don't forget to run `mgr-sync refresh` before to get the latest data.
