### ISSUE TITLE
Inconsistency between filesystem and Packages.gz filename for Debian / Ubuntu repos for Salt clients

### ISSUE THREAD

**Issue by rpasche** [uyuni-project/uyuni#252]
I'm running Spacewalk since 2.1 and currently using SW 2.7 with Debian 8/9 clients.

Now I'm trying to migrate the SW server to Uyuni and also get the power of Salt into our infrastructure.

I'm currently testing with a modified version of apt-transport-spacewalk (with modified apt method) to get Debian clients to download the packages via curl (and token appended). This works for the metadata (e.g. Packages.gz) like a charm now. But I'm unable to download the packages from Uyuni. And now I found the error.

The name of the .deb files within the Packages.gz is the name + '_' + version. But the files on the filesystem are separated with a normal hyphon '-', thus I always get a 404 HTTP error.

Example: Within the web interface, I have a ```db-util-5.3.1-X.all-deb``` package within a channel. The path within the web interface is shown as ```packages/1/c7c/db-util/5.3.1-X/all-deb/c7c71323bd77968b259a22e98218910c99da739e41b972af48beb3818e02d1cd/db-util-5.3.1-X.all-deb.deb```.

But the filename within the Packages.gz is shown as

```Filename: XMLRPC/GET-REQ/stretch_main_main/getPackage/db-util_5.3.1-X.all-deb.deb```

If I replace with '_' with '-' between the name and version, the download works as expected. But this seems to work with a ```traditional``` client without a problem. Only the ```salt``` clients (with that direct curl request) seem to have this problem

But because the ```_``` is the default separation character for name and version, this should be kept within the "Packages.gz" but the filename on the filesystem (and possibly the name of the link within the web interface) should be modified (to show the '_' character).

Also, when I tried to download packages with this path ```XMLRPC/GET-REQ```, I get a 405 HTTP error. Thus, I also rewrite the target request and replace ```XMLRPC/GET-REQ/``` with ```rhn/manager/download/```.

So the final requests look like ```https://<server>/rhn/manager/download/<channel>/getPackage/db-util-....?<token>```

**Comment by cbbayburt** [comment]
Fixed with the recent merge of #461 and the following [Ubuntu support PRs](https://github.com/uyuni-project/uyuni/pulls?q=label%3AUbuntu+is%3Apr+is%3Aclosed).
