### ISSUE TITLE
Usage of apt_auth.conf(5) should be preferred on Ubuntu and Debian uyuni clients

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#2523]
Uyuni version 2020.07

Executing `apt update` on an Ubuntu or Debian client always throw up this message:

```
N: Usage of apt_auth.conf(5) should be preferred over embedding login information directly in the sources.list(5) entry for 'https://my_proxy:443/rhn/manager/download'
```

I was about to try to use the auth.conf file, and propose it as an improvement, however I can see from the documentation that the fact to have different tokens on each repository pointing to the same path and server complicate the use of auth.conf.

In the NOTE section of https://manpages.debian.org/buster/apt/apt_auth.conf.5.en.html

`
For maximum backward compatibility you should avoid multiple machine tokens with the same hostname, but if you need multiple they should all have a path specified in the machine token. 
`

Which is actually our case:

```bash
$ cat /etc/apt/sources.list.d/susemanager\:channels.list 
# Channels managed by SUSE Manager
# Do not edit this file, changes will be overwritten
#

deb [trusted=yes] https://TOKEN1@my_proxy:443/rhn/manager/download debian-10-pool-amd64 main
deb [trusted=yes] https://TOKEN2@my_proxy:443/rhn/manager/download debian-10-amd64-main-security main
deb [trusted=yes] https://TOKEN3@my_proxy:443/rhn/manager/download debian-10-amd64-main-updates main
```

So not sure if with the current implementation of the Debian repositories in Uyuni, there is a way to solve this issue ?

**Comment by mcalmer** [comment]
PR is merged so I think it is fixed
