### ISSUE TITLE
Initial sync of Uyuni client from inside the gui fails in error

### ISSUE THREAD

**Issue by ewenf-uindy** [uyuni-project/uyuni#2528]
I have built from scratch an new openLeap 15.2 server and installed Uyuni 2020.7 on it.  When I go to do the sync process on the repos, which have been added through spacewalk-common-channels, everything seems to sync fine EXCEPT for the Uyuni Client Tools for CentOS 7 (x86_64) repo.  When I run it, it fails to complete and when I look at the logs, I see : https://pastebin.com/SN8jTa3j .  To make it easier to read I broke down the errors into one document : https://pastebin.com/6vsiE8nk .  As it isn't failing on all the packages and only on certain ones, which leads me me to believe that there is still a sync error with the Provo server.  I have tried to do a wget on several of the rpms listed with no luck, it just times out.  This also happens with the devlop tree of the Uyuni client.  I have had no issues downloading any of the other repo channels, just these two.  Nor did I have any problems with the previous of Uyuni.  Right now I am stuck with a show stopper errors, which sucks, because I was supposed to demo this spacewalk replacement to my director this week.  At this point in time, I have no idea what else to do.  Is there a way to make the Uyuni point to another repo zone so I can move forward?

**Comment by EthanB11** [comment]
Check your firewall, I downloaded a package you said didn't work in Gitter. I've had to unblock my spacewalk and now uyuni host from web filtering because that was causing issues doing downloads from rpm and deb repos.

**Comment by EthanB11** [comment]
I can download this from provo just fine.

uyuni-host:~ # wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/noarch/cobbler-2.6.6-6.2.uyuni.noarch.rpm
--2020-08-26 08:17:00-- https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/noarch/cobbler-2.6.6-6.2.uyuni.noarch.rpm
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://provo-mirror.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/noarch/cobbler-2.6.6-6.2.uyuni.noarch.rpm [following]
--2020-08-26 08:17:08-- https://provo-mirror.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/noarch/cobbler-2.6.6-6.2.uyuni.noarch.rpm
Resolving provo-mirror.opensuse.org (provo-mirror.opensuse.org)... 91.193.113.70
Connecting to provo-mirror.opensuse.org (provo-mirror.opensuse.org)|91.193.113.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 525756 (513K) [application/x-redhat-package-manager]
Saving to: ‘cobbler-2.6.6-6.2.uyuni.noarch.rpm’

cobbler-2.6.6-6.2.uyuni.noarch.rpm 100%[=======================================================================================================>] 513.43K 2.05MB/s in 0.2s

2020-08-26 08:17:09 (2.05 MB/s) - ‘cobbler-2.6.6-6.2.uyuni.noarch.rpm’ saved [525756/525756]

**Comment by ewenf-uindy** [comment]
Just closing it.
