### ISSUE TITLE
Bugfixing "Package Architecture: not specified" on Debian10 Minions with cpuach=aarch64, osarch=arm64, DB Schema-Extension needed

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni#2548]
**Debian-9/19 Client Tools for aarch64 are supported since Uyuni 2020.03 release:**
see https://www.uyuni-project.org/doc/2020.03/release-notes-uyuni-server.html
Version 2020.03
Debian client tools
We now offer Debian client tools that allow for easy onboarding of Debian as salt minions, as well as running spacecmd from them.
Check the Client Configuration Guide for information about how to configure Uyuni Server to work with Debian clients.
For now the following architectures are supported: **x86_64, aarch64, armv7l, i586**

**Salt-Minion Binaries:**
•	Debian 10 (x86_64, aarch64, armv7l, i586): https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Debian10-Uyuni-Client-Tools/Debian_10/

```
root@deb10-aarch64:~# dpkg --print-architecture
arm64
root@deb10-aarch64:~# /var/cache/salt/minion/extmods/grains/cpuinfo.py
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
SNIP
root@deb10-aarch64:~# salt-call --local grains.items
SNIP
    cpuarch:
        aarch64
    cpusockets:
        2
SNIP
    osarch:
        arm64
SNIP
root@deb10-aarch64:~# 
```

**Problem description:**
Doing Onbording of Debian10 Minions with cpuach=aarch64, cpuarch=arm64, I run into a problem with the new deb-package architecture "arm64-deb"
e.g. in Uyuni-Server Web-UI System >> Software the deb packages are shown with "Package Architecture: not specified"

A DB Schema-Extension is needed, in order to fix this problem.

**References:**
DB schema definition for "amd86" or "armv6xx" Systems:
https://github.com/spacewalkproject/spacewalk/blob/master/schema/spacewalk/upgrade/spacewalk-schema-2.0-to-spacewalk-schema-2.1/036-armv6hl.sql

**Comment by Shirocco88** [comment]
> A DB Schema-Extension is needed, in order to fix this problem.
PR https://github.com/uyuni-project/uyuni/pull/2549 was merged;
I' do further tests and give feedback.

**Comment by mcalmer** [comment]
It seems this is fixed as the PR with the DB schema upgrade was merged. Closing
