### ISSUE TITLE
Feature Request: Provide Monitoring (prometheus exporters) packages for Debian-10 x86_64

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni#2555]
Hello Uyuni team!
It would be great to have Monitoring (prometheus exporters) packages for Debian-10 x86_64.
Currently there are only packages for ubuntu-20.04/18.04, but not for Debian-10.

Ubuntu-20.04:
http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/xUbuntu_20.04/amd64/
prometheus-apache-exporter_0.7.0+ds-1_amd64.deb
prometheus-node-exporter_0.18.1+ds-2_amd64.deb
prometheus-postgres-exporter_0.8.0+ds-1_amd64.deb

Ubuntu-18.04:
http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/amd64/
golang-github-prometheus-client-golang-dev_0.9.2-0ubuntu2_amd64.deb
golang-prometheus-client-dev_0.9.2-0ubuntu2_amd64.deb
moreutils-dbgsym_0.62-1_amd64.ddeb
moreutils_0.62-1_amd64.deb
prometheus-apache-exporter_0.5.0+ds-2_amd64.deb
prometheus-node-exporter_0.17.0+ds-3_amd64.deb
prometheus-postgres-exporter_0.4.7+ds-2_amd64.deb

Debian-10
http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Debian10-Uyuni-Client-Tools/Debian_10/

dito Debian-9
http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Debian9-Uyuni-Client-Tools/Debian_9/

Could you please also provide packages for Debian-9/10.

Best wishes,
Shirocco88

**Comment by paususe** [comment]
@Shirocco88 

It would be trivial to do that (it's essentially rebuilding them) but I wonder if you really want that? Those packages are already available in Debian:

https://packages.debian.org/search?keywords=exporter
