### ISSUE TITLE
Checksum failure on Centos6 client sync

### ISSUE THREAD

**Issue by ewenf-uindy** [uyuni-project/uyuni#2573]
Fresh SLES15.2 install
Fresh Uyuni 2020.07 install

When syncing the centos 6 uyuni client I am getting checksum errors causing the repo creation to fail.  Attached is the sync fails.  I have tried downloading it multiple times and it has failed.  The developer client downloads fine.

Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'centos6-uyuni-client-x86_64', '--type', 'yum', '--non-interactive']
2020/09/04 11:58:49 -04:00 Sync of channel started.
2020/09/04 11:58:53 -04:00 Repo URL: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/
2020/09/04 11:58:53 -04:00     Packages in repo:               211
2020/09/04 11:58:54 -04:00     Packages already synced:        205
2020/09/04 11:58:54 -04:00     Packages to sync:                 6
2020/09/04 11:58:54 -04:00     New packages to download:         6
2020/09/04 11:58:54 -04:00   Downloading packages:
2020/09/04 11:58:54 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-check-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 169cfd2c926972335368246446b1f21253e2f0726dc530241e9f94a1a6777153 (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-client-setup-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be f26d9e5bb30a2ca22294d0d9333fb6a9f12fb0309ca439e56654017799d6a281 (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-client-tools-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 5005d998c91103a7b5eec79b0e699cd67ee50ebc21e960e62e66b61b26a8627f (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-client-setup-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 4f7e827008bcc96652f607270b6d4b31b47e2dca287ff96bd16eb5379f857338 (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-check-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 3d9c19edf001ffa703de0d446b7422a6cfd40fb3661f5672d6b32986d93d06bf (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-client-setup-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be f26d9e5bb30a2ca22294d0d9333fb6a9f12fb0309ca439e56654017799d6a281 (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-client-tools-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 5005d998c91103a7b5eec79b0e699cd67ee50ebc21e960e62e66b61b26a8627f (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-check-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 3d9c19edf001ffa703de0d446b7422a6cfd40fb3661f5672d6b32986d93d06bf (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-client-setup-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 4f7e827008bcc96652f607270b6d4b31b47e2dca287ff96bd16eb5379f857338 (sha256).. Retrying...
2020/09/04 11:58:55 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-client-setup-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be f26d9e5bb30a2ca22294d0d9333fb6a9f12fb0309ca439e56654017799d6a281 (sha256)..
2020/09/04 11:58:55 -04:00     1/6 : spacewalk-client-setup-4.1.5-3.1.uyuni.noarch.rpm (failed)
2020/09/04 11:58:56 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-check-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 3d9c19edf001ffa703de0d446b7422a6cfd40fb3661f5672d6b32986d93d06bf (sha256)..
2020/09/04 11:58:56 -04:00     2/6 : spacewalk-check-4.1.5-3.1.uyuni.noarch.rpm (failed)
2020/09/04 11:58:56 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-client-tools-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 5005d998c91103a7b5eec79b0e699cd67ee50ebc21e960e62e66b61b26a8627f (sha256)..
2020/09/04 11:58:56 -04:00     3/6 : python2-spacewalk-client-tools-4.1.5-3.1.uyuni.noarch.rpm (failed)
2020/09/04 11:58:56 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-client-setup-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 4f7e827008bcc96652f607270b6d4b31b47e2dca287ff96bd16eb5379f857338 (sha256)..
2020/09/04 11:58:56 -04:00     4/6 : python2-spacewalk-client-setup-4.1.5-3.1.uyuni.noarch.rpm (failed)
2020/09/04 11:58:56 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-check-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 169cfd2c926972335368246446b1f21253e2f0726dc530241e9f94a1a6777153 (sha256).. Retrying...
2020/09/04 11:58:56 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-client-tools-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be c04d63d0ea4bea683eb5361d342ed7e3ceaa3f5ef6cfa802bc5c612373e2d0e0 (sha256).. Retrying...
2020/09/04 11:58:56 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/python2-spacewalk-check-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be 169cfd2c926972335368246446b1f21253e2f0726dc530241e9f94a1a6777153 (sha256)..
2020/09/04 11:58:56 -04:00     5/6 : python2-spacewalk-check-4.1.5-3.1.uyuni.noarch.rpm (failed)
2020/09/04 11:58:56 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-client-tools-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be c04d63d0ea4bea683eb5361d342ed7e3ceaa3f5ef6cfa802bc5c612373e2d0e0 (sha256).. Retrying...
2020/09/04 11:58:56 -04:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/noarch/spacewalk-client-tools-4.1.5-3.1.uyuni.noarch.rpm - Target file isn't valid. Checksum should be c04d63d0ea4bea683eb5361d342ed7e3ceaa3f5ef6cfa802bc5c612373e2d0e0 (sha256)..
2020/09/04 11:58:56 -04:00     6/6 : spacewalk-client-tools-4.1.5-3.1.uyuni.noarch.rpm (failed)
2020/09/04 11:58:57 -04:00 Importing packages started.
2020/09/04 11:58:57 -04:00 
2020/09/04 11:58:57 -04:00   Importing packages to DB:
2020/09/04 11:58:57 -04:00 (50, 'checksums did not match 169cfd2c926972335368246446b1f21253e2f0726dc530241e9f94a1a6777153 vs 0ce31fc17841d2ef10afa8dfca82a6057702dd1bc0fdea60ca2da265ae82af54', 'Invalid information uploaded to the server')
2020/09/04 11:58:57 -04:00 (50, 'checksums did not match 4f7e827008bcc96652f607270b6d4b31b47e2dca287ff96bd16eb5379f857338 vs 1e7fcfec740d98f037f2945d4f048da39717e08db664878169ed2dc10b55b09e', 'Invalid information uploaded to the server')
2020/09/04 11:58:57 -04:00 (50, 'checksums did not match 5005d998c91103a7b5eec79b0e699cd67ee50ebc21e960e62e66b61b26a8627f vs e4c21357d8d3569bae751db7813d65906dafdd8a3de73e430179f00ae75dbb64', 'Invalid information uploaded to the server')
2020/09/04 11:58:57 -04:00 (50, 'checksums did not match 3d9c19edf001ffa703de0d446b7422a6cfd40fb3661f5672d6b32986d93d06bf vs 6d62d4c932bdbd6d2a84d1b309c85fdd3935e58d1b654230ab2b0849294b6153', 'Invalid information uploaded to the server')
2020/09/04 11:58:57 -04:00 (50, 'checksums did not match f26d9e5bb30a2ca22294d0d9333fb6a9f12fb0309ca439e56654017799d6a281 vs dcdb6505c58a4817cc6d961e345f4dffdda4f1b316272a28976b12d948127baf', 'Invalid information uploaded to the server')
2020/09/04 11:58:57 -04:00 (50, 'checksums did not match c04d63d0ea4bea683eb5361d342ed7e3ceaa3f5ef6cfa802bc5c612373e2d0e0 vs 2ab39d45fe563a2d51ed4374c132d44bf79f6a0aa4a13560c1a127d6e94c16b0', 'Invalid information uploaded to the server')
2020/09/04 11:58:57 -04:00   Package batch #1 of 1 completed...
2020/09/04 11:58:57 -04:00 Importing packages finished.
2020/09/04 11:58:57 -04:00 
2020/09/04 11:58:57 -04:00   Patches in repo: 0.

**Comment by Shirocco88** [comment]
>> @ewenf-uindy commented 19 hours ago
>> Fresh SLES15.2 install
>> Fresh Uyuni 2020.07 install

#2488
>> @juliogonzalez
>> This is an unsupported scenario. Uyuni Server and Proxy to are be installed only on top of openSUSE Leap (current stable on top of Leap 15.2)

unsupported scenario ???

**Comment by juliogonzalez** [comment]
@ewenf-uindy if you mean that your server or your proxy are based on SLE, that is not supported.

@Shirocco88: having SLE clients is supported. Having the server or the proxy installed on top of SLE as in https://github.com/uyuni-project/uyuni/issues/2488#issuecomment-675016361 is *not* supported. It's clearly stated on the website, the doc and the release notes.

https://www.uyuni-project.org/pages/stable-version.html#serversetup
https://www.uyuni-project.org/pages/devel-version.html#serversetup
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-install-requirements.html <- @Loquacity it says here 15.1, not only there but on the whole guide. Make sure this gets changed to say 15.2
https://www.uyuni-project.org/doc/2020.07/release-notes-uyuni-server.html#_requirements
https://www.uyuni-project.org/doc/2020.07/release-notes-uyuni-proxy.html#_system_requirements

In all cases it says openSUSE Leap, and this was always the case for Uyuni since the first version.

Will it install? Maybe. Will it work fine? Probably not. SLE and openSUSE are not (for now) 100% equivalent in terms of packages. So Uyuni Server and Proxy only tested to work on top of openSUSE Leap.

People using SLE should use SUSE Manager, or otherwise they are on their own. We don't have enough resources to maintain Uyuni on top of SLE as well.

**Comment by Loquacity** [comment]
> https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-install-requirements.html <- @Loquacity it says here 15.1, not only there but on the whole guide. Make sure this gets changed to say 15.2

This is already done in master.

**Comment by ewenf-uindy** [comment]
This is one of those emails where I have been dreading replying to all
weekend., and now it is 5:30am and I can't sleep anymore because of it.
Yes, i am an idiot, I freely admit it, but rather than browbeating me, it
could have gone "SLES 15.2?  Did you mean OpenLeap15.2" rather than
spending a paragraph pointing out my stupidity.

It is Openleap 15.2, I apologize for stating myself incorrectly.

The dev client downloaded fine, but the checksums happened when I tried to
sync the stable client.  This is not the only place I have seen checksum
errors, but in this case it is a show stopper.



---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.

**Comment by mcalmer** [comment]
I will close this issue here.
I for the checksum errors we have the other issue from you. I think they are generic because of the mirror infrastructure.
