### ISSUE TITLE
Checksum errors during install phase of Uyuni

### ISSUE THREAD

**Issue by ewenf-uindy** [uyuni-project/uyuni#2577]
Openleap 15.2
Uyuni 2020.07
uname -a Linux uyuni 5.3.18-lp152.36-default #1 SMP Tue Aug 18 17:09:44 UTC 2020 (885251f) x86_64 x86_64 x86_64 GNU/Linux

When installing, checksum errors are thrown but can be passed by accepting the package and unblocking it.  This has been repeatable for me on all recent installs.

[checksum-error.txt](https://github.com/uyuni-project/uyuni/files/5182955/checksum-error.txt)

**Comment by Shirocco88** [comment]
@ewenf-uindy 
which opensuse mirror are you using ?

can you download the file with wget ?
wget  https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/noarch/vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm

**Comment by ewenf-uindy** [comment]
How do I see which repo I am pulling from?  Remember, I am stupid so go slow.

**Comment by ewenf-uindy** [comment]
Downloads just fine using the wget.  Looks like it is pulling from purdue this week as oppsed to last week when I was pulling from Provo.

wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/noarch/vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm
--2020-09-07 09:14:29--  https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/noarch/vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://plug-mirror.rcac.purdue.edu/opensuse/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/noarch/vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm [following]
--2020-09-07 09:14:29--  http://plug-mirror.rcac.purdue.edu/opensuse/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/noarch/vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm
Resolving plug-mirror.rcac.purdue.edu (plug-mirror.rcac.purdue.edu)... 128.211.151.254, 2001:18e8:804:35::fe
Connecting to plug-mirror.rcac.purdue.edu (plug-mirror.rcac.purdue.edu)|128.211.151.254|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13920 (14K) [application/x-redhat-package-manager]
Saving to: ‘vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm.1’

vsftpd-formula-0.1.1568808472.be9f236-1.3.u 100%[==========================================================================================>]  13.59K  --.-KB/s    in 0.004s  

2020-09-07 09:14:29 (3.04 MB/s) - ‘vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm.1’ saved [13920/13920]

**Comment by juliogonzalez** [comment]
Can you `wget http://download.opensuse.org/opensuse/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/repodata/886a5359052abf37b999243e5e41e4fce33231ff2a1cfc173d07b2bfc520df0c-primary.xml.gz`?

At ` plug-mirror.rcac.purdue.edu` the data looks good:

```
<package type="rpm">
  <name>vsftpd-formula</name>
  <arch>noarch</arch>
  <version epoch="0" ver="0.1.1568808472.be9f236" rel="1.3.uyuni"/>
  <checksum type="sha256" pkgid="YES">dcd35370f1ea99530d1be7478e6a29985eb274c574bcc6992bfefb536e378f94</checksum>
```
```
juliogonzalez@juliogonzalez:~$ wget http://plug-mirror.rcac.purdue.edu/opensuse/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/noarch/vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm--2020-09-08 10:20:36--  http://plug-mirror.rcac.purdue.edu/opensuse/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/noarch/vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm
Resolviendo plug-mirror.rcac.purdue.edu (plug-mirror.rcac.purdue.edu)... 2001:18e8:804:35::fe, 128.211.151.254
Conectando con plug-mirror.rcac.purdue.edu (plug-mirror.rcac.purdue.edu)[2001:18e8:804:35::fe]:80... falló: La red es inaccesible.
Conectando con plug-mirror.rcac.purdue.edu (plug-mirror.rcac.purdue.edu)[128.211.151.254]:80... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 13920 (14K) [application/x-redhat-package-manager]
Grabando a: “vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm”

vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm          100%[==================================================================================================================================================================>]  13,59K  --.-KB/s    en 0s      

2020-09-08 10:20:36 (340 MB/s) - “vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm” guardado [13920/13920]

juliogonzalez@juliogonzalez:~$ sha256sum vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm 
dcd35370f1ea99530d1be7478e6a29985eb274c574bcc6992bfefb536e378f94  vsftpd-formula-0.1.1568808472.be9f236-1.3.uyuni.noarch.rpm
```
So, once again, this look like zypper getting metadata from one mirror, packages from other mirror, and a mismatch happening between the two mirrors.

Right now it seems provo-mirror.opensuse.org has an expired SSL certificate, and even if you bypass the alert you get a 404, but using ftp and downloading ftp://provo-mirror.opensuse.org/pub/opensuse/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/repodata/85389bcf181674574d3a5e494ffc30bd5f2269e50fe5f5d73c6e19894d322ccd-primary.xml.gz:

```
<package type="rpm">
  <name>vsftpd-formula</name>
  <arch>noarch</arch>
  <version epoch="0" ver="0.1.1568808472.be9f236" rel="1.3.uyuni"/>
  <checksum type="sha256" pkgid="YES">fbb1527f49d64ab5608863667804dd534e5a7f1ab91c15098cf75429bf2e3699</checksum>
  <summary>Formula for vsftpd server for SUSE Manager</summary>
  <description>Formula for installation and setup of vsftpd server.</description>
```
Clearly a mismatch.

**Comment by juliogonzalez** [comment]
According to what I see at other European mirrors, I'd say purdue.edu is out of sync, but I am not 100% sure.

**Comment by juliogonzalez** [comment]
Correction: provo-mirror.opensuse.org seems out of sync. I reviewed two European mirrors and the hash there is `fbb1527f49d64ab5608863667804dd534e5a7f1ab91c15098cf75429bf2e3699`

**Comment by juliogonzalez** [comment]
Reported at https://progress.opensuse.org/projects/opensuse-admin/activity?from=2020-09-08

**Comment by ewenf-uindy** [comment]
wget
http://download.opensuse.org/opensuse/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/repodata/886a5359052abf37b999243e5e41e4fce33231ff2a1cfc173d07b2bfc520df0c-primary.xml.gz
--2020-09-08 08:47:19--
http://download.opensuse.org/opensuse/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/repodata/886a5359052abf37b999243e5e41e4fce33231ff2a1cfc173d07b2bfc520df0c-primary.xml.gz
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134,
2001:67c:2178:8::13
Connecting to download.opensuse.org
(download.opensuse.org)|195.135.221.134|:80...
connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-08 08:47:20 ERROR 404: Not Found.

*I tried from an internal and an external source and got the same result.
I will note that when I was back tracking this yesterday that prudue had
their version of the repo still named 15.1, but that could be irrelevant to
this problem.*

---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.

**Comment by mcalmer** [comment]
@ewenf-uindy Is it solved in the meanwhile? AFAIK we released some new versions of uyuni and I hope the mirrors now get the correct content.

**Comment by ewenf-uindy** [comment]
you can close this.

---------------

Len Ewen

Systems Administrator 1

Information Technology

University of Indianapolis

(317) 788-3362

[image: UIndyIT.jpg]

Confidentiality Notice: This communication and/or its content are for the
sole use of the intended recipient, and may be privileged, confidential, or
otherwise protected from disclosure by law. If you are not the intended
recipient, please notify the sender and then delete all copies of it.
Unless you are the intended recipient, your use or dissemination of the
information contained in this communication may be illegal.
