### ISSUE TITLE
[WIP] Enabling/Onbording of Debian10 Minions with cpuach=aarch64, cpuarch=arm64 (Raspberry PI4)

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni#2579]
Debian-9/10 Client Tools for aarch64 are supported since Uyuni 2020.03 release:
see https://www.uyuni-project.org/doc/2020.03/release-notes-uyuni-server.html
Version 2020.03
Debian client tools
We now offer Debian client tools that allow for easy onboarding of Debian as salt minions, as well as running spacecmd from them.
Check the Client Configuration Guide for information about how to configure Uyuni Server to work with Debian clients.
For now the following architectures are supported: x86_64, aarch64, armv7l, i586

## Version of Uyuni Server and Proxy (if used)
Uyuni Server Master

## Details about issue
At the moment the following features didn’t work:
•	Bootstrapping and performing initial state runs such as setting repositories and performing profile updates
•	Assigning .deb channels to minions
•	Information displayed in System details pages
                  „Installed Products:”
•	Package install, update, and remove
•	Package install using Package States
•	Configuration and state channels
•	Support Debian ARM64 architectures in mgr-sync
•	Support creating bootstrap repositories for Debian 10 on ARM64v8/AARCH64

This as first inputs;
I will add a comment if I have time for furter Tests.

see also PR
https://github.com/uyuni-project/uyuni/pull/2549
DB schema extension for Debian10-Minions on cpuarch=aarch64,osarch=arm64

**Comment by juliogonzalez** [comment]
@Shirocco88 can this be closed since the PR was merged?

**Comment by Shirocco88** [comment]
@juliogonzalez
at the moment there are many projects parallel, which I have to at my company;

I will do the following test with Raspberry PI4 (cpuach=aarch64, cpuarch=arm64) and uyuni-2020.09 in October:
• Bootstrapping and performing initial state runs such as setting repositories and performing profile updates
• Assigning .deb channels to minions
• Information displayed in System details pages
 „Installed Products:”
• Package install, update, and remove
• Package install using Package States
• Configuration and state channels
• Support Debian ARM64 architectures in mgr-sync
• Support creating bootstrap repositories for Debian 10 on ARM64v8/AARCH64
and give feedback.

If other community members can help testing, it would also be fine ;-)

**Comment by paususe** [comment]
Hey @Shirocco88 , did you try this? Does it work now?

**Comment by Shirocco88** [comment]
@paususe 
Sorry, our project with ARM64 Server have been stopped :-(
Therefore I couldn't continue working on this topic;

How can we continue with this issue ?

**Comment by paususe** [comment]
I'd say let's close this issue and if anyone finds the bug is not solved with the code we merged then just open an issue.
