### ISSUE TITLE
reposync with kickstart tree fails

### ISSUE THREAD

**Issue by skoehnen23** [uyuni-project/uyuni#2583]
i got following URLGrabError when i try to sync an repositoy with kickstart enabled:

my command:

/usr/bin/spacewalk-repo-sync --channel stable_base_centos7-x86_64 --type yum --sync-kickstart

07:21:51   Importing kickstarts.
07:21:51 Trying treeinfo
07:21:51 Unexpected error: <class 'AttributeError'>
07:21:51 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 1163, in get_file
    downloaded = urlgrabber.urlgrab(path, temp_file)
  File "/usr/lib/python3.6/site-packages/urlgrabber/grabber.py", line 787, in urlgrab
    return default_grabber.urlgrab(url, filename, **kwargs)
  File "/usr/lib/python3.6/site-packages/urlgrabber/grabber.py", line 1203, in urlgrab
    raise err
urlgrabber.grabber.URLGrabError: [Errno 2] Local file does not exist: /root/treeinfo
During handling of the above exception, another exception occurred:

## Version of Uyuni Server
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2020.07-86.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.07-86.3.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

openSUSE
VERSION = 15.2

Sync without kickstart runs well

**Comment by mateiw** [comment]
Please test the following patch:
```patch
--- /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py.orig  2020-09-16 15:52:57.000000000 +0200
+++ /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py      2020-09-17 16:39:17.081997936 +0200

@@ -1165,7 +1165,7 @@
                     return target_file
                 else:
                     return urlgrabber.urlread(path)
-            except urlgrabber.URLGrabError:
+            except urlgrabber.grabber.URLGrabError:
                 return
         finally:
             if os.path.exists(temp_file):

```

**Comment by skoehnen23** [comment]
hi,

i have tested:

/usr/bin/spacewalk-repo-sync --channel stable_base_centos7-x86_64 --type yum --sync-kickstart

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 48, in <module>
    from spacewalk.satellite_tools import reposync
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 58, in <module>
    from spacewalk.satellite_tools.repo_plugins import yum_src
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 1168
    except urlgrabber.grabber.URLGrabError: 
                                           ^
IndentationError: unindent does not match any outer indentation level

**Comment by sbluhm** [comment]
I just found your issue. A fix is pushed to master and awaying merge (#3149 ). 
As a current workaround, you need to replace these two files:
backend/satellite_tools/repo_plugins/yum_src.py
backend/satellite_tools/reposync.py
From here:
https://github.com/sbluhm/uyuni/tree/sbluhm-kickstart
To here:
/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/

This github branch will be deleted once it is merged to master. Then the source url will change to
https://github.com/uyuni-project/uyuni

**Comment by skoehnen23** [comment]
thanks @sbluhm,

work like expected.

**Comment by meaksh** [comment]
This should be now fixed by https://github.com/uyuni-project/uyuni/pull/3149

Closing issue. Thanks!
