### ISSUE TITLE
Get Debian clients registered as Salt clients into Uyuni

### ISSUE THREAD

**Issue by rpasche** [uyuni-project/uyuni#261]
This is some kind of general issue to collect the current problems getting Debian systems integrated as Salt clients into Uyuni.

I will start to list the first points I recognized until now and add some further information later as I'm able to collect all needed information. Nearly all modifications (for my tests so far) have been done on the Debian test client (despite the modifications of some salt states with ```/usr/share/susemanager/salt/```)

1. New apt ```method``` needed to download deb packages via HTTP request (and token). See also https://github.com/uyuni-project/uyuni/issues/252
2. Jinja template rendering error within ```bootstrap.remove_traditional_stack.sls```. This seems to be caused by ```repos.items()``` where the ```data``` is an array of type ```dict``` instead of dict only as in Suse or RedHat.
3. pkg.info_installed in Debian does not support to set ```attr``` to be returned by the function. Therefore you get an exception, that these arguments are not supported.
4. Also, the ```install_date``` is missing for many debian packages (and therefore ```install_date_time_t``` even after modification of the clients salt modules). See https://github.com/saltstack/salt/pull/50318
5. After registering a Debian system (after slight modifications of the base salt states within Uyuni), the ```packages.profileupdate``` does not seem to trigger a real package update within the database. Within the salt master logfile (running in ```debug``` mode), several errors parsing the IPv4 address are reported.

As said, I will add further information.

**Comment by rpasche** [comment]
Jinja rendering error of ```bootstrap.remove_traditional_stack```

```
[DEBUG   ] LazyLoaded highstate.output
uyuni-test-client.domain:
    Data failed to compile:
----------
    Rendering SLS 'base:bootstrap.remove_traditional_stack' failed: Jinja variable 'list object' has no attribute 'get'
```

**Comment by rpasche** [comment]
Hmmmm....looks like after I disabled the IPv6, the ```pacakges.profileupdate``` seems to work. I will re-check that.

**Comment by rpasche** [comment]
I created PR #264 to somehow track the changes I made on my test systems to get Debian clients registered as Salt clients into Uyuni.

On the client side, I had to change the functions
* ```pkg.list_repos``` (from ```aptpkg.py```)
* ```pkg.info_installed``` (from ```aptpkg.py```)
* ```_get_pkg_info``` (from ```dpkg.py```)
* ```_get_pkg_install_time``` (from ```dpkg.py```)

```pkg.list_repos``` had to be modified to return a more unique ```alias```. Otherwise, rendering state file threw an error with duplicate IDs (for repos to disable). This function also returns an array of repos for one ```alias```. I did not want to change that also, because I don't know, what impact that might cause.

```_get_pkg_info``` and ```_get_pkg_install_time``` needed to be changed to correctly retrieve the ```install_date``` (and thus ```install_date_time_t```) that seems to be a mandatory attribute for the package refresh task.

```pkg.info_installed``` did not support to apply a list of attributes that should be retrieved. I modified that on the client test system to return the attrs ```epoch```, ```arch```, ```install_date_time_t```. But these attributes are not available on a Debian system. So later, I think it would be better to change the state file to request the corresponding attributes for Debian clients and *transform* them to the RPM attributes within the state file.

**Comment by cbbayburt** [comment]
Some of the items mentioned are covered in #309

**Comment by mbologna** [comment]
Hi @rpasche !
First of all, thanks for your valuable contribution.
We proceeded in implementing Ubuntu support: you can find implementation details in this PR https://github.com/uyuni-project/uyuni/pull/461, which is already merged.

Updated installer packages are in progress, but as soon as they are ready (take a look at the Uyuni mailing list) we invite you to test them out and let us know if the Ubuntu support is working for you as well.
