### ISSUE TITLE
after update  packages spacewalk services failing many services 

### ISSUE THREAD

**Issue by suhailsid** [uyuni-project/uyuni#2623]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2020.07-86.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

 tail rhn_taskomatic_daemon.log
2020-09-18 11:04:32,814 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:04:35,323 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:04:36,448 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:04:37,675 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:04:38,967 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:05:54,336 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:05:55,439 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:05:56,680 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:05:57,925 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE
2020-09-18 11:05:59,150 [main] FATAL com.redhat.rhn.taskomatic.core.TaskomaticDaemon - FILE

spacewalk-service status
● uyuni-check-database.service - Uyuni check database
   Loaded: loaded (/usr/lib/systemd/system/uyuni-check-database.service; static; vendor preset: disabled)
   Active: active (exited) since Fri 2020-09-18 11:04:11 EEST; 7min ago
  Process: 19202 ExecStart=/usr/sbin/spacewalk-startup-helper check-database (code=exited, status=0/SUCCESS)
 Main PID: 19202 (code=exited, status=0/SUCCESS)
    Tasks: 0
   CGroup: /system.slice/uyuni-check-database.service

● tomcat.service - Apache Tomcat Web Application Container
   Loaded: loaded (/usr/lib/systemd/system/tomcat.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/tomcat.service.d
           └─override.conf
   Active: active (running) since Fri 2020-09-18 11:04:11 EEST; 7min ago
  Process: 19143 ExecStop=/usr/lib/tomcat/server stop (code=exited, status=1/FAILURE)
 Main PID: 19243 (java)
    Tasks: 66 (limit: 576)
   CGroup: /system.slice/tomcat.service
           └─19243 /usr/lib64/jvm/jre/bin/java -ea -Xms256m -Xmx1G -Djava.awt.headless=true -Dorg.xml.sax.driver=com.re…rt

● spacewalk-wait-for-tomcat.service - Spacewalk wait for tomcat
   Loaded: loaded (/usr/lib/systemd/system/spacewalk-wait-for-tomcat.service; static; vendor preset: disabled)
   Active: active (exited) since Fri 2020-09-18 11:04:30 EEST; 7min ago
  Process: 19244 ExecStart=/usr/sbin/spacewalk-startup-helper wait-for-tomcat (code=exited, status=0/SUCCESS)
 Main PID: 19244 (code=exited, status=0/SUCCESS)
    Tasks: 0
   CGroup: /system.slice/spacewalk-wait-for-tomcat.service

● salt-master.service - The Salt Master Server
   Loaded: loaded (/usr/lib/systemd/system/salt-master.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/salt-master.service.d
           └─override.conf
   Active: active (running) since Fri 2020-09-18 11:04:11 EEST; 7min ago
     Docs: man:salt-master(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 19237 (salt-master)
    Tasks: 56
   CGroup: /system.slice/salt-master.service
           ├─19237 /usr/bin/python3 /usr/bin/salt-master
           ├─19297 /usr/bin/python3 /usr/bin/salt-master
           ├─19411 /usr/bin/python3 /usr/bin/salt-master
           ├─19414 /usr/bin/python3 /usr/bin/salt-master
           ├─19418 /usr/bin/python3 /usr/bin/salt-master
           ├─19419 /usr/bin/python3 /usr/bin/salt-master
           ├─19420 /usr/bin/python3 /usr/bin/salt-master
           ├─19421 /usr/bin/python3 /usr/bin/salt-master
           ├─19422 /usr/bin/python3 /usr/bin/salt-master
           ├─19433 /usr/bin/python3 /usr/bin/salt-master
           ├─19434 /usr/bin/python3 /usr/bin/salt-master
           ├─19435 /usr/bin/python3 /usr/bin/salt-master
           ├─19436 /usr/bin/python3 /usr/bin/salt-master
           ├─19437 /usr/bin/python3 /usr/bin/salt-master
           ├─19439 /usr/bin/python3 /usr/bin/salt-master
           ├─19440 /usr/bin/python3 /usr/bin/salt-master
           ├─19441 /usr/bin/python3 /usr/bin/salt-master
           └─19442 /usr/bin/python3 /usr/bin/salt-master

● salt-api.service - The Salt API
   Loaded: loaded (/usr/lib/systemd/system/salt-api.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/salt-api.service.d
           └─override.conf
   Active: active (running) since Fri 2020-09-18 11:04:11 EEST; 7min ago
     Docs: man:salt-api(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 19235 (salt-api)
    Tasks: 104
   CGroup: /system.slice/salt-api.service
           ├─19235 /usr/bin/python3 /usr/bin/salt-api
           └─19303 /usr/bin/python3 /usr/bin/salt-api

● spacewalk-wait-for-salt.service - Make sure that salt is started before httpd
   Loaded: loaded (/usr/lib/systemd/system/spacewalk-wait-for-salt.service; static; vendor preset: disabled)
   Active: active (exited) since Fri 2020-09-18 11:04:11 EEST; 7min ago
  Process: 19238 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 19238 (code=exited, status=0/SUCCESS)
    Tasks: 0
   CGroup: /system.slice/spacewalk-wait-for-salt.service

● apache2.service - The Apache Webserver
   Loaded: loaded (/usr/lib/systemd/system/apache2.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/apache2.service.d
           └─override.conf
   Active: active (running) since Fri 2020-09-18 11:04:30 EEST; 7min ago
  Process: 19180 ExecStop=/usr/sbin/start_apache2 -DSYSTEMD -DFOREGROUND -k graceful-stop (code=exited, status=0/SUCCESS)
 Main PID: 19734 (httpd-prefork)
   Status: "Processing requests..."
    Tasks: 6
   CGroup: /system.slice/apache2.service
           ├─19734 /usr/sbin/httpd-prefork -DSYSCONFIG -DSSL -DISSUSE -C PidFile /var/run/httpd.pid -C Include /etc/apa…rt
           ├─19793 /usr/sbin/httpd-prefork -DSYSCONFIG -DSSL -DISSUSE -C PidFile /var/run/httpd.pid -C Include /etc/apa…rt
           ├─19794 /usr/sbin/httpd-prefork -DSYSCONFIG -DSSL -DISSUSE -C PidFile /var/run/httpd.pid -C Include /etc/apa…rt
           ├─19795 /usr/sbin/httpd-prefork -DSYSCONFIG -DSSL -DISSUSE -C PidFile /var/run/httpd.pid -C Include /etc/apa…rt
           ├─19796 /usr/sbin/httpd-prefork -DSYSCONFIG -DSSL -DISSUSE -C PidFile /var/run/httpd.pid -C Include /etc/apa…rt
           └─19797 /usr/sbin/httpd-prefork -DSYSCONFIG -DSSL -DISSUSE -C PidFile /var/run/httpd.pid -C Include /etc/apa…rt

● rhn-search.service - Spacewalk search engine
   Loaded: loaded (/usr/lib/systemd/system/rhn-search.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/rhn-search.service.d
           └─override.conf
   Active: active (running) since Fri 2020-09-18 11:04:30 EEST; 7min ago
 Main PID: 19785 (rhn-search)
    Tasks: 79
   CGroup: /system.slice/rhn-search.service
           ├─19785 /bin/sh /usr/sbin/rhn-search
           └─19827 /usr/bin/java -Djava.library.path=/usr/lib:/usr/lib64:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/po…in

● cobblerd.service - Cobbler Helper Daemon
   Loaded: loaded (/usr/lib/systemd/system/cobblerd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-09-18 11:04:11 EEST; 7min ago
  Process: 19234 ExecStartPost=/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi (code=exited, status=1/FAILURE)
 Main PID: 19233 (cobblerd)
    Tasks: 1
   CGroup: /system.slice/cobblerd.service
           └─19233 /usr/bin/python3 -s /usr/bin/cobblerd -F

● taskomatic.service - Taskomatic
   Loaded: loaded (/usr/lib/systemd/system/taskomatic.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/taskomatic.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Fri 2020-09-18 11:05:59 EEST; 6min ago
  Process: 21358 ExecStart=/usr/sbin/taskomatic (code=exited, status=255)
 Main PID: 21358 (code=exited, status=255)

● spacewalk-wait-for-taskomatic.service - Spacewalk wait for taskomatic
   Loaded: loaded (/usr/lib/systemd/system/spacewalk-wait-for-taskomatic.service; static; vendor preset: disabled)
   Active: active (exited) since Fri 2020-09-18 11:06:02 EEST; 6min ago
  Process: 19789 ExecStart=/usr/sbin/spacewalk-startup-helper wait-for-taskomatic (code=exited, status=0/SUCCESS)
 Main PID: 19789 (code=exited, status=0/SUCCESS)

● salt-secrets-config.service - Configures secrets between salt-master and other services
   Loaded: loaded (/usr/lib/systemd/system/salt-secrets-config.service; static; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/salt-secrets-config.service.d
           └─override.conf
   Active: active (exited) since Fri 2020-09-18 11:04:01 EEST; 8min ago
  Process: 19201 ExecStart=/usr/bin/salt-secrets-config.py (code=exited, status=0/SUCCESS)
 Main PID: 19201 (code=exited, status=0/SUCCESS)
    Tasks: 0
   CGroup: /system.slice/salt-secrets-config.service

● mgr-websockify.service - TCP to WebSocket proxy
   Loaded: loaded (/usr/lib/systemd/system/mgr-websockify.service; static; vendor preset: disabled)
   Active: active (running) since Fri 2020-09-18 11:04:11 EEST; 7min ago
  Process: 19236 ExecStartPre=/usr/bin/sh -c grep secret_key /etc/rhn/rhn.conf | tr -d ' ' | cut -f2 -d '=' | perl -ne 's/([0-9a-f]{2})/print chr hex $1/gie' > /etc/rhn/websockify.key (code=exited, status=0/SUCCESS)
 Main PID: 19250 (websockify)
    Tasks: 4
   CGroup: /system.slice/mgr-websockify.service
           └─19250 /usr/bin/python3 /usr/bin/websockify --token-plugin JWTTokenApi --token-source /etc/rhn/websockify.k…50
● spacewalk.target - Spacewalk
   Loaded: loaded (/usr/lib/systemd/system/spacewalk.target; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2020-09-18 10:49:04 EEST; 22min ago
● jabberd.service - Jabber Server
   Loaded: loaded (/usr/lib/systemd/system/jabberd.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2020-09-18 09:49:30 EEST; 1h 22min ago
 Main PID: 3398 (code=exited, status=0/SUCCESS)
● osa-dispatcher.service - OSA Dispatcher daemon
   Loaded: loaded (/usr/lib/systemd/system/osa-dispatcher.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2020-09-18 09:49:30 EEST; 1h 22min ago
 Main PID: 3466 (code=killed, signal=TERM)

**Comment by mateiw** [comment]
@suhailsid can you check if also have jar files in `/srv/tomcat/webapps/rhn/WEB-INF/lib` besides the symlinks that point to `/usr/share/java...`? There should be no jar files in that directory, only symlinks.
If that's the case delete all files from `/srv/tomcat/webapps/rhn/WEB-INF/lib` and reinstall `spacewalk-java`, `spacewalk-taskomatic`, `spacewalk-java-postgresql` and `spacewalk-branding`.

**Comment by mateiw** [comment]
@suhailsid did you by any chance deploy using the Ant development script (`ant -f manager-build.xml deploy`) and then executed `zypper up` ?

**Comment by juliogonzalez** [comment]
I seem to remember this was fixed at rocket.chat or the mailing lists :-?

Is this still a problem?

**Comment by mcalmer** [comment]
noresponse

**Comment by suhailsid** [comment]
Sorry for delay yes it was closed long back in rocket chay
