### ISSUE TITLE
Cobbler error <class 'AttributeError'>:module 'string' has no attribute 'join'

### ISSUE THREAD

**Issue by Joerg1962** [uyuni-project/uyuni#2624]
Hello,

I'm trying to get a network installation started. When I call the Cobbler URL I get the following message:

uyuni01:~ # curl -k http://212.84.201.157/cblr/svc/op/gpxe/mac/00:50:56:9a:d4:eb
<class 'AttributeError'>:module 'string' has no attribute 'join'

In /var/log/cobbler/cobbler.log :

Fri Sep 18 11:03:29 2020 - INFO | REMOTE find_items(system); criteria({'mac_address': '00:50:56:9a:d4:eb'}); sort(None); user(?)
Fri Sep 18 11:03:29 2020 - INFO | find_items; ['system']
Fri Sep 18 11:03:29 2020 - INFO | REMOTE generate_gpxe; user(?)
Fri Sep 18 11:03:29 2020 - INFO | generate_gpxe
Fri Sep 18 11:03:29 2020 - INFO | Exception occured: <class 'AttributeError'>
Fri Sep 18 11:03:29 2020 - INFO | Exception value: module 'string' has no attribute 'join'
Fri Sep 18 11:03:29 2020 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 2241, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1123, in generate_gpxe
    return self.api.generate_gpxe(profile, system)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 650, in generate_gpxe
    return self.tftpgen.generate_gpxe("system", system)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 800, in generate_gpxe
    distro_mirror_name = string.join(distro.kernel.split('/')[-2:-1], '')

Fri Sep 18 11:03:41 2020 - INFO | REMOTE find_items(system); criteria({'mac_address': '00:50:56:9a:d4:eb'}); sort(None); user(?)
Fri Sep 18 11:03:41 2020 - INFO | find_items; ['system']
Fri Sep 18 11:03:41 2020 - INFO | REMOTE generate_gpxe; user(?)
Fri Sep 18 11:03:41 2020 - INFO | generate_gpxe
Fri Sep 18 11:03:41 2020 - INFO | Exception occured: <class 'AttributeError'>
Fri Sep 18 11:03:41 2020 - INFO | Exception value: module 'string' has no attribute 'join'
Fri Sep 18 11:03:41 2020 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 2241, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 1123, in generate_gpxe
    return self.api.generate_gpxe(profile, system)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 650, in generate_gpxe
    return self.tftpgen.generate_gpxe("system", system)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 800, in generate_gpxe
    distro_mirror_name = string.join(distro.kernel.split('/')[-2:-1], '')

I'm pretty new to Cobbler and Uyuni. We have a running Spacewalk 2.10 and I'm investigating porting this to Uyuni.

When I call a cobbler order on the "old" Spacewalk I get something like this when calling the URL:

wget http://212.84.201.155/cblr/svc/op/gpxe/mac/00:50:56:9a:d4:eb

#!ipxe
isset $iface || set iface:string net0
set os_breed:string redhat
set os_version:string rhel7
set os_hostname:string jrdtest.info-ag.de
initrd --name initrd.img http://212.84.201.155/cobbler/images/CentOS7_x86_64:1:QSCAG/initrd.img
chain http://212.84.201.155/cobbler/images/CentOS7_x86_64:1:QSCAG/vmlinuz ip=${${iface}/ip}::${${iface}/gateway}:${${iface}/netmask}:jrdtest.info-ag.de:deploy0:none ifname=deploy0:${${iface}/mac} inst.ks.sendmac lang= noparport nomodeset text net.ifnames=0 nofirewire nopcmcia ks=http://212.84.201.155/cblr/svc/op/ks/system/jrdtest-CI123456:1 initrd=initrd.img

Am I doing something wrong on Uyuni or is this a bug??

Any help/hints greatly appreciated.

Thanks in advance

Joerg

**Comment by mcalmer** [comment]
spacewalk 2.10 is using cobbler 2.0 while Uyuni uses cobbler 3.0 . So there is a big difference.
But I am not sure if this is here the problem.

@SchoolGuy did this came along your way already?

**Comment by SchoolGuy** [comment]
So no I didn't came across this but the reason this is occurring is straightforward if you know Python (which doesn't excuse the bad error handling).

The reason we are failing here is the following: We are using the join method completely wrong in this line and thus this will always fail. So this is a Cobbler Bug.

Please change the line 800 in tftpgen.py from

```python
distro_mirror_name = str.join(distro.kernel.split('/')[-2:-1], '')
```

to

```python
distro_mirror_name = ''.join(distro.kernel.split('/')[-2:-1])
```

This is appearing twice in that file. So please replace it twice this way. I am not sure if this works because I didn't test it (and I don't have a setup to do) but in theory that should do the trick.

CC @brejoc Could you maybe give this as a small task to Dominik. This seems like something he could enjoy?

**Comment by brejoc** [comment]
@SchoolGuy @nodeg is currently either in school or on vacation. SR to `systemsmanagement / cobbler` can be found here: https://build.opensuse.org/request/show/845695

**Comment by SchoolGuy** [comment]
@brejoc I will check it out later today.

**Comment by brejoc** [comment]
SR got accepted, closing the issue.
