### ISSUE TITLE
Wrong Icon shown in View "Recently Registered Systems" https://uyuni-srv.corp.lan/rhn/systems/Registered.do

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni#2632]
Problem: all servers/systems are shown with "physical system" icon

@Developer: please display the correct icon ("physical" or "virtual") per system.
https://uyuni-srv.corp.lan/rhn/systems/Registered.do

**Comment by mcalmer** [comment]
I think this was fixed already. If you can reproduce it with a current version of Uyuni, please open a new issue. Thanks.
