### ISSUE TITLE
Strange issue with RHEL8 client 

### ISSUE THREAD

**Issue by suhailsid** [uyuni-project/uyuni#2652]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_
Version        : 2020.09-98.2.uyuni

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

issue when I adding  redhat 8 clients its override the other client on same salt keys .
for example :-
i added on rhel 8 client name A .
when I add another redhat 8 client B it override on A  

So Client name in SuSE manager showing B but hostname under system info Showing A.
what cause of this issue hennaing
![Capture](https://user-images.githubusercontent.com/35805910/94229020-feec3100-ff06-11ea-990c-2f695fa36066.PNG)
 with RHEL8 clients only build by VMware same template.

**Comment by Shirocco88** [comment]
> i added on rhel 8 client name A .
when I add another redhat 8 client B it override on A
...
with RHEL8 clients only build by VMware same template.

@suhailsid 
Have you alreade done the "sysprep for Linux" 
After cloning you need to change "non unique" object ids
ensure that content of file /etc/machine-id is unique on all salt-clients
command to check "cat /etc/machine-id"

**Comment by suhailsid** [comment]
Yes , i tired this and issue now fixed , thanks for your help.
