### ISSUE TITLE
SLES 11 SP4 LTSS and Client Repo?

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#2687]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2020.09-98.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.09-98.2.uyuni.src
Summary        : Uyuni Server

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

First Question:
On our old SMT SLES 12 SP3 Installation there is a LTSS SLE 11 Update Repo. I can't find it on Uyuni. But I can see there is a LTSS for SLES 12 in Uyuni. Why I can't see/access the SLE 11 LTSS from Uyuni?

Second Question:
After enabling SLE-11 SP4 I got bootstrapping error from Uyuni. I can't find SLE 11 Client Tool Repos from Uyuni. How I can manage SLE 11 with Uyuni without the bootstrapping error mesages.

Regards

**Comment by mcalmer** [comment]
Q1: If you have a subscription for SLE11 SP4 LTSS it should be there. But it is not a products (like in SLE12 and later) it is just a channel which is marked as optional. You can enable it on the commandlin only.

  $> mgr-sync list channel
  $> mgr-sync add channel sles11-sp4-ltss-updates-x86_64

Q2: As SLES 11 is EOL Uyuni do not provide own client tools channel for it. Here I can only recommend to update the systems to SLE12 or buy SUSE Manager where we have Client Tools channel for LTSS products.

**Comment by mrstigmata** [comment]
thank you!!! amazing!
I cant see the channel but I was able to add the channel
