### ISSUE TITLE
Provide way to check from UI the filename of created OS image

### ISSUE THREAD

**Issue by calancha** [uyuni-project/uyuni#2701]
This issue comes from: https://github.com/SUSE/spacewalk/issues/12540

In the test suite, after we successfully build an OS kiwi image, we check
that the name of the image matches the expected value.

This is the scenario for this check:
https://github.com/uyuni-project/uyuni/blob/b78556bd92ff562d4c110267c486b3a410b1092c/testsuite/features/secondary/buildhost_osimage_build_image.feature#L41

The following step navigates to the directory in the server where those OS images are stored:
https://github.com/uyuni-project/uyuni/blob/b78556bd92ff562d4c110267c486b3a410b1092c/testsuite/features/step_definitions/docker_steps.rb#L33

Note how this step leaves the SUMA UI to verify the name of the created image: it uses `visit(URL)`.

This opens the following question: is this a valid user workflow?
I.e., do users might want to check the name of the created OS images?

If the answer is affirmative, then we might want to provide such information
somewhere in the UI accessible by the menus.

**Comment by aaannz** [comment]
This is a good question. In retail formulas we do not care about the actual path and filename of the image, we are interested only in image name as kiwi knows it. ... And checking this we do not print it anywhere either.

I think it does not hurt to provide direct link to generated image in the UI, but AFAIK this UI is shared with containers where I don't think direct link to container image is useful at all.
What should be fixed is that at least image name is updated after image is generated to correspond to what is in the config.xml and thus in pillars and used in the rest of retail.

**Comment by calancha** [comment]
Moved this card (description and comments) to Spacewalk under Pau's request.
