### ISSUE TITLE
How to run custom states?

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#2704]
# Additional Information

https://github.com/uyuni-project/uyuni-docs/pull/807 to be merged first.

## Version of Uyuni Server and Proxy (if used)

Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2020.09-98.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.09-98.2.uyuni.src
Summary        : Uyuni Server

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

I created a test.sls file in /srv/salt and I can run it via salt -I 'group_ids:12' state.apply ''test'' without a problem it works on the client. But how can I get Uyuni that this state is executed at highstate? What do I wrong?

Thx and Regards

**Comment by mcalmer** [comment]
AFAIK you need to adapt /srv/salt/top.sls . Try to find sombody who can give an example

**Comment by agraul** [comment]
@mrstigmata as you probably already know, Uyuni's system groups are targeted as pillars. `salt -I 'key:value' do.something` is the way to target minions via its pillar data on the CLI. For highstates, you need to create a mapping in `/srv/salt/top.sls` as @mcalmer said. A short example that maps the "test" state to system group 12 would be:
```yaml
# /srv/salt/top.sls
base:
  'group_ids:12':
    - match: pillar
    - test
```
There are more ways to match target minions, take a look at [saltstack's documentation](https://docs.saltstack.com/en/latest/ref/states/top.html#advanced-minion-targeting) for more information.

**Comment by paususe** [comment]
@keichwa can we add this to our docs? It seems a fairly common use case.

**Comment by Loquacity** [comment]
> @keichwa can we add this to our docs? It seems a fairly common use case.

@keichwa you might want to piggy back on this PR: https://github.com/uyuni-project/uyuni-docs/pull/807

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

>> @keichwa can we add this to our docs? It seems a fairly common use case.
>
> @keichwa you might want to piggy back on this PR:
> https://github.com/uyuni-project/uyuni-docs/pull/807

Yes, thanks, I'll take a look!

-- 
Karl Eichwalder
