### ISSUE TITLE
Documentation update about new Menu labels

### ISSUE THREAD

**Issue by ncounter** [uyuni-project/uyuni#271]
Thanks to @amannch now we have better labels in the menu tree to prevent redundancies. :+1: 

See the [Uyuni PR](https://github.com/uyuni-project/uyuni/pull/259).

Useful screenshots are available in a previous *invalid* PR [here](https://github.com/SUSE/spacewalk/pull/5929).

The changes are targeting Uyuni only.

CC-ing doc-squad-coordinator: @Loquacity :wink:

**Comment by juliogonzalez** [comment]
@ncounter we can close this, right? Do I understand correctly that this was fixed by https://github.com/uyuni-project/uyuni/pull/259?

**Comment by Loquacity** [comment]
Why is this one closed? I can't see where the docs changes happened?

**Comment by ncounter** [comment]
@Loquacity I checked some of the changes and they already are in the docs (for instance `Software > Channel List`) but others are not actually (like `Patches > Patch List` is still `Patches > Patches`). No idea why some are in and some not.

Sorry for closing this too early. Reopening. :+1:

**Comment by Loquacity** [comment]
We've probably picked some up organically as we've been working on other things. Thanks for clarifying :)
