### ISSUE TITLE
Cobbler sync still fails to proxy

### ISSUE THREAD

**Issue by megamaced** [uyuni-project/uyuni#2715]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
2020.09

## Details about issue
I have a Uyuni Server and 1 Uyuni Proxy. I have updated some PXE profiles on the server and trying to sync them to the Proxy using `cobbler sync`. 

I have attached the output

I tried running the scripts again but this did not resolve the issue https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-proxy-setup.html#uyuni-proxy-setup-pxe

I previously reported that cobbler sync does not work here https://github.com/uyuni-project/uyuni/issues/1200

Thank you

[cobbler_sync.log](https://github.com/uyuni-project/uyuni/files/5371816/cobbler_sync.log)

**Comment by mcalmer** [comment]
> uploading to proxy myproxyserver.domain.co.uk failed: HTTP Error 500: Server Error
> Push failed

We would need the apache logs from the proxy. There should be more information about why it is not working

**Comment by aaannz** [comment]
I am going to close this issue. We identified some possible problems during tftpsync-recv configuration on proxy which could result in apache misconfiguration and fixed them already.
If cobbler sync is still failing, feel free to reopen or open new issue and provide proxy apache logs.
