### ISSUE TITLE
Support of CentOS 8 AppStream modules in Uyuni

### ISSUE THREAD

**Issue by agayon** [uyuni-project/uyuni#2791]
Running on Uyuni 2020.09, I am trying to manage the AppStream modules of the CentOS 8 registered clients.

I have followed this procedure [appstream_filters](https://www.uyuni-project.org/uyuni-docs/uyuni/administration/content-lifecycle-examples.html#_appstream_filters) however my understanding is that a filter needs to be created for each existing module.

Knowing that there are almost 60 modules in CentOS8, the best way would be to use the "matches" matcher to select all the modules at once as describe here [filter_rule_parameter](https://www.uyuni-project.org/uyuni-docs/uyuni/administration/content-lifecycle.html#_filter_rule_parameter)

However 'equals' matcher only  is present when "Module (Stream)" filter type is selected:

![image](https://user-images.githubusercontent.com/48300548/98097781-c50b3480-1e8d-11eb-97fb-427dc7af27a1.png)

Not sure if this is a bug or not, but right now it seems complicate to manage CentOS 8 clients with Uyuni.

Is there perhaps a better way ? Or perhaps some improvements in Uyuni are coming not to have to go through CLM to manage AppStream modules ?

**Comment by cbbayburt** [comment]
Hi @agayon,

> I have followed this procedure appstream_filters however my understanding is that a filter needs to be created for each existing module.

This is correct, but you only need filters for modules you want to be included in your repository, and that is the point. Depending on the client's purpose, you'd only need a few modules selected on any group of clients. It's not a common case to have all the modules enabled for a client.

This is also the intention at the upstream when introducing modules. Unlike base packages, every module has a specific purpose.

If you have multiple client groups with different needs, it's best to have separate projects with different module filters for them.

That being said, I know some other users have the same need as you. @bjin01 has written a nice script to use for this purpose. Please check it out: https://github.com/bjin01/patchsystems/tree/master/contentlifecyclemgmt

We don't have a native way of achieving this in Uyuni currently, but UX-wise, any suggestions are welcome.

**Comment by digdilem** [comment]
As per email discussion on the list today with Michael Calmer and Allen Beddingfield, bumping this issue. 

Affects: Centos8 (Also Rhel/Fedora/Rocky/Alma/Amazon/Alibaba etc) ALL rhel8 derived issues, plus several compatible individual repos like MariaDb 10.5 for Centos 8. This issue likely to increase in effect. 

Ideal solution for us is that Uyuni responds to *8 clients exactly as the Master repo that Uyuni is syncing from, even if that repo has modules. 

Current best workaround I've found: Add CentOS8-AppStream.repo as a local .repo file for each client, which then fetches module affected files from the Master repo, bypassing Uyuni.

Notable things:

- Using CLM is not a viable option for us. Or rather, it is, but adds a whole new work process that we don't currently use. 
- Pulp has had the same issue and reportedly solved it - there may be inspiration there. 

Thank you

**Comment by cbbayburt** [comment]
> Ideal solution for us is that Uyuni responds to *8 clients exactly as the Master repo that Uyuni is syncing from, even if that repo has modules.

@digdilem this should be possible if you sync CentOS 8 channels into Uyuni and then assigning them directly to clients. The only caveat is that you need to use the client's CLI to do updates since Uyuni UI doesn't know about parallel streams.

**Comment by digdilem** [comment]
@cbbayburt - Sadly it does  not work that way. "dnf update" returns a lot of module related errors.

**Comment by digdilem** [comment]
It appears that the modules.yaml file is not being updated when the repo syncs. 

And, apparently, no longer being created for a new repo containing modules.


Attached conversation relating to this issue from the mailing list for context.

[bug.txt](https://github.com/uyuni-project/uyuni/files/6638445/bug.txt)

**Comment by mcalmer** [comment]
I see the problem. Current CentOS compress modules.yaml using `.xz` but our (old) code only know `.gz`.
the good news is, that I reacently fixed it in this PR:
   https://github.com/uyuni-project/uyuni/pull/3834 

@juliogonzalez  - we need to add this to Uyuni 2021.06 release

**Comment by juliogonzalez** [comment]
OK, It has the merge candidate, so it will be part of 2021.06.

Thanks for the fix.

**Comment by digdilem** [comment]
Excellent news, thanks both!

**Comment by EthanB11** [comment]
@mcalmer @juliogonzalez Did this get merged into 2021.06 or 2021.08? 

I am having issues syncing Fedora 32-34 due the what looks like only having the .xz comp file. But what is also interesting is the log file shows a comp file name that doesn't match the directory listing of the files.

Sync log
```
2021/08/18 10:48:07 -05:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'fedora34-x86_64', '--type', 'yum', '--non-interactive']
2021/08/18 10:48:07 -05:00 Sync of channel started.
2021/08/18 10:48:14 -05:00 
2021/08/18 10:48:14 -05:00   Importing comps file 6522f32f97f6130551a976fbd8f0c330bf2c845a5e4e0c02693ead4dae7288a1-comps-Everything.x86_64.xml.
2021/08/18 10:48:14 -05:00   Renaming non-standard filename 6522f32f97f6130551a976fbd8f0c330bf2c845a5e4e0c02693ead4dae7288a1-comps-Everything.x86_64.xml to comps.x86_64.xml.
2021/08/18 10:48:14 -05:00 Unexpected error: <class 'FileNotFoundError'>
2021/08/18 10:48:14 -05:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 593, in sync
    self.import_groups(plugin)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 841, in import_groups
    abspath = self.copy_metadata_file(plug, groupsfile, 'comps', relative_comps_dir)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 795, in copy_metadata_file
    src = fileutils.decompress_open(filename)
  File "/usr/lib/python3.6/site-packages/uyuni/common/fileutils.py", line 511, in decompress_open
    file_obj = codecs.open(filename, 'r', encoding="utf8")
  File "/usr/lib64/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/rhn/reposync/1/External___Fedora_34__x86_64_/var/cache/zypp/raw/fedora34-x86_64/repodata/6522f32f97f6130551a976fbd8f0c330bf2c845a5e4e0c02693ead4dae7288a1-comps-Everything.x86_64.xml'
```

Directory listing
```
foohost:/var/cache/rhn/reposync/1/External___Fedora_34__x86_64_/var/cache/zypp/raw/fedora34-x86_64/repodata # ll
total 30220
-rw-r--r-- 1 root root   257176 Aug 18 10:48 3c36c82cf344497420f33a181ea9aa6d7f23d9bd506099993c1b3bfb3292cf2e-comps-Everything.x86_64.xml.xz
-rw-r--r-- 1 root root   477025 Aug 18 10:48 70347b9dac1250f8548b2428392db9d4a869cc9b549950547e25e3044542673b-comps-Everything.x86_64.xml.zck
-rw-r--r-- 1 root root 30196531 Aug 18 10:48 8a86f4f966bb4a95b3e954356ef33727a0ca0fbe583722288cfd2a9dafea90b7-primary.xml.zck
-rw-r--r-- 1 root root     6285 Aug 18 10:48 repomd.xml
```

**Comment by juliogonzalez** [comment]
If you mean https://github.com/uyuni-project/uyuni/pull/3834, then yes. It's part of 2021.08, and most likely part of 2021.06

**Comment by phibid** [comment]
> Ideal solution for us is that Uyuni responds to *8 clients exactly as the Master repo that Uyuni is syncing from, even if that repo has modules.

Can't wait to see this implemented in Uyuni ! :-) Is there some progress regarding this ?

**Comment by digdilem** [comment]
I think this may be solved. 

Apart from an issue for 24h after Rocky 8.5 was released (turns out someone made an error with the mirrors), Uyuni has been performing perfectly with Rocky 8, including importing errata and handling the previously problematic modules.

I can't vouch for other EL8 based repos, including stream, though.

**Comment by cbbayburt** [comment]
> I have followed this procedure appstream_filters however my understanding is that a filter needs to be created for each existing module.
>
> Knowing that there are almost 60 modules in CentOS8, the best way would be to use the "matches" matcher to select all the modules at once as describe here filter_rule_parameter

To address the issue in the original description, now we have a new functionality called "AppStream modules with defaults" filter template.

On the filter creation dialog, you can click on "Use a template" and select the "AppStreams with defaults" from the dropdown list. When you click "Save", it will create a filter for each module in the specified repository and, if initiated from inside the project's page, it will add all the filters to the project.

<img width="608" alt="130215823-25357e9c-3479-47f7-8ed4-01a83338ef78" src="https://user-images.githubusercontent.com/1103552/143229390-947b2a05-f9d0-4cf1-966f-a1079907550a.png">
