### ISSUE TITLE
Deploying Configuration Files results in salt-minion[3751]: [ERROR   ] Source file salt://manager_org_1/1000010016/motd not found in saltenv 'base'

### ISSUE THREAD

**Issue by vega82** [uyuni-project/uyuni#2794]
Hi,

we use a fresh installes Uyuni  2020.09 and try to deploy Configuration Files to some Clients.

I created a ConfigChannel "global_motd".
In it with a state file wich contains following content:
![motd](https://user-images.githubusercontent.com/2478621/98209873-f6dcd380-1f3f-11eb-8092-c6faea7f4549.JPG)

and a configuration File
![motd2](https://user-images.githubusercontent.com/2478621/98209834-e9274e00-1f3f-11eb-95d4-2c84f9e9c3f0.JPG)

This also looks fine on cli.
But if i deploy this to my clients, the salt-minion on this clients resume an error:
salt-minion[3751]: [ERROR   ] Source file salt://manager_org_1/1000010016/motd not found in saltenv 'base'

I have no idea, where they get this connectionstring from.

**Comment by mcalmer** [comment]
@admd can you remember how this was implemented and why it look for a different path?

**Comment by admd** [comment]
@mcalmer haven't seen this before and I can't think of anything particular which could cause this issue. 

@vega82 can you please tell us how you are deploying the file to the minions?

**Comment by mcalmer** [comment]
The underlying backend has changed. I think these problems should be fixed. Please open a new issue if you can still reproduce this problem. Thanks.
