### ISSUE TITLE
display absolute timestaps for configuration files

### ISSUE THREAD

**Issue by sejo23** [uyuni-project/uyuni#2803]
On file detail and revisions pages times for creation date and last modified are shown as relative times (for instance "7 weeks ago").
This is to inaccurate in some cases like multiple changes in short time.

Is it possible to (maybe optionally) show absolute times for creation date and last modified?

**Comment by mcalmer** [comment]
Does a "mouse over" provide you a tooltip with the exact timestamp? AFAIK it should do it.

**Comment by sejo23** [comment]
Sorry, I can't find any "mouse over" messages  in uyuni web-gui. Tested with firefox 78.3, IE 11 and chromium 86.0 (on Windows).
