### ISSUE TITLE
Typo in patch documentation

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#2822]
On page: https://www.uyuni-project.org/pages/patches.html

Step 4 reads

`sudo zypper update:`

The trailing colon shouldn't be there. It breaks this command and should be removed.

**Comment by mcalmer** [comment]
@juliogonzalez not sure if this comes from our doc team or from you.

**Comment by juliogonzalez** [comment]
Website is not maintained by the doc team, but mostly by me... with help from other people, of course.

@digdilem can you create a PR? It's something easy for a first contribution. The site repository is at https://github.com/uyuni-project/uyuni-project.github.io

You just need to fork it, fix the typo and submit a PR.

Otherwise I will do it later.

**Comment by digdilem** [comment]
Julio - Not done one of those, but happy to give it a try, definitely
something I should know how to do and as you say, something that should be
simple. Leave with me, please!

**Comment by juliogonzalez** [comment]
Great! Thanks! :-)

A nice guide about using forks is https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo

When the fork is created, you can clone it and create a branch from master, and finally you can submit your change from that branch as PR.

So in the end:

1. Create a fork
2. Clone it to your computer (`git clone ....`)
3. Switch to the folder created by the clone
4. Create new branch (`git branch -b fix-typo-patching`)
5. Do your changes, commit, and push. That will give you the URL to create the PR.
6. Create the PR.

I am not 100% sure, but I think this can also be done directly from the GitHub WebUI if you try to edit the file via WebUI. Maybe you can give it a try as well.

**Comment by digdilem** [comment]
Thanks for the guide, @juliogonzalez 

I /think/ I've done it (via Github's webui) and the PR will hopefully be showing now.

**Comment by juliogonzalez** [comment]
PR merged. Thanks for the contribution!

The website will take a few minutes to get this updated, while GitHub regenerates the site.
