### ISSUE TITLE
Since the last security update for the salt stack, the status of some clients is not displayed correctly.

### ISSUE THREAD

**Issue by StefanSa** [uyuni-project/uyuni#2824]
# Additional Information
Since the last security update for the salt stack, the status of some clients is not displayed correctly.
Either patches to be installed are displayed although they are already installed, or the clock symbol is displayed indicating that patches are being installed.
Such erroneous status messages have not seen before this security patch.

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` 
```
Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : @System
Name               : Uyuni-Server-release
Version            : 2020.09-98.2.uyuni
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Installierte Größe : 1,4 KiB
Installiert        : Ja
Status             : aktuell
Quellpaket         : Uyuni-Server-release-2020.09-98.2.uyuni.src
Zusammenfassung    : Uyuni Server
Beschreibung       :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```
## Details about issue
![System-Status](https://user-images.githubusercontent.com/6105075/98681821-749b4780-2363-11eb-9317-4a238e67efa4.png)
![Statsu_02](https://user-images.githubusercontent.com/6105075/98682157-e2477380-2363-11eb-9539-cfea929531c7.png)

```
{
  "file_|-mgrchannels_repo_|-/etc/zypp/repos.d/susemanager:channels.repo_|-managed": {
    "changes": {},
    "comment": "File /etc/zypp/repos.d/susemanager:channels.repo is in the correct state",
    "name": "/etc/zypp/repos.d/susemanager:channels.repo",
    "result": true,
    "__sls__": "channels",
    "__run_num__": 0.0,
    "start_time": "14:26:37.934111",
    "duration": 63.69,
    "__id__": "mgrchannels_repo"
  },
  "pkg_|-mgr_regular_patches_|-mgr_regular_patches_|-patch_installed": {
    "name": "mgr_regular_patches",
    "changes": {},
    "result": true,
    "comment": "All specified advisory patches are already installed",
    "__sls__": "packages.patchinstall",
    "__run_num__": 1.0,
    "start_time": "14:26:45.696065",
    "duration": 2593.133,
    "__id__": "mgr_regular_patches"
  }
}
```

**Comment by StefanSa** [comment]
Hi there,
any information about this behavior?

**Comment by meaksh** [comment]
Hi @StefanSa ,
the "clock" is shown when there is still a "pending / picked up" actions. How the "Events -> History" look for on of those clients? 

Maybe there are some stuck actions there that might be cancelled.

**Comment by StefanSa** [comment]
Hi @meaksh 

i found this with all affected clients
```
  "pkg_|-mgr_regular_patches_|-mgr_regular_patches_|-patch_installed": {
    "name": "mgr_regular_patches",
    "result": false,
    "changes": {},
    "comment": "An error was encountered while downloading package(s): Advisory id \"openSUSE-2020-1905\" not found",
    "__sls__": "packages.patchinstall",
    "__run_num__": 2.0,
    "start_time": "10:16:09.459087",
    "duration": 4813.12,
    "__id__": "mgr_regular_patches"
  }
```

**Comment by meaksh** [comment]
@StefanSa could you please schedule a "Highstate" action and also a "Package Profile Refresh" (Software -> Update Package List) action for those systems?

That should make sure the channels are properly set and the actual package profile from those minions is updated on SUMA.

After those actions are completed. You would need to wait some minutes until the "errata-cache" taskomatic job is executed (every few minutes) to see the "System Status" (available patches) is refreshed. 

You can also trigger the "errata-cache" job manually by clicking into "Admin -> Task Schedules -> errata-cache-bunch -> Single run schedule".

Let see if that fixes the issue.

**Comment by StefanSa** [comment]
hi Pablo @meaks, muchas graciash.
Thanks to your competent help, everything is OK again.
Greetings to my beloved Canary Islands. 
You can close this ticket.

**Comment by meaksh** [comment]
@StefanSa great to hear that!

Thank you! Your greetings are really welcomed here :beach_umbrella: :volcano:  :canary_islands:  :smile:
