### ISSUE TITLE
Installed Products field in ppc64le centos 7 traditional client is empty

### ISSUE THREAD

**Issue by ktsamis** [uyuni-project/uyuni#2905]
# Additional Information

The `Installed Products:` field in ppc64le centos 7 traditional client is empty. 

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_
```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-devel
Name           : Uyuni-Server-release
Version        : 2020.11-99.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
```
No proxy used.

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
bootstrapped a centos 7 ppc64le client with traditional script. I used the `spacewalk-common-channels` with these mirrored:
```
CentOS 7 (ppc64le)
Uyuni Client Tools for CentOS 7 (ppc64le) (Development)
CentOS 8 (ppc64le)
Uyuni Client Tools for CentOS 8 (ppc64le) (Development)
```
All smoke tests, actions work, except the  `Installed Products:` field is empty.

**Comment by ktsamis** [comment]
On salt ssh, same product I have:
```
Installed Products: | unknown
```

**Comment by mcalmer** [comment]
This is normal as we show only products in SCC DB. But afaik we do not have ppc64(le) EL products in SCC.
