### ISSUE TITLE
ubuntu 16.04 security repo missing

### ISSUE THREAD

**Issue by eins** [uyuni-project/uyuni#2911]
Hello Folks
I added ubuntu 16 base repo
```
# spacewalk-common-channels \
  ubuntu-1604-pool-amd64-uyuni \
  ubuntu-1604-amd64-main-uyuni \
  ubuntu-1604-amd64-main-updates-uyuni \
  ubuntu-1604-amd64-main-security-uyuni \
  ubuntu-1604-amd64-universe-uyuni \
  ubuntu-1604-amd64-universe-updates-uyuni \
  ubuntu-1604-amd64-uyuni-client
```
just I saw in uyuni documentation, and 1604 channels are very similar to the 1804 repositories
 https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-ubuntu-old.html

I don't have the ubuntu-1604-amd64-main-security-uyuni  repository

If I try to add that particular repository I have this output:
```
# spacewalk-common-channels \                                                                                                                           
 ubuntu-1604-pool-amd64-uyuni \
 ubuntu-1604-amd64-main-security-uyuni
SUSE Manager username: eins
SUSE Manager password:
No channels matching your selection.
```

I don't want to delete the whole 1604 repository and sync all over again.
do I need to add the repo from uyuni web ?

**Comment by juliogonzalez** [comment]
The correct name for 16.04 is `ubuntu-1604-amd64-security-uyuni`.

We'll need a fix for the doc.

@Loquacity this a bug for you. The repositories are:

- ubuntu-1604-pool-amd64-uyuni
- ubuntu-1604-amd64-main-uyuni
- ubuntu-1604-amd64-updates-uyuni
- ubuntu-1604-amd64-security-uyuni
- ubuntu-1604-amd64-universe-uyuni
- ubuntu-1604-amd64-universe-updates-uyuni
- ubuntu-1604-amd64-uyuni-client

**Comment by juliogonzalez** [comment]
@eins or if you feel breave, you can fix this with a PR for this: https://raw.githubusercontent.com/uyuni-project/uyuni-docs/master/modules/client-configuration/pages/clients-ubuntu-old.adoc

**Comment by eins** [comment]
added pull request with the line that we talked about it
ubuntu-1604-amd64-security-uyuni

I couldn't find a way to add a realistic example:

```
# ubuntu 16 04
spacewalk-common-channels \
 ubuntu-1604-pool-amd64-uyuni \
 ubuntu-1604-amd64-main-uyuni \
 ubuntu-1604-amd64-main-updates-uyuni \
 ubuntu-1604-amd64-security-uyuni \
 ubuntu-1604-amd64-universe-uyuni \
 ubuntu-1604-amd64-universe-updates-uyuni \
 ubuntu-1604-amd64-uyuni-client

# ubuntu 18 04
spacewalk-common-channels \
ubuntu-1804-pool-amd64-uyuni \
ubuntu-1804-amd64-main-uyuni \
ubuntu-1804-amd64-main-updates-uyuni \
ubuntu-1804-amd64-main-security-uyuni \
ubuntu-1804-amd64-universe-uyuni \
ubuntu-1804-amd64-universe-updates-uyuni \
ubuntu-1804-amd64-uyuni-client

# ubuntu 20 04
spacewalk-common-channels \
ubuntu-2004-pool-amd64-uyuni \
ubuntu-2004-amd64-main-uyuni \
ubuntu-2004-amd64-main-updates-uyuni \
ubuntu-2004-amd64-main-security-uyuni \
ubuntu-2004-amd64-universe-uyuni \
ubuntu-2004-amd64-universe-updates-uyuni \
ubuntu-2004-amd64-uyuni-client
```

and the warning if you need to add one channel:
```
spacewalk-common-channels ubuntu-1604-amd64-security-uyuni
```

**Comment by juliogonzalez** [comment]
> I couldn't find a way to add a realistic example:

At the doc? No need, just you just need to adjust the channel names on the table. I think you need to adjust more than one, notice that ` ubuntu-1604-amd64-main-uyuni ` and `ubuntu-1604-amd64-main-updates-uyuni` are not right for ubuntu16.04 (compare it with the list I gave above).

> and the warning if you need to add one channel:

What warning :-?

**Comment by eins** [comment]
Oh you are right I fixed two:
+ ubuntu-1604-amd64-updates-uyuni
+ ubuntu-1604-amd64-security-uyuni
you added ubuntu-1604-amd64-main-uyuni . is this correct ?

About the warning, I mean there isn't so much information in that particular package about what to do if you need to add a particular channel like ubuntu-1604-amd64-security-uyuni
it isn't a warning though

**Comment by juliogonzalez** [comment]
> you added ubuntu-1604-amd64-main-uyuni . is this correct ?

This one was already there. I gave the complete list on this issue so it could be verified on the doc. PR looks good now.

> About the warning, I mean there isn't so much information in that particular page about what to do if you need to add a missing channel like ubuntu-1604-amd64-security-uyuni
> it isn't a warning though

Well, it's an ERROR IIRC. And in such case it's either that you wrote the wrong name, or (most likely, such in this case) that the doc has a bug.

We could tell users to check the file `spacewalk-common-channels.ini`, but maybe they'd be scared about it, and in this case you came to ask to ask, and thanks to this (and your PR) the bug will be fixed :-)
