### ISSUE TITLE
Add possibility to automate initial organization/user creation

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#296]
**Is your feature request related to a problem? Please describe.**
I'm currently writing a Chef cookbook for automating Uyuni test deployments.
After installing Uyuni, the first organization still needs to be created using
the web page.

I understand that there is an automation tool `spacecmd`, but this seems not to
work if no organization or admin user exist:

```
# spacecmd org_create
Spacewalk Username:
Spacewalk Password:
ERROR: Invalid credentials
```

I figured out that entering no username/password does not work (*also not via
the `.spacecmd/config` file*) - so therefore the error message seems legit.

**Describe the solution you'd like**
It would be great if `spacecmd` would work without username/password for the first setup or supply a dedicated command for this, e.g. `spacecmd initial_setup`

**Describe alternatives you've considered**
As a workaround, I'm using `curl` to get the CSRF token and send a POST request to the appropriate script:

```
csrf="$(curl --insecure https://localhost/rhn/newlogin/CreateFirstUser.do |
grep csrf | grep -o 'value=.*' | tr -d 'a-zA-Z">=')"
curl --insecure -d
"csrf_token=$csrf&submitted=true&orgName=demoOrg&login=admin&desiredpassword=Mimimi01&desiredpasswordConfirm=Mimimi01&email=info@xxxxxxxxxxxx&firstNames=Paula&lastName=Pinkepank"
-X POST https://localhost/rhn/newlogin/CreateFirstUser.do
```

**Additional context**
See also the discussion on the mailing list: https://lists.opensuse.org/uyuni-devel/2018-11/msg00009.html

**Comment by moio** [comment]
As a side note, we use the same workaround in our Salt files: https://github.com/uyuni-project/sumaform/blob/master/salt/server/initial_content.sls#L18-L34

**Comment by wombelix** [comment]
Thank you @moio for your Feedback on the devel list, happy to give this task a try :)

My understanding is, that every module in spacecmd actually interact with the xmlrpc api and right now the org creation endpoint requires valid Credentials. So adding this functionality to spacecmd would mainly required adjusting the API to work without Authentication if no User exist yet?
Because implementing it based on the above Workaround doesn't seems like the spacecmd way?

Or, to have everything regarding the initial Setup in one Place, should it be part of mgr_setup instead?

**Comment by moio** [comment]
We aim at keeping all of the functionality available in the UI also available in the (public XMLRPC) API. At the moment, the creation of the very first User and Organization is only possible in the UI, so there is a gap to fill there. We need a new method.

Most of the API methods require authentication, but there are exceptions to this rule. This endpoint should be such an exception, as it is only needed once at the very first setup (it should just raise an Exception if the initial User and Organization already exist).

Usage of the XMLRPC API requires that all other components are completely and correctly set up, ie., mgr_setup should be finished. I think it is perfectly OK to surface this in `spacecmd`.

**Comment by wombelix** [comment]
> We aim at keeping all of the functionality available in the UI also available in the (public XMLRPC) API. At the moment, the creation of the very first User and Organization is only possible in the UI, so there is a gap to fill there. We need a new method.
> 
> Most of the API methods require authentication, but there are exceptions to this rule. This endpoint should be such an exception, as it is only needed once at the very first setup (it should just raise an Exception if the initial User and Organization already exist).
> 
> Usage of the XMLRPC API requires that all other components are completely and correctly set up, ie., mgr_setup should be finished. I think it is perfectly OK to surface this in `spacecmd`.

Thanks, make sense, also as soon it's available via spacecmd, it still could be triggered as last step from mgr_setup in case a full end to end setup through one interface is required at a later point.

I already have some ideas how to tackle that, will create a WIP PR shortly.
