### ISSUE TITLE
Enabling monitoring is not possible in Uyuni 2020.11

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#2973]
# Additional Information

Enabling the integrated monitoring in accordance with [the documentation](https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/administration/monitoring.html#_configure_suse_manager_monitoring) is not working.
When clicking the "**Enable**" button, the following error is written to the Tomcat log:

```
2020-12-05 09:47:08,581 [ajp-nio-127.0.0.1-8009-exec-3] ERROR com.suse.manager.webui.services.impl.MonitoringService - Error parsing JSON: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 3 column 10 path $.local[0]
```

## Version of Uyuni Server and Proxy (if used)
```
# zypper info Uyuni-Server-release
...
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.11-99.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.11-99.2.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

## Details about issue

See log above.

The command used to install the required modules is:

```
# zypper in golang-github-prometheus-node_exporter golang-github-wrouesnel-postgres_exporter prometheus-jmx_exporter golang-github-lusitaniae-apache_exporter prometheus-jmx_exporter-tomcat grafana-formula prometheus-formula prometheus-exporters-formula
```

**Comment by witekest** [comment]
Could you please [enable debug logging](https://github.com/uyuni-project/uyuni/wiki/Java-Logging#tomcat) and post preceding debug information? In particular I'm interested in lines containing:

`/usr/sbin/mgr-monitoring-ctl output:`

**Comment by witekest** [comment]
@stdevel Are you able to provide additional information about your system from the debug logs?

**Comment by stdevel** [comment]
Hi @witekest!
I will keep you updated with the information requested - I'm currently on vacation and have no access to the system.

Is this okay?

Best wishes!

**Comment by witekest** [comment]
That's perfectly fine.

Best wishes to you too!

**Comment by stdevel** [comment]
Hi @witekest,
I was not able to reproduce this issue in several Vagrant runs. Looks like this issue was fixed in one of the latest updates.

Thanks anyway! 👍🏻 

Best wishes,
Christian.
