### ISSUE TITLE
DB schema upgrade triggered after each Uyuni services start

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#3024]
After the upgrade from Uyuni 2020.09 to 2020.11, I can see that each time I start the Uyuni services, it tries to upgrade the DB schema:

Stopping:

```
# spacewalk-service stop
Shutting down spacewalk services...
Done.
```

Starting:

```
# spacewalk-service start
Starting spacewalk services...
  Running DB schema upgrade. This may take a while.
  Call the following command to see progress: journalctl -f -u uyuni-check-database.service
Done.
```

From the jounalctl output, I can see that no upgrade was actually necessary:

```
Dec 15 09:12:58 uyuni systemd[1]: Starting Uyuni check database...
Dec 15 09:13:07 uyuni spacewalk-startup-helper[63288]: Your database schema already matches the schema package version [susemanager-schema-4.2.3-1.1.uyuni].
Dec 15 09:13:07 uyuni spacewalk-startup-helper[63288]: Schema upgrade: [susemanager-schema-4.2.3-1.1.uyuni] -> [susemanager-schema-4.2.3-1.1.uyuni]
Dec 15 09:13:07 uyuni spacewalk-startup-helper[63288]: Searching for upgrade path to: [susemanager-schema-4.2.3-1]
Dec 15 09:13:07 uyuni spacewalk-startup-helper[63288]: Searching for upgrade path to: [susemanager-schema-4.2.3]
Dec 15 09:13:07 uyuni systemd[1]: Started Uyuni check database.
```

**Comment by juliogonzalez** [comment]
Yes, that's normal... since 2020.04 in fact: https://www.uyuni-project.org/doc/2020.11/release-notes-uyuni-server.html#_automated_schema_database_upgrades_and_failure_security_mechanism

The startup runs the DB upgrade script that checks if there's something to be applied. Nothing to worry about.

**Comment by phibid** [comment]
Ah ok. I knew that indeed the `spacewalk-schema-upgrade` was not needed anymore, but I don't remember to have seen this `Running DB schema upgrade` during each Uyuni service restart. Must be me memory playing tricks on me.

Closing this issue.

**Comment by paususe** [comment]
> Ah ok. I knew that indeed the `spacewalk-schema-upgrade` was not needed anymore

You don't need to run it manually but it's still happening (automagically) when required.

**Comment by phibid** [comment]
Automagically ? Nice word :-)

Mmmmh, when required or always ? This is my doubt now, is `spacewalk-schema-upgrade` not triggered after each and every restart (`spacewalk-service stop & stop`) ?

**Comment by mcalmer** [comment]
It is a systemd dependency and should be triggered by every "start" of the spacewalk.target .
As spacewalk-service start use this target to start all the services it will be done.
Additionally it is done when you update susemanager-schema package and the services are **not** stopped.

What we may improve in the future is a faster detection that the current schema is already applied and nothing needs to be done. But this may bring us only a few seconds.
