### ISSUE TITLE
Request: Please add support for Centos 8 Stream - Uyuni Tools

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#3043]
# Please add a new set of uyuni tools build for Centos 8 Stream

Uyuni tools will need to be rebuilt for Centos 8 Stream (A rolling upstream repo, quite separate from Centos 8 Linux)

The existing tools repo for Centos 8 Linux does not work with Stream.

## For current and future versions
As Redhat have cancelled the traditional Centos 8 Linux model, with EOL Dec 2021, the recommended action is to migrate to a new system, "Centos 8 Stream" (Not to be confused with Centos 8 Appstream, which is a traditional repo supporting Centos 8 Linux and will be EOL 2021 too).  It is likely a large number of existing Centos users will need to make this change during 2021. 

Centos 7 Linux has EOL 2024 and no change needed there.

C8 Stream will be upstream of RHEL instead of downstream and will feature much more rapidly changing packages with content controlled by Redhat rather than the community. My understanding it is forked from Fedora every 4 years. 

## Details about issue
I've moved three test servers from C8 ot C8S and it appears part of Salt functionality is no longer working. I raised this in Gitter and mailing list and it was suggested I raise this ticket for @juliogonzalez and understand it may not be an instant fix.

Thank you

# Copy of email to list for reference.
Hi

Following Redhat's announcement last week, I've moved three systems from Centos 8 Linux to centos 8 Stream. 

I've added the Stream repos to Uyuni and switched channels to them, then followed the instructions at https://centos.org/distro-faq/ 
(As Uyuni doesn't have a uyuni-tools repo for Stream, I used the same Centos 8 Linux repo)  The operation went successfully on the clients and all seemed good.   However, it later emerged some of Uyuni's salt functionality has been lost on these clients. 

What’s okay: Remote commands still work, and all scheduled instructions to these servers are picked up as before. 

What’s not okay: 

1. 
Highstate won't apply. This also breaks repos when re-running the bootstrap command: "curl -Sks https://{URL}/pub/bootstrap/bootstrap-c8.sh | /bin/bash" 
As part of the script, existing repos are disabled, and any existing susemanager:channels.repo file is removed. Normally, this file is recreated when Highstate is applied, but this now fails. (Ditto when applying via Uyuni's webui)

Error: Error: Could not parse state file. Please check YAML syntax.
On server, /var/log/salt/minion logs show things like;
2020-12-16 11:50:41,871 [salt.state       :3636][CRITICAL][36037] Rendering SLS 'base:services.salt-minion' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg.list_repos'

2. 
When running “Update Package List” via the webui (Server page: Software -> Packages)
An unexpected error has occurred. Please check the server logs.
We see
2020-12-15 14:29:41,653 [salt.utils.decorators:636 ][WARNING ][7610] The function "module.run" is using its deprecated version and will expire in version "Sodium".
2020-12-15 14:29:46,319 [salt.state       :323 ][ERROR   ][7610] Module function pkg.info_installed is not available

System info:
/etc/centos-release:  CentOS Stream release 8
salt-minion –version:  salt-minion 3000
Uyuni master is 2020-11
yum repolist:
repo id                                                                       repo name
susemanager:c8s-powertools                                                    CentOS 8-stream Powertools
susemanager:c8s_appstream                                                     Centos 8-stream Appstream
susemanager:centos8stream_x86_64                                              Centos 8 Stream (x86_64)
susemanager:uyuni_client_stream                                               Uyuni Client Tools for CentOS 8 (x86_64) Stream

To me, these two problems look linked, and I’m guessing that the Stream migration process has ‘lost’ a Salt module for package and repo management. My knowledge of salt is not good enough to diagnose this issue, and it’s proved difficult to google a way to success despite spending too much time on it yesterday.

Can someone please help?

**Comment by paususe** [comment]
Uyuni master client tools are already being built for CentOS 8 Stream:

https://build.opensuse.org/project/show/systemsmanagement:Uyuni:Master:CentOS8-Uyuni-Client-Tools

I'm not sure we can provide Uyuni stable client tools for CentOS 8 Stream, since it changes too much :-?

**Comment by juliogonzalez** [comment]
Besides enabling them, we should add all the channels to `spacewalk-common-channels` for the OS, and at least for the master client tools.

**Comment by paususe** [comment]
> Besides enabling them, we should add all the channels to `spacewalk-common-channels` for the OS, and at least for the master client tools.

That's a good point indeed.

**Comment by digdilem** [comment]
Prompted by @ppc6446 in the users Gitter, it's perhaps sensible to review this issue. 

The EL landscape has changed significantly in the past year, with the fully formed alternatives to Centos Linux (Alma, Rocky, Oracle etc) being both released and very well supported - something that was very much in doubt at the time this was created.  Ourselves and many others have now simply moved away from C8L and C8-Stream to one of those, and consider that Stream is not sufficiently stable to use in production, as per Redhat's advice.

I believe all this has reduced the need of Uyuni to support Stream to the point where I would like to withdraw this issue. That it hasn't progressed suggests there is very little need from any other quarters and probably the developer's time would be better spent elsewhere. 

As the originator, I intend to close this issue in 48 hours unless there is anyone who strongly feels it should still be actioned.

**Comment by juliogonzalez** [comment]
> Prompted by @ppc6446 in the users Gitter, it's perhaps sensible to review this issue.
> 
> The EL landscape has changed significantly in the past year, with the fully formed alternatives to Centos Linux (Alma, Rocky, Oracle etc) being both released and very well supported - something that was very much in doubt at the time this was created. Ourselves and many others have now simply moved away from C8L and C8-Stream to one of those, and consider that Stream is not sufficiently stable to use in production, as per Redhat's advice.
> 
> I believe all this has reduced the need of Uyuni to support Stream to the point where I would like to withdraw this issue. That it hasn't progressed suggests there is very little need from any other quarters and probably the developer's time would be better spent elsewhere.

If you mean the SUSE Manager developers, then that's right, as this is not in our schedule, but the community can still have a look at it.

**Comment by Shirocco88** [comment]
@digdilem 
did you test venv-salt-minion bundle with CentOS 8 Steam ?
see https://github.com/uyuni-project/uyuni/pull/3895
It salt bundle was working quite well with Debian-11;
maybe it helps you also with CentOS 8 Steam;

**Comment by digdilem** [comment]
@Shirocco88  - I didn't, no. 

And we no longer have any C8 Stream machines, nor likely to - so am unable to help with that.

**Comment by ppc6446** [comment]
CentOS 8 Stream more closely aligns with our use case than CentOS 8, so the  bundle is welcome news.  My original plan had been to use salt-ssh for CentOS 8 stream and Fedora 35, but a full salt client would of course be preferable.

**Comment by juliogonzalez** [comment]
As soon as the bundle is stable enough, we'll start adding it to the existing Uyuni client tools, and that will also allow us to support clients that otherwise would be broken.

In our plan is Debian 11. But if the community wants to help with CentOS8 Stream or Fedora, all help is welcomed :-)

**Comment by digdilem** [comment]
Closing - initial requirements changed, and salt-bundle plan will add support for less popular OSs.
