### ISSUE TITLE
Uyuni Container Image

### ISSUE THREAD

**Issue by kmf** [uyuni-project/uyuni#306]
Wanted to know if there is a container image for Uyuni?

**Comment by mcalmer** [comment]
No, there is not.

Uyuni and containers is challenging as it consists of multiple services which need to play together.
So you have to possibilities to build containers.

1. One big beast: write a script which starts all services in the right order and put everything in one container. (Not really the way how containers should be used but maybe easier to achieve)
2. Every single service in separate containers: Here you need an orchestration tool to start them in the right order like kubernetes. You need to write that manifest and it would require everybody to install it.

Sounds like an interesting community project.

**Comment by stdevel** [comment]
I'm currently writing a Chef cookbook for deploying Uyuni - should be able to use it along with [Packer](https://www.packer.io) in order to create a container. I can share it if you like.

**Comment by kmf** [comment]
@stdevel would be awesome

**Comment by stdevel** [comment]
> 
> 
> @stdevel would be awesome

There you go: https://github.com/stdevel/katprep/tree/feature-vagrant-issue108/tests/cookbooks/uyuni-basic

Successfully tested the cookbook along with Vagrant and Inspec on openSUSE 42.3:
![cookbook](https://user-images.githubusercontent.com/5862725/50976802-2ad84080-14f1-11e9-901d-5fcaa8a1015e.jpg)

Keep in mind, that this might be moved into my project's master branch later - so maybe this link might point to 404 later.

**Comment by matya** [comment]
From a plain ops view option 1) is not that bad, there is a real usecase on deploying one single big container and not scaling out.  Example it the Gitlab Omnibus image at https://docs.gitlab.com/omnibus/docker/README.html

**Comment by zhijianli88** [comment]
/cc

Want to know any new progress about this issue. I'm looking forward a dockerize solution so that i can deploy it flexibly.

**Comment by stdevel** [comment]
Short update on the Chef Cookbook: it is not maintained, anymore. I created an Ansible Role in the meantime: https://github.com/stdevel/ansible-uyuni/

**Comment by rjmateus** [comment]
@zhijianli88 @stdevel we are actively working on containerizing uyuni using option 2) from Michael's comments: Every single service in separate containers.
This will be a big and complex task, and we don't have a release date for it yet.
Our approach is to containerize the proxy component first, and after that start working on the server component.
If you want, you can also participate in the Uyuni community hours to check for updates/ongoing efforts and give us your feedback: https://github.com/uyuni-project/uyuni/wiki/Uyuni-Community-Hours

**Comment by zhijianli88** [comment]
> @zhijianli88 @stdevel we are actively working on containerizing uyuni using option 2) from Michael's comments: Every single service in separate containers. This will be a big and complex task, and we don't have a release date for it yet. Our approach is to containerize the proxy component first, and after that start working on the server component. 

Awesome!! Glad to know this.


> If you want, you can also participate in the Uyuni community hours to check for updates/ongoing efforts and give us your feedback: https://github.com/uyuni-project/uyuni/wiki/Uyuni-Community-Hours

Thanks for the information, i will take a look first

**Comment by zhijianli88** [comment]
> Short update on the Chef Cookbook: it is not maintained, anymore. I created an Ansible Role in the meantime: https://github.com/stdevel/ansible-uyuni/

Thanks, an ansible playbook is cool.

**Comment by mayrstefan** [comment]
Some references
- Development is done in folder [containers](https://github.com/uyuni-project/uyuni/tree/master/containers) 
- long term plan is to package it as a helm chart as stated in [HackWeek 20](https://hackweek.opensuse.org/20/projects/uyuni-slash-suse-manager-containerization-project)
- there is a [wiki](https://github.com/uyuni-project/uyuni/wiki/HackWeek-20:-Uyuni-SUSE-Manager-containerization-project) - which does not seem to reflect the current state

**Comment by trueshanti** [comment]
> Wanted to know if there is a container image for Uyuni?

!AFAIK .. but the actual installproc https://www.uyuni-project.org/pages/stable-version.html i quite straight forward .. it asks for ssl-info and a db-password .. it should quiet simple be possible to build via docker .. just if can feed yast with those variables

**Comment by mbussolotto** [comment]
uyuni container is present from version 2024.06. Closing this issue
