### ISSUE TITLE
Modify smdba to work on all Postgresql versions. [RHEL8]

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#3067]
# Additional Information
The current SMDBA implementation requires the SUSE Postgresql package installation and will fail with the error message on other installations or OS.

```
# /usr/bin/smdba
General error:
	Unknown database backend. Please check /etc/rhn/rhn.conf configuration file.
```

## Version of SMDBA
smdba-1.7.7.tar.bz2 (2021-01-04)

## Details about issue
```
<module 'smdba.postgresqlgate' from '/usr/lib/python3.6/site-packages/smdba/postgresqlgate.py'>
General error:
[Errno 2] No such file or directory: '/etc/sysconfig/postgresql'
(L231)
```
This seems to boil down to `/etc/sysconfig/postgresql` not being found on all systems (i.e. RHEL).
See line 231 from `/usr/lib/python3.6/site-packages/smdba/postgresqlgate.py` (lines 227 to 233):
```
    def _get_sysconfig(self) -> None:
        """
        Read the system config for the postgresql.
        """
        for line in filter(None, map(lambda line: line.strip(), open('/etc/sysconfig/postgresql').readlines())):
            if line.startswith('#'):
                continue

```

For example RHEL has the options from that file directly in  `/etc/systemd/system/multi-user.target.wants/postgresql.service`. So that file should also be processed. (but has a different format.)
(See: [https://superuser.com/questions/1424293/where-to-set-pgopts-variable-in-centos-7](https://superuser.com/questions/1424293/where-to-set-pgopts-variable-in-centos-7))

SMDBA lives at:
https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master/smdba
https://github.com/SUSE/smdba

**Comment by mcalmer** [comment]
CC @jordimassaguerpla

**Comment by sbluhm** [comment]
Same goes for susemanager.spec:
https://github.com/uyuni-project/uyuni/blob/c8f35edc9b69e28e2e36151e93b8d4d8af89b4b0/susemanager/susemanager.spec#L270

**Comment by jordimassaguerpla** [comment]
Hi @sbluhm ! Thanks for the report and sorry I have not answered for a while. I can't commit to look into that in the short term, but if you could provide us with a patch and how you tested it, it would certainly speed up things. Otherwise, I'll put it on my backlog and when time/priority permits I will look into it.

**Comment by sbluhm** [comment]
@jordimassaguerpla , I actually have no idea how to solve it what really is done by smdba. So I have just ignored these errors for my purposes.
I would say add it to the backlog. And if anyone finds performance issues with RHEL then we can increase the priority. (I assume smdba is meant for tuning).

**Comment by mcalmer** [comment]
Problem description:

smdba is reading some values from `/etc/sysconfig/postgresql`, but this file only exists on SUSE systems.
RedHat/CentOS use different mechanism to configure values.

1. Find out what values smdba read from that file and for what it is used
2. find ways to read these values on a RedHat system
3. implement alternative mechanism for RedHat

**Comment by sbluhm** [comment]
Nevermind, just done the RCA twice.... Didn't realise I had done it already and put it in here...

Anyways, those two PRs should address the issues:
https://github.com/SUSE/smdba/pull/49
https://github.com/uyuni-project/uyuni/pull/3994

**Comment by juliogonzalez** [comment]
@jordimassaguerpla ping ^
