### ISSUE TITLE
Add dnf backend to reposync [RHEL8]

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#3074]
# Additional Information

To synchronise packages into the Uyuni software management [reposync](https://github.com/uyuni-project/uyuni/blob/master/backend/satellite_tools/reposync.py) is used.

Reposync is using a Zypper backend to analyse and download the data from the repositories. Zypper is not available and compatible on RHEL8 systems so the dnf package manager has to be used. I.e. ~~Zypper does not support modules or groups.~~

Background: Zypper and dnf both require their own version of libsolv with own feature sets. Replacing libsolv with a custom version on RHEL would invalidate supportability to the system.

# Required Activities

Add a RHEL version of [yum_src.py](https://github.com/uyuni-project/uyuni/blob/master/backend/satellite_tools/repo_plugins/yum_src.py) that is using dnf as backend.

You could use the last [Spacewalk master version](https://github.com/uyuni-project/uyuni/tree/master/backend/satellite_tools) as a basis:
[reposync](https://github.com/spacewalkproject/spacewalk/blob/master/backend/satellite_tools/reposync.py)
[yum_src](https://github.com/spacewalkproject/spacewalk/blob/master/backend/satellite_tools/repo_plugins/yum_src.py)
[custom_update_md](https://github.com/spacewalkproject/spacewalk/blob/master/backend/satellite_tools/repo_plugins/custom_update_md.py)
[arch](https://github.com/spacewalkproject/spacewalk/blob/master/backend/satellite_tools/repo_plugins/arch.py)
[Makefile](https://github.com/spacewalkproject/spacewalk/blob/master/backend/satellite_tools/repo_plugins/Makefile)

If you use the above basis, the you would have to double check changes to the apis and port it to Python3.

## Version of Uyuni Server and Proxy (if used)
master on 2021-01-05

**Comment by mcalmer** [comment]
The zypper plugin can download the groups and modules metadata. Otherwise we could not support it when it is installed on a SUSE system. But this is not the point here.

The goal is to provide a 2nd implementation using dnf and depending on what OS is used as base for the server the one or the other is installed.
