### ISSUE TITLE
Update code to use URLGrabber 4

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#3113]
# Additional Information

Currently, spacewalk-backend-tools requires URLGrabber 3. Latest URLGrabber version is 4.
The RHEL EPEL repository and Tumbleweed already use v4. 

## Version of Uyuni Server and Proxy (if used)
Master 2021-01-12

## Details about issue
Reposync fails on URLGrabber4 in different areas. At least on passing the URL and verifying the completed file.
(/backend/satellite_tools/reposync.py)

**Comment by agraul** [comment]
The urlgrabber code in backend/satellite_tools/download.py needs some cleanup in general, in my opinion urlgrabber should not leak pycurl specifics.

**Comment by sbluhm** [comment]
https://github.com/uyuni-project/uyuni/pull/4604
