### ISSUE TITLE
salt-minion | libmq

### ISSUE THREAD

**Issue by amathar** [uyuni-project/uyuni#3135]
# Additional Information
libmq compatibility 

## Version of Uyuni Server and Proxy (if used)
 # zypper info Uyuni-Server-release
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.11-99.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.11-99.2.uyuni.src
Summary        : Uyuni Server
....

## Details about issue
Some of our (Centos) webserver use the php-zmq package (php74-php-pecl-zmq), which needs libzmq.so.5
The salt-minion client needs libzmq.so.4, so I am unable to install the salt client on all these machines.

Error: Package: python-zmq-14.5.0-3.9.uyuni.x86_64 (SUSE-Manager-Bootstrap)
           Requires: libzmq.so.4()(64bit)
           Available: zeromq-4.0.5-1.9.uyuni.x86_64 (systemsmanagement_Uyuni_Stable_CentOS7-Uyuni-Client-Tools)
               libzmq.so.4()(64bit)
           Installed: zeromq-4.1.4-6.el7.x86_64 (@epel)
              ~libzmq.so.5()(64bit)

is there something I can do, to solve this? Maybe installing salt-minion manually? Or is there a salt-minion client compiled with libzmq.so.5? 

Ragards,
Peter

**Comment by juliogonzalez** [comment]
If I am not wrong this is a know problem... without a solution until we have a bundle of salt with all dependencies.

@meaksh can you have a look? I tried to locate an issue for this, but maybe this was only discussed at the mailing lists or Gitter?

**Comment by amathar** [comment]
@juliogonzalez 
I have found a workaround:
https://enterprise.saltstack.com/en/latest/docs/install-salt.html
install python3.6., add the salt repo, install salt-minion via repo and confgure the salt-minion manually. It seems to work.. Maybe this could be a hint on the uyuni webpage...

**Comment by juliogonzalez** [comment]
@amathar do I understand that you installed salt from saltstacks repository and not from the Uyuni Client Tools?

If so, this is known to break at least some things.

**Comment by amathar** [comment]
yes, I used this repo https://repo.saltstack.com/py3/redhat/7/$basearch/3000, as you can see, the same version..
Till now I can not see any problems, installed packages are reported, I can patch / install packages.

What kind of problems do you mean? What will break?

**Comment by juliogonzalez** [comment]
I don't really remember, but I know there were (are?) some problems, so only the salt we provide is official supported.

Here is the thing: sometimes we need to implement stuff, and while we upstream all our changes to saltstack, sometimes a PR for saltstack can be waiting for a while before it's merged.

So it could just work fine, but don't surprise if you find something that doesn't.

The official solution for this (we are working on it) would be having salt in a bundle, with all required dependencies (which is basically what the official saltstack does). That way salt doesn't conflict with anything else. But in our case the bundling packages is slightly more complicated as we also need to keep in mind things specific to openSUSE/SLE at OBS (would be the same for Fedora/CentOS on their build systems) such as not downloading dependencies from the internet, so it's still WIP.

I think this is the issue I was looking for: https://github.com/uyuni-project/uyuni/issues/2115

However this will not fix the problem in your case as you *really* need that zeromq version.

Unless our salt squad can give a better idea for this issue, I'd say your workaround is the best approach for now.

**Comment by amathar** [comment]
Thank you for your comment. When the development team publishes a better solution I will change our salt installation.

Kind regards,
Peter

**Comment by juliogonzalez** [comment]
Hello!

The salt bundle I described in my previous comment is now available for all operating systems so...

- New systems will use it by default (no more problems onboarding if EPEL is enabled)
- Old systems can be migrated

I am closing the issue for now, but feel free to reopen if needed.
