### ISSUE TITLE
Bootstrapping CentOS 7 salt-minion fails via Web UI, required packages not installed 

### ISSUE THREAD

**Issue by sleepygh0st** [uyuni-project/uyuni#3144]
# Additional Information
After bootstrapping a host from the Web UI, a message is displayed "Successfully bootstrapped host! Your system should appear in systems shortly" - But the system never appears in the list.  The bootstrapping process completes, and the keys are added and accepted, but on the client side, the salt-minion fails to start due to python-certifi having not been installed, although it is available via the bootstrap repo.  

Installing python-certifi manually via the bootstrap repo after the bootstrapping process completes the registration

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.11-99.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.11-99.2.uyuni.src
Summary        : Uyuni Server

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

Steps to reproduce the issue:

**1. Create the bootstrap repo**

 # mgr-create-bootstrap-repo --with-custom-channels
1. centos-7-x86_64-uyuni
Enter a number of a product label: 1

Creating bootstrap repo for centos-7-x86_64-uyuni
copy 'salt-3000-25.1.uyuni.x86_64'
copy 'salt-minion-3000-25.1.uyuni.x86_64'
copy 'python2-salt-3000-25.1.uyuni.x86_64'
copy 'python-futures-2.1.3-0.8.9.uyuni.x86_64'
copy 'python-jinja2-2.7.2-4.el7.noarch'
copy 'python-msgpack-python-0.4.6-2.9.uyuni.x86_64'
copy 'python-psutil-1.2.1-0.10.9.uyuni.x86_64'
copy 'python-pycrypto-2.6.1-2.9.uyuni.x86_64'
copy 'python-requests-2.6.0-10.el7.noarch'
copy 'python-setuptools-0.9.8-7.el7.noarch'
copy 'python-singledispatch-3.4.0.3-4.2.uyuni.noarch'
copy 'python-tornado-4.2.1-5.el7.x86_64'
copy 'python-zmq-14.5.0-3.9.uyuni.x86_64'
copy 'zeromq-4.0.5-1.9.uyuni.x86_64'
copy 'python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch'
copy 'python-backports-1.0-8.el7.x86_64'
copy 'python-certifi-2015.9.6.2-2.9.uyuni.noarch'
copy 'python-simplejson-3.5.3-5.el7.x86_64'
copy 'PyYAML-3.10-11.el7.x86_64'
copy 'python-markupsafe-0.11-10.el7.x86_64'
copy 'python-urllib3-1.10.2-7.el7.noarch'
copy 'libyaml-0.1.4-11.el7_0.i686'
copy 'libyaml-0.1.4-11.el7_0.x86_64'
copy 'python-chardet-2.2.1-3.el7.noarch'
copy 'python-six-1.9.0-2.el7.noarch'
copy 'python-babel-0.9.6-8.el7.noarch'
copy 'yum-rhn-plugin-4.2.2-2.1.uyuni.noarch'
copy 'yum-3.4.3-168.el7.centos.noarch'
copy 'python2-rhnlib-4.2.1-2.2.uyuni.noarch'
copy 'openssl-1.0.2k-21.el7_9:1.x86_64'
copy 'openssl-libs-1.0.2k-21.el7_9:1.i686'
copy 'openssl-libs-1.0.2k-21.el7_9:1.x86_64'
copy 'python-ipaddress-1.0.16-2.el7.noarch'
copy 'redhat-rpm-config-9.1.0-88.el7.centos.noarch'
copy 'rpm-python-4.11.3-45.el7.x86_64'
copy 'spacewalk-check-4.2.3-2.1.uyuni.noarch'
copy 'python2-spacewalk-check-4.2.3-2.1.uyuni.noarch'
copy 'spacewalk-client-setup-4.2.3-2.1.uyuni.noarch'
copy 'python2-spacewalk-client-setup-4.2.3-2.1.uyuni.noarch'
copy 'spacewalk-client-tools-4.2.3-2.1.uyuni.noarch'
copy 'python2-spacewalk-client-tools-4.2.3-2.1.uyuni.noarch'
copy 'python2-uyuni-common-libs-4.2.2-2.1.uyuni.x86_64'
copy 'mgr-daemon-4.2.3-2.1.uyuni.noarch'
copy 'suseRegisterInfo-4.2.1-2.2.uyuni.noarch'
copy 'python2-suseRegisterInfo-4.2.1-2.2.uyuni.noarch'
copy 'python2-hwdata-2.3.5-2.9.uyuni.noarch'
copy 'dmidecode-3.2-5.el7:1.x86_64'
Directory walk started
Directory walk done - 48 packages
Temporary output repo path: /srv/www/htdocs/pub/repositories/centos/7/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished

**2. Add repo to Activation Key, then bootstrap the host from the WebUI**

**After the "Successfully bootstrapped host!" message, in the client logs:** 

Jan 18 11:37:24 jbtestcent7-2 salt-minion: salt-minion: error: Error while processing <bound method Minion.process_config_dir of <salt.cli.daemons.Minion object at 0x2361190>>: Traceback (most recent call last):
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 223, in parse_args
Jan 18 11:37:24 jbtestcent7-2 salt-minion: process_option_func()
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 561, in process_config_dir
Jan 18 11:37:24 jbtestcent7-2 salt-minion: self.config.update(self.setup_config())
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 1850, in setup_config
Jan 18 11:37:24 jbtestcent7-2 salt-minion: ignore_config_errors=False)
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2392, in minion_config
Jan 18 11:37:24 jbtestcent7-2 salt-minion: apply_sdb(opts)
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2526, in apply_sdb
Jan 18 11:37:24 jbtestcent7-2 salt-minion: import salt.utils.sdb
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 14, in <module>
Jan 18 11:37:24 jbtestcent7-2 salt-minion: import salt.loader
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/loader.py", line 31, in <module>
Jan 18 11:37:24 jbtestcent7-2 salt-minion: import salt.utils.event
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 74, in <module>
Jan 18 11:37:24 jbtestcent7-2 salt-minion: import salt.ext.tornado.iostream
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/ext/tornado/iostream.py", line 41, in <module>
Jan 18 11:37:24 jbtestcent7-2 salt-minion: from salt.ext.tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
Jan 18 11:37:24 jbtestcent7-2 salt-minion: File "/usr/lib/python2.7/site-packages/salt/ext/tornado/netutil.py", line 40, in <module>
Jan 18 11:37:24 jbtestcent7-2 salt-minion: import certifi
Jan 18 11:37:24 jbtestcent7-2 salt-minion: ImportError: No module named certifi
Jan 18 11:37:24 jbtestcent7-2 systemd: salt-minion.service: main process exited, code=exited, status=64/n/a
Jan 18 11:37:24 jbtestcent7-2 systemd: Unit salt-minion.service entered failed state.

**List of packages installed during bootstrap process**

Jan 18 11:16:53 Installed: python-markupsafe-0.11-10.el7.x86_64
Jan 18 11:16:54 Updated: python-chardet-2.2.1-3.el7.noarch
Jan 18 11:16:54 Installed: zeromq-4.0.5-1.9.uyuni.x86_64
Jan 18 11:16:54 Installed: python-zmq-14.5.0-3.9.uyuni.x86_64
Jan 18 11:16:55 Installed: python-babel-0.9.6-8.el7.noarch
Jan 18 11:16:55 Installed: python-jinja2-2.7.2-4.el7.noarch
Jan 18 11:16:55 Installed: python2-futures-3.1.1-5.el7.noarch
Jan 18 11:16:55 Installed: python-psutil-1.2.1-0.10.9.uyuni.x86_64
Jan 18 11:16:55 Installed: python-singledispatch-3.4.0.3-4.2.uyuni.noarch
Jan 18 11:16:55 Installed: python-pycrypto-2.6.1-2.9.uyuni.x86_64
Jan 18 11:16:55 Installed: python-ipaddress-1.0.16-2.el7.noarch
Jan 18 11:16:55 Installed: libyaml-0.1.4-11.el7_0.x86_64
Jan 18 11:16:55 Installed: PyYAML-3.10-11.el7.x86_64
Jan 18 11:16:55 Installed: python-msgpack-python-0.4.6-2.9.uyuni.x86_64
Jan 18 11:16:55 Installed: python-six-1.9.0-2.el7.noarch
Jan 18 11:16:55 Installed: python-urllib3-1.10.2-7.el7.noarch
Jan 18 11:16:55 Installed: python-requests-2.6.0-10.el7.noarch
Jan 18 11:16:56 Installed: salt-3000-25.1.uyuni.x86_64
Jan 18 11:17:00 Installed: python2-salt-3000-25.1.uyuni.x86_64
Jan 18 11:17:00 Installed: salt-minion-3000-25.1.uyuni.x86_64

**python-certifi is not present, although should have been installed during bootstrap**

After bootstrapping, issuing yum install python-certifi completes the registration 

# yum install python-certifi
Loaded plugins: fastestmirror, langpacks, yumnotify
SUSE-Manager-Bootstrap                                                                           | 2.6 kB  00:00:00
SUSE-Manager-Bootstrap/primary_db                                                                |  26 kB  00:00:00
Determining fastest mirrors
Resolving Dependencies
--> Running transaction check
---> Package python-certifi.noarch 0:2015.9.6.2-2.9.uyuni will be installed
--> Finished Dependency Resolution

Dependencies Resolved

 Package                   Arch              Version                            Repository                         Size

Installing:
 python-certifi            noarch            2015.9.6.2-2.9.uyuni               SUSE-Manager-Bootstrap            183 k

Transaction Summary

Install  1 Package

Total download size: 183 k
Installed size: 680 k
Is this ok [y/d/N]: y
Downloading packages:
python-certifi-2015.9.6.2-2.9.uyuni.noarch.rpm                                                   | 183 kB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python-certifi-2015.9.6.2-2.9.uyuni.noarch                                                           1/1
  Verifying  : python-certifi-2015.9.6.2-2.9.uyuni.noarch                                                           1/1

Installed:
  python-certifi.noarch 0:2015.9.6.2-2.9.uyuni

Complete!

**Comment by agraul** [comment]
I think this is a missing `Requires: python-certifi` in our Salt RPM. On SLE/openSUSE we require `python-requests` which in turn requires `python-certifi`. CentOS 7's `python-requests` does not require `python-certifi`, i.e. nothing pulls it in.

**Comment by juliogonzalez** [comment]
But why is this failing now? Was this changed recently on the SPEC?

**Comment by agraul** [comment]
@sleepygh0st after looking into this a bit more, I wonder why you run into this issue. As you said in gitter, `python-certifi` is only needed on some cases that are related to SSL.

Could you please run `python -c 'import ssl; print hasattr(ssl, "create_default_context")'` on the CentOS7 installation? Only if that command prints `False` it is required to install `python-certifi`. Inside a plain CentOS7 docker container that command printed `True` when I tested this right now.

For future releases we will add `python-certifi` as a requirement to the pythonX-salt rpm, but it is too late for the upcoming January release of Uyuni to add this. But I'm still interested in why this is needed in your use case.

**Comment by sleepygh0st** [comment]
@agraul Thank you for digging into this deeper.. To clarify my earlier statement in Gitter, I was making an off the top assumption. 

I've ran python -c 'import ssl; print hasattr(ssl, "create_default_context")' on a couple of my CentOS 7 hosts, and have inconsistent results on older releases versus newer

[root@localhost jb]#  python -c 'import ssl; print hasattr(ssl, "create_default_context")'
False
[root@localhost jb]# cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core) 

This version is what I have been testing with, a default install via a Cent7 iso

On various other hosts which are running newer Cent 7 releases - I ran this command on and it would seem that at some point this returns true 

[root@testcent7-3 jb]# python -c 'import ssl; print hasattr(ssl, "create_default_context")'
True
[root@testcent7-3 jb]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

**Comment by juliogonzalez** [comment]
Now it's clear to me why we never detected this problem before. We never tested CentOS 7.0 since Uyuni started being published, and SUSE Manager only supports the most recent version of CentOS/RHEL/Oracle.

Do you really a so old and unmaintained CentOS7 version?

My opinion on this issue:
- Since we have python-certifi at the repository, and since we have a require for at the SPEC (that for some reason is not working), let's fix it unless it takes a lot of effort.
- Now it's too late to get the fix into 2021.01, so the fix would be part of the next version (for now, at least, there's a workaround

**Comment by sleepygh0st** [comment]
@juliogonzalez Thanks for getting this into the pipeline, I appreciate your help. 

As for using the older version, only for initial imaging and never in production.  I suppose it would behoove me to start with an ISO that is a little more current now.
