### ISSUE TITLE
openscap --fetch-remote-resources is ignored while triggering the action from WEBUI

### ISSUE THREAD

**Issue by oddyutza** [uyuni-project/uyuni#3222]
## Version of Uyuni Server and Proxy (if used)
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.11-99.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1,4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.11-99.2.uyuni.src
Summary        : Uyuni Server

## Details about issue
Openscap Audit Scan error message:
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-com.redhat.rhsa-RHEL7.xml' points out to the remote 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml'. Use '--fetch-remote-resources' option to download it.

Audit scan was triggered from WebUI and here are the details

File System Path: 	/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
Command-line Arguments: 	--fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_cis
Scheduled By: 	admin
Benchmark Identifier: 	xccdf_org.ssgproject.content_benchmark_RHEL-7
Benchmark Version: 	0.1.52
Profile Identifier: 	xccdf_org.ssgproject.content_profile_cis
Profile Title: 	CIS Red Hat Enterprise Linux 7 Benchmark

The problem is that '--fetch-remote-resources' is ignored completely or not pushed to the client machine.

Target machine is properly connected to internet, has network configuration correct
Manual trigger on the machine works perfectly  ( cli command on the client )

**Comment by mcalmer** [comment]
So the command is executed correctly with the option on the target system?
If yes, I assume the target system is a RHEL7 or similar as you use that benchmark.
In this case openscap comes from RedHat/CentOS and is not part of uyuni. You might have found a bug in the OS and you need to talk to the OS vendor to get it fixed.

**Comment by oddyutza** [comment]
the " --fetch-remote-resources " is not passed by uyuni to the client when the action is triggered from webui, does not appear in the PS list ( when it's running ).
i`ve made the test with cli in order to rule out any other issues, and worked fine - as to rule out any other potential issues

"So the command is executed correctly with the option on the target system? "
A: No, when using the uyuni web ui to trigger the action | that option is missing
A: Yes, if the command is issued directly on the client machine using CLI, no problems.

**Comment by mcalmer** [comment]
Seems that salt does not allow other arguments:
  https://github.com/saltstack/salt/blob/master/salt/modules/openscap.py#L29-L38

CC @brejoc @agraul

**Comment by paususe** [comment]
@oddyutza As a workaround, you can find the latest SCAP content in this repository, so no need to fetch from external sources:
https://build.opensuse.org/project/show/home:pagarcia:branches:security

**Comment by oddyutza** [comment]
Initially i've changed the ssg xml file to point out to a local resource, and worked and searched for the parameter afterwords
I've already made the change to : /usr/lib/python2.7/site-packages/salt/modules/openscap.py
Line 35
            "--oval-results --results results.xml --report report.html "
Became
            "--fetch-remote-resources --oval-results --results results.xml --report report.html "
The check is running great now, and the report is properly generated and uploaded to uyuni.
The actual current problem is that the Audit tab cannot be opened, tomcat logs show;
 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-11] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back
javax.el.ELException: Error reading [diffIcon] on type [com.redhat.rhn.frontend.dto.XccdfTestResultDto]

i guess this is another bug :(

**Comment by oddyutza** [comment]
@paususe Thanks for the pointer, but those files are not usable, the packs are not complete therefore cannot be used for example for centos 7.x

**Comment by paususe** [comment]
> @paususe Thanks for the pointer, but those files are not usable, the packs are not complete therefore cannot be used for example for centos 7.x

What do you mean they are not complete? What's missing?

**Comment by oddyutza** [comment]
@paususe 
for example the file:
scap-security-guide-0.1.54-13.1.noarch.rpm
from:
https://build.opensuse.org/package/binaries/home:pagarcia:branches:security/scap-security-guide/CentOS_7
is missing:
ssg-centos7-ds.xml / ssg-centos7-ds-1.2.xml
Hence becomes unusable

I've also noticed that the generated report ( with --fetch-remote-resources working ) has the following result:
Evaluation target	something_goes_here
Benchmark URL	/usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml
Benchmark ID	xccdf_org.ssgproject.content_benchmark_RHEL-7
Profile ID	xccdf_org.ssgproject.content_profile_standard

**The target system did not satisfy the conditions of 1266 rules! Please review rule results and consider applying remediation.** 
The detailed exploded/unfolded view of the failed checks, show only 33 failed ones based on the profile checked

My today's conclusion for the openscap part for uyuni is that it needs some testing, debuging, and currently is not functional/reliable

**Comment by paususe** [comment]
@oddyutza the `scap-security-guide` package contains the SUSE profiles.

For CentOS, RHEL, Oracle Linux and SLES ES, use `scrap-security-guide-redhat`.

For Debian, use `scrap-security-guide-debian`. 

For Ubuntu, use `scrap-security-guide-ubuntu`.

**Comment by oddyutza** [comment]
@paususe 
I guess you missed something. I`m using the XML files provided by https://github.com/ComplianceAsCode/content/releases/tag/v0.1.54 - i just said that the link you've provided is not quite correct.
Hence, the errors have nothing to do with the uyuni interface, for example this! :+1: 
[ajp-nio-0:0:0:0:0:0:0:1-8009-exec-11] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back
javax.el.ELException: Error reading [diffIcon] on type [com.redhat.rhn.frontend.dto.XccdfTestResultDto]

**Comment by nkrinner** [comment]
Be aware: https://github.com/saltstack/salt/pull/60211
