### ISSUE TITLE
Minor upgrade to 2021.01 results in 404 errors and no webui.

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#3230]
Good work on the new version - watching Community hours I was keen to give this a try. 

Preamble - not sure if this is an issue unique to my setup/due to my unfamiliarity with OpenSyse - but raising as an issue in case,  as an early adopter, this  may be affecting others.  I followed the process twice with the same result.

# Issue:
Tomcat errors returning 404 on all webui urls, including login etc

Dedicated uyuni vm running OpenSuse Leap 15.2

## Process
**zypper ref** 

**zypper up** 

Shows warning, Detected 1 file conflict:

```
File /usr/share/java/commons-el.jar
  from install of
     apache-commons-el-1.0-lp152.1.1.noarch (openSUSE-Leap-15.2-1)
  conflicts with file from package
     jakarta-commons-el-1.0-2.6.uyuni.noarch (@System)


(Gives option to continue or not. Not aborts all updates. Continue proceeds. Cannot reinstall jakarta-commons-el which it says is not in any configured repo. )


(Another attempt updating a specific patch returns  this)

Problem: patch:openSUSE-2020-2257-1.noarch conflicts with apache-commons-el < 1.0-lp152.2.3.1 provided by apache-commons-el-1.0-lp152.1.1.noarch
 Solution 1: Following actions will be done:
  deinstallation of apache-commons-el-1.0-lp152.1.1.noarch
  downgrade of spacewalk-java-4.2.7-1.3.uyuni.noarch to spacewalk-java-4.2.3-1.1.uyuni.noarch
 Solution 2: install apache-commons-el-1.0-lp152.2.3.1.noarch (with vendor change)
  obs://build.opensuse.org/systemsmanagement:Uyuni  -->  openSUSE
 Solution 3: do not install patch:openSUSE-2020-2257-1.noarch

(And later, when update output was scrolling by, got this, which may be unrelated;)

( 30/121) Installing: prometheus-jmx_exporter-0.3.1-3.10.uyuni.noarch .......................................................................................[done]
Additional rpm output:
Failed to try-restart prometheus-jmx_exporter@.service: Unit name prometheus-jmx_exporter@.service is missing the instance name.
See system logs and 'systemctl status prometheus-jmx_exporter@.service' for details.

```

repos are:
```
 zypper repos
Repository priorities are without effect. All enabled repositories share the same priority.

#  | Alias                                  | Name                                                                           | Enabled | GPG Check | Refresh
---+----------------------------------------+--------------------------------------------------------------------------------+---------+-----------+--------
 1 | openSUSE-Leap-15.2-1                   | openSUSE-Leap-15.2-1                                                           | Yes     | (r ) Yes  | Yes
 2 | repo-debug                             | Debug Repository                                                               | No      | ----      | ----
 3 | repo-debug-non-oss                     | Debug Repository (Non-OSS)                                                     | No      | ----      | ----
 4 | repo-debug-update                      | Update Repository (Debug)                                                      | No      | ----      | ----
 5 | repo-debug-update-non-oss              | Update Repository (Debug, Non-OSS)                                             | No      | ----      | ----
 6 | repo-non-oss                           | Non-OSS Repository                                                             | Yes     | (r ) Yes  | Yes
 7 | repo-oss                               | Main Repository                                                                | Yes     | (r ) Yes  | Yes
 8 | repo-source                            | Source Repository                                                              | No      | ----      | ----
 9 | repo-source-non-oss                    | Source Repository (Non-OSS)                                                    | No      | ----      | ----
10 | repo-update                            | Main Update Repository                                                         | Yes     | (r ) Yes  | Yes
11 | repo-update-non-oss                    | Update Repository (Non-Oss)                                                    | Yes     | (r ) Yes  | Yes
12 | systemsmanagement_Uyuni_Stable_Patches | Project used to release critical patches between releases (openSUSE_Leap_15.2) | Yes     | (r ) Yes  | No
13 | uyuni-server-stable                    | uyuni-server-stable                                                            | Yes     | (r ) Yes  | No
```

Continuing past that, upgrade appears to complete fully. I restart the vm as advised, and 

`spacewalk-service start` after reboot shows expected db schema update, which completes without error.

I'm guessing the core has updated fine, but something in apache2/tomcat has gone screwy, possibly because of that conflict?
 

Unfortunately I needed to restore Uyuni to productivity, so reverted to a snapshot I took prior.

**Comment by digdilem** [comment]
(To confirm, I stopped the service first - sorry, juggling a few things this afternoon!)

**Comment by juliogonzalez** [comment]
What option did you use when you got the conflict?

**Comment by juliogonzalez** [comment]
Ok, the thing is that now the package `apache-commons-el` should indeed come from openSUSE Leap.

I assume you didn't pick option `2`, right @dgdilem?

If so, can you please stop the services, run zypper up again (you should get the same question), select 2, start the services and see if works fine

**Comment by juliogonzalez** [comment]
Bofore I explain the solution: Thanks a lot to @digdilem @rpasche @EthanB11 and @stdevel (and I hope I am not missing someone else) for your help finding the problem, and testing the solution.

# Solution

1. Stop spacewalk-services
2. Run: ```zypper install --allow-downgrade --allow-vendor-change -f apache-commons-cli-1.4-lp152.1.3.noarch apache-commons-jexl-2.1.1-lp152.1.1.noarch apache-commons-el-1.0-lp152.2.3.1.noarch
3. Start spacewalk-services.

# Explanation

Uyuni 2021.01 stopped providing some Java dependencies from Uyuni itself, and started using them from openSUSE Leap 15.2

The problem is that we did that in the December, and sadly we did not remember that doing such things means:

1. Making sure that we document at the release notes the **vendor change**.
2. Making sure that the package at Leap has version *and* a release newer than we provide.

# Takeaway

1. Avoid vendor changes at all unless we are changing the Leap version used as base OS. If we still need what Leap has, let's temporary build it ourselves.
2. Do vendor changes only when we change the Leap version. We have a script for that, so we can force a version from Leap 15.2, even if the release number is lower.
3. If we don't want, this then each time we want a vendor change, let's give on the release command the exact zypper command to be executed by the users (I don't like it too much, but we can discuss it)
4. We to think about testing upgrades from at the last version to master after we tag on master. That means:
    a) sumaform needs to support snapshots from https://build.opensuse.org/project/show/systemsmanagement:Uyuni:Snapshots so we can install an old version on the server, and maybe the proxy
   b) We need the a reduced cucumber testsuite that just upgrades the server to what is on Master, and check (at least) that all services on the Server and Proxy are up.
   c) This environment will run on-demand. Doing such test should not take more than one hour. It would be better to have something continuous, but for that we'd need to allow (somehow) applying SQL scripts from the most recent schema migration folder.

@paususe @mcalmer ^

**Comment by juliogonzalez** [comment]
Announcement sent to the mailing lists, twitter, gitter #users topic, and website.

On Monday I will submit the release notes RPMs to the Patches repository, together with a fix to show `2021.01` at the WebUI and the `/etc/uyuni-release`.

**Comment by digdilem** [comment]
Thanks to @juliogonzalez for a prompt response. It's been a busy week and have only now had a chance to retry this. 

The suggested amend worked fine and I'm upgraded.

Exact process thus:

1. spacewalk-server stop
2. zypper ref
3. zypper patch
4. zypper patch (it asked to be run again and got some other stuff)
5. zypper up (Failed with the conflict again)
6. Ran the suggested line: zypper install --allow-downgrade --allow-vendor-change -f apache-commons-cli-1.4-lp152.1.3.noarch apache-commons-jexl-2.1.1-lp152.1.1.noarch apache-commons-el-1.0-lp152.2.3.1.noarch
7. zypper up (no errors reported)
8. Rebooted vm
9. All returned including webui.

#winning

**Comment by eins** [comment]
Folks thanks for reporting this. ti worked for me.
Now I can see in the uyuni server the new Minor version:  'Uyuni release 2021.01'
