### ISSUE TITLE
Support Alma Linux clients

### ISSUE THREAD

**Issue by paususe** [uyuni-project/uyuni#3237]
Alma Linux is a 1:1 RHEL8 clone by CloudLinux, hoping to take CentOS place.

Alma Linux 8.3 beta was recently released. It's a 1:1 clone of RHEL, so it should be easy to support.

This is what `python-distro` (installed via `platform-python-pip`) returns:

```
[root@localhost ~]# distro -j
{
    "codename": "Purple Manul",
    "id": "almalinux",
    "like": "rhel centos fedora",
    "version": "8.3",
    "version_parts": {
        "build_number": "",
        "major": "8",
        "minor": "3"
    }
}
```

**Comment by Shirocco88** [comment]
@paususe : Can we close this issue ?
Uyuni-2021.05 supports Alma Linux;

**Comment by paususe** [comment]
This is now done, yes
