### ISSUE TITLE
attempting schema upgrade

### ISSUE THREAD

**Issue by tsikkema24** [uyuni-project/uyuni#3247]
# Additional Information
After upgrade spacewalk-schema-upgrade is failing to upgrade schema

spacewalk-schema-upgrade
Found unfinished schema migration
Try to continue schema migration
Planning to run schema upgrade with dir '/var/log/spacewalk/schema-upgrade/schema-from-20210209-080648'
Hit Enter to continue or Ctrl+C to interrupt:
Executing spacewalk-sql, the log is in [/var/log/spacewalk/schema-upgrade/schema-from-20210209-080648-to-susemanager-schema-4.2.6.log].
(1/8) apply upgrade [susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/702-debvercmp.sql.postgresql]
Upgrade failed, please see log [/var/log/spacewalk/schema-upgrade/schema-from-20210209-080648-to-susemanager-schema-4.2.6.log].
You can fix the failed migration in [/var/log/spacewalk/schema-upgrade/schema-from-20210209-080648]
and run spacewalk-schema-upgrade again

tail /var/log/spacewalk/schema-upgrade/schema-from-20210209-080648-to-susemanager-schema-4.2.6.log
UPDATE 1
UPDATE 0
UPDATE 0
UPDATE 0
UPDATE 0
UPDATE 0
UPDATE 0
UPDATE 0
UPDATE 0
psql:<stdin>:444: ERROR:  syntax error at or near "("
LINE 1: ...f not exists type varchar(10) generated always as ((evr).typ...

## Version of Uyuni Server and Proxy (if used)
2021.01-2.1.uyuni from 2020.04
 
have proxy but need to get main server upgraded first.

**Comment by paususe** [comment]
What version are you coming from?

**Comment by tsikkema24** [comment]
going from 2020.06. i said 4 but didnt remember correctly.

**Comment by Shirocco88** [comment]
2021.01-2.1.uyuni from 2020.04

@tsikkema24 : How did you upgrade ? 
Did you read to release notes for Uyuni-2020.07:

[https://www.uyuni-project.org/doc/2021.01/release-notes-uyuni-server.html#_upgrade_notes](url)
**Version 2020.07**
Upgrade notes
WARNING: Check "Update from previous versions of Uyuni Server" section below for details, as this release updates the base OS from openSUSE Leap 15.1 to openSUSE Leap 15.2, and there are special steps required.
The migration will be performed allowing vendor changes, so this upgrade will fix the issues with python3-psycopg2 mentioned at Uyuni Server 2020.05 release notes. Therefore you will not need to perform the manual steps mentioned there.

IMHO: you can not direktly update from 2020.04 or 2020.06 to 2021.01;
you first have to do an SP-Migration from openSUSE Leap 15.1 to 15.2

**Comment by Shirocco88** [comment]
@tsikkema24 : Uyuni-2021.05 was released;
is this problem still existend ? can we close this issue ?

**Comment by tsikkema24** [comment]
i was able to get it figured out.
