### ISSUE TITLE
Uyuni token missing while registering old non-patched Ubuntu 18.04 servers

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#3281]
The MR https://github.com/uyuni-project/uyuni/pull/2572 prevents apt on some old non patched Ubuntu 18.04 servers to connect to the Uyuni server after registration. This is because of the token file not being created, due to the absence of the `/etc/apt/auth.conf.d` directory.

This is mentioned in this bug https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1818996.

I have created the directory `/etc/apt/auth.conf.d` by hand, and the file `/etc/apt/auth.conf.d/susemanager.conf` is then correctly created during the registration.

However this is not enough and the token configuration is still not detected. I have to copy the content of `/etc/apt/auth.conf.d/susemanager.conf` to`/etc/apt/auth.conf`, which this time allows the update of Ubuntu.

With the new apt version, `/etc/apt/auth.conf.d/susemanager.conf` is then correctly taken into account.

**Comment by mcalmer** [comment]
@phibid can you find out since which apt version it works correctly? Creating the directory would be easy, but what does it help when it still does not work. 
If we know the version we could add a check in the SLS file and deploy the old variant.

**Comment by phibid** [comment]
@mcalmer Yes, from the Bionic apt changelog, this is solved since apt 1.6.10:

https://launchpad.net/ubuntu/bionic/+source/apt/+changelog

```
apt (1.6.10) bionic; urgency=medium

  * Fix name of APT::Update::Post-Invoke-Stats (was ...Update-Post...)
  * CMake: Install auth.conf.d directory (LP: #1818996)
  * Merge translations from 1.7.4
```

**Comment by mcalmer** [comment]
@phibid see the attached Pull Request. Are you able to test this?

**Comment by phibid** [comment]
@mcalmer Sorry, don't have a preprod Uyuni server, this is on my TODO list to setup one but missing time to do so.

From what I can see on this PR, if apt < 1.6.10, then the token won't be separated as it was in fact before ?

**Comment by mcalmer** [comment]
Right. Only for apt > 1.6.10 we can make use of the new feature and use auth.conf.d/ 
This is the idea

**Comment by phibid** [comment]
And if the Ubuntu server is updated, which action would need to be done to force Uyuni to deploy new separate token file ? A package_refresh perhaps ?

**Comment by mcalmer** [comment]
A state.apply or highstate will do the job. But the config will also work with newer versions of apt.
