### ISSUE TITLE
Schemaupgrade failed / hung up from Uyuni stable 11/2020 --> 02/2021

### ISSUE THREAD

**Issue by vega82** [uyuni-project/uyuni#3355]
Hi today i tried another update of our productive uyuni server from 11/2020(stable) to 02/2021 (stable).
Everythink runs fine but after reboot i could not start the uyuni manager.

So i tried to find out what's wrong.
Uyuni stucks while upgrading the Manager Scheme:

journal show:
>systemd[1]: Starting Uyuni check database...
spacewalk-startup-helper[1307]: Schema upgrade: [susemanager-schema-4.2.3-1.1.uyuni] -> [susemanager-schema-4.2.8-1.3.uyuni]
spacewalk-startup-helper[1307]: Searching for upgrade path to: [susemanager-schema-4.2.8-1]
spacewalk-startup-helper[1307]: Searching for upgrade path to: [susemanager-schema-4.2.8]
spacewalk-startup-helper[1307]: Searching for start path:  [susemanager-schema-4.2.3-1]
spacewalk-startup-helper[1307]: Searching for start path:  [susemanager-schema-4.2.3]
spacewalk-startup-helper[1307]: The path: [susemanager-schema-4.2.3] -> [susemanager-schema-4.2.4] -> [susemanager-schema-4.2.5] -> [susemanager-schema-4.2.6] -> [susemanager-schema-4.2.7] -> [susemanager-schema->
spacewalk-startup-helper[1307]: Planning to run schema upgrade with dir '/var/log/spacewalk/schema-upgrade/schema-from-20210303-115659'
spacewalk-startup-helper[1307]: Executing spacewalk-sql, the log is in [/var/log/spacewalk/schema-upgrade/schema-from-20210303-115659-to-susemanager-schema-4.2.8.log].

/var/log/spacewalk/schema-upgrade/schema-from-20210303-115659-to-susemanager-schema-4.2.8.log shows at last:
> alter table rhnpackageevr add column if not exists type varchar(10) generated always as ((evr).type) stored;
> ALTER TABLE rhnpackageevr ENABLE TRIGGER USER;
> commit;

**Comment by vega82** [comment]
![psql](https://user-images.githubusercontent.com/2478621/109803498-68dcd500-7c21-11eb-9081-5fd1865e42f1.JPG)

**Comment by mcalmer** [comment]
let it run. That might take hours. See the release notes and warning added at the announcement of 2021.01

**Comment by vega82** [comment]
Oh thank you. So i don't have to become nervous :) 
I guess there is a problem with the database or migrationscript :)
So 'ill wait patiently.
