### ISSUE TITLE
event-stream security update

### ISSUE THREAD

**Issue by kkaempf** [uyuni-project/uyuni#342]
Known critical severity security vulnerability in event-stream v> 3.3.4, defined in https://github.com/uyuni-project/uyuni/blob/master/susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
Review the vulnerable dependency:
https://github.com/uyuni-project/uyuni/network/alert/susemanager-frontend/susemanager-nodejs-sdk-devel/package.json/event-stream/open

cc @juliogonzalez

**Comment by ncounter** [comment]
AFAIK we are using [version greater or equal to 4.0.0](https://github.com/uyuni-project/uyuni/blob/master/susemanager-frontend/susemanager-nodejs-sdk-devel/package.json#L29) so I think we are fine with this.

**Comment by lneves12** [comment]
I think we don't need this dependency anymore. It's left overs from the old js dependency management/gulp thing. I will assign this to me, to check which dependencies are not used anymore and remove them.
