### ISSUE TITLE
Issue wrong 'Content Provider' packages - spacecmd softwarechannel_clone 

### ISSUE THREAD

**Issue by mikebmb512** [uyuni-project/uyuni#3432]
# Additional Information

Hi, 

I have an issue with wrong 'Content Provider' packages in my softwarechannels.
When this error appires it makes my channels useless because the update on the system fails. 
I'm using the `spacecmd softwarechannel_clone` command to clone base and child channels for my systems (like monthly snapshots).
I suspect a bug in softwarechannel_clone..

Thank you :)

## Version of Uyuni Server and Proxy (if used)
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.01-107.1.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2020.11-99.2.uyuni installed)
Source package : Uyuni-Server-release-2021.01-107.1.uyuni.src
Summary        : Uyuni Server

## Details about issue

In this example I have at least 4 wrong packages from a *Oracle-Linux 6* and *Cent OS 8* in my __Cent OS 7 update channel__. Detected as el6 and el8.
The label is: rel-2021-01-centos-7-dist-updates

#### Part of the CSV export via GUI: 
Id	    |nvrea	                                     |Content Provider
------------| -------------| -------------
99329	  |vim-common-7.4.629-8.el7_9:2.x86_64	       |  CentOS
99325	  |tzdata-java-2020d-2.el7.noarch	             |CentOS
129204	|tzdata-java-2020d-1.el8.noarch	             |CentOS
327305	|tzdata-java-2020d-1.el6.noarch	             |Oracle Inc.
99262	  |tzdata-2020d-2.el7.noarch	                 |  CentOS
127132	|tzdata-2020d-1.el8.noarch	                 |  CentOS
327069	|tzdata-2020d-1.el6.noarch	                 |  Oracle Inc.
99210	  |tuned-utils-systemtap-2.11.0-10.el7.noarch	 |CentOS

#### Database query:
```sql
SELECT COUNT(rp.id), rp.vendor, rc.label
FROM (((public.rhnchannelpackage rhp 
INNER JOIN public.rhnpackage rp ON rp.id = rhp.package_id)
INNER JOIN public.rhnpackagename rpn ON rpn.id = rp.name_id)
INNER JOIN public.rhnchannel rc ON rc.id = rhp.channel_id)
WHERE rhp.channel_id = 328  /* id rel-2021-01-centos-7-dist-updates */
GROUP BY rc.id, rp.vendor 

# Result SQL query:
count ,vendor           ,label
1164  ,CentOS           ,rel-2021-01-centos-7-dist-updates
2     ,Oracle America   ,rel-2021-01-centos-7-dist-updates
```

#### spacecmd softwarechannel_listpackages don't lists them up! Just the corect 'el7' packages.
```shell
spacecmd -q softwarechannel_listpackages rel-2021-01-centos-7-dist-updates | grep tzdata
tzdata-2020d-2.el7.noarch
tzdata-java-2020d-2.el7.noarch
```
#### Details about the softwarechannel:
```shell
pacecmd {SSM:0}> spacecmd {SSM:0}> softwarechannel_details rel-2021-01-centos-7-dist-updates
Label:              rel-2021-01-centos-7-dist-updates
Name:               CentOS Linux 7 - Distribution - Updates - BMB Release 2021-01
Architecture:       x86_64
Parent:             rel-2021-01-centos-7-dist-os
Systems Subscribed: 258
Number of Packages: 1166
```

**Comment by mcalmer** [comment]
If I remember correctly this issue was fixed.
In case you can reproduce it, feel free to open a new issue for it.
Thanks.
