### ISSUE TITLE
Link to "Get an OpenID" on OpenID Sign In page is not working

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [uyuni-project/uyuni#3454]
Link to "Get an OpenID" on OpenID Sign In page is not working, it returns "ooops, page not found"

https://lists.opensuse.org/accounts/openid/login/?process=login&next=%2Farchives%2Flist%2Fusers%40lists.uyuni-project.org%2F

**Comment by juliogonzalez** [comment]
@NotAProfessionalDeveloper thanks for the report!

Please open a ticket for the [openSUSE heroes](https://en.opensuse.org/openSUSE:Heroes) as they manage the mailing list infrastructure :-)
