### ISSUE TITLE
Ubuntu 18.04 Repository doesn't sync

### ISSUE THREAD

**Issue by support-tt** [uyuni-project/uyuni#3467]
## Version of Uyuni Server and Proxy (if used)
2021.02
no proxy

## Details about issue
This issue is similar to #1163 but it was supposedly fixed. When we try to sync an ubuntu repository, the packages in the url are found, but aren't synced.

Log output from _/var/log/rhn/reposync/ubuntu-1804-amd64-main-uyuni.log_:
```
2021/03/23 16:49:54 +02:00 Repo URL: http://archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64
2021/03/23 16:49:54 +02:00     Packages in repo:              6391
2021/03/23 16:49:54 +02:00     No new packages to sync.
2021/03/23 16:49:54 +02:00 
2021/03/23 16:49:54 +02:00   Patches in repo: 0.
2021/03/23 16:49:54 +02:00 Sync completed.
```

We also tested Centos8 and it synched without any issues so only with ubuntu/debian (Ubuntu 18 and Debian 10 was tested by us)

**Comment by Shirocco88** [comment]
@support-tt :

>> When we try to sync an ubuntu repository, the packages in the url are found, but aren't synced.
>> 
>> Log output from /var/log/rhn/reposync/ubuntu-1804-amd64-main-uyuni.log:
>> 
>> 2021/03/23 16:49:54 +02:00 Repo URL: http://archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64
>> 2021/03/23 16:49:54 +02:00     Packages in repo:              6391
>> 2021/03/23 16:49:54 +02:00     No new packages to sync.
>> 2021/03/23 16:49:54 +02:00 
>> 2021/03/23 16:49:54 +02:00   Patches in repo: 0.
>> 2021/03/23 16:49:54 +02:00 Sync completed.

I couldn't see a problem, the repo is sync completted successfully, there are 6391 packages in repo;

can we close this issue ?

**Comment by support-tt** [comment]
Hi @Shirocco88,
Sorry if the description was misleading. The files are found in the repo, but it won't download the files. It's basically empty.

**Comment by Shirocco88** [comment]
@support-tt 
>> The files are found in the repo, but it won't download the files. It's basically empty.

Could you please give more details, e.g. error message, ...
so we can reproduce the problem.

**Comment by support-tt** [comment]
Hello yes sorry here are some information if you need more feel free to ask me:
OS of the uyumi Server:
`
NAME="openSUSE Leap"
VERSION="15.2"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.2"
PRETTY_NAME="openSUSE Leap 15.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
`

Channel and Repository Settings:
`
Settings of non working Ubuntu channel
Channel Name*: ubuntu-1804-pool-amd64-uyuni
Channel Label*: ubuntu-1804-pool-amd64-uyuni
Parent Channel: None
Architecture: x86_64
Repository Checksum Type: sha256
Channel Summary*:  ubuntu-1804-pool-amd64-uyuni
Channel Description:
Testchannel

Repository Settings (we use the official Ubuntu Main Repo )
Repository Label*: Ubuntu 18.04 Bionic Main
Repository URL*: http://archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64/
Repository Type*: deb
Has Signed Metadata?: (tried true and false without success)
SSL CA Certificate: None
SSL Client Certificate: None
SSL Client Key: None
Filters: 
`

The Server has full internetconnection without any proxy.
Here is the Log of the spacewalk:
[spacewalk_Ubuntu_1804_debug.txt](https://github.com/uyuni-project/uyuni/files/6348740/spacewalk_Ubuntu_1804_debug.txt)

CentOS Sync is working without any issues.

Hope you maybe see the issues im new to uyuni so I hope this is not my vault..

**Comment by mcalmer** [comment]
```
Channel Name*: ubuntu-1804-pool-amd64-uyuni
Channel Label*: ubuntu-1804-pool-amd64-uyuni
Parent Channel: None
Architecture: x86_64
```

Wrong Architecture! The architecture names are different for Ubuntu/Debian. 
Look for "amd64" or "amd64-deb"

**Comment by support-tt** [comment]
Thank you for your help :)
In the dropdown for architecture I see:
  x86_64
  AMD64 Debian
both doesn't work for me and the other are for very special architecture like ARM.
The others are complete different architectures like ARM or IA

[spacewalk_Ubuntu_1804_debug_secondtest.txt](https://github.com/uyuni-project/uyuni/files/6349079/spacewalk_Ubuntu_1804_debug_secondtest.txt)

I will remove and readd the channel and repository config maybe this helps.

**Comment by support-tt** [comment]
Thank you it's working now my issue was that after all that testing I had a filter in the repository.
After changing the architecture from  x86_64 to AMD 64 Debian and removed the wrong filter it worked.
