### ISSUE TITLE
Unable to sync flat repository format for Debian repositories

### ISSUE THREAD

**Issue by lumarel** [uyuni-project/uyuni#3559]
# Additional Information

I tried to add and sync the Jenkins Debian Repository ([pkg.jenkins.io](https://pkg.jenkins.io/debian-stable/)) to our Uyuni Server, but I was unfortunately not able to find the correct way to insert the url so it gets downloaded.
Maybe I'm just missing something or maybe it is not possible.

## Version of Uyuni Server
`2021.02-116.3` on `OpenSUSE Leap 15.2` (this system has been setup lately so the packages are new)

## Details about issue

I'm following the guide in the documentation about the [Custom Channel Creation](https://www.uyuni-project.org/uyuni-docs/uyuni/administration/custom-channels.html#_creating_custom_channels_and_repositories), so I created a Channel via the UI and added a Repository with the deb type.

Configuration of the softwarechannel:
```
Label:              ubuntu-1804-amd64-jenkins
Name:               Jenkins repository for Ubuntu 18.04 AMD64
Architecture:       AMD64 Debian
Parent:             ubuntu-18.04-pool-amd64-uyuni
Systems Subscribed: 3
Number of Packages: 0

Summary
-------
Jenkins repository for Ubuntu 18.04 AMD64

GPG Key:            45F2C3D5
GPG Fingerprint:    62A9 756B FD78 0C37 7CF2  4BA8 FCEF 32E7 45F2 C3D5
GPG URL:            https://pkg.jenkins.io/debian-stable/jenkins.io.key
GPG CHECK:          True

Repos
-----
External - Jenkins repository AMD64
```

Configuration of the repository:
```
Repository Label:                  External - Jenkins repository AMD64
Repository URL:                    https://pkg.jenkins.io/debian-stable/binary/
Repository Type:                   deb
Repository SSL Ca Certificate:     None
Repository SSL Client Certificate: None
Repository SSL Client Key:         None
```

And here is the current output of the spacewalk-repo-sync:
```
2021/04/14 14:02:32 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'ubuntu-1804-amd64-jenkins', '--type', 'deb', '--non-interactive']
2021/04/14 14:02:32 +02:00 Sync of channel started.
2021/04/14 14:02:36 +02:00 Repo URL: https://pkg.jenkins.io/debian-stable/binary/
2021/04/14 14:02:36 +02:00     Packages in repo:               108
2021/04/14 14:02:36 +02:00     Packages already synced:          0
2021/04/14 14:02:36 +02:00     Packages to sync:               108
2021/04/14 14:02:36 +02:00     New packages to download:       108
2021/04/14 14:02:36 +02:00   Downloading packages:
2021/04/14 14:02:39 +02:00 ERROR: Download failed: https://pkg.jenkins.io/debian-stable/binary/direct/jenkins_1.466.2_all.deb - [Errno 14] HTTPS Error 404 - Not Found.
2021/04/14 14:02:39 +02:00     1/108 : jenkins_1.466.2_all.deb (failed)
2021/04/14 14:02:39 +02:00 ERROR: Download failed: https://pkg.jenkins.io/debian-stable/binary/direct/jenkins_2.7.3_all.deb - [Errno 14] HTTPS Error 404 - Not Found.
2021/04/14 14:02:39 +02:00     2/108 : jenkins_2.7.3_all.deb (failed)
...
2021/04/14 14:02:47 +02:00 ERROR: Download failed: https://pkg.jenkins.io/debian-stable/binary/binary/jenkins_2.277.2_all.deb - [Errno 14] HTTPS Error 404 - Not Found.
2021/04/14 14:02:47 +02:00     108/108 : jenkins_2.277.2_all.deb (failed)
2021/04/14 14:02:47 +02:00 Importing packages started.
2021/04/14 14:02:47 +02:00 
2021/04/14 14:02:47 +02:00   Importing packages to DB:
2021/04/14 14:02:48 +02:00   Package batch #2 of 6 completed...
2021/04/14 14:02:48 +02:00   Package batch #1 of 6 completed...
2021/04/14 14:02:48 +02:00   Package batch #4 of 6 completed...
2021/04/14 14:02:48 +02:00   Package batch #6 of 6 completed...
2021/04/14 14:02:48 +02:00   Package batch #3 of 6 completed...
2021/04/14 14:02:48 +02:00   Package batch #5 of 6 completed...
2021/04/14 14:02:48 +02:00 Importing packages finished.
2021/04/14 14:02:48 +02:00 
2021/04/14 14:02:48 +02:00   Patches in repo: 0.
```

**Comment by Shirocco88** [comment]
@lumarel 
``
2021/04/14 14:02:39 +02:00 ERROR: Download failed: https://pkg.jenkins.io/debian-stable/binary/direct/jenkins_1.466.2_all.deb - 
[Errno 14] HTTPS Error 404 - Not Found.
2021/04/14 14:02:39 +02:00     1/108 : jenkins_1.466.2_all.deb (failed)
2021/04/14 14:02:39 +02:00 ERROR: Download failed: https://pkg.jenkins.io/debian-stable/binary/direct/jenkins_2.7.3_all.deb - 
[Errno 14] HTTPS Error 404 - Not Found.
2021/04/14 14:02:39 +02:00     2/108 : jenkins_2.7.3_all.deb (failed)
``
could you please try with:
``
URLGRABBER_DEBUG=1;
spacewalk-repo-sync -c ubuntu-1804-amd64-jenkins -vvv
``

please post cmd output;

**Comment by lumarel** [comment]
Thank you for helping @Shirocco88 !

Here is the output in [a gist](https://gist.github.com/lumarel/0bae591f455719a3c342b0fe9657b06f)

This already shows me something more, it actually searches in the right path, but on the wrong domain..

**Comment by brejoc** [comment]
I think we've also seen this internally. Could be related to the `is_flat` detection. I'll be looking into this.

**Comment by lumarel** [comment]
Thank you very much!
If I can help somehow I will gladly do that, I'm just quite new to this product and didn't find the right code up to now.

**Comment by Shirocco88** [comment]
@lumarel:
Could you please test to exclude the packages with error404 by: 
```
spacecmd repo_addfilters 'ubuntu-1804-amd64-jenkins' '-conflicting_package*'; 
e.g.
spacecmd repo_addfilters 'ubuntu-1804-amd64-jenkins' '-jenkins_1.466.2_*'; 
```
it seams that jenkins repo for debian is inkonsistent
and uyuni want's to do a full mirroring and runs into error404.

**Comment by lumarel** [comment]
Hm I think this is a more substantial problem @Shirocco88, because I see the exact same behavior for every package, which would mean I would have to exclude all packages.

But I tried it anyways! As far as I can see (also tried to make a diff from the logs) the outputs are nearly identical, maybe the filter only takes in place after the download of the file. I also verified that the filter is in place.

Maybe it is really a problem with the flat-detection, as brejoc mentioned.

**Comment by Shirocco88** [comment]
@brejoc: is there something that can be done to help to solve the problem ?

**Comment by vzhestkov** [comment]
The problem is bit deeper.
spacewalk-repo-sync is trying to get https://pkg.jenkins.io/debian-stable/binary/direct/jenkins_1.466.2_all.deb
while the package is actually placed at https://pkg.jenkins.io/debian-stable/direct/jenkins_1.466.2_all.deb
In general it detects repo as a flat one, but it's actually not flat, as @brejoc said.
More tricky thing that it doesn't contain `Components`, just a `Suite` in the Release file and doesn't match the file placement we expects from non flat repos.

Debian repository specification defines package source as:
`deb uri distribution [component1] [component2] [...]`
Flat repos defined with distribution set to `/` and no components listed.
This one has distribution (Suite) set to `binary` with no components.
For repo definition we are using `https://pkg.jenkins.io/debian-stable/binary/` while the correct one is `https://pkg.jenkins.io/debian-stable/` with `binary` suite, but modification of the URL will not help as we are not providing `Suite` with the URL in this case.

Will try to find out possible solutions.

**Comment by lumarel** [comment]
Thank you for further tracking this down @vzhestkov !

Yeah, they are definitely doing weird stuff, but they still stick with it as it works, if you put it in the sources.list file.
Little bit unfortunate but it is as it is.

Hope you can find an easy solution!

**Comment by vzhestkov** [comment]
@lumarel, I created PR with the fix making reposync working with this repo: https://github.com/uyuni-project/uyuni/pull/3921
You may check the fix on your server, it's quite simple to add, but requre changing the URL for this repo to `https://pkg.jenkins.io/debian-stable/binary/../` looks strange, but it's the only way I found how to pass two distinct path points with the only URL field.

**Comment by agraul** [comment]
Maybe this is nonsense, but have you investigated using `deb uri distribution [component1] [component2] [...]` as input for the "Repository URL"?

**Comment by vzhestkov** [comment]
There are 2 points to not to do it this way:
1. It will harm URL format of the field in web UI and in the DB, probably not too bad, but some side effects are possible.
2. Definition with format `deb uri distribution [component1] [component2] [...]` actually points not to just one entity which we defines as a distinct repository, but in case of using multiple components refers to more than one repo. Probably not bad also and for Debian users could look more native and understandable, but requires way more complicated changes in the code especially for the cases with multiple components.

**Comment by lumarel** [comment]
I just tried out the pull-request on my system, and it really works as intended!
One note, this really can't be found out by just playing around, so a message in the documenation would be necessary, that in such cases a '../' has to be added to the URI.

**Comment by agraul** [comment]
> There are 2 points to not to do it this way:
> 
>     1. It will harm URL format of the field in web UI and in the DB, probably not too bad, but some side effects are possible.
> 
It would be more work to change the UI, but I think it is possible. There is the "Repository Type" dropdown that could be compared to "deb" and show a different "Repository URL" field or something like that. The current patch could also use some hint in the UI, having to specify trailing `../` is not really intuitive.

>     2. Definition with format `deb uri distribution [component1] [component2] [...]` actually points not to just one entity which we defines as a distinct repository, but in case of using multiple components refers to more than one repo. Probably not bad also and for Debian users could look more native and understandable, but requires way more complicated changes in the code especially for the cases with multiple components.

Sure, it would be a bigger change. But maybe it would be worth doing nonetheless, I image it would be a lot more intuitive for Debian admins that use Uyuni. And we wouldn't have to resort to hacks such as `../`. It works, but it isn't nice.

**Comment by lumarel** [comment]
I really don't like to compare the projects, but this is actually the way how Katello/Pulp is doing it, they have separate components for releases, components and architectures in the UI.
They also had the same problem with the flat-structure, if I remember correctly they created a whole new type, which has to be selected.

**Comment by vzhestkov** [comment]
@agraul, sure it's better to impelement native solution working the same way as apt sources in Debian, but it will take much more effort, almost full refacroting of deb_src plugin. I don't like the current solution of determination if the repo is flat or not, not less magic than in this solution. Now I just see that it will be quite hard to modify the code to handle multiple components even if parse the URL as an APT source entry.

**Comment by Shirocco88** [comment]
>  vzhestkov: commented on 28 Jun
> @lumarel, I created PR with the fix making reposync working with this repo: #3921
> You may check the fix on your server, it's quite simple to add

@lumarel : have you already able to test PR #3921 ?

**Comment by lumarel** [comment]
@Shirocco88 Sorry I was kind of dragged out of all of this for the last 20 days,
just tried the latest changes, and... I don't know right now how I have to enter the URI 🙂
Before the change with the ugly `/../` it worked, but since then I upgraded, which removed this fix again,
and now with the new fix:

- `https://pkg.jenkins.io/debian-stable/binary/` or `https://pkg.jenkins.io/debian-stable/binary`:

```
2021/08/30 20:51:04 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'ubuntu-2004-amd64-jenkins', '--type', 'deb', '--non-interactive']
2021/08/30 20:51:04 +02:00 Sync of channel started.
2021/08/30 20:51:05 +02:00 Repo URL: https://pkg.jenkins.io/debian-stable/binary/
2021/08/30 20:51:05 +02:00     Packages in repo:               114
2021/08/30 20:51:05 +02:00     Packages already synced:        113
2021/08/30 20:51:05 +02:00     Packages to sync:                 1
2021/08/30 20:51:05 +02:00     New packages to download:         1
2021/08/30 20:51:05 +02:00   Downloading packages:
2021/08/30 20:51:06 +02:00 ERROR: Download failed: https://pkg.jenkins.io/debian-stable/binary/binary/jenkins_2.303.1_all.deb - [Errno 14] HTTPS Error 404 - Not Found.
2021/08/30 20:51:06 +02:00     1/1 : jenkins_2.303.1_all.deb (failed)
```

(also looked at the most verbose log, but nothing helpful)

- removed `binary/` finds nothing
- added `/../` also finds nothing
- changed to `https://pkg.jenkins.io/debian-stable binary/` also finds nothing

I also restarted the uyuni-server in between the changes so to make sure it uses the updated python module, but I'm not sure how I need to enter it now

Maybe you know more than me 🙂

**Comment by vzhestkov** [comment]
@lumarel with the latest updated PR try this url:
```
https://pkg.jenkins.io/debian-stable?uyuni_suite=binary/
```

**Comment by lumarel** [comment]
> 
> 
> @lumarel with the latest updated PR try this url:
> 
> ```
> https://pkg.jenkins.io/debian-stable?uyuni_suite=binary/
> ```

Thank you for that tipp @vzhestkov !
That did the trick, it is working now 👌🏻

**Comment by lumarel** [comment]
Oh and... sorry I should have read the PR description again... Just saw that you added the solution to there

**Comment by vzhestkov** [comment]
No problem. If you know any other non-flat repos and can check it, it would be great

**Comment by lumarel** [comment]
I have kind of a "big" suite of non-flat repos over Ubuntu 16.04/18.04/20.04 (all default + Docker, Elastic, Jenkins, MS, PostgreSQL, Zabbix, ...) , tried all of them now and everything looks fine!
(I also heard MS has an flat repo but I didn't have any use for that up to now, only have the Jenkins flat repo)
I unfortunately don't have any Debian systems and so repos for them in here, maybe one of you has something like that setup anywhere.

**Comment by lumarel** [comment]
@vzhestkov I just upgraded to 2021.09 and re-added the patch, still works like a charm!

**Comment by Shirocco88** [comment]
@vzhestkov 
Thanks for providing PR https://github.com/uyuni-project/uyuni/pull/3921

I've tested with Jenkins Repos:
Ubuntu-20.04:
https://pkg.jenkins.io/debian-stable?uyuni_suite=binary/
#
Ubuntu-18.04:
https://pkg.jenkins.io/debian-stable?uyuni_suite=binary/
#
Debian-10:
https://pkg.jenkins.io/debian-stable?uyuni_suite=binary/
#
==> everything is running quite well.


But now I run into trouble with RepoSync of GitLan-Runner
Ubuntu-20.04:
https://packages.gitlab.com/runner/gitlab-runner/ubuntu?uyuni_suite=focal&uyuni_component=main
#
Ubuntu-18.04:
https://packages.gitlab.com/runner/gitlab-runner/ubuntu?uyuni_suite=bionic&uyuni_component=main
#
Debian-10:
https://packages.gitlab.com/runner/gitlab-runner/debian?uyuni_suite=buster&uyuni_component=main


Logfile:
# cat /var/log/rhn/reposync/debian-9-amd64-gitlab-runner.log
2021/11/05 09:45:43 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '-c', 'debian-9-amd64-gitlab-runner']
2021/11/05 09:45:43 +02:00 Sync of channel started.
2021/11/05 09:45:43 +02:00 Base URL: https://packages.gitlab.com/runner/gitlab-runner/debian
2021/11/05 09:45:43 +02:00 Suite: stretch
2021/11/05 09:45:43 +02:00 Component: main
2021/11/05 09:45:43 +02:00 Unhandled error occurred: name 'rhnSQL' is not defined
2021/11/05 09:45:43 +02:00 Unexpected error: <class 'NameError'>
2021/11/05 09:45:43 +02:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 574, in sync
    client_key_file=client_key_file)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 338, in __init__
    self.proxy_addr, self.proxy_user, self.proxy_pass, gpg_verify=not(insecure))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 127, in __init__
    rhnSQL.initDB()
NameError: name 'rhnSQL' is not defined


Excerp from Repo-Installation-Doku: https://packages.gitlab.com/runner/gitlab-runner/install#manual-deb
Create a file named /etc/apt/sources.list.d/runner_gitlab-runner.list that contains the repository configuration below.
Make sure to replace ubuntu and trusty in the config below with your Linux distribution and version:
#
deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ bionic main
deb-src https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ bionic main
#


@vzhestkov:
could you please give me a hint, how to solve the problem;

**Comment by vzhestkov** [comment]
@Shirocco88 please try https://github.com/uyuni-project/uyuni/pull/4443.
One line missing during PR modifications

**Comment by Shirocco88** [comment]
@vzhestkov 
modified file "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py"
but there is still an error:

/usr/bin/spacewalk-repo-sync -c debian-9-amd64-gitlab-runner
15:38:56 ======================================
15:38:56 | Channel: debian-9-amd64-gitlab-runner
15:38:56 ======================================
15:38:56 Sync of channel started.
15:38:56 Base URL: https://packages.gitlab.com/runner/gitlab-runner/debian
15:38:56 Suite: stretch
15:38:56 Component: main
15:38:56 Unhandled error occurred: name 'channel_label' is not defined
15:38:56 Unexpected error: <class 'NameError'>
15:38:56 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 574, in sync
    client_key_file=client_key_file)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 339, in __init__
    self.proxy_addr, self.proxy_user, self.proxy_pass, gpg_verify=not(insecure))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 136, in __init__
    h.execute(channel_label=channel_label)
NameError: name 'channel_label' is not defined
15:38:56 Total time: 0:00:00

What has do be done to fix this issue ?

**Comment by Shirocco88** [comment]
@vzhestkov 
Did another test:

# /usr/bin/spacewalk-repo-sync -c debian-9-amd64-gitlab-runner  -u https://packages.gitlab.com/runner/gitlab-runner/debian?uyuni_suite=stretch&uyuni_component=main -p debian-9-pool                                                                                 [1] 15411
If '-p' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf -p
# 15:50:31 ======================================
15:50:31 | Channel: debian-9-amd64-gitlab-runner
15:50:31 ======================================
15:50:31 Sync of channel started.
error: /tmp/tmptzfjrike: key 1 import failed.
Retrieving repository 'debian-9-amd64-gitlab-runner' metadata ..............................................................................[error]
15:50:33 RepoMDError: Cannot access repository.
Repository 'debian-9-amd64-gitlab-runner' is invalid.
[debian-9-amd64-gitlab-runner|https://packages.gitlab.com/runner/gitlab-runner/debian?uyuni_suite=stretch&proxy=http%3A//proxy.corp.lan%3A3128] Valid metadata not found at specified URL
History:
 - [debian-9-amd64-gitlab-runner|https://packages.gitlab.com/runner/gitlab-runner/debian?uyuni_suite=stretch&proxy=http%3A//proxy.corp.lan%3A3128] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'debian-9-amd64-gitlab-runner' because of the above error.
Could not refresh the repositories because of errors.
15:50:33 Total time: 0:00:02
[1]+  Exit 1                  /usr/bin/spacewalk-repo-sync -c debian-9-amd64-gitlab-runner -u https://packages.gitlab.com/runner/gitlab-runner/debian?uyuni_suite=stretch
#

Is there a problem with key or proxy ?

How can I debug this ?

**Comment by vzhestkov** [comment]
Have not tested on my system, but stupid guess on first glance: are you sure the `deb` is selected as channel type?

**Comment by Shirocco88** [comment]
yes
Repository Type='deb'

Channel Architecture = 'AMD64 Debian'

**Comment by vzhestkov** [comment]
Try to run reposync the following way: `URLGRABBER_DEBUG=DEBUG spacewalk-repo-sync -c debian-9-amd64-gitlab-runner`

I just updated the PR to fix https://github.com/uyuni-project/uyuni/issues/3559#issuecomment-961952215
Here is the test of running `spacewalk-repo-sync -c gitlab-runner`:
```
18:42:20 ======================================
18:42:20 | Channel: gitlab-runner
18:42:20 ======================================
18:42:20 Sync of channel started.
18:42:20 Base URL: https://packages.gitlab.com/runner/gitlab-runner/debian
18:42:20 Suite: stretch
18:42:20 Component: main
18:42:20 Channel architecture: amd64
18:42:24 Repo URL: https://packages.gitlab.com/runner/gitlab-runner/debian?uyuni_suite=stretch&uyuni_component=main
18:42:24     Packages in repo:                99
18:42:26     Packages already synced:          0
18:42:26     Packages to sync:                99
18:42:27     New packages to download:        99
18:42:27   Downloading packages:
18:42:27 Downloading total 99 files from 1 queues.
18:42:34     1/99 : gitlab-runner_10.0.0_amd64.deb
18:42:49     2/99 : gitlab-runner_10.1.0_amd64.deb
18:42:49     3/99 : gitlab-runner_10.0.2_amd64.deb
18:42:50     4/99 : gitlab-runner_10.0.1_amd64.deb
18:42:51     5/99 : gitlab-runner_10.2.0_amd64.deb
...
```

**Comment by Shirocco88** [comment]
output as requested:

URLGRABBER_DEBUG=DEBUG spacewalk-repo-sync -c debian-9-amd64-gitlab-runner
2021-11-05 17:10:23,490 urlgrabber version  = 3.10.2
2021-11-05 17:10:23,490 trans function "_"  = <function _ at 0x7f42ee5aaf28>
17:10:23 ======================================
17:10:23 | Channel: debian-9-amd64-gitlab-runner
17:10:23 ======================================
17:10:23 Sync of channel started.
17:10:23 Base URL: https://packages.gitlab.com/runner/gitlab-runner/debian
17:10:23 Suite: stretch
17:10:23 Component: main
17:10:23 Unhandled error occurred: name 'channel_label' is not defined
17:10:23 Unexpected error: <class 'NameError'>
17:10:23 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 574, in sync
    client_key_file=client_key_file)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 339, in __init__
    self.proxy_addr, self.proxy_user, self.proxy_pass, gpg_verify=not(insecure))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 136, in __init__
    h.execute(channel_label=channel_label)
NameError: name 'channel_label' is not defined
17:10:23 Total time: 0:00:00

**Comment by Shirocco88** [comment]
Details to reproduce this issue:


====================================================================
Channel Details:

Channel Name: Debian 9 (stretch) AMD64 GitLab-Runner
Channel Label: debian-9-amd64-gitlab-runner
Parent Channel: debian-9-pool 
Architecture: AMD64 Debian
Repository Checksum Type: sha256
Channel Summary: Debian 9 (stretch) AMD64 GitLab-Runner
Enable GPG Check: No
====================================================================
Repository Details:

Repository Label:
Repository URL: 
Repository Type: deb
Has Signed Metadata: No
SSL CA Certificate: None
SSL Client Certificate: None
SSL Client Key: None
Filters: 
====================================================================

**Comment by vzhestkov** [comment]
@Shirocco88 I mean I've updated PR and there is a fix for this:
```
17:10:23 Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 574, in sync
client_key_file=client_key_file)
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 339, in init
self.proxy_addr, self.proxy_user, self.proxy_pass, gpg_verify=not(insecure))
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 136, in init
h.execute(channel_label=channel_label)
NameError: name 'channel_label' is not defined
```

https://github.com/uyuni-project/uyuni/pull/4443/commits/ef51369a445ac7c607e65c8352075cc1f01cf1bb

**Comment by Shirocco88** [comment]
OK, I'll test updated PR https://github.com/uyuni-project/uyuni/pull/4443/files

**Comment by Shirocco88** [comment]
Now it is working!!!
Thank You!!!

spacewalk-repo-sync -c debian-9-amd64-gitlab-runner
17:24:49 ======================================
17:24:49 | Channel: debian-9-amd64-gitlab-runner
17:24:49 ======================================
17:24:49 Sync of channel started.
17:24:49 Base URL: https://packages.gitlab.com/runner/gitlab-runner/debian
17:24:49 Suite: stretch
17:24:49 Component: main
17:24:49 Channel architecture: amd64
17:24:53 Repo URL: https://packages.gitlab.com/runner/gitlab-runner/debian?uyuni_suite=stretch&uyuni_component=main
17:24:53     Packages in repo:                99
17:24:53     Packages already synced:          0
17:24:53     Packages to sync:                99
17:24:53     New packages to download:        99
17:24:53   Downloading packages:
17:24:53 Downloading total 99 files from 1 queues.
17:24:55     1/99 : gitlab-runner_10.0.0_amd64.deb
17:24:56     2/99 : gitlab-runner_10.2.0_amd64.deb
17:24:57     3/99 : gitlab-runner_10.2.1_amd64.deb
