### ISSUE TITLE
Uyuni Client tools repo missing python3-certifi package for CentOS 8

### ISSUE THREAD

**Issue by an0nz** [uyuni-project/uyuni#3567]
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.02-116.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.02-116.3.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
Minion is unable to update Uyuni client tools due to missing python3-certifi package

OS: CentOS 8
Existing Packages
openpgm.x86_64                       5.2.122-16.30.uyuni                    @susemanager:centos8-uyuni-client-x86_64
python3-m2crypto.x86_64              0.35.2-1.27.uyuni                      @susemanager:centos8-uyuni-client-x86_64
python3-msgpack.x86_64               0.4.6-1.32.uyuni                       @susemanager:centos8-uyuni-client-x86_64
python3-salt.x86_64                  3000-25.1.uyuni                        @susemanager:centos8-uyuni-client-x86_64
python3-tornado.x86_64               4.2.1-1.32.uyuni                       @susemanager:centos8-uyuni-client-x86_64
python3-zmq.x86_64                   17.0.0-4.30.uyuni                      @susemanager:centos8-uyuni-client-x86_64
salt.x86_64                          3000-25.1.uyuni                        @susemanager:centos8-uyuni-client-x86_64
salt-minion.x86_64                   3000-25.1.uyuni                        @susemanager:centos8-uyuni-client-x86_64
zeromq.x86_64                        4.1.6-11.28.uyuni                      @susemanager:centos8-uyuni-client-x86_64

dnf update salt salt-minion
Error: 
 Problem 1: package salt-3000-29.1.uyuni.x86_64 requires python3-salt = 3000-29.1.uyuni, but none of the providers can be installed
  - cannot install the best update candidate for package salt-3000-25.1.uyuni.x86_64
  - nothing provides python3-certifi needed by python3-salt-3000-29.1.uyuni.x86_64
 Problem 2: package salt-minion-3000-29.1.uyuni.x86_64 requires salt = 3000-29.1.uyuni, but none of the providers can be installed
  - package salt-3000-29.1.uyuni.x86_64 requires python3-salt = 3000-29.1.uyuni, but none of the providers can be installed
  - cannot install the best update candidate for package salt-minion-3000-25.1.uyuni.x86_64
  - nothing provides python3-certifi needed by python3-salt-3000-29.1.uyuni.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

python3-certifi package only exists in EPEL so this can be fixed by adding EPEL to the client provided the EPEL repo is configured to exclude all other packages required by Uyuni client tools.
Bootstrapping likely also fails as this package isn't listed in uyuni/susemanager/src/mgr_bootstrap_data.py

The dependency doesn't exist in the client tools repo for CentOS 8 at https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS8-Uyuni-Client-Tools/CentOS_8/x86_64/

**Comment by brejoc** [comment]
I think we should be able to fix this with [this PR](https://github.com/uyuni-project/uyuni/pull/3641).

**Comment by juliogonzalez** [comment]
@an0nz pythin-certifi is not required for RES8 on the latest released salt:

https://build.opensuse.org/package/view_file/systemsmanagement:Uyuni:Stable:CentOS8-Uyuni-Client-Tools/salt/salt.spec?expand=1

```
%if 0%{?rhel} && 0%{?rhel} < 8
Requires:       python-certifi
%endif
```

Can you please resync your client tools channel for CentOS8 at your server? You have `3000-29.1.uyuni` but stable has `3000-36.2` already.

**Comment by an0nz** [comment]
Our client tools sync's every 24 hours and it was up to date at the time of raising the issue so it must have been a problem in the previous stable release.

I have tested again on our clients and they successfully updated to salt-3000-36.2.uyuni.x86_64 so this issue looks to be resolved in the latest stable version, thanks for the quick turnaround.
