### ISSUE TITLE
Oranization Config broken after update to 2021.02

### ISSUE THREAD

**Issue by bochi** [uyuni-project/uyuni#3569]
Hi,

I upgraded to 2021.02 and whenever I go to "Organization config" (or click on the Org Name top right), I get the following in the logs and an Internal Server Error.

https://gist.github.com/bochi/cd8f2970c160257ca2a9def2a54a74ae

Any hints appreciated.

Thanks
Stefan

**Comment by Shirocco88** [comment]
Is this Problem with Uyuni-2021.04 still existent ?

**Comment by brejoc** [comment]
@Shirocco88 Did you also run into this problem? I can't see something like this on our reference server.

**Comment by Shirocco88** [comment]
@brejoc : at the moment I don't use config channels;

**Comment by bochi** [comment]
I am going to update asap and give feedback whether or not the problem vanishes.

**Comment by bochi** [comment]
Finally got to upgrade to 2021.04 and the issue vanished. Closing :)
