### ISSUE TITLE
Uyuni packages depend on snapper

### ISSUE THREAD

**Issue by ppc6446** [uyuni-project/uyuni#3586]
# Additional Information

To avoid btrfs-related filesystem corruption commonly seen on busy VMs when VMware DRS is in use, snapper and btrfs are not in use on the system hosting the Uyuni server.  Rather than manage snapper-related services and package updates, it would be preferable to be able to remove snapper without removing packages related to Uyuni.

## Version of Uyuni Server and Proxy (if used)
```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.02-116.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.02-116.3.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```
## Details about issue

# zypper remove snapper
Reading installed packages...
Resolving package dependencies...

The following 11 packages are going to be REMOVED:
  patterns-uyuni_server python3-dnf-plugin-snapper snapper snapper-zypp-plugin
  spacewalk-common spacewalk-java spacewalk-postgresql
  supportutils-plugin-susemanager susemanager uyuni-cluster-provider-caasp
  yast2-snapper

The following pattern is going to be REMOVED:
  uyuni_server

11 packages to remove.
After the operation, 20.8 MiB will be freed.

 # df -Tlh
Filesystem                       Type      Size  Used Avail Use% Mounted on
devtmpfs                         devtmpfs  3.9G  8.0K  3.9G   1% /dev
tmpfs                            tmpfs     3.9G  412K  3.9G   1% /dev/shm
tmpfs                            tmpfs     3.9G  9.2M  3.9G   1% /run
tmpfs                            tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/mapper/system-root          xfs        38G  7.0G   31G  19% /
/dev/mapper/uyunivg-varlibpgsql  xfs        50G   19G   32G  38% /var/lib/pgsql
/dev/mapper/uyunivg-varspacewalk xfs       350G  235G  116G  68% /var/spacewalk
tmpfs                            tmpfs     796M     0  796M   0% /run/user/31631

**Comment by Shirocco88** [comment]
@ppc6446 :
Why do you want to remove snapper ?
I couldn't find a btrfs filesystem;

```
df -Tlh
Filesystem Type Size Used Avail Use% Mounted on
/dev/mapper/system-root xfs 38G 7.0G 31G 19% /
/dev/mapper/uyunivg-varlibpgsql xfs 50G 19G 32G 38% /var/lib/pgsql
/dev/mapper/uyunivg-varspacewalk xfs 350G 235G 116G 68% /var/spacewalk
```

**Comment by ppc6446** [comment]
The reason for removing snapper is to have one less unused component on the system generating logs and requiring updates.

Earlier today, I noticed it snapper-related messages in the system logs and that snapper-timeline and snapper-cleanup were enabled in systemd, so I disabled them as there is no btrfs filesystem or thin LVM volume in use for snapper to create snapshots for.

Now the dbus-daemon logging snapper-related messages is the chattiest thing in syslog -

2021-04-20T20:00:05.758738-04:00 snip dbus-daemon[1207]: [system] Activating service name='org.opensuse.Snapper' requested by ':1.225' (uid=0 pid=22996 comm="/usr/lib/snapper/systemd-helper --timeline ") (using servicehelper)
2021-04-20T21:00:05.759816-04:00 snip dbus-daemon[1207]: [system] Activating service name='org.opensuse.Snapper' requested by ':1.228' (uid=0 pid=26261 comm="/usr/lib/snapper/systemd-helper --timeline ") (using servicehelper)
2021-04-20T22:00:05.755734-04:00 snip dbus-daemon[1207]: [system] Activating service name='org.opensuse.Snapper' requested by ':1.231' (uid=0 pid=29173 comm="/usr/lib/snapper/systemd-helper --timeline ") (using servicehelper)
2021-04-20T23:00:05.752469-04:00 snip dbus-daemon[1207]: [system] Activating service name='org.opensuse.Snapper' requested by ':1.234' (uid=0 pid=32073 comm="/usr/lib/snapper/systemd-helper --timeline ") (using servicehelper)

**Comment by Shirocco88** [comment]
@ppc6446 
this is no uyuni issue;
you should open contact opensuse leap15.2 community support.

**Comment by ppc6446** [comment]
To clarify, does the openSUSE team own the packaging for Uyuni, while this github owns the code inside the packages?

**Comment by Shirocco88** [comment]
Yes, this is also my understanding;
 
Reganding os dependency: every os dependency should be defined zypper "patterns-uyuni_server"

**Comment by Shirocco88** [comment]
more Inputs: 
https://gitter.im/uyuni-project/users?at=6081802aa9dd556843f452db
@ppc6446   Apr 22 15:54
>> Btw, for uyuni-project/uyuni#3586 any idea which openSUSE team owns the Uyuni rpm's? I am still learning which places different things should go

https://gitter.im/uyuni-project/users?at=6081a37a2e5574669b520b4f
@paususe  Apr 22 18:25
>> Uyuni (SUSE Manager) team owns the Uyuni RPMs. Uyuni is not openSUSE but a separate project, loosely associated with openSUSE. Here you have where to find all the source code for the different bits: https://www.uyuni-project.org/pages/source-code.html

**Comment by ppc6446** [comment]
Thank you for the additional information.  Rather than creating custom packages for Uyuni, our goal is to have the dependencies official packages changed so it can make its way to our downstream installation with official support.

**Comment by brejoc** [comment]
The susemanager pkg has a requirement on snapper. So this has nothing to do with openSUSE.
