### ISSUE TITLE
Error generating bootstrap: openSUSE-Leap-15.2-x86_64-uyuni ERROR: package 'gio-branding-SLE' not found

### ISSUE THREAD

**Issue by StefanSa** [uyuni-project/uyuni#3633]
# Additional Information
The following error message is generated during the daily bootstrap repo creation.
```
Error generating bootstrap repo for: openSUSE-Leap-15.2-x86_64-uyuni ERROR: package 'gio-branding-SLE' not found
```
However, the boostrap repo is created correctly.

@juliogonzalez makes the following comment:
` 
it's a bug https://github.com/uyuni-project/uyuni/blob/master/susemanager/src/mgr_bootstrap_data.py#L462 is common for leap and sle there, which is not correct
other than the error showing up, things should work for you, as the bootstrap repo should be created anyway
and that package missing only prevents SLE15 JeOS bootstrapping, which is not your case
`

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release`
```
zypper info Uyuni-Server-release
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...


Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : uyuni-server-stable
Name               : Uyuni-Server-release
Version            : 2021.04-122.3.uyuni
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3
Installierte Größe : 1,4 KiB
Installiert        : Ja
Status             : veraltet (Version 2021.01-107.1.uyuni installiert)
Quellpaket         : Uyuni-Server-release-2021.04-122.3.uyuni.src
Zusammenfassung    : Uyuni Server
Beschreibung       :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by juliogonzalez** [comment]
I will split https://github.com/uyuni-project/uyuni/blob/master/susemanager/src/mgr_bootstrap_data.py#L462 to a different group, only for SLE.

**Comment by juliogonzalez** [comment]
PR with the fix is now pending review.
