### ISSUE TITLE
salt-ssh writing to /var/cache/salt/master/jobs as root, leading to errors

### ISSUE THREAD

**Issue by ppc6446** [uyuni-project/uyuni#3700]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.04-122.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.04-122.3.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
After a salt-ssh command is run, for example `salt-ssh testhost cmd.run uptime`, files are left over under /var/cache/salt/master/jobs with root ownership (rather than salt:salt like the rest of the files in this tree)

This is repetitively logged about in the journal by salt-master -

```
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/84/8c6a3367da9ab12b934392a4344a98ce3a34c733e767f349157a1279adee72: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/8a/64b6fded0540fe923c5092ef46a56a9849783e7c63c281ef162c1a1e0852ea: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/b5/e60bdaf80b2506ec5a1b46c8a415e28e132110fff87c7dbe5fd8aafdce3011: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/45/cff3bc28699d2ad93942ce175efe24452ef9a01d46ecc8f6c1359c30479283: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/41/e581e961985a1b9d259beb18d3c46a064b87694b161fbacbd82977b12f48cc: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/12/24d5e24aa2d1abd765892d16c9b0c77c7685a0ea9d87f0cf5a233278f3a672: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/c2/e359abac9e14d945bd1a6e80462cdf44060a3c87e963f7ac5998a8797bd8fd: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/e8/131d69b90f32095d224ba10fc50f3642d5f160327c71820eec86209ec38083: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/0d/627185411eb6cc3d0d4325d1e00b7f0c35ddd271c970e472b6d0a115b9a020: [Errno 13] Permission denied: 'jid'
May 04 20:35:43 salt-master[2416]: [ERROR   ] Unable to remove /var/cache/salt/master/jobs/06/b826f125483670f3cce722081f50ebfaa5506b4121e398613275c8b63abd02: [Errno 13] Permission denied: 'jid'
```

```
\# journalctl -u salt-master | grep -c "Unable to remove"
56175
```

I cross-checked this with a SUMA 4.1 system and saw the same results.

**Comment by ppc6446** [comment]
To update, on these systems, the ssh key directories are owned by root -

~> whoami
salt
~> salt-ssh 'snip*' test.ping
Saving key "/etc/salt/pki/master/ssh/salt-ssh.rsa" failed: Permission denied

/etc/salt/pki/master> ls -ld ssh
drwx------ 2 root root 50 Apr 26 08:37 ssh

It may be necessary for salt-ssh to drop privileges to 'salt' if it will lead to permissions errors when run as root.

I wonder whether use case of salt-ssh for systems that don't have support for a full salt client may be better served by the upcoming ansible support.  The only reason for trying salt-ssh on these particular systems was they are openSUSE Tumbleweed / Fedora rather than an explicitly supported release of enterprise Linux

**Comment by agraul** [comment]
This should be fixed. I think salt-ssh should be able to run as another user and potentially use another key directory. Or maybe we could use a `salt` group that has access to the directory (not the keys, they should only be readable by their respective users). Salt could do better with supporting non-root use on the Salt Master, the newly formed Security Working Group wants to work on this.

> I wonder whether use case of salt-ssh for systems that don't have support for a full salt client may be better served by the upcoming ansible support.

The upcoming support runs  the ansible "payload" through Salt's ansiblegate module. Salt-ssh is still used.

**Comment by agraul** [comment]
@ppc6446 did you run salt-ssh as `root` before you ran it as `salt`? I just did a fresh installation of `salt-ssh`, called it with ` sudo -u salt salt-ssh 'sles15sp2*' test.ping` and got this:
```
suma:/ # ls -l /etc/salt/pki/master/ssh
total 8
-rw------- 1 salt salt 2590 May 17 19:03 salt-ssh.rsa
-rw-r--r-- 1 salt salt  563 May 17 19:03 salt-ssh.rsa.pub
```

It could be that they are created on first run (or rather when they don't exist). This directory isn't owned by any package, but I think it shouldn't be a subdirectory of `master` (which is owned by `salt-master`). A clearer separation is definitely needed.

**Comment by ppc6446** [comment]
Yes, salt-ssh was run as the root user.

The /etc/salt/pki/master/ssh/ ownership is set to root:root, while the keyfiles are owned by salt:salt, so salt-ssh run as the salt user is not successful.

If the salt user should be used with salt-ssh, could this be documented?

**Comment by ppc6446** [comment]
After setting /etc/salt/pki/master/ssh/ to salt:salt, salt-ssh (and the salt command as well) can be run as the salt user from the Uyuni server.

**Comment by mcalmer** [comment]
Salt do not want to change this. So we have to live with it. There is a documentation task open.
Currently I cannot see nothing else we can do.
Closing
