### ISSUE TITLE
Implement API to gather whether an erratum required a reboot

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#3733]
# Additional Information

I'm trying to check whether a particular erratum requires a reboot. This is independent of the system as this meta information is stored in the database. You can see it from the web UI:

![grafik](https://user-images.githubusercontent.com/5862725/117618218-e830dc80-b16d-11eb-9ac1-e68078ae4233.png)

## Version of Uyuni Server and Proxy (if used)
```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.04-122.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1,4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.01-107.1.uyuni installed)
Source package : Uyuni-Server-release-2021.04-122.3.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.


package 'Uyuni-Proxy-release' not found.
```

## Details about issue

I figured out that there is a call `listSuggestedReboot` that lists systems that have recently installed errata that require a reboot - anyhow it would be nice to have an API call that show this information **before** errata have been installed. I think this information could be part of the `errata.getDetails` call.

This API could can be important for further automation.

**Comment by agraul** [comment]
I need to check if this is already exposed by the xmlrpc api and `spacecmd` is just not printing it or if this needs changes on the server side. From skimming the code I think it's not part of the answer yet.
