### ISSUE TITLE
AlmaLinux upstream repos left enabled during client bootstrap - yum hanging

### ISSUE THREAD

**Issue by ppc6446** [uyuni-project/uyuni#3755]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.04-122.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.04-122.3.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
An error is logged in the WebUI when activating AlmaLinux, but yum is left running indefinitely, trying to hit internet sites instead of using the bootstrap repo provided by Uyuni.

Set the repos in /etc/yum.repos.d/almalinux*repo to enabled=0 allowed bootstrap.sh to work (WebUI would presumably also work once this is done)
```
[root@almalinux tmp]# ps -ef | grep yum
root       34560   34508  0 01:47 pts/1    00:00:00 /usr/libexec/platform-python /usr/bin/yum -y install salt salt-minion
root       34638    2632  0 01:51 pts/1    00:00:00 grep --color=auto yum
[root@almalinux tmp]# kill 34560
[root@almalinux tmp]# kill -9 34560
```
/var/log/rhn/rhn_web_ui.log shows the following -
```
2021-05-13 01:49:22,240 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-10] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - States failed during bootstrap: pkg_|-salt-minion-package_|-salt-minion_|-installed(retcode=2): Error occurred installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-rcd34207d707545848ddec971ea08fbaf.scope
      AlmaLinux 8 - BaseOS                            0.0  B/s |   0  B     05:15
      Errors during downloading metadata for repository 'baseos':
        - Curl error (7): Couldn't connect to server for https://mirrors.almalinux.org/mirrorlist/8/baseos [Failed to connect to mirrors.almalinux.org port 443: Connection timed out]
      Error: Failed to download metadata for repo 'baseos': Cannot prepare internal mirrorlist: Curl error (7): Couldn't connect to server for https://mirrors.almalinux.org/mirrorlist/8/baseos [Failed to connect to mirrors.almalinux.org port 443: Connection timed out]
file_|-/etc/salt/minion.d/susemanager.conf_|-/etc/salt/minion.d/susemanager.conf_|-managed(retcode=2): One or more requisite failed: bootstrap.salt-minion-package
file_|-/etc/salt/minion_id_|-/etc/salt/minion_id_|-managed(retcode=2): One or more requisite failed: bootstrap.salt-minion-package
```

**Comment by ppc6446** [comment]
Update - Adding the AlmaLinux system only appeared to work using the bootstrap.sh script and WebUI once the upstream repo had been set to `enabled=0`.   The salt key has been accepted and salt commands can be run against the client system, but it is not appearing in the Uyuni system list and dnf commands on the client are failing, as it has no repos from Uyuni

**Comment by juliogonzalez** [comment]
Do I understand that the AlmaLinux client does NOT have access to the internet in your case, so you want it to use only the bootstrap repo?

If so, I guess this is a problem not just for AlmaLinux, but for all RHEL clones as well.

**Comment by ppc6446** [comment]
Yes, that is correct.  I haven't registered any other RHEL client clone recently, but it would make sense that they would all be handled the same way.  

The use case includes SUSE Manger/Uyuni system acting as the gatekeeper between the client systems and repositories on the Internet (e.g., using filters so the EPEL python packages that conflict with the Uyuni client tools aren't downloaded)

**Comment by juliogonzalez** [comment]
@meaksh I always get confused by the WebUI onboarding... but I seem to remember this was a known problem? Do we have this reported somewhere else?

**Comment by paususe** [comment]
A similar problem happens with Alibaba Cloud Linux 2

**Comment by meaksh** [comment]
IIRC the local repositories are disabled AFTER the bootstrapping is done. During the initial actions that are triggered just after the new system is registered in Uyuni.

During bootstrapping, Uyuni adds the bootstrap repo to the system but it does not disable the local repositories.

**Comment by paususe** [comment]
> IIRC the local repositories are disabled AFTER the bootstrapping is done. During the initial actions that are triggered just after the new system is registered in Uyuni.
> 
> During bootstrapping, Uyuni adds the bootstrap repo to the system but it does not disable the local repositories.

That's a problem because when those non-bootstrap repositories are inaccessible, bootstrap will fail. That happens e. g. with Alibaba 2.

**Comment by juliogonzalez** [comment]
> That's a problem because when those non-bootstrap repositories are inaccessible, bootstrap will fail. That happens e. g. with Alibaba 2.

Which is why I always say that the bootstrap repos should contain everything that's need to be able to bootstrap on the most minimal setup you can find, and together with that, the repos should be disabled before we install installing everything.

**Comment by nkrinner** [comment]
https://github.com/SUSE/spacewalk/issues/15196
