### ISSUE TITLE
Replacing SSL certificates does not work properly

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#3808]
# Additional Information

When changing the SSL certificated in accordance with [the documentation](https://www.uyuni-project.org/uyuni-docs/uyuni/administration/ssl-certs-imported.html#_replace_certificates_with_a_third_party_certificate) I figured out that the SSL key is not updated in the Apache2 configuration folder.

## Version of Uyuni Server and Proxy (if used)

```
# zypper info Uyuni-Server-release
Information for package Uyuni-Server-release:---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.04-122.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.04-122.3.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

## Details about issue

The `rhn-ssl-tool` commands worked but the following manual command was required to get it working:

```
# cp new-server.key /etc/apache2/ssl.key/server.key
```

**Comment by mcalmer** [comment]
Could it be that you did not install the newly generated RPM which was generated in step 3?
Seems we forgot to write down that you need to install it.

**Comment by stdevel** [comment]
That's a good point, thanks for pointing out. I did not install the RPM afterwards as it was not mentioned in the manual.
In my case only the key changed which explains why I had to manually copy the appropriate file.
