### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.05 - Upgrade from 2020.07

### ISSUE THREAD

**Issue by disschnarch** [uyuni-project/uyuni#3841]
# Additional Information

After upgrading and reboot  the postgres schema migration process was stuck and we had to manually intervene and change one of the SQL script.

## Version of Uyuni Server and Proxy (if used)
```
zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.05-123.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.05-123.2.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

## Details about issue
The following steps were performed.

```
zypper ref
zypper up susemanager
/usr/lib/susemanager/bin/server-migrator.sh
rpm -qa| grep postgre
# there was the following package in the output
# postgresql-server-13-lp152.3.6.1.noarch
# so we thought we had to run the following script which failed
/usr/lib/susemanager/bin/pg-migrate-12-to-13.sh
# after that we ran the migration script from 10 to 12 because we were not sure 
/usr/lib/susemanager/bin/pg-migrate-10-to-12.sh
shutdown -r now
```

So after that postgres was using 100% CPU and the processes displayed in
```
spacewalk-services status
```
were down. So we were unsure on what is happening and began troubleshooting, also because we had two unsuccessful update attempts last year already.

We looked at pg_top and on the psql cli we could see a process stuck for more than 45 minutes
```
postgres=# select *
from pg_stat_activity
where datname = 'uyuni';
```

That was the following process. Here the log file passage

[schema-from-20210601-153144-to-susemanager-schema-4.2.14.log](https://paste.ubuntu.com/p/jXpJrKTJ4z/)

To "solve" or work around this hanging process, we striped down the SQL script [05_702-debvercmp.sql.postgresql](https://paste.ubuntu.com/p/ZHmD6bNs7F/), which was able to run through and we could restart the uyuni-check-database.service which now was able to finish successfully and Uyuni afterwards was able to start all processes.

Did we do something wrong? Or is this a known problem? Or is this a new issue?

**Comment by Shirocco88** [comment]
@dincamihai : 
Did you read the release notes ?
https://www.uyuni-project.org/doc/2021.05/release-notes-uyuni-server.html#_version_2021_05

Are you shure that a direct upgrade from 2020.07 to 2021.05 is supported ?
Version Revision History
•	2021/05/24: 2021.05 release
•	2021/04/21: 2021.04 release
•	2021/03/01: 2021.02 release
•	2021/02/05: 2021.01 release
•	2020/11/26: 2020.11 release
•	2020/09/22: 2020.09 release
•	2020/07/24: 2020.07 release

**Comment by disschnarch** [comment]
@Shirocco88 

Honestly, I have no idea why we executed that 12 to 13 script. It did not do anything except throw some errors. But I guess more importantly we thought that after seeing a  postgres upgrade from a package from 12 to version 13 we had to do the major version procedure. Which was wrong. I get that now.

We have a snapshot and will try the minor upgrade tomorow morning again. I will post an update after that.

**Comment by disschnarch** [comment]
@Shirocco88 Well the minor upgrade procedure did not work either, at least in a timely manner.

I guess we ran into https://github.com/uyuni-project/uyuni/issues/3355 and with the above initially reported problem also. We will try to wait longer for the migration to finish and I will come to with the result.

We also tried to upgrade a second uyuni instance from 2020.11 to 2021.05 and this did not work either. The error we are getting is similar to https://github.com/uyuni-project/uyuni/issues/3525. Any idea in which release version that would be fixed?

Other than that we took the time and tried the sp-upgrade to SP3 on Leap and with that the upgrade to 2021.05, which also failed badly. SP3 does not seem to be supported on Leap for uyuni version 2021.05, which is strange because the compatibility table shows that, well for SLES. Why is a table for SLES in a Leap upgrade documentation anyways?

**Comment by Shirocco88** [comment]
What is the size of your postgreSQL database ?
output of "df -Th /var/lib/pgsql" gives us in indication of how much time is neccessary for the schema upgrade.

**Comment by Shirocco88** [comment]
are there errors in PostgreSQL DB logfile ?
please also post the output of command:
uyuni-srv:/# grep -i error /var/lib/pgsql/data/log/*

**Comment by Shirocco88** [comment]
@disschnarch: is the problem solved ?
can we close this issue ?

**Comment by juliogonzalez** [comment]
No feedback from @disschnarch, so closing the issue.

Needless to say, it can be reopened if needed.
