### ISSUE TITLE
Uyuni cannot detect XEN/KVM on aarch64 server

### ISSUE THREAD

**Issue by mytxyang-arm** [uyuni-project/uyuni#3845]
# Additional Information

We setup Uyuni on X86 machine, and want it to manager VM on aarch64 server, but uyuni cannot detect KVM/Xen is running on SLES 12SP2 aarch64, so we cannot create VM from Uyuni page and cannot Synchronize status with libvirtd.

## Version of Uyuni Server and Proxy (if Used)
```
# zypper info Uyuni-Server-release
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.05-123.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.05-123.2.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

# Details about issue
SLES 12SP2 aarch64 have been installed on one ARM server (Model: Altra Jade):
```
# cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```

KVM and kvm_tools is installed on this server, libvirtd is running and create one running VM:
```
# service libvirtd status
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-06-03 01:57:36 BST; 6min ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 8880 (libvirtd)
    Tasks: 17 (limit: 32768)
   CGroup: /system.slice/libvirtd.service
           └─8880 /usr/sbin/libvirtd --timeout 120

# virsh list --all
 Id   Name       State
--------------------------
 1    sle15sp2   running
```

But Uyuni cannot detect KVM is running on arm server, it report error:
"Neither KVM nor Xen is running. Ensure they are installed and the kernel modules are loaded."

Also Uyuni cannot synchronize VM information with arm server, and cannot Create VM from Uyuni page.

**Comment by mytxyang-arm** [comment]
![system_info](https://user-images.githubusercontent.com/71255730/120571131-17c0c500-c44c-11eb-9add-064890daaf9d.jpg)
![virtualization_info](https://user-images.githubusercontent.com/71255730/120571139-1b544c00-c44c-11eb-8322-2e840fdc0e99.jpg)

**Comment by mytxyang-arm** [comment]
After click "Create Guest" button, it show a blank page:
![CreateVM](https://user-images.githubusercontent.com/71255730/120571735-53a85a00-c44d-11eb-8696-dcb5c8024f9e.jpg)

**Comment by mytxyang-arm** [comment]
Update: after delete the system and bootstrap this server with install salt-minor agent, Uyuni can synchronize the VM list with SLES12SP2 aarch64, and it can start/stop VM from Uyuni GUI, but it still cannot create Guest from Uyuni.
![vitual_2](https://user-images.githubusercontent.com/71255730/120572423-7b4bf200-c44e-11eb-8df6-b1ab1e50e449.jpg)

**Comment by cbosdo** [comment]
@mytxyang-arm there are actually two issues for your problem:
* The `Neither KVM nor Xen is running. Ensure they are installed and the kernel modules are loaded.` error message comes from the fact that Salt checks for `kvm_*` modules to be loaded to detect KVM. I just discovered that those are builtin on SLES aarch64. I will create a Salt issue for that and fix it.
* The second issue is the blank page when loading the *Create Guest* dialog. Could you open the Web Developer Tools of your browser and paste here the errors that could tell me what goes wrong?

**Comment by cbosdo** [comment]
Salt upstream issue: https://github.com/saltstack/salt/issues/60419

**Comment by cbosdo** [comment]
upstream PR fixing the issue: https://github.com/saltstack/salt/pull/60420

**Comment by cbosdo** [comment]
@mytxyang-arm any feedback on the fix?

**Comment by mytxyang-arm** [comment]
@cbosdo  How to apply this fix on my environment?

**Comment by mytxyang-arm** [comment]
I have manually modified "/usr/lib/python2.7/site-packages/salt/modules/virt.py", seem it cannot work.

**Comment by cbosdo** [comment]
> I have manually modified "/usr/lib/python2.7/site-packages/salt/modules/virt.py", seem it cannot work.

You probably need to remove the corresponding pyc file and restart the salt minion after doing the change. You can also double check hat python version is used by your salt-minion? is it python 2.7 or a python 3.x? `pgrep -a salt-minion` will tell you which python is used.

**Comment by mytxyang-arm** [comment]
You mean to remove the pyc file on the salt agent? or change it on the uyuni server?
I modified this file on the uyuni server, not on the agent because i use SSH mode to bootstrapping the machine.

**Comment by mytxyang-arm** [comment]
"salt-minion" doesn't run on uyuni server and agent both.

**Comment by mytxyang-arm** [comment]
Just remove one physical system and re-add it via "salt mode", it use the "python3", i will apply the change into this system, and test if it can work.

**Comment by mytxyang-arm** [comment]
Cannot find "virt.pyc" on the target, weird. Also the change cannot work after modified "/usr/lib/python3.6/site-packages/salt/modules/virt.py".

**Comment by cbosdo** [comment]
The file to be modified is on the minion as you have guessed it. `.pyc` files for python 3.x are located in `__pycache__` folder. Here I have it in `/usr/lib/python3.6/site-packages/salt/modules/__pycache__/virt.cpython-36.pyc`.

In all cases you need to restart the salt-minion to get the change seen by Salt. I am not familiar enough with the alt-ssh case to guide you through it.

To test the fix you can also run this command on the salt minion where you applied the change:

    salt-call --local virt.get_hypervisor

It should return `kvm`.

**Comment by cbosdo** [comment]
If you want more live discussion you can also join the gitter User channel: https://www.uyuni-project.org/pages/contact.html#gitter

**Comment by mytxyang-arm** [comment]
Sure, ping you in User channel.

**Comment by cbosdo** [comment]
For the other error (blank page when creating VM), I would be interested in the output of this command on the virtualization host:
`salt-call --local virt.all_capabilities`

I wonder if it fails

**Comment by cbosdo** [comment]
@mytxyang-arm Could you also try out this change? https://github.com/saltstack/salt/pull/60492 it's pretty likely to fix the blank page problem

**Comment by cbosdo** [comment]
Opening issue #3960 for the blank page problem. I will close this issue since the other problem is fixed
