### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.05 -  zypper commands in redhat register autoinstallation code snippet

### ISSUE THREAD

**Issue by jorx-dev** [uyuni-project/uyuni#3880]
Hello,

Uyuni comes with some autoinstallation code snippets which are inserted automatically in the autoinstallation kickstart file.
In this case, while autoinstalling an AlmaLinux 8 client, this code snippet was automatically inserted:

File path:  /var/lib/cobbler/snippets/spacewalk/redhat_register_using_salt
Snippet Macro: $SNIPPET('spacewalk/redhat_register_using_salt')

At the end of this code snippet, there are "zypper" commands which are found in SUSE distributions, but not in Red Hat ones ( which use yum or dnf ).

These commands leave errors on the post installation log file.

## Version of Uyuni Server and Proxy (if used)
LANG=en_US zypper info Uyuni-Server-Release
Loading repository data...
Reading installed packages...

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.05-123.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2020.09-98.2.uyuni installed)
Source package : Uyuni-Server-release-2021.05-123.2.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue

These commands leave errors on the post installation log file.

**Comment by Shirocco88** [comment]
@jorx-dev : Could you please post the installation log file;
please also provide "redhat_register_using_salt", it is needed to check if salt-minion from uyuni is used.

**Comment by jorx-dev** [comment]
Hi,

ks-rhn-post.log:

Running in chroot, ignoring request: restart
Created symlink /etc/systemd/system/multi-user.target.wants/salt-minion.service -> /usr/lib/systemd/system/salt-minion.service.
* Disable all repos not provided by SUSE Manager Server.
/tmp/ks-script-vjbm3dk0: line 365: zypper: command not found
/tmp/ks-script-vjbm3dk0: line 366: zypper: command not found
/tmp/ks-script-vjbm3dk0: line 367: zypper: command not found
/tmp/ks-script-vjbm3dk0: line 368: zypper: command not found

redhat_register_using_salt:

# begin SUSE Manager registration
cat <<EOF >"/etc/salt/minion.d/susemanager.conf"
master: $redhat_management_server
server_id_use_crc: adler32
enable_legacy_startup_events: False
enable_fqdns_grains: False
mine_enabled: False

EOF
#set activation_keys = ""
#set management_key  = ""
#if $varExists('registration_key')
   #set activation_keys = $registration_key
#end if

#if $varExists('redhat_management_key')
   #set management_key = $redhat_management_key.split(",",1)[0]
#end if

#if not $activation_keys and $management_key
  #set keys= $redhat_management_key.split(",",1)
  #if len(keys) > 1
     #set activation_keys = $keys[1]
  #end if
#end if

#if $activation_keys or $management_key
cat <<EOF >>"/etc/salt/minion.d/susemanager.conf"
grains:
    susemanager:
EOF
#end if
#if $management_key
cat <<EOF >>"/etc/salt/minion.d/susemanager.conf"
        management_key: "$management_key"
EOF
#end if
#if $activation_keys
cat <<EOF >>"/etc/salt/minion.d/susemanager.conf"
        activation_key: "$activation_keys"
EOF
#end if

#if not $varExists('dont_register')
# if you don't want to register, set the 'dont_register' variable

systemctl restart salt-minion
systemctl enable salt-minion
#end if

#if not $varExists('dont_disable_automatic_onlineupdate')
YAOU_SYSCFGFILE="/etc/sysconfig/automatic_online_update"
if [ -f "$YAOU_SYSCFGFILE" ]; then
  echo "* Disable YAST automatic online update."
  sed -i 's/^ *AOU_ENABLE_CRONJOB.*/AOU_ENABLE_CRONJOB="false"/' "$YAOU_SYSCFGFILE"
  for D in /etc/cron.*; do
    test -L $D/opensuse.org-online_update && rm $D/opensuse.org-online_update
  done
fi
#end if

#if not $varExists('dont_disable_local_repos')
echo "* Disable all repos not provided by SUSE Manager Server."
zypper ms -d --all
zypper ms -e --medium-type plugin
zypper mr -d --all
zypper mr -e --medium-type plugin
#end if

# end SUSE Manager registration
""

**Comment by Shirocco88** [comment]
>> Uyuni comes with some autoinstallation code snippets
we need to know which rpm package contains the file "redhat_register_using_salt",
please poste the output of the following command:
"rpm -qf /var/lib/cobbler/snippets/spacewalk/redhat_register_using_salt"

**Comment by Shirocco88** [comment]
as a first fix, you can change Lines 365 - 368 of file "/var/lib/cobbler/snippets/spacewalk/redhat_register_using_salt"

ZYPPER_BIN="/usr/bin/zypper"
if [ -f "$ZYPPER_BIN" ]; then
   zypper ms -d --all
   zypper ms -e --medium-type plugin
   zypper mr -d --all
   zypper mr -e --medium-type plugin
fi

**Comment by jorx-dev** [comment]
Hello,

# rpm -qf /var/lib/cobbler/snippets/spacewalk/redhat_register_using_salt 
spacewalk-java-4.2.19-1.1.uyuni.noarch

In my case, I've solved it by setting dont_disable_local_repos=1 via Uyuni's webUI at Systems -> Profiles -> almalinux8-x86_64 -> Autoinstallation details -> Variables

Anyway, I'm not sure whether this code has to be commented, deleted or changed to some dnf/yum equivalent

Thank you,

> as a first fix, you can change Lines 365 - 368 of file "/var/lib/cobbler/snippets/spacewalk/redhat_register_using_salt"
> 
> ZYPPER_BIN="/usr/bin/zypper"
> if [ -f "$ZYPPER_BIN" ]; then
> zypper ms -d --all
> zypper ms -e --medium-type plugin
> zypper mr -d --all
> zypper mr -e --medium-type plugin
> fi
> 
> found script:
> https://github.com/uyuni-project/uyuni/blob/master/java/conf/cobbler/snippets/redhat_register_using_salt
