### ISSUE TITLE
UI shows already installed patches - Uyuni 2021.05

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#3900]
# Additional Information

For one managed system (*SLES4SAP 15 SP2*) already installed patches are displayed in the Web UI:

![grafik](https://user-images.githubusercontent.com/5862725/122740099-efc2c580-d283-11eb-8429-0af6bfa5396d.png)

Installing them results in an error message saying that the appropriate patch/package is already installed.

`zypper` on the affected system confirms this:

```
# zypper in gpm
Loading repository data...
Reading installed packages...
'gpm' is already installed.
No update candidate for 'gpm-1.20.7-7.3.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.
```

## Version of Uyuni Server and Proxy (if used)
```# zypper info Uyuni-Server-release
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.05-123.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.04-122.3.uyuni installed)
Source package : Uyuni-Server-release-2021.05-123.2.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

## Details about issue

I ran a package profile-sync from the Web UI in order to verify that Uyuni has the lastest package information from the system. 

The task succeeded and also Taskomatic including all tasks and bunches is working fine. I checked the Tomcat log and couldn't find any issues. Also, Uyuni was restarted, all service are running fine according to `spacewalk-service status`.

Please let me know if you need full log files, etc.

Is there a way to fix this? Thanks a lot in advance!

**Comment by Shirocco88** [comment]
@stdevel : could you please verify, if the client is using the correct repo
minion:/# zypper lr

**Comment by Shirocco88** [comment]
@stdevel: please also do a "package list refresh" for this client
and then check counters for missing "patches" and "package upgrade"

**Comment by stdevel** [comment]
I attached the requested commands to the post: [uyuni_client_infos.txt](https://github.com/uyuni-project/uyuni/files/6816150/uyuni_client_infos.txt)

YaST (`you`) is installed and can be executed from the command line.

The client is registered to an Uyuni server. Interestingly, we upgraded Uyuni today and the issue was gone:

```shell
# rpm -qi Uyuni-Server-release
Name        : Uyuni-Server-release
Version     : 2021.06
Release     : 132.3.uyuni1
Architecture: x86_64
Install Date: Wed Jul 14 11:11:20 2021
Group       : System/Fhs
Size        : 1455
License     : GPL-2.0-or-later
Signature   : RSA/SHA256, Wed Jun 23 18:32:03 2021, Key ID 972e5d6c0d20833e
Source RPM  : Uyuni-Server-release-2021.06-132.3.uyuni1.src.rpm
Build Date  : Wed Jun 23 18:31:57 2021
Build Host  : old-atreju5
Relocations : (not relocatable)
Vendor      : obs://build.opensuse.org/systemsmanagement:Uyuni
Summary     : Uyuni Server
Description :
Uyuni lets you efficiently manage physical, virtual,
and cloud-based Linux systems. It provides automated and cost-effective
configuration and software management, asset management, and system
provisioning.
Distribution: systemsmanagement:Uyuni:Master / openSUSE_Leap_15.3

# cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Comment by Shirocco88** [comment]
> Interestingly, we upgraded Uyuni today and the issue was gone

can we close this issue _

**Comment by stdevel** [comment]
Hi @Shirocco88,
sorry for the late answer - I've been on vacation.

Yes, you can close this issue. Thanks a lot for the help.
