### ISSUE TITLE
salt-minion issue with python3.8 decorators

### ISSUE THREAD

**Issue by jpgrazi** [uyuni-project/uyuni#3902]
Description of problem:
Salt-minion not able to take process commands from salt-master.

Version-Release number of selected component (if applicable):
salt-minion-3003-1.el7.noarch and salt-3003-1.el7.noarch
python-decorator-3.4.0-3.el7.noarch

How reproduce:
Master uyuni server 2021.05 on OpneSuSe Leap 15.2 with salt-master-3000-lp152.3.33.1.x86_64

All client machine Centos CentOS Linux release 7.9.2009 (Core) exhibit this issue.

Steps to Reproduce:
	
    Python 2.7.5 and Python 3.6.8
    salt-minion salt-minion-3003-1 on client. installed manually from https://repo.saltproject.io/#rhel
	Bootstrap Client Server using curl (pull bootstrap script from uyuni master)
	
Actual Result:
2021-06-21 10:53:53,712 [salt.state       :321 ][ERROR   ][9058] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
TypeError: _run() missing 1 required positional argument: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2172, in call
    *cdata["args"], **cdata["kwargs"]
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2316, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 363, in _call_function
    self._function, self._orig_f_name
TypeError: replace() argument 1 must be str, not function

See reported bug in saltstacjk project GitHub:  https://github.com/saltstack/salt/issues/58895

File /var/cache/salt/minion/extmods/states/mgrcompat.py is from uyuni project.

Expected results:
No errors and salt commands complete sucessfully.
[minion-log.txt](https://github.com/uyuni-project/uyuni/files/6689405/minion-log.txt)

**Comment by Shirocco88** [comment]
@jpgrazi 
Why are there two versions of python installed 2.7 and 3.6;
do you really need both versions installed in parallel;

Could you please try to bootstrap uyuni-version of salt-minion on an fresh installed system (without muliple pythen version installed); there is no need to use salt-minion packages from saltstack;

**Comment by jpgrazi** [comment]
Thanks Shirocco88 for your answer/comments. This is a Centos7 server. Python 2.7 is in the core of many system tools like yum for example. If python 2.7 is removed (if possible) many OS tools will be broken. So the option is to install python 3.6 in parallel. 
I made the bootstrap process using uyuni's bootstrap script using curl to pull the salt-minion from uyuni server and it pulls also the python 3.6. After the minion was installed, the server wasn't registered to the uyuni server. I use curl to pull bootstrap because the root user cannot ssh to the server. So I su to root and pull the bootstrap using curl from the uyuni master server.
By looking for solutions, I decided to manually install the salt minion from saltstack and the server got registered... but Now I have the errors that I explained in my previous post. This error has the effect to don't let the uyuni server to update the packages list required to be installed from the software channels to the server.

**Comment by agraul** [comment]
On CentOS7 you should have `python2-salt` from Uyuni and it should run with the system Python 2.7. Having Python3.6  present on the client shouldn't be a problem, we also have Python2.7 + Python 3.4 on SLE 12 and don't see problems due to this.

I don't know why the bootstrapping failed, but you need to use Uyuni's Salt package. It's the only one we can ensure supports all Salt features needed by Uyuni. We are upstreaming all of our work, but it can take some time until features we need are included upstream.

Can you remove the upstream salt-minion, everything under `/etc/salt/`, `/var/cache/salt` and `/run/salt/` and try to bootstrap again? The script *should* work.

**Comment by jpgrazi** [comment]
Thanks Agraul. 
I ran the bootstrap script using curl to pull the script's contents to the client server, after removing what you suggested. 
I got conflicting errors with some python packages: python-zmq, zeromq, python2-crypto and python-mskpack. So, I removed those packages using yum remove and re-ran the script (using curl again). No issues this time. So the sever got registered to the uyuni server and the packages list were updated. 
As I understand, those packages were re-installed in a different version, (for uyuni to work), and the issue was python versioning related with the packages uyuni needs vs the packages that were installed. 
Hope this won't break any other thing related with python's scripts in the server. 
Thanks for your answer and help.-

B/R
Jean Pierre

**Comment by agraul** [comment]
It's possible that those (python-zmq, zeromq, python2-crypto and python-msgpack) were pulled in by the upstream Salt package. Generally everything should be fine if your package manager didn't complain. Other scripts on your system that come from packages normally have a version dependency that would stop a particular version from being installed.

Great that it works again, I'm closing the issue. If the symptoms come back, feel free to re-open this issue.

**Comment by corosou** [comment]
Hi, I have some insight into this issue for posterity:

Setting up a brand new Uyuni server I decided to add the SaltStack repo to Uyuni.

What this does is create a bootstrap which puts:

salt-3003.1 in - "/srv/www/htdocs/pub/repositories/oracle/8/bootstrap/noarch"

salt-3002.2 in - "/srv/www/htdocs/pub/repositories/oracle/8/bootstrap/x86_x64"

And so salt3003.1 gets installed the next time you use the bootstrap script and you get this error.

The fix for me:

1) Remove SaltStack repo from Uyuni
2) Move the old bootstrap directories out of the way (/srv/www/htdocs/pub/repositories/<oracle|centos|etc>)
2) Recreate your bootstrap repo directories (mgr-create-bootstrap-repo as root)
