### ISSUE TITLE
Fatal error aplying errata - Uyuni 2021.05-2021.08

### ISSUE THREAD

**Issue by kluchoslaw** [uyuni-project/uyuni#3904]
Upgrade from 2021.05 to 2021.06 and to 2021.08 not helped in this problem:
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.08-139.2.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.08-139.2.uyuni1.src

## Details about issue
Errata patching only 1 of 2 ways is working:
1. Not working: click System -> Overview -> click any server -> "Software" -> "Patches" -> mark any patch - Apply Patches -> Confirm  and after that enter in Events -> History is red status with "Fatal error in Python code occurred [[6]] (code -1)"
and on email comes TRACEBACK with info 
Exception type <class 'spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError'>
Exception while handling function errata.getErrataInfo Request object information
[traceback.txt](https://github.com/uyuni-project/uyuni/files/6693187/traceback.txt)

2. Working way: 
From  Patches->Patch List -> chosen patch which failed earlier -> Affected systems ->mark the same server as in point 1 - Apply Patches -> Confirm and it ends with "Update Succeeded (code 0)"

**Comment by Shirocco88** [comment]
what is the os-version of the minion system to be patched ?
CentOS7 ???

**Comment by kluchoslaw** [comment]
> what is the os-version of the minion system to be patched ?
> CentOS7 ???
In this example Yes, you can check this in attached traceback.txt
OS: centos-release
Release: 7
CPU Arch: x86_64

> 
> How did you apply the erratas ?
The way of applying erratas is described in 1st post.

**Comment by mcalmer** [comment]
On the client, which version of  `yum-rhn-plugin` is installed?
It seems this is handling incomming data wrong.

yum-rhn-plugin-4.2.7 should handle it correctly. 

@phibid @symbatkarzhassov  please also check your clients.

**Comment by kluchoslaw** [comment]
During this time I've upgraded Uyuni, also clients migrated from traditional to salt clients and problem is gone. Unfortunately dont know what helped.
