### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.06

### ISSUE THREAD

**Issue by RipperSK** [uyuni-project/uyuni#3907]
# Additional Information

When installing uyuni on openSuse 15.3 following the official install guide:
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-uyuni.html

```
uyuni:~ # zypper in patterns-uyuni_server
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides product(openSUSE) >= 15.2 needed by product:Uyuni-Server-2021.05-0.x86_64
 Solution 1: do not install patterns-uyuni_server-2021.05-1.1.uyuni.x86_64
 Solution 2: break Uyuni-Server-release-2021.05-123.2.uyuni.x86_64 by ignoring some of its dependencies
```

and one more issue during install:

```
Problem: nothing provides salt = 3000-30.1 needed by python2-salt-3000-30.1.x86_64
 Solution 1: do not install patterns-uyuni_server-2021.05-1.1.uyuni.x86_64
 Solution 2: break python2-salt-3000-30.1.x86_64 by ignoring some of its dependencies
```

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

```
uyuni:~ # zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.05-123.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.05-123.2.uyuni.src
Summary        : Uyuni Server
```

## Details about issue
all that is needed to reproduce the issue:

start with fresh openSUSE 15.3 and try to follow the install guide.
it fails on this step:

```
Install the pattern for the Uyuni Server as root:

zypper in patterns-uyuni_server
```

**Comment by juliogonzalez** [comment]
Uyuni 2021.06 is not released yet.

As you can see you are installing Uyuni 2021.05, which works only on top of openSUSE Leap 15.2

> When installing uyuni on openSuse 15.3 following the official install guide:
> https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-uyuni.html

The guide specifies 15.2: https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-install-requirements.html

**Comment by RipperSK** [comment]
OK my bad - I think I'll close this bug report then.

**Comment by juliogonzalez** [comment]
> OK my bad - I think I'll close this bug report then.

No worries. Thanks for closing the issue :-)

Uyuni 2021.06 (requires Leap 15.3 as base OS) will be released hopefully out this week (maybe even today).
