### ISSUE TITLE
CentOS6/7 gets detected as RHEL Expanded Support 6/7

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#391]
![screenshot_20181210_151258](https://user-images.githubusercontent.com/4226070/49737863-2c161380-fc8e-11e8-902d-feebfc71f5d9.png)
![screenshot_20181210_161639](https://user-images.githubusercontent.com/4226070/49741606-13f6c200-fc97-11e8-8eed-84df02ccb2e8.png)

How to reproduce:

1. Create the CentOS6/7 channels with `spacewalk-common-channels`
2. Create bootstrap repositories for CentOS6/7.
3. Create bootstrap scripts for CentOS6/7 (in my case it happened with traditional).
4. Bootstrap CentOS6/7 clients.
5. Look at the products installed.

**Comment by mcalmer** [comment]
@brejoc - I think this is an issue in the java code. Not in salt. But we may need to double check.

**Comment by brejoc** [comment]
@mcalmer Might be. But I might also have broken this with a change in `grains.py`. Lets see. :wink:

**Comment by brejoc** [comment]
I've re-checked this with a generic Centos7 installation and a salt from `systemsmanagement:saltstack:products`. Output from salt looks good to me. I don't think this is coming from salt, so I'm unassigning myself.
```
[root@localhost]# salt-call --local grains.get os
local:
    CentOS
[root@localhost]# salt-call --local grains.get os_family
local:
    RedHat
```

**Comment by srbarrios** [comment]
It might have some relation with https://bugzilla.suse.com/show_bug.cgi?id=1173584 (Installed products: unknown on CentOS6 client)

**Comment by srbarrios** [comment]
This is not happening anymore:
![image](https://user-images.githubusercontent.com/2827771/97579015-da95df80-19f1-11eb-8278-03f6974eb571.png)
