### ISSUE TITLE
Minor Typos, and issue with google's search of Uyuni's documentation

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#3913]
# Some minor typos

I spent a long time using Uyuni's documentation today (struggling with the update) and have recorded some minor typos and problems.

1. 
### Typo in new repo file:
15 | systemsmanagement_Uyuni_Stable | Uyuni **Stabe** release (openSUSE_Leap_15.3)            

2. 
### Typo in /usr/lib/susemanager/bin/server-migrator.sh
Retrieving repository 'Update repository **wiht** updates from SUSE Linux Enterprise 15' metadata  

3.
### Unexpanded macro in documentation:
https://www.uyuni-project.org/uyuni-docs/en/uyuni/upgrade/server-major-upgrade-uyuni.html
". After the migration is complete, manually reboot the **{productname}** Server:"

4. 
### Observation:
The URL layout for Uyuni documentation appears to have changed, meaning Google's links for Uyuni topics are now returning 404  (Although the documentation itself is complete)

Eg: Search for "https://www.uyuni-project.org/uyuni-docs/uyuni/upgrade/server-minor-upgrade-uyuni.html" which gives you the  404 from https://www.uyuni-project.org/uyuni-docs/uyuni/upgrade/server-minor-upgrade-uyuni.html

This might be a matter of time to let google update its caches, or the domain owner can force a refresh of scanning, or some 404 redirectors added with some clever regexp.

**Comment by jcayouette** [comment]
@digdilem Thanks for the report. The 404's should have been resolved with the latest update. We had a few issues with the last update due to new translation code. Ill add the card to our board for fixing the typos.

**Comment by digdilem** [comment]
Smashing.  Feel free to close when you wish.
