### ISSUE TITLE
Repo sync [Errno 14] HTTP Error 404 - Not Found. / Linking packages to the channel failure. Uyuni release 2021.06

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#3967]
Uyuni release 2021.06
When trying to sync a repo it fails to get a lot of .rpm packages. Packages can be downloaded with wget.
``` ERROR: Download failed: http://download.opensuse.org/update/leap/15.3/sle/sle-sp2/noarch/zypper-needs-restarting-1.14.45-10.1.noarch.rpm - [Errno 14] HTTP Error 404 - Not Found.```
`4032/4032 : zypper-needs-restarting-1.14.45-10.1.noarch.rpm (failed)`

At the end of the sync linking packages to the channel fails with the following text.
```021/07/08 14:48:13 +03:00   Linking packages to the channel.
2021/07/08 14:48:16 +03:00 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
2021/07/08 14:48:16 +03:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 596, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1139, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 778, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2506, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'bind-chrootenv', 'epoch': None, 'version': '9.16.6', 'release': '22.7.1', 'arch': 'i586', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {198: 'sle-update-x86_64'}, 'checksum_list': None, 'checksum': 'e4c025858bafe3ba93bb2f0a82633ef520b30d054722357a48b9333c823abaf6', 'checksum_type': 'sha256', 'checksums': {'sha256': 'e4c025858bafe3ba93bb2f0a82633ef520b30d054722357a48b9333c823abaf6'}, 'name_id': 40424, 'evr_id': 182631, 'package_arch_id': 103, 'nevra_id': 276410, 'checksum_id': 10841305}] in table rhnPackage

**Comment by Shirocco88** [comment]
@j-kihet 
could you please provide the logfile part of "/var/log/rhn/rhn_web_ui.log", "/var/log/rhn/rhn_web_ui.log", "/var/lib/pgsql/data/log/postgresql-2021-07-08_000000.log" for the timeframe of reposync error.

**Comment by j-kihet** [comment]
Thank you for responding.
There is nothing in /var/log/rhn/rhn_web_ui.log from 14:01:48 to 15:01:14 .
In postgresql-2021-07-08_000000.log nothing from 13:29:42 to 21:33:22
/var/log/rhn/rhn_web_ui.log is mentioned twice , is there a third log file to check?

**Comment by Shirocco88** [comment]
Could you please test if download is working:
uyuni-srv:~ # wget http://download.opensuse.org/update/leap/15.3/sle/sle-sp2/noarch/zypper-needs-restarting-1.14.45-10.1.noarch.rpm

**Comment by j-kihet** [comment]
wget works.
```
Saving to: 'zypper-needs-restarting-1.14.45-10.1.noarch.rpm'

zypper-needs-restarting-1.14.45-10.1.noarch.rpm 

100%[====================================================================================================>]  46.79K  --.-KB/s    in 0.007s
2021-07-12 09:46:11 (6.85 MB/s) - 'zypper-needs-restarting-1.14.45-10.1.noarch.rpm' saved [47912/47912] 
```

This is the sync command that shows up in the log:
`2021/07/12 09:51:33 +03:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'sle-update-x86_64', '--type', 'yum', '--non-interactive']`

**Comment by srinidhibs** [comment]
Subscribing to this defect for any future updates!

I also had the same issue:

```sh
# zgrep -nic 'incompletepackage' /var/log/rhn/reposync/* | grep -v -e "0$"
/var/log/rhn/reposync/opensuse-leap-15.2-updates.log:3
/var/log/rhn/reposync/opensuse_leap15_2-x86_64-updates.log:4
/var/log/rhn/reposync/sle-module-web-scripting12-updates-x86_64-sp5.log:1
/var/log/rhn/reposync/sles12-sp3-updates-x86_64.log:1
```
**had** - because, as mentioned in #3928, I had to re-initialize my Uyuni server due to multiple such errors.

**Comment by srinidhibs** [comment]
@j-kihet can you try running the following command and see if it solves the problem?

`/usr/bin/spacewalk-repo-sync --verbose --type yum --channel sle-update-x86_64 -n -f -i "zypper-needs-restarting*"`

This should force downloading binaries of a single package.

**Comment by j-kihet** [comment]
The error has gone away after a scheduled sync, I think it has something to do with the mirrors. 
The default suse repo link redirects to a mirror witch did not have the files.
Repo is now syncing.

**Comment by Shirocco88** [comment]
Hint: there is another issue with Channel "sle-update":
https://github.com/uyuni-project/uyuni/issues/3936#issuecomment-880615023
https://github.com/uyuni-project/uyuni/issues/3936#issuecomment-880625813
