### ISSUE TITLE
Uyuni Question - Uyuni 2021.06 - cant enable scheduling

### ISSUE THREAD

**Issue by greinick** [uyuni-project/uyuni#4003]
Hi,

Recently I installed my first Uyuni server and shortly after the version 2021.06 was released. I followed teh upgrade documenattion and the server is up and running.

I also have my first client registered and he receives updates. But I still have to schedule the repo sync by hand; I can't enable it on a daily or weekly base under Software => Manage => Channels => Repository … => Sync.

I can click the radio button and also can choose the differnt time/day options, but whenever I click on „Schedule“ the page is reset to „Disable Schedule“.

Searching the net did not help me yet, so I hope to get some helpfull hints and feedback.

	Thanks and Regards . Götz

**Comment by juliogonzalez** [comment]
Adding the bug label, this looks to me like a bug.

**Comment by greinick** [comment]
Dear Julio, thanks for looking into that. I checked today and *magically* it works .... I can choose a time slot and hit the Schedule button and the settings are saved.

I have no clue what happened or what triggered.

I'll keep you  posted if I have any further symptoms regarding Schedules.

**Comment by mcalmer** [comment]
As it seems to work now, I close this.
