### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.06: Scheduled actions run after hours

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#4028]
I have noticed that the tasks scheduled to be executed asap are actually not:

Example:

```
Action Details
Action Type: 	Package Install
Scheduler: 	phibid
Earliest execution: 	7/22/21 2:45:00 PM GMT
Notes: 	1 system failed to complete this action. 
```

Was in fact executed 1h30 after:

```
System	Failed	Message
server01 	7/22/21 4:20:19 PM GMT ....
```

This is not a unique case, same behaviour for all the scheduled tasks.

There is no lack of resources at all on the server, I can see taskomatic not especially stressed, so not sure why this delay.
Something configurable perhaps ?

**Comment by phibid** [comment]
Another example:

```
 Details:
This action will be executed after 7/22/21 5:31:00 PM GMT
This action's status is: Failed.
The client picked up this action on 7/22/21 8:26:02 PM GMT
The client completed this action on 7/22/21 8:26:18 PM GMT
Client execution returned 
```

3h of delay.

**Comment by phibid** [comment]
I have noticed that `salt-minion` is not installed on the Uyuni proxies, on which I have this delay issue.
I wonder how come I do not have `salt-minion` installed on the proxies ....

If you confirm that salt-minion should be installed on the proxies, then I guess that it could explain the delay to execute the tasks.

**Comment by juliogonzalez** [comment]
Are all actions failing, as the one you pasted here? Somehow I understood they were running, but just taking hours to run.

Having the Proxies onboarded as traditional should not cause there, but traditional proxies are not supported for a long time already, so I'd suggest moving them to salt: https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation/proxy-setup.html#replace-susemgrproxy

**Comment by juliogonzalez** [comment]
Still I recommend you wait a little so @cbbayburt or his squad can have a quick look.

**Comment by phibid** [comment]
Yes indeed, all the Uyuni proxies we have use traditional clients.

I have re-registered 1 with salt-minion, and much better indeed, the tasks are executed almost immediately. Is there a way not to loose the clients registered against the Uyuni proxy while during such a migration, from traditional to Salt client ?

**Comment by juliogonzalez** [comment]
Yes, you need to follow the procedure I linked above. It reads:

>  Create a reactivation key for this system and then register the new proxy using the reactivation key. If you do not use the reactivation key, you will need to re-register all the clients against the new proxy.

**Comment by phibid** [comment]
Aaaah yes, ok same procedure as the major upgrade. Will try it next week, thanks.

**Comment by phibid** [comment]
So I am migrating all our Uyuni proxies from Traditional client to salt-minion clients, and the good news is that this is really smooth.

I only have to bootstrap again the Uyuni proxy from the GUI, with same name, and it remains there in the system list, this time as Salt system-type, without even loosing its registers clients

**Comment by juliogonzalez** [comment]
So it seems the problem was using a proxy registered as a traditional client?

If so, I think we can close the issue, as in fact I think proxies as traditional clients were only supported on the pre XXXX.YY versions.s

**Comment by phibid** [comment]
Yes, indeed, seems that traditional clients are not welcome anymore in the last release of Uyuni :-)

Closing ticket.
