### ISSUE TITLE
Uyuni 2021.06 - don't see more than 5 systems, having 7 salt keys, some are in pending state

### ISSUE THREAD

**Issue by greinick** [uyuni-project/uyuni#4084]
Hi,

I added 7 centos 7.9 servers to my uyuni installation, all in the same way.

At the Systems overview I just see 5 - random picket - systems from the 7, at the slat keys page i do see the seven servers with a pending state and no clickable host name in the first column.

Any hints or explanations why looks like that?

**Comment by Shirocco88** [comment]
could you please check, if all 7 systems have unique /etc/machine-id files;
or are there 2 cloned systems ?

**Comment by greinick** [comment]
Hi, some VMs have uniq machine-ids, but 3 Systems have the same. 🧐

They are all citrix xen systems but "older ones" so I don't know if they where clones ore based on the sam template  ... 

Would it be possible to just regenerate the machine-id ?

**Comment by Shirocco88** [comment]
I use this procedure for SLES12, SLES15, Ubuntu-18.04, Debian-10 systems:

If your machines have the same machine IDs then delete the file on each client and recreate it:
# rm /etc/machine-id
# rm /var/lib/dbus/machine-id
# dbus-uuidgen --ensure
# systemd-machine-id-setup

**Comment by greinick** [comment]
Thanks, lesson learned :)
