### ISSUE TITLE
Request: Please add Uyuni-Client-Tools (salt-minion) for Debian-11 (Bullseye)

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni#4108]
On 07/15/2021 Debian 11 (Bullseye) was "freezed", this means official release date is comming soon;
see:
https://wiki.debian.org/DebianBullseye
https://lists.debian.org/debian-devel-announce/2021/07/msg00003.html

Could you please add Uyuni-Client-Tools (salt-minion) for Debian-11 (Bullseye):
https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/
and https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/

* [x]  Client Tools repository at OBS
* [x]  venv-salt-minion package at OBS
* [x]  Add the client tools repo at OBS to spacewalk-common-channels.ini
* [ ]  Add the venv-salt-minion at OBS to spacewalk-common-channels.ini

References:
salt-minion for Debian10
https://build.opensuse.org/project/show/systemsmanagement:Uyuni:Master:Debian10-Uyuni-Client-Tools
venv-salt-minion for Debian-10:
https://build.opensuse.org/package/show/systemsmanagement:saltstack:bundle:Debian-10/venv-salt-minion

Update:
Debian 11 was released on 2021-08-14. It is the current stable distribution. 
see: https://wiki.debian.org/DebianBullseye

**Comment by Shirocco88** [comment]
checked OBS:
https://build.opensuse.org/package/show/systemsmanagement:saltstack:products:debian/salt

==> there is a unresolved dependancy :
![image](https://user-images.githubusercontent.com/69859238/128701620-a765d5ea-6db3-4008-a0a9-118876861f96.png)

how can this fixed ?

**Comment by Shirocco88** [comment]
@juliogonzalez :
is there anything to do, to help to provide salt-minion for Debian-11 ?

**Comment by Shirocco88** [comment]
Hint:
Directory https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/Debian11-Uyuni-Client-Tools/ is now available

**Comment by Shirocco88** [comment]
Hint:
Directory https://build.opensuse.org/package/show/systemsmanagement:saltstack:bundle:Debian-11/venv-salt-minion is now available

**Comment by Shirocco88** [comment]
Hint:
Directory https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Debian11-Uyuni-Client-Tools/ is still missing

**Comment by Shirocco88** [comment]
Link to PR https://github.com/uyuni-project/uyuni/pull/4122 "Basic-Support-for-Debian-11-as-clients"

**Comment by juliogonzalez** [comment]
This one is done. The Master client tools are created, and Stable will have the packages when we release the support for Debian 11.

But for now, both will have the regular salt and not the bundle (doesn't mean users can't use the bundle for testing)
