### ISSUE TITLE
Request: Basic Support for Debian 11 as clients

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni#4109]
On 07/15/2021 Debian 11 (Bullseye) was "freezed", this means official release date is comming soon;
see:
https://wiki.debian.org/DebianBullseye
https://lists.debian.org/debian-devel-announce/2021/07/msg00003.html

Please add Support for Debian-11 (Bullseye) as uyuni client

Reference PR https://github.com/uyuni-project/uyuni/pull/1917

**Comment by Shirocco88** [comment]
Idea: 
files to be checked:
•	susemanager-utils/susemanager-sls/salt/bootstrap/init.sls 
•	susemanager-utils/susemanager-sls/salt/packages/redhatproductinfo.sls
•	link at susemanager-utils/susemanager-sls/salt/certs/ to a Debian11.sls ( (Webui bootstrapping)
•	spacewalk/certs-tools/rhn_bootstrap_strings.py 	(bootstrap script generator)
•	susemanager/src/mgr_bootstrap_data.py         	(bootstrap repo generation)
•	utils/spacewalk-common-channels.ini		(common channels)

**Comment by Shirocco88** [comment]
root@4f60311a69e2:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@4f60311a69e2:~#

**Comment by juliogonzalez** [comment]
@Shirocco88 since we have very limited bandwidth now, can you help us with the initial PR, at least for the non-java code? You already know most of the files that could require changes. In fact I am quite sure some of them such as `susemanager-utils/susemanager-sls/salt/bootstrap/init.sls` and `• spacewalk/certs-tools/rhn_bootstrap_strings.py` should not require changes as they use variables for the version.

You can include the Java part, as the changes should be minimal.

Needless to say we'll provide help and guidance, and will eventually take over the PR if needed, as it was the case for Rocky Linux.

**Comment by Shirocco88** [comment]
@juliogonzalez : Thanks; I will do it;
due to holidays I can provide the PR at the end of month.

**Comment by Shirocco88** [comment]
@juliogonzalez :
Draft PR  Basic-Support-for-Debian-11-as-clients #4122 done:

We have to wait for availability of "Uyuni-Client-Tools (salt-minion) for Debian-11 (Bullseye)", see #4108
then the definition file for bootstrap repo generation susemanager/src/mgr_bootstrap_data.py could be addapted for Debian-11 (Bullseye)

**Comment by Shirocco88** [comment]
Test venv-salt-minion im debin11-container:

root@debian11-container:/# pstree
entrypoint.sh---sleep

root@debian11-container:/# /usr/lib/venv-salt-minion/usr/bin/salt-minion -d

root@debian11-container:/# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

root@debian11-container:/#  lsb_release -d
Description:    Debian GNU/Linux 11 (bullseye)

root@debian11-container:/# cat /etc/debian_version
11.0

root@debian11-container:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


root@debian11-container:/# /usr/lib/venv-salt-minion/bin/salt-call --versions-report
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.13 (default, Mar 24 2021, 13:30:48) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: debian 11 bullseye
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-17-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye

root@debian11-container:/# /usr/lib/venv-salt-minion/bin/salt-call --local grains.items
local:
    ----------
    __suse_reserved_pkg_all_versions_support:
        True
    __suse_reserved_pkg_patches_support:
        True
    __suse_reserved_saltutil_states_support:
        True
    biosreleasedate:
        12/12/2018
    biosversion:
        6.00
    cpu_flags:
        - fpu
        - vme
        - de
        - pse
        - tsc
        - msr
        - pae
        - mce
        - cx8
        - apic
        - sep
        - mtrr
        - pge
        - mca
        - cmov
        - pat
        - pse36
        - clflush
        - mmx
        - fxsr
        - sse
        - sse2
        - ss
        - ht
        - syscall
        - nx
        - pdpe1gb
        - rdtscp
        - lm
        - constant_tsc
        - arch_perfmon
        - nopl
        - xtopology
        - tsc_reliable
        - nonstop_tsc
        - cpuid
        - pni
        - pclmulqdq
        - ssse3
        - fma
        - cx16
        - pcid
        - sse4_1
        - sse4_2
        - x2apic
        - movbe
        - popcnt
        - tsc_deadline_timer
        - aes
        - xsave
        - avx
        - f16c
        - rdrand
        - hypervisor
        - lahf_lm
        - abm
        - cpuid_fault
        - invpcid_single
        - pti
        - ssbd
        - ibrs
        - ibpb
        - stibp
        - fsgsbase
        - tsc_adjust
        - bmi1
        - avx2
        - smep
        - bmi2
        - invpcid
        - xsaveopt
        - arat
        - md_clear
        - flush_l1d
        - arch_capabilities
    cpu_model:
        Intel(R) Xeon(R) Gold 6246 CPU @ 3.30GHz
    cpuarch:
        x86_64
    cpusockets:
        1
    cwd:
        /
    disks:
        - sdf
        - sdd
        - sdb
        - sr0
        - fd0
        - sde
        - sdc
        - sda
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 127.0.0.11
        ip6_nameservers:
        nameservers:
            - 127.0.0.11
        options:
            - ndots:0
        search:
            - intra.ifm
        sortlist:
    domain:
    efi:
        False
    efi-secure-boot:
        False
    fqdn:
        debian11-container
    fqdn_ip4:
        - 192.168.4.2
        - 192.168.4.2
        - 192.168.4.2
    fqdn_ip6:
    fqdns:
    gid:
        0
    gpus:
    groupname:
        root
    host:
        debian11-container
    hwaddr_interfaces:
        ----------
        eth0:
            02:42:c0:a8:04:02
        lo:
            00:00:00:00:00:00
    id:
        dettlx613.intra.ifm
    init:
        unknown
    ip4_gw:
        192.168.4.1
    ip4_interfaces:
        ----------
        eth0:
            - 192.168.4.2
        lo:
            - 127.0.0.1
    ip6_gw:
        False
    ip6_interfaces:
        ----------
        eth0:
        lo:
    ip_gw:
        True
    ip_interfaces:
        ----------
        eth0:
            - 192.168.4.2
        lo:
            - 127.0.0.1
    ipv4:
        - 127.0.0.1
        - 192.168.4.2
    ipv6:
    kernel:
        Linux
    kernelparams:
        |_
          - BOOT_IMAGE
          - /boot/vmlinuz-4.19.0-17-amd64
        |_
          - root
          - None
        |_
          - ro
          - None
        |_
          - vsyscall
          - emulate
        |_
          - quiet
          - None
    kernelrelease:
        4.19.0-17-amd64
    kernelversion:
        #1 SMP Debian 4.19.194-2 (2021-06-21)
    locale_info:
        ----------
        defaultencoding:
            UTF-8
        defaultlanguage:
            en_US
        detectedencoding:
            UTF-8
        timezone:
            unknown
    localhost:
        debian11-container
    lsb_distrib_codename:
        bullseye
    lsb_distrib_id:
        Debian GNU/Linux
    lsb_distrib_release:
        11
    machine_id:
        e7e98a88fab99156c099b5655ff2c1c8
    manufacturer:
        VMware, Inc.
    master:
        salt-master.intra.ifm
    mem_total:
        7955
    nodename:
        debian11-container
    num_cpus:
        4
    num_gpus:
        0
    os:
        Debian
    os_family:
        Debian
    osarch:
        amd64
    oscodename:
        bullseye
    osfinger:
        Debian-11
    osfullname:
        Debian GNU/Linux
    osmajorrelease:
        11
    osrelease:
        11
    osrelease_info:
        - 11
    path:
        /usr/lib/venv-salt-minion/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    pid:
        312
    productname:
        VMware Virtual Platform
    ps:
        ps -efHww
    pythonexecutable:
        /usr/lib/venv-salt-minion/bin/python.original
    pythonpath:
        - /usr/lib/venv-salt-minion/bin
        - /usr/lib/venv-salt-minion/lib/python36.zip
        - /usr/lib/venv-salt-minion/lib/python3.6
        - /usr/lib/venv-salt-minion/lib/python3.6/lib-dynload
        - /usr/lib/venv-salt-minion/lib/python3.6/site-packages
    pythonversion:
        - 3
        - 6
        - 13
        - final
        - 0
    saltpath:
        /usr/lib/venv-salt-minion/lib/python3.6/site-packages/salt
    saltversion:
        3002.2
    saltversioninfo:
        - 3002
        - 2
    serialnumber:
        VMware-42 07 34 04 68 f4 85 14-d7 06 b9 ea 4d 5e b3 38
    server_id:
        1166149350
    shell:
        /bin/sh
    ssds:
    swap_total:
        2044
    systemd:
        ----------
        features:
            +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
        version:
            247
    systempath:
        - /usr/lib/venv-salt-minion/bin
        - /usr/local/sbin
        - /usr/local/bin
        - /usr/sbin
        - /usr/bin
        - /sbin
        - /bin
    total_num_cpus:
        4
    transactional:
        False
    uid:
        0
    username:
        root
    uuid:
        04340742-f468-1485-d706-b9ea4d5eb338
    virtual:
        container
    virtual_subtype:
        Docker
    zfs_feature_flags:
        False
    zfs_support:
        False
    zmqversion:
        4.2.3
root@debian11-container:/#

**Comment by Shirocco88** [comment]
Link to PR https://github.com/uyuni-project/uyuni/pull/4122 "Basic-Support-for-Debian-11-as-clients"

**Comment by Shirocco88** [comment]
@juliogonzalez 
> You can include the Java part, as the changes should be minimal.

done, see PR https://github.com/uyuni-project/uyuni/pull/4180 "Debian-11-Java-enablement"

**Comment by mcalmer** [comment]
@Shirocco88 AFAIK this is now fully implemented. Can we close this issue?

**Comment by agraul** [comment]
Closing as done.
