### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021-08 spacewalk-backend unit test "test_rhnLib_timestamp" fails

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#4125]
# Information

Unit test rhnLib.timestamp fails when run locally (not on build server):
https://github.com/uyuni-project/uyuni/blob/d398e310086cfaeed9f10e165c17323f310b3c01/backend/server/test/unit-test/test_rhnLib_timestamp.py#L67
```
======================================================================
FAIL: test_timestamp_3 (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rhnLib_timestamp.py", line 71, in test_timestamp_3
    self.assertTrue(is_eq, "Failed: %s, %s" % (t1, t2))
AssertionError: False is not true : Failed: 57739297, 57739297

----------------------------------------------------------------------
Ran 1 test in 0.002s

```
Test includes daylight savings time
https://github.com/uyuni-project/uyuni/blob/d398e310086cfaeed9f10e165c17323f310b3c01/backend/server/test/unit-test/test_rhnLib_timestamp.py#L49

library function does ignores DST (from my understanding). So input time plus DST will never be output time without DST.
https://github.com/uyuni-project/uyuni/blob/d398e310086cfaeed9f10e165c17323f310b3c01/uyuni/common-libs/common/rhnLib.py#L83

I assume tests have passed so far on the build servers as they are not running on a DST time locale.

**Comment by sbluhm** [comment]
Can you tell me the wanted behaviour? I cannot tell if the test is wrong or if the timestamp function is wrong.

**Comment by mcalmer** [comment]
I think we removed this test already.
