### ISSUE TITLE
Bugreport - Uyuni 2021.08 - spacewalk-proxy "ModuleNotFoundError: No module named 'new'"

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#4126]
https://github.com/uyuni-project/uyuni/blob/d398e310086cfaeed9f10e165c17323f310b3c01/proxy/proxy/rhnAuthCacheClient.py#L170

`ModuleNotFoundError: No module named 'new'`
Does not exist anymore so should be replaced.

**Comment by meaksh** [comment]
Yeah, we definetely need to replace this with something that can replace its functionality. Thanks for reporting!
