### ISSUE TITLE
Uyuni Bugreport - 2021.08: CentOS 7 Client Repo cant be mirrored

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#4127]
# Additional Information
Uyuni CentOS7 Client Repo cant be mirrored.

## Version of Uyuni Server and Proxy (if used)
root@uyuni:~ # zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.08-139.2.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.08-139.2.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
root@uyuni:~ # /usr/bin/spacewalk-repo-sync -vv --channel centos7-uyuni-client-x86_64 --type yum --non-interactive
10:32:29 ======================================
10:32:29 | Channel: centos7-uyuni-client-x86_64
10:32:29 ======================================
10:32:29 Sync of channel started.
Retrieving repository 'centos7-uyuni-client-x86_64' metadata .......................................................................................................................................................................[error]
10:32:41 RepoMDError: Cannot access repository.
Repository 'centos7-uyuni-client-x86_64' is invalid.
[centos7-uyuni-client-x86_64|https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/?proxy=http%3A//proxy.intra.de%3A8080] Valid metadata not found at specified URL
History:
 - File './repodata/81ff48b3bca17b11995246f583d79df8d3ecf30b2fcda2118d136bc0c7d09cbd-primary.xml.gz' not found on medium 'https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/?proxy=http%3A//proxy.intra.de%3A8080'
 - Can't provide ./repodata/81ff48b3bca17b11995246f583d79df8d3ecf30b2fcda2118d136bc0c7d09cbd-primary.xml.gz

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'centos7-uyuni-client-x86_64' because of the above error.
Could not refresh the repositories because of errors.

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 590, in sync
    repo_checksum_type = plugin.get_md_checksum_type()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 750, in get_md_checksum_type
    if self._md_exists('repomd'):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 701, in _md_exists
    self.setup_repo(self.repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 648, in setup_repo
    raise RepoMDError("Cannot access repository.\n{}".format(sstr(process.stderr)))
spacewalk.satellite_tools.repo_plugins.yum_src.RepoMDError: Cannot access repository.
Repository 'centos7-uyuni-client-x86_64' is invalid.
[centos7-uyuni-client-x86_64|https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/?proxy=http%3A//proxy.intra.de%3A8080] Valid metadata not found at specified URL
History:
 - File './repodata/81ff48b3bca17b11995246f583d79df8d3ecf30b2fcda2118d136bc0c7d09cbd-primary.xml.gz' not found on medium 'https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/?proxy=http%3A//proxy.intra.de%3A8080'
 - Can't provide ./repodata/81ff48b3bca17b11995246f583d79df8d3ecf30b2fcda2118d136bc0c7d09cbd-primary.xml.gz

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'centos7-uyuni-client-x86_64' because of the above error.
Could not refresh the repositories because of errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 286, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 269, in main
    elapsed_time, channel_ret_code = sync.sync()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 634, in sync
    self.sendErrorMail("RepoMDError: %s" % e)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 2332, in sendErrorMail
    rhnMail.send(headers, extra + body)
  File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnMail.py", line 64, in send
    server = smtplib.SMTP('localhost')
  File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
root@uyuni:~ #

**Comment by mrstigmata** [comment]
with the last creation / sync 17-Aug-2021 10:30 the repo is fine again.

thx a lot!

**Comment by imagineTh4t** [comment]
I think problem repeated
