### ISSUE TITLE
Uyuni Bugreport - Uyuni Master 2021-08-25: spacewalk-setup-cobbler fails on Enterprise Linux

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#4163]
`spacewalk-setup-cobbler` fails with  
`FileNotFoundError: [Errno 2] No such file or directory: '/etc/httpd/cobbler.conf'`

This is due to the defined default value via:
https://github.com/uyuni-project/uyuni/blob/32c6a635be497454fe6b7ad4aea46c02f52d2dfc/spacewalk/setup/bin/spacewalk-setup-cobbler#L25

Correct location on EL is `/etc/httpd/conf.d`

**Comment by sbluhm** [comment]
@SchoolGuy , thank you for clarifying. Doesn't seem to work for me. libutil.32 seems to be missing on load. Will move this to a different thread though.

Going back to my original topic: How is it expected to run mkgrub.sh? During setup? Manually? During reposync?
How does this work on SUSE? On Enterprise Linux there is definitely a piece missing unless it is meant to be manual.

**Comment by sbluhm** [comment]
ok, found it in the SUSE spec file. Will see how I can get this upstream.

**Comment by SchoolGuy** [comment]
@sbluhm If you look at Cobbler Code please be aware that we will integrate this script into the Python Codebase soon. So don't put to much effort into this right now as it is subject to change soon. See [here](https://github.com/cobbler/cobbler/pull/2739) for details.

**Comment by sbluhm** [comment]
I believe the originally reported issue is fixed. Therefore closing.
For the other issue (mkgrub/bootloaders_dir), we will wait for the next cobbler release.
