### ISSUE TITLE
Add VNC display page for all clients

### ISSUE THREAD

**Issue by cbosdo** [uyuni-project/uyuni#418]
Virtual Machines will naturally get a VNC display page -- see PR #417 for this.
This feature should be extended to all other clients. This requires installing a VNC server on the physical machines.

**Comment by kkaempf** [comment]
Are there alternatives ? Different VNC implementations ? What were the reasons to choose the implementation in pr #417 ?

**Comment by juliogonzalez** [comment]
Since we have https://github.com/uyuni-project/uyuni/pull/417 ... what's missing at this PR? Should we maybe have a checklist?

**Comment by cbosdo** [comment]
That one is done. Forgot about it.
