### ISSUE TITLE
Dubbed recording - Uyuni 2021.08

### ISSUE THREAD

**Issue by Gabslocks** [uyuni-project/uyuni#4185]
# Additional Information

error with duplicate repository records after migrating DB to an external resource. Tried to clean up duplicates in "rhnchannel" and removed 2 new lines in "Dual". But there are still duplicates of repositories left in server's options "software- software Channels"

![photo5296374127365568336](https://user-images.githubusercontent.com/45531037/131707854-c5803221-0ad4-40e4-b4bd-4b1b5057264a.jpg)

## Version of Uyuni Server 
Uyuni 2021.08

**Comment by juliogonzalez** [comment]
What does `migrating DB to an external resource` mean?

The PostgreSQL cluster must be on the same instance where the rest of the software is (the database can be on a network volume, attached to the server instance, but that's not really recommended).

**Comment by Gabslocks** [comment]
explanation of the problem


I wanted to change the database server. Since there is a setting for the database in the uyuni settings, where I could change the server value, I began to look for the documentation. In the documentation itself, there is no information about transferring the database to another server. Therefore, I decided to look in the spacewalk, because they are close in system.

I found an instruction for transferring a database to a satellite. I decided to use their method.

https://access.redhat.com/documentation/en-us/red_hat_satellite/5.7/html/installation_guide/sect-migrating_from_an_embedded_database_to_an_external_postgresql_database


I exported the database using the standard PostgreSQL commands (
pg_dump the_db_name > the_backup.sql

psql the_new_dev_db < the_backup.sql
).

However, the system did not transfer the old data to the new system. This was a bit of a problem for me as these are just test users and machines. The database was working, giving and receiving the rows I wanted, so I just kept filling it in.

I filled the base with a few more test machines and started tweaking them, checking what could be done. After that, I just saw the problem that I described in a bug on GitHub.

**Comment by Gabslocks** [comment]
> What does `migrating DB to an external resource` mean?
> 
> The PostgreSQL cluster must be on the same instance where the rest of the software is (the database can be on a network volume, attached to the server instance, but that's not really recommended).

That is, you cannot use an external database in uyuuni?

**Comment by juliogonzalez** [comment]
> That is, you cannot use an external database in uyuuni?

Yes, that's what it means.

The procedure is for Satellite, I am not even sure if Spacewalk itself officially supported it.

Can it work? It depends on a lot of factors, such as:
- Does the PostgreSQL support all the options we need (not the case for AWS RDS for example)?
- Is the remote PostgreSQL is configured correctly, as Uyuni tweaks the PostgreSQL configuration for the local server?
- Does the network connectivity work fine?
- What about the storage?

Some could break Uyuni, some could mean performance problems 

So while you can try it, we can't help if there are issues.

**Comment by Gabslocks** [comment]
OK good. I transferred the database from external databases to local. I tried to fix or identify the error. I realized that the error is still in the database, since I got additional duplicates after pg_restore to an existing database (there was a key in pg_dump that cleared the previous data, but it did not work fine). If it's inside the database, what can you do about it?

**Comment by mcalmer** [comment]
I fear here you can only re-install. As this was filled a long time ago, I think this was already done.
