### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.08 python2  ( /usr/share/susemanager/salt/_grains/virt.py)

### ISSUE THREAD

**Issue by vailenwallaces** [uyuni-project/uyuni#4213]
## Version of Uyuni Server
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.08-139.2.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.08-139.2.uyuni1.src
Summary        : Uyuni Server

## Details about issue
Client OS :  -SLES 12 SP5 as salt-client use python2.

The Module /usr/share/susemanager/salt/_grains/virt.py includes code that as i understand only run under python3: 

`try:
    import libvirt
except ModuleNotFoundError:
    libvirt = None`

ModuleNotFoundError is not available on python2 so the salt-client reported this error: 

`[ERROR   ] Failed to import grains virt, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1658, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/grains/virt.py", line 12, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined`

**Comment by cbosdo** [comment]
Commit https://github.com/uyuni-project/uyuni/commit/53ce08a probably fixes the issue

**Comment by beaconfield** [comment]
I'm also having this issue on a new deployment of Uyuni client with a new Uyuni server setup. What kind of process does this go through in order to get pushed to the repos where it can be updated on our side?

**Comment by cbosdo** [comment]
> I'm also having this issue on a new deployment of Uyuni client with a new Uyuni server setup. What kind of process does this go through in order to get pushed to the repos where it can be updated on our side?

This patch will be in the next Uyuni release. Either you wait for it or you manually apply the change temporarily on your server.

**Comment by beaconfield** [comment]
> > I'm also having this issue on a new deployment of Uyuni client with a new Uyuni server setup. What kind of process does this go through in order to get pushed to the repos where it can be updated on our side?
> 
> This patch will be in the next Uyuni release. Either you wait for it or you manually apply the change temporarily on your server.

Thanks! I am interested in tooling around with the code, and I have it cloned to my machine. If I switch to the json_pillar branch and grab that virt.py is that sufficient to apply the change manually?

**Comment by beaconfield** [comment]
Actually that won't work since the file resides in /var/cache. Looks like virt.py gets deployed/overwritten when salt-minion starts up.

**Comment by cbosdo** [comment]
> Thanks! I am interested in tooling around with the code, and I have it cloned to my machine. If I switch to the json_pillar branch and grab that virt.py is that sufficient to apply the change manually?

Why are you mentioning the `json_pillar` branch? That one is a work in progress to move the pillar data files to the database... and completely unrelated to this bug.

On the minion side, yes it resides in the `/var/cache` since those are grains shipped to the minion from the master. [`salt '*' saltutil.sync_all`](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_all) may be needed to refresh the cache indeed.

**Comment by beaconfield** [comment]
Ah thank you. Yes I recognize I was ignorant of the arch and I didn't realize the file was shipped from the salt master. Got it now, thanks!
