### ISSUE TITLE
Uyuni Bugreport - errata apply error

### ISSUE THREAD

**Issue by symbatkarzhassov** [uyuni-project/uyuni#4237]
```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.05-123.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.02-116.3.uyuni installed)
Source package : Uyuni-Server-release-2021.05-123.2.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

when i update security patch i got an error on uyuni server:

```
2021/09/23 14:46:35 +06:00 6114 10.34.152.18: xmlrpc/errata.getErrataInfo(1000010269, {'allow_vendor_change': False, 'errata_ids': [11464]})
2021/09/23 14:46:35 +06:00 6114 10.34.152.18: server/apacheRequest.call_function('ERROR', 'rhnSQL.SQLError caught', SQLStatementPrepareError(None, "<connection object at 0x7fdf0a3ef180; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", '\n        select distinct\n               pn.name,\n               pe.epoch,\n               pe.version,\n               pe.release,\n               pa.label arch\n        from\n               rhnPackageName pn,\n               rhnPackageEVR pe,\n               rhnPackage p,\n               rhnPackageArch pa,\n               rhnChannelPackage cp,\n               rhnServerChannel sc,\n               rhnErrataPackage ep\n        where\n                   ep.errata_id = %(errata_id)s\n               and ep.package_id = p.id\n               and p.name_id = pn.id\n               and p.evr_id = pe.id\n               and p.package_arch_id = pa.id\n               and sc.server_id = %(server_id)s\n               and sc.channel_id = cp.channel_id\n               and cp.package_id = p.id\n        '))
2021/09/23 14:46:35 +06:00 6814 10.34.152.18: xmlrpc/queue.submit(1000010269, 1976, [6])
2021/09/23 14:46:35 +06:00 6121 10.34.152.18: xmlrpc/queue.get(1000010269, 2, 'checkins enabled')
2021/09/23 14:46:35 +06:00 6119 10.34.152.18: xmlrpc/registration.welcome_message('lang: None',)
```

How to solve it?

**Comment by juliogonzalez** [comment]
> when i update security path i got an error on uyuni server:

What does this mean?

**Comment by symbatkarzhassov** [comment]
when i update security patch i got an error on uyuni server
I try to install for example  'kernel security and bug fix update'  or 'microcode_ctl security, bug fix and enhancement update '

**Comment by symbatkarzhassov** [comment]
problem is note solved when i update for latest Uyuni release 2021.09

**Comment by juliogonzalez** [comment]
> when i update security patch i got an error on uyuni server
> I try to install for example 'kernel security and bug fix update' or 'microcode_ctl security, bug fix and enhancement update '

I a not sure I am understanding. You get the error *applying* the security patch to a *client*?

If so, please provide more details about the client, specify how you are applying the patch (WebUI? XMLRPC API call? spacecmd?), and please check if any other errors are present at any files inside `/var/log/rhn` at the server (if there are, please paste them)

**Comment by symbatkarzhassov** [comment]
yes i get the error applying the security patch to a client. Client is Redhat 7.
I apply the patch with Web UI. 
And yes I paste the error from the server 
Web UI error:
`Client execution returned

Fatal error in Python code occurred [[6]]

(code -1)

Patches Affected:

    RHSA-2021:3296 - Important: libX11 security update`
client error:
`: rpcServer: Calling XMLRPC errata.getErrataInfo
A protocol error occurred: **Internal Server Error** , attempt #1,
D: Sending back response((6,), 'Fatal error in Python code occurred', {})
D: do_call packages.checkNeedUpdate('rhnsd=1',){}
D: local action status: (0, 'rpm database not modified since last update (or package list recently updated)', {})
D: rpcServer: Calling XMLRPC registration.welcome_message
D: closed   db index       /var/lib/rpm/Providename
D: closed   db index       /var/lib/rpm/Packages
D: closed   db environment /var/lib/rpm`

it was error from rhn_server_xmlrpc.log:
`2021/09/27 09:52:34 +06:00 49231 some_ip: xmlrpc/errata.getErrataInfo(1000010269, {'allow_vendor_change': False, 'errata_ids': [11671]})
2021/09/27 09:52:34 +06:00 49231 some_ip: server/apacheRequest.call_function('ERROR', 'rhnSQL.SQLError caught', SQLStatementPrepareError(None, "<connection object at 0x7fe1b71cb2b8; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", '\n        select distinct\n               pn.name,\n               pe.epoch,\n               pe.version,\n               pe.release,\n               pa.label arch\n        from\n               rhnPackageName pn,\n               rhnPackageEVR pe,\n               rhnPackage p,\n               rhnPackageArch pa,\n               rhnChannelPackage cp,\n               rhnServerChannel sc,\n               rhnErrataPackage ep\n        where\n                   ep.errata_id = %(errata_id)s\n               and ep.package_id = p.id\n               and p.name_id = pn.id\n               and p.evr_id = pe.id\n               and p.package_arch_id = pa.id\n               and sc.server_id = %(server_id)s\n               and sc.channel_id = cp.channel_id\n               and cp.package_id = p.id\n        '))`

**Comment by juliogonzalez** [comment]
Salt? Salt SSH? Traditional?

Nothing at all at any other log at `/var/log/rhn`? Only at `rhn_server_xmlrpc.log`?

**Comment by symbatkarzhassov** [comment]
Traditional
in osa-dispatcher.log

`2021/09/27 17:06:22 +06:00 1962 0.0.0.0: osad/jabber_lib._error_callback('ERROR', 'Received an error stanza: ', <error><conflict xmlns = 'urn:ietf:params:xml:ns:xmpp-streams'  /></error>)
2021/09/27 17:06:22 +06:00 1962 0.0.0.0: osad/jabber_lib._error_callback('ERROR', 'Received an conflict. Restarting with new credentials.')`
but I do not think it is current problem, because not errata security packages updated successfuly on any client machine
And other log files not modified

**Comment by symbatkarzhassov** [comment]
Any ideas?

**Comment by symbatkarzhassov** [comment]
I found duplicate error in  /var/log/apache2/error_log:
`[Tue Sep 28 14:36:27.585806 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Exception reported from lsp-sup1-lp1
[Tue Sep 28 14:36:27.585819 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Time: Tue Sep 28 14:36:27 2021
[Tue Sep 28 14:36:27.585821 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Exception type <class 'spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError'>
[Tue Sep 28 14:36:27.585824 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Exception while handling function errata.getErrataInfo
[Tue Sep 28 14:36:27.585825 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Request object information:
[Tue Sep 28 14:36:27.585828 2021] [wsgi:error] [pid 77376] [client some_ip:41722] URI: /XMLRPC
[Tue Sep 28 14:36:27.585829 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Remote Host: test-pc1.hq.bc
[Tue Sep 28 14:36:27.585840 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Server Name: lsp-sup1-lp1.hq.bc:80
[Tue Sep 28 14:36:27.585841 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Headers passed in:
[Tue Sep 28 14:36:27.585843 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tAccept-Encoding: identity
[Tue Sep 28 14:36:27.585844 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tCONTENT_LENGTH: 2466
[Tue Sep 28 14:36:27.585846 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tCONTENT_TYPE: text/xml
[Tue Sep 28 14:36:27.585847 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tCONTEXT_DOCUMENT_ROOT: /srv/www/htdocs
[Tue Sep 28 14:36:27.585848 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tCONTEXT_PREFIX: 
[Tue Sep 28 14:36:27.585850 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tDOCUMENT_ROOT: /srv/www/htdocs
[Tue Sep 28 14:36:27.585851 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tGATEWAY_INTERFACE: CGI/1.1
[Tue Sep 28 14:36:27.585852 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_ACCEPT_ENCODING: identity
[Tue Sep 28 14:36:27.585854 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_HOST: lsp-sup1-lp1.hq.bc
[Tue Sep 28 14:36:27.585855 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_USER_AGENT: rhn.rpclib.py/2.9.52.9.5-1.el71.el7
[Tue Sep 28 14:36:27.585856 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_X_CLIENT_VERSION: 1
[Tue Sep 28 14:36:27.585858 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_X_INFO: RPC Processor (C) Red Hat, Inc (version 2.9.52.9.5-1.el71.el7)
[Tue Sep 28 14:36:27.585860 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_X_RHN_CLIENT_CAPABILITY: osad.ping(1)=1,packages.verify(1)=1,packages.extended_profile(2)=1,osad.rhn_check(1)=1,configfiles.base64_enc(1)=1,reboot.reboot(1)=1,configfiles.deploy(1)=1,caneatCheese(1)=1,packages.rollBack(1)=1,configfiles.mtime_upload(1)=1,configfiles.diff(1)=1,packages.update(2)=2,script.run(1)=1,configfiles.upload(1)=1,packages.runTransaction(1)=1
[Tue Sep 28 14:36:27.585863 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_X_RHN_TRANSPORT_CAPABILITY: follow-redirects=3
[Tue Sep 28 14:36:27.585864 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_X_TRANSPORT_INFO: Extended Capabilities Transport (C) Red Hat, Inc (version 2.9.52.9.5-1.el71.el7)
[Tue Sep 28 14:36:27.585867 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHTTP_X_UP2DATE_VERSION: 2.10.10-1.el7
[Tue Sep 28 14:36:27.585869 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tHost: lsp-sup1-lp1.hq.bc
[Tue Sep 28 14:36:27.585871 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tPATH_INFO: 
[Tue Sep 28 14:36:27.585873 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tQUERY_STRING: 
[Tue Sep 28 14:36:27.585875 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tREMOTE_ADDR: some_ip
[Tue Sep 28 14:36:27.585877 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tREMOTE_PORT: 41722
[Tue Sep 28 14:36:27.585879 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tREQUEST_METHOD: POST
[Tue Sep 28 14:36:27.585881 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tREQUEST_SCHEME: http
[Tue Sep 28 14:36:27.585883 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tREQUEST_URI: /XMLRPC
[Tue Sep 28 14:36:27.585885 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSCRIPT_FILENAME: /usr/share/rhn/wsgi/xmlrpc.py
[Tue Sep 28 14:36:27.585887 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSCRIPT_NAME: /XMLRPC
[Tue Sep 28 14:36:27.585889 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSCRIPT_URI: http://lsp-sup1-lp1.hq.bc/XMLRPC
[Tue Sep 28 14:36:27.585890 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSCRIPT_URL: /XMLRPC
[Tue Sep 28 14:36:27.585891 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSERVER_ADDR: 10.1.119.128
[Tue Sep 28 14:36:27.585895 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSERVER_ADMIN: [no address given]
[Tue Sep 28 14:36:27.585897 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSERVER_NAME: lsp-sup1-lp1.hq.bc
[Tue Sep 28 14:36:27.585898 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSERVER_PORT: 80
[Tue Sep 28 14:36:27.585900 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSERVER_PROTOCOL: HTTP/1.1
[Tue Sep 28 14:36:27.585901 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSERVER_SIGNATURE: 
[Tue Sep 28 14:36:27.585902 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tSERVER_SOFTWARE: Apache
[Tue Sep 28 14:36:27.585904 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tUser-Agent: rhn.rpclib.py/2.9.52.9.5-1.el71.el7
[Tue Sep 28 14:36:27.585905 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tX-Client-Version: 1
[Tue Sep 28 14:36:27.585906 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tX-Info: RPC Processor (C) Red Hat, Inc (version 2.9.52.9.5-1.el71.el7)
[Tue Sep 28 14:36:27.585909 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tX-RHN-Client-Capability: osad.ping(1)=1,packages.verify(1)=1,packages.extended_profile(2)=1,osad.rhn_check(1)=1,configfiles.base64_enc(1)=1,reboot.reboot(1)=1,configfiles.deploy(1)=1,caneatCheese(1)=1,packages.rollBack(1)=1,configfiles.mtime_upload(1)=1,configfiles.diff(1)=1,packages.update(2)=2,script.run(1)=1,configfiles.upload(1)=1,packages.runTransaction(1)=1
[Tue Sep 28 14:36:27.585911 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tX-RHN-Transport-Capability: follow-redirects=3
[Tue Sep 28 14:36:27.585913 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tX-Transport-Info: Extended Capabilities Transport (C) Red Hat, Inc (version 2.9.52.9.5-1.el71.el7)
[Tue Sep 28 14:36:27.585915 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tX-Up2Date-Version: 2.10.10-1.el7
[Tue Sep 28 14:36:27.585916 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tapache.version: (2, 4, 43)
[Tue Sep 28 14:36:27.585917 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.application_group: lsp-sup1-lp1.hq.bc|/xmlrpc
[Tue Sep 28 14:36:27.585919 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.callable_object: application
[Tue Sep 28 14:36:27.585920 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.enable_sendfile: 0
[Tue Sep 28 14:36:27.585922 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.handler_script: 
[Tue Sep 28 14:36:27.585923 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.ignore_activity: 0
[Tue Sep 28 14:36:27.585924 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.listener_host: 
[Tue Sep 28 14:36:27.585926 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.listener_port: 80
[Tue Sep 28 14:36:27.585927 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.path_info: 
[Tue Sep 28 14:36:27.585928 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.process_group: 
[Tue Sep 28 14:36:27.585930 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.request_handler: wsgi-script
[Tue Sep 28 14:36:27.585931 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.request_id: xKgNHMrZNfs
[Tue Sep 28 14:36:27.585932 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.request_start: 1632818187577540
[Tue Sep 28 14:36:27.585934 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.script_name: /XMLRPC
[Tue Sep 28 14:36:27.585935 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.script_reloading: 1
[Tue Sep 28 14:36:27.585936 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.script_start: 1632818187577774
[Tue Sep 28 14:36:27.585938 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.thread_id: 0
[Tue Sep 28 14:36:27.585941 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.thread_requests: 20
[Tue Sep 28 14:36:27.585942 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.total_requests: 20
[Tue Sep 28 14:36:27.585943 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \tmod_wsgi.version: (4, 5, 18)
[Tue Sep 28 14:36:27.585945 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \twsgi.errors: <_io.TextIOWrapper name='<wsgi.errors>' encoding='utf-8'>
[Tue Sep 28 14:36:27.585947 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \twsgi.file_wrapper: <class 'mod_wsgi.FileWrapper'>
[Tue Sep 28 14:36:27.585948 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \twsgi.input: <mod_wsgi.Input object at 0x7fd8044f5180>
[Tue Sep 28 14:36:27.585949 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \twsgi.multiprocess: True
[Tue Sep 28 14:36:27.585951 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \twsgi.multithread: False
[Tue Sep 28 14:36:27.585952 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \twsgi.run_once: False
[Tue Sep 28 14:36:27.585953 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \twsgi.url_scheme: http
[Tue Sep 28 14:36:27.585955 2021] [wsgi:error] [pid 77376] [client some_ip:41722] \twsgi.version: (1, 0)
[Tue Sep 28 14:36:27.585956 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Extra information about this error:
[Tue Sep 28 14:36:27.585959 2021] [wsgi:error] [pid 77376] [client some_ip:41722] SQL Error generated: (None, "<connection object at 0x7fd804ce2180; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", '\\n        select distinct\\n               pn.name,\\n               pe.epoch,\\n               pe.version,\\n               pe.release,\\n               pa.label arch\\n        from\\n               rhnPackageName pn,\\n               rhnPackageEVR pe,\\n               rhnPackage p,\\n               rhnPackageArch pa,\\n               rhnChannelPackage cp,\\n               rhnServerChannel sc,\\n               rhnErrataPackage ep\\n        where\\n                   ep.errata_id = %(errata_id)s\\n               and ep.package_id = p.id\\n               and p.name_id = pn.id\\n               and p.evr_id = pe.id\\n               and p.package_arch_id = pa.id\\n               and sc.server_id = %(server_id)s\\n               and sc.channel_id = cp.channel_id\\n               and cp.package_id = p.id\\n        ')
[Tue Sep 28 14:36:27.585963 2021] [wsgi:error] [pid 77376] [client some_ip:41722] 
[Tue Sep 28 14:36:27.585964 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Exception Handler Information
[Tue Sep 28 14:36:27.585965 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Traceback (most recent call last):
[Tue Sep 28 14:36:27.585967 2021] [wsgi:error] [pid 77376] [client some_ip:41722]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
[Tue Sep 28 14:36:27.585969 2021] [wsgi:error] [pid 77376] [client some_ip:41722]     retval = function(*p, **kw)
[Tue Sep 28 14:36:27.585970 2021] [wsgi:error] [pid 77376] [client some_ip:41722]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 182, in _execute
[Tue Sep 28 14:36:27.585972 2021] [wsgi:error] [pid 77376] [client some_ip:41722]     return self._execute_(args, kwargs)
[Tue Sep 28 14:36:27.585973 2021] [wsgi:error] [pid 77376] [client some_ip:41722]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 322, in _execute_
[Tue Sep 28 14:36:27.585975 2021] [wsgi:error] [pid 77376] [client some_ip:41722]     self._real_cursor.execute(self.sql, params)
[Tue Sep 28 14:36:27.585976 2021] [wsgi:error] [pid 77376] [client some_ip:41722] psycopg2.ProgrammingError: can't adapt type 'dict'
[Tue Sep 28 14:36:27.585978 2021] [wsgi:error] [pid 77376] [client some_ip:41722] 
[Tue Sep 28 14:36:27.585979 2021] [wsgi:error] [pid 77376] [client some_ip:41722] During handling of the above exception, another exception occurred:
[Tue Sep 28 14:36:27.585982 2021] [wsgi:error] [pid 77376] [client some_ip:41722] 
[Tue Sep 28 14:36:27.585983 2021] [wsgi:error] [pid 77376] [client some_ip:41722] Traceback (most recent call last):
[Tue Sep 28 14:36:27.585985 2021] [wsgi:error] [pid 77376] [client some_ip:41722]   File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 135, in call_function
[Tue Sep 28 14:36:27.585986 2021] [wsgi:error] [pid 77376] [client some_ip:41722]     response = func(*params)
[Tue Sep 28 14:36:27.585988 2021] [wsgi:error] [pid 77376] [client some_ip:41722]   File "/usr/share/rhn/server/handlers/xmlrpc/errata.py", line 223, in getErrataInfo
[Tue Sep 28 14:36:27.585989 2021] [wsgi:error] [pid 77376] [client some_ip:41722]     h.execute(errata_id=errata_id, server_id=self.server_id)
[Tue Sep 28 14:36:27.585991 2021] [wsgi:error] [pid 77376] [client some_ip:41722]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 150, in execute
[Tue Sep 28 14:36:27.585992 2021] [wsgi:error] [pid 77376] [client some_ip:41722]     return self._execute_wrapper(self._execute, *p, **kw)
[Tue Sep 28 14:36:27.585994 2021] [wsgi:error] [pid 77376] [client some_ip:41722]   File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 309, in _execute_wrapper
[Tue Sep 28 14:36:27.585995 2021] [wsgi:error] [pid 77376] [client some_ip:41722]     raise sql_base.SQLStatementPrepareError(str(self.dbh), e.pgerror, self.sql)
[Tue Sep 28 14:36:27.585998 2021] [wsgi:error] [pid 77376] [client some_ip:41722] spacewalk.server.rhnSQL.sql_base.SQLStatementPrepareError: (None, "<connection object at 0x7fd804ce2180; dsn: 'user=uyuni password=xxx dbname=uyuni', closed: 0>", '\\n        select distinct\\n               pn.name,\\n               pe.epoch,\\n               pe.version,\\n               pe.release,\\n               pa.label arch\\n        from\\n               rhnPackageName pn,\\n               rhnPackageEVR pe,\\n               rhnPackage p,\\n               rhnPackageArch pa,\\n               rhnChannelPackage cp,\\n               rhnServerChannel sc,\\n               rhnErrataPackage ep\\n        where\\n                   ep.errata_id = %(errata_id)s\\n               and ep.package_id = p.id\\n               and p.name_id = pn.id\\n               and p.evr_id = pe.id\\n               and p.package_arch_id = pa.id\\n               and sc.server_id = %(server_id)s\\n               and sc.channel_id = cp.channel_id\\n               and cp.package_id = p.id\\n        ')
[Tue Sep 28 14:36:27.586006 2021] [wsgi:error] [pid 77376] [client some_ip:41722] `

**Comment by symbatkarzhassov** [comment]
I found solution. We need install packages with their dependencies

**Comment by kluchoslaw** [comment]
@symbatkarzhassov Can You please explain a bit? what dependencies? I have the same errors appying erratas for libx11 or kernel.

**Comment by symbatkarzhassov** [comment]
for example to install     polkit, you must install polkit-libs with them, because polkit-libs is dependencie of polkit. To make it easier install all packages, because to find dependencies I run yum update polkit command on client
 yum update polkit
Updating Subscription Management repositories.
Unable to read consumer identity
This system is receiving updates from Red Hat Satellite or Spacewalk server.
Last metadata expiration check: 0:01:01 ago on Thu 30 Sep 2021 10:56:57 PM +06.
Dependencies resolved.
=================================================================================================================================
 Package                    Architecture          Version                            Repository                             Size
=================================================================================================================================
Upgrading:
 polkit                     x86_64                0.115-11.el8_4.1                   tibco-bw-8-test-rhel-8                154 k
 polkit-libs                x86_64                0.115-11.el8_4.1                   tibco-bw-8-test-rhel-8                 76 k

Transaction Summary

**Comment by kluchoslaw** [comment]
So this is not solution but dirty workaround using yum, I use simply ie. yum -y upgrade --advisory=CESA-2021:3582 from gui "remote commands" and it works. 
**Applying patches directly from gui simply dont work**, ticket since several months not closed https://github.com/uyuni-project/uyuni/issues/3904

**Comment by mcalmer** [comment]
As we have a duplicate, I close this issue.
