### ISSUE TITLE
Uyuni Bugreport - VHM kubernetes 

### ISSUE THREAD

**Issue by cspaldi** [uyuni-project/uyuni#4294]
Hello,
when i add kubeconfig file to VHM i got an error on uyuni server:

_**"the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is application/x-www-form-urlencoded; charset=UTF-8"**_

OS name and version: openSUSE Leap 15.3

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.09-141.3.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1,4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.09-141.3.uyuni1.src

**Comment by mcalmer** [comment]
This was fixed a few days ago. Should be working with 2022.06
