### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.08 - Content Lifecycle Filters ignore my regex

### ISSUE THREAD

**Issue by lechneradmin** [uyuni-project/uyuni#4312]
# Additional Information

Content Lifecycle Filters ignore my regex

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.08-139.2.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.06-132.3.uyuni1 installed)
Source package : Uyuni-Server-release-2021.08-139.2.uyuni1.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about issue
I would like to deny perl modul packages on my OracleLinux 8 clients but it didn't work.
A few of them: 
perl-Errno-1.30-452.module+el8.4.0+20078+01326e37:0.x86_64
perl-Digest-HMAC-1.03-17.module+el8.3.0+7739+ee8eefab.noarch
perl-Encode-3.01-439.module+el8.3.0+7729+86a74f64:4.x86_64
perl-HTML-Tagset-3.20-34.module+el8.3.0+7739+ee8eefab.noarch

I use the following  regex with Content Lifecycle Filters. 

![package_regex](https://user-images.githubusercontent.com/92080707/136343575-d875318f-e32d-46bc-8cd3-02340b1cef61.png)

**Comment by cbbayburt** [comment]
hi @lechneradmin, the packages you mentioned belong to the perl module in the AppStream repository. The behavior depends on whether you use any AppStream filters in the CLM project:

- If no AppStream filter is attached to a project, you should be able to filter out any modular package as you wish, though it might break the module handling by `dnf`, complaining about missing packages
- If you use other AppStrem filters in the project but do not have one for the `perl` module, these packages should not be there at all
- If you enable a module explicitly with an AppStream filter, currently there is no way to filter out any of its packages since as in the first case, it might cause `dnf` to fail with module metadata

So the question is, do you have any AppStream filters attached to the project? If so, which ones?

**Comment by lechneradmin** [comment]
Hi @cbbayburt 

I use the following AppStream filters: 
-  php:7.4 
-  httpd:2.4 -
-  nginx:1.20

Any of the mentioned AppStream filter is enabled the following perl packages marked as "upgradable". Originally, the packages are coming from the BaseOS repository.

perl-Carp.noarch               1.50-439.module+el8.3.0+7729+86a74f64
perl-Encode.x86_64             4:3.01-439.module+el8.3.0+7729+86a74f64
perl-Exporter.noarch           5.73-440.module+el8.3.0+7729+86a74f64
perl-File-Path.noarch          2.16-439.module+el8.3.0+7729+86a74f64
perl-File-Temp.noarch          1:0.230.900-439.module+el8.3.0+7729+86a74f64
perl-HTTP-Tiny.noarch          0.076-439.module+el8.3.0+7729+86a74f64
perl-MIME-Base64.x86_64        3.15-1001.module+el8.3.0+7729+86a74f64
perl-PathTools.x86_64          3.78-439.module+el8.3.0+7729+86a74f64
perl-Pod-Escapes.noarch        1:1.07-396.module+el8.3.0+7729+86a74f64
perl-Pod-Perldoc.noarch        3.28.01-442.module+el8.3.0+7729+86a74f64
perl-Pod-Simple.noarch         1:3.40-1.module+el8.3.0+7729+86a74f64
perl-Pod-Usage.noarch          4:1.69-396.module+el8.3.0+7729+86a74f64
perl-Scalar-List-Utils.x86_64  3:1.53-439.module+el8.3.0+7729+86a74f64
perl-Socket.x86_64             4:2.029-4.module+el8.3.0+7729+86a74f64
perl-Storable.x86_64           1:3.15-442.module+el8.3.0+7729+86a74f64
perl-Term-ANSIColor.noarch     4.06-397.module+el8.3.0+7729+86a74f64
perl-Term-Cap.noarch           1.17-396.module+el8.3.0+7729+86a74f64
perl-Text-ParseWords.noarch    3.30-396.module+el8.3.0+7729+86a74f64
perl-Text-Tabs+Wrap.noarch     2013.0523-396.module+el8.3.0+7729+86a74f64
perl-Time-Local.noarch         1:1.280-2.module+el8.3.0+7729+86a74f64
perl-Unicode-Normalize.x86_64  1.26-439.module+el8.3.0+7729+86a74f64
perl-constant.noarch           1.33-1001.module+el8.3.0+7729+86a74f64
perl-parent.noarch             1:0.237-2.module+el8.3.0+7729+86a74f64
perl-threads.x86_64            1:2.22-439.module+el8.3.0+7729+86a74f64
perl-threads-shared.x86_64     1.60-440.module+el8.3.0+7729+86a74f64

**Comment by cbbayburt** [comment]
The "Package (Name)" filter matches only against a package name, not the whole NEVRA.

For example, for package `perl-Errno-1.30-452.module+el8.4.0+20078+01326e37:0.x86_64` your regex will be tested against `perl-Errno`, which will fail.

Unfortunately, CLM doesn't have a type of filter that tests the whole NEVRA against a regex.
You can filter with "perl-", and then add exceptions for any required package specifically with an "Allow" filter.

You can also use "Package (NEVRA)" filter, but in that case, you need to add one filter per package, with the exact values for each field.

I hope this helps

**Comment by lechneradmin** [comment]
Okay, so then I will use the regex only the package name.
