### ISSUE TITLE
Uyuni Client Tools for Centos8 Bugreport - os_family incorrect on Stream

### ISSUE THREAD

**Issue by bochi** [uyuni-project/uyuni#4436]
The Uyuni Client Tools for CentOS8 should be updated (or at least include the fix from https://github.com/garethgreenaway/salt/commit/3bbae00e94a091fabe72af29a4d7e979e7b011e0).

Without that fix, on CentOS Stream the os_family grain returns "CentOS Stream" which in return makes the Uyuni specific states fail that rely on the os_family being RedHat.

Tested with the latest client tools from https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS8-Uyuni-Client-Tools/CentOS_8/

Workaround: Hardcode os_family in /etc/salt/grains - things seem to be working fine using that workaround.

**Comment by vzhestkov** [comment]
The issue will be fixed with releasing salt 3004 in June, this version already contains the proper detection of os_family.
