### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.09 (Ubuntu Repo Parsing Error)

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#4481]
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.09-141.3.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2021.09-141.3.uyuni1.src
Summary        : Uyuni Server

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help reproducing the issue or understanding it_

We mirror the microsoft tools repo for linux (https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod/dists/focal/main/binary-amd64/)
Download, import etc. works fine. 
If we subscribe the channel to a server we got this error after running apt update:

  Reading package lists... Error!
  E: Problem parsing dependency 21 of procdump:amd64=1.2-359
  E: Error occurred while processing procdump (NewVersion2)
  E: Problem with MergeList /var/lib/apt/lists/uyuni:443_rhn_manager_download_dists_microsoft-ubuntu2004-x86%5f64_main_binary-amd64_Packages
  E: The package lists or status file could not be parsed or opened.

in the MergeList file (var/lib/apt/lists/uyuni:443_rhn_manager_download_dists_microsoft-ubuntu2004-x86%5f64_main_binary-amd64_Packages) there is this line: 
Depends: gdb (>= 7.6.1),libc6) if we change it to: Depends: gdb (>= 7.6.1),libc6 
apt update works fine.

is this a problem in the source directory or is this a uyuni repo parser thing?

thx a lot!

**Comment by os-sengel** [comment]
Hi, we have the same issue with an hp tools repository:
https://downloads.linux.hpe.com/SDR/repo/mcp/ubuntu/dists/focal/current/non-free/binary-amd64/Packages

There you find this package:
```
Package: hponcfg
Architecture: amd64
Version: 5.6.0-0
Priority: extra
Section: admin
Maintainer: Lamparter, Richard (Craig) <Linux_SWdeliverables@groups.ext.hpe.com>
Installed-Size: 191
Depends: libc6 (>= 2.3.4),binutils,xsltproc
Filename: pool/non-free/hponcfg-5.6.0-0_amd64.deb
Size: 46994
MD5sum: 640f85f7b23e33b80bf07519e4d03427
SHA1: 9ef95f0e20a3d65ccd422cdd4c9a35527a98b21e
SHA256: 913a29b8f2bcf6c3529da4eabe71799a8bf429b696a520063542c7c3b289ae16
SHA512: 00e75a4210230480b89f51566ebd3e056c1efd8ccb3c373cf05ee247b94368dbe544db6febab806974ea30accf493b72dce3db420fe1e79541f9596be0997b8d
Description: Hponcfg - HP Lights-Out Online Configuration Utility
 Hponcfg is a command line utility that can be used to configure iLO from with in the operating system without requiring a reboot of the server.
 .
```

Which contains the row depends where its entries are not separated by space. Uyuni and Suma are parsing this string incorrectly:
```
Depends: libc6 (>= 2.3.4),binutils,xsltproc
```

This is the synced package from:
https://downloads.linux.hpe.com/SDR/repo/mcp/ubuntu/dists/focal/current/non-free/binary-amd64/Packages
![image](https://user-images.githubusercontent.com/93204679/148981583-1dbfdf88-97d4-4bac-b980-79d028419a9c.png)

while a previous version has consitent syntax (comma-space separated) and is parsed correctly
https://downloads.linux.hpe.com/SDR/repo/mcp/ubuntu/dists/focal/12.05/non-free/binary-amd64/Packages
![image](https://user-images.githubusercontent.com/93204679/148981885-09f4ce37-df83-4f21-b451-0f68ae880b41.png)

We found the same result, if we fix the synchronized Packages on the minion, the apt update problem is temporarly fixed.

----

I dug as down to this https://github.com/uyuni-project/uyuni/blob/d822e162ff914ee267584a9c20f1aae3baec2423/uyuni/common-libs/common/rhn_deb.py

where the python library `debian` contains the class `DebFile` which has the method `debcontrol`. The latter might be the parsing method.

**Comment by blu-base** [comment]
This.
https://github.com/uyuni-project/uyuni/blob/b317bfb48a4c9f9ed490e12178eab65021d0bcc0/backend/server/importlib/debPackage.py#L135

This is the reason why parsing of our vendor repo failed.
I understand, this splitting seems to be by convention. Though i'm not able to see the consequences what would happen if the convention is somewhat loosen here.
