### ISSUE TITLE
Make "Search" text field active immediately after dialog opens

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [uyuni-project/uyuni#4492]
Hello,
It’s a small and stupid request, but gets on my nerves every time.
Why, after clicking on the magnifying glass, do I have to click into the field inside the dialog again in order to make it active before being able to type.
Please make the field active immediately after the dialog opens.
Thanks.

![image](https://user-images.githubusercontent.com/277893/142727287-459f732b-98fc-4b81-8d54-f46ec9857e18.png)

**Comment by digdilem** [comment]
+1, 

I share the tiny amount of irritation this causes. It mounts up through the day and it would be nice to get resolved.

This is a minor QoL issue that was introduced some time ago. From memory I think that Spacewalk had the search box in the banner, so it was "click, type, enter" to search. Now it's "click (box opens), move to box, click, type, enter". Looks nicer like it is now, but slower to use.

**Comment by mcalmer** [comment]
CC @Etheryte

**Comment by Etheryte** [comment]
Thanks for the ping Michael, I didn't notice this ticket before. I've fixed up this issue and a few other related problems, the changes will probably get reviewed after the holidays.
