### ISSUE TITLE
uyuni refuses to sync deb repo (again) - release 2021.09

### ISSUE THREAD

**Issue by Zappelphilipp** [uyuni-project/uyuni#4511]
Hello Uyuni Community,

I pretty much experience the exact same problem as https://github.com/uyuni-project/uyuni/issues/1163

Adding a new .deb source, try to sync the new channel in the web-GUI as well as in the CLI gets me:

```
uyuni:~ # spacewalk-repo-sync --channel debian-10-x64
09:47:22 ======================================
09:47:22 | Channel: debian-10-x64
09:47:22 ======================================
09:47:22 Sync of channel started.
09:47:26 Repo URL: http://ftp.at.debian.org/debian/dists/buster/main/binary-amd64/
09:47:26     Packages in repo:             56883
09:47:26     No new packages to sync.
09:47:26
09:47:26   Patches in repo: 0.
09:47:27 Repo URL: http://archive.ubuntu.com/ubuntu/dists/bionic/main/binary-amd64
09:47:27     Packages in repo:              6391
09:47:27     No new packages to sync.
09:47:27
09:47:27   Patches in repo: 0.
09:47:27 Sync completed.
09:47:27 Total time: 0:00:04
```

what am i doing wrong or is this considered as a new bug?

**Comment by Zappelphilipp** [comment]
i figured it out by myself. The channel-architecture needs to be changed (in reality in cant be changed, a new channel has to be made) from x86_64 to AMD64 Debian.  

feeling dumb now. I hope this helps anyone having the same issue.

**Comment by brekke-roq** [comment]
@Zappelphilipp thanks. What a nice trap it is  ....
