### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12 - venv-salt-minion - installation and registration get blocked by SELinux

### ISSUE THREAD

**Issue by lumarel** [uyuni-project/uyuni#4546]
# Additional Information

As we discussed in Gitter, there is the issue, that the package install uses `semanage` and `restorecon` in the post-install, but does not Require the applications to be installed.
This means if the `venv-salt-minion` package gets installed on a minimal system which doesn't have the `policycoreutils-python-utils` (for EL 8+, fedora 34+) or the policycoreutils-python (for EL 7) installed, it won't update the SELinux fcontexts even if it is enabled.

## Version of Uyuni Server and Proxy (if used)
```bash
# dnf info Uyuni-Server-release
Last metadata expiration check: 2:22:40 ago on Thu 09 Dec 2021 01:25:14 PM CET.
Installed Packages
Name         : Uyuni-Server-release
Version      : 2021.11
Release      : 161.3.uyuni1
Architecture : x86_64
Size         : 1.4 k
Source       : Uyuni-Server-release-2021.11-161.3.uyuni1.src.rpm
Repository   : @System
From repo    : @commandline
Summary      : Uyuni Server
```

## Details about issue
```bash
# dnf info venv-salt-minion
Last metadata expiration check: 0:15:08 ago on Thu 09 Dec 2021 03:14:15 PM CET.
Installed Packages
Name         : venv-salt-minion
Version      : 3002.2
Release      : 37.1.uyuni
Architecture : x86_64
Size         : 90 M
Source       : venv-salt-minion-3002.2-37.1.uyuni.src.rpm
Repository   : @System
From repo    : susemanager:bootstrap
Summary      : The venvjailed client component for Salt
```

The initial error where I noticed that the venv-salt-minion is unable to run while SELinux is enabled was this log message from the system log:
```
SELinux is preventing /usr/lib/venv-salt-minion/bin/python.original from name_connect access on the tcp_socket port 4506.
```

The best might be to add a conditional Requires to the package for EL 8 (and maybe fedora, didn't test there) so it installs the needed packages to being able to run the SELinux commands. (Could also be a check if SELinux is enabled and then install it if it is)

Another option would be to create a selinux policy package, which doesn't need any of these 2 tools. (should be the preferred option, I think, but takes a bit more time and knowledge about SELinux)

**Comment by lumarel** [comment]
@vzhestkov Sorry for pinging you, but this might be interesting for you, as we already talked about that in Gitter

**Comment by vzhestkov** [comment]
@lumarel , oh thanks. No problem. I will add the requirements to the spec for EL8+ and Fedora 34+

**Comment by lumarel** [comment]
Thank you very much! 👍🏻

**Comment by vzhestkov** [comment]
The fix is in https://build.opensuse.org/request/show/942087

**Comment by mcalmer** [comment]
I close this issue as it should be fixed
