### ISSUE TITLE
Uyuni Bugreport - Uyuni Master reposync fails with UnicodeEncodeError

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#4614]
# Additional Information

On AlmaLinux 8.
repo URL: http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os
(CentOS 7 base)

## Version of Uyuni Server and Proxy (if used)
Master code

## Details about issue

```
08:22:03   Package batch #382 of 480 completed...
08:22:03   Package batch #383 of 480 completed...
08:22:03   Package batch #384 of 480 completed...
08:22:03   Package batch #385 of 480 completed...
08:22:03   Package batch #386 of 480 completed...
packages/1/ffc/autogen/5.18-5.el7/x86_64/ffc02110cf6bd3a97180ae4c8ce7af9f261fa2d23a489a22ad09fb9902ede70e/autogen-5.18-5.el7.x86_64.rpm
packages/1/f03/compat-libcap1/1.10-7.el7/x86_64/f03a3843b53fc9eba490760caefdd79679b1043b67bfccc784e5d326395fc887/compat-libcap1-1.10-7.el7.x86_64.rpm
packages/1/275/expat-devel/2.1.0-12.el7/i686/275fe3cbc73d662f72c3244222c2329caa68e4aaf7d107ef009657dd06fb6e92/expat-devel-2.1.0-12.el7.i686.rpm
packages/1/745/compat-libcap1/1.10-7.el7/i686/7453914fde0bec5a7849548d54f0f922da541493b2e9f2e6a1be19f57956364b/compat-libcap1-1.10-7.el7.i686.rpm
packages/1/c73/expat/2.1.0-12.el7/x86_64/c73d74dee6c977bda30983111a290f054a8301797f32a20b550b4242679f057e/expat-2.1.0-12.el7.x86_64.rpm
08:22:03   Package batch #389 of 480 completed...
packages/1/18e/glib2-devel/2.56.1-7.el7/i686/18e10901a5adadad23b729b4ae13c28a6cc19e238237d69bc1bbd087aba4e5bf/glib2-devel-2.56.1-7.el7.i686.rpm
packages/1/6de/glib2/2.56.1-7.el7/x86_64/6dea72243379ae62c699ac7311cd5e8020d21bce162640046e8c4edc7bb270c3/glib2-2.56.1-7.el7.x86_64.rpm
packages/1/199/gtk2-devel-docs/2.24.31-1.el7/x86_64/19964d905f10899d0454ae9f1b5bb3efe69e2f331920b756ad10ab081cbb027f/gtk2-devel-docs-2.24.31-1.el7.x86_64.rpm
packages/1/0d5/gtk2-devel/2.24.31-1.el7/x86_64/0d5303d89e65fa5a6231ed9740f1aa64621bfeff5bdfec01ccc3588c5bc74553/gtk2-devel-2.24.31-1.el7.x86_64.rpm
packages/1/045/intltool/0.50.2-7.el7/noarch/0451aa0d15dda258f0e852888d618dac270718042a215f10f58d2999ec1194e5/intltool-0.50.2-7.el7.noarch.rpm
packages/1/458/iok/2.1.3-6.el7/x86_64/458f2b61c6f95964027ed7cff1e52a2b92949a5de234887058efc75a47686420/iok-2.1.3-6.el7.x86_64.rpm
packages/1/69b/kdepimlibs-kxmlrpcclient/4.10.5-4.el7/i686/69b2339a003256e48508d16902874b3e247d8f6cbb1f55239cb383ff22aab510/kdepimlibs-kxmlrpcclient-4.10.5-4.el7.i686.rpm
packages/1/a36/kdepimlibs-devel/4.10.5-4.el7/x86_64/a36a2a72fcb2335541220a75e09b9d74be7f877fb3475380cdf756e608426b15/kdepimlibs-devel-4.10.5-4.el7.x86_64.rpm
08:22:03   Package batch #390 of 480 completed...
08:22:03   Package batch #391 of 480 completed...
08:22:03   Package batch #392 of 480 completed...
08:22:03   Package batch #393 of 480 completed...
08:22:03   Package batch #394 of 480 completed...
08:22:03   Package batch #395 of 480 completed...
08:22:03 'utf-8' codec can't encode character '\udcf8' in position 19: surrogates not allowed
08:22:03   Package batch #396 of 480 completed...
08:22:03 'utf-8' codec can't encode character '\udcf8' in position 19: surrogates not allowed
08:22:03   Package batch #397 of 480 completed...
08:22:04   Package batch #398 of 480 completed...
08:22:04   Package batch #399 of 480 completed...
08:22:04 Unexpected error: <class 'UnicodeEncodeError'>
08:22:04 multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1293, in import_package_batch
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 777, in run
    self.fi)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 337, in fix
    self.backend.processChangeLog(self.changelog_data)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 171, in processChangeLog
    h.execute_values(sql, values, fetch=False)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 166, in execute_values
    return self._execute_wrapper(self._execute_values, sql, argslist, template, page_size, fetch)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
    retval = function(*p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 353, in _execute_values
    results = psycopg2.extras.execute_values(self._real_cursor, sql, argslist, template=template, page_size=page_size, fetch=fetch)
  File "/usr/lib64/python3.6/site-packages/psycopg2/extras.py", line 1267, in execute_values
    parts.append(cur.mogrify(template, args))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf8' in position 19: surrogates not allowed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 598, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1113, in import_packages
    affected_channels_batch, failed_packages_batch, all_packages, processed_batch = result.get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf8' in position 19: surrogates not allowed

08:22:04 Total time: 0:00:32
```

I think I was able to pin down the data to a changelog entry in the package:

`283, 'Than Ngo <than@redhat.com> - 4.10.5-1', datetime.datetime(2013, 6, 30, 14, 0), '- 4.10.5'), (284, 'Than Ngo <than@redhat.com> - 4.2.0-1', datetime.datetime(2009, 1, 22, 13, 0), '- 4.2.0\n- exclude kdepimlibs-apidocs from main pkg'), (285, 'Than Ngo <than@redhat.com> - 4.2.0-4', datetime.datetime(2009, 2, 18, 13, 0), '- enable akonadi subpkg'), (286, 'Than Ngo <than@redhat.com> - 4.2.1-1', datetime.datetime(2009, 2, 27, 13, 0), '- 4.2.1'), (287, 'Than Ngo <than@redhat.com> - 4.2.95-1', datetime.datetime(2009, 6, 25, 14, 0), '- 4.3 RC1'), (288, 'Than Ngo <than@redhat.com> - 4.2.95-2', datetime.datetime(2009, 6, 29, 14, 0), '- respin'), (289, 'Than Ngo <than@redhat.com> - 4.2.96-1', datetime.datetime(2009, 7, 11, 14, 0), '- 4.3rc2'), (290, 'Than Ngo <than@redhat.com> - 4.2.98-1', datetime.datetime(2009, 7, 22, 14, 0), '- 4.3rc3'), (291, 'Than Ngo <than@redhat.com> - 4.3.0-1', datetime.datetime(2009, 7, 30, 14, 0), '- 4.3.0'), (292, 'Than Ngo <than@redhat.com> - 4.3.1-1', datetime.datetime(2009, 8, 28, 14, 0), '- 4.3.1'), (293, 'Than Ngo <than@redhat.com> - 4.3.2-1', datetime.datetime(2009, 10, 5, 14, 0), '- 4.3.2'), (294, 'Than Ngo <than@redhat.com> - 4.3.3-2', datetime.datetime(2009, 11, 13, 13, 0), '- rhel cleanup, remove Fedora<=9 conditionals'), (295, 'Than Ngo <than@redhat.com> - 4.4.0-1', datetime.datetime(2010, 2, 5, 13, 0), '- 4.4.0'), (296, 'Than Ngo <than@redhat.com> - 4.5.0-1', datetime.datetime(2010, 8, 3, 14, 0), '- 4.5.0'), (297, 'Than Ngo <than@redhat.com> - 4.5.3-1', datetime.datetime(2010, 10, 31, 13, 0), '- 4.5.3'), (298, 'Than Ngo <than@redhat.com> - 4.6.90-1', datetime.datetime(2011, 6, 28, 14, 0), '- 4.6.90 (rc1)'), (299, 'Than Ngo <than@redhat.com> - 4.7.1-1', datetime.datetime(2011, 9, 2, 14, 0), '- 4.7.1'), (300, 'Than Ngo <than@redhat.com> - 4.9.1-1', datetime.datetime(2012, 9, 3, 14, 0), '- 4.9.1'), (301, 'Than Ngo <than@redhat.com> - 4.9.4-1', datetime.datetime(2012, 12, 3, 13, 0), '- 4.9.4'), (302, 'Than Ngo <than@redhat.com> 4.0.0-1', datetime.datetime(2008, 1, 7, 13, 0), '- 4.0.0'), (303, 'Than Ngo <than@redhat.com> 4.0.2-1', datetime.datetime(2008, 2, 28, 13, 0), '- 4.0.2'), (304, 'Than Ngo <than@redhat.com> 4.0.3-1', datetime.datetime(2008, 3, 28, 13, 0), '- 4.0.3\n- -apidocs: Drop Requires: %name\n- include noarch build hooks (not enabled)'), (305, 'Than Ngo <than@redhat.com> 4.0.80-1', datetime.datetime(2008, 5, 26, 14, 0), '- 4.1 beta1'), (306, 'Than Ngo <than@redhat.com> 4.0.83-1', datetime.datetime(2008, 6, 19, 14, 0), '- 4.0.83 (beta2)'), (307, 'Than Ngo <than@redhat.com> 4.0.83-2', datetime.datetime(2008, 6, 24, 14, 0), '- respun'), (308, 'Than Ngo <than@redhat.com> 4.1.0-1', datetime.datetime(2008, 7, 23, 14, 0), '- 4.1.0'), (309, 'Than Ngo <than@redhat.com> 4.1.1-1', datetime.datetime(2008, 8, 28, 14, 0), '- 4.1.1'), (310, 'Than Ngo <than@redhat.com> 4.1.3-1', datetime.datetime(2008, 11, 12, 13, 0), '- 4.1.3'), (311, 'Than Ngo <than@redhat.com> 4.1.80-2', datetime.datetime(2008, 11, 20, 13, 0), '- merged'), (312, 'Than Ngo <than@redhat.com> 4.2.85-1', datetime.datetime(2009, 5, 11, 14, 0), '- 4.2.85'), (313, 'Thomas Janssen <thomasj@fedoraproject.org> 4.5.85-1', datetime.datetime(2010, 12, 4, 13, 0), '- 4.5.85 (4.6beta2)'), (314, 'Thomas Janssen <thomasj@fedoraproject.org> 4.5.85-2', datetime.datetime(2010, 12, 8, 13, 0), '- respun upstream tarball'), (315, 'Tim Powers <timp@redhat.com>', datetime.datetime(2002, 5, 23, 14, 0), '- automated rebuild'), (316, 'Tim Powers <timp@redhat.com>', datetime.datetime(2002, 6, 21, 14, 0), '- automated rebuild'), (317, 'Tim Powers <timp@redhat.com>', datetime.datetime(2003, 1, 22, 13, 0), '- rebuilt'), (318, 'Tomas Mraz <tmraz@redhat.com> - 4.9.1-4', datetime.datetime(2012, 9, 26, 14, 0), '- drop libgpgme++-pth.so.2 as gpgme does not ship the pth-linked library\n  anymore'), (319, 'Trond Eivind Glomsrød <teg@redhat.com>', datetime.datetime(2002, 3, 13, 13, 0), '- 1.95.2'), (320, 'Trond Eivind Glomsrød <teg@redhat.com>', datetime.datetime(2002, 3, 22, 13, 0), '- Change a prereq in -devel on main package to a req\n- License from MIT/X11 to BSD'), (321, 'Trond Eivind Glomsrød <teg@redhat.com> 1,95.3-1', datetime.datetime(2002, 6, 6, 14, 0), '- 1.95.3'), (322, 'Trond Eivind Glomsrød <teg@redhat.com> 1,95.4-1', datetime.datetime(2002, 8, 19, 14, 0), '- 1.95.4. 1.95.3 was withdrawn by the expat developers.'), (323, 'Trond Eivind Glomsr\udcf8d <teg@redhat.com>', datetime.datetime(2001, 6, 20, 14, 0), '- Rebuild - it was missing for alpha'), 
(324, 'Trond Eivind Glomsr\udcf8d <teg@redhat.com>', datetime.datetime(2001, 7, 16, 14, 0), '- Add post,postun scripts'), (325, 'Ville Skyttä <ville.skytta@iki.fi> - 5.9.4-7', datetime.datetime(2009, 8, 10, 14, 0), '- Use bzipped upstream tarball.')]`

Entry 324 near the end contains `\udcf8d` which is the character in the error message (should be an `ø`).  (variable `argslist` at  file "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 353, in _execute_values).

I don't know if Leap shows the same behaviour. This is on AlmaLinux using yum_dnf_src.py. So this might be a specific issue.

**Comment by sbluhm** [comment]
Just found this somewhere on the internet:

> The definition of UTF-8 prohibits encoding character numbers between U+D800 and U+DFFF, which are reserved for use with the UTF-16 encoding form (as surrogate pairs) and do not directly represent characters. When encoding in UTF-8 from UTF-16 data, it is necessary to first decode the UTF-16 data to obtain character numbers, which are then encoded in UTF-8 as described above.

So not sure for now on how to best go about it...

**Comment by sbluhm** [comment]
I do see correct entries in the log file using the ø. This seems to be a conditional issue. Sometimes the ø get's inserted (and maybe not replaced to the unicode format)? As seen in table `rhnpackagechangelogdata`

**Comment by sbluhm** [comment]
After adding `.replace("\udcf8", "o")` to `key[0]` at https://github.com/uyuni-project/uyuni/blob/af1378e64418e68d62311d48ac08374d8cc664a7/backend/server/importlib/backend.py#L169 I get an interesting new error. Not sure if it is related:
```

18:58:33   Package batch #385 of 480 completed...
18:58:33   Package batch #386 of 480 completed...
18:58:33   Package batch #387 of 480 completed...
18:58:36 null value in column "changelog_data_id" of relation "rhnpackagechangelogrec" violates not-null constraint
DETAIL:  Failing row contains (1943954, 17105, null, 2021-12-23 16:58:35.045586-01, 2021-12-23 16:58:35.045586-01).

18:58:36 null value in column "changelog_data_id" of relation "rhnpackagechangelogrec" violates not-null constraint
DETAIL:  Failing row contains (1944009, 17107, null, 2021-12-23 16:58:35.452933-01, 2021-12-23 16:58:35.452933-01).

18:58:36 Unexpected error: <class 'psycopg2.errors.NotNullViolation'>
18:58:36 multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1292, in import_package_batch
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 778, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 359, in submit
    transactional=self.transactional)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 991, in processPackages
    transactional=transactional)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2322, in __processObjectCollection__
    return self.__doDML(dml)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2427, in __doDML
    self.__doInsert(dml.insert, dml.tables)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2434, in __doInsert
    self.__doInsertTable(tname, dict)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2449, in __doInsertTable
    insertObj.query(hash)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backendLib.py", line 453, in query
    statement.execute_values(self._buildQuery(None), value_list, fetch=False, page_size=10_000)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 166, in execute_values
    return self._execute_wrapper(self._execute_values, sql, argslist, template, page_size, fetch)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 299, in _execute_wrapper
    retval = function(*p, **kw)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 353, in _execute_values
    results = psycopg2.extras.execute_values(self._real_cursor, sql, argslist, template=template, page_size=page_size, fetch=fetch)
  File "/usr/lib64/python3.6/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.NotNullViolation: null value in column "changelog_data_id" of relation "rhnpackagechangelogrec" violates not-null constraint
DETAIL:  Failing row contains (1943954, 17105, null, 2021-12-23 16:58:35.045586-01, 2021-12-23 16:58:35.045586-01).

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 598, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1113, in import_packages
    affected_channels_batch, failed_packages_batch, all_packages, processed_batch = result.get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
psycopg2.errors.NotNullViolation: null value in column "changelog_data_id" of relation "rhnpackagechangelogrec" violates not-null constraint
DETAIL:  Failing row contains (1943954, 17105, null, 2021-12-23 16:58:35.045586-01, 2021-12-23 16:58:35.045586-01).


18:58:36 Total time: 0:01:02

```

**Comment by sbluhm** [comment]
@vzhestkov

**Comment by vzhestkov** [comment]
@sbluhm do you know what pakage has this symobl in the changelog?

**Comment by sbluhm** [comment]
Must be one of the above few. Will check out in a bit

**Comment by vzhestkov** [comment]
I have a bit outdated test deployment of the Uyuni Master and it's not failing, but it's on the Leap. It could take some time to reproduce it.

**Comment by sbluhm** [comment]
If it does not show up on Leap, then it must by yum_dnf_src (not?) preprocessing the values the same. I am also looking at it as some Centos 7 packages seem to be ignored when reading the primary repo file. And maybe also the Null issue I posted above.

So I would say assign this ticket to me whilst I revisit what I have done two yrs ago on this (crazy how time passes).

**Comment by sbluhm** [comment]
> @sbluhm do you know what pakage has this symobl in the changelog?
compat-libcap1
Interestingly, rpmfind is also struggling with it.

expat-devel, expat
(for a start)

**Comment by vzhestkov** [comment]
Looks line it's synching different list of the packages on Leap as I didn't find any package with such changelog entries. But I suppose we can reproduce it with Uyuni on Leap anyway, but it's better to find out which package causing it.

**Comment by sbluhm** [comment]
Maybe it is skipping those change logs?
I am currently installing Leap 15.3 so I can compare.

Here more reproducible: set up a repo with:
Repo URL: http://ftp.agdsn.de/pub/mirrors/centos/7.9.2009/os/x86_64/
Filter: +compat-libcap1

It fails with the unicode issue. If you remove the character, (key[0].replace() around line 171 on backend.py) it will fail with the above null-constrain error

**Comment by vzhestkov** [comment]
I just made a PR not directly related, but fixing one issue with `CFG`: https://github.com/uyuni-project/uyuni/pull/4620

Will try with the repo from previous comment, but `expat` packages was synchronized with no issues

**Comment by vzhestkov** [comment]
And for fun I'm using `yum_dnf_src` on Leap, it seems working with slight modification of reposync and installing yum/dnf on the system.
```
14:07:08 ======================================
14:07:08 | Channel: test-unicode-chars
14:07:08 ======================================
14:07:08 Sync of channel started.
14:07:12 
14:07:12   Importing comps file a4e2b46586aa556c3b6f814dad5b16db5a669984d66b68e873586cd7c7253301-c7-x86_64-comps.xml.gz.
14:07:12   Renaming non-standard filename a4e2b46586aa556c3b6f814dad5b16db5a669984d66b68e873586cd7c7253301-c7-x86_64-comps.xml.gz to comps.xml.gz.
14:07:12 *** NOTE: Importing comps file for the channel 'test-unicode-chars'. Previous comps will be discarded.
WARNING:dnf:allow_vendor_change is disabled. This option is currently not supported for downgrade and distro-sync commands
14:07:13 Repo URL: http://ftp.agdsn.de/pub/mirrors/centos/7.9.2009/os/x86_64/
14:07:13     Packages in repo:             10072
14:07:13     Packages passed filter rules:     2
14:07:13     Packages already synced:          0
14:07:13     Packages to sync:                 2
14:07:13     New packages to download:         2
14:07:13   Downloading packages:
14:07:13 Downloading total 2 files from 1 queues.
14:07:13     1/2 : compat-libcap1-1.10-7.el7.i686.rpm
14:07:13     2/2 : compat-libcap1-1.10-7.el7.x86_64.rpm
14:07:14 
14:07:14   Importing packages to DB:
14:07:15   Package batch #1 of 1 completed...
14:07:15 
14:07:15   Linking packages to the channel.
14:07:15     2 packages linked
14:07:15 
14:07:15   Patches in repo: 0.
14:07:16   Regenerating bootstrap repositories.
Generating bootstrap repos for all available products which had changes.
Nothing to do.
14:07:16 Sync completed.
14:07:16 Total time: 0:00:08
```

**Comment by sbluhm** [comment]
ok, wanted to try the exact same thing (dnf on Leap). Did you get change logs as well?
Also what were the modifications? Wanted to address #804 at the same time...

**Comment by vzhestkov** [comment]
It was hacky, not a proper modificatio. I just removed isSUSE from the conditon in reposync where it adds dnf to yum in the plugin name.

**Comment by mcalmer** [comment]
Hint: a setup with sumaform disable changelog parsing and inserting into the DB. Moio added this to speedup reposync during tests. 
Check for an option in rhn.conf.

This could be the reason why @vzhestkov  cannot reproduce it

**Comment by sbluhm** [comment]
Thank you @mcalmer . I checked and the log is indeed there on Leap (and correct character).

Current observation on Leap 15.3 (zypper):
```
13:58:47 Repo URL: http://ftp.agdsn.de/pub/mirrors/centos/7.9.2009/os/x86_64/
13:58:47     Packages in repo:             10072
13:58:47     Packages passed filter rules:    23
```

On Alma:
```
14:26:13 Repo URL: http://ftp.agdsn.de/pub/mirrors/centos/7.9.2009/os/x86_64/
14:26:13     Packages in repo:              9597
14:26:13     Packages passed filter rules:    27

```
Interestingly using python3 directly:
```
import dnf
url="http://ftp.agdsn.de/pub/mirrors/centos/7.9.2009/os/x86_64/"
dnfbase = dnf.Base()
name="test"
repo = dnf.repo.Repo(name,dnfbase.conf)
repo.mirrorlist = url
repo.baseurl = [url]
 
dnfbase.repos.add(repo)
dnfbase.repos[repo.id].load()
dnfbase.fill_sack(load_system_repo=False)
print (len(dnfbase.sack))

```
returns 10072 on Alma.

So will try to fix yum_dnf_src first and see if I can find the unicode issue at the same time.

**Comment by vzhestkov** [comment]
@mcalmer I'm using test environment deployed manually, not with sumaform.

**Comment by sbluhm** [comment]
I was finally able to get a step closer to the issue on Leap (or at least get somewhat closer)
System Prep:
`curl http://ftp.agdsn.de/pub/mirrors/centos/7.9.2009/os/x86_64/Packages/compat-libcap1-1.10-7.el7.x86_64.rpm -o /tmp/compat-libcap1-1.10-7.el7.x86_64.rpm`
Test:
```
python3
import rpm
filename="/tmp/compat-libcap1-1.10-7.el7.x86_64.rpm"
f = open(filename, 'r')
file_desc = f.fileno()
SHARED_TS = rpm.ts()
SHARED_TS.setVSFlags(-1)
hdr=SHARED_TS.hdrFromFdno(file_desc)
print(hdr[1081])
```
**Results (slightly anonymised to avoid finger pointing):**
Leap
`b'Xxxxx Xxxxxx Xlomsr\xc3\xb8d <xxx@xxxxxx.com>'`

Alma
`'Xxxxx Xxxxxx Xlomsr\udcf8d <xxx@xxxxxx.com>'`

Even changing the file opening to f = open(filename, 'rb') the lines stay the same.

As a stream is being used in the Uyuni code (https://github.com/uyuni-project/uyuni/blob/5cd6a32213e003371434ff38f2f9bd4a0b184544/uyuni/common-libs/common/rhn_rpm.py#L349), I will try to trace it back even further so see how to influence this.

Any idea upfront?

**Comment by vzhestkov** [comment]
On first glance could be a difference in `rpm` python module.

**Comment by sbluhm** [comment]
I will open an rpm Bugzilla. `\udcf8` isn't even the correct unicode character.
In the meantime, I would add a `string = repr(string)` and an additional type check with try/error in the changelog part https://github.com/uyuni-project/uyuni/blob/5cd6a32213e003371434ff38f2f9bd4a0b184544/backend/server/importlib/headerSource.py#L505 as a workaround.

**Comment by sbluhm** [comment]
Bugzilla got closed as not a bug:

> > Additional info:
> > \udcf8 is not even a valid unicode character. Expected character in the end is "ø"
> 
> And therein lies the problem: the string in the header is not unicode to begin with, but some unknown encoding and there's no way for rpm to know which, so it's not possible to convert either.
> 
> Old rpm's may contain whatever arbitrary mix of encodings. Only packages with an explicit "encoding" tag can be assumed to be in that (always utf-8) encoding. In practise this means packages built with rpm >= 4.13.
> 
Panu Matilainen

So will keep my workaround above as the solution.

**Comment by sbluhm** [comment]
Update to the ticket:
The `Unexpected Error` during the "**Importing packages to DB**" phase as mentioned in the ticket description does not exist anymore (`'utf-8' codec can't encode character '\udcf8' in position 19: surrogates not allowed` still exists).

Instead now, the process is failing in the "**Linking packages to the channel.**" phase with the below unexpected error:
```
11:16:03   Package batch #501 of 504 completed...
11:16:04   Package batch #502 of 504 completed...
11:16:42   Package batch #503 of 504 completed...
11:16:50   Package batch #504 of 504 completed...
11:17:06 
11:17:06   Linking packages to the channel.
11:17:53 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
11:17:54 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 595, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1146, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 778, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2506, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'autocorr-sr', 'epoch': 1, 'version': '5.3.6.1', 'release': '24.el7', 'arch': 'noarch', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {178: 'centos7-x86_64'}, 'checksum_list': None, 'checksum': 'e5587b2933f5453072e7084d3437f9a68fcab73c333ce6d4c637de80c378b1d1', 'checksum_type': 'sha256', 'checksums': {'sha256': 'e5587b2933f5453072e7084d3437f9a68fcab73c333ce6d4c637de80c378b1d1'}, 'name_id': 6615, 'evr_id': 979, 'package_arch_id': 100, 'nevra_id': 8415, 'checksum_id': 738742}] in table rhnPackage

11:18:01 Total time: 2:26:05
```

**Comment by sbluhm** [comment]
Stack trace is probably due to continuing import despite batch failure: https://github.com/uyuni-project/uyuni/issues/4746
