### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12 "spacecmd system_upgradepackage" does not work  

### ISSUE THREAD

**Issue by marmau06** [uyuni-project/uyuni#4628]
# Additional Information

_The following information is very important in order to help us help you. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

2021.12

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help someone to reproduce the issue or understand it_

Hi all, moving from Spacewallk to Uyuni, I'm quite disappointed when meeting this situation..
With Spacewalk, we are used to submit server patching with spacecmd CLI command:

spacecmd system_upgradepackage  myserver.mydomain.com *

The schedule is created, server will be processed.

Today, with Uyuni we get this:

spacecmd system_upgradepackage  myserver.mydomain.com *
Start Time: 20211229T10:59:58

Install these packages [y/N]: y
ERROR: Failed to schedule myserver.mydomain.com
INFO: Scheduled 0 system(s)**

So no possibility to move to uyuni without changing our way of patching...

Detail: submitting the same patching using UI works perfectly, schedule is created and processed.

Other detail: submitting reboot operation with spacecmd works fine...

Thanks for your attention.

**Comment by mcalmer** [comment]
'*' is a bash wildcard character and is evaluated already on the bash. You need to escape or quote it. Try:

$> spacecmd system_upgradepackage myserver.mydomain.com '*'

**Comment by marmau06** [comment]
Hello, I tried these commands :

1009  2022-05-05 10:55:57 spacecmd system_upgradepackage  uyuni_client '*'
1010  2022-05-05 11:06:28 spacecmd system_upgradepackage  uyuni_client '\*'
1011  2022-05-05 11:06:58 spacecmd system_upgradepackage  uyuni_client \*

And all of them gave the same result :

vim-enhanced-8.0.1763-16.el8_5.13:2.x86_64
vim-minimal-8.0.1763-16.el8_5.13:2.x86_64
zlib-1.2.11-18.el8_5.x86_64

Start Time: 20220505T11:06:28

Upgrade these packages [y/N]: y
ERROR: Failed to schedule flxviuynprd1773.france.rexel
INFO: Scheduled 0 system(s)

**Comment by Fredouye** [comment]
Hi

same issue here, running Uyuni 2022.04 : 

```bash
uyuni:~ # spacecmd -y -- system_upgradepackage almalinux8-1 '*'
INFO: Connected to https://uyuni.home.lab/rpc/api as admin_TEST
almalinux8-1
------------
NetworkManager-1.32.10-5.el8_5:1.x86_64
NetworkManager-libnm-1.32.10-5.el8_5:1.x86_64
[...]
zlib-1.2.11-18.el8_5.x86_64

Start Time: 20220505T17:04:53
ERROR: Failed to schedule almalinux8-1
INFO: Scheduled 0 system(s)
```

/var/log/messages contains this error : 

```bash
2022-05-05T17:12:45.968093+02:00 uyuni server[70449]: 05-May-2022 17:12:45.965 WARNING [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] redstone.xmlrpc.XmlRpcDispatcher.writeError redstone.xmlrpc.XmlRpcFault: unhandled internal exception: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
```

**Comment by marmau06** [comment]
Hello, I tried these commands :

1009  2022-05-05 10:55:57 spacecmd system_upgradepackage  flxviuynprd1773.france.rexel '*'
1010  2022-05-05 11:06:28 spacecmd system_upgradepackage  flxviuynprd1773.france.rexel '\*'
1011  2022-05-05 11:06:58 spacecmd system_upgradepackage  flxviuynprd1773.france.rexel \*

And all of them gave the same result :

vim-enhanced-8.0.1763-16.el8_5.13:2.x86_64
vim-minimal-8.0.1763-16.el8_5.13:2.x86_64
zlib-1.2.11-18.el8_5.x86_64

Start Time: 20220505T11:06:28

Upgrade these packages [y/N]: y
ERROR: Failed to schedule flxviuynprd1773.france.rexel
INFO: Scheduled 0 system(s)

Cordialement,

Hervé PLANEIX
Opérations Management (DP02)
[sopra-steria]
449 route des Crêtes
Bâtiment les Genêts - BP 345
06906 Sophia Antipolis - France
Phone: +33 (0)4 89 87 64 04
***@***.*** - www.soprasteria.com<http://www.soprasteria.com/>

Le contenu de cet e-mail est susceptible d'être confidentiel, soumis au secret professionnel ou protégé par la loi. L'utilisation, la copie et la divulgation non autorisées d'une partie ou de l'intégralité de ce message sont susceptibles d'être illégales. Si vous avez reçu ce message par erreur, supprimez-le après avoir averti l'expéditeur. Les pièces jointes du présent e-mail ont fait l'objet d'un contrôle antivirus. Néanmoins, nous déclinons toute responsabilité concernant les dommages causés par d'éventuels virus.
Pensez à l'environnement avant d'imprimer.




C2 - Usage restreint



C2 - Usage restreint
De : Michael Calmer ***@***.***>
Envoyé : mercredi 4 mai 2022 16:22
À : uyuni-project/uyuni ***@***.***>
Cc : PLANEIX Herve ***@***.***>; Author ***@***.***>
Objet : Re: [uyuni-project/uyuni] Uyuni Bugreport - Uyuni 2021.12 "spacecmd system_upgradepackage" does not work (Issue #4628)


You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


'*' is a bash wildcard character and is evaluated already on the bash. You need to escape or quote it. Try:

$> spacecmd system_upgradepackage myserver.mydomain.com '*'

-

**Comment by juliogonzalez** [comment]
> Hello, I tried these commands : 1009 2022-05-05 10:55:57 spacecmd system_upgradepackage flxviuynprd1773.france.rexel '*' 1010 2022-05-05 11:06:28 spacecmd system_upgradepackage flxviuynprd1773.france.rexel '\*' 1011 2022-05-05 11:06:58 spacecmd system_upgradepackage flxviuynprd1773.france.rexel \* And all of them gave the same result : vim-enhanced-8.0.1763-16.el8_5.13:2.x86_64 vim-minimal-8.0.1763-16.el8_5.13:2.x86_64 zlib-1.2.11-18.el8_5.x86_64 Start Time: 20220505T11:06:28 Upgrade these packages [y/N]: y ERROR: Failed to schedule flxviuynprd1773.france.rexel INFO: Scheduled 0 system(s)

Do you also see
```
2022-05-05T17:12:45.968093+02:00 uyuni server[70449]: 05-May-2022 17:12:45.965 WARNING [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] redstone.xmlrpc.XmlRpcDispatcher.writeError redstone.xmlrpc.XmlRpcFault: unhandled internal exception: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
```
At `/var/log/messages` at the server, or any errors at `/var/log/rhn` at the server?
