### ISSUE TITLE
"Unexpected token ','" when trying to view a virtual hosts' guests

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#4664]
I’ve successfully added our five Vcentre hosts to Uyuni using the[ VHM guide](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/vhm-vmware.html) and this has resulted in a lot of interesting new information in several menus, letting me see on which hosts my registered vms live. All very exciting. 

But when I follow the guide to “[Create Virtual Guests](https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/client-configuration/virtualization.html)” and “navigate to Systems  Systems List, click the name of the virtualization host, and navigate to the Virtualization tab.” 

Example url: https://MY-FQDN/rhn/manager/systems/details/virtualization/guests/1000010299

I see an empty window instead of the General section the docs suggest I should see.  What I do is is the usual Uyuni navigation bar, and the top pane “hostname…” Tab bar “Details Virtualization” and a sub tab bar “Guests” and then nothing else whatsoever. 

When I refresh that page, then the following appears in _rhn/rhn_web_frontend.log_ 

```
022-01-12 14:53:32,496 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] ERROR com.suse.manager.webui.controllers.FrontendLogController - [1 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36] - Uncaught SyntaxError: Unexpected token ','
url: https://MY-FQDN/rhn/manager/systems/details/virtualization/guests/1000010299
line: 261
column: 25
error: SyntaxError: Unexpected token ','
2022-01-12 14:53:32,604 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] INFO  com.suse.manager.webui.controllers.FrontendLogController - [1 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36] - [Wed, 12 Jan 2022 14:53:32 GMT] - Loading `https://MY-FQDN/rhn/manager/systems/details/virtualization/guests/1000010299`
```

How can I progress this, please?

**Comment by cbosdo** [comment]
Fixed by https://github.com/uyuni-project/uyuni/pull/4809
