### ISSUE TITLE
Uyuni 2021.12 create bootstrap repo does not work

### ISSUE THREAD

**Issue by ifridemberg** [uyuni-project/uyuni#4686]
# Additional Information

_The following information is very important in order to help us help you. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.12-160.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.09-141.3.uyuni1 installed)
Source package : Uyuni-Server-release-2021.12-160.4.uyuni1.src
Summary        : Uyuni Server

## Details about the issue
After syncing the custom channels (centos 7/8, ubuntu 2004, red hat ), i have tried to create a bootstrap repo, but the command "mgr-create-bootstrap-repo -l"  isn't detected at distributions at all. 

In a previous version, this issue isn't present, could be the last version of the problem?

When i attempt to create a repo for 'centos7-x86_64-os'    manually i get the next output:
'centos7-x86_64-os' not found

Thanks  in advanced

.

**Comment by mcalmer** [comment]
@ifridemberg is the problem still reproducable in the latest uyuni version?

**Comment by ifridemberg** [comment]
sorry by not close this issue, the problem wasn't related with the version. 
It was necessary create the channels throught space command first from uyuni catalog. Then the bootstrap repo was able to created.

regards

**Comment by mcalmer** [comment]
Ok, so the channels were just created in a way that create bootstrap repo command could not identify it.
Closing. Thanks.
