### ISSUE TITLE
spacewalk-repo-sync - [Errno 28] No space left on device

### ISSUE THREAD

**Issue by umrubi1** [uyuni-project/uyuni#4697]
# Additional Information

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release`

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2021.12-160.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2021.12-160.4.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

`# rpm -qa|egrep -i "^spacewalk|^uyuni|^susemanager"|sort`
```
Uyuni-Server-release-2021.12-160.4.uyuni1.x86_64
spacewalk-admin-4.3.3-1.1.uyuni1.noarch
spacewalk-backend-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-app-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-applet-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-config-files-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-config-files-common-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-config-files-tool-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-iss-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-iss-export-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-package-push-server-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-server-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-sql-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-sql-postgresql-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-tools-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-xml-export-libs-4.3.6-1.1.uyuni1.noarch
spacewalk-backend-xmlrpc-4.3.6-1.1.uyuni1.noarch
spacewalk-base-4.3.6-1.4.uyuni1.noarch
spacewalk-base-minimal-4.3.6-1.4.uyuni1.noarch
spacewalk-base-minimal-config-4.3.6-1.4.uyuni1.noarch
spacewalk-branding-4.3.1-1.2.uyuni1.x86_64
spacewalk-certs-tools-4.3.3-1.1.uyuni1.noarch
spacewalk-client-tools-4.3.4-1.9.uyuni1.noarch
spacewalk-common-4.3.2-1.3.uyuni1.noarch
spacewalk-config-4.3.2-1.1.uyuni1.noarch
spacewalk-html-4.3.6-1.4.uyuni1.noarch
spacewalk-java-4.3.6-1.3.uyuni1.noarch
spacewalk-java-config-4.3.6-1.3.uyuni1.noarch
spacewalk-java-lib-4.3.6-1.3.uyuni1.noarch
spacewalk-java-postgresql-4.3.6-1.3.uyuni1.noarch
spacewalk-postgresql-4.3.2-1.3.uyuni1.noarch
spacewalk-reports-4.3.2-1.1.uyuni1.noarch
spacewalk-search-4.3.1-1.2.uyuni1.noarch
spacewalk-setup-4.3.4-1.1.uyuni1.noarch
spacewalk-setup-jabberd-4.3.1-1.2.uyuni1.noarch
spacewalk-taskomatic-4.3.6-1.3.uyuni1.noarch
spacewalk-utils-4.3.4-1.1.uyuni1.noarch
susemanager-4.3.6-1.1.uyuni1.x86_64
susemanager-frontend-libs-4.3.0-2.1.uyuni1.noarch
susemanager-schema-4.3.4-1.2.uyuni1.noarch
susemanager-sls-4.3.5-1.1.uyuni1.noarch
susemanager-sync-data-4.3.4-1.1.uyuni1.noarch
susemanager-tftpsync-4.3.1-1.2.uyuni1.x86_64
susemanager-tools-4.3.6-1.1.uyuni1.x86_64
susemanager-web-libs-4.3.6-1.4.uyuni1.noarch
uyuni-base-common-4.3.1-1.2.uyuni1.x86_64
uyuni-base-server-4.3.1-1.2.uyuni1.x86_64
uyuni-build-keys-2021.09-1.1.uyuni1.noarch
uyuni-build-keys-web-2021.09-1.1.uyuni1.noarch
uyuni-cluster-provider-caasp-4.3.1-1.2.uyuni1.noarch
uyuni-doc-indexes-2021.12-4.4.uyuni1.noarch
uyuni-docs_en-2021.12-3.1.uyuni1.noarch
uyuni-docs_en-pdf-2021.12-3.1.uyuni1.noarch
```

## Details about issue
I have created repositories for Ubuntu 20.04 and have a sync schedule. There are two large packages, where it is not possible to sync. Every time I got the message, there is not enough space.

`/var/log/rhn/reposync/ubuntu-2004-amd64-universe-uyuni.log`
```
  2022/01/17 21:54:09 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'ubuntu-2004-amd64-universe-uyuni', '--type', 'deb']
  2022/01/17 21:54:09 +02:00 Sync of channel started.
  2022/01/17 21:54:13 +02:00 Repo URL: http://archive.ubuntu.com/ubuntu/dists/focal/universe/binary-amd64/
  2022/01/17 21:54:13 +02:00     Packages in repo:             53206
  2022/01/17 21:57:38 +02:00     Packages already synced:      53204
  2022/01/17 21:57:38 +02:00     Packages to sync:                 2
  2022/01/17 21:57:38 +02:00     New packages to download:         2
  2022/01/17 21:57:38 +02:00   Downloading packages:
  2022/01/17 21:58:07 +02:00     1/2 : flightgear-data-base_2019.1.1+dfsg-1_all.deb
  2022/01/17 21:58:28 +02:00     2/2 : qgis-api-doc_3.10.4+dfsg-1ubuntu2_all.deb
  2022/01/17 21:58:28 +02:00 Importing packages started.
  2022/01/17 21:58:28 +02:00
  2022/01/17 21:58:28 +02:00   Importing packages to DB:
  2022/01/17 21:58:31 +02:00 [Errno 28] No space left on device
  2022/01/17 21:58:35 +02:00 [Errno 28] No space left on device
  2022/01/17 21:58:36 +02:00   Package batch #1 of 1 completed...
  2022/01/17 21:58:36 +02:00 Importing packages finished.
  2022/01/17 21:58:36 +02:00
  2022/01/17 21:58:36 +02:00   Patches in repo: 0.
```
Unfortunately I am unable to determine, where is no space left on the device?!
```
# df -h /var/log /var/spacewalk /var/lib/pgsql
Filesystem                        Size  Used Avail Use% Mounted on
/dev/mapper/vg_system-lv_log      2.9G  196M  2.6G   8% /var/log
/dev/mapper/vg_data-lv_spacewalk  492G  410G   79G  84% /var/spacewalk
/dev/mapper/vg_db-lv_pgsql         69G   30G   36G  47% /var/lib/pgsql

# df -i /var/log /var/spacewalk /var/lib/pgsql
Filesystem                         Inodes  IUsed    IFree IUse% Mounted on
/dev/mapper/vg_system-lv_log       196608   1184   195424    1% /var/log
/dev/mapper/vg_data-lv_spacewalk 32768000 949452 31818548    3% /var/spacewalk
/dev/mapper/vg_db-lv_pgsql        4587520   8155  4579365    1% /var/lib/pgsql
```
_Note:_ The same packages are also available for OpenSUSE Leap 15.3 and were successfully imported to our Uyuni server.

Thanks in advanced and regards

**Comment by meaksh** [comment]
Hi @umrubi1,
during a `spacewalk-repo-sync` execution most of the required disk space is used at `/var/spacewalk/` (for the RPM files) and then `/var/lib/pgsql` where all DB metadata is stored.

This `[Errno 28] No space left on device` is raised when OS cannot write the filesystem returning `ENOSPC`. This error is coming from the OS, I guess you should be also able to reproduce it even without reposync.

IMHO this sounds like some issue with one of the underlying LVM volume, even if `df -h`  and `df -i` show that there is disk space and inodes available, there might be some issue in those volumes. For example, if there is no more physical space for your logical vollumes.

I would recommend to review the LVM setup and volumes.

Hth!

**Comment by umrubi1** [comment]
Hi,

thanks for the reply. I will check it. I wouldn't have thought of that.

Regards

**Comment by umrubi1** [comment]
### Update
I obviously found _my_ issue. After checking few stuff, it turns out, that my `/tmp` was to small. I had to extend it from 1GB to 3GB. I have seen, that for the step "`Importing packages to DB`" for a very short time (approx 4 seconds) large temporally files were generated. The `[Errno 28]` was generated, as the process had not the necessary space in `/tmp`. After my change, the sync process finished without issues.

Maybe this info is useful for someone.

**Comment by sbluhm** [comment]
@umrubi1 that is a nice issue. If noone takes it, I might have a go and see if we can elaborate the message to the location.

Silly question: How come that a `df -h`didn't pinpoint straight away to `/tmp` by showing 99/100%? Was the space released again after termination?

**Comment by sbluhm** [comment]
I just tried to unsuccessfully reproduce the issue:
1. create a 1 GB /tmp folder.
2. Modify reposync.py to wait 1 min after the message `Importing packages to DB`
3. `/usr/bin/spacewalk-repo-sync --channel almalinux8-aarch64 --type yum --non-interactive`
4. On the message of 2. above, I fill the tmp folder with `cat /dev/zero > /tmp/file`
5. reposync continues after that message. Below is the error I get on Leap. Alma is different but also not what you got.
```
10:34:28     1533/1534 : zsh-5.5.1-6.el8_1.2.aarch64.rpm
10:35:09     1534/1534 : linux-firmware-20210702-103.gitd79c2677.el8.noarch.rpm
10:35:10 
10:35:10   Importing packages to DB:
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
10:35:40 descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
```
As I can't reproduce. I would not follow any further with a fix for a more descriptive error message.

**Comment by umrubi1** [comment]
The `/tmp` was only full for a very short time. I only saw it by using `watch -n 5 df -h /var/lib/pgsql /var/spacewalk /var/cache` to see what happens during a reposync. I had different sessions open in parallel (also with htop and iotop). 
I had this issue only with two large files. If you want to reproduce it, you could try to sync Ubuntu channels where the packages  "flightgear-data-base" and "qgis-api-doc" are in it. 

Repo URL: http://archive.ubuntu.com/ubuntu/dists/focal/universe/binary-amd64/

`flightgear-data-base_2019.1.1+dfsg-1_all.deb` -> 1.1 GB
`qgis-api-doc_3.10.4+dfsg-1ubuntu2_all.deb `-> 1.0GB 

Newer versions are even larger (approx. 1.6 GB). Maybe your packages from almalinux8 are to small for reproducing it? Haven't check the files there.

**Comment by sbluhm** [comment]
Ah, Ubuntu uses a different plugin. Will give it one more shot later.

**Comment by sbluhm** [comment]
I tried on a SUSE Leap system with "your" repo and had no luck. Maybe it was my test case of mapping a 1GB file as /tmp. This is not where it stopped. So am giving up on that for definite now. Was worth a try.

**Comment by umrubi1** [comment]
Ok thanks for testing. For me it was the solution. I will close this thread. At least it is documented for other users.

**Comment by hsh-it** [comment]
I ran into the same issue with `spacewalk-repo-sync` on Uyuni while syncing Ubuntu 22.04 repositories, especially `universe`.

In my case the host still had plenty of disk space available, but inside the Uyuni container `/tmp` was mounted as tmpfs and filled up during the package import phase:

```bash
mgrctl exec -- df -hT /tmp
# tmpfs  7.9G  7.8G  49M  100% /tmp
```

After restarting the container, `/tmp` was empty again. As an alternative to increasing `/tmp`, I used a larger temporary directory on persistent/overlay storage and exported `TMPDIR` before running `spacewalk-repo-sync`:

```bash
mgrctl exec -- mkdir -p /var/tmp/uyuni-reposync-tmp
mgrctl exec -- chmod 1777 /var/tmp/uyuni-reposync-tmp

mgrctl exec -- bash -lc '
export TMPDIR=/var/tmp/uyuni-reposync-tmp
spacewalk-repo-sync --channel ubuntu-2204-amd64-universe-uyuni --type deb --non-interactive
'
```

This kept `/tmp` almost empty while the sync was running:

```bash
/tmp                         tmpfs    7.9G  100K  7.9G   1%
/var/tmp/uyuni-reposync-tmp  overlay  2.0T  580G  1.5T  29%
```

So another possible workaround is not only to increase `/tmp`, but to explicitly set `TMPDIR` to a location with enough space before running `spacewalk-repo-sync`.
