### ISSUE TITLE
Update golang-github-wrouesnel-postgres_exporter

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#4721]
golang-github-wrouesnel-postgres_exporter is still on 0.4.7 in the Uyuni Master OBS repository and is from 11 Nov 2018.

The request is to update the package to 0.10.1.

**Comment by sbluhm** [comment]
Is there a reason for for this older version or can I try to provide this?

**Comment by mcalmer** [comment]
If i remember correctly we had problems to get it build on redhat 😁

**Comment by mcalmer** [comment]
See https://build.opensuse.org/package/show/home:mseidl81:branches:server:monitoring/golang-github-wrouesnel-postgres_exporter

**Comment by sbluhm** [comment]
> If i remember correctly we had problems to get it build on redhat

If that is the only reason....(not sure if it works but its green :) )

https://build.opensuse.org/package/show/home:sbluhm:branches:systemsmanagement:Uyuni:Master/golang-github-prometheus-postgres_exporter
