### ISSUE TITLE
Uyuni Bugreport - Uyuni 2022.01 - Error adding Debian 11 Salt repo using spacewalk-common-channels CLI

### ISSUE THREAD

**Issue by Fredouye** [uyuni-project/uyuni#4748]
# Additional Information

Error when adding Debian 11 Uyuni client repo with spacewalk-common-channels.

## Version of Uyuni Server and Proxy (if used)
```Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.01-165.2.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.12-160.4.uyuni1 installed)
Source package : Uyuni-Server-release-2022.01-165.2.uyuni1.src
Summary        : Uyuni Server
```

## Details about issue

On a Uyuni server where Debian 9 and 10 repos are already defined, I get a duplicate channel name when adding Debian 11 repos : 

```uyuni:~ # spacewalk-common-channels -a amd64-deb debian-11-pool-amd64-uyuni debian-11-amd64-main-security-uyuni debian-11-amd64-main-updates-uyuni debian-11-amd64-uyuni-client -u admin
SUSE Manager password: 
WARNING: debian-11-amd64-uyuni-client: redstone.xmlrpc.XmlRpcFault: The channel name 'Uyuni Client Tools for Debian 10 Buster AMD64' is already in use, please enter a different name
```

Error seems to be located in https://github.com/uyuni-project/uyuni/blob/bb626b248bf2f1d8453884abbbfdd8660428cc49/utils/spacewalk-common-channels.ini, line 2778 ("name = Uyuni Client Tools for Debian 10 Buster AMD64") :

```[debian-11-amd64-uyuni-client]
label    = debian-11-amd64-uyuni-client
name     = Uyuni Client Tools for Debian 10 Buster AMD64
archs    = amd64-deb
repo_type = deb
checksum = sha256
base_channels = debian-11-pool-amd64-uyuni
repo_url = https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Debian11-Uyuni-Client-Tools/Debian_11/
```

**Comment by mbussolotto** [comment]
Same issue reported here: https://github.com/uyuni-project/uyuni/issues/4755

**Comment by juliogonzalez** [comment]
I think this is fixed https://github.com/uyuni-project/uyuni/pull/5262 ?

**Comment by juliogonzalez** [comment]
Closing this one, as https://github.com/uyuni-project/uyuni/issues/4755 was marked as fixed as well.

@Fredouye feel free to reopen if you can reproduce with the latest Uyuni version.
