### ISSUE TITLE
Remote command target directory configuration on salt clients

### ISSUE THREAD

**Issue by jpgrazi** [uyuni-project/uyuni#4775]
# Question
client agent and OS: Uyuni salt-minion on Linux Centos7.

The remote commands feature, in uyuni, allows running a script by mean of the salt agent in clients. The script is copied to /tmp directory on the client and run from there.  As a hardening measure, our /tmp directories on clients are mounted with noexec option, so no script will run from that directory.  Does uyuni have a way to copy and run the remote command (script) to a different directory? I mean, is an option to configure a different target directory for to copy the script in salt clients?

**Comment by vzhestkov** [comment]
Hi @jpgrazi , here is the solution https://www.suse.com/support/kb/doc/?id=000019376

**Comment by meaksh** [comment]
I'm closing this as solution has been provided. Feel free to reopen if necessary. Thanks!
