### ISSUE TITLE
Uyuni Bugreport - Uyuni 2022.01 (Ubuntu Repo Mirror Erros)

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#4856]
# Additional Information

_The following information is very important in order to help us help you. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.01-165.2.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.01-165.2.uyuni1.src
Summary        : Uyuni Server

## Details about issue
_Include as many details as you can. The procedure you are following,  the commands you are running, logs (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help someone to reproduce the issue or understand it_

We want to mirror this ppa: https://launchpad.net/~ansible/+archive/ubuntu/ansible?field.series_filter=focal
So we setup this URL to mirror the deb Packages: https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/dists/focal/main/binary-amd64/
Mirroring is successful: 
   ```
 spacewalk-repo-sync -c ansible-ubuntu2004-amd64 -vv
    10:30:54 ======================================
    10:30:54 | Channel: ansible-ubuntu2004-amd64
    10:30:54 ======================================
    10:30:54 Sync of channel started.
    10:30:55 Repo URL: https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/dists/focal/main/binary-amd64/
    10:30:55     Packages in repo:                 4
    10:30:55     Packages already synced:          0
    10:30:55     Packages to sync:                 4
    10:30:55     New packages to download:         4
    10:30:55   Downloading packages:
    10:30:55 Downloading total 4 files from 1 queues.
    10:30:55 Downloading 4 files from queue #0.
    10:30:55     1/4 : ansible-test_2.12.2-1ppa~focal_all.deb
    10:30:55     2/4 : python3-resolvelib_0.5.4-2ppa~focal_all.deb
    10:30:55     3/4 : ansible-core_2.12.2-1ppa~focal_all.deb
    10:30:57     4/4 : ansible_5.3.0-1ppa~focal_all.deb
    10:30:57
    10:30:57   Importing packages to DB:
    10:31:12   Package batch #1 of 1 completed...
    10:31:12
    10:31:12   Linking packages to the channel.
    10:31:12     4 packages linked
    10:31:13
    10:31:13   Patches in repo: 0.
    10:31:13 Sync completed.
    10:31:13 Total time: 0:00:18

```
But we cant publish that channel to a Ubuntu client:

```
Err:33 https://xxxx:443/rhn/manager/download ansible-ubuntu2004-amd64/ Packages
  404  404 [IP: xxxxx 443]
Ign:34 https://xxxxx:443/rhn/manager/download ansible-ubuntu2004-amd64/ Translation-en
Reading package lists...
2022-02-17 10:46:20,340 [salt.loaded.int.module.cmdmod:848 ][ERROR   ][51193] stderr: W: Skipping acquire of configured file 'Packages' as repository 'https://xxxx:443/rhn/manager/download ubuntu-2004-amd64-universe-uyuni/ InRelease' does not seem to provide it (sources.list entry misspelt?)
E: Failed to fetch https://xxxx:443/rhn/manager/download/ansible-ubuntu2004-amd64/Packages  404  404 [IP: xxxxx 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
2022-02-17 10:46:20,340 [salt.loaded.int.module.cmdmod:850 ][ERROR   ][51193] retcode: 100
2022-02-17 10:46:20,341 [salt.state       :322 ][ERROR   ][51193] An error was encountered while checking the newest available version of package(s): W: Skipping acquire of configured file 'Packages' as repository 'https://xxxxx:443/rhn/manager/download ubuntu-2004-amd64-universe-uyuni/ InRelease' does not seem to provide it (sources.list entry misspelt?)
E: Failed to fetch https://xxxx:443/rhn/manager/download/ansible-ubuntu2004-amd64/Packages  404  404 [IP: xxxx 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Do we anything wrong in the setup?

Regards

**Comment by mrstigmata** [comment]
the same Problem with:

Repo URL: https://cloud.r-project.org/bin/linux/ubuntu/focal-cran40

Sync Log:

2022/03/11 10:20:07 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'external-rbase40-ubuntu20', '--type', 'deb', '--non-interactive']
2022/03/11 10:20:07 +02:00 Sync of channel started.
2022/03/11 10:20:09 +02:00 Repo URL: https://cloud.r-project.org/bin/linux/ubuntu/focal-cran40
2022/03/11 10:20:09 +02:00     Packages in repo:               188
2022/03/11 10:20:09 +02:00     Packages already synced:          0
2022/03/11 10:20:09 +02:00     Packages to sync:               188
2022/03/11 10:20:09 +02:00     New packages to download:       188
2022/03/11 10:20:09 +02:00   Downloading packages:
2022/03/11 10:20:09 +02:00 ERROR: Download failed: https://cloud.r-project.org/bin/linux/ubuntu/focal-cran40/focal-cran40/elpa-ess_18.10.2-2focal0_all.deb - [Errno 14] HTTPS Error 404 - Not Found.
2022/03/11 10:20:09 +02:00     1/188 : elpa-ess_18.10.2-2focal0_all.deb (failed)
2022/03/11 10:20:09 +02:00 ERROR: Download failed: https://cloud.r-project.org/bin/linux/ubuntu/focal-cran40/focal-cran40/littler_0.3.13-1.2004.0_all.deb - [Errno 14] HTTPS Error 404 - Not Found.
2022/03/11 10:20:09 +02:00     2/188 : littler_0.3.13-1.2004.0_all.deb (failed)

The created Repo URL is wrong:
 https://cloud.r-project.org/bin/linux/ubuntu/focal-cran40/focal-cran40
should be:
 https://cloud.r-project.org/bin/linux/ubuntu/focal-cran40/

If I changed the Repo URL to  https://cloud.r-project.org/bin/linux/ubuntu/ I got this:
2022/03/11 10:20:54 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'external-rbase40-ubuntu20', '--type', 'deb', '--non-interactive']
2022/03/11 10:20:54 +02:00 Sync of channel started.
2022/03/11 10:20:55 +02:00 Repo URL: https://cloud.r-project.org/bin/linux/ubuntu/
2022/03/11 10:20:55 +02:00     Packages in repo:                 0
2022/03/11 10:20:55 +02:00     No new packages to sync.
2022/03/11 10:20:55 +02:00 
2022/03/11 10:20:55 +02:00   Patches in repo: 0.
2022/03/11 10:20:55 +02:00 Sync completed.

this behavior is a big problem because we can't mirror this kind Ubuntu repos... any fix or workaround available?

**Comment by mrstigmata** [comment]
are there any solutions for that behavior?

**Comment by vzhestkov** [comment]
@mrstigmata, could you please show the content of `/etc/apt/sources.list.d/susemanager:channels.list` from the affected client system?

The problem with https://cloud.r-project.org/bin/linux/ubuntu/focal-cran40 is the different one. Try to specufy the repo URL in the repo definition with the syntax eplained in this document:
https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/custom-channels.html
Using `uyuni_suite` and `uyuni_suite`.

There is an exaple for https://pkg.jenkins.io/debian-stable repo in the document.

**Comment by mrstigmata** [comment]
@vzhestkov thx! I didn't see that new part at the documentation. perfect it works now!!

**Comment by vzhestkov** [comment]
@mrstigmata but what's with the issue described in the first message of this issue? It looks different to me as I see reposync works for it, but some issues with publishing the synchronized repo to the client. Do you have this issue still?

**Comment by mrstigmata** [comment]
@vzhestkov I use that URL: https://ppa.launchpadcontent.net/ansible/ansible/ubuntu?uyuni_suite=focal&uyuni_component=main

**Comment by zaybon** [comment]
> I mean in the inital description of the issue you show the proper sync log with actually successful synchronisation, but then pointed that the Ubuntu client was not able to get data from the repo published by Uyuni. Is it working now?

I am having the same problem with the missing "Packages" files.

Err:3 https://uyuni.something.com:443/rhn/manager/download ubuntu-2004-amd64-main-uyuni/ Packages
  404  404 [IP: 10.124.4.100 443]
Ign:4 https://uyuni.something.com:443/rhn/manager/download ubuntu-2004-amd64-main-uyuni/ Translation-en_US
Ign:5 https://uyuni.something.com:443/rhn/manager/download ubuntu-2004-amd64-main-uyuni/ Translation-en
Reading package lists... Done
E: Failed to fetch https://uyuni.something.com:443/rhn/manager/download/ubuntu-2004-amd64-main-uyuni/Packages  404  404 [IP: 10.124.4.100 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.

Is there anything I can check why this is not working anymore?

**Comment by zaybon** [comment]
The contents of /etc/apt/sources.list.d/susemanager:channels.list is:

# Channels managed by SUSE Manager
# Do not edit this file, changes will be overwritten
#

deb [trusted=yes] https://uyuni.something.com:443/rhn/manager/download ubuntu-20.04-pool-amd64-uyuni/


deb [trusted=yes] https://uyuni.something.com:443/rhn/manager/download ubuntu-2004-amd64-main-uyuni/

**Comment by mrstigmata** [comment]
> > I mean in the inital description of the issue you show the proper sync log with actually successful synchronisation, but then pointed that the Ubuntu client was not able to get data from the repo published by Uyuni. Is it working now?
> 
> I am having the same problem with the missing "Packages" files.
> 
> ```
> Err:5 https://uyuni.something.com:443/rhn/manager/download ubuntu-20.04-pool-amd64-uyuni/ Packages
>   404  404 [IP: 10.124.4.100 443]
> Ign:6 https://uyuni.something.com:443/rhn/manager/download ubuntu-20.04-pool-amd64-uyuni/ Translation-en_US
> Ign:7 https://uyuni.something.comm:443/rhn/manager/download ubuntu-20.04-pool-amd64-uyuni/ Translation-en
> Err:8 https://uyuni.something.com:443/rhn/manager/download ubuntu-2004-amd64-main-uyuni/ Packages
>   404  404 [IP: 10.124.4.100 443]
> Ign:9 https://uyuni.something.com:443/rhn/manager/download ubuntu-2004-amd64-main-uyuni/ Translation-en_US
> Ign:10 https://uyuni.something.com:443/rhn/manager/download ubuntu-2004-amd64-main-uyuni/ Translation-en
> Reading package lists... Done
> E: Failed to fetch https://uyuni.something.com:443/rhn/manager/download/ubuntu-20.04-pool-amd64-uyuni/Packages  404  404 [IP: 10.124.4.100 443]
> E: Failed to fetch https://uyuni.something.com:443/rhn/manager/download/ubuntu-2004-amd64-main-uyuni/Packages  404  404 [IP: 10.124.4.100 443]
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ```
> 
> Is there anything I can check why this is not working anymore?

Hello @vzhestkov - it is working now! We run the latest Uyuni-Build and changed the repo url to https://ppa.launchpadcontent.net/ansible/ansible/ubuntu?uyuni_suite=focal&uyuni_component=main

we can close this ticket.

**Comment by vzhestkov** [comment]
Thanks for letting know :+1:

**Comment by Ripper66Six** [comment]
ubuntu20.04 focal-backports

We have the same problem on Ubuntu Archive Repositories

Command '[/usr/bin/spacewalk-repo-sync, --channel, external-ubuntu20.04-focal-backports, --type, yum, --non-interactive]' exited with error code 1: ... the above error.
Could not refresh the repositories because of errors.

Retrieving repository 'external-ubuntu20.04-focal-backports' metadata [.error]
02:26:50 RepoMDError: Cannot access repository.
Repository 'external-ubuntu20.04-focal-backports' is invalid.
[external-ubuntu20.04-focal-backports|http://archive.ubuntu.com/ubuntu/dists/focal-backports/main/] Valid metadata not found at specified URL
History:
- [external-ubuntu20.04-focal-backports|http://archive.ubuntu.com/ubuntu/dists/focal-backports/main/] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'external-ubuntu20.04-focal-backports' because of the above error.
Could not refresh the repositories because of errors.

Retrieving repository 'external-ubuntu20.04-focal-backports' metadata [.error]
02:26:51 RepoMDError: Cannot access repository.
Repository 'external-ubuntu20.04-focal-backports' is invalid.
[external-ubuntu20.04-focal-backports|http://archive.ubuntu.com/ubuntu/dists/focal-backports/restricted/] Valid metadata not found at specified URL
History:
- [external-ubuntu20.04-focal-backports|http://archive.ubuntu.com/ubuntu/dists/focal-backports/restricted/] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'external-ubuntu20.04-focal-backports' because of the above error.
Could not refresh the repositories because of errors.

Retrieving repository 'external-ubuntu20.04-focal-backports' metadata [.error]
02:26:52 RepoMDError: Cannot access repository.
Repository 'external-ubuntu20.04-focal-backports' is invalid.
[external-ubuntu20.04-focal-backports|http://archive.ubuntu.com/ubuntu/dists/focal-backports/universe/] Valid metadata not found at specified URL
History:
- [external-ubuntu20.04-focal-backports|http://archive.ubuntu.com/ubuntu/dists/focal-backports/universe/] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'external-ubuntu20.04-focal-backports' because of the above error.
Could not refresh the repositories because of errors.

02:26:52 Updating overview of 5 systems
02:26:52 Total time: 0:00:04
