### ISSUE TITLE
salt-minion[254238]: [WARNING ] Unable to process beacon pkgset (Oracle Linux Client)

### ISSUE THREAD

**Issue by ucraspberry** [uyuni-project/uyuni#4917]
Hello,

I was trying to use the Uyuni app. When it is installed on the client(salt), the continuous warning logs start to fall as follows. What can I do to avoid these warnings? Is there a workaround?

Thanks

Uyuni release 2022.01
CLIENT OS: Oracle Linux Server 8.5

/var/log/venv-salt-minion.log
/var/log/messages

tail -f /var/log/messages
Feb 28 12:35:14 xxxxxxsys01 salt-minion[254238]: [WARNING ] Unable to process beacon pkgset
Feb 28 12:35:15 xxxxxxsys01 salt-minion[254238]: [WARNING ] Unable to process beacon pkgset
Feb 28 12:35:16 xxxxxxsys01 salt-minion[254238]: [WARNING ] Unable to process beacon pkgset
Feb 28 12:35:17 xxxxxxsys01 salt-minion[254238]: [WARNING ] Unable to process beacon pkgset
...

**Comment by ZsBT** [comment]
This issue should be escalated to BUG.

Currently, you can patch the file on your own. Using the latest salt-minion package (3004), I get an exception:

```
2022-03-01 10:18:35,809 [salt.minion      :2879][CRITICAL][1684] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 2877, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 516, in process_beacons
    b_conf, self.opts["grains"]
  File "/usr/lib/python3.6/site-packages/salt/beacons/__init__.py", line 75, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
```

Also, in this version of Uyuni, the pkgset beacon cannot be deleted as it is defined in pillar. However, there is no clue which file in it is, I already rgrep-ed the whole filesystem and found none.

In file `/usr/lib/python3.6/site-packages/salt/beacons/__init__.py` , replace 

```
            b_config[mod].append({"_beacon_name": mod})
```
to
```
            try:
                b_config[mod].append({"_beacon_name": mod})
            except AttributeError:
                continue
```
for a workaround.

**Comment by ucraspberry** [comment]
Thank you for your help. I updated "UYUNI". 2022.01 ---> 2022.02 error does not appear constantly anymore. 

Thank you
