### ISSUE TITLE
Question - How do I use a Custom Salt Extension with the Salt Bundle

### ISSUE THREAD

**Issue by claudekenni** [uyuni-project/uyuni#4940]
# Question

How do I use a Custom Salt Extension with the Salt Bundle. 
It doesn't seem like the salt bundle has pip available and I couldn't figure out how to install pip.

**Comment by agraul** [comment]
Hi @claudekenni!

You're right, at the moment the Salt Bundle does not include `pip`. The Salt Bundle can currently only use the shipped Python packages.

We are evaluating possible ways of letting users use Python packages that are not shipped inside the Bundle. At this moment we can't give you any estimation when we will have something, but we'll keep you posted!

**Comment by vzhestkov** [comment]
@claudekenni we've added the documentation section about extending the bundle with `pip`: https://github.com/uyuni-project/uyuni-docs/pull/1674

The bundle with `pip` was already released, but it requres an extra alignment which will be released with the next Uyuni release.
Check the following changelog entry to ensure is the alignment required for `pip` is present in the package:
```
- Set VENV_PIP_TARGET to /var/lib/venv-salt-minion/local
  to force PIP use it as the destination to install modules
```

**Comment by vzhestkov** [comment]
I would suggest to close the issue if you don't mind.

**Comment by meaksh** [comment]
Let's close this for now, as Salt Bundle is able to extend now the available modules.
