### ISSUE TITLE
Uyuni 2022.02 - Deploying files from configuration channels stays forever in pending state

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#4998]
# Problem description

Deploying simple configuration files from a configuration channel is not working as expected.

If a file is deployed, the appropriate tasks stays forever in pending state. When manually applying the Salt Highstate, the file is created, but the former task still stays in pending state.

## Version of Uyuni Server and Proxy (if used)

```
uyuni-server-stable 2022.02-171.1.uyuni1
```

## Details about the issue

Steps to reproduce:

1. Create a configuration channel and a simple text file (*e.g. `/tmp/test.txt`).
2. Deploy the configuration file to the system
3. Watch pending tasks for a couple of minutes
4. Manually apply the Highstate and check the file existence
5. Watch pending tasks, it still contains the configuration file deployment task

**Comment by mackdk** [comment]
From my testing, this issue has already been fixed on the master branch (even though I haven't been able to exactly pinpoint the problem yet) so next version 2022.03 should work properly.

**Comment by stdevel** [comment]
Hi @mackdk - thanks for the feedback. Happy to hear that it was fixed.
Do you have any details on the issue?
