### ISSUE TITLE
Uyuni 2022.02 - 'yast2 susemanager_setup' hangs indefinitely on '** Database: Setting up report database.'

### ISSUE THREAD

**Issue by dvosburg** [uyuni-project/uyuni#5009]
# Problem description

Normal setup with Uyuni Stable repos, answer all questions but setup stops while creating reporting database.  Installation must be aborted, but only the reporting database setup appears to have been interrupted.  

## Version of Uyuni Server and Proxy (if used)
2022.02

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

## Details about the issue

Chose the 'Abort' option, and it then claimed setup was complete, as if it was a normal completion:

![uyuni2022-02-setup-fail-complete](https://user-images.githubusercontent.com/8925618/158250913-9a730226-a1dd-40c0-9e13-d8d52d1ca86c.png)

**Comment by spartonicus** [comment]
Was able to recreate this on fresh install.   The following are the processes currently running when this occurs.  Nothing is present in terms of errors or events in the logs.  



```
 3729 root      20   0    4944    652    560 R 99.67 0.004 190:25.32 fold
 3727 root      20   0    5080    656    564 R 48.84 0.004  93:11.55 cat
 3728 root      20   0    4964    688    596 R 39.87 0.004  75:47.06 tr

```

**Comment by mcalmer** [comment]
@spartonicus @dvosburg 
Could it be that /dev/urandom is blocking? 

`cat /dev/urandom | tr -dc '[:alpha:]' | fold -w 20 | head -n 1`

This command is used to autogenerate the password. But on a current OS, urandom should not block anymore.
Can you check if `haveged` is installed. If not, please install it and try again and see if it still happens

**Comment by thesp0nge** [comment]
I had the same issue and haveged daemon is installed and running

**Comment by Bischoff** [comment]
Same issue, but:
```
zinfandel-2:~ # rpm -qa | grep haveged
haveged-1.9.14-150400.1.2.ppc64le
zinfandel-2:~ # cat /dev/urandom | tr -dc '[:alpha:]' | fold -w 20 | head -n 1
sSTiaJlSPvzdQzVcFrOd
zinfandel-2:~ # pstree
(...)
        ├─sshd─┬─sshd───bash───yast───Zypp-main─┬─mgr-setup───spacewalk-setup───uyuni-setup-rep───uyuni-setup-rep─┬─cat
        │      │                                │                                                                 ├─fold
        │      │                                │                                                                 └─tr
```

**Comment by Bischoff** [comment]
Michael's fix works for me.

**Comment by mcalmer** [comment]
Closing as fixed
