### ISSUE TITLE
Uyuni 2022.02: Change base channel for EPEL8, CentOS 8 being EOL

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#5066]
In `/etc/rhn/spacewalk-common-channels.ini` :

```
[epel8]
label    = epel8-%(base_channel)s
name     = EPEL 8 for %(base_channel_name)s
archs    = x86_64, ppc64le, aarch64
base_channels = centos8-%(arch)s
gpgkey_url = http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
gpgkey_id = 2F86D6A1
gpgkey_fingerprint = 94E2 79EB 8D8F 25B2 1810 ADF1 21EA 45AB 2F86 D6A1
repo_url = http://mirrors.fedoraproject.org/mirrorlist?repo=epel-8&arch=%(arch)s
```

`base_channels` should be changed from `centos8-%(arch)s` to rocky or AlmaLinux 8 base channel, as most of the Uyuni users, me included, are in the process of removing CentOS 8 repos from Uyuni.

**Comment by juliogonzalez** [comment]
@phibid my guess is that instead we need two channels.

One for Alma, one for Rocky.

Can you give it a try , and prepare a PR?
