### ISSUE TITLE
Uyuni 2022.02: Typo in spacewalk-common-channels.ini; Debian 11 repo is using Debian 10 once

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#5069]
There is a typo for those 2 channels in `/etc/rhn/spacewalk-common-channels.ini`

```
[debian-11-amd64-uyuni-client-devel]
label    = debian-11-amd64-uyuni-client-devel
name     = Uyuni Client Tools for Debian 10 Buster AMD64 (Development)
archs    = amd64-deb
repo_type = deb
checksum = sha256
base_channels = debian-11-pool-amd64-uyuni
repo_url = https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/Debian11-Uyuni-Client-Tools/Debian_11/

[debian-11-amd64-uyuni-client]
label    = debian-11-amd64-uyuni-client
name     = Uyuni Client Tools for Debian 10 Buster AMD64
archs    = amd64-deb
repo_type = deb
checksum = sha256
base_channels = debian-11-pool-amd64-uyuni
repo_url = https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Debian11-Uyuni-Client-Tools/Debian_11/
```

The name is the same as of the Debian 10 ones, which prevents the add via `spacewalk-common-channels` if Debian 10 channels already exist:

```
uyuni:/var/log/rhn/reposync # spacewalk-common-channels -a amd64-deb debian-11-pool-amd64-uyuni debian-11-amd64-uyuni-client debian-11-amd64-main-updates-uyuni debian-11-amd64-main-security-uyuni
SUSE Manager username: admin
SUSE Manager password:
WARNING: debian-11-amd64-uyuni-client: redstone.xmlrpc.XmlRpcFault: The channel name 'Uyuni Client Tools for Debian 10 Buster AMD64' is already in use, please enter a different name
```

Modifying the channel name by something like `Uyuni Client Tools for Debian 11 Bullseye AMD64` in the ini file solve the issue.

**Comment by wombelix** [comment]
@phibid thanks for reporting this issue, looks like a easy fix indeed and a great opportunity for you to create your first Pull Request? :)

High Level steps:
1. Clone the Repository `git@github.com:uyuni-project/uyuni.git`
2. Create a feature branch `git checkout -b <branchname>`
3. Change `utils/spacewalk-common-channels.ini` accordingly
4. Add a new line, that starts with `- ` followed by a short description of the fixed issue, at the top of `utils/spacewalk-utils.changes`.
5. Commit your Changes `git commit -a -m "<commit message>"`
6. Push your Changes `git push origin <branchname>`
7. Create a Pull Request

**Comment by juliogonzalez** [comment]
Fixed at https://github.com/uyuni-project/uyuni/pull/5262, just in case @phibid doesn't notice in time.
