### ISSUE TITLE
Uyuni 2022/02 "Reboot required" is ignored?

### ISSUE THREAD

**Issue by chr78** [uyuni-project/uyuni#5084]
Hi,

I installed several kernel updates on a centos 7, oracle 8 and ubuntu 20 system, and the updates were marked as "reboot" in the patch list.
But after upgrade, the systems are not listed in the "Requiring Reboot" list, also there is no information about reboot in the details->overview view
Is this feature only with SLES/opensuse clients?

**Comment by digdilem** [comment]
(Not a dev, just a user with EL clients)

Yes - you are correct. Certainly I've never had Uyuni or Spacewalk before it act upon this, and when I explored I could find no evidence that it was ever designed to do anything based on that setting. 

There are a couple of workarounds:

1. Reboot after every patch window regardless of values. 

2. Run a script after patching that runs `needs-restarting -r` (available in the normal yum/dnf repos for C7/OEL8) which tests for this and then reboot if it returns true.

Ubuntu/Debian has a similar method for testing whether a reboot is needed (I vaguely recall it being a file that's created within /etc)

All these options can be automated as part of your regular patch routines.

**Comment by mcalmer** [comment]
Use this as state:

```
init_keep_system_up2date_pkgs:
  pkg.uptodate:

init_reboot_if_needed:
  cmd.run:
    - name: shutdown -r +5
{%- if grains['os_family'] == 'RedHat' and grains['osmajorrelease'] >= 8 %}
    - onlyif: 'dnf -q needs-restarting -r; [ $? -eq 1 ]'
{%- elif grains['os_family'] == 'RedHat' and grains['osmajorrelease'] <= 7 %}
    - onlyif: 'needs-restarting -r; [ $? -eq 1 ]'
{%- elif grains['os_family'] == 'Debian' %}
    - onlyif:
      - test -e /var/run/reboot-required
{%- else %}
    - onlyif: 'zypper ps -s; [ $? -eq 102 ]'
{%- endif %}
```

**Comment by chr78** [comment]
Hi,

I had a spacewalk 2.x installation with  centos 7 and ubuntu 18 clients and I got a notification in the machine panel and daily digest after i installed a patch which contained the "reboot" keyword. So i expected that uyuni works the same (you also have the reboot-requred menu within the system list for those machines, but its empty)
But with spacewalk, I had traditional clients, maybe with salt there is an issue. 

I have a lot of simple machines that install automatic patches over night, but i don't want to reboot automatically. Right now I check the reboot state with zabbix, but having it in uyuni with a simple view and at the daily digest would be nice.

**Comment by gabira2003** [comment]
Hi,

I second same observation on Ubunu18 LTS running as client and Uyuni2022.05 as server.
I can see the '/var/run/reboot-required' mechanism is created on client,but  those clients don't appear under  'reboot required' in GUI menu under "Systems->System List->Requiring Reboot" , even after new kernel has been installed.

This feature used to work on older Uyuni versions.
May someone check and fix the ability to schedule systems reboot like TopicStarter (chr78) mentioned.

Thanks

**Comment by chr78** [comment]
> 

I think the difference is that now, Uyuni gets the patch information directly from the channels, with the old mechanism it was imported by script from the ubuntu mailing list. Maybe the "new" mechanism doesn't provide this "reboot required" flag in the Patch information.

**Comment by mcalmer** [comment]
The latest Uyuni version should have this implemented also for not SUSE OSes

**Comment by SupremeGit** [comment]
Yeah well done.
Your so called "fix" is now hogging CPU by running this stupid command: /usr/bin/dnf -q needs-restarting -r

ENDLESSLY.
EVERY TEN SECONDS.

ARE YOU INSANE? or just INCREDIBLY incompetent?
