### ISSUE TITLE
Migrating DB from Leap 15.3 to Leap 15.4

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni#5092]
Update server migrator script to upgrade from Leap 15.3 to Leap 15.4

**Comment by mbussolotto** [comment]
Blocked until Leap 15.4 GA is out

**Comment by mbussolotto** [comment]
@juliogonzalez @jordimassaguerpla JFYI, I will re-test the PR today and if everything is still fine I'll move it to ready and ask for review.

Thanks!

**Comment by mbussolotto** [comment]
`server-migrator.sh` correctly migrate from 15.3 to 15.4, but `pg-migrate-x-to-y.sh` is not working cause it seems that postgres 14 is not available. Last version available is 13:
```
uyuni:~ # rpm -qa --qf '%{VERSION}\n' 'name=postgresql[0-8][0-9]-server'  | cut -d. -f1 | sort -n | tail -n1
13
```

**Comment by jordimassaguerpla** [comment]
pg14 is not in leap 15.4? :thinking: could you check which repos do you have configured? I am thinking if we are missing some sle backports or something...

**Comment by mbussolotto** [comment]
it seems `zypper dup` does not migrate postgres. If I try to install `postgresql14` using zypper:

```
zypper in postgresql14
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: the installed spacewalk-postgresql-4.3.3-1.6.uyuni1.noarch conflicts with 'postgresql-implementation >= 14' provided by the to be installed postgresql14-14.2-5.9.2.x86_64
 Solution 1: Following actions will be done:
  deinstallation of spacewalk-postgresql-4.3.3-1.6.uyuni1.noarch
  deinstallation of susemanager-4.3.13-1.1.uyuni1.x86_64
  deinstallation of patterns-uyuni_server-2022.05-1.1.uyuni1.x86_64
  deinstallation of supportutils-plugin-susemanager-4.3.4-1.1.uyuni1.noarch
 Solution 2: do not install postgresql14-14.2-5.9.2.x86_64

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 
```

So yes, `postgresql14` is available from repo but it seems there's other issue. Still investigating on it

**Comment by juliogonzalez** [comment]
Probably that means `spacewalk-postgresql` (and the patterns) need to be adapted.

I guess we did it if the base OS is SLE (SUSE Manager), but now it needs to apply to openSUSE (Uyuni) as well.

**Comment by mbussolotto** [comment]
closing as duplicated of https://github.com/SUSE/spacewalk/issues/17546
