### ISSUE TITLE
Bugreport - Uyuni-check-database fails

### ISSUE THREAD

**Issue by SSchott** [uyuni-project/uyuni#5149]
# Problem description

Already found some other reports on similar lines, but none of them was exactly what I got here (#4958 here at least got fixed by updating...). Uyuni got updated to schema 4.3.9, according to the available log files:
```
-rw-r--r-- 1 root root 26298 Feb  7 18:15 schema-from-20220207-181519-to-susemanager-schema-4.3.7.log
-rw-r--r-- 1 root root 22137 Apr  5 11:06 schema-from-20220405-110658-to-susemanager-schema-4.3.9.log
```

Both logs seem to be pretty much equivalent, with the distinctions of the version numbers.

After a first reboot everything worked fine. I had to reboot the machine once again, and after the second time, Uyuni refuses to start with problems regarding the database upgrade:

```
spacewalk-service start
Starting spacewalk services...
  Running DB schema upgrade. This may take a while.
  Call the following command to see progress: journalctl -f -u uyuni-check-database.service
db_host = localhost
● uyuni-check-database.service - Uyuni check database
     Loaded: loaded (/usr/lib/systemd/system/uyuni-check-database.service; static)
     Active: failed (Result: exit-code) since Tue 2022-04-05 18:15:04 CEST; 8ms ago
    Process: 7936 ExecStart=/usr/sbin/spacewalk-startup-helper check-database (code=exited, status=1/FAILURE)
   Main PID: 7936 (code=exited, status=1/FAILURE)

Apr 05 18:15:04 spacewalk-startup-helper[7962]: Your database schema already matches the schema package version [susemanager-schema-4.3.9-1.6.uyuni1].
Apr 05 18:15:04 spacewalk-startup-helper[7962]: Schema upgrade: [susemanager-schema-4.3.9-1.6.uyuni1] -> [susemanager-schema-4.3.9-1.6.uyuni1]
Apr 05 18:15:04 spacewalk-startup-helper[7987]: psql:<stdin>:1: ERROR:  relation "dual" does not exist
Apr 05 18:15:04 spacewalk-startup-helper[7987]: LINE 1: select '1' || '2' || '3' as testing from dual;
Apr 05 18:15:04 spacewalk-startup-helper[7987]:                                                  ^
Apr 05 18:15:04 spacewalk-startup-helper[7983]: Connect to database was not successful.
Apr 05 18:15:04 spacewalk-startup-helper[7936]: Report Database schema upgrade failed. Please check the logs.
Apr 05 18:15:04 systemd[1]: uyuni-check-database.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 18:15:04 systemd[1]: uyuni-check-database.service: Failed with result 'exit-code'.
Apr 05 18:15:04 systemd[1]: Failed to start Uyuni check database.
FAILED

```

I can access to `spacewalk-sql -i` and get info within the db, so at least there is that. I am not an SQL user at all, so maybe I am missing something pretty obvious here. Any ideas?

This is what I found for the schema upgrade:

```
/etc/sysconfig/rhn/reportdb-schema-upgrade
/etc/sysconfig/rhn/reportdb-schema-upgrade/uyuni-reportdb-schema-4.3.1-to-uyuni-reportdb-schema-4.3.2
/etc/sysconfig/rhn/reportdb-schema-upgrade/uyuni-reportdb-schema-4.3.1-to-uyuni-reportdb-schema-4.3.2/003-fix-inventoryreport-duplication.sql.postgresql
/etc/sysconfig/rhn/reportdb-schema-upgrade/uyuni-reportdb-schema-4.3.1-to-uyuni-reportdb-schema-4.3.2/001-change-event-data-type.sql.postgresql
/etc/sysconfig/rhn/reportdb-schema-upgrade/uyuni-reportdb-schema-4.3.1-to-uyuni-reportdb-schema-4.3.2/004-fix-view-naming.sql.postgresql
/etc/sysconfig/rhn/reportdb-schema-upgrade/uyuni-reportdb-schema-4.3.1-to-uyuni-reportdb-schema-4.3.2/002-remove-unneeded-column.sql.postgresql
/etc/sysconfig/rhn/reportdb-schema-upgrade/Makefile
```

## Version of Uyuni Server and Proxy (if used)

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.03-172.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.09-141.3.uyuni1 installed)
Source package : Uyuni-Server-release-2022.03-172.4.uyuni1.src
Summary        : Uyuni Server
```

Should I force a `zypper up Uyuni-Server-release`? At the moment zypper skips it. Susemanager is up to date:

```
Information for package susemanager:
------------------------------------
Repository     : uyuni-server-stable
Name           : susemanager
Version        : 4.3.10-1.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 207.8 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : susemanager-4.3.10-1.1.uyuni1.src
Summary        : SUSE Manager specific scripts
```

**Comment by SSchott** [comment]
From Gitter seems like either `uyuni-setup-reportd` and/or `/usr/lib/susemanager/bin/server-migrator.sh` with `/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh` should be used. Is there any proper documentation for this. Should this be handled by the zypper update automatically?

**Comment by juliogonzalez** [comment]
> From Gitter seems like either `uyuni-setup-reportd` and/or `/usr/lib/susemanager/bin/server-migrator.sh` with `/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh` should be used. Is there any proper documentation for this. Should this be handled by the zypper update automatically?

Those scripts are to be used only for major upgrades, basically when the base OS changes (https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/server-major-upgrade-uyuni.html)

As of today, that's only the case if you are migrating from a version older than 2021.06 (https://www.uyuni-project.org/pages/stable-version.html#releasenotes)

Otherwise a minor upgrade is to be applied: https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/server-minor-upgrade-uyuni.html

Still, I seem to remember applying such scripts won't break things anymore, so... what's the content of `schema-from-20220207-181519-to-susemanager-schema-4.3.7.log` and `schema-from-20220405-110658-to-susemanager-schema-4.3.9.log`?

**Comment by SSchott** [comment]
Thanks for the reply. I went through the server migration scripts; I will get back to you once I have the chance to reboot the machine again.

Attached are the schema update logs if they help somehow:
[schema-from-20220405-110658-to-susemanager-schema-4.3.9.log](https://github.com/uyuni-project/uyuni/files/8424853/schema-from-20220405-110658-to-susemanager-schema-4.3.9.log)
[schema-from-20220207-181519-to-susemanager-schema-4.3.7.log](https://github.com/uyuni-project/uyuni/files/8424854/schema-from-20220207-181519-to-susemanager-schema-4.3.7.log)

Saludos!

**Comment by SSchott** [comment]
Ok, just did a reboot, and still the same state 😬

**Comment by juliogonzalez** [comment]
> Apr 05 18:15:04 spacewalk-startup-helper[7987]: psql:<stdin>:1: ERROR:  relation "dual" does not exist
> Apr 05 18:15:04 spacewalk-startup-helper[7987]: LINE 1: select '1' || '2' || '3' as testing from dual;

Looks like that sentence is part of:
```
spacewalk/spacewalk-schema-upgrade:my $test = run_query("select '1' || '2' || '3' as testing from dual;")
```

But that's nothing new: https://github.com/uyuni-project/uyuni/blame/master/schema/spacewalk/spacewalk-schema-upgrade#L65

I can't find anything strange at the logs you provided, but I wonder with `4.3.8` is missing.

My guess is that something failed running that upgrade?

First of all, we need to know:

1. On what Uyuni version you were, before you applied this udpate
2. The exact steps and commands you took to run the upgrade
3. Any possible errors you saw, while running those steps and commands

**Comment by SSchott** [comment]
1. The last time the server was updated was the 7th of February. According to zypper history:
```
2022-02-07 18:14:35|install|spacewalk-common|4.3.3-1.2.uyuni1|noarch||uyuni-server-stable|833efb28e15c47b9c07802bb111a6093e951702b318fbaac332f4574cfda6ec3|
2022-02-07 18:14:35|install|spacewalk-postgresql|4.3.3-1.2.uyuni1|noarch||uyuni-server-stable|3809342a68587c8e8469d81047268ce21251dbc2b873ad9f57a0f9868b2606b4|
2022-02-07 18:14:35|install|susemanager|4.3.7-1.2.uyuni1|x86_64||uyuni-server-stable|8799b9de5394b70f1ba318027e3a52495174b8d497449ec75d905801e715d1be|
2022-02-07 18:14:35|install|supportutils-plugin-susemanager|4.3.3-1.1.uyuni1|noarch||uyuni-server-stable|3b0ebffcae8be5d5d51fe02cc4bfaf4d12263a2f4ee65b092125454d2f6995d0|
2022-02-07 18:14:35|install|patterns-uyuni_server|2022.01-1.1.uyuni1|x86_64||uyuni-server-stable|098baf344cdda2319763b09e30cc59d217d2073c676dca590b4c92477d153c9e|
```

2. For the update I just did a typical `zypper ref` + `zypper up`. I hope I didn't miss a specific Uyuni step there

3. No errors at all. And for me the weirdest thing is that after the first reboot it worked, and I even updated other machine connected to Uyuni. After I rebooted it up again, I lost access to the web interface, which is how I found the error.

**Comment by juliogonzalez** [comment]
> 1. The last time the server was updated was the 7th of February. According to zypper history:
> 
> ```
> 2022-02-07 18:14:35|install|spacewalk-common|4.3.3-1.2.uyuni1|noarch||uyuni-server-stable|833efb28e15c47b9c07802bb111a6093e951702b318fbaac332f4574cfda6ec3|
> 2022-02-07 18:14:35|install|spacewalk-postgresql|4.3.3-1.2.uyuni1|noarch||uyuni-server-stable|3809342a68587c8e8469d81047268ce21251dbc2b873ad9f57a0f9868b2606b4|
> 2022-02-07 18:14:35|install|susemanager|4.3.7-1.2.uyuni1|x86_64||uyuni-server-stable|8799b9de5394b70f1ba318027e3a52495174b8d497449ec75d905801e715d1be|
> 2022-02-07 18:14:35|install|supportutils-plugin-susemanager|4.3.3-1.1.uyuni1|noarch||uyuni-server-stable|3b0ebffcae8be5d5d51fe02cc4bfaf4d12263a2f4ee65b092125454d2f6995d0|
> 2022-02-07 18:14:35|install|patterns-uyuni_server|2022.01-1.1.uyuni1|x86_64||uyuni-server-stable|098baf344cdda2319763b09e30cc59d217d2073c676dca590b4c92477d153c9e|
> ```
> 
> 2. For the update I just did a typical `zypper ref` + `zypper up`. I hope I didn't miss a specific Uyuni step there

Did you stop the services before doing that? That's one of the mandatory steps.

> 3. No errors at all. And for me the weirdest thing is that after the first reboot it worked, and I even updated other machine connected to Uyuni. After I rebooted it up again, I lost access to the web interface, which is how I found the error.

**Comment by SSchott** [comment]
No sir I didn't 😢. Still weird that it worked after the first reboot though? What would I lose if the reportdb is "rebuilt". At this point I wouldn't mind resetting part of it, as long as installation scripts and configuration files are kept in place.

**Comment by juliogonzalez** [comment]
> Still weird that it worked after the first reboot though

Hard to say what that happened, but updating without stopping risks breaking the system in some situations.

> What would I lose if the reportdb is "rebuilt"

Not sure how you plan to "rebuild it", but that database is separate from the main one, so in terms of data you should not lose anything important if you don't care about the reporting.

However depending on what you do to "rebuild it" or "reset it", you could break the system even more.

**Comment by SSchott** [comment]
To be honest, I am kind of throwing stones at the air at the moment to see how I can get this back working again, but I thought this is where `uyuni-setup-reportdb` would come into play. In Gitter a user reported using it to solve a similar issue as mine here, but he didn't specify which flags to use, and as you mention, I am not looking forward to break things further. Any idea if this could be a way out?

**Comment by juliogonzalez** [comment]
Well, before going further, I'd recommend a backup.

That's always recommended before updating, anyway, just in case.

But to be honest, I don't see how "resetting/rebuilding" the reportdb could bring your system back?

**Comment by SSchott** [comment]
For further reference: https://gitter.im/uyuni-project/users?at=62220f8799d94f5f0c34fcab

**Comment by SSchott** [comment]
> But to be honest, I don't see how "resetting/rebuilding" the reportdb could bring your system back?
Oki, but then what would be "the way to go". Start from scratch, or is there any middleground I could aim for?

**Comment by juliogonzalez** [comment]
> For further reference: https://gitter.im/uyuni-project/users?at=62220f8799d94f5f0c34fcab

FMPOV, it looks quite different from your issue. In his case it seems the PostgreSQL service was dead. In your case the PostgreSQL service is alive, but the migration script fails to run a query.

**Comment by juliogonzalez** [comment]
> > But to be honest, I don't see how "resetting/rebuilding" the reportdb could bring your system back?
> 
> Oki, but then what would be "the way to go". Start from scratch, or is there any middleground I could aim for?

Hard to say on what status your system is now. 

The `dual` table is created on the main Uyuni database (in the instance where I checked the DB is called Uyuni, but you can pick a different name during the setup)
```
uyuni=# select '1' || '2' || '3' as testing from dual;
 testing 
---------
 123
(1 row)
```
If this table doesn't exist, it could show the DB is corrupted for some reason, and it would be better to start from scratch.

**Comment by SSchott** [comment]
I'll see to backup things and get back if I manage something beyond starting from scratch.

**Comment by SSchott** [comment]
Hi again,
I am wondering from your last comment, you were actually refering to the manage_db, right? Because that one seems to be fine, and dual seems to be there when I do that check manually. 

```
spacewalk-sql -i
psql (13.6)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

uyuni=# select '1' || '2' || '3' as testing from dual;
 testing 
---------
 123
(1 row)
```



Reportdb on the other hand seems to be...empty apparently? 
```
spacewalk-sql -i --reportdb
psql (13.6)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

reportdb=# select '1' || '2' || '3' as testing from dual;
ERROR:  relation "dual" does not exist
LINE 1: select '1' || '2' || '3' as testing from dual;
                                                 ^
```

Is reportdb a new database that wasn't implemented on the 2021 version?

**Comment by juliogonzalez** [comment]
> Is reportdb a new database that wasn't implemented on the 2021 version?

https://www.uyuni-project.org/doc/2022.03/release-notes-uyuni-server.html#_reporting_database

Only part of 2022.02 and newer

**Comment by SSchott** [comment]
Ok, so since I never really had 2022.02, because apparently I went from 2022.01 to 2022.03, could that be the cause? If so, any way in which I can replicate the "original" creation process for the reportdb?

**Comment by juliogonzalez** [comment]
Not really, the new reportdb is created if it doesn't exist, so it doesn't need users to go through 2022.02 first.

Not knowing the status your server instance is. The "original" creation process is done by several parts of the product, so I don't think there's really an easy way to do it manually, as it will changed authentication configuration, created the database, filled it with some data, and more.

**Comment by SSchott** [comment]
Sigh. I am really confused as I haven't done anything aside of the zypper update. I just tried a reinstall with `/usr/lib/susemanager/bin/mgr-setup -s` and it is failing at the same point:

```
Asserting correct java version...
/var/spacewalk already exists. Leaving it untouched.
Filesystem type for /var/cache is ext4 - ok.
Open needed firewall ports...
running
Warning: ALREADY_ENABLED: suse-manager-server
success
success
Performing forced re-installation!
Shutting down spacewalk services...
Done.
Delete existing database...
Delete existing salt minion keys
CREATE ROLE
* Loading answer file: /root/spacewalk-answers.
** Database: Setting up database connection for PostgreSQL backend.
** Database: Populating database.
** Database: --clear-db option used.  Clearing database.
** Database: Shutting down spacewalk services that may be using DB.
** Database: Services stopped.  Clearing DB.
*** Progress: ###############################
* Configuring tomcat.
* Setting up users and groups.
* Performing initial configuration.
* Configuring apache SSL virtual host.
* Configuring jabberd.
* Creating SSL certificates.
** SSL: Generating CA certificate.
** SSL: Generating server certificate.
** Database: Setting up report database.
** Database: --clear-db option used.  Clearing report database.
*** Progress: ###
Could not install report database.
ERROR: spacewalk-setup failed
```
Noticed in `/var/log/rhn/install_db.log` that it was complaining that `reportdb` already exists. Manually deleting it with `dropdb` still fails, with only `NOTICE:  extension "plpgsql" already exists, skipping` in the log file now. Any guideline at this point would be helpful.

**Comment by SSchott** [comment]
Eureka....
Ok, the existing `pythia_susemanager` user was also causing trouble. A `dropuser`, and then executing `/usr/lib/susemanager/bin/mgr-setup -s` (where if anyone else has the same issue, you can look on how `uyuni-setup-reportdb` is being called) at least allowed to get a clean Uyuni again. 

So throughout the testing process the database got restarted. What I had to do to fix this was essentially to recover all files I backed up with rsync, replace the database under `/var/lib/pgsql/data` by the migration backup `/var/lib/pgsql/data-pg13`, and I got to where I started in this issue. From there I did:

```
spacewalk-service stop
rcpostgresql stop
su postgres
dropdb reportdb
dropuser pythia_susemanager
exit
uyuni-setup-reportdb create --db reportdb --user pythia_susemanager --address "*" --password $(Here the password under  /etc/rhn/rhn.conf for remote_db) --remote 0.0.0.0/0,::/0
rcpostgresql start
spacewalk-service start
```

Everything seems to be working again just as after the first restart. I still don't know what happened, and I hope after the next restart the db will still be there. Maybe this will help someone with similar issues.

**Comment by juliogonzalez** [comment]
Not sure I'd call that "clean", but if it works, then OK :-)

I'd recommend you do the restart now, to check that the DB Is still OK.

In any case, we should check if we  can lock zypper while the services are running, somehow. Maybe a project for the next [hackweek](https://hackweek.opensuse.org/) :-D

**Comment by SSchott** [comment]
Managed to restart the machine, and no issues for now. Surely for the next update I'll backup things first to not lose things. Would a disclaimer in the zypper update process whenever DB changes are in place make sense? I know, RTFM, but some of us have the "admin" task as a side job only :grimacing: . I'll leave it as a suggestion :v:

**Comment by juliogonzalez** [comment]
This is not only about the DB changes, other packages being updated without stopping the service could cause problems as well.

All I can think of is what I suggested: locking zypper somehow, if the services are running (no idea if that's possible). Maybe I will run that as a hackweek project.

**Comment by mcalmer** [comment]
You need to migrate to Pg14. There is a script which convert the db from13 to 14. Please check the update instructions.

**Comment by Zayan1221** [comment]
where can I have those instructions

**Comment by Zayan1221** [comment]
uyunisuse:~ # /usr/lib/susemanager/bin/pg-migrate-12-to-13.sh
23:43:40    You have postgresql-server 14 installed.
23:43:40    You have postgresql server 13 configured.
23:43:40   ERROR: Latest installed version is 14, which does not match 13, the option you provided with -d.

**Comment by mcalmer** [comment]
In the same directory there is a script which is named with x-to-y. Use that. It autodetect the versions.

**Comment by Zayan1221** [comment]
I did use that now, but same error
<img width="678" alt="Capture" src="https://user-images.githubusercontent.com/65530039/176194693-77f774f8-a499-4024-95fe-ebbf0765b690.PNG">
.

**Comment by Zayan1221** [comment]
<img width="957" alt="Capture1" src="https://user-images.githubusercontent.com/65530039/176195180-120eeb94-7e23-4c36-a87b-e009f1ec0f86.PNG">


Still Failed

**Comment by Zayan1221** [comment]
I am good now- Thanks for ythe help

**Comment by Zayan1221** [comment]
I have upgraded the OpenSUSE Leap from 15.3 to 15.4
Then Upgrade the Uyuni Tool from 2021.08 to 2022.06
Then Update the salt minion to latest which is 3004
Problem Solved
Thanks
Hassan

**Comment by mcalmer** [comment]
@Zayan1221 this report is closed and the title does not match your problem. Please open a new bugreport.
