### ISSUE TITLE
I upgraded from Uyuni 2022.02 to 2022.03 and now Bootstrapping clients cannot get the salt packages

### ISSUE THREAD

**Issue by keano74** [uyuni-project/uyuni#5219]
# Question - I am using a Proxy for this client but the bootstrap repo is only on the master, should it also be on the proxy? 

_What do you want to know about Uyuni?_

CentOS7 bootstrap repository not found, using RES7 bootstrap repository instead
https://PROXYSERVERNAME/pub/repositories/res/7/bootstrap/repodata/repomd.xml:
2022-04-15 14:45:47 ERROR 500: Internal Server Error.
Bootstrap repo 'https://PROXYSERVERNAME/pub/repositories/res/7/bootstrap' does not exist.
* going to install missing packages...
Loaded plugins: langpacks
No package salt available.
No package salt-minion available.
Error: Nothing to do
package salt is not installed
ERROR: Failed to install all missing packages.

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

**Comment by juliogonzalez** [comment]
IIRC, the proxy works as a HTTP proxy for the bootstrap repositories as well, not just for the channels.

You didn't fill `Version of Uyuni Server and Proxy`, please do it.

And also provide logs from the proxy, for squid and apache, when the error 500 is happening.

It could also be you need to check the server logs as well.

**Comment by keano74** [comment]
nothing showing in the Squid logs on the Proxy

Apache logs

xx.xx.xx..xx - - [25/Apr/2022:08:07:49 +0000] "GET /pub/bootstrap/client_config_update.py HTTP/1.1" 200 6331
xx.xx.xx..xx - - [25/Apr/2022:08:07:49 +0000] "GET /pub/bootstrap/client-config-overrides.txt HTTP/1.1" 200 641
xx.xx.xx..xx - - [25/Apr/2022:08:07:49 +0000] "GET /pub/uyuni-gpg-pubkey-0d20833e.key HTTP/1.1" 200 1126
xx.xx.xx..xx - - [25/Apr/2022:08:07:50 +0000] "GET /pub/rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm HTTP/1.1" 200 13700
xx.xx.xx..xx - - [25/Apr/2022:08:07:51 +0000] "GET /pub/repositories/centos/7/bootstrap/repodata/repomd.xml HTTP/1.1" 500 1021
xx.xx.xx..xx - - [25/Apr/2022:08:07:51 +0000] "GET /pub/repositories/res/7/bootstrap/repodata/repomd.xml HTTP/1.1" 500 1021

**Comment by keano74** [comment]
[Mon Apr 25 08:07:51.531084 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082] mod_wsgi (pid=32696): Exception occurred processing WSGI script '/usr/share/rhn/wsgi/xmlrpc.py'.
[Mon Apr 25 08:07:51.531592 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082] Traceback (most recent call last):
[Mon Apr 25 08:07:51.531635 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]   File "/usr/share/rhn/wsgi/xmlrpc.py", line 23, in application
[Mon Apr 25 08:07:51.531639 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]     "proxy.apacheServer")
[Mon Apr 25 08:07:51.531646 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]   File "/usr/share/rhn/wsgi/wsgiHandler.py", line 35, in handle
[Mon Apr 25 08:07:51.531650 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]     parseServ = get_handle(servertype, "HeaderParserHandler")
[Mon Apr 25 08:07:51.531656 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]   File "/usr/share/rhn/wsgi/wsgiHandler.py", line 63, in get_handle
[Mon Apr 25 08:07:51.531660 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]     handler_module = __import__(servertype, globals(), locals(), [servertype.split('.')[-1]])
[Mon Apr 25 08:07:51.531666 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]   File "/usr/share/rhn/proxy/apacheServer.py", line 20, in <module>
[Mon Apr 25 08:07:51.531670 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]     from spacewalk.common.rhnTB import Traceback
[Mon Apr 25 08:07:51.531675 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]   File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnTB.py", line 33, in <module>
[Mon Apr 25 08:07:51.531679 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082]     from uyuni.common.stringutils import to_string
[Mon Apr 25 08:07:51.531693 2022] [wsgi:error] [pid 32696] [client 10.21.68.88:44082] ModuleNotFoundError: No module named 'uyuni.common.stringutils'
[Mon Apr 25 08:07:51.682794 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084] mod_wsgi (pid=32692): Exception occurred processing WSGI script '/usr/share/rhn/wsgi/xmlrpc.py'.
[Mon Apr 25 08:07:51.683299 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084] Traceback (most recent call last):
[Mon Apr 25 08:07:51.683340 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]   File "/usr/share/rhn/wsgi/xmlrpc.py", line 23, in application
[Mon Apr 25 08:07:51.683344 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]     "proxy.apacheServer")
[Mon Apr 25 08:07:51.683363 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]   File "/usr/share/rhn/wsgi/wsgiHandler.py", line 35, in handle
[Mon Apr 25 08:07:51.683367 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]     parseServ = get_handle(servertype, "HeaderParserHandler")
[Mon Apr 25 08:07:51.683372 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]   File "/usr/share/rhn/wsgi/wsgiHandler.py", line 63, in get_handle
[Mon Apr 25 08:07:51.683376 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]     handler_module = __import__(servertype, globals(), locals(), [servertype.split('.')[-1]])
[Mon Apr 25 08:07:51.683382 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]   File "/usr/share/rhn/proxy/apacheServer.py", line 20, in <module>
[Mon Apr 25 08:07:51.683386 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]     from spacewalk.common.rhnTB import Traceback
[Mon Apr 25 08:07:51.683392 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]   File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnTB.py", line 33, in <module>
[Mon Apr 25 08:07:51.683396 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084]     from uyuni.common.stringutils import to_string
[Mon Apr 25 08:07:51.683410 2022] [wsgi:error] [pid 32692] [client 10.21.68.88:44084] ModuleNotFoundError: No module named 'uyuni.common.stringutils'

**Comment by keano74** [comment]
Information for package Uyuni-Server-release:                                                                                                                          
---------------------------------------------                                                                                                                          
Repository     : Uyuni Server Stable                                                  
Name           : Uyuni-Server-release                                                                                                                                  
Version        : 2022.03-172.4.uyuni1                                                                                                                                  
Arch           : x86_64

**Comment by keano74** [comment]
THe Proxy is showing as a much older release but I am updating every month!
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : opensuse-leap-15_3-pool-leap15_3-prod-Uyuni Proxy Stable for openSUSE Leap 15.3 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2021.08-139.2.uyuni1
Arch           : x86_64

**Comment by keano74** [comment]
Have just realized that Pushing Patches is also failing with 500 Errors

**Comment by juliogonzalez** [comment]
For the proxy, please paste the output of running `zypper up` there.

Maybe your problem with the release package is something already reported about a vendor change that happens from time to time with at OBS (I still could not get anyone to explain me why, or how to fix it).

Still, that should not case such issues.

When we see the output of `zypper up` we'll tell you how to fix it.

**Comment by keano74** [comment]
zypper up
Loading repository data...
Reading installed packages...
Nothing to do.

**Comment by juliogonzalez** [comment]
Doesn't mention anything about packages that can be updated?

If not, then make sure the repositories/channels for the proxy are synced at the  server. Maybe you didn't configure the automated synchronization.

**Comment by keano74** [comment]
They are sync'd, The Proxy is already up-to-date. I am trying to update all other servers and I get the following..
https://servername:443/rhn/manager/download/centos7-pool-centos7-prod-centos7-uyuni-client-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error
Trying other mirror.
https://servername:443/rhn/manager/download/centos7-pool-centos7-prod-centos7-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error
Trying other mirror.
https://servername:443/rhn/manager/download/centos7-pool-centos7-prod-centos7-x86_64-extras/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error
Trying other mirror.
https:/servername:443/rhn/manager/download/centos7-pool-centos7-prod-centos7-x86_64-fasttrack/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error
Trying other mirror.

**Comment by juliogonzalez** [comment]
Try `zypper dup` at the proxy and paste the results (do not reply with `yes`).

If that's also telling that there are no packages to be updated, looks like the channels for the proxy are not updated at the server, and you will need to check what packages you have there.

As for the your error, I am afraid your logs and explanations are too messed up to understand what's really going on, so please:

1. Format all the comments, including the description, so we can see what's explanation and what's log.
2. Clearly explain what your setup is, and what you tried. The [original log](https://github.com/uyuni-project/uyuni/issues/5219#issue-1205654864) is about getting the bootstrap repo from the proxy. Then you mention a [proxy is not updated](https://github.com/uyuni-project/uyuni/issues/5219#issuecomment-1108239934), but it seems the [proxy is not being used at the last log you added](https://github.com/uyuni-project/uyuni/issues/5219#issuecomment-1108396916).

**Comment by keano74** [comment]
Sorry I do realize that my explanation is a bit messed up. I originally thought that it was only bootstrapping that was affected. But now I see it is more than that!.

I updated my Uyuni Master and Proxy with the latest updates- That is why it is showing as not having any updates! It is up-to-date.

Now when I try to do any other server updates or New server bootstrapping it fails. Its seems that the proxy is not functioning correctly. I get the error below when trying to do updates. HTTPS Error 500.

https://PROXYservername:443/rhn/manager/download/centos7-pool-centos7-prod-centos7-x86_64-fasttrack/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error

The apache error_log has the following since the update which it think might be the issue!
 [wsgi:error] [pid 1940] [client 10.21.68.21:34266] mod_wsgi (pid=1940): Exception occurred processing WSGI script '/usr/share/rhn/wsgi/xmlrpc.py'.
[Mon Apr 25 11:24:59.741727 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266] Traceback (most recent call last):
[Mon Apr 25 11:24:59.741784 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]   File "/usr/share/rhn/wsgi/xmlrpc.py", line 23, in application
[Mon Apr 25 11:24:59.741792 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]     "proxy.apacheServer")
[Mon Apr 25 11:24:59.741803 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]   File "/usr/share/rhn/wsgi/wsgiHandler.py", line 35, in handle
[Mon Apr 25 11:24:59.741810 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]     parseServ = get_handle(servertype, "HeaderParserHandler")
[Mon Apr 25 11:24:59.741821 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]   File "/usr/share/rhn/wsgi/wsgiHandler.py", line 63, in get_handle
[Mon Apr 25 11:24:59.741829 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]     handler_module = __import__(servertype, globals(), locals(), [servertype.split('.')[-1]])
[Mon Apr 25 11:24:59.741839 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]   File "/usr/share/rhn/proxy/apacheServer.py", line 20, in <module>
[Mon Apr 25 11:24:59.741846 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]     from spacewalk.common.rhnTB import Traceback
[Mon Apr 25 11:24:59.741857 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]   File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnTB.py", line 33, in <module>
[Mon Apr 25 11:24:59.741871 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266]     from uyuni.common.stringutils import to_string
[Mon Apr 25 11:24:59.741895 2022] [wsgi:error] [pid 1940] [client 10.21.68.21:34266] ModuleNotFoundError: No module named 'uyuni.common.stringutils'

**Comment by keano74** [comment]
I have this working now- I had to Downgrade python3-uyuni-common-libs-4.3.2-2.1.uyuni.x86_64 and also I had to take
/usr/lib/python3.6/site-packages/rhn/i18n.py from python3-rhnlib-4.3.2-2.1.uyuni.noarch and place it into the same folder after it had update. 

Obviously some issues with these newer versions of Python libs

**Comment by juliogonzalez** [comment]
Downgrade from what version to what version?

And where exactly? Proxy? Server? Both?

**Comment by keano74** [comment]
Just on the Proxy - 
I had to downgrade from python3-uyuni-common-libs-4.3.3-2.1.uyuni.x86_64 to python3-uyuni-common-libs-4.3.2-2.1.uyuni.x86_64
The new version was missing /usr/lib/python3.6/site-packages/uyuni/common/stringutils.py
and the new version python3-rhnlib-4.3.3-2.1.uyuni.noarch was missing /usr/lib/python3.6/site-packages/rhn/i18n.py

**Comment by keano74** [comment]
If I down graded from python3-rhnlib-4.3.3-2.1.uyuni.noarch to python3-rhnlib-4.3.2-2.1.uyuni.noarch there was other file missing so I just copied over /usr/lib/python3.6/site-packages/rhn/i18n.py from a server with python3-rhnlib-4.3.2-2.1.uyuni.noarch

**Comment by mcalmer** [comment]
i18n.py was removed and stringutils.py was introduced for it.
I think it would be better to check if the file which still import the old i18n file is up to date.

**Comment by keano74** [comment]
[Tue Apr 26 10:14:42.327320 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592] Exception Handler Information
[Tue Apr 26 10:14:42.327327 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592] Traceback (most recent call last):
[Tue Apr 26 10:14:42.327334 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]   File "/usr/share/rhn/proxy/apacheServer.py", line 62, in __call__
[Tue Apr 26 10:14:42.327342 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]     ret = f(req)
[Tue Apr 26 10:14:42.327348 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]   File "/usr/share/rhn/proxy/apacheHandler.py", line 359, in handler
[Tue Apr 26 10:14:42.327355 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]     from .broker import rhnBroker
[Tue Apr 26 10:14:42.327362 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]   File "/usr/share/rhn/proxy/broker/rhnBroker.py", line 43, in <module>
[Tue Apr 26 10:14:42.327370 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]     from . import rhnRepository
[Tue Apr 26 10:14:42.327376 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]   File "/usr/share/rhn/proxy/broker/rhnRepository.py", line 45, in <module>
[Tue Apr 26 10:14:42.327384 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]     from spacewalk.common import rhnRepository
[Tue Apr 26 10:14:42.327391 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]   File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnRepository.py", line 29, in <module>
[Tue Apr 26 10:14:42.327398 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]     from uyuni.common import rhn_rpm
[Tue Apr 26 10:14:42.327405 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]   File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_rpm.py", line 27, in <module>
[Tue Apr 26 10:14:42.327412 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]     from uyuni.common.rhn_pkg import A_Package, InvalidPackageError
[Tue Apr 26 10:14:42.327420 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]   File "/usr/lib/python3.6/site-packages/uyuni/common/rhn_pkg.py", line 17, in <module>
[Tue Apr 26 10:14:42.327427 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592]     from rhn.i18n import bstr
[Tue Apr 26 10:14:42.327434 2022] [wsgi:error] [pid 823] [client 10.21.68.78:35592] ModuleNotFoundError: No module named 'rhn.i18n'

**Comment by keano74** [comment]
Unfortunately I am not overly familiar with the workings of this. But this was the error showing in the apace2 error log

**Comment by mcalmer** [comment]
Fine the package name which contains the file with:
$> rpm -qf /usr/lib/python3.6/site-packages/uyuni/common/rhn_pkg.py

Now check all packages with this name to see if you have the latest version installed.
$> zypper se -s <package name>

**Comment by keano74** [comment]
rhn_pkg.py belongs to python3-uyuni-common-libs-4.3.2-2.1.uyuni.x86_64. I had to Downgrade to this version as version 4.3.3-1.1 it was missing.
 /usr/lib/python3.6/site-packages/uyuni/common/stringutils.py

Original error. the file here /usr/lib/python3.6/site-packages/spacewalk/common/rhnTB.py is part of spacewalk-backend of which I have version 4.3.1-1.5.uyuni1 which looks to be the latest version


Traceback (most recent call last):
File "/usr/share/rhn/wsgi/xmlrpc.py", line 23, in application
"proxy.apacheServer")                                                                                                    
File "/usr/share/rhn/wsgi/wsgiHandler.py", line 35, in handle                                                      
parseServ = get_handle(servertype, "HeaderParserHandler")
File "/usr/share/rhn/wsgi/wsgiHandler.py", line 63, in get_handle                                                          
handler_module = __import__(servertype, globals(), locals(), [servertype.split('.')[-1]])
File "/usr/share/rhn/proxy/apacheServer.py", line 20, in <module>
 from spacewalk.common.rhnTB import Traceback
File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnTB.py", line 33, in <module>                                    
from uyuni.common.stringutils import to_string
ModuleNotFoundError: No module named 'uyuni.common.stringutils'

**Comment by keano74** [comment]
Thank You, looks like one of our repos was not cloning from the correct location. I will update and hopefully that will solve my problem. Thanks for your help

**Comment by juliogonzalez** [comment]
@keano74 any news?

**Comment by keano74** [comment]
Hi, yes this did resolve my issue. Somehow my proxies were way out of date without us knowing
