### ISSUE TITLE
spacewalk-search uses unmaintained apache-commons-httpclient

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#5239]
# Problem description

The Commons HttpClient project is now end of life, and is no longer being developed. (Date of publishing: 2011-06-16)
This poses a security and maintenance risk for **spacewalk-search**.

It has been replaced by the [Apache HttpComponents](https://hc.apache.org/) project in its [HttpClient](https://hc.apache.org/httpcomponents-client-ga) and [HttpCore](https://hc.apache.org/httpcomponents-core-ga/) modules, which offer better performance and more flexibility.

## Version of Uyuni Server and Proxy (if used)

Master 2022-04-21

**Comment by sbluhm** [comment]
Build works without apache-commons-httpclient

**Comment by sbluhm** [comment]
`$ git grep commons` only returns these 4 java files:

```
src/java/com/redhat/satellite/search/DeleteIndexes.java:import org.apache.commons.lang3.StringUtils;
src/java/com/redhat/satellite/search/config/Configuration.java:import org.apache.commons.lang3.StringUtils;
src/java/com/redhat/satellite/search/config/Configuration.java:     * commons conf system just throws Exception, which makes it hard to react.
src/java/com/redhat/satellite/search/db/DatabaseManager.java:import org.apache.commons.lang3.StringUtils;
```

`$ git grep httpclient` returns not results in the source code.

So does this mean that `commons-httpclient` is already not in use?


(Also some requirements are apache-commons `cli`, `codec` and `logging` and no lines showed up on the first grep. Maybe the dependencies can also be rmoved...)

**Comment by rjmateus** [comment]
PR merged, closing this issue
