### ISSUE TITLE
Registering Clients with Proxy still connecting from Master

### ISSUE THREAD

**Issue by makkii86** [uyuni-project/uyuni#5247]
Hi Guys

We want to use a Proxy server in a different tenant that only the Proxy has connection for that environment to the clients. But when we try to add a Server on the WebUi with the Proxy it always try to connect from Master instead of the Proxy:

WARN  com.suse.manager.webui.services.impl.SaltService - SaltSSHError(255, ssh: connect to host XXXX port 22: Connection timed out
 ERROR com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Aborting: needed grains are not found for minion: XXXX

We are registering directly with ssh and without any Agent (all are CentOS systems)

Release is 2022.03

Thanks!

**Comment by makkii86** [comment]
my bad could be solved with a little bit more brain usage

**Comment by benled** [comment]
Can you share some insights about your solution? Running into a similar issue... #5370
