### ISSUE TITLE
Content Lifecycle Filters being ignored.

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#5249]
# Content Lifecycle Filters being ignored 
## Version of Uyuni Server and Proxy (if used)
Uyuni release 2022.03

## Details about the issue
Content Lifecycle Filters being ignored on repositories. Centos 8 servers where yum now shows php 8.1 as available when there is a filter limiting it to php 7.4

Filter Type *: Module (Stream)
Matcher *: equals
Module Name *: php
Stream: remi-7.4

**Comment by cbbayburt** [comment]
I posted an update here: https://github.com/uyuni-project/uyuni/issues/4769#issuecomment-1183767517

I believe this is a duplicate, so let's close this one and track the issue at #4769
