### ISSUE TITLE
Moving to LEAP 15?

### ISSUE THREAD

**Issue by mansam-ger** [uyuni-project/uyuni#528]
Hi,

I just wanted to try out uyuni, but it i asks me to use Leap 42.3 is it planned that the project moves forward to Leap 15?

**Comment by juliogonzalez** [comment]
Hi @mansam-ger.

Yes, we are already working on it at https://build.opensuse.org/project/show/systemsmanagement:Uyuni:Master (as you can see the repositories are for Leap 15 already), but it is not ready yet.

We hope we can complete all the remaining problems within 2/3 weeks maximum, and maybe release if we have a procedure for the migration that it can work at that point.

**Comment by mansam-ger** [comment]
That sounds nice, i will definately test the migration then. At this point I will try it out on OSS 42.3
