### ISSUE TITLE
What is needed to support Ubuntu 22.04 LTS?

### ISSUE THREAD

**Issue by mayrstefan** [uyuni-project/uyuni#5320]
# Short description

Last week Ubuntu 22.04 "Jammy Jellyfish" LTS has been released. What is needed to officially support this new version in Uyuni?

# Details

I guess adding a new operating system falls into two categories
1. things that need to be done by some (openSUSE/Uyuni) internal teams like providing [Client-Tools](https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/)
2. code changes the community can contribute

What can we do to make Ubuntu 22.04 an officially supported OS?

**Comment by mayrstefan** [comment]
Identified source files so far:

- java/code/src/com/redhat/rhn/domain/server/MinionServer.java
- java/code/src/com/suse/manager/reactor/utils/test/productdata/additional_products.json
- java/code/src/com/suse/manager/reactor/utils/test/productdata/productsUnscoped.json (one line, is this generated?)
- java/code/src/com/suse/manager/reactor/utils/test/productdata/product_tree.json
  - Reference to https://updates.suse.com/SUSE/Updates/Ubuntu/
- java/code/src/com/suse/manager/reactor/utils/test/productdata/repositories.json (one line, is this generated?)
- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager-utils/testing/automation/update-obs-environment-cr-project.sh
- testsuite/features/build_validation/core/allcli_sanity.feature
- testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature
- testsuite/features/build_validation/init_clients/ubuntu2004_minion.feature
- testsuite/features/build_validation/init_clients/ubuntu2004_ssh_minion.feature
- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/secondary/min_ubuntu_openscap_audit.feature
- testsuite/features/support/constants.rb
- testsuite/features/support/env.rb
- testsuite/features/support/twopence_init.rb
- testsuite/run_sets/build_validation_init_clients.yml
- utils/spacewalk-common-channels.ini
  - Reference to https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/
- utils/spacewalk-utils.changes

Does it make sense to start adding Ubuntu 22.04 even if the external references don't exist yet?
How are those one line json files generated? They don't look like they should be manually edited.

**Comment by juliogonzalez** [comment]
For the basics, most likely you won't need handle the java package, unless Ubuntu 22.04 has big changes that break the product identification or similar stuff.

If you want to contribute, you can use this as base: https://github.com/uyuni-project/uyuni/pull/4122/files

Most likely you don't need to change `susemanager-sls` as it should work with the generic for Ubuntu, and for sure not `susemanager-sync-data` as that's only relevant for SUSE Manager and not Uyuni.

The PR above does not include the testsuite changes, but maybe  @srbarrios can provide the PR where Debian11 was added.

It doesn't include doc, and that's a separate repository. Maybe @keichwa and @jcayouette can help with that.

From the SUSE part (our developers), we'll need:
- The Salt developers to enable the Bundle for 22.04, I guess we won't have the "classic" package there
- Me to create the client tools OBS projects, and add there the bundle and exporters.

However the PR can be prepared and even tested partially, without the client tools repos (adding the repos with spacewalk-common-channels, syncing should work).

**Comment by tlivolsi** [comment]
Issue #5490 is relevant to this enhancement

**Comment by srbarrios** [comment]
> The PR above does not include the testsuite changes, but maybe @srbarrios can provide the PR where Debian11 was added.

https://github.com/uyuni-project/uyuni/pull/4182

**Comment by juliogonzalez** [comment]
Code is merged. If doc gets ready for 2022.07, it will be part of .07. Otherwise .08 Ping @admd
