### ISSUE TITLE
complete set of parameters with smtp host, port, user and password for SUSE Manager

### ISSUE THREAD

**Issue by mlaguilharre** [uyuni-project/uyuni#5343]
# Short description
complete set of parameters with smtp host, port, user and password for SUSE Manager

# Details

We have a rule that enforce "“An application has to have it own dedicated user and credential to use SMTP servers”

We can define the smtp server in /etc/rhn/rnh.conf. java.smtp_server but we need to define  a complete set of parameters with smtp host, port, user and password .

**Comment by tacerus** [comment]
Hello! Thanks for implementing this! Do you happen to know if it will make it into the stable release? If not, is there a workaround to configure a custom SMTP server with authentication in 2022.08?

**Comment by admd** [comment]
Hi @tacerus, this will be part of the next 2022.10 release which we expect to have early this month if all goes well. There is no easy workaround as this involves code-level changes.

**Comment by tacerus** [comment]
Good to know - thank you for the response!
