### ISSUE TITLE
Adding Ubuntu2004 Base Channel to System results in ERROR: redstone.xmlrpc.XmlRpcFault: Invalid channel 

### ISSUE THREAD

**Issue by bochi** [uyuni-project/uyuni#5354]
# Problem description

I created a base channel for Ubuntu 20.04 using

```spacewalk-common-channels -a amd64-deb ubuntu-2004-pool-amd64-uyuni```

When going to a system in the Uyuni Web UI and selecting "Alter Channel Subscriptions", its not offered as Base Channel. Yet, spacecmd softwarechannel_listbasechannels shows the channel.

When trying to add it to a system using spacecmd I get the following message:

spacecmd {SSM:0}> system_setbasechannel testserver ubuntu-20.04-pool-amd64-uyuni
System:           testserver
Old Base Channel: None
New Base Channel: ubuntu-20.04-pool-amd64-uyuni

Is this ok [y/N]: y
ERROR: redstone.xmlrpc.XmlRpcFault: Invalid channel

Unfortunately there's no more details in the logs as to why Uyuni thinks the channel is invalid.
Furthermore, I created more basechannels using the Web UI as well as using spacecmd. To me it appears that whenever I use "amd64-deb" as architecture Uyuni behaves as described above. Creating a basechannel with x86_64 and the same parameters as above is working fine. 

Uyuni Version is 2022.04 but it also happened before the update with 2022.03

Also, on another testsystem I have I tried the same and it is working, but this system already had amd64-deb Channels with 2021.X versions. 

Please let me know if I can provide any additional logs, rhn_web_api only shows
`2022-05-03 15:50:03,430] INFO  - REQUESTED FROM: 172.17.250.8 CALL: system.getSubscribedBaseChannel(admin, 1000010078) CALLER: (admin) TIME: 0.186 seconds
[2022-05-03 15:50:07,814] INFO  - REQUESTED FROM: 172.17.250.8 CALL: system.setBaseChannel(admin, 1000010078, ubuntu-20.04-pool-amd64-uyuni) CALLER: (admin) TIME: 0.095 seconds
redstone.xmlrpc.XmlRpcFault: Invalid channel`

```uyuni:~ # spacecmd softwarechannel_details ubuntu-20.04-pool-amd64-uyuni
Label:              ubuntu-20.04-pool-amd64-uyuni
Name:               Ubuntu 20.04 LTS AMD64 Base for Uyuni
Architecture:       AMD64 Debian
Parent:             
Systems Subscribed: 0
Number of Packages: 0

Summary
-------
Ubuntu 20.04 LTS AMD64 Base for Uyuni

GPG Key:            
GPG Fingerprint:    
GPG URL:            
GPG CHECK:          True

Repos
-----
External - Ubuntu 20.04 LTS AMD64 Base for Uyuni```

**Comment by juliogonzalez** [comment]
Does it happen if you create the channels with:
```
spacewalk-common-channels ubuntu-2004-pool-amd64-uyuni
```
?

**Comment by juliogonzalez** [comment]
Note https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-ubuntu.html doesn't tell you to use `-a` (in part because we don't support more architectures).

**Comment by bochi** [comment]
> > Yes, it does, already tried that.
> 
> Just to be clear: even using `spacewalk-common-channels ubuntu-2004-pool-amd64-uyuni`, you still get `ERROR: redstone.xmlrpc.XmlRpcFault: Invalid channel` when you try to use the channel as base channel?

Correct.

**Comment by bochi** [comment]
Closing. One should never use experimental systems for reproducing bugs. Compared with my clean uyuni and found the issue, it was a relict of missing alma support which I workarounded in my bootstrap script.
