### ISSUE TITLE
Replace Struts 1 with a maintained version

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#5360]
# Short description

Struts 1.3.10 is EOL since 2013-04-05: https://struts.apache.org/struts1eol-press
Uyuni is using an even older version 1.2.9.

The framework should be replaced with something maintained.

As far as I understand, Struts 2 is not a drop in replacement.

**Comment by admd** [comment]
We don't want to stick with struts but rather migrate to spark. We have quite a few pages which are already migrated and any new pages are based on spark, there is still a long way to go though.
