### ISSUE TITLE
Uyuni 2022.04 -- Automatic RepoSync ignoring http_proxy

### ISSUE THREAD

**Issue by benled** [uyuni-project/uyuni#5367]
# Problem description
The current release does not use a http_proxy for the automated RepoSyncs via TaskOMatic
When running the spacewalk-repo-sync command manually the http_proxy system variable and/or the /etc/sysconfig/proxy are used correctly.

## Version of Uyuni Server and Proxy (if used)
Name           : Uyuni-Server-release
Version        : 2022.04-179.7.uyuni1
Upgraded today as the same issue was already existing in 2022.03
Previously I did a Major Upgrade from about 2021.03, just a week ago.

**Comment by wombelix** [comment]
Sounds familiar, maybe you want to take a look at https://github.com/uyuni-project/uyuni/issues/4850#issuecomment-1075481991

**Comment by benled** [comment]
Thanks for the hint. I can confirm that solved the issue.
Updated: 
```
/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py

  80 APACHE_USER = 'wwwrun'
  81 APACHE_GROUP = 'www'
  82
  83 def find_proxy(self, url, scheme):
  84     urlgrabber_find_proxy(self, url, scheme.decode('utf-8'))
  85
  86 urlgrabber_find_proxy = urlgrabber.grabber.URLGrabberOptions.find_proxy
  87 urlgrabber.grabber.URLGrabberOptions.find_proxy = find_proxy
  88
  89 class ZyppoSync:
  90     """
```

```
/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/download.py
116         (scheme, host, path, parm, query, frag) = parts
117         #opts.find_proxy(url, scheme.decode("utf-8"))
118         opts.find_proxy(url, scheme)
```

And now it seems to work again.
