### ISSUE TITLE
Uyuni 2022.04 -- ssh-push bootstrap no longer working through Uyuni Proxy

### ISSUE THREAD

**Issue by benled** [uyuni-project/uyuni#5370]
# Problem description
All clients are managed via ssh-push behind a Uyuni-Proxy.
Since the Upgrade to 2022.03 (and today to 2022.04)  it is no longer possible to bootstrap new ssh-push manged clients.
When bootstrapping via WI the SSH-Keys, etc. are pushed to the new client, but the system never appear.
In rhn_web_ui.log the following messages are recorded:

```
2022-05-05 15:03:36,674 [ajp-nio-127.0.0.1-8009-exec-2] ERROR com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Aborting: needed grains are not found for minion: newhost.local.intra
2022-05-05 15:08:13,400 [ajp-nio-127.0.0.1-8009-exec-3] WARN  com.suse.manager.webui.services.impl.SaltService - SaltSSHError(255, ssh: connect to host newhost.local.intra port 22: Connection timed out)
```

When watching the processes it is obvious that at one point the Uyuni attempts a direct ssh connection instead of going through the UyuniProxy:
```

salt       2113  0.0  0.1 278000 58988 ?        Ss   11:32   0:01 /usr/bin/python3 /usr/bin/salt-api
salt       2225  2.9  0.5 4281532 241004 ?      Sl   11:32   9:43  \_ /usr/bin/python3 /usr/bin/salt-api
salt      70978  6.7  0.5 4281532 234504 ?      S    16:57   0:00      \_ /usr/bin/python3 /usr/bin/salt-api
salt      71003  0.5  0.0  38500  6420 pts/2    Ss+  16:57   0:00          \_ ssh newhost.local.intra -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=180 -o StrictHostKeyChecking=no -o Port=22 -o IdentityFile=/srv/susemanager/salt/salt_ssh/temp_bootstrap_keys/boostrapKeyTmp-7e3cfbb1-6f6f-4663-8625-625830259dc9 -o User=root -o StrictHostKeyChecking=no -o ProxyCommand=/usr/bin/ssh -p 22 -i /srv/susemanager/salt/salt_ssh/mgr_ssh_id -o StrictHostKeyChecking=no -o User=mgrsshtunnel -W newhost.local.intra:22 uyuniproxy.local.intra  /bin/sh  << 'EOF' [...]
```

```
salt       2113  0.0  0.1 278000 58988 ?        Ss   11:32   0:00 /usr/bin/python3 /usr/bin/salt-api
salt       2225  3.8  0.5 4279412 214172 ?      Sl   11:32   7:26  \_ /usr/bin/python3 /usr/bin/salt-api
salt      48422  0.4  0.4 4279412 204068 ?      S    14:43   0:00      \_ /usr/bin/python3 /usr/bin/salt-api
salt      48423  0.0  0.0  38560  4776 pts/2    Ss+  14:43   0:00          \_ ssh newhost.local.intra -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=180 -o Port=22 -o IdentityFile=/srv/susemanager/salt/salt_ssh/mgr_ssh_id -o User=root /bin/sh  << 'EOF' [...]
```

## Version of Uyuni Server and Proxy (if used)
Name           : Uyuni-Server-release
Version        : 2022.04-179.7.uyuni1

Name           : Uyuni-Proxy-release
Version        : 2022.04-179.7.uyuni1

**Comment by mcalmer** [comment]
@benled I checked the code and now I wonder if that had ever worked. Are you sure it worked with 2022.03? Or did you allow direct acccess to your system from the server and cut it later?

Anyway: we will have a deper look into it.

**Comment by benled** [comment]
@mcalmer I did not work with 2022.03. I did a an upgrade from 2021.05 where it was working fine. But I remember that the same issue was existing in some older releases as well.

Unfortunately I am not familiar enough with all the code, therefore I am wondering where that faulty command is called. If you could give me some hints then I can look for a workaround as well.
