### ISSUE TITLE
Duplicate URL in Bootstrap Link

### ISSUE THREAD

**Issue by iTimo01** [uyuni-project/uyuni#5372]
# Problem description

When Trying to Bootstrap an AlmaLinux 8.5 Client, it throws an exception with a duplicate url
**SaltSSHError(3, Error: Unable to download https://uyuni.example.com:443/pub/repositories/https://uyuni.example.com:443/pub/repositories/almalinux/8/bootstrap/venv-enabled-x86_64.txt file!**

## Version of Uyuni Server and Proxy (if used)

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.04-179.7.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.04-179.7.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

```

## Details about the issue

Steps to Reproduce:

1. Install AlmaLinux 8.5
2. Install Fresh Copy of Uyuni 2022.04 on OpenSuse Leap 15.3
3. Follow doc about registering AlmaLinux clients (https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-almalinux.html) 
4. Follow doc about bootstrapping via webui (https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-webui.html)
5. Error throws while bootstrapping

**Comment by vzhestkov** [comment]
@iTimo01 thanks for finding it.
Could you please test with `preflight.sh` from this PR: https://github.com/uyuni-project/uyuni/pull/5380
just replace `/usr/share/susemanager/salt-ssh/preflight.sh` with the new one from the PR above.

**Comment by iTimo01** [comment]
@vzhestkov Works fine

**Comment by vzhestkov** [comment]
Closing. The PR with the fix was merged already.
