### ISSUE TITLE
Uyuni 2022.03/04 - mgr-create-bootstrap-repo wont find RHEL products

### ISSUE THREAD

**Issue by HerrmannMax** [uyuni-project/uyuni#5376]
# Problem description

Im not able to create a bootstrap-repo with the "mgr-create-bootstrap-repo" for RHEL 7 and RHEL 8.

## Version of Uyuni Server
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.04-179.7.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2022.02-171.1.uyuni1 installed)
Source package : Uyuni-Server-release-2022.04-179.7.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about the issue  
This behavior occured already in version 2022.03 and the update to 2022.04 didn't changed it.
Sadly I dont know if this occured in earlier versions.
Running " psql -U uyuni -d uyuni -c 'select label from rhnChannel where parent_channel IS null and org_id IS NOT NULL' " shows that there is a rhel7 channel

```
uyuni-server:~ # psql -U uyuni -d uyuni -c 'select label from rhnChannel where parent_channel IS null and org_id IS NOT NULL'
Password for user uyuni:
          label
--------------------------
 opensuse_leap15_3-x86_64
 rhel7-pool-x86_64
 centos7-x86_64
 rhel-base
(4 rows)
uyuni-server:~ #
```

#5150 already gave the solution by editing /usr/share/susemanager/mgr_bootstrap_data.py, removing the PDID reference and adding the name of the basechannel directly, but i dont think this issue should be closed  
```
uyuni-server:/usr/share/susemanager # diff mgr_bootstrap_data-rhel7_custom.py mgr_bootstrap_data.py
1423c1425
<         'BASECHANNEL' : 'rhel7-pool-x86_64', 'PKGLIST' : RES7 + RES7_X86,
---
>         'PDID' : [-7, 1683], 'BETAPDID' : [2065], 'PKGLIST' : RES7 + RES7_X86,
```
Is there maybe an issue with the mapping PDID's or need RHEL Parent Channels to be named in a specific pattern to get detected?

Thanks for your help!

**Comment by juliogonzalez** [comment]
> Im not able to create a bootstrap-repo with the "mgr-create-bootstrap-repo" for RHEL 7 and RHEL 8.

You are not telling what the problem is: packages not found? Channels not found? A stacktrace?

My guess is Red Hat does not show in the list.

> https://github.com/uyuni-project/uyuni/issues/5150 already gave the solution by editing /usr/share/susemanager/mgr_bootstrap_data.py, removing the PDID reference and adding the name of the basechannel directly, but i dont think this issue should be closed

The definitions you edited are for SUSE Manager, not Uyuni, and will be overwritten by the next Uyuni release.

Looks to me the problem is that https://github.com/uyuni-project/uyuni/blob/master/susemanager/src/mgr_bootstrap_data.py is missing definitions for RHEL for Uyuni itself.

Please rollback and add:

```
    'RHEL7-x86_64-uyuni' : {
        'BASECHANNEL' : 'rhel7-pool-x86_64', 'PKGLIST' : RES7 + RES7_X86,
        'DEST' : DOCUMENT_ROOT + '/pub/repositories/res/7/bootstrap/'
    },
    'RHEL8-x86_64-uyuni' : {
        'BASECHANNEL' : 'rhel8-pool-x86_64', 'PKGLIST' : RES8 + RES8_X86,
        'DEST' : DOCUMENT_ROOT + '/pub/repositories/res/8/bootstrap/'
    },    
```
If you followed https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-overview-redhat.html, it should work.

If you confirm this fixed the issue, I will prepare a Pull Request.

**Comment by HerrmannMax** [comment]
> My guess is Red Hat does not show in the list.
Correct, it just didn't showed up. I'm sorry I don't know how I could forgot this...

But your solution works like a charm. I just added it and now the Repos get build.
Thank you!

**Comment by juliogonzalez** [comment]
Thanks for the feedback :-)

I will prepare a PR, so we can have the fix at 2022.06.

**Comment by saquib-akhtar** [comment]
spacewalk:/srv/www/htdocs/pub/repositories/res/7/bootstrap # mgr-create-bootstrap-repo --with-custom-channels  -f -d
1. RHEL7-x86_64-uyuni
2. RHEL8-x86_64-uyuni
3. SLE-12-SP5-x86_64
4. SLE-15-SP2-x86_64
5. SLE-15-SP3-x86_64
6. centos-7-x86_64-uyuni
7. oracle-7-x86_64-uyuni
8. oracle-8-x86_64-uyuni
Enter a number of a product label: 1

Creating bootstrap repo for latest Service Pack of RHEL7-x86_64-uyuni
copy 'python-jinja2-2.7.2-4.el7.noarch'
copy 'python-requests-2.6.0-10.el7.noarch'
copy 'python-setuptools-0.9.8-7.el7.noarch'
copy 'python-singledispatch-3.4.0.2-2.el7.noarch'
copy 'python-tornado-4.2.1-5.el7.x86_64'
copy 'python-tornado-2.2.1-8.el7.noarch'
copy 'zeromq-4.1.4-6.el7.x86_64'
copy 'python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch'
copy 'python-backports-1.0-6.el7.noarch'
copy 'python-backports-1.0-8.el7.x86_64'
copy 'PyYAML-3.10-11.el7.x86_64'
copy 'python-markupsafe-0.11-10.el7.x86_64'
copy 'python-urllib3-1.10.2-7.el7.noarch'
copy 'libyaml-0.1.4-11.el7_0.i686'
copy 'libyaml-0.1.4-11.el7_0.x86_64'
copy 'python-chardet-2.2.1-3.el7.noarch'
copy 'python-six-1.9.0-2.el7.noarch'
copy 'python-babel-0.9.6-8.el7.noarch'
copy 'yum-rhn-plugin-2.0.1-10.el7.noarch'
copy 'yum-3.4.3-168.el7.noarch'
copy 'openssl-1.0.2k-25.el7_9:1.x86_64'
copy 'openssl-libs-1.0.2k-25.el7_9:1.x86_64'
copy 'openssl-libs-1.0.2k-25.el7_9:1.i686'
copy 'python-ipaddress-1.0.16-2.el7.noarch'
copy 'redhat-rpm-config-9.1.0-88.el7.noarch'
copy 'rpm-python-4.11.3-48.el7_9.x86_64'
copy 'dmidecode-3.2-5.el7_9.1:1.x86_64'
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Directory walk started
Directory walk done - 27 packages
Temporary output repo path: /srv/www/htdocs/pub/repositories/res/7/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
ERROR: package 'salt' not found
ERROR: package 'salt-minion' not found
ERROR: package 'python2-salt' not found
ERROR: package 'python-futures' not found
ERROR: package 'python-msgpack-python' not found
ERROR: package 'python-psutil' not found
ERROR: package 'python-pycrypto' not found
ERROR: package 'python-zmq' not found
ERROR: package 'python-certifi' not found
ERROR: package 'python-simplejson' not found
ERROR: package 'python2-rhnlib' not found
ERROR: package 'spacewalk-check' not found
ERROR: package 'python2-spacewalk-check' not found
ERROR: package 'spacewalk-client-setup' not found
ERROR: package 'python2-spacewalk-client-setup' not found
ERROR: package 'spacewalk-client-tools' not found
ERROR: package 'python2-spacewalk-client-tools' not found
ERROR: package 'python2-uyuni-common-libs' not found
ERROR: none of 'mgr-daemon', 'spacewalksd' found
ERROR: package 'suseRegisterInfo' not found
ERROR: package 'python2-suseRegisterInfo' not found
ERROR: package 'python2-hwdata' not found
ERROR: package 'venv-salt-minion' not found

Suggestions:
mgr-create-bootstrap-repo uses the locally synchronized versions of files
from the Tools repository, and uses the locally synchronized pool channel
for dependency resolution.
Both should be fully synced before running the mgr-create-bootstrap-repo script.

**Comment by saquib-akhtar** [comment]
What should I do above as it cannot find required packages neither for RHEL 7 nor for RHEL 8 ?
