### ISSUE TITLE
failure creating containerized proxy config if client exists in Uyuni

### ISSUE THREAD

**Issue by dvosburg** [uyuni-project/uyuni#5385]
# Problem description
Creating a configuration .zip file fails from both webUI and CLI.  Output from cli:
brie:/var/log/rhn # spacecmd proxy_container_config_generate_cert -- cornelius.ad.libertyonline.org brie.libertyonline.org 4096 admin@libertyonline.org
INFO: Connected to https://brie.libertyonline.org/rpc/api as admin
SSL CA private key password: 
ERROR: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: File not found: /var/cache/tomcat/temp/ssltool14232356529336192959/cornelius/server.crt

WebUI reports this:
Server error, please check log files.

Attaching rhn_web_ui.log

_The following information is very important in order to help us to understand your problem. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
2022.04

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.04-179.7.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.04-179.7.uyuni1.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about the issue

Tried several times - once with the wrong password for the CA.
[rhn_web_ui.log](https://github.com/uyuni-project/uyuni/files/8645548/rhn_web_ui.log)

_Include as many details as you can. The procedure you are following, the commands you are running, log messages (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help someone to reproduce the issue or understand it._

**Comment by cbosdo** [comment]
Not finding the `server.crt` file means the SSL certificate generation failed. Could you try creating a temporary folder with the CA cert and key as `ca.crt` and `ca.key` files and run the following command on the server:

    rhn-ssl-tool --gen-server -q --no-rpm -d /path/to/tmp/dir --ca-cert /path/to/tmp/dir/ca.crt \
        --ca-key /path/to/tmp/dir-ca.key --set-hostname your.proxy.fqdn

I would be interested in the result code and the list of files created in the temporary folder.

**Comment by cbosdo** [comment]
@dvosburg I'm curious about the ssl packages you have. This error is fishy:

2022-05-07 11:53:38,709 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] ERROR com.redhat.rhn.frontend.xmlrpc.proxy.ProxyHandler - Failed to generate SSL certificate
com.suse.manager.ssl.SSLCertGenerationException: /usr/lib64/python3.6/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
CA password: 

web server's SSL certificate generation/signing failed:

> Using configuration from /var/cache/tomcat/temp/ssltool13614105760491137378/rhn-ca-openssl.cnf
> unable to load CA private key
> 139748481591104:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:630:
139748481591104:error:0906A065:PEM routines:PEM_do_header:bad decrypt:crypto/pem/pem_lib.c:461:
