### ISSUE TITLE
registry for containerized proxy pointing to non-existent directory

### ISSUE THREAD

**Issue by dvosburg** [uyuni-project/uyuni#5387]
# Problem description
After installing 'uyuni-proxy-systemd-services-4.3.2-2.1.uyuni', the included '/etc/sysconfig/uyuni-proxy-systemd-services' points to a non-existent namespace:
NAMESPACE=registry.opensuse.org/systemsmanagement/uyuni/stable/containers/uyuni

If I change it to:
NAMESPACE=registry.opensuse.org/uyuni

Everything works.

_The following information is very important in order to help us to understand your problem. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
2022.04

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.04-179.7.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.04-179.7.uyuni1.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about the issue

Tried to navigate through registry.opensuse.org to the provided URI and it does not exist.

_Include as many details as you can. The procedure you are following, the commands you are running, log messages (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help someone to reproduce the issue or understand it._

**Comment by cbosdo** [comment]
indeed, looks like those have been replaced by the short ones. We'll fix it! thanks for the report 🙏🏻
