### ISSUE TITLE
After client bootstrap some Centos7 are not present/registered as 'System' in UI although Salt connection exists and minion key is accepted

### ISSUE THREAD

**Issue by cbalan58** [uyuni-project/uyuni#5461]
# Problem description

I ran bootstrap from client since our servers have root's ssh disabled and after script finished OK i accepted in Uyuni UI the Salt key. However, unlike previous systems, the last 2 (both Centos 7.9.2009) are not showing up at all in System Overview.

## Version of Uyuni Server  - no proxy
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.04-179.7.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.09-141.3.uyuni1 installed)
Source package : Uyuni-Server-release-2022.04-179.7.uyuni1.src

## Details about the issue

The issue appeared after local bootstrap of client when going in UI -> Salt, to accept the key for new system there was a glitch in the view of salt clients: accepting the key for new one, after few seconds refresh of page made an older system to dissapear and then come back as if key was not accepted. Accepting again the key for the old system lef the key for the new one also, but then, the new system would not be present in Systems. Tried then with another different client - ran the bootstrap locally on client, then in Uyuni UI accepted the new key but same glitch happened.
None of the clients have ever been registered to another Salt master.

What probably is the issue, is visible from /var/log/rhn/rhn_web_ui.log
/var/log/rhn/rhn_web_ui.log:2022-05-13 15:23:19,671 [salt-event-thread-4] WARN  com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Minion 'nfv-mil3-test-restore' already registered, updating profile to '<redacted: new minion>' [14634b0ca9944683b8e1063c6ce1abc4]
On client, the minion_id shows the correct value (its hostname).

Testing, i removed one old system and then used same steps to re-add it and there was no issue.
Since new clients are not "systems" i cannot remove their profile, but i removed their Salt key and ran the bootstrap again. Again, their Salt key appears in UI waiting to be accepted but then one older system would dissapear and need to be acccepted back when reapearing and new clients are not registered as systems.

Maybe interesting:
After few days of tests, i applied the states that i saw mentioned as being applied to a new client: 
util.systeminfo, certs, channels, channels.disablelocalrepos, packages and services.salt-minion.

Channels would fail at first because:
rpm --import https:**//:**443/pub/res-gpg-pubkey-0182b964.key 
rpm --import https**://:**443/pub/sle12-gpg-pubkey-39db7c82.key # so there is no name for the uyuni server - solved it by importing manually the keys on client;

Channels.disablelocalrepos would fail due to not met requirement:
The following requisites were not found:
                                 require:
                                     saltutil: sync_states # after disabling the requirement in sls file it ran ok, also if running just 'state.apply util.syncstates' against minion it would return ok;

And lastly, services.salt-minion fails due to what i saw online being mentioned as a pillar issue, but how would be changed? No idea. Failure msg:
          ID: /etc/venv-salt-minion/minion.d/susemanager.conf
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.context.NamespacedDictWrapper object' has no attribute 'mgr_server'
I overwrote the client's susemanager.conf file with the content from older client that works but this didn't make the salt state finish OK.

**Comment by wombelix** [comment]
Maybe you should consider upgrading to Uyuni 2022.05, I think some of the issue you observed are fixed in that version already.

Regarding `com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Minion 'nfv-mil3-test-restore' already registered, updating profile to '<redacted: new minion>' [14634b0ca9944683b8e1063c6ce1abc4]`, can you please check if the Clients maybe have the same machine id and therefore not show up as new system but just overwrite an existing one?

See: https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/tshoot-registerclones.html

**Comment by cbalan58** [comment]
> Maybe you should consider upgrading to Uyuni 2022.05, I think some of the issue you observed are fixed in that version already.
> 
> Regarding `com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Minion 'nfv-mil3-test-restore' already registered, updating profile to '<redacted: new minion>' [14634b0ca9944683b8e1063c6ce1abc4]`, can you please check if the Clients maybe have the same machine id and therefore not show up as new system but just overwrite an existing one?
> 
> See: https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/tshoot-registerclones.html

Thank you Dominik, i don't know how/why i skipped that check - machine IDs were same and once new generated + salt restart, the registration finished OK.
I'll add the steps to generate new ID in the bootstrap script and that should solve my issue.
Thanks again!
