### ISSUE TITLE
Proxy installation on openSUSE Leap 15.3 fails at patterns-uyuni_proxy step 

### ISSUE THREAD

**Issue by cbalan58** [uyuni-project/uyuni#5476]
# Problem description

I am installing a fresh new proxy and am at the step: "Install the pattern for the Uyuni Proxy: As root enter:
zypper in patterns-uyuni_proxy" - from https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/install-proxy-uyuni.html
Yet, system replies that: "Problem: nothing provides 'supportconfig-plugin-resource' needed by the to be installed supportutils-plugin-susemanager-proxy-4.3.2-1.1.uyuni1.noarch
 Solution 1: do not install patterns-uyuni_proxy-2022.05-1.1.uyuni1.x86_64
 Solution 2: break supportutils-plugin-susemanager-proxy-4.3.2-1.1.uyuni1.noarch by ignoring some of its dependencies"

All steps for proxy install were followed and finished OK, until now.
On opensuse page for this package i found that "There is no official package available for openSUSE Leap 15.3" - https://software.opensuse.org/package/supportutils-plugin-susemanager-proxy - yet Uyuni documentation mentions same Leap version as ok for proxy installation - https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/install-proxy-uyuni.html
I don't want to enter some package conflict and am not aware how important is this step in proxy configuration, so am pending on what actions to do next.

## Version of Uyuni Server and Proxy (if used)

zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.05-180.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2021.09-141.3.uyuni1 installed)
Source package : Uyuni-Server-release-2022.05-180.1.uyuni1.src
Summary        : Uyuni Server

zypper info Uyuni-Proxy-release
Loading repository data...
Reading installed packages...
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : uyuni-proxy-stable
Name           : Uyuni-Proxy-release
Version        : 2022.05-180.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : No
Status         : not installed
Source package : Uyuni-Proxy-release-2022.05-180.1.uyuni1.src
Summary        : Uyuni Proxy

## Details about the issue

--- End of bootstrap for proxy - nothing went wrong:
]
Executing %posttrans scripts ..................................................................[done]
salt-3002.2-150300.53.16.1.x86_64
salt-minion-3002.2-150300.53.16.1.x86_64
Loading repository data...
Reading installed packages...
No update candidate for 'openssl-1.1.1d-1.46.noarch'. The highest available version is already installed.
No update candidate for 'zypper-1.14.52-150200.30.2.x86_64'. The highest available version is already installed.
No update candidate for 'salt-3002.2-150300.53.16.1.x86_64'. The highest available version is already installed.
No update candidate for 'salt-minion-3002.2-150300.53.16.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.

REGISTRATION
------------
* registering
Using activation key: 1-opensuse153
* removing TLS certificate used for bootstrap
  (will be re-added via salt state)
* starting salt daemon and enabling it during boot
Created symlink /etc/systemd/system/multi-user.target.wants/salt-minion.service → /usr/lib/systemd/system/salt-minion.service.
-bootstrap complete-

### --- adding proxy repo went OK too:
zypper ar https://download.opensuse.org/$repo uyuni-proxy-stable
Adding repository 'uyuni-proxy-stable' ........................................................[done]
Repository 'uyuni-proxy-stable' successfully added
URI         : https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Proxy-POOL-x86_64-Media1/
Enabled     : Yes
GPG Check   : Yes
Autorefresh : No
Priority    : 99 (default priority)

### --- Attempt to chose option 2 and break supportutils resulted in more packages being "not found":
 zypper in patterns-uyuni_proxy
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'supportconfig-plugin-resource' needed by the to be installed supportutils-plugin-susemanager-proxy-4.3.2-1.1.uyuni1.noarch
 Solution 1: do not install patterns-uyuni_proxy-2022.05-1.1.uyuni1.x86_64
 Solution 2: break supportutils-plugin-susemanager-proxy-4.3.2-1.1.uyuni1.noarch by ignoring some of its dependencies
Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2
Resolving dependencies...
Resolving package dependencies...

Problem: nothing provides 'supportconfig-plugin-resource' needed by the to be installed supportutils-plugin-susemanager-client-4.3.2-1.1.uyuni1.noarch
 Solution 1: do not install patterns-uyuni_proxy-2022.05-1.1.uyuni1.x86_64
 Solution 2: break supportutils-plugin-susemanager-client-4.3.2-1.1.uyuni1.noarch by ignoring some of its dependencies
Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2
Resolving dependencies...
Resolving package dependencies...

Problem: nothing provides 'httpd' needed by the to be installed spacewalk-proxy-redirect-4.3.9-1.1.uyuni1.noarch
 Solution 1: do not install patterns-uyuni_proxy-2022.05-1.1.uyuni1.x86_64
 Solution 2: break spacewalk-proxy-redirect-4.3.9-1.1.uyuni1.noarch by ignoring some of its dependencies
Choose from above solutions by number or cancel [1/2/c/d/?] (c): c

### --- spacecmd 'system_details' returns OK the channels that proxy was registered with:
Software Channels
-----------------
opensuse_leap15_3-x86_64
  |-- opensuse_leap15_3-uyuni-client-x86_64
  |-- opensuse_leap15_3-x86_64-non-oss
  |-- opensuse_leap15_3-x86_64-non-oss-updates
  |-- opensuse_leap15_3-x86_64-updates
  |-- uyuni-proxy-stable-leap-153-x86_64

Entitlements
------------
salt_entitled

**Comment by mcalmer** [comment]
Hmm, seems that openSUSE Leap 15.3 miss repositories.  AFAIK there should be a sle-updates and a backports-update repository.

**Comment by cbalan58** [comment]
Thank you Michael, not sure exactly which repo was not enabled because i searched first for backports and updates that weren't enabled, enabled them and patterns still failed. But then i enabled also the debug ones and to be safe i enabled all of them (except the one that came from install cd) and then the patterns was installed OK.
