### ISSUE TITLE
SSL cert of proxy is deinstalled through highstate

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#5477]
# Problem description

_The following information is very important in order to help us to understand your problem. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.05-180.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.05-180.1.uyuni1.src
Summary        : Uyuni Server

Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.3 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2022.05-180.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Proxy-release-2022.05-180.1.uyuni1.src
Summary        : Uyuni Proxy

## Details about the issue

_Include as many details as you can. The procedure you are following, the commands you are running, log messages (specially from_ `/var/log/rhn/`_)..._
_In general: all that can help someone to reproduce the issue or understand it._

After upgrading to uyuni 2022.05 the proxy ssl cert is deinstalled every time via highstate:

----------
          ID: mgr_absent_ca_package
    Function: pkg.removed
        Name: rhn-org-trusted-ssl-cert
      Result: true
     Comment: All targeted packages were removed.
     Started: 09:29:45.778487
    Duration: 69192.152
         SLS: certs
     Changed: rhn-org-trusted-ssl-cert:
                  new: ''
                  old: 1.0-1
              
----------
          ID: mgr_ca_cert
    Function: file.managed
        Name: /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT
      Result: true
     Comment: File /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT updated
     Started: 09:30:54.998602
    Duration: 81.734
         SLS: certs
     Changed: diff: New file
              mode: '0644'

at the end /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT is missing and no client can connect to the proxy. I have to reinstall the rpm by hand (zypper install /root/ssl-build/rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm).

how can I prevent the ssl cert proxy rpm deinstallation at highstate?

I can't do the re-registration via rhnreg_ks (like the docs said):

rhnreg_ks -v --activationkey=re-1-14c651c0b39f4b95d83edcb12825d10d --force
rhn-plugin: Error communicating with server. The message was:

Error Message:
    This system is already registered as a Salt Minion. If you want to register it as a traditional client
    please delete it first via the web UI or API and then register it using the traditional tools.
Error Class Code: 48
Error Class Info:
    This system is already registered as a Salt Minion. If you want to register it as a traditional client
    please delete it first via the web UI or API and then register it using the traditional tools.
Explanation:
     An error has occurred while processing your request. If this problem
     persists please enter a bug report at scc.suse.com.
     If you choose to submit the bug report, please be sure to include
     details of what you were trying to do when this error occurred and
     details on how to reproduce this problem.

**Comment by mrstigmata** [comment]
should I add the CA file to the configuration channel and deploy it via that mechanism?

**Comment by mcalmer** [comment]
What mechanism do you want to use?

I see you use `rhnreg_ks` which is the traditional stack. This is not supported and will be removed soon.
You you say that you use "highstate". This is salt managed and for this the CA is deployed automatically.

Do not mix these both.

As you also wrote, the CA gets deployed at /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT

In /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT should be a symlink to this file.
Maybe that is missing?

configure-proxy.sh create this symlink.
Maybe it was traditional registered, proxy was conigured, after that you switched to salt management and the package was removed and nothing created the symlink.

**Comment by mrstigmata** [comment]
sorry but I'm a bit confused now. Is there a document that describes this change? 
after the last uyuni upgrade the rpm at the proxy is remove via highstate, so the connection from the clients are no longer possible because of missing cert. at the same point the proxy is no more connected to the configuration channel [rhn_proxy_config_<systemid>] at the uyuni server. the proxy ssl cert wasn't moved to the configuration channel.

I just want to understand what I have to do to "survive" the next highstate ;) shoud I re-create the config channel via confiure-proxy.sh at the proxy? should I manually add the ssl cert to the proxy config channel? I didn't see a hint at the release notes. the cert is already linked: /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT -> /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT 

executing rhnreg_ks is a step at the docu: https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/proxy-uyuni.html#_upgrade_the_proxy - thats why I tried to executed it.

**Comment by mcalmer** [comment]
That's definitiv a doc bug :-)

I am on the way to prepare a state to create the symlink. When the rpm package gets removed and the system is a proxy, the symlink should be created.
I would suggest you just call:

```
$> ln -s /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
```

**Comment by mrstigmata** [comment]
do have any hint about the config-channel?
