### ISSUE TITLE
Receiving many "missing required part in given .deb" errors when syncing Ubuntu 22.04 repositories

### ISSUE THREAD

**Issue by tlivolsi** [uyuni-project/uyuni#5490]
# Problem description

I receive the following error many times when trying to sync repository packages for Ubuntu 22.04, with only a fraction of the packages being linked properly:

`2022/05/23 21:21:11 -05:00 missing required part in given .deb (expected one of: ['control.tar.gz', 'control.tar.bz2', 'control.tar.xz', 'control.tar.lzma', 'control.tar'])`

## Version of Uyuni Server and Proxy (if used)

Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.05-180.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.05-180.1.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about the issue

Attached is the log file for the following command:
`spacewalk-repo-sync -vvv --channel ubuntu-2204-amd64-main`

Let me know if you have any questions. Thank you in advance for your help and time!

[ubuntu-2204-amd64-main.log](https://github.com/uyuni-project/uyuni/files/8759246/ubuntu-2204-amd64-main.log)

**Comment by mcalmer** [comment]
Seems they use now `control.tar.zst`

**Comment by meaksh** [comment]
This error message is coming from `python3-debian` package (which is used for reading the headers of DEB packages).

We currently used version `0.1.31` coming from Leap, we would need to update this to newer versions (latest is 0.1.43): https://salsa.debian.org/python-debian-team/python-debian/-/tags

**Comment by mcalmer** [comment]
We need to remember that the package needs to add `Requires: zstd` . They use the commandline tool to uncompress things.

**Comment by mayrstefan** [comment]
The package is coming from the SUSE Package Hub 15 SP3 repository. There is no package for SP4 yet and I guess SLES15 SP4 may be released next month. So maybe this is the chance to create a new version of the package for SP4 and backport the changes to SP3

**Comment by juliogonzalez** [comment]
The update to `python-debian` to 0.1.44 fixes reposync. I did a SR that should go to openSUSE:Factory soon (https://build.opensuse.org/request/show/985321)

However the backport to SLE (and openSUSE) is a different story. I am quite sure we'll be able to have it only at SP4, because the 0.1.44 does not support Debian anymore. The internal ECO will handle this.

But in the end, for Uyuni, having the package at SP4 is enough (so openSUSE Leap 15.4 can get it).

**Comment by juliogonzalez** [comment]
The update is now released, so I am going to close the issue:

```
$ rpm -q --changelog python3-python-debian|grep zstd
  * Add support for zstd compression in .deb files
  * Update packaging for zstd compressed .deb code
```

The support for Ubuntu 22.04 is not at Uyuni 2022.06, but it will be part of the upcoming 2022.07.
