### ISSUE TITLE
Salt state execution error when Uyuni tries to read contents of Ansible inventory file

### ISSUE THREAD

**Issue by tlivolsi** [uyuni-project/uyuni#5507]
# Problem description

I receive a lengthy error (see below) when Uyuni tries to read the contents of an Ansible inventory file that exists on our Ansible control node.

## Version of Uyuni Server and Proxy (if used)

Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.05-180.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.05-180.1.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.`

## Details about the issue

The Ansible control node is running CentOS 7 if this helps. The only thing that I see in the logs that might be related to this is the message in venv-salt-minion.log
`[salt.minion      :1972][WARNING ][71403] The minion function caused an exception`

```
Error when executing salt state: The minion function caused an exception: Traceback (most recent call last): File "/usr/lib/venv-salt-minion/lib64/python3.9/site-packages/salt/minion.py", line 1894, in _thread_return return_data = minion_instance._execute_job_function( File "/usr/lib/venv-salt-minion/lib64/python3.9/site-packages/salt/minion.py", line 1851, in _execute_job_function return_data = self.executors[fname](opts, data, func, args, kwargs) File "/usr/lib/venv-salt-minion/lib/python3.9/site-packages/salt/executors/venv.py", line 26, in execute return __executors__["direct_call.execute"](opts, data, func, args, kwargs) File "/usr/lib/venv-salt-minion/lib/python3.9/site-packages/salt/executors/direct_call.py", line 12, in execute return func(*args, **kwargs) File "/usr/lib/venv-salt-minion/lib/python3.9/site-packages/salt/modules/ansiblegate.py", line 459, in targets return __utils__["ansible.targets"](**kwargs) File "/usr/lib/venv-salt-minion/lib/python3.9/site-packages/salt/utils/ansible.py", line 44, in targets return salt.utils.json.loads(salt.utils.stringutils.to_str(inv)) File "/usr/lib/venv-salt-minion/lib64/python3.9/site-packages/salt/utils/json.py", line 97, in loads return json_module.loads(s, **kwargs) File "/usr/lib/venv-salt-minion/lib64/python3.9/json/__init__.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/venv-salt-minion/lib64/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/venv-salt-minion/lib64/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1) 
```

**Comment by mcalmer** [comment]
@tlivolsi 
`json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)`
This sounds like a problem in the inventory file itself. Are you sure it has correct formatted Json?

CC @meaksh

**Comment by aaannz** [comment]
@tlivolsi Any feedback from your side?

**Comment by tlivolsi** [comment]
@mcalmer @aaannz Apologies for the late reply. I missed mcalmer's message. I converted the inventory file to Json, and passed it through a Json validator to confirm that it's formatted correctly. I still encounter the same issue however.

**Comment by vzhestkov** [comment]
@tlivolsi have you tried to check the output of the command from the previous commend?

**Comment by meaksh** [comment]
I double check that this is working fine on CentOS7 with `venv-salt-minion` and `ansible` package coming from EPEL:

```console
[root@8a117ac59773 ~]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
[root@8a117ac59773 ~]# rpm -qa | grep salt
venv-salt-minion-3004-13.1.uyuni.x86_64
[root@8a117ac59773 ~]# ansible-inventory --list --export /etc/ansible/hosts
{
    "_meta": {
        "hostvars": {}
    }, 
    "all": {
        "children": [
            "ungrouped"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "foobar", 
            "testserver"
        ]
    }
}
[root@8a117ac59773 ~]# venv-salt-call --local ansible.targets
local:
    ----------
    _meta:
        ----------
        hostvars:
            ----------
    all:
        ----------
        children:
            - ungrouped
    ungrouped:
        ----------
        hosts:
            - foobar
            - testserver
[root@8a117ac59773 ~]# 
```

As mentioned, there is probably a problem with the particular inventory file that is being parsed, making `ansible-inventory` to not produce a clean output.

I'm closing this one as it seems everything works as expected. Feel free to reopen this if you consider this is still a valid issue.

Thanks!
