### ISSUE TITLE
Building a new Environment Lifecycle version for a Content Lifecycle Project without using the Uyuni GUI.

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#5548]
# Question
Is there mechanism, outside of the Uyuni GUI, to initiate the build of a new Environment Lifecycle version for a Content Lifecycle Project? In other words, is there some other way than having to manually press the "Build (version#)" button?
We are looking to automate building an ELC version and GUI buttons don't work very well for that. We did check out the `spacewalk-manage-channel-lifecycle` command, but based on its option set it maybe doesn't appear to be exactly what we are looking for. Any guidance is much appreciated. Thanks!
## Version of Uyuni Server and Proxy (if used)

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.05-180.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.05-180.1.uyuni1.src
Summary        : Uyuni Server

Not running Uyuni-Proxy.

**Comment by mcalmer** [comment]
`https://uyuni-server.domain.top/rhn/apidoc/handlers/ContentManagementHandler.jsp`

This is our API where you can use all features of CLM to write automation scripts.
Original only XMLRPC API, but now also available via HTTP and Json. Check the Sample Scripts at the end.
To use JSON over HTTP API, please install the latest version as this feature is really new.

**Comment by gabjef** [comment]
> `https://uyuni-server.domain.top/rhn/apidoc/handlers/ContentManagementHandler.jsp`
> 
> This is our API where you can use all features of CLM to write automation scripts. Original only XMLRPC API, but now also available via HTTP and Json. Check the Sample Scripts at the end. To use JSON over HTTP API, please install the latest version as this feature is really new.

Awesome!
The answer was always right there in front me, just a couple of mouse clicks away. Man, I missed the boat on that one.
Thanks for pointing me in the right direction @mcalmer

**Comment by gabjef** [comment]
Closing this "issue".
We really appreciate the support from the Uyuni team.
