### ISSUE TITLE
spacewalk-config posttrans has errors

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#5606]
# Problem description

_The following information is very important in order to help us to understand your problem. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.06-183.9.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.06-183.9.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

## Details about the issue

While installing the pattern:
```
diff: /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT: No such file or directory
diff: /srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT: No such file or directory
cp: cannot stat '/srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT': No such file or directory
warning: %posttrans(spacewalk-config-4.3.8-1.9.uyuni2.noarch.rpm) scriptlet failed, exit status 1
```
Seeems to be caused by https://github.com/uyuni-project/uyuni/commit/c5bc6107ababbb0519f8735449eaa1fe90293ee7

Other than that, the pattern installation worked, I could run the YaST2 setup, start the WebUI and create the first user.

Since @nodeg could not see problems at the testsuite while preparing the validation for 2022.06, most likely this is harmless, but it should be fixed anyway.

**Comment by mbussolotto** [comment]
PR reviewed, waiting CI tests
