### ISSUE TITLE
Route Configuration

### ISSUE THREAD

**Issue by MHamza-07** [uyuni-project/uyuni#5638]
Hello,

I am working with OEL 8.6 and configuring gateway statically.

![netstae1](https://user-images.githubusercontent.com/85833913/177535763-1ead725e-f650-4f0e-8d65-14fbd92098b3.png)

the configuration works fine until I reboot the machine.
![netstate2](https://user-images.githubusercontent.com/85833913/177535886-bc6d3d2c-3d8a-4a12-b0e9-daf24fb405b5.jpg)

as you can see, after rebooting there is another entry added with the same ifname but different gateway. Even after deleting this duplicated entry when I reboot the machine it appear again and pinging got stopped.

I want this entry to be deleted permanently and never to be fetched again on reboot.

**Comment by mbussolotto** [comment]
Hi @MHamza-07,

I'm missing something.. why is a Uyuni issue? Did you use salt to configure static gateway?

Thanks

**Comment by MHamza-07** [comment]
I only used route command to configure gateway.

**Comment by mbussolotto** [comment]
Closing cause it's not a uyuni issue
