### ISSUE TITLE
Package versions not matching the CLM filter are included (again) - Uyuni 2022.06

### ISSUE THREAD

**Issue by cseres3** [uyuni-project/uyuni#5658]
# Problem description
The same problem than in #4533 which seemed to be fixed at some point. Package versions not matching the CLM filter are included in builds and because of that yum updates on AlmaLinux 8 clients fail.

I was not sure what is the correct procedure, but I opened a new ticket instead of editing the old one.

## Version of Uyuni Server and Proxy (if used)

Uyuni-Server-release 2022.06-183.9.uyuni2

## Details about the issue
almalinux-release-8.6-2.el8.x86_64 is the latest AlmaLinux version included in the source channel.

Software Channels: AlmaLinux 8 (x86_64) AlmaLinux 8 PowerTools (x86_64) AlmaLinux 8 AppStream (x86_64) Uyuni Client Tools for AlmaLinux 8 (x86_64) AlmaLinux 8 Extras (x86_64) EPEL 8 for AlmaLinux 8 (x86_64) Software Filter: php74-filter: enable module php:7.4 a8-clm-module-scala: enable module scala:2.10 a8-clm-module-idm: enable module idm:client a8-clm-module-llvm-toolset: enable module llvm-toolset:rhel8 a8-clm-module-gimp: enable module gimp:2.8 a8-clm-module-python27: enable module python27:2.7 a8-clm-module-varnish: enable module varnish:6 a8-clm-module-jmc: enable module jmc:rhel8 a8-clm-module-rust-toolset: enable module rust-toolset:rhel8 a8-clm-module-freeradius: enable module freeradius:3.0 a8-clm-module-perl-DBD-MySQL: enable module perl-DBD-MySQL:4.046 a8-clm-module-ant: enable module ant:1.10 a8-clm-module-perl-App-cpanminus: enable module perl-App-cpanminus:1.7044 a8-clm-module-mysql: enable module mysql:8.0 a8-clm-module-ruby: enable module ruby:2.5 a8-clm-module-mailman: enable module mailman:2.1 a8-clm-module-mercurial: enable module mercurial:4.8 a8-clm-module-container-tools: enable module container-tools:rhel8 a8-clm-module-python39: enable module python39:3.9 a8-clm-module-python38: enable module python38:3.8 a8-clm-module-python36: enable module python36:3.6 a8-clm-module-go-toolset: enable module go-toolset:rhel8 a8-clm-module-httpd: enable module httpd:2.4 a8-clm-module-satellite-5-client: enable module satellite-5-client:1.0 a8-clm-module-mariadb: enable module mariadb:10.3 a8-clm-module-inkscape: enable module inkscape:0.92.3 a8-clm-module-perl-DBI: enable module perl-DBI:1.641 a8-clm-module-javapackages-runtime: enable module javapackages-runtime:201801 a8-clm-module-squid: enable module squid:4 a8-clm-module-virt: enable module virt:rhel a8-clm-module-rhn-tools: enable module rhn-tools:1.0 subversion-114-filter: enable module subversion:1.14 maven-36-filter: enable module maven:3.6 nodejs-14-filter: enable module nodejs:14 nginx-118-filter: enable module nginx:1.18 postgresql-12-filter: enable module postgresql:12 redis-6-filter: enable module redis:6 swig-4-filter: enable module swig:4.0

Expected results: only mariadb-10.3 series packages available in the CLM build, for instance
Observed results: mariadb-10.5 packages included:

```
$ sudo yum clean all
$ sudo yum info mariadb-server-utils
Last metadata expiration check: 0:00:09 ago on Tue Jul 12 15:31:38 2022.
Installed Packages
Name         : mariadb-server-utils
Epoch        : 3
Version      : 10.3.32
Release      : 2.module_el8.5.0+2632+14ced695
Architecture : x86_64
Size         : 7.1 M
Source       : mariadb-10.3.32-2.module_el8.5.0+2632+14ced695.src.rpm
Repository   : @System
From repo    : susemanager:a8-clm-a8_clm-almalinux8-x86_64-appstream

Available Packages
Name         : mariadb-server-utils
Epoch        : 3
Version      : 10.5.13
Release      : 1.module_el8.5.0+2637+d11efe18
Architecture : x86_64
Size         : 1.2 M
Source       : mariadb-10.5.13-1.module_el8.5.0+2637+d11efe18.src.rpm
Repository   : susemanager:a8-clm-a8_clm-almalinux8-x86_64-appstream

Name         : mariadb-server-utils
Epoch        : 3
Version      : 10.3.32
Release      : 2.module_el8.5.0+2632+14ced695
Architecture : i686
Size         : 1.1 M
Source       : mariadb-10.3.32-2.module_el8.5.0+2632+14ced695.src.rpm
Repository   : susemanager:a8-clm-a8_clm-almalinux8-x86_64-powertools
```
Related issues, I believe: #5520 #4769

**Comment by mbussolotto** [comment]
CC @cbbayburt

**Comment by cbbayburt** [comment]
I posted an update here: https://github.com/uyuni-project/uyuni/issues/4769#issuecomment-1183767517

I believe this is a duplicate, so let's close this one and track the issue at #4769
