### ISSUE TITLE
mgr-update-reporting-hub wont finish.

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#5665]
I noticed that under Task Engine Status - Runtime Status mgr-update-reporting-hub has been running for a long time. Is this normal?
![task](https://user-images.githubusercontent.com/87128532/178960292-a29213f9-6214-4670-b862-03eadfd01cca.png)

Uyuni release 2022.06

If there are any logs that would help, let me know.

**Comment by mbussolotto** [comment]
Hi @j-kihet,
It may requires long time, but in this case is too long :) . `mgr-update-reporting-hub` on the hub-peripheral server scenario, is supposed to run on the hub to fetch information from peripheral server ( https://www.uyuni-project.org/uyuni-docs/en/uyuni/specialized-guides/large-deployments/hub-reporting.html#_data_generation_and_update ). In a uyuni server it should do nothing (I don't remember if it's not scheduled at all, or if it just start then finish instantaneously, need to check).  
Question: Is this a uyuni hub ?

Logs are in `/var/log/rhn/tasko/sat/mgr-update-reporting-hub-bunch/` you should have a file called  mgr-update-reporting-hub_<YOUR_TASK_ID>\_out  (and in case of error also  mgr-update-reporting-hub_<YOUR_TASK_ID>_err)

**Comment by mbussolotto** [comment]
@j-kihet this task is scheduled at 1:30 daily, can you check if this running task (that I supposed was triggered few days ago) prevent newer task to be scheduled ? 
Thanks

**Comment by mbussolotto** [comment]
Admin -> Task Schedules
On Bunch column, you should find "mgr-update-reporting-hub-bunch" (probably on the second page). It contains 
the list of runs of the specific bunch type. Is it something scheduled after the current running tasks?

**Comment by j-kihet** [comment]
No , nothing has been scheduled after the current task.

**Comment by j-kihet** [comment]
Would anything break if I Disable the schedule for mgr-update-reporting-hub?

**Comment by mbussolotto** [comment]
no, you can disable it (since it's not an hub, the task do nothing). I was able to reproduce the issue, so hopefully we'll provide a fix soon.

**Comment by j-kihet** [comment]
I will disable it for now.
Thank you for the fast responses and help!

**Comment by mbussolotto** [comment]
Hi @j-kihet , can you please provide `/var/log/rhn/rhn_web_ui.log` ?

Thanks!

**Comment by mcalmer** [comment]
And also `/var/log/rhn/rhn_taskomatic_daemon.log` Thanks
