### ISSUE TITLE
Rocky Linux .treeinfo file in kickstartable tree contains wrong paths to AppStream

### ISSUE THREAD

**Issue by frank-f** [uyuni-project/uyuni#5677]
# Problem description

I've created a kickstartable tree for Rocky Linux 8.6 with Uyuni 2022.06 and the .treeinfo file is an exact copy of the one contained in the upstream repository. Therefore it references AppStream like this, which does not work.
```
packages = ../../../AppStream/x86_64/os/Packages
repository = ../../../AppStream/x86_64/os/
```

## Version of Uyuni Server and Proxy (if used)

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.06-183.9.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.06-183.9.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```
_and_
```
package 'Uyuni-Proxy-release' not found.
```

## Details about the issue

There's not much to say. I manually edited the .treeinfo file, removed the AppStream variant from it and I was able to kickstart my system just fine (thank you to @lumarel for the tip).
This kept me busy for quite a bit, because it totally did not go as smooth as I'm used to from OSes without stream repositories. So I would like to suggest that Uyuni at least lets me know to remove the variants manually or even better to remove them for me and just give me a hint to check the repository in the kickstart configuration if I need any packages from it.

**Comment by cbosdo** [comment]
Thanks for reporting the issue. I'm not that familiar with that part of the product. Could you tell me in details how you created that kickstartable tree?

**Comment by frank-f** [comment]
I am not sure, if this is what you're looking for, but here you go:

You go to "Software", "Manage", select your Base Channel, click on "Repositories", then "Sync" and before clicking on "Sync now" you select "Create kickstartable tree".

**Comment by cbosdo** [comment]
OK, I managed to see the issue here. I don't really know what to do here. You may only have the `Base OS` repo synchronized and then there will be no `AppStream` to reference in the generated `.treeinfo`. But if you have both the `Base OS` and the `AppStream` the relative path needs to be changed to `../<the-repo-name-in-uyuni>/`.

What do you think makes more sense? I am tempted to completely remove the `AppStream` variant and force the user to add it in the kickstart definition. What do you think?

**Comment by frank-f** [comment]
We were finally able to resolve the blocker that was keeping us from updating beyond 2022.06.

We are now running 2022.12 and I can confirm that Uyuni generates working .treeinfo files. 🙂
