### ISSUE TITLE
Bootstrap repository not found, using RES7 bootstrap repository instead

### ISSUE THREAD

**Issue by jpgrazi** [uyuni-project/uyuni#5703]
hello
Some minions behind a uyuni proxy are not registering to the master. The error is:
centos 7 bootstrap repository not found, using RES7 bootstrap repository instead
curl: (7) Failed connect to ftw-uyunimaster.mccintra.local:443; Connection timed out
Bootstrap repo 'https://uyunimaster.domain.com/pub/repositories/res/7/bootstrap' does not exist.
curl: (3) <url> malformed
package salt is not installed
package salt-minion is not installed

I would review the url (is malformed) but I have others minions that register correctly. 
All are in the same network as the proxy, no firewall or router in the middle. 
Minions OS is Centos 7.9
uyuni proxy and master: OpenSUSE leap 15.4 with the latest update. 

No record in any of the /var/log/salt logs about the register try in master or proxy.

PLease help..

**Comment by jpgrazi** [comment]
Issue were solved. The bootstrap script was recreated in the eproxy and it worked fine now.

**Comment by jpgrazi** [comment]
REsolved

**Comment by thiagormateus** [comment]
Hi. How did you resolve? I don't understand what you mean by eproxy.
