### ISSUE TITLE
Ref: Uyuni 2022.03/04 - mgr-create-bootstrap-repo wont find RHEL products #5376

### ISSUE THREAD

**Issue by saquib-akhtar** [uyuni-project/uyuni#5727]
spacewalk:/srv/www/htdocs/pub/repositories/res/7/bootstrap # mgr-create-bootstrap-repo --with-custom-channels -f -d

RHEL7-x86_64-uyuni
RHEL8-x86_64-uyuni
SLE-12-SP5-x86_64
SLE-15-SP2-x86_64
SLE-15-SP3-x86_64
centos-7-x86_64-uyuni
oracle-7-x86_64-uyuni
oracle-8-x86_64-uyuni
Enter a number of a product label: 1
Creating bootstrap repo for latest Service Pack of RHEL7-x86_64-uyuni
copy 'python-jinja2-2.7.2-4.el7.noarch'
copy 'python-requests-2.6.0-10.el7.noarch'
copy 'python-setuptools-0.9.8-7.el7.noarch'
copy 'python-singledispatch-3.4.0.2-2.el7.noarch'
copy 'python-tornado-4.2.1-5.el7.x86_64'
copy 'python-tornado-2.2.1-8.el7.noarch'
copy 'zeromq-4.1.4-6.el7.x86_64'
copy 'python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch'
copy 'python-backports-1.0-6.el7.noarch'
copy 'python-backports-1.0-8.el7.x86_64'
copy 'PyYAML-3.10-11.el7.x86_64'
copy 'python-markupsafe-0.11-10.el7.x86_64'
copy 'python-urllib3-1.10.2-7.el7.noarch'
copy 'libyaml-0.1.4-11.el7_0.i686'
copy 'libyaml-0.1.4-11.el7_0.x86_64'
copy 'python-chardet-2.2.1-3.el7.noarch'
copy 'python-six-1.9.0-2.el7.noarch'
copy 'python-babel-0.9.6-8.el7.noarch'
copy 'yum-rhn-plugin-2.0.1-10.el7.noarch'
copy 'yum-3.4.3-168.el7.noarch'
copy 'openssl-1.0.2k-25.el7_9:1.x86_64'
copy 'openssl-libs-1.0.2k-25.el7_9:1.x86_64'
copy 'openssl-libs-1.0.2k-25.el7_9:1.i686'
copy 'python-ipaddress-1.0.16-2.el7.noarch'
copy 'redhat-rpm-config-9.1.0-88.el7.noarch'
copy 'rpm-python-4.11.3-48.el7_9.x86_64'
copy 'dmidecode-3.2-5.el7_9.1:1.x86_64'
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Directory walk started
Directory walk done - 27 packages
Temporary output repo path: /srv/www/htdocs/pub/repositories/res/7/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
ERROR: package 'salt' not found
ERROR: package 'salt-minion' not found
ERROR: package 'python2-salt' not found
ERROR: package 'python-futures' not found
ERROR: package 'python-msgpack-python' not found
ERROR: package 'python-psutil' not found
ERROR: package 'python-pycrypto' not found
ERROR: package 'python-zmq' not found
ERROR: package 'python-certifi' not found
ERROR: package 'python-simplejson' not found
ERROR: package 'python2-rhnlib' not found
ERROR: package 'spacewalk-check' not found
ERROR: package 'python2-spacewalk-check' not found
ERROR: package 'spacewalk-client-setup' not found
ERROR: package 'python2-spacewalk-client-setup' not found
ERROR: package 'spacewalk-client-tools' not found
ERROR: package 'python2-spacewalk-client-tools' not found
ERROR: package 'python2-uyuni-common-libs' not found
ERROR: none of 'mgr-daemon', 'spacewalksd' found
ERROR: package 'suseRegisterInfo' not found
ERROR: package 'python2-suseRegisterInfo' not found
ERROR: package 'python2-hwdata' not found
ERROR: package 'venv-salt-minion' not found

Suggestions:
mgr-create-bootstrap-repo uses the locally synchronized versions of files
from the Tools repository, and uses the locally synchronized pool channel
for dependency resolution.
Both should be fully synced before running the mgr-create-bootstrap-repo script.

What should I do above as it cannot find required packages neither for RHEL 7 nor for RHEL 8 ?

**Comment by avshiliaev** [comment]
Do you have the Uyuni Client Tools Channel for RHEL7 added and syncronized? Sync does not happen automatically. It needs to be triggered and preferably its own schedule should be defined.
This will change in the near future where the sync will happen automatically for all custom channels together with the vendor channels. But for now you need to define this manually.

**Comment by saquib-akhtar** [comment]
@avshiliaev Yes it was present but the problem was here that newer client tools are having venv-salt-minion instead of older salt-minion whereas the RHEL official Client Tools doesn't provide this. Thus added https://provo-mirror.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/ & synced the repo to get those. Then performed bootstrap generation & it solved this. Also, it was required to correct this under /usr/share/susemanager/mgr_bootstrap_data.py 

'RHEL7-x86_64' : {
        'PDID' : [-7, 1683], 'BETAPDID' : [2065], 'PKGLIST' : RES7 + RES7_X86,
        'DEST' : DOCUMENT_ROOT + '/pub/repositories/res/7/bootstrap/'
    },
    'RHEL7-x86_64-uyuni' : {
        'BASECHANNEL' : 'rhel-7-server-rpms', 'PKGLIST' : RES7 + RES7_X86,
        'DEST' : DOCUMENT_ROOT + '/pub/repositories/res/7/bootstrap/'
    },

Should have got fixed in this version!!

**Comment by mackdk** [comment]
>  it was required to correct this under /usr/share/susemanager/mgr_bootstrap_data.py

The configuration needs to be adapted if the base channel label is different from the default expected one.
