### ISSUE TITLE
Uyuni 08/2022: no gpg rpm download if client does not have WAN access

### ISSUE THREAD

**Issue by chr78** [uyuni-project/uyuni#5762]
Hi there,

I'm not sure if it is a bug or feature...

With the new gpg signing feature, the gpg keys from signed yum repos should be downloaded automatically from the specified url. Great feature btw.

I have an oracle 8 custom channel (cloned as Content Lifecycle) with a working gpg url defined and gpg check is enabled.

When the client wants to install the package, it says: curl error (28): Timeout was reached from https://repos.zabbix.com/https://repo.zabbix.com/zabbix/6.0/ubuntu/dists/focal/main/binary-amd64/

It seems the client tries to download the gpg from the source url directly, but WAN access is limited on this server so it can't.

For me it makes no sense to restrict access to external repos allowing only those from uyuni, and then downloading the gpg key from the URL directly. Better would be caching the key on the uyuni server?

**Comment by santeri3700** [comment]
I'm not 100% sure how the new feature works, but have you tried downloading the keys and setting the GPG key urls to point towards the Uyuni server's pub-directory `/srv/www/htdocs/pub/` (e.g. "https://uyuni-server-fqdn/pub/zabbix-official-repo.key" instead of "https://repo.zabbix.com/zabbix-official-repo.key")? \
I would imagine this works with systems which have restricted or no internet connection, but can communicate with the Uyuni server. \
I'm planning on upgrading from 2022.06 and I have used a custom state to trust GPG keys which is probably unnecessary on 2022.08. My plan is to store the keys on the Uyuni server instead of relying on public repos.

**Comment by mcalmer** [comment]
This is mostly needed for PRM based distros. AFAIK Debian does not sign the packages, but the metadata.
We have docs how to sign the metadata in Uyuni and that key (your own GPG key) is automatically deployed to the client and the repo is setup that it uses that key. (https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/repo-metadata.html)

For RPM based distros, also the packages are directly signed. Just signing the metadata with a different key may not be enough. It depends a bit on the installer. For this setting the gpk key url to https on the uyuni server would work.
But it would be better if you deploy the keys via salt to the clients and use file urls to reference them.

You can set some pillar data to deploy the keys. This should also be in the docs. (https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/gpg-keys.html)

But for Debian/Ubuntu there has nothing changed.

**Comment by mcalmer** [comment]
Btw: the GPG of the OS Vendor is in case of Oracle Linux installed on the client system. Here you only need to point to it using a file URL (file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle as an example)

**Comment by chr78** [comment]
> I'm not 100% sure how the new feature works, but have you tried downloading the keys and setting the GPG key urls to point towards the Uyuni server's pub-directory `/srv/www/htdocs/pub/` (e.g. "https://uyuni-server-fqdn/pub/zabbix-official-repo.key" instead of "https://repo.zabbix.com/zabbix-official-repo.key")?
> I would imagine this works with systems which have restricted or no internet connection, but can communicate with the Uyuni server.
> I'm planning on upgrading from 2022.06 and I have used a custom state to trust GPG keys which is probably unnecessary on 2022.08. My plan is to store the keys on the Uyuni server instead of relying on public repos.

oh, yes, I haven't thought about that.
