### ISSUE TITLE
Fails to bootstrap Ubuntu 22.04 client

### ISSUE THREAD

**Issue by domrcrel** [uyuni-project/uyuni#5765]
# Problem description

_The following information is very important in order to help us to understand your problem. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)

2022.08

## Details about the issue

When bootstrapping an Ubuntu 22.04 client using the Web UI (Systems - Bootstrapping) and using the root account (enabled on the client system for SSH purposes), the below error is received:

````
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:66jbgxDCyqzm0SOY8DlGvGem6wq3RJXa45r0BKzCTlw.
Please contact your system administrator.
Add correct host key in /var/lib/salt/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /var/lib/sss/pubconf/known_hosts:9
You can use following command to remove the offending key:
ssh-keygen -R xx.xx.xx.xx -f /var/lib/sss/pubconf/known_hosts
Password authentication is disabled to avoid man-in-the-middle attacks.
Challenge/response authentication is disabled to avoid man-in-the-middle attacks.
root@xx.xx.xx.xx: Permission denied (publickey,password).
````
It is only possible to connect the client manually, by grabbing the `venv-salt-minion` package from the Uyuni server directly and configuring the Salt master details.

**Comment by juliogonzalez** [comment]
@domrcrel looks to me you are reusing the IP, or you reinstalled that system.

You need remove the wrong key `ssh-keygen -R xx.xx.xx.xx -f /var/lib/sss/pubconf/known_hosts`

Then
> Password authentication is disabled to avoid man-in-the-middle attacks.
> Challenge/response authentication is disabled to avoid man-in-the-middle attacks.

Should go away, and unless the are more problems, bootstrapping from UI should work.

**Comment by mackdk** [comment]
@domrcrel Has the issue been fixed using Julio suggestion?

**Comment by domrcrel** [comment]
No, unfortunately. The issue happened from a new host with an IP not used before. Removing the IP from the `known_hosts` does remove it, but it immediately is added when trying to connect again. So I'm a little unsure what's going on. It should be noted though (and I'm sorry that I forgot to mention) that both the Uyuni server and the Ubuntu client are running `freeipa-client` hence the SSH `known_hosts` being in `/var/pub/sss`.

**Comment by domrcrel** [comment]
Looks like this was in fact user error :-) Seems like we were a bit too egregious with reverse DNS and it covered the IP.

Sorry for the noise.
