### ISSUE TITLE
Uyuni client has two entries in spacecmd, but is no more visible in GUI.

### ISSUE THREAD

**Issue by marmau06** [uyuni-project/uyuni#5771]
**Client "registered" twice**

We had a server, registered through rhsn, present in gui...

system_listcustomvalues command didn't return anything, even if two were setup in gui...

Investigating, I found that there are two server entries in uyuni, even now after I removed the server in gui, successfully:

flxviuynqaf1904.france.client: 1000010235
flxviuynqaf1904.france.client: 1000010236

Impossible to remove these entries, using system_delete:

spacecmd {SSM:0}> system_delete -c FORCE_DELETE 1000010235
Profile                       System ID
----------------------------  ---------
flxviuynqaf1904.france.client1000010235

Delete these systems [y/N]: y
ERROR: redstone.xmlrpc.XmlRpcFault: The following systems were NOT deleted:
1000010235

Any tool to clean Uyuni DB ?

**Comment by marmau06** [comment]
Plop ...? Any idea ? 
Thx

**Comment by marmau06** [comment]
Plop ? any sql request to remove unused system entries in DB ?

**Comment by marmau06** [comment]
Hello,
sorry to harass you, but I would need this little help to clean  my Uyuni client DB :)

**Comment by avshiliaev** [comment]
traditional clients are no more supported
