### ISSUE TITLE
Package Refresh failing Ubuntu 22.04

### ISSUE THREAD

**Issue by kyle-aas** [uyuni-project/uyuni#5784]
# Problem description

Once the Ubuntu 22.04 machine has been bootstrapped, the "Package Refresh" functionality fails to run properly.

## Version of Uyuni Server and Proxy (if used)

conman:~ # zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about the issue

From /var/log/salt/minion on the client:

2022-08-16 10:55:32,196 [salt.utils.decorators:717 ][WARNING ][3594] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2022-08-16 10:55:32,298 [salt.utils.decorators:717 ][WARNING ][3594] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2022-08-16 10:55:32,443 [salt.utils.decorators:717 ][WARNING ][3594] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2022-08-16 10:55:32,487 [salt.state       :317 ][ERROR   ][3594] Module function pkg.info_installed threw an exception. Exception: The following keyword arguments are not valid: attr=status,arch,epoch,version,release,install_date_time_t, errors=report
2022-08-16 10:55:32,852 [salt.minion      :2956][CRITICAL][3219] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2954, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'

**Comment by juliogonzalez** [comment]
@kyle-aas by looking at the stacktrace, I'd say you are not using the bundle, but rather a salt-minion package we don't provide (for Ubuntu 22.04 we only provide the bundle).

Is it that the case?

**Comment by juliogonzalez** [comment]
Try with `dpkg -l|grep salt` to find the installed packages that match `salt`

then use `apt-cache show <package>` for the packages, and paste the results.

If my theory is correct, you should have a package called `salt-minion` installed, from Ubuntu, which is what's causing your issue.

If that's the case, next step is figuring out why that is the case, and if you really need it.

If you don't, I see to alternatives:
- remove the package, and bootstrap again (so the bundle is used)
- check the doc, as we explained there how to migrate a client using salt-minion to the new bundle (not sure if this will work for Ubuntu 22.04 as we never provided the non-bundle salt).

**Comment by juliogonzalez** [comment]
@vzhestkov can you have a look?

**Comment by vzhestkov** [comment]
I think I know the root cause. I saw similat before.
Check this issue: https://github.com/uyuni-project/uyuni/issues/5523
The package causing the issue could be different, but the root cause looks the same.

**Comment by kyle-aas** [comment]
Ran the same command as the other issue.  Output attached
[venv-salt-call.log](https://github.com/uyuni-project/uyuni/files/9374749/venv-salt-call.log)
.

**Comment by vzhestkov** [comment]
@kyle-aas thanks for the output. The root cause of the issue is totally identical to the issue I gave a link to, but the only difference it's caused by the data from the other package - `owncloud-client`.
If it's possible to remove it from the system, try to check it, the issue should gone. We will fix this bug for sure. It's in our backlog already, just had no time to fix it before.

**Comment by kyle-aas** [comment]
@vzhestkov you were 100% correct.  Removing the owncloud-client package resolved the issue.

**Comment by vzhestkov** [comment]
Thanks for the confirmation. I would suggest to close this issue as it's a duplicate. I'm going to fix the bug asap, but the fix most probably will be included to the release on October.

**Comment by kyle-aas** [comment]
Closing as duplicate per request.
