### ISSUE TITLE
EFI PXE boot

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [uyuni-project/uyuni#5851]
Just wanted to let u know that 

https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/autoinst-pxeboot.html
https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/autoinst-pxeboot.html

says the following

"In the Filename EFI field, type grub/grub.efi to enable EFI PXE support."

However: In a VMware ESXi 7.x VM, it seems you have to use grub/shim.efi however. (found this out by trial-and-error)

If you use "grub/grub.efi" as the filename, then nothing happens at PXE stage.
Only using "grub/shim.efi" actually starts the boot menu and lets installation begin.

Sidenote: This is not a problem with a formula. This is just the way the DHCP server needs to be configured, even if you configure it manually. In that regard, I don't think the remark about what filename to use for PXE EFI is very well located in the note about how to use a formula. Legacy BIOS and EFI options should be explained independently of whether a formula is used or not.

**Comment by keichwa** [comment]
> Sidenote: This is not a problem with a formula. This is just the way the DHCP server needs to be configured, even if you configure it manually. In that regard, I don't think the remark about what filename to use for PXE EFI is very well located in the note about how to use a formula. Legacy BIOS and EFI options should be explained independently of whether a formula is used or not.

Thanks for the proposal.  I created an enhancement request on it's own: https://github.com/SUSE/spacewalk/issues/19004

**Comment by keichwa** [comment]
everything merged and backported.
