### ISSUE TITLE
Problems when listing system events using JSON API

### ISSUE THREAD

**Issue by AnsgarKlein** [uyuni-project/uyuni#5860]
# Problem description

I am having problems using the JSON API endpoint `/api/system/listSystemEvents` for some but not all hosts on SUSE Manager 4.3.0.

Calling the API for some hosts will work as expected and return HTTP 200 and  a json object containing the requested information.  
For other hosts the API will always return HTTP 500 with body 
```json
{
  "message": "class com.redhat.rhn.domain.action.Action declares multiple JSON fields named created"
}
```

## Version of Uyuni Server and Proxy (if used)

I am running SUSE Manager 4.3.0:

```
Information for package SUSE-Manager-Server-release:
----------------------------------------------------
Repository     : SLE-Product-SUSE-Manager-Server-4.3-Pool
Name           : SUSE-Manager-Server-release
Version        : 4.3-150400.55.1
Arch           : x86_64
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 334.3 KiB
Installed      : Yes
Status         : up-to-date
Source package : SUSE-Manager-Server-release-4.3-150400.55.1.src
Summary        : SUSE Manager Server 4.3
```

## Details about the issue

The endpoint `/api/system/listSystemEvents` has multiple variants with different arguments according to [the documentation](https://documentation.suse.com/suma/4.3/api/suse-manager/api/system.html#apidoc-system-listSystemEvents-550917991).
All those endpoints behave the same for one host, meaning they either all work or none of them do.

**Reproducible code snippet**:

```shell
API_PATH='https://my-suse-manager/rhn/manager/api'
USER='...'
PASS='...'
SYSTEM_ID='1000010076'

# Login
curl -X POST -H "Content-Type:application/json" --cookie-jar 'cookies.txt' --data "{\"login\": \"$USER\", \"password\": \"$PASS\"}" "${API_PATH}/auth/login"

# List system events
curl -X GET -H "Content-Type:application/json" --cookie 'cookies.txt' "${API_PATH}/system/listSystemEvents?sid=$SYSTEM_ID"
curl -X GET -H "Content-Type:application/json" --cookie 'cookies.txt' "${API_PATH}/system/listSystemEvents?sid=$SYSTEM_ID&actionType=System%20reboot"
curl -X GET -H "Content-Type:application/json" --cookie 'cookies.txt' "${API_PATH}/system/listSystemEvents?sid=$SYSTEM_ID&earliestDate=1970-01-01T00:00:00Z"
```

**Expected behaviour**:

Get list of system events like this:

```json
{
  "success": true,
  "result": [
    {
      "completion_time": "2022-08-05 13:20:37.737538",
      "action_type": "Package List Refresh",
      "created": "2022-08-05 13:20:32.683388",
      "successful_count": 1,
      "modified_date": "Aug 5, 2022, 1:20:37 PM",
      "version": "2",
      "completed_date": "Aug 5, 2022, 1:20:37 PM",
      "result_msg": "Success",
      "archived": 0,
      "pickup_date": "Aug 5, 2022, 1:20:33 PM",
      "earliest_action": "2022-08-05 13:20:32.747",
      "name": "Package List Refresh",
      "modified": "2022-08-05 13:20:37.737538",
      "failed_count": 0,
      "id": 2235,
      "pickup_time": "2022-08-05 13:20:33.06453",
      "created_date": "Aug 5, 2022, 1:20:32 PM"
    }
  ]
}
```

**Actual behaviour**:

Returned data in HTTP 500 body does not contain system events:

```json
{
  "message": "class com.redhat.rhn.domain.action.Action declares multiple JSON fields named created"
}
```

I cannot see any pattern regarding which hosts work and which don't.

If I set the arguments so the result will always be empty (like setting `earliestDate` to 2050) I will not get that error message but a valid empty result list. But this is of course not helpful.

**Comment by mackdk** [comment]
Unfortunately I could not reproduce the issue in any of my test environment. Could you please provide the log files in the server directory `/var/log/rhn` taken after reproducing the issue? There should be some additional pieces of information in `rhn_web_api.log` and in `rhn_web_ui.log`. Could also please list the types of the events expected on one of the server that show the problem? I guess that the problem should be connected to a very specific event type/value, otherwise it would be always evident.

**Comment by AnsgarKlein** [comment]
I have checked event types manually via web interface for a few servers and these are the results:

> works
> 1000010305
> Events:
>   - added system entitlement
>   - Hardware List Refresh
>   - Apply states
>   - Package List Refresh
> 
> works
> 1000010263
> Events:
>   - added system entitlement
>   - Hardware List Refresh
>   - Apply states
>   - Package List Refresh
> 
> works
> 1000010211
> Events:
>   - added system entitlement
>   - Hardware List Refresh
>   - Apply states
>   - Package List Refresh
>   - Subscribe channels scheduled
>   - subscribed to channel
>   - unsubscribed from channel
> 
> works
> 1000010369
> Events:
>   - added system entitlement 
>   - Hardware List Refresh
>   - Apply states
>   - Package List Refresh
> 
> works
> 1000010229
> Events:
>   - added system entitlement
>   - Apply states
>   - Hardware List Refresh
>   - Package List Refresh
>   - Apply highstate scheduled
>   - Subscribe channels scheduled
>   - subscribed to channel
>   - unsubscribed from channel
> 
> does not work
> 1000010011
> Events:
>   - added system entitlement
>   - Hardware List Refresh
>   - Apply states
>   - Package List Refresh
>   - Package Install/Upgrade scheduled
>   - System reboot scheduled
>   - Apply highstate
> 
> does not work
> 1000010041
> Events:
>   - Package List Refresh
>   - Package Install/Upgrade scheduled
>   - Apply highstate scheduled
>   - Subscribe channels scheduled
>   - subscribed to channel
>   - System reboot schedule
>   
> does not work
> 1000010046
> Events:
>   - added system entitlement
>   - Hardware List Refresh
>   - Apply states
>   - Package List Refresh
>   - Subscribe channels scheduled
>   - subscribed to channel
>   - Package Install/Upgrade scheduled
>   - System reboot scheduled

It looks to me that the _System reboot schedule_ event is causing the problems. I could not find a server that gives expected results and has a _System reboot scheduled_ event. Unfortunately I cannot simply reboot one of those servers that currently give expected results to see if that changes anything because those are all critical production systems. But I will try with a dummy server.

`rhn_web_ui.log` will only have one entry after calling the `/auth/login` endpoint:
`2022-09-02 17:51:07,749 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-31] INFO  com.suse.manager.webui.controllers.login.LoginController - LOCAL AUTH SUCCESS: [<username>]`

It seems only requests to XML-RPC API are logged in `rhn_web_api.log`.

Neither successful nor unsuccessful requests to `api/system/listSystemEvents` will have create any entry in any log file in `/var/log/rhn`. Is that something that I need to enable first?

**Comment by AnsgarKlein** [comment]
I have reported this problem to SUSE directly via the SUSE customer center.
They have created a fix for the spacewalk component, which solves this problem.
I hope this fix will make its way into uyuni's spacewalk. If you have extended access to SUSE Bugzilla this seems to be the internal bug: bsc#1202899
