### ISSUE TITLE
Ubuntu 22.04 depends on logrotate but is not available

### ISSUE THREAD

**Issue by domrcrel** [uyuni-project/uyuni#5912]
Running a vanilla, minimalized (per the official installer) install of Ubuntu 22.04 does not have logrotate installed pre-built. When you try to bootstrap it on Uyuni, the bootstrapping will fail as `venv-salt-minion` requires `logrotate`. Adding this before bootstrapping works perfectly.

Perhaps it could be useful to check for any deps before disabling the default repos? Or including `logrotate` in the client tools repo?

**Comment by mcalmer** [comment]
CC @vzhestkov do we need logrotate? I wo der what ubuntu use to rotate logfiles

**Comment by domrcrel** [comment]
I forgot to mention but this is specific to the Ubuntu Server installer, not the desktop one. I chose the option as below:

![Ubuntu Minimal](https://i.imgur.com/Lt2kav5.png)

**Comment by vzhestkov** [comment]
Looks like it was fixed already, if you still have any issues with it, feel free to reopen.
