### ISSUE TITLE
Machines Bootstrapped over-riding old ones

### ISSUE THREAD

**Issue by fmcardosom** [uyuni-project/uyuni#595]
While registering machines i am getting some machines overriding older ones already registered.
I've checked system uuid's, ssh keys just about anything i can remember has anyone seen this behaviour ?

**Comment by mcalmer** [comment]
Maybe this will help you https://wiki.microfocus.com/index.php/SUSE_Manager/Register_Clones

**Comment by fmcardosom** [comment]
Will give it a shot thank you.

**Comment by cbbayburt** [comment]
> Will give it a shot thank you.

@fmcardosom has the wiki guide worked for you?

**Comment by Shirocco88** [comment]
@fmcardosom : Is this issue still existend ? can we close this issue ?

**Comment by Shirocco88** [comment]
see also issue https://github.com/uyuni-project/uyuni/issues/2378

**Comment by aaannz** [comment]
I think we can close the issue as the registration handling was changed quite a bit recently - see https://github.com/uyuni-project/uyuni/pull/3626

Registration routine in general looks at 3 things - machineid (generated usually by systemd), minion_id (fqdn by default, used by salt) and reactivation key (optionally added grain susemanager:management_key).

If machineid or minion_id match already existing system in the database - unless both matches different system - existing system would be overwritten.
To prevent overwriting systems both machine id and minion id must be unique.

**Comment by aaannz** [comment]
Closing this one as it works as designed.
