### ISSUE TITLE
What determines a systems reboot required status?

### ISSUE THREAD

**Issue by Beeez** [uyuni-project/uyuni#6003]
# Question

What function in Uyuni is determining the status of a system requiring a reboot?

I had installed updates to a host via Uyuni, one of those updates requiring a reboot. Since then this host (and many others) are stuck in a "The system requires a reboot" state. 

These hosts have been rebooted multiple times since the updates, as well as rebooted from Uyunis own reboot scheduling. 

needs-restarting returns that a reboot is not needed. 

How can I tell Uyuni to re-poll that status from a host? I have tried package refreshes, and hardware refreshes. 

## Version of Uyuni Server and Proxy (if used)
```
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Server
```

**Comment by gabira2003** [comment]
Hi Beez,

I own  many my Uyuni installations and I second that feature in GUI menu under "Systems->System List->Requiring Reboot" 
is broken. Clients don't appear under 'reboot required' any more.

This feature used to work in old Uyuni versions , which is very important feature for our case.

See more details about it inside : [#5084](https://github.com/uyuni-project/uyuni/issues/5084)

**Comment by mcalmer** [comment]
This should be better now with the latest version as we take the status from the client
