### ISSUE TITLE
spacecmd: Add doc strings to functions and modules

### ISSUE THREAD

**Issue by agraul** [uyuni-project/uyuni#6006]
Many functions in `spacecmd` don't have a [docstring](https://peps.python.org/pep-0257/#what-is-a-docstring). Some of them have a comment in place of a docstring, which is a good starting point. Still, docstrings have advantages over plain comments since they are "attached" to the function:
```python
>>> def foo():
...     # I'm a comment
...     pass
... 
>>> def bar():
...     """I'm a docstring"""
...     pass
... 
>>> help(foo)
foo()
>>> help(bar)
bar()
    I'm a docstring
```

Whole modules (i.e. Python files that are imported by other Python files) should also be documented with docstrings to explain what they are for and how they are used.

**Comment by PriyanshuAhlawat** [comment]
I will like to work on it, pls assign

**Comment by agraul** [comment]
There you go @PriyanshuAhlawat! Please reach out if you have any questions

**Comment by PriyanshuAhlawat** [comment]
@agraul can you tell in which files doc strings need to be applied

**Comment by agraul** [comment]
@PriyanshuAhlawat in general all Python modules in `spacecmd/src/spacecmd/`. The `spacecmd` commands each have three functions: `help_command_name`,  `complete_command_name`,  and `do_command_name`. These don't require docstrings as badly as utility functions, i.e. those that are used inside these "command implementations".

`spacecmd/src/spacecmd/utils.py` contains only utility functions, I think it's a good idea to start with that one.

**Comment by PriyanshuAhlawat** [comment]
Thanks @agraul for the elaboration, working on it

**Comment by agraul** [comment]
Hi @PriyanshuAhlawat, I just wanted to check how you are doing. If you already have some change in a branch, feel free to open a Draft Pull Request. As always, please don't hesitate and ask away if you get stuck!

**Comment by Rakielle** [comment]
Hi @agraul, has this issue been picked up? I would like to work on it.
