### ISSUE TITLE
salt/channels/channels.repo jinja file appears to generate invalid configuration

### ISSUE THREAD

**Issue by ppanon2022** [uyuni-project/uyuni#6021]
### Problem description

channels.repo contains the following jinja statements that are evaluated for non-Debian systems
[{{ args['alias'] }}]
name={{ args['name'] }}
enabled={{ args['enabled'] }}
{%- if args['gpgkeyurl'] is defined %}
gpgkey={{ args['gpgkeyurl'] }}
{%- if salt['pillar.get']('mgr_metadata_signing_enabled', false) %}
file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
{%- endif %}
{%- elif salt['pillar.get']('mgr_metadata_signing_enabled', false) %}
gpgkey=file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
{%- endif %}

This Uyuni server also has Ubuntu repos so manager keys have been generated for the Ubuntu channels to support signing and those channels work fine. I appear to somehow have gpgkeyurl defined and mgr_metadata_signing_enabled set as false, generating the following lines in the config file

    [susemanager:centos7-x86_64]
    name=CentOS 7 (x86_64)
    enabled=1
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
    baseurl=https://...

Having that file:///etc/pki... on a second line causes any update to fail on CentOS 7. So it seems that the template as currently written makes it possible for a bad config file to be generated. I'm not sure what is intended there, but it's not working properly.

### Steps to reproduce
Not sure exactly but our environment has
1. CentOS 7 stock channels set up with spacewalk-common-channels
2. Ubuntu 18.04, 20.04, and 22.04 channels set up using spacewalk-common-channels
3. GPG key set up for repo signing with https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/repo-metadata.html
...

### Uyuni version

```bash
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
Having determined that the gpgkey= line in the configuration was the problem, we edited the 
configuration file to remove the extra line, keeping the mgr key. Then, when reapplying the high
state on that server, I noticed that the mgrchannels_repo state was breaking the config file again.

----------
          ID: mgrchannels_repo
    Function: file.managed
        Name: /etc/yum.repos.d/susemanager:channels.repo
      Result: True
     Comment: File /etc/yum.repos.d/susemanager:channels.repo updated
     Started: 11:30:25.640710
    Duration: 85.16 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,13 +1,12 @@
                   # Channels managed by SUSE Manager
                   # Do not edit this file, changes will be overwritten
                  -#
                  -##gpgkey=file:///etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
                   #

                   [susemanager:centos7-x86_64]
                   name=CentOS 7 (x86_64)
                   enabled=1
                  -gpgkey=file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
                  +gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
                  +file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
                   baseurl=https://<server.fqdn>:443/rhn/manager/download/centos7-x86_64
                   susemanager_token=<longtokenstring>
                   gpgcheck=1
                  @@ -18,7 +17,8 @@
                   [susemanager:epel7-centos7-x86_64]
                   name=EPEL 7 for CentOS 7 (x86_64)
                   enabled=1
                  -gpgkey=file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
                  +gpgkey=https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdownload.fedoraproject.org%2Fpub%2Fepel%2FRPM-GPG-KEY-EPEL-7&amp;data=05%7C01%7Cppanon%40sierrawireless.com%7C4a2d04cc45ac49c1012b08daabe437cf%7C08059a4c248643dd89e33a747e0dcbe8%7C0%7C0%7C638011293944509753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=v%2FBr%2Fcm5y7wq2L%2F3XQIwq9VwI1Sytmcmkf3%2FXPO7KRw%3D&amp;reserved=0
                  +file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
                   baseurl=https://<server.fqdn>:443/rhn/manager/download/epel7-centos7-x86_64
                   susemanager_token=<longtokenstring>                   gpgcheck=1
                  @@ -29,7 +29,8 @@
                   [susemanager:centos7-x86_64-updates]
                   name=CentOS 7 Updates (x86_64)
                   enabled=1
                  -gpgkey=file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
                  +gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
                  +file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
                   baseurl=https://<server.fqdn>:443/rhn/manager/download/centos7-x86_64-updates
                   susemanager_token=<longtokenstring>
                   gpgcheck=1
                  @@ -40,7 +41,8 @@
                   [susemanager:centos7-uyuni-client-x86_64]
                   name=Uyuni Client Tools for CentOS 7 (x86_64)
                   enabled=1
                  -gpgkey=file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
                  +gpgkey=file:///etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
                  +file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
                   baseurl=https://<server.fqdn>:443/rhn/manager/download/centos7-uyuni-client-x86_64
                   susemanager_token=<longtokenstring>
                   gpgcheck=1
----------
```

**Comment by ppanon2022** [comment]
How should it look like instead?
Option A
{%- if args['gpgkeyurl'] is defined %}
gpgkey={{ args['gpgkeyurl'] }}
{%- elif salt['pillar.get']('mgr_metadata_signing_enabled', false) %}
gpgkey=file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
{%- endif %}

Option B
{%- if salt['pillar.get']('mgr_metadata_signing_enabled', false) %}
gpgkey=file:///etc/pki/rpm-gpg/mgr-gpg-pub.key
{%- elif args['gpgkeyurl'] is defined %}
gpgkey={{ args['gpgkeyurl'] }}
{%- endif %}

**Comment by mcalmer** [comment]
The man page of yum say, that this syntax should work. Can you chech the manpage of yum on your installed system and paste the section about gpgkey option? Your suggested change may not work with newer versions. 
Is your yum up to date? Are you running latest v7 service pack?

**Comment by ppanon2022** [comment]
Sigh. You're right and I must admit to having been somewhat confused and perhaps jumped to a conclusion. First, to answer your question, these systems are running current CentOS Linux release 7.9.2009 (Core) 

The problem first came up when we were trying to register some new CentOS systems. We had successfully registered at least one of them in the past and successfully patched it. To do that, we created and modified a bootstrap script to add some GPG keys for some additional packages in a custom channel (because we were getting missing key errors when trying to install those packages).
ORG_GPG_KEY=uyuni-gpg-pubkey-0d20833e.key,centos7-gpg-pubkey-f4a80eb5.key,redhat-epel7-6A2FAEA2352C64E5.key,falcon-sensorv2-519b177f.key,tenable2022-1C0C4A5D.key
The additional keys were added to the .../pub on the Uyuni server.

Then with some of the newer CentOS installs, the commands triggered by the bootstrap script after accepting the key were failing.

----------
          ID: mgr_deploy_customer_gpg_key
    Function: file.managed
        Name: /etc/pki/rpm-gpg/mgr-gpg-pub.key
      Result: false
     Comment: Source file salt://gpg/mgr-gpg-pub.key not found in saltenv 'base'
     Started: 15:07:52.672780
    Duration: 10.243
         SLS: channels.gpg-keys
     Changed: {}
----------
and

----------
          ID: pkg_installed
    Function: pkg.installed
        Name: pkg_installed
      Result: false
     Comment: Error occurred installing package(s). Additional info follows:

errors:
    - Running scope as unit run-28729.scope.
      Loaded plugins: fastestmirror, langpacks, susemanagerplugin, venv-yumnotify
      Loading mirror speeds from cached hostfile
      Retrieving key from file:///etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
      https://carmd-nv-uyuni1.sierrawireless.local:443/rhn/manager/download/centos7-uyuni-client-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for susemanager:centos7-uyuni-client-x86_64
      Trying other mirror.
      
      
       One of the configured repositories failed (Uyuni Client Tools for CentOS 7 (x86_64)),
       and yum doesn't have enough cached data to continue. At this point the only
       safe thing yum can do is fail. There are a few ways to work "fix" this:
     ...
     
Now the interesting thing is that the key name in the second error doesn't match the key name in the pub folder. uyuni-tools-gpg-pubkey-0d20833e.key != uyuni-gpg-pubkey-0d20833e.key

So maybe that was the fundamental problem and an issue with the configuration file for mgr-create-bootstrap-repo which created the Uyuni tools repo? Then perhaps the portion of the bootstrap which loads the GPG keys in the minion failed and caused the mgr key copy/import to also fail? I manually copied/imported that mgr key and updates were still failing until I edited the repo file to only use the mgr key. 

I'm not getting any errors on a yum update on those minions now, but the system is also already up to date so perhaps it just isn't having to do key verifications and the problem might come back with new updates. Or if I try to switch to a different LCM Base channel and children (which was also failing). So if the issue is with the uyuni GPG key for the tools channel, how do I fix that? And what is the underlying problem which caused it and which needs to be fixed?

**Comment by mcalmer** [comment]
I think you problem is with /etc/pki/rpm-gpg/mgr-gpg-pub.key .
The state which should deploy the key file to you client failed.
We had an issue that `mgr-sign-metadata-ctl` did not export the generated GPG key into the salt filesystem.

Please check with: `mgr-sign-metadata-ctl check-config`

If it report an error like: ERROR. Public key file /..... is missing.
please copy your self created GPG key to that place.

The filename of the uyuni key is not important. I think if you compare the content, you will see it is the same.
We named it now just "uyuni key" as it is one key for the whole uyuni project.
It is also used for uyuni server and proxy. So "uyuni-tools" was not really correct.

**Comment by mcalmer** [comment]
Ahh, I forgot. That check will come with 2022.10. So currently "mgr-sign-metadata-ctl check-config" will not report problems.

**Comment by ppanon2022** [comment]
Yes, I just see
mgr-sign-metadata-ctl check-config
Metadata signing is enabled in /etc/rhn/rhn.conf.

OK. KEYID is set in /etc/rhn/signing.conf.
OK. Found key 79106066 in keyring.
OK. Key 79106066 was exported to /srv/susemanager/salt/gpg/mgr-keyring.gpg.
OK. Key 79106066 was exported to /srv/www/htdocs/pub/mgr-gpg-pub.key.

**Comment by ppanon2022** [comment]
The weird thing is that, for those CentOS systems with failed state with
Retrieving key from file:///etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
[https://carmd-nv-uyuni1.sierrawireless.local:443/rhn/manager/download/centos7-uyuni-client-x86_64/repodata/repomd.xml](https://carmd-nv-uyuni1.sierrawireless.local/rhn/manager/download/centos7-uyuni-client-x86_64/repodata/repomd.xml): [Errno -1] repomd.xml signature could not be verified for susemanager:centos7-uyuni-client-x86_64

When I run
salt servername.fqdn cmd.run "ls -l /etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key"
the result is
    -rw-r--r-- 1 root root 1126 Oct 11 19:41 /etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
so the key exists, and I can use the same approach to compare its sha256sum to /srv/www/htdocs/pub/uyuni-gpg-pubkey-0d20833e.key on the Uyuni server and they match.

**Comment by ppanon2022** [comment]
Upgraded to 2022.10 and I get no notification of any issue with a missing file.
# mgr-sign-metadata-ctl check-config
Metadata signing is enabled in /etc/rhn/rhn.conf.

OK. KEYID is set in /etc/rhn/signing.conf.
OK. Found key 79106066 in keyring.
OK. Key 79106066 was exported to /srv/susemanager/salt/gpg/mgr-keyring.gpg.
OK. Key 79106066 was exported to /srv/susemanager/salt/gpg/mgr-gpg-pub.key.
OK. Key 79106066 was exported to /srv/www/htdocs/pub/mgr-gpg-pub.key.

**Comment by mcalmer** [comment]
I just merged a change which configure gpgkeys in one line which seems to be supported by all 3 installers.
We will also import the GPG keys directly in future as this is working better than to rely on the installers.

Should be in Uyuni 2022.11 and will hopefully fix all the problems.

**Comment by ppanon2022** [comment]
Thanks. I had temporarily modified our jinja file to still include both keys on separate lines, but to place the mgr gpg key first. After applying the high state with that as a stopgap, the updates were working again although I suspect the functionality still wasn't what you were hoping for. Since we were also seeing some systems reporting errors about missing the mgr gpg keys, and having to install them with salt, I look forward to your changes in the next release.

**Comment by mcalmer** [comment]
I will close this for now. If you see problems with 2022.11, please open a new issue. Thanks.
