### ISSUE TITLE
To many open Files since upgrade from 2022.03 

### ISSUE THREAD

**Issue by vega82** [uyuni-project/uyuni#6080]
### Problem description

My Uyuni is running in trouble and filling up the system ressources with open files.
This problem exists since upgrade from 2022.03 to 2022.04 in May and is still existing in 2022.10.

![openfiles](https://user-images.githubusercontent.com/2478621/198513326-be5b86b4-068b-4bfa-86f2-3a517decc5b2.PNG)

### Steps to reproduce

Let Spacewalk Service running. Open Files filling up without doing anything.
Restart of Spacewalk Service resets the problem.

### Uyuni version

```bash
2022.10-220400.191.2.uyuni2
```

**Comment by juliogonzalez** [comment]
@avshiliaev, I think this is https://github.com/uyuni-project/uyuni/pull/6066?

If so, I think you need to change the PR target to the branch `Uyuni-2022.10` so we can release it as a patch and people don't need to wait for 2022.11
