### ISSUE TITLE
Calling spacewalk-repo-sync --help should always work

### ISSUE THREAD

**Issue by cbosdo** [uyuni-project/uyuni#6128]
When `spacewalk-repo-sync` is already running another one can't be started... OK, but that shouldn't prevent `spacewalk-repo-sync --help` from printing help. For now this is what it does in such a case.

```
# spacewalk-repo-sync --help
ERROR: attempting to run more than one instance of spacewalk-repo-sync Exiting.
```

Code pointer: the code of the tool starts here: https://github.com/uyuni-project/uyuni/blob/master/python/spacewalk/satellite_tools/spacewalk-repo-sync

**Comment by amentee** [comment]
I am not able to assign this issue to myself. Please can you help me out

**Comment by agraul** [comment]
Sure, no problem @amentee! Thanks for offering your help.

**Comment by amentee** [comment]
I need help in setting up my environment to test the code. I was trying to refer the Wiki but the link seems not working (http://bosdonnat.fr/slides/openSUSEAsiaSummit19/). Can you guide me in how to set up the development environment or any active link that explains the process will be helpful

**Comment by agraul** [comment]
@amentee [the https version](https://bosdonnat.fr/slides/openSUSEAsiaSummit19/#/cover-page) works, I'll fix the link in the wiki. Feel free to look through all of it, the [sumaform](https://bosdonnat.fr/slides/openSUSEAsiaSummit19/#/sumaform) page is what you probably want to do first. Once you have a virtualized setup running, you can already execute `spacewalk-repo-sync --help`

**Comment by amentee** [comment]
Thanks @agraul ..just a basic question regarding the environment setup..we need openSUSE box(in any public cloud) with minimum requirements of cpu , memory and disk as mentioned in the uyuni documentation - https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/uyuni-install-requirements.html. And once we have the SUSE box setup with requisite configuration and mount points , we can follow the document linked above to setup. Please confirm if this is right approach.

**Comment by amentee** [comment]
@agraul ..Thanks for the corrected link. I was following sumaform page and installed the required packages. I also configured bridged networking . But the libvirt README page says that I need a storage pool named default. When I ran the command on my system "virsh pool-list --details" , it gave me below error.

```
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
```

Any idea how to fix this.

**Comment by amentee** [comment]
@cbosdo . Please guide me to the function in the test case that tests two instances of the command spacewalk-repo-sync written in (https://github.com/uyuni-project/uyuni/blob/master/python/test/unit/spacewalk/satellite_tools/test_reposync.py) that can be used to test against above issue.

**Comment by m-czernek** [comment]
Fixed in https://github.com/uyuni-project/uyuni/pull/6845, closing dangling issue
