### ISSUE TITLE
Kickstart setup always installs perl

### ISSUE THREAD

**Issue by rulev** [uyuni-project/uyuni#6149]
### Problem description

When I set up new system using kickstart it always has perl packages installed. Actually perl needed only for traditional client, not for salt managed one. It is hardcoded to java/code/src/com/redhat/rhn/manager/kickstart/KickstartFormatter.java

`if (ConfigDefaults.get().getUserSelectedSaltInstallTypeLabels().contains(ksdata.getInstallType().getLabel())) {`
`         // packages necessary for RHEL 6+ and Fedora (salt)`
`            buf.append("perl" + NEWLINE);`
`            buf.append("wget" + NEWLINE);`
`            buf.append("salt-minion" + NEWLINE);`
`        }

But perl is not necessary. Lines like
`
perl -pe 's/RHNS-CA-CERT/RHN-ORG-TRUSTED-SSL-CERT/g' -i /etc/sysconfig/rhn/up2date
`
are not necessary in kickstart file for salt clients as there no such a file /etc/sysconfig/rhn/up2date

You should think about wget as well cause it is not necessary either.

### Steps to reproduce

1. Create autoinstallation profile for salt client
2. See perl in autoinstallation file packages list
%packages  --ignoremissing
-iwl*
perl
wget
salt-minion
%end

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.10-220400.191.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.10-220400.191.2.uyuni2.src
Summary        : Uyuni Server
```

**Comment by Dark-Schnitzel** [comment]
Also happens on our Installation after Updating to 2022.10. Its a mayor blocker because Redhat 8.6 and 8.7 seems to have a problem with the perl module in the Installation. Is it possible to edit the kickstart file manually on the filesystem?

**Comment by Dark-Schnitzel** [comment]
i just discovered the kickstart file lcoation: 
/var/lib/cobbler/templates/wizard/ 
you can edit it there till a option in the WebUI is available

**Comment by aaannz** [comment]
This should be fixed by https://github.com/uyuni-project/uyuni/pull/6186 where salt based clients no longer install perl.
