### ISSUE TITLE
Systems list in webui only shows SSM selected machines after 2022.11 upgrade

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#6179]
### Problem description

Upgrade from fully-patched 2022.10 went fine (minor, having made the additional changes for .10, followed by reboot), but after doing so all systems disappeared from the systems list. 

In 2022.10, `{hostname}/rhn/manager/systems/list/all` would show ALL systems registered to Uyuni. Including those inactive or unselected.

In 2022.11, this same url will show "No systems". However, if you select systems into SSM, then it will show SSM selected machines only, the same list as `{hostname}/rhn/systems/ssm/ListSystems.do` does.

This means there's currently no way to show all machines.

All of the "Systems List" sub-menus (apart from Currency and Types) under "Systems" show "No Systems".

The vms still exist and are still reachable from the search box, and System Groups shows a normal amount of vms in the Systems column, and they do appear in there.  Additionally, spacecmd system_list shows all vms as normal.

Refreshed browser, and also checked with a new private browser, and verified with a second user. (Chrome and Firefox)

I've now had to roll back to .10 to continue working.

If anyone else is experiencing the same thing following this upgrade, please mention this here to help the devs build a picture of how widely this issue is.

### Steps to reproduce

Follow minor upgrade process, reboot vm. 

Refresh browser and visit:  /rhn/manager/systems/list/all

![image](https://user-images.githubusercontent.com/4052275/203284461-0b5be89e-4277-4d43-98d3-84db0998c8a1.png)

### Uyuni version

```bash
2022.11
```

**Comment by mcalmer** [comment]
CC @cbosdo

**Comment by cbosdo** [comment]
Could you check that you have those tasks in the `Admin > Task Schedules` page?

* system-overview-update-queue-default
* update-system-overview-default

The new page uses a `susessytemoverview` table in the DB that caches the data. This table needs to be updated. It may take some time for that to happen if you have many registered systems.

The systems should be updated in the table within 1 minute after a change on them or at the top of every hour.

You could also check the postgresql logs if anything wrong happens with this update query.

The following SQL query will show you the pending update actions for that table:

    select * from rhntaskqueue where task_name = 'update_system_overview';

**Comment by matthiashinrichs** [comment]
@cbosdo Yes, these tasks are there.
And after triggering them manually all systems are back.

So, I think, there is not an issue. But it's very confusing that the systems list is empty after the first login :)

**Comment by digdilem** [comment]
Thanks for update - I can't check atm as ours is back on 2022.10 and in production.

We had 2022.11 up and running for about 40 minutes, and the systems list didn't re-appear by then. We have 200 registered systems.

**Comment by digdilem** [comment]
Thanks for the info, @cbosdo - I can confirm that also worked for me, having undergone the update again and 2022.11 seems to be all happy again now.

I didn't see anything about this change in the release notes (possibly my fault) - it would have saved some confusion if I had been aware this was changing and extra steps were needed, but no harm done. It's certainly more responsive loading that list now.

The new page is paginated and resets to a size of 15. Under "My Preferences", I have a setting of 250 set for `Uyuni List Page Size` but this doesn't seem to be respected here. Am I doing something wrong here too, or should I create a new issue for that?

**Comment by cbosdo** [comment]
> The new page is paginated and resets to a size of 15. Under "My Preferences", I have a setting of 250 set for `Uyuni List Page Size` but this doesn't seem to be respected here. Am I doing something wrong here too, or should I create a new issue for that?

Should be an issue... I probably forgot to handle that in the UI

**Comment by cbosdo** [comment]
> Thanks for the info, @cbosdo - I can confirm that also worked for me, having undergone the update again and 2022.11 seems to be all happy again now.

Nice!

> I didn't see anything about this change in the release notes (possibly my fault) - it would have saved some confusion if I had been aware this was changing and extra steps were needed, but no harm done. It's certainly more responsive loading that list now.

I completely forgot to check the upgrade from legacy to new page to be honest... so I didn't add it to the release notes. I could probably see if I can force triggering an update as soon as the tomcat server is restarted after the upgrade to save some time.

**Comment by digdilem** [comment]
Closing this - not really a bug. Cedric has provided a solution, and Julio is updating documentation to include this change.

**Comment by juliogonzalez** [comment]
We just refreshed the release notes to explain this: https://lists.opensuse.org/archives/list/announce@lists.uyuni-project.org/thread/ZGMN2RLLLADZKYZI2PCPVQEP2KT3M2VY/
