### ISSUE TITLE
Missing binary spacewalk-setup-httpd on proxy

### ISSUE THREAD

**Issue by Ripper66Six** [uyuni-project/uyuni#6218]
### Problem description

On replace current certificates we get in trouble because the binary spacewalk-setup-httpd for the job was missing.

[root@uyuniproxy01]:~/certs_new # mgr-ssl-cert-setup --root-ca-file=-chain_root_ca.crt --server-cert-file=../usercert.pem --server-key-file=../ serverkey.pem -i chain_subca01.crt -v
sh: /usr/bin/spacewalk-setup-httpd: No such file or directory
After changing the server certificate please execute:
$> spacewalk-service stop
cp: '/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT' and '/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT' are the same file
$> spacewalk-service start

As the CA certificate has been changed, please deploy the CA to all registered clients.
On salt-managed clients, you can do this by applying the highstate.

### Steps to reproduce

1. mgr-ssl-cert-setup --root-ca-file=-chain_root_ca.crt --server-cert-file=../usercert.pem --server-key-file=../ serverkey.pem -i chain_subca01.crt -v

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2022.10-220400.191.2.uyuni2 installed)
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.4 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2022.11-220400.193.3.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : out-of-date (version 2022.10-220400.191.2.uyuni2 installed)
Source package : Uyuni-Proxy-release-2022.11-220400.193.3.uyuni2.src
Summary        : Uyuni Proxy
Description    :
    Uyuni Proxies extend large and/or geographically
    dispersed Uyuni environments to reduce load on the Uyuni
    Server, lower bandwidth needs, and provide faster local
    updates.
```

**Comment by Ripper66Six** [comment]
Hello @mcalmer,

Thanks for the answer :)

On 08/29/2022 the package was removed by an upgrade.
This is not the configured and expected behavior.

[root@proxy]:~ # grep spacewalk-proxy-installer /var/log/zypp* -R
/var/log/zypp/history:# 2022-08-16 14:59:20 spacewalk-proxy-installer-4.3.10-1.6.uyuni2.noarch.rpm installed ok
/var/log/zypp/history:2022-08-16 14:59:20|install|spacewalk-proxy-installer|4.3.10-1.6.uyuni2|noarch||susemanager:uyuni-proxy-stable-leap-154-x86_64|c741951beabde5d9d78b88b646873fb39ae58854702b1b8165d13ef1f8378f8a|
/var/log/zypp/history:2022-08-29 14:34:30|remove |spacewalk-proxy-installer|4.3.10-1.6.uyuni2|noarch||

**Comment by mcalmer** [comment]
Well, this package is required by the proxy pattern. So you cannot have a valid proxy installation if the pattern is not installed.
But if you install this package, changing the certificate is working, right?

**Comment by aaannz** [comment]
I am assuming answer by @mcalmer was enough and I am going to close the issue. Feel free to reopen if there are further problems.

**Comment by Ripper66Six** [comment]
Good morning @mcalmer and @aaannz,

thanks for the reply.
We will test this today.

Many thanks for your help and the informations.


With kind regards,
Pieter Wittmann
