### ISSUE TITLE
spacecmd gives incorrect help message for scap_schedulexccdfscan 

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#6225]
### Problem description

spacecmd gives incorrect help advice:

`spacecmd scap_schedulexccdfscan help` provides this help message:

```
usage: scap_schedulexccdfscan PATH_TO_XCCDF_FILE XCCDF_OPTIONS SYSTEMS
       scap_schedulexccdfscan ssm PATH_TO_XCCDF_FILE XCCDF_OPTIONS
```

The second line appears to be erroneous and incorrect. Using ssm/hostname in that position does create the event but puts 'ssm' as the path to file, causing the event to fail. 

![image](https://user-images.githubusercontent.com/4052275/204301800-44aa7083-9354-4c94-b6c2-a34b0631e9cd.png)

 Using the first method,  with the systems (or ssm) at the end of the line, works as expected.

Suggested fix: Remove second line from spacecmd's help message for this command.

### Steps to reproduce

As above

### Uyuni version

```bash
2022.11
```

**Comment by aaannz** [comment]
Thank you for the report.

This is not only help text issue, parsing of options was indeed wrong. [This commit](https://github.com/uyuni-project/uyuni/commit/8e60271ffde390c2792c3d8e7d1b30c56c9e4de5) should fix it.

But I wonder, if system expansion understands `ssm` keyword, maybe we indeed can rather get rid of this extra ssm parsing and just accept it as system list.

**Comment by aaannz** [comment]
After discussion with maintainers, `ssm` keyword on this position is used on multiple occasions, so I created PR https://github.com/uyuni-project/uyuni/pull/6234 instead to fix this.
