### ISSUE TITLE
Link to documentation 404, possibly branding issue?

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#6242]
### Problem description

The Suse Manager Monitoring page at 

`https://{hostname}/rhn/manager/admin/config/monitoring` has a link to documentation.  (Second of these links)

![image](https://user-images.githubusercontent.com/4052275/205071354-782c5a5f-ebd1-433f-b966-9337097f71c9.png)

That link goes to `https://{hostname}/docs/en/suse-manager/administration/monitoring.html`

Which is 404, displaying Uyuni's 404-catcher page, "Page not found".

A quick `locate` on the filesystem finds these files:

```
/srv/www/htdocs/docs/en/uyuni/administration/monitoring.html
/srv/www/htdocs/docs/en/uyuni/reference/admin/monitoring.html
```

Manually replacing the "suse-manager" in the URL provided by the 404 link with "uyuni" does result in the correct file being displayed.

Conclusion: Possibly a missed link in a previous rebranding, or a symlink is missing that duplicates ./uyuni/ with ./suse-manager/ on the filesystem allowing both to work, or a rewriting rule is missing.

Note: I have not checked for other such links, it's possible there may be more.

### Steps to reproduce

As above.

### Uyuni version

```bash
2022.11
```

**Comment by juliogonzalez** [comment]
I am confused about this description: is this bug about SUSE Manager itself, or about Uyuni?

**Comment by digdilem** [comment]
Apologies if I was unclear. Agree, first line is misleading.

This is with Uyuni, but uyuni is providing a link with "suse-manager" within it.

**Comment by juliogonzalez** [comment]
Aha, thanks.

That URL should be different depending on what product we are building, yes.

We already have that in other places, so I guess the Java code for this section will need some changes to use the right naming.
