### ISSUE TITLE
Upgrade venv-salt-minion to version 3004-10.4.uyuni File /etc/venv-salt-minion/minion.d/_mgractionchains.conf not found

### ISSUE THREAD

**Issue by rchekhina** [uyuni-project/uyuni#6248]
### Problem description

HI After upgraded the venv-salt-minion from version 3004-9.1.uyuni to version 3004-10.4.uyuni I have this error when the service restart:

File /etc/venv-salt-minion/minion.d/_mgractionchains.conf not found

this file doesnt exist on the system not in /etc/salt/minion.d nor /etc/venv-salt-minion/minion.d.

if I create the empty file /etc/venv-salt-minion/minion.d/_mgractionchains.conf the service venv-salt-minion start without error.

Best regards.

### Steps to reproduce

1. upgrade venv-salt-minion from version 3004-9.1.uyuni to version 3004-10.4.uyuni
2. service venv-salt-minion status
3. show error File /etc/venv-salt-minion/minion.d/_mgractionchains.conf not found
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
/var/log/venv-salt-minion.log

[salt.loaded.ext.module.mgractionchains:85  ][ERROR   ][190504] File /etc/venv-salt-minion/minion.d/_mgractionchains.conf not found
```

**Comment by mbussolotto** [comment]
Hi @rchekhina,
File `_mgractionchains.conf` contains information for recovering an action chains after a reboot. So my question: is there any action chains interrupted by a reboot? If this is is not the case, the file should not be used (so it's fine if it does not exist, we need to remove this misleading error). Instead if there's any interrupted action chain, it might be a problem :).

Please let me know,
Thanks!

**Comment by dvosburg** [comment]
In my lab this error appears even on newly-registered minions that have never had Action Chains run on them.

**Comment by saquib-akhtar** [comment]
This is causing too much problems now with newer Uyuni 2022.12 update where repositories are getting denied now. Even could not alter subscriptions now.

**Comment by saquib-akhtar** [comment]
Please raise this as P1 bug now.

**Comment by mbussolotto** [comment]
fixed in the next release

**Comment by saquib-akhtar** [comment]
I am still waiting to see the new package of venv-salt-minion under UYUNI REPO but I couldn't see any new updates yesterday.
When it shall be released or Global REPO has changed ?

**Comment by mbussolotto** [comment]
the bug was not in `venv-salt-minion` but in uyuni. Next release (2023.1) will happen by the end of the month. Anyway, this was just a cosmetic error, so by now you can just ignore the error message.
Thanks
