### ISSUE TITLE
Channel states fail with name '__low__' is not defined on salt-minion 3004+ds-1+187.1.uyuni 

### ISSUE THREAD

**Issue by an0nz** [uyuni-project/uyuni#6270]
### Problem description

salt-common and salt-minion 3004+ds-1+187.1.uyuni fail to join Uyuni correctly with multiple states returning NameError: name '\_\_low\_\_' is not defined

The previous version (3004+ds-1+182.1.uyuni) does not have this issue
Only tested on an Ubuntu 20.04 LTS minion connecting to Uyuni 2022.06

### Steps to reproduce

1. Ensure bootstrap repository contains packages for salt-common and salt-minion 3004+ds-1+187.1.uyuni
2. Bootstrap a new Ubuntu 20.04 LTS Client on latest updates
3. Observe the Apply states [certs, channels, channels.disablelocalrepos, packages, services.salt-minion] step will fail
4. Hardware List Refresh does not return
5. Downgrade minion using `apt install salt-common=3004+ds-1+182.1.uyuni salt-minion=3004+ds-1+182.1.uyuni`
6. Reapply failed states and observe they now work correctly

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.06-183.9.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : out-of-date (version 2022.03-172.4.uyuni1 installed)
Source package : Uyuni-Server-release-2022.06-183.9.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
```

### Useful logs

```bash
Started: 13:11:07.839179
    Duration: 0.866
         SLS: channels.disablelocalrepos
     Changed: {}
----------
          ID: disable_repo_6
    Function: mgrcompat.run
        Name: pkg.mod_repo
      Result: false
     Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2214, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1251, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/module.py", line 390, in run
    log.debug("Detected legacy module.run syntax: %s", __low__["__id__"])
NameError: name '__low__' is not defined
```

**Comment by gabjef** [comment]
We are seeing the same issue with both venv-salt-minion-3004-11.1 (CentOS 7) and venv-salt-minion-3004-11.6 (Rocky 8).

**Comment by saquib-akhtar** [comment]
This same issue now I am seeing across RHEL 8 / SLES 15 and also RHEL 7 where venv-salt-minion has now been updated.

**Comment by mcrispen** [comment]
I was able to at least get the state to run successfully with: 

`sed -i "s/, __low__\[\"__id__\"\]//g" /usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/states/module.py`

or via salt: 

salt '<host>' cmd.run 'sed -i "s/, __low__\[\"__id__\"\]//g" /usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/states/module.py'

**Comment by meaksh** [comment]
This issue was fixed already some time ago: https://github.com/uyuni-project/uyuni/pull/5526 

It is strange that you are still getting this issue. From what I can see, the custom salt state module `mgrcompat` seems out-dated in the minion. These custom salt modules should be synchronized automatically from the Uyuni server to the minions, so I wonder why the minion seems to get an outdated version of the module (without the fix for this issue)

This module is provided to the Uyuni server by the `susemanager-sls` package. Is this package fully updated?

If so, could we get the latest changelog entries for this package? Running this on the Uyuni server:

```console
# rpm -q susemanager-sls --changes | head
```

OTOH, if you want to manually synchronize the modules to the minion:

```console
# salt MINION saltutil.sync_all
```

Hth!

**Comment by parlt91** [comment]
Since there was no followup I assume this is fixed.
Closing...
