### ISSUE TITLE
PAYG documentation missing from setup wizard reference guide

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#6283]
### Problem description

Uyuni appears to have a new tab for "Pay-as-you-go" in the Setup Wizards page at {hostname}/rhn/admin/setup/ProxySettings.do

![image](https://user-images.githubusercontent.com/4052275/206225749-04fe409f-97a5-4aeb-b68e-567ab456fed7.png)

The ? link on this page takes you to what looks like the [correct help page](https://ata-oxy-uyuni01.atass.com/docs/en/uyuni/reference/admin/setup-wizard.html) , but there is no information about this new tab or what it's for.

### Steps to reproduce

Visit page, click help link, be puzzled.

### Uyuni version

```bash
2022.11
```

**Comment by aaannz** [comment]
Thank you for the report, indeed setup wizard documentation is incomplete. PAYG documentation is available at https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/connect-payg.html

**Comment by 0rnela** [comment]
This issue has been foxed.

**Comment by keichwa** [comment]
@0rnela fixed it.
