### ISSUE TITLE
After upgrade from 2022.08 to 2022.11, some repo syncs are failing

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#6298]
### Problem description

After upgrade from 2022.08 to 2022.11, some repo syncs are failing
I have included a python stack trace and sync log example for Remi EL8
Repo syncs were working fine before the 2022.11 upgrade

### Steps to reproduce

1. Sync a repo

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
From error details under Notifications:
Command '[/usr/bin/spacewalk-repo-sync, --channel, rockylinux8-remi-el8-x86_64, --type, yum, --non-interactive]' exited with error code 1: 12:52:47 ======================================
12:52:47 | Channel: rockylinux8-remi-el8-x86_64
12:52:47 ======================================
12:52:47 Sync of channel started.
12:52:48 Unexpected error:
12:52:48 Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 610, in sync
repo_checksum_type = plugin.get_md_checksum_type()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 807, in get_md_checksum_type
if self._md_exists('repomd'):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 756, in _md_exists
self.setup_repo(self.repo)
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 648, in setup_repo
mirrorlist = self._get_mirror_list(repo, self.url)
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 539, in _get_mirror_list
content_type = webpage.headers["Content-Type"]
File "/usr/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
return self._store[key.lower()][1]
KeyError: 'content-type'

12:52:48 Total time: 0:00:00

--------------------------------------------------------------------------------------------------------
From the sync log:
2022/12/08 12:52:47 -04:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'rockylinux8-remi-el8-x86_64', '--type', 'yum', '--non-interactive']
2022/12/08 12:52:47 -04:00 Sync of channel started.
2022/12/08 12:52:48 -04:00 Unexpected error: <class 'KeyError'>
2022/12/08 12:52:48 -04:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 610, in sync
    repo_checksum_type = plugin.get_md_checksum_type()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 807, in get_md_checksum_type
    if self._md_exists('repomd'):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 756, in _md_exists
    self.setup_repo(self.repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 648, in setup_repo
    mirrorlist = self._get_mirror_list(repo, self.url)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 539, in _get_mirror_list
    content_type = webpage.headers["Content-Type"]
  File "/usr/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```

**Comment by gabjef** [comment]
Details about the channel and repo.

Channel info:
GPG key URL: https://uyuni-lab-linux-mgmt.lab.tierpoint.com/pub/remi-el8-gpg-pubkey-5F11735A.key
GPG key ID: 5F11735A
GPG key Fingerprint: 6B38 FEA7 231F 87F5 2B9C A9D8 5550 9759 5F11 735A
GPG public key:
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFpYvNcBEAC2zo9//ebrNepP/TKSCSwRb2V1VGRLL8SS1RrthG26xr/VTxDC
p7ZSxYdEcFl/f0ppjrjTp9LPrPqKL+Hjjw1eDJjRWNOXgSNW/uD5TO5vrbTiIzmb
QIWdMoZ7RUc1pJNHn5DtCjp/6Cm7ntijqxcNYOYd4TEAvv9DPHrj5mYCgLQJ++BT
oONap0cLCRTcEH8q+GqLfwgnLEJ2g7HJYtmlte6YsuKK23GjpvQaNoAzA72aCr47
JKVhH1k1Fzaw1M8tTURe5WWZvxGT/lD+pl0Cf39X7bbatR1r9RiijGROhMfndyO/
wqTKLk6gY6Lm5pj6RTKFg+6AUixcUOn0t2zWY7V4VFNnsxACLcQx04zp9T0lRofc
FCN0HQAMBzo52stezMvLJlncuMYgHuzbkCf7Avan15MwzOO8rrq5v2tokm6tB0Mf
SRK7HT04gBVxJT9Y9IiACr7iCcIJcgysbHsR7LbJay+15xWDA6ywdeXt50MKxUpl
MWeqMnCCdQSNMFRp9hdoKZuo/7PUI+4Wc6ShiFH+WqZ33E6EZbVowC/NHvhrftTP
yo+t6h/ok6l5j+gLYA+Y9VNtt9kfC7rhl1c+3oh01zkO/WVEFy7RDLOm8ah75oMF
2hKP4FSfX3cX7n9baPhKcFHx2namblICnoNBAIDvG9H6/6EYVhTMzDOI2QARAQAB
tClSZW1pJ3MgUlBNIHJlcG9zaXRvcnkgPHJlbWlAcmVtaXJlcG8ubmV0PokCTgQT
AQgAOBYhBGs4/qcjH4f1K5yp2FVQl1lfEXNaBQJaWLzXAhsDBQsJCAcCBhUICQoL
AgQWAgMBAh4BAheAAAoJEFVQl1lfEXNaM5gP/0k2snbeOKSS93DXz8gnItcU8isw
jfy+DA8Oum0vItugVtAnykLgB1h0KyVokuT9QII1KfourxVS4UZo+1QsEAxT/JS0
DT1kWC69kdZzx2j6N5fatBQ/xq8btIHpPl/guaaxgz4db3Hnzly+Gjako1zRUK28
F87i41fAjgky5qbjozqodBfmRCFRqUzX23MtP/b3+GYz4WL4KSPg/OmiPwosYH41
faVH34eFTrXFehOMyjTuAR5MZty+nQUO1gUJrmPYaKiRHnymz0aRPOF8YVpFxVV/
wQBRUGzNpK/UkQPja5w0Ec3EuOoDd3Vn0P1QCSOmicrCkGd6bEcPqL6tIlT0NQ1H
uKv6HJWAlorivFVhfIku+nyBmv5A9j28A80ut8tlRoHIm7RJiPc8INBd7hguNreh
M+iHzGWIrfg255AYt8T+h2LQkMcrIap93U/UYq8d9VKDkJ1uQ+sMtET8wk2RkHhu
GJwJmEFzLUNQ7e156yr3N1BS7caa5grguW1UxOeV2NoFX2e3Wm2VygZymNwa6mZO
7gQPyIY3iWw4WHj5oFKSAYqHcjWOgBQm2V1mGgDJB5j9noI0hJNH533QKK1C/D/g
n9TUOF0G7XthASeYxBHut3y8JalOXWKj+cmXf6+Nw37Q0X6bu+CcEiQN2L8sKwE0
AYmegXGCr9nQi4AkuQINBFpYvNcBEADHD25KtshnEgQLXgexLk5K3WBjCDR/d/vg
no5Tl/6lWRQqpwFAo6N1fCAKoUhlFhdsxR40dNAA8QPYT/EK9c7j/PbknGzp0+dY
vSa7HNQ71JeoEjv/y+UFnZA6ZvDspkNCkj35hc8tDXpJtf3Vbv3gaA7gZ6fpw9OT
/xA6P1leMB1JQm9QEgeiHeNH0rLLpHmfMjMippl3JxL5S4N7FzXmJtnYxpgEn9k/
MMGg4zLisCZeJoT/VU8usjFuV3PPXNnVir3iBv2TwJM9qjcZ48YWfy4ZkFXf+SH0
1fkVkBmmuRs316rIftjnjBWXNaA/StpM2OCCx7ktnj+rIX9Pxnvlz9izDKhqHcUB
cUS3gVkMH7NBTuoP/vIFbenpbOPqRdCVS7u1fpk180T5zyyEEcyzEgWaqCz5soR1
EG7zRTnPb6u9FTsOX9XU6zhOrYd4SZRWFlvkMtcPpW0o126RVAQ8uys0pH2fR3e1
rRWngKs2dAOrKbbITLtXqrXZjlZOWMJS5pDbu8RsMwJDc7yHAJ1O0pYE2SC8vgqg
ZjHZeJ8mrobVcvMXnLCzyri8ZcuIDKGscmiOznN666t2yaYYIf2EmkrzjKxh09M8
NdpNG/LxyIn3kAG4vObjmKZ0r2BHlsdyJ33wN1qSWtFKeZrc8JnQJbT3eHE0VMP7
/UjxADwqZQARAQABiQI2BBgBCAAgFiEEazj+pyMfh/UrnKnYVVCXWV8Rc1oFAlpY
vNcCGwwACgkQVVCXWV8Rc1qyQw//W4DqpkzQMjcnTrjwPq5daxJSQnPKhatVQj2o
bdb0yRo+Qd8YoTFlldQJY1+zzRiiQ7qO40DZWU/mejgMajmOX2tjFozCa3ENbb6r
w49BlSbrMyI2kAOtwSTehrzprgzblQhcQy0mM4oxRePQcRZynN4nYA8afb5ROjzN
Cb4+UAlnTKGukzakmRiPKUInepdTUnA/4UZFQEHj2nb8iP/RxeI1bCMOQoxQMhYh
dpsCoCOKcmvNYZPVjz3/tmdjet+5WLtzy4xcYqOJQ6aNF4ggjBfuMYRuiFjpMazm
FS1kDcYtcEAOV6tZ+dlsHYJdoJh52ghUs/kxPJlZM+VzFv/10ToWpCNVwqC+BDXC
gXUZYxo5XIwUzIbUlHuhVcGsCxEgndaf5qzu0UWGoLdmLgo56yg4ivUATGRnm92T
WXgjHzSuJhsVEmriswqxd1h4R9EF1TWNhwc4RhrvomzDTuXIy3kAaORqVxCZgbxj
sSY0+jqkX/AEU0cR4aiD4fEvMPeHJwoo0vnS1nETi2KZrhEnGa6JhJxe91V0vAxR
9tBx2KLkl4uYHJELoH9JOcv4WMFMgdoA2MjcIzhH5Cc4t+vQC2cK8lLT7IiGfI57
vhFCsz+GEqHusDfQgLAp0onI9wwCUwtiFZh4jMOJvk6HMGaGVSP30zh1bGqIPjFS
qk7agVI=
=sJgk
-----END PGP PUBLIC KEY BLOCK-----

Repo:
Repository URL: http://cdn.remirepo.net/enterprise/8/safe/x86_64/mirror

Not using signed metadata.

**Comment by gabjef** [comment]
Update
I replaced the REMI repo mirror list URL with "http://rpms.remirepo.net/enterprise/8/safe/x86_64/" and the sync worked fine.
Given that the above mirror list worked in 2022.08, and earlier, I will leave this issue open for now.

**Comment by mbussolotto** [comment]
Hi @gabjef , sorry maybe I'm missing something. I don't see `rockylinux8-remi-el8` here https://github.com/uyuni-project/uyuni/blob/master/utils/spacewalk-common-channels.ini . I guess you had `http://cdn.remirepo.net/enterprise/8/safe/x86_64/mirror` and it worked until 2022.08: now you changed it to `http://rpms.remirepo.net/enterprise/8/safe/x86_64/` , right?

**Comment by ChrisN812** [comment]
I wanted to add an additional error I now see with my RHEL repository sync, which I've not seen before in previous versions of Uyuni.  I have updated to the latest version via the patch repository"

09:38:58 ======================================
09:38:58 | Channel: rhel7-x86_64-server
09:38:58 ======================================
09:38:58 Sync of channel started.
Preparing custom SSL CAPATH at /var/cache/rhn/reposync/.ssl-certs/1
Retrieving repository 'rhel7-x86_64-server' metadata ....................................................[done]
Building repository 'rhel7-x86_64-server' cache .........................................................[done]
All repositories have been refreshed.
09:39:13
09:39:13   Importing comps file f9f16c24eddc2f6eb2088a4148b95bc912176719-comps.xml.
09:39:13   Renaming non-standard filename f9f16c24eddc2f6eb2088a4148b95bc912176719-comps.xml to comps.xml.
09:39:13 *** NOTE: Importing comps file for the channel 'rhel7-x86_64-server'. Previous comps will be discarded.
09:39:15 Repo URL: https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os
09:39:15     Packages in repo:             33401
09:40:31     No new packages to sync.
09:40:33
09:40:33   Patches in repo: 5075.
09:40:48     No new patch to sync.
**09:40:48 ERROR[14/403]: Media product file download failed: https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os/media.1/products - HTTPS Error 403 - Forbidden**
09:40:48   Updating overview of 139 systems
09:40:53 Sync completed.

This similar error shows up on all my RHEL repository syncs for EL7, EL8 and EL9.

**Comment by gabjef** [comment]
> Hi @gabjef , sorry maybe I'm missing something. I don't see `rockylinux8-remi-el8` here https://github.com/uyuni-project/uyuni/blob/master/utils/spacewalk-common-channels.ini . I guess you had `http://cdn.remirepo.net/enterprise/8/safe/x86_64/mirror` and it worked until 2022.08: now you changed it to `http://rpms.remirepo.net/enterprise/8/safe/x86_64/` , right?

@mbussolotto `rockylinux8-remi-el8` is a custom channel we configured in Uyuni. It points to the RHEL 8 / CentOS 8 repo from [Remi's RPM repository](https://rpms.remirepo.net/). We use it for a few of our internal support servers.
But that is correct, we were using the mirror list pre-2022.11 and it was working. We discovered that using the mirror list in 2022.11 is broken, but switching to the direct base URL for the repo works.

**Comment by mbussolotto** [comment]
```
From error details under Notifications:
Command '[/usr/bin/spacewalk-repo-sync, --channel, rockylinux8-remi-el8-x86_64, --type, yum, --non-interactive]' exited with error code 1: 12:52:47 ======================================
12:52:47 | Channel: rockylinux8-remi-el8-x86_64
12:52:47 ======================================
12:52:47 Sync of channel started.
12:52:48 Unexpected error:
12:52:48 Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 610, in sync
repo_checksum_type = plugin.get_md_checksum_type()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 807, in get_md_checksum_type
if self._md_exists('repomd'):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 756, in _md_exists
self.setup_repo(self.repo)
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 648, in setup_repo
mirrorlist = self._get_mirror_list(repo, self.url)
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 539, in _get_mirror_list
content_type = webpage.headers["Content-Type"]
File "/usr/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
return self._store[key.lower()][1]
KeyError: 'content-type'

12:52:48 Total time: 0:00:00

--------------------------------------------------------------------------------------------------------
From the sync log:
2022/12/08 12:52:47 -04:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'rockylinux8-remi-el8-x86_64', '--type', 'yum', '--non-interactive']
2022/12/08 12:52:47 -04:00 Sync of channel started.
2022/12/08 12:52:48 -04:00 Unexpected error: <class 'KeyError'>
2022/12/08 12:52:48 -04:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 610, in sync
    repo_checksum_type = plugin.get_md_checksum_type()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 807, in get_md_checksum_type
    if self._md_exists('repomd'):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 756, in _md_exists
    self.setup_repo(self.repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 648, in setup_repo
    mirrorlist = self._get_mirror_list(repo, self.url)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 539, in _get_mirror_list
    content_type = webpage.headers["Content-Type"]
  File "/usr/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```

@zzaimeche (as author)  @meaksh (as reviewer)  it seems that's something introduced by these changes https://github.com/uyuni-project/uyuni/commit/56699a2a96a0bec7294922710e7fe8a328d336ba ...can you please have a look?

**Comment by rulev** [comment]
The case of this issue is cdn.remirepo.net actually does not return Content-Type header:
```
curl -D - -o /dev/null http://cdn.remirepo.net/enterprise/8/safe/x86_64/mirror
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Date: Thu, 15 Dec 2022 16:27:19 GMT
Server: Apache/2.4.37 (centos) OpenSSL/1.1.1k
Last-Modified: Fri, 02 Dec 2022 12:39:06 GMT
ETag: "ecd-5eed79f90f0d2"
Accept-Ranges: bytes
Content-Length: 3789
```

But rpms.remirepo.net does:
```
curl -D - -o /dev/null http://rpms.remirepo.net/enterprise/8/safe/x86_64/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Date: Thu, 15 Dec 2022 16:27:53 GMT
Server: Apache/2.4.37 (centos) OpenSSL/1.1.1k
Transfer-Encoding: chunked
Content-Type: text/html;charset=ISO-8859-1
```

In your code you should check if this header present.

**Comment by zzaimeche** [comment]
Thanks for the report! I think I know why this is happening; looks like when a page is cached it doesn't return a Content-Type header (https://www.rfc-editor.org/rfc/rfc7232#section-4.1). I didn't realise that was left out. I can update the code to wrap the content-type check in an 'if' block, so that if there's no header at all the page is treated as though it's the right content-type, though at that point it's a bit of a weird check so maybe it indicates we should be using a different approach to filter out invalid urls longterm...

**Comment by Q-Storm** [comment]
I get the same error when Syncing repos from elasticsearch [https://artifacts.elastic.co/packages/8.x/yum]
`2023/01/08 11:16:03 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'rockylinux8-x86_64-elasticsearch-8', '--type', 'yum', '--non-interactive']
2023/01/08 11:16:03 +02:00 Sync of channel started.
2023/01/08 11:16:03 +02:00 Unexpected error: <class 'KeyError'>
2023/01/08 11:16:03 +02:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 626, in sync
    repo_checksum_type = plugin.get_md_checksum_type()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 808, in get_md_checksum_type
    if self._md_exists('repomd'):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 757, in _md_exists
    self.setup_repo(self.repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 649, in setup_repo
    mirrorlist = self._get_mirror_list(repo, self.url)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 539, in _get_mirror_list
    content_type = webpage.headers["Content-Type"]
  File "/usr/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
`
