### ISSUE TITLE
problem themes display

### ISSUE THREAD

**Issue by rchekhina** [uyuni-project/uyuni#6388]
### Problem description

HI,

When I change the uyuni theme from uyuni to susemanager-light or susemanager-dark there is a problem with the display of the select box on the system list:

![image](https://user-images.githubusercontent.com/78473404/209333365-14236d8c-85a6-4a1c-9129-1733fdc6925f.png)

Can you look it please?

Best regards.

### Steps to reproduce

1. Go to preferences
2. change theme to susemanager-ligh or susemanager-dark
3. Go to list all systems
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.195.1.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.195.1.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by mbussolotto** [comment]
CC @cbbayburt

**Comment by rchekhina** [comment]
HI,

I have upgraded from version 2022.12 to 2023.01 and the issue is still here.

Best regards.

**Comment by Etheryte** [comment]
Thanks for the heads up, this was fixed in https://github.com/uyuni-project/uyuni/pull/6596.
