### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: column "physical" does not exist

### ISSUE THREAD

**Issue by cheesetrain** [uyuni-project/uyuni#6461]
# Question

After upgrading to the 2022.12 version of Uyuni I am seeing the error below in my /var/log/rhn/rhn_web_ui.log.  I have not been able to find any information regarding this error message.  Short of manually adding the column to the backend database does anybody know how to fix this?  I upgraded from Uyuni 2022.08.

org.postgresql.util.PSQLException: ERROR: column "physical" does not exist

## Version of Uyuni Server and Proxy (if used)

2022.12

**Comment by mcalmer** [comment]
Please check the schema migation logs in `/var/log/spacewalk/schema-upgrade/`
I am pretty sure that something failed there.

**Comment by cheesetrain** [comment]
I got lucky and still had a vmware snapshot from before I performed the upgrade.  I reverted back to the snapshot and ran through the upgrade again.  This time things worked and no database missing columns.

**Comment by mcalmer** [comment]
ok

**Comment by mcalmer** [comment]
Good to hear that it worked on the second try at least
