### ISSUE TITLE
"Recently Registered Systems page" returns a 404 if the system list is completely empty

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#6558]
### Problem description

When you have no minions, the overview shows:

![image](https://user-images.githubusercontent.com/4226070/216029915-c1b459a5-c915-45e0-b6e0-923b1c58f6a3.png)

Clicking `Systems > Recently Registered` returns a 404 error.
![image](https://user-images.githubusercontent.com/4226070/216028360-a2ddee71-b0c0-45b1-8dae-2e244b6a7722.png)

Clicking `View All Recently Registered Systems` works OK.

I am not 100% sure if this only happens when a single cliet is onboarded and then removed (so the are no more clients), or even when no clients at all were ever registered

TBH:
```
No recently registered systems.
You have no systems that were registered within the past 30 days. You may view a list of all registered systems at Systems > Recently Registered
```

Looks strange. If the are no recently registered systems, why do we even provide a user to check them? Is it because that "Recently Registered" list can provide systems registered 60 days ago, for example?

### Steps to reproduce

1. Install a clean Uyuni server
2. Check the UI

If things are working, then:
3. Bootstrap a minion  with a bootstrap script
4. Remove from Uyuni
5. Go to overview, follow the link. It should return a 404

### Uyuni version

```bash
2023.01, but it's from master with my changes for the support of openSUSE Leap Micro
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
Could not find anything.
```

**Comment by cbbayburt** [comment]
I can't seem to reproduce this one anymore. It's likely fixed with the new systems list implementation.
