### ISSUE TITLE
 mgr-bootstrap failied - missing package: python3-ordered-set

### ISSUE THREAD

**Issue by Ripper66Six** [uyuni-project/uyuni#6663]
### Problem description

On our UYUNI instance we´ve got the problem that the python3-ordered-set packe is not longer available.
In this case we have many errors at the bootstrap process.

On the manual run we got the following output:

Temporary output repo path: /srv/www/htdocs/pub/repositories/sle/15/2/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
ERROR: package 'python3-ordered-set' not found

Suggestions:
mgr-create-bootstrap-repo uses the locally synchronized versions of files
from the Tools repository, and uses the locally synchronized pool channel
for dependency resolution.
Both should be fully synced before running the mgr-create-bootstrap-repo script.

### Steps to reproduce

1. mgr-create-bootstrap-repo -i

2. SLE-15-SP2-x86_64

3. ERROR: package 'python3-ordered-set' not found

### Uyuni version

```bash
zypper info Uyuni-Server-release
Loading repository data...
Warning: Repository 'Main Update Repository' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.01-220400.196.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.01-220400.196.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
Not needed
```

### Useful logs

```bash
No files
```

### Additional information

Also seen this problem in [Systems failed to run sync_states](https://github.com/uyuni-project/uyuni/issues/6530#top)
#6530

**Comment by Ripper66Six** [comment]
Update on this issue.

The same behaviour we have on SLES15 SP2 & SP3

SLE-15-SP3-x86_64
ERROR: package 'python3-ordered-set' not found

SLE-15-SP2-x86_64
ERROR: package 'python3-ordered-set' not found

**Comment by MetalMinotaur** [comment]
Yes, can confirm (SLES15 SP1+)

**Comment by mcalmer** [comment]
In SP4 python3-ordered-set is required by python3-setuptools which is required by python3-cryptography which is required by python3-urllib, required by python3-urllib3 which is finally required by python3-salt.
 So in SP4 it seems we really need it.

But in SP3, python3-setuptools does not require python3-ordered-set. So maybe we make it optional?

**Comment by juliogonzalez** [comment]
> In SP4 python3-ordered-set is required by python3-setuptools which is required by python3-cryptography which is required by python3-urllib, required by python3-urllib3 which is finally required by python3-salt. So in SP4 it seems we really need it.
> 
> But in SP3, python3-setuptools does not require python3-ordered-set. So maybe we make it optional?

I'd say so, yeah. Can you prepare the fix and backport as needed?

**Comment by mcalmer** [comment]
fix merged. Will be available in the next release

**Comment by Ripper66Six** [comment]
Cheers,

many thanks for the quick solution.

Kind regards :)
