### ISSUE TITLE
mgr-create-bootstrap-repo commend giving error

### ISSUE THREAD

**Issue by rakeshsujan** [uyuni-project/uyuni#6693]

**Comment by rakeshsujan** [comment]
When i try to merge the Centos7 repo it's giving an below error message. 

Find the below command output & help to fix the issue.

uyuni:/srv/www/htdocs/pub/bootstrap # mgr-create-bootstrap-repo  -c centos-7-x86_64-uyuni --with-custom-channel

Creating bootstrap repo for centos-7-x86_64-uyuni
copy 'iproute-4.11.0-30.el7.x86_64'
copy 'iptables-1.4.21-35.el7.i686'
copy 'iptables-1.4.21-35.el7.x86_64'
copy 'libmnl-1.0.3-7.el7.i686'
copy 'libmnl-1.0.3-7.el7.x86_64'
copy 'libnetfilter_conntrack-1.0.6-1.el7_3.i686'
copy 'libnetfilter_conntrack-1.0.6-1.el7_3.x86_64'
copy 'libnfnetlink-1.0.1-4.el7.x86_64'
copy 'libnfnetlink-1.0.1-4.el7.i686'
copy 'logrotate-3.8.6-19.el7.x86_64'
copy 'python-babel-0.9.6-8.el7.noarch'
copy 'python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch'
copy 'python-backports-1.0-8.el7.x86_64'
copy 'python-futures-2.1.3-0.8.12.uyuni.x86_64'
copy 'python-jinja2-2.7.2-4.el7.noarch'
copy 'python-msgpack-python-0.4.6-2.12.uyuni.x86_64'
copy 'python-psutil-5.0.1-1.4.uyuni.x86_64'
copy 'python-pycrypto-2.6.1-2.12.uyuni.x86_64'
copy 'python-requests-2.6.0-10.el7.noarch'
copy 'python-setuptools-0.9.8-7.el7.noarch'
copy 'python-singledispatch-3.4.0.3-4.5.uyuni.noarch'
copy 'python-tornado-4.2.1-5.el7.x86_64'
copy 'python-zmq-14.5.0-3.12.uyuni.x86_64'
copy 'zeromq-4.0.5-1.12.uyuni.x86_64'
copy 'python-certifi-2015.9.6.2-2.12.uyuni.noarch'
copy 'PyYAML-3.10-11.el7.x86_64'
copy 'python-markupsafe-0.11-10.el7.x86_64'
copy 'python-urllib3-1.10.2-7.el7.noarch'
copy 'libyaml-0.1.4-11.el7_0.i686'
copy 'libyaml-0.1.4-11.el7_0.x86_64'
copy 'python-chardet-2.2.1-3.el7.noarch'
copy 'python-six-1.9.0-2.el7.noarch'
copy 'yum-3.4.3-168.el7.centos.noarch'
copy 'openssl-1.0.2k-19.el7:1.x86_64'
copy 'openssl-libs-1.0.2k-19.el7:1.i686'
copy 'openssl-libs-1.0.2k-19.el7:1.x86_64'
copy 'python-ipaddress-1.0.16-2.el7.noarch'
copy 'redhat-rpm-config-9.1.0-88.el7.centos.noarch'
copy 'rpm-python-4.11.3-45.el7.x86_64'
copy 'venv-salt-minion-3004-15.1.uyuni.x86_64'
copy 'dmidecode-3.2-5.el7:1.x86_64'
Directory walk started
Directory walk done - 41 packages
Temporary output repo path: /srv/www/htdocs/pub/repositories/centos/7/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
ERROR: package 'salt' not found
ERROR: package 'salt-minion' not found
ERROR: package 'python2-salt' not found

Suggestions:
mgr-create-bootstrap-repo uses the locally synchronized versions of files
from the Tools repository, and uses the locally synchronized pool channel
for dependency resolution.
Both should be fully synced before running the mgr-create-bootstrap-repo script.

**Comment by rakeshsujan** [comment]
Hi Mcalmer,

But when i tried to do bootstrapping of Centos7 i am getting an below error.

![image](https://user-images.githubusercontent.com/50227412/223641045-70922715-e907-4b7c-bf8f-a087410862ef.png)

**Comment by mcalmer** [comment]
Please have a look at the client if you can find any "salt" log. Look for salt-ssh.log or venv-salt-minion.log.
On the uyuni server side, please check the salt master and api logs for any message.
Also rhn_web_ui.log can have something.

We need more info about what could not be parsed.
And please add the logfiles or what you found to https://github.com/uyuni-project/uyuni/issues/6699
We keep this open for the change needed in mgr-create-bootstrap-repo data file

**Comment by rakeshsujan** [comment]
Is there any way that i can install the Uyuni version of 2022.12-220400.1.1.uyuni2 ??

If yes can u share the steps to install.

**Comment by juliogonzalez** [comment]
@rakeshsujan, Uyuni is rolling release, and going back is not supported.

I merged the fix for the problems creating the bootstrap repo (as mc can be ignored for now).

Closing this issue. We'll track the bootstrap problem issue itself on the other issue.
