### ISSUE TITLE
Handling AlmaLinux AppStream modules 

### ISSUE THREAD

**Issue by bigmike-19** [uyuni-project/uyuni#6806]
Hi Everyone, 

We have a subset of AlmaLinux 8 servers and we are syncing the AlmaLinux repositories. Uyuni reports there are bugfixes available. I push out the update, it looks to be successful. However, the update still reports in the console. Interesting enough, when we run "dnf update", no updates are available. Looking at the updates listed as needed in Uyuni, they appear to be modules from the AppStream repository.  Does anyone have any insight on how to properly handle updating modules in Uyuni?

Thanks, 
Mike

**Comment by cbbayburt** [comment]
The way we handle AppStream modules has changed since version 2024.05. This problem should not happen anymore. Please reopen if you see the issue again after this version.
