### ISSUE TITLE
Deleting systems causes high load and unresponsiveness.

### ISSUE THREAD

**Issue by digdilem-work** [uyuni-project/uyuni#6925]
### Problem description

I deleted three systems from my Uyuni installation today,  each in its own browser tab. 

Whilst the actions completed, Uyuni became unresponsive and very slow. 

On checking with htop, I abserved the Uyuni vm's load was above 10 (it's a 2 core machine with 12g/ram) and postgres was taking the load.

![image](https://user-images.githubusercontent.com/130057973/234200695-b1a2b138-afec-4cc4-8e67-6993848ecd5d.png)

This state continued for around five minutes before load dropped to normal levels and responsiveness returned.

I _assume_ that when deleting a system, Uyuni is searching its database and purging references and logs relating to the deleted system, and by me triggering three in a row this temporarily overwhelmed the system. 

It turns out I seem to have quite a large database too, which possibly doesn't help;

```
ata-oxy-uyuni01:/var/lib/pgsql # du -shc *
4.0K    analyze_new_cluster.sh
23G     data
20G     data-pg13
4.0K    delete_old_cluster.sh
4.0K    initlog
42G     total

```

If my assumption is correct and each delete triggers an expensive search and purge of the entire database, might it be better to queue such requests and single-thread them as a periodic maintenance task which might be more controllable? 

Or is my database unusually large and there is something I can do to shrink it?

(This system has been running and upgraded in turn shortly after Uyuni was forked from Spacewalk, and currently has around 220 EL clients)

### Steps to reproduce

1. Open multiple browser tabs for machines. 
2. Click "Delete machine", wait for the check, then click the red button to "yes, really do that"
3. Watch system load escalate and uyuni stop responding. 
4. Go make a cup of tea whilst it sorts it all out.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.03-220400.199.1.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.03-220400.199.1.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```
```


### Uyuni proxy version (if used)

_No response_

### Useful logs

_No response_

### Additional information

_No response_

**Comment by digdilem-work** [comment]
Note: Even deleting a single system causes a load in excess of 2 and some unresponsiveness for several minutes with multiple postgres SELECT and DELETE commands and autovacuum.

**Comment by avshiliaev** [comment]
Hey @digdilem-work. Thanks for your report. Can you try running the following command on the server and check whether the load is still high?

```
spacewalk-sql --select-mode - <<<"vacuum (full, analyze)
rhnServer;vacuum (full, analyze) 
rhnErrata;vacuum (full, analyze) 
rhnServerInfo;vacuum (full, analyze) 
rhnServerPackage;vacuum (full, analyze) 
rhnPackage;vacuum (full, analyze) 
rhnErrataPackage;vacuum (full, analyze) 
rhnerratakeyword;vacuum (full, analyze) 
rhnUserServerPerms;"
```

**Comment by digdilem-work** [comment]
Hi, and thanks for the reply. 

I've run that and it's taken 35 minutes so far, at low system load. 

I'll let it complete, but I don't have any systems available to delete at the present to test for comparison - but next time I have one to delete, I'll try and remember to time it and update this then.

Thanks

**Comment by digdilem-work** [comment]
I left this running overnight, but had to kill it as it was still running after 20 hours, and blocks uyuni from doing its normal housekeeping, as well as an inability to use the webui.   

Disappointingly, even after 20 hours of work, the database hasn't shrunk at all...

Thoughts?

**Comment by slsnow** [comment]
That's kind of crazy it took that long. 

I believe the "VACUUM FULL" rewrites the entire content (locks while doing so). If it didn't complete, then it probably won't return space to the operating system. 

Refer here: https://www.postgresql.org/docs/current/sql-vacuum.html#:~:text=VACUUM%20FULL%20rewrites%20the%20entire,while%20it%20is%20being%20processed

[VACUUM FULL]
>This method also requires extra disk space, since it writes a new copy of the table and doesn't release the old copy until the operation is complete.
 
---
 
If you try it again, you might want to just `spacewalk-service stop` while you're doing it, unless you can't do that for 20+ hours again. You could always try a `spacewalk-sql --select-mode - <<<"VACUUM ANALYZE;"` first and see if that helps at all.

Just FYI, I tested deleting 4 clients at the same time and I went to 0.3 load for 15 seconds or so, and back down to below ".1", but on SUMA 4.3.5 (16G RAM, 2CPU)

**Comment by mbussolotto** [comment]
> If you try it again, you might want to just spacewalk-service stop 
@digdilem-work this should help to reduce execution time, please let us if it works :)
