### ISSUE TITLE
Errata/Patches tab is missing on ChannelDetail page for Ubuntu Systems

### ISSUE THREAD

**Issue by lumarel** [uyuni-project/uyuni#6966]
### Problem description

If you open any of the Ubuntu channels on a synced system, you won't see the tab in the header:

![image](https://user-images.githubusercontent.com/42647570/235601745-47a5c9c1-cb8a-4c04-8e47-67e2ad60f69c.png)
![image](https://user-images.githubusercontent.com/42647570/235602236-97d39de5-9a1f-42d0-903c-486750706f3b.png)

### Steps to reproduce

1. Sync Ubuntu 20.04 LTS or 22.04 LTS
2. Go to the channel list (/rhn/software/channels/All.do)
3. Open one of the Ubuntu repos that have patches in the Patches column
4. Click on the Patches number
5. See that the Patches are there on the /rhn/channels/ChannelErrata.do?cid=<cid> page, but the tab in the top nav is missing
6. Click on Details
7. Still don't see the Patches button in the navigation bar

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.03-220400.199.1.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.03-220400.199.1.uyuni2.src
```

**Comment by lumarel** [comment]
Just noticed that it's also happening on `/rhn/channels/manage/errata/Errata.do`

**Comment by mcalmer** [comment]
Right, the ACL is just checking for rpm 

ChannelAclHandler.java: aclChannelTypeCapable()
