### ISSUE TITLE
Uyuni Server Setup

### ISSUE THREAD

**Issue by rakeshsujan** [uyuni-project/uyuni#7034]

**Comment by rakeshsujan** [comment]
Hello Team,

It's possible to set up a Uyuni server in Rocky Linux instead of Opensuse. Because in our organization the Antivirus agent is not supported by the Opensuse .

If it's possible to setup in rockylinux can you guide us?

**Comment by mcalmer** [comment]
@sbluhm might be able to give tips

**Comment by sbluhm** [comment]
Thank you for the reference. Not sure why I don't get notified...

@rakeshsujan , use this link. https://www.bluhm-de.com/content/os-tools/en/applications/uyuni/installing-uyuni-on-almalinux-9.html
On the next release, I will update the doc so you have a release version. At the moment it is synched with the unreleased master version.

**Comment by rakeshsujan** [comment]
Hi Sbluhm,

Thanks for the Link which you shared.

In the link it's mentioned Alma Linux 9 instead of Alma Linux 9 can I use the Rocky Linux 9?

**Comment by sbluhm** [comment]
Yepp, should work. If not, please let me know

**Comment by rakeshsujan** [comment]
Hi Sbluhm,

While downloading the Uyuni package i am getting the below error.

[root@uyuni ~]# dnf -y install patterns-uyuni_server $NEWPACKAGES
created by dnf config-manager from https://download.opensuse.org/repositories/home:/sbluhm:/branches:/systemsmanagement:/Uyuni:/Master/EL_9/                                                           0.0  B/s |   0  B     00:18
Errors during downloading metadata for repository 'download.opensuse.org_repositories_home_sbluhm_branches_systemsmanagement_Uyuni_Master_EL_9_':
  - Curl error (28): Timeout was reached for https://download.opensuse.org/repositories/home:/sbluhm:/branches:/systemsmanagement:/Uyuni:/Master/EL_9/repodata/repomd.xml [Failed to connect to download.opensuse.org port 443: Connection timed out]
  - Curl error (7): Couldn't connect to server for https://download.opensuse.org/repositories/home:/sbluhm:/branches:/systemsmanagement:/Uyuni:/Master/EL_9/repodata/repomd.xml [Failed to connect to download.opensuse.org port 443: Connection refused]
Error: Failed to download metadata for repo 'download.opensuse.org_repositories_home_sbluhm_branches_systemsmanagement_Uyuni_Master_EL_9_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
[root@uyuni ~]#

**Comment by sbluhm** [comment]
Hello @rakeshsujan ,

you picked the wrong time, it seems. The repository server is currently not available (see ticket: https://progress.opensuse.org/issues/129721).

If this is urgent for you and you cannot wait until the server is fixed, follow these instructions below instead of the second grey box on my installation page:
```
dnf -y copr enable sbluhm/uyuni-server 
dnf -y config-manager --add-repo https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-9-x86_64/
dnf -y install patterns-uyuni_server

curl https://raw.githubusercontent.com/sbluhm/uyuni-repo/master/root/setup_env.sh > /root/setup_env.sh
curl https://raw.githubusercontent.com/sbluhm/uyuni-repo/master/patch9.sh | bash # Installs current fixes
# Edit your installation configuration here NOW (do it manually): /root/setup_env.sh

# Start the installation of the server now:
/usr/lib/susemanager/bin/mgr-setup -s
```

**Comment by rakeshsujan** [comment]
Hello @sbluhm 

I have implemented the Uyuni server in the Rocky Linux 9.2 without any issues.

But while starting the setup I get the below error message it will cause anything?

Find the below output for your reference. 

[root@uyuni ~]# /usr/lib/susemanager/bin/mgr-setup -s
Asserting correct java version...
/var/spacewalk already exists. Leaving it untouched.
Filesystem type for /var/cache is xfs - ok.
Open needed firewall ports...
success
Initializing PostgreSQL  at location /var/lib/pgsql/14/data
CREATE ROLE
* Loading answer file: /root/spacewalk-answers.
** Database: Setting up database connection for PostgreSQL backend.
** Database: Populating database.
** Database: --clear-db option used.  Clearing database.
** Database: Shutting down spacewalk services that may be using DB.
** Database: Services stopped.  Clearing DB.
*** Progress: ###########################
* Setting up users and groups.
* Performing initial configuration.
* Configuring apache SSL virtual host.
** /etc/httpd/conf.d/ssl.conf has been backed up to ssl.conf-swsave
* Creating SSL certificates.
** SSL: Generating CA certificate.
** SSL: Generating server certificate.
** Database: Setting up report database.
** Database: --clear-db option used.  Clearing report database.
*** Progress: #
** Database: Installation complete.
* Report DB Configured.
* Update configuration in database.
* Setting up Cobbler..
* Deploying configuration files.
* Restarting services.
Installation complete.
Visit https://uyuni.demo.com to create the Uyuni administrator account.
**General error:
        Gate error: Custom database component? Please strictly use SUSE components only!**

Shutting down spacewalk services...
Done.
Starting spacewalk services...
  Checking DB schema and running DB schema upgrade if needed. This may take a while.
  Call the following command to see progress: journalctl -f -u uyuni-check-database.service
Done.
success

**Comment by sbluhm** [comment]
@rakeshsujan , the "Gate Error" message is unfortunately expected. It is on my removal list.
Do let me know if you see any issues though. I am not aware of any at the moment.

**Comment by rakeshsujan** [comment]
@sbluhm 

While syncing the rockylinux9-uyuni client I am getting the below error. It's due to that the repository server is down it's causing this issue?


[root@uyuni ~]# spacewalk-repo-sync --channel=rockylinux9-uyuni-client-x86_64
16:35:46 ======================================
16:35:46 | Channel: rockylinux9-uyuni-client-x86_64
16:35:46 ======================================
16:35:46 Sync of channel started.

(process:19310): librepo-WARNING **: 16:35:49.462: LRO_MIRRORLISTURL processing failed: Status code: 404 for https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/ (IP: 116.202.118.202)
16:35:50 Unhandled error occurred: Failed to download metadata for repo 'External_-_Uyuni_Client_Tools_for_Rocky_Linux_9_x86_64_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
16:35:50 RepoMDError: Failed to download metadata for repo 'External_-_Uyuni_Client_Tools_for_Rocky_Linux_9_x86_64_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
16:35:50 Total time: 0:00:04
[WARNING ] Errors during downloading metadata for repository 'External_-_Uyuni_Client_Tools_for_Rocky_Linux_9_x86_64_':
  - Status code: 404 for https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/repodata/repomd.xml (IP: 116.202.118.202)
  - Status code: 404 for https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/ (IP: 116.202.118.202)
[root@uyuni ~]#

**Comment by sbluhm** [comment]
See my comment from earlier:

> you picked the wrong time, it seems. The repository server is currently not available (see ticket: https://progress.opensuse.org/issues/129721).

I am also stuck on this step for my testing at the moment. So you have to wait, I guess.

**Comment by sbluhm** [comment]
Try now? Seems to be back again. (at least for my required area)

**Comment by rakeshsujan** [comment]
@sbluhm 

Yes now it's working fine without any issues, successfully configured the Uyuni server setup in Rocky Linux 9 and I have connected one Rocky Linux 9 machine to the Uyuni server it's communicating without any issues.

Thanks for your support @sbluhm

**Comment by rakeshsujan** [comment]
@sbluhm 

One last question i want to ask currently the Uyuni version is 2023.04 it's possible to install 2023.02 or 2023.03 version of Uyuni application?

If yes can you share me the procedure please

**Comment by sbluhm** [comment]
@rakeshsujan , not without a lot of manual effort.
The required packages would have to be rebuild. You could try by cloning the above mentioned copr repository and rebuild the Uyuni packages by using the relevant github commit of the release.

I only have the current master (the one you used which is closer to 2023.05) and a backup of 2023.04 release which might require some minor work to get working.

**Comment by rakeshsujan** [comment]
@sbluhm ,

For some servers While bootstrapping the client machine getting the below error.

![image](https://github.com/uyuni-project/uyuni/assets/50227412/da49d960-9afb-4f5b-a8d0-b8a7ebfed453)

**Comment by sbluhm** [comment]
Can you please open a new discussion for that (https://github.com/uyuni-project/uyuni/discussions)? I don't think this is Rocky Linux 9 related.
Or maybe contact the team via chat/gitter: https://app.gitter.im/#/room/#uyuni-project_users:gitter.im

**Comment by rakeshsujan** [comment]
@sbluhm 

I created the new already for this #7125
