### ISSUE TITLE
Also trigger "System requires Reboot" info using SALT

### ISSUE THREAD

**Issue by heiwu** [uyuni-project/uyuni#7053]
# Short description

Uyuni recognizes and shows systems, that need to be rebooted, based on upgraded/installed RPMs. Please make it possible to also trigger this information/notification within SALT, e.g. if we changed some kernel/boot config.

# Details

- `needs-restarting / zypper needs-rebooting` within OS depends on existence of file `/run/reboot-needed`, but uyuni currently doesn't care about that file. Maybe if uyuni could check for that file after each client property/software/state update, that could be the trigger for showing the notification in GUI?
- maybe [salt.modules.system.[set/get]_reboot_required_witnessed](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.system.html#salt.modules.system.set_reboot_required_witnessed) helps?

**Comment by agraul** [comment]
Recently we added a beacon for SLE Micro that's similar to what you're describing: https://github.com/uyuni-project/uyuni-rfc/blob/master/accepted/00090-sle-micro-reboot-needed.md

We could enhance it to also work on non-transactional systems, where it uses a different source to determine its state.

**Comment by heiwu** [comment]
Hi @agraul , thanks, that would be awesome!

**Comment by agraul** [comment]
The RFC process has already started and we have agreed on a way to implement this: https://github.com/uyuni-project/uyuni-rfc/pull/83

**Comment by admd** [comment]
@heiwu feature was already released. If this new feature meets your requirements, kindly mark this issue as closed.

**Comment by mcalmer** [comment]
It should be sufficient. closing

**Comment by heiwu** [comment]
Thanks, hope it will be included in SUSE Manager soon.

**Comment by rjmateus** [comment]
Hey @heiwu 
It's already released on SUSE Manager 4.3. You can check the release notes in here: https://www.suse.com/releasenotes/x86_64/SUSE-MANAGER/4.3/index.html#_reboot_required_indication_for_non_suse_distributions
