### ISSUE TITLE
Systems link for inactive systems shows all systems, not just inactive.

### ISSUE THREAD

**Issue by digdilem-work** [uyuni-project/uyuni#7067]
### Problem description

**Uyuni Webui -> Systems -> Inactive**

URL: https://hostname/rhn/manager/systems/list/all?qc=system_kind&q=awol

This returns a list of ALL registered machines. (206 here)

**Expected**: To show just the inactive machines (4 here)

The systems themselves appear to be identified and marked as inactive properly - the "Home" link https://hostname/rhn/YourRhn.do  has a section for "Inactive systems" which is properly filled, so I believe the main section is somehow missing a filter or similar.

Thank you

### Steps to reproduce

As above. 

### Uyuni version

```bash
2023.04


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by mbussolotto** [comment]
Thanks for reporting!
Can you please verify if [https://hostname/rhn/manager/systems/list/all?qc=status_type&q=awol](https://hostname/rhn/manager/systems/list/all?qc=status_type&q=awol) returns the correclt inactive list ??? Thanks :)

**Comment by HoussemNasri** [comment]
I just tried that and it always returns a blank page whether the client is up or down. I looked into 'susesystemoverview' table and the 'status_type' column and it was equal to 'up2date', which explains this behavior.

**Comment by mbussolotto** [comment]
IIUC  there's two issues here:
1. UI checks for system_type == awol, instead I think it should be status_type == awol
2. status_type is not correctly set

I'm able to easily reproduce the issue and it seems it was introduced recently (it works as expected in older version). @cbosdo I remember you mentioned there was some changes in system overview in the latest changes... do you know who can help with this ?? Thanks!

**Comment by RenownTwiz** [comment]
We're also seeing this bug, we first noticed it in:

Name        : Uyuni-Server-release
Version     : 2023.03
Release     : 220400.199.1.uyuni2
Architecture: x86_64

**Comment by cbosdo** [comment]
Just filed a PR fixing this. Thanks for the report and pinging me again!
