### ISSUE TITLE
Unable to upgrade packages for MicroOs installation

### ISSUE THREAD

**Issue by rdouman** [uyuni-project/uyuni#7068]
### Problem description

I am unable to upgrade my server after successfully registering it ("openSUSE MicroOS - 20230522) using salt with the Uyuni server.  I'm am presented with a list of packages to be upgraded, but the upgrade fails once the salt state executes.

### Steps to reproduce

1. Install new opensuse microos server
2. Install salt minion 3006.0-1.1
3. Configure Channel for X86 using repo tumbleweed oss (http://download.opensuse.org/tumbleweed/repo/oss/)
4. Subscribe to the relevant channel and wait for package etc so synch up and list of packages to be upgrade to be available under the software tab for the system.
5. Select packages under the package selection and click upgrade packages
6. Confirm upgrade and wait for salt state to execute.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
Not installed
```

### Additional information

Salt reports the following error when trying to apply the changes:

```bash
Problem: the installed product:MicroOS-20230522-0.x86_64 conflicts with 'distribution-release' provided by the to be installed product:openSUSE-20230524-0.x86_64 

 Problem: the to be installed product:openSUSE-20230524-0.x86_64 requires 'product(openSUSE) = 20230524-0', but this requirement cannot be provided 
 Problem: the installed product:MicroOS-20230522-0.x86_64 conflicts with 'distribution-release' provided by the to be installed product:openSUSE-20230524-0.x86_64

The target server appears to have two conflicting products, namely:
 zypper search --provides --type product
Loading repository data...
Reading installed packages...

S  | Name     | Summary             | Type
---+----------+---------------------+--------
i+ | MicroOS  | openSUSE MicroOS    | product
   | openSUSE | openSUSE Tumbleweed | product
```

I believe that the offending code might be in /usr/share/susemanager/salt/_states/product.py.  I believe that it's trying to install the conflicting product "openSUSE" causing the update to fail.

I've attached the full Salt error:
[saltstateupgrade.log](https://github.com/uyuni-project/uyuni/files/11573736/saltstateupgrade.log)

**Comment by rdouman** [comment]
[saltstateupgrade.log](https://github.com/uyuni-project/uyuni/files/11573759/saltstateupgrade.log)

**Comment by agraul** [comment]
The logs show that the error comes from `mgrchannels_install_products` which uses `product.all_installed`. That's a problem for MicroOS with Tumbleweed repos since both products ("MicroOS" and "Tumbleweed") are in the repos.

**Comment by juliogonzalez** [comment]
@mbussolotto with openSUSE MicroOS, yes.but I don't know why it's happening.

What @agraul is describing should always be the case, as the full Tumbleweed repo is available in MicroOS IIRC (don't have my VM at hand now).

**Comment by mbussolotto** [comment]
ok, I noticed the two products in the same repo, but I thought we should find a way to handle it (if there's a way)...instead IIUC we should ask to have one repo for each product (and then change `spacewalk-common-channels.ini` ), am I right?

**Comment by agraul** [comment]
> What @agraul is describing should always be the case, as the full Tumbleweed repo is available in MicroOS IIRC (don't have my VM at hand now).

True, but not everyone tries to install all products they find in the repos.

> ok, I noticed the two products in the same repo, but I thought we should find a way to handle it (if there's a way)...

We already have logic in the SLS to not install the products for Leap, we can adjust it to also skip MicroOS (channels/init.sls)
