### ISSUE TITLE
While Bootstrap the Client machine it's giving error like machine is already exits

### ISSUE THREAD

**Issue by rakeshsujan** [uyuni-project/uyuni#7107]
# Short description

_Short description about the requested feature._

# Details

_Please include as many details here as you can._
_In general: all that can help to understand what you suggest._

**Comment by rakeshsujan** [comment]
While doing the Bootstrap to add a Client machine it's giving an error stating that machine already exits. But when i check the System under the system tab the Client machine is not showing.

![image](https://github.com/uyuni-project/uyuni/assets/50227412/0e8a8e2e-2f86-4966-9d62-99659355d130)


Can u help me to resolve this issue?

**Comment by deneb-alpha** [comment]
closing in favor of https://github.com/uyuni-project/uyuni/issues/7104
