### ISSUE TITLE
Disabling Modules for Rocky V9 not Working

### ISSUE THREAD

**Issue by sysy69** [uyuni-project/uyuni#7133]
### Problem description

I  want to remove all Modules from the App stream repo with a Content Lifecycle and the Content Lifecycle Filter: disable all modules.

But after creating the Enviroment the Modules are still there.

Content Lifecycle:
<img width="752" alt="image" src="https://github.com/uyuni-project/uyuni/assets/107186616/0db387a0-59da-4e72-893a-8e67d0dfb937">
Created Enviroment:
<img width="761" alt="image" src="https://github.com/uyuni-project/uyuni/assets/107186616/cc68bdc3-f528-40ab-9a42-30acdc13f6a3">

### Steps to reproduce

1.sync Rcoky V9 Appstream Repo
2.Create Content Lifecycle with Filter disable all modules
3.Create Enviroment

### Uyuni version

```bash
Uyuni Release 2023.04
```

**Comment by agraul** [comment]
> I think i have to do this via the CLM. There is no such filter avaiable in the channel or repository tab.

Yes, the linked docs contain step-by-step instructions on how to do it with CLM.

**Comment by sysy69** [comment]
I understand now that the Filter removes the Module data. But why does it not remove the Packages from the channels which belong to a Module? Have i to Remove the associated Packages via another Filter?

The Problem is that i can't update php because the Packages from the Module are Present in the Channel. I have installed php 8.0 on the Machine but uyuni want's to Upgrade to version 8.1. I hoped that they would be removed by the "disable all modules" filter.

![Screenshot 2023-06-20 121111](https://github.com/uyuni-project/uyuni/assets/107186616/e3434a3d-748a-4062-b3af-a1234997a1f5)

**Comment by sysy69** [comment]
Rocky Linux v9 always includes a base version of various packages, such as PHP 8.0 as non-modular packages. Additional versions are added as modules, for example, PHP 8.1. How can i use PHP 8.0 and Manage it via uyuni? You see in the Screenshot above that uyuni wants to update to PHP 8.1. This issue is not limited to PHP alone. I want to remove all Modules inclunding Modular Packages from the repo.

**Comment by cbbayburt** [comment]
As an (ugly) workaround, you can add an arbitrary AppStream filter to filter out the other modules.
