### ISSUE TITLE
Custom repository not synced

### ISSUE THREAD

**Issue by ase7en34** [uyuni-project/uyuni#7156]
### Problem description

I have one Proxmox node and I'm trying to manage it with Uyuni. 
There is a non-subscription repository for Free version of Proxmox which I'm trying to add.
However when I'm tryiing to sync I got this output:

2023-06-17 16:08:44,122 urlgrabber version  = 4.1.0
2023-06-17 16:08:44,122 trans function "_"  = <function _ at 0x7f2020785598>
16:08:44 ======================================
16:08:44 | Channel: pve-non-subscription
16:08:44 ======================================
16:08:44 Sync of channel started.
16:08:44 Repo URL: http://download.proxmox.com/debian/pve/dists/bullseye/pve-no-subscription/binary-amd64/
16:08:44     Packages in repo:              1991
16:08:44     No new packages to sync.
16:08:44
16:08:44   Patches in repo: 0.
16:08:44 Sync completed.
16:08:44 Total time: 0:00:00

It refuses to download all 1991 packages found in the repo.

### Steps to reproduce

1. Create repo as image bleow
...
![image](https://github.com/uyuni-project/uyuni/assets/65528374/5264bcab-64cd-4112-a910-c0da467aabd7)

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by mcalmer** [comment]
Please check the architecture of the "Channel".
What did you set there?

**Comment by ase7en34** [comment]
> Please check the architecture of the "Channel". What did you set there?

Hello and thank you for your response. I used x86_64 as architecture.

![image](https://github.com/uyuni-project/uyuni/assets/65528374/d4cc4815-3e59-4915-9d9e-896627cb4b3d)

**Comment by mcalmer** [comment]
This is wrong. Debian use different names for the architectures. Look for 

  AMD64 Debian

That should do what you want.
spacewalk-repo-sync sync only packages from the selected architecture. With x86_64 it does not find any package to sync. That explains the output.

**Comment by ase7en34** [comment]
I'm afraid that I cannot change this since this field is grey and it is auto filled by web interface.
Do you know another method for setting this parameter ?

Many thanks in advance.

**Comment by mcalmer** [comment]
Delete the channel and create it again. That's the way to go.
Even if packages would be synced already, you do not need to delete packages. They will stay on the system and if a new channel would need them, the existing info would just be linked and not downloaded and re-imported again.

**Comment by ase7en34** [comment]
I did it and now another error occur :

![image](https://github.com/uyuni-project/uyuni/assets/65528374/27108ad9-fd46-4bdd-b697-c3bf0f87be04)

GPG section looks like that:

![image](https://github.com/uyuni-project/uyuni/assets/65528374/6c153910-1ce5-4e0b-86e8-926455aa22cd)

Here is the fingerprint details of gpg key provided from https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg

gpg> fpr
pub   rsa4096/DD4BA3917E23BF59 2020-11-09 Proxmox Bullseye Release Key <proxmox-release@proxmox.com>
 Primary key fingerprint: 2813 9A2F 830B D684 78A1  A01F DD4B A391 7E23 BF59

gpg>

Thank you in advance.

**Comment by ase7en34** [comment]
I have removed tick form Has Signed Metadata option and now it is working fine:

![image](https://github.com/uyuni-project/uyuni/assets/65528374/82a847a4-b940-439a-819b-516ae876431c)

Thank you for the support.
