### ISSUE TITLE
Ubuntu reboot required status not set on Uyuni 2023.04

### ISSUE THREAD

**Issue by tbryant-vygr** [uyuni-project/uyuni#7203]
### Problem description

On Ubuntu 20.04 minions connected to Uyuni 2023.04 after pushing an upgrade or patch task from Uyuni or any action performed directly on the minion that causes the server to require a reboot. Uyuni does not detect this and the servers status is never set to reboot required.

Ubuntu creates the file _/var/run/reboot-required_ when a system needs to be restarted.
```
sudo cat /var/run/reboot-required
*** System restart required ***
```

Reboot required status of Ubuntu Servers should be updated based on the existence of /var/run/reboot-required

### Steps to reproduce

1. Install a package to Ubuntu that requires a system reboot
2. Confirm existence of /var/run/reboot-required
3. Apply highstates, run package sync and hardware refresh tasks
4. Note that the reboot required flagt in Uyuni is never shown

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Additional information

# Related Issues
https://github.com/uyuni-project/uyuni/issues/5084
https://github.com/uyuni-project/uyuni/issues/6003

**Comment by tbryant-vygr** [comment]
Seems to be relevant for other OS's too https://github.com/uyuni-project/uyuni/issues/7053

**Comment by mcalmer** [comment]
Should be implemented now for ubuntu as well
