### ISSUE TITLE
Some of the packages are not listing in the Uyuni

### ISSUE THREAD

**Issue by rakeshsujan** [uyuni-project/uyuni#7212]
# Short description

_Short description about the requested feature._

# Details

_Please include as many details here as you can._
_In general: all that can help to understand what you suggest._

**Comment by rakeshsujan** [comment]
I am using Rocky Linux 9.2 version when i tried to install the *telnet* package it's gives an error stating that no package is available in the Uyuni.

Find the below output for your reference. 

[root@server yum.repos.d]# yum clean all
13 files removed
[root@server yum.repos.d]# yum repolist
repo id                                                                                                               repo name
susemanager:rockylinux9-uyuni-client-x86_64                                                                           Uyuni Client Tools for Rocky Linux 9 (x86_64)
susemanager:rockylinux9-x86_64                                                                                        Rocky Linux 9 (x86_64)
[root@server yum.repos.d]# yum install telnet
Rocky Linux 9 (x86_64)                                                                                                                                                                                       3.3 MB/s | 2.2 MB     00:00
Uyuni Client Tools for Rocky Linux 9 (x86_64)                                                                                                                                                                159 kB/s |  73 kB     00:00
Last metadata expiration check: 0:00:01 ago on Wed Jun 28 01:59:17 2023.
No match for argument: telnet
Error: Unable to find a match: telnet
[root@server yum.repos.d]# yum search telnet
Last metadata expiration check: 0:00:09 ago on Wed Jun 28 01:59:17 2023.
No matches found.
[root@server yum.repos.d]# yum list telnet
Last metadata expiration check: 0:00:21 ago on Wed Jun 28 01:59:17 2023.
Error: No matching Packages to list
[root@server yum.repos.d]#

**Comment by tjmullicani** [comment]
Did you add and synchronize the Rocky Linux AppStream channel (rockylinux9-appstream) per the [documentation](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-rocky.html)?
