### ISSUE TITLE
FIPS installation issue

### ISSUE THREAD

**Issue by tjmullicani** [uyuni-project/uyuni#7253]
### Problem description

When attempting to install Uyuni with FIPS enabled, I ran into an issue where the **taskomatic** service was failing to start. The following generic error was logged to **/var/log/rhn/rhn_taskomatic_daemon.log**
![1](https://github.com/uyuni-project/uyuni/assets/18095326/d6ea7d53-59ad-4fa4-9820-49652a2219ef)
After checking journalctl, it seemed there was an issue with the Java security provider trying to load data from the non-existent directory **/etc/pki/nssdb**.
![2](https://github.com/uyuni-project/uyuni/assets/18095326/e9efb6c4-3490-4796-8696-ae8ac7b0dc70)
I was able to fix the issue by installing the **mozilla-nss-sysinit** package, which creates and initializes the /etc/pki/nssdb directory, and rebooting. After this the taskomatic service was able to successfully start.

### Steps to reproduce

1. Install openSUSE Leap 15.4 with /boot on a separate partition.
2. Enable FIPS by following https://doc.opensuse.org/documentation/leap/archive/15.3/security/html/book-security/cha-security-fips.html. Verify **/proc/sys/crypto/fips_enabled** returns a value of 1.
3. Reboot
4. Install Uyuni by following https://www.uyuni-project.org/pages/stable-version.html
5. The spacewalk installer will fail on starting spacewalk.target, due to the taskomatic.service dependency failing to start.

### Uyuni version

```bash
Repository: uyuni-server-stable
Name: Uyuni-Server-release
Version: 2023.04-220400.204.2.uyuni2
Arch: x86_64
Vendor: obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level: Level 3
Installed Size: 1.4 KiB
Installed: Yes (automatically)
Status: up-to-date
Source package: Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary: Uyuni Server
```

**Comment by tjmullicani** [comment]
It looks like there may be issues with Tomcat as well. I'm still testing to make sure everything is running correctly.

**Comment by tjmullicani** [comment]
> It looks like there may be issues with Tomcat as well (causing 404 error). I'm still testing to make sure everything is running correctly.

**/var/log/rhn/rhn_web_ui.log** contained the following error
![image](https://github.com/uyuni-project/uyuni/assets/18095326/54babb92-3299-45df-aeb3-972ecb6ecfab)
I was able to solve by modifying **/usr/lib64/jvm/java-11-openjdk-11/conf/security/java.security** to set **security.useSystemPropertiesFile=false** ([reference](https://access.redhat.com/solutions/6653921)).
![image](https://github.com/uyuni-project/uyuni/assets/18095326/eba3adee-1e19-4c5a-b6e4-ecf471ea7b66)

**Comment by avshiliaev** [comment]
Hi @tjmullicani 
Thank you for your report. I'm afraid we don't officially support running uyuni on the FIPS-enabled Leap. It's up to the administrator to fill in the gaps. However, we could definitely improve our documentation on the subject.
