### ISSUE TITLE
Stuck task: system-overview-update-queue

### ISSUE THREAD

**Issue by hbrown-uiowa** [uyuni-project/uyuni#7313]
# Question

How do I terminate a stuck job in taskomatic? We currently have system-overview-update-queue that seems to run forever and never complete. Additionally, the mgr-repo-sync task is failing and none of our repositories have been syncing.

It started after we accidentally patched the salt stack to 3006. We have since downgraded, but the system-overview-update-queue job doesnt seem to be working since those packages were updated.

## Version of Uyuni Server and Proxy (if used)
```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : out-of-date (version 2023.03-220400.199.1.uyuni2 installed)
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

```

**Comment by hbrown-uiowa** [comment]
We also have the taskomatic queue claiming that it has too many workers already going

```
2023-07-25 13:33:03,521 [DefaultQuartzScheduler_Worker-15] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 689
2023-07-25 13:33:51,868 [DefaultQuartzScheduler_Worker-1] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.

```

**Comment by hbrown-uiowa** [comment]
This also seems concerning:
```
 select count(*) from rhntaskqueue ;
  count  
---------
 1814100
```

**Comment by rjmateus** [comment]
Hey @hbrown-uiowa ,
Can you see if there are any errors on the logs from "/var/log/rhn/*" and also in the database log "/var/lib/pgsql/data/log/"

You can also try to run the tool "taskotop" on the server and see if any values are strange.

**Comment by hbrown-uiowa** [comment]
Each time I restart, the RUN ID changes, but one system-overview-update-queue task sits in a running state and just keeps running.

Here's taskotop snapshot right now:
```
     RUN ID                      TASK NAME   ELAPSED         END                                                                                   CHANNEL                                                                          
6756102       system-overview-update-queue     2829s           (running)                                                                                                                                                            
6756466                      errata-mailer        0s 2023-07-28 12:37:00                                                                                                                                                            
6756462                       errata-cache        0s 2023-07-28 12:37:00                                                                                                                                                            
6756463                           ssh-push        0s 2023-07-28 12:37:00                                                                                                                                                            
6756464                       cobbler-sync        0s 2023-07-28 12:37:00                                                                                                                                                            
6756465       system-overview-update-queue        0s 2023-07-28 12:37:00                                                                                                                                                            
6756461                   channel-repodata        0s 2023-07-28 12:37:00                                                                                                                                                            
6756460                       errata-queue        0s 2023-07-28 12:37:00       
```


The only thing I see in the logs in /var/log/rhn/* is that there are 697 items in the queue and `[DefaultQuartzScheduler_Worker-18] DEBUG com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Run with id 6756102 handles the whole task queue`

In the postgres logs for today, I see things like:
```
2023-07-28 11:49:13.229 CDT uyuni uyuni [75283]LOG:  could not receive data from client: Connection reset by peer
2023-07-28 11:57:05.658 CDT uyuni uyuni [9900]LOG:  unexpected EOF on client connection with an open transaction
2023-07-28 12:01:17.266 CDT   [93686]LOG:  using stale statistics instead of current ones because stats collector is not responding
2023-07-28 12:37:32.446 CDT uyuni uyuni [128962]LOG:  unexpected EOF on client connection with an open transaction
```

The connection reset by peer is by far the most common

**Comment by kluchoslaw** [comment]
I have exactly the same situation after zypper up. Will be enough to clean via "delete from rhntaskqueue ;" ?

**Comment by ddholstad99** [comment]
It looks to me like the issue might be related to not having enough resources to run the requests. It looks like there is a SystemsOverviewUpdateDriver that runs against the table and calls the sql stored procedure for each system. 

It seems like we should set taskomatic.systems_overview_update_workers to a higher number?
is this set in /etc/rhn/rhn.conf?
I assume maxThreads in tomcat needs to be bumped as well? (https://www.uyuni-project.org/uyuni-docs/en/uyuni/specialized-guides/large-deployments/tuning.html#max-threads)
https://github.com/uyuni-project/uyuni/blob/711a33f4fd0b98635aae61a6f9445c71fd9ebaa3/java/code/src/com/redhat/rhn/taskomatic/task/systems/SystemsOverviewUpdateDriver.java#L34


We dont see contention in postgres, so I assume the bottleneck is oin the tomcat workers...

**Comment by ddholstad99** [comment]
It looks to me like the task_data is supposed to match up with the server id, but we have an org(5) with no systems in it that is showing a large number of system update jobs. We have channels that are loaded as org #1, then shared out to the other orgs (2,3,5). Is it possible that whatever is triggering these is putting in a request to refresh each system in more than one org? 

uyuni=# select count(*),org_id from rhntaskqueue group by org_id;
  count  | org_id 
---------+--------
  843226 |      2
 1142782 |      5
(2 rows)

**Comment by ddholstad99** [comment]
It looks like when a channel sync hits, the systems are inserted as org1, and those process through, but the org2/5 requests are not getting processed (or are not getting removed).

uyuni=# select count(*),org_id from rhntaskqueue group by org_id;
  count  | org_id 
---------+--------
       6 |      1
  843319 |      2
 1143144 |      5
(3 rows)

uyuni=# select count(*),org_id from rhntaskqueue group by org_id;
  count  | org_id 
---------+--------
  843319 |      2
 1143144 |      5
(2 rows)

**Comment by ddholstad99** [comment]
It looks like SystemsOverviewUpdateWorker removes the task by specifying the system id, and supplying the org lookup which I assume just returns 1? 
https://github.com/uyuni-project/uyuni/blob/711a33f4fd0b98635aae61a6f9445c71fd9ebaa3/java/code/src/com/redhat/rhn/taskomatic/task/systems/SystemsOverviewUpdateWorker.java


https://github.com/uyuni-project/uyuni/blob/711a33f4fd0b98635aae61a6f9445c71fd9ebaa3/java/code/src/com/redhat/rhn/domain/task/TaskFactory.java#L118

**Comment by cbosdo** [comment]
Thanks a lot for the investigations. You have nailed it to the proper issue. Could you create a new `TaskFactory.deleteByNameData(String name, Long data)` function to ignore the org and priority and use it instead in the worker's remove function? That would be fantastic if you could file a Pull Request with the change!

**Comment by DENISKI** [comment]
Any updates here?
It looks very bad.
```
2023-09-08 18:01:00,124 [DefaultQuartzScheduler_Worker-5] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 2496
2023-09-08 18:02:00,105 [DefaultQuartzScheduler_Worker-11] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:03:00,114 [DefaultQuartzScheduler_Worker-50] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:04:00,070 [DefaultQuartzScheduler_Worker-25] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:05:00,103 [DefaultQuartzScheduler_Worker-52] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:06:00,066 [DefaultQuartzScheduler_Worker-72] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:07:00,073 [DefaultQuartzScheduler_Worker-100] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
```

**Comment by hbrown-uiowa** [comment]
Unfortunately, we (ddholstad99 or myself) don't have the java expertise to submit a PR for the fix. 

Is there anyone else that has java experience that can make this fix?

**Comment by DENISKI** [comment]
So maybe better to address it to the project maintainer? Who is developing Uyuni? :)
We didn't see any releases for more then 6 months.

**Comment by ddholstad99** [comment]
Denys,

I would like to clarify, are you using uyuni with multiple organizations?

Thanks,
Dan
________________________________________
From: Denys Kyrii ***@***.***
Sent: Friday, September 8, 2023 1:23 PM
To: uyuni-project/uyuni
Cc: Holstad, Dan D; Comment
Subject: [External] Re: [uyuni-project/uyuni] Stuck task: system-overview-update-queue (Issue #7313)

Any updates here?
It looks very bad.

2023-09-08 18:01:00,124 [DefaultQuartzScheduler_Worker-5] INFO  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - In the queue: 2496
2023-09-08 18:02:00,105 [DefaultQuartzScheduler_Worker-11] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:03:00,114 [DefaultQuartzScheduler_Worker-50] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:04:00,070 [DefaultQuartzScheduler_Worker-25] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:05:00,103 [DefaultQuartzScheduler_Worker-52] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:06:00,066 [DefaultQuartzScheduler_Worker-72] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.
2023-09-08 18:07:00,073 [DefaultQuartzScheduler_Worker-100] WARN  com.redhat.rhn.taskomatic.task.SystemOverviewUpdateQueue - Maximum number of workers already put ... skipping.

**Comment by DENISKI** [comment]
No. I have just 1 organization.

**Comment by ddholstad99** [comment]
The issue we were seeing is when there are multiple organizations. If you are are seeing this issue with one organization you should review the tuning guide: https://www.uyuni-project.org/uyuni-docs/en/uyuni/specialized-guides/large-deployments/tuning.html.

The graphic with all the arrows is the key to understanding what you need to tweak. 

Are you syncing a large number of channels/operating systems?  It seemed that the long running job started running for us when I increased the taskomatic memory and workers. 
If you need to change the number of workers for the systems_overview_update, the entry is not in the guide yet, but seems to be java.taskomatic.systems_overview_update_workers = N, where N is your desired worker count (default is 2). Keep in mind in order to change that you would also need to change java.message_queue_thread_pool_size (https://www.uyuni-project.org/uyuni-docs/en/uyuni/specialized-guides/large-deployments/tuning.html#java-salt-event-thread-pool-size) and make the changes recommended in the "After changing" section. 


Thanks,
Dan
________________________________________
From: Denys Kyrii ***@***.***
Sent: Friday, September 8, 2023 2:35 PM
To: uyuni-project/uyuni
Cc: Holstad, Dan D; Comment
Subject: [External] Re: [uyuni-project/uyuni] Stuck task: system-overview-update-queue (Issue #7313)

No. I have just 1 organization.

**Comment by DENISKI** [comment]
I already posted it to the community. The is is related to the long DB transactions.
The next one executing for more then 30 minutes. I did vacuum and even db_repack to make sure all indexes are up to date.
`select roleimpl0\_.id as id1\_238\_, roleimpl0\_.name as name2\_238\_, roleimpl0\_.label as label3\_238\_, roleimpl0\_.created as created4\_238\_, roleimpl0\_.modified as modified5\_238\_ from RHNUSERGROUPTYPE roleimpl0\_ where roleimpl0\_.label=$1`
So I believe app tuning won't be helpful here.

**Comment by DENISKI** [comment]
Just imaging it's UTC time.
Current time is: Fri Sep  8 21:08:27 UTC 2023
![image](https://github.com/uyuni-project/uyuni/assets/13982002/4e272263-468a-4fe7-927e-9013ac7fe690)

**Comment by cbosdo** [comment]
> Unfortunately, we (ddholstad99 or myself) don't have the java expertise to submit a PR for the fix.
> 
> Is there anyone else that has java experience that can make this fix?

OK, then I'll fix it
