### ISSUE TITLE
Openscap not report not generating through uyuni

### ISSUE THREAD

**Issue by rakeshsujan** [uyuni-project/uyuni#7428]
# Short description

_Short description about the requested feature._

# Details

_Please include as many details here as you can._
_In general: all that can help to understand what you suggest._

**Comment by rakeshsujan** [comment]
Hello All,

I have installed the required packages in the client machine even though when in go to the system Audit-->Schedule it's saying that Openscap package is not installed in the client machine.

Kindly help me out on this issues. 

![image](https://github.com/uyuni-project/uyuni/assets/50227412/169ce467-a5c6-41d0-b2a8-f913dd5d7369)

**Comment by admd** [comment]
@rakeshsujan  which package have you installed exactly? and what client do you have?

**Comment by rakeshsujan** [comment]
@admd , I have install the **openscap-utils & scap-security-guide-redhat** package in the client machine.

The Client machine version is Rocky Linux 9.2
