### ISSUE TITLE
Fail in Bootstrapscript for Handle Certificate

### ISSUE THREAD

**Issue by killproc84** [uyuni-project/uyuni#7465]
### Problem description

In following lines from initial bootstrapscript.sh is used variable "$ORG_CERT_FILE" but never be set and have to be "$CERT_FILE"

```
321     if [ -n "$SNAPSHOT_ID" ]; then
322         # we need to copy certificate to the trustroot outside of transaction for zypper
323         cp "$ORG_CA_CERT" /etc/pki/trust/anchors/
324         call_tukit "test -d '$CERT_DIR' || mkdir -p '$CERT_DIR'"
325         call_tukit "cp '/etc/pki/trust/anchors/$ORG_CA_CERT' '${CERT_DIR}/${ORG_CERT_FILE}'"
326     else
327         test -d "$CERT_DIR" || mkdir -p "$CERT_DIR"
328         mv "$ORG_CA_CERT" "${CERT_DIR}/${ORG_CERT_FILE}"
329     fi  
```

### Steps to reproduce

1. Create an Initial bootstrap.sh under /rhn/admin/config/BootstrapConfig.do
2. Fill the variables with activationkey
3. Try to Bootstrap as root f.e. Ubuntu System with  
`curl -Sks https://uyunisystem/pub/bootstrap/bootstrap.sh | /bin/bash`

apt will fail;
  `Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP:  x.x.x.x 443]`

After fix variable from ${ORG_CERT_FILE} to ${CERT_FILE} Registration from Client-side working fine.

### Uyuni version

```bash
2023.04
```

**Comment by avshiliaev** [comment]
Hey @killproc84,
thanks for your report. It looks like this is indeed a valid problem. The ORG_ prefix should not be there. We should take care of it.

**Comment by mcalmer** [comment]
This one is already fixed.
