### ISSUE TITLE
syncronizing disconnected ubuntu repositories fails with "Package index checksum failure"

### ISSUE THREAD

**Issue by frossmant** [uyuni-project/uyuni#7521]
### Problem description

When using varius tools for syncronizing ubuntu repositories it seems to break the syncronization process for uyuni.

The checksum files is okey but Uyuni still breaks and when syncronizing outputs

sth-bg-upd002:/var/log/rhn # spacewalk-repo-sync -l|grep test123
12:10:08 test123 | http://10.0.0.32/linux/ubuntu/mirror/napoleon.ftp.acc.umu.se/ubuntu/dists/jammy/main/binary-amd64/

/var/log/rhn # spacewalk-repo-sync -p test123 -v
12:06:34 ======================================
12:06:34 | Channel: test123
12:06:34 ======================================
12:06:34 Sync of channel started.
12:06:34 Plugin error: Package index checksum failure
12:06:34 Total time: 0:00:00

I've used apt-mirror in order to syncronize the ubuntu repositories

### Steps to reproduce

1. configure the apt-mirror list file for ubuntu repository

```
# cat /etc/apt/mirror.list

set base_path         /shared/sth-bg-nas002/update/linux/ubuntu
set mirror_path       $base_path/mirror
set skel_path         $base_path/skel
set var_path          $base_path/var
set cleanscript       $var_path/clean.sh
set postmirror_script $var_path/postmirror.sh
set defaultarch	      amd64
set run_postmirror    0
set nthreads          20
set limit_rate        100m
set _tilde            0
set unlink            1
set use_proxy         off

deb https://napoleon.ftp.acc.umu.se/ubuntu jammy main restricted
deb https://napoleon.ftp.acc.umu.se/ubuntu jammy-updates main restricted

deb https://napoleon.ftp.acc.umu.se/ubuntu jammy universe
deb https://napoleon.ftp.acc.umu.se/ubuntu jammy-updates universe

deb https://napoleon.ftp.acc.umu.se/ubuntu jammy multiverse
deb https://napoleon.ftp.acc.umu.se/ubuntu jammy-updates multiverse

deb https://napoleon.ftp.acc.umu.se/ubuntu jammy-backports main restricted universe multiverse

deb https://napoleon.ftp.acc.umu.se/ubuntu jammy-security main restricted
deb https://napoleon.ftp.acc.umu.se/ubuntu jammy-security universe
deb https://napoleon.ftp.acc.umu.se/ubuntu jammy-security multiverse
```

2. run apt-mirror so syncronize the repository
`# apt-mirror`

3. do some initial verifying of integrity for repo files.

`# cd /shared/sth-bg-nas002/update/linux/ubuntu/mirror/napoleon.ftp.acc.umu.se/ubuntu/dists/jammy/main/binary-amd64`

```
# find .
.
./by-hash
./by-hash/SHA256
./by-hash/SHA256/37cb57f1554cbfa71c5a29ee9ffee18a9a8c1782bb0568e0874b7ff4ce8f9c11
./by-hash/SHA256/712ee19b50fa5a5963b82b8dd00438f59ef1f088db8e3e042f4306d2b7c89c69
./by-hash/SHA256/d0eb69cd34be34406d2e2aa4d0751005b17808e30c5d32acd5890c5b8cba7517
./by-hash/MD5Sum
./by-hash/MD5Sum/f27cee24646e541717959598ca71230b
./by-hash/MD5Sum/538cd329c0295cc02754faf265e47e35
./by-hash/MD5Sum/d41b45afb922d3bd828d168ef2c1e380
./by-hash/SHA1
./by-hash/SHA1/370c66437d49460dbc16be011209c4de9977212d
./by-hash/SHA1/b5230c4d59d77d91fdcefe76135df12737a1bc2f
./by-hash/SHA1/beef05fb432a5851c438fa535afeb22f63bb89c0
./Packages.xz
./Packages.gz
./Release 
```

```
for __FILE in $(find . -maxdepth 1 -type f)
do
    echo ${__FILE}
    find by-hash/|grep -w $(sha256sum ${__FILE}|awk '{ print $1 }') >/dev/null 2>&1 && echo "  OK SHA256" || echo "  FAIL SHA256" 
    find by-hash/|grep -w $(sha1sum ${__FILE}|awk '{ print $1 }') >/dev/null 2>&1 && echo "  OK SHA1" || echo "  FAIL SHA1" 
    find by-hash/|grep -w $(md5sum ${__FILE}|awk '{ print $1 }') >/dev/null 2>&1 && echo "  OK MD5" || echo "  FAIL MD5" 
done

./Packages.xz
  OK SHA256
  OK SHA1
  OK MD5
./Packages.gz
  OK SHA256
  OK SHA1
  OK MD5
./Release
  OK SHA256
  OK SHA1
  OK MD5
```

4. Integrity of package index files looks OK so let's try to sync

```
# spacewalk-repo-sync -l |grep test123
12:34:12 test123 | http://10.0.0.32/linux/ubuntu/mirror/napoleon.ftp.acc.umu.se/ubuntu/dists/jammy/main/binary-amd64/

# spacewalk-repo-sync -c test123
12:35:02 ======================================
12:35:02 | Channel: test123
12:35:02 ======================================
12:35:02 Sync of channel started.
12:35:02 Plugin error: Package index checksum failure
12:35:03 Total time: 0:00:00
```

### Uyuni version

```bash
Repository     : uyuni-server-pool
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
```

### Uyuni proxy version (if used)

Not using any proxy server

### Useful logs

Not that i can find of, the output of the spacewalk reposync command is pretty sparse.

### Additional information

The syncronization of the repo works as it should when using the original repository but when trying to sync via the offline one it does not work. I bet apt-mirror are doing something with the repo that uyuni does not like but i cannot find out what.

Also other offline ubuntu installations can use the same offline repo without any issues, it's just uyuni that complains.

**Comment by frossmant** [comment]
@avshiliaev thanks for the reply, ah okey i've tried to search after another issue related to this, do you know any existing issue that takes care of this problem ? also is there any more information about what the actually problem is ? possible a workaround.

Regards

**Comment by avshiliaev** [comment]
Sure, it's this small change here https://github.com/uyuni-project/uyuni/pull/7467
Would you be able to apply the changes and rebuild the code?

**Comment by avshiliaev** [comment]
Closing the issue. Feel free to reopen if needed
