### ISSUE TITLE
Increase value of maximum_object_size on Uyuni proxy Squid configuration

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#7554]
### Problem description

The value of parameter maximum_object_size is currently 200MB in Squid configuration for the Uyuni proxies.

I would suggest to increase this value to 300MB or even 400MB, knowing that for example the linux-firmware packages for Ubuntu 22.04 (243MB) and for the RH OS family (Oracle Linux, Rocky, Alma) is almost 300MB (289MB for Oracle Linux 9).

### Steps to reproduce

1. Update an Ubuntu 22.04 server
2. Check the Squid access_log and see that the linux-firmware package is in TCP_MISS

### Uyuni version

```bash
2023.03
```

### Uyuni proxy version (if used)

```bash
2023.03
```

**Comment by avshiliaev** [comment]
Hey @phibid! Thanks for your proposal. 
@cbosdo what do you think? :smile:

**Comment by cbosdo** [comment]
Here is the config in the source tree: https://github.com/uyuni-project/uyuni/blob/ef1ee55b1a6d3f7bff2a5d9977a23e1cb892d7ea/proxy/installer/squid.conf . Do I read it right that this value is already set to `10GB`? This configuration file is duplicated in https://github.com/uyuni-project/uyuni/blob/ef1ee55b1a6d3f7bff2a5d9977a23e1cb892d7ea/proxy/installer/squid.conf for the squid container image.

**Comment by avshiliaev** [comment]
@cbosdo thanks! You're right, that's already high enough I think.
