### ISSUE TITLE
Product migration by using "Product migration" from SLES15 SP4 to SLES 15 SP5 not possible

### ISSUE THREAD

**Issue by Ripper66Six** [uyuni-project/uyuni#7560]
# Question
Hello there,

when we try to migrate SLES 15 SP4 to SP5 we get the message, thats not possible.
We have followed documentation and done all steps for the migration, but we don´t get the function for the migration.

The message we earn:
**There is currently no migration available for this system. Either the latest Service Pack is already installed or possible target products are not available. Please use the [Setup Wizard] to identify and add missing products.**

After all we have checked the provided channels and packages.

For SLES 15 SP3 to SP4 there was the function ready without any problems after the installation of the first SLES 15 SP4 Server.

_What do you want to know about Uyuni?_
In which way we can get the possibility for the migration?

## Version of Uyuni Server and Proxy (if used)

UYUNI Server:
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

UYUNI Proxy:
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.4 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Proxy-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Proxy
Description    :
    Uyuni Proxies extend large and/or geographically
    dispersed Uyuni environments to reduce load on the Uyuni
    Server, lower bandwidth needs, and provide faster local
    updates.

With kind regards

**Comment by Ripper66Six** [comment]
Update:
We found out that in the Basechannel of SLES15 SP3 and SLES15 SP4 are provided the following channels:

SLE-Product-HA15-SP(3/4)-Pool for x86_64
SLE-Product-HA15-SP(3/4)-Updates for x86_64

In this case we also saw that these channels are not provided in SLES15 SP5.
After the deactivation of these channels migration was possible and running without problems.

We don´t find out in witch product channel of SLES15 SP5 this channels are provided.
Also we was not able to implement the channel manually.

Is there a bug?


Kind regards

**Comment by mcalmer** [comment]
SLE-Product-HA is an extension product to SLES. You have to extra pay for it. 
If you have bought a subscription for this extension, than you just need to mirror the HA product also for SLES15 SP5.
You can do it on the Product page when you expand the SLES15 SP5 product. You should see HA there as well.

If you do not have a subscription, you should remove it and all packages which comes from this channels, otherwise you are not compliant :-)

**Comment by Ripper66Six** [comment]
Good morning,

thank you :)
We close the question now.


Kind regards
