### ISSUE TITLE
spacewalk-common-channel for rhel7 and rhel8 does not exists?!

### ISSUE THREAD

**Issue by tani-DN** [uyuni-project/uyuni#7564]
# Question
Hi, 

for registering rhel8 client I have first to add the rhel8-pool-x86_64 and the res8-manager-tools-pool-x86_64, see
https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-rh-cdn.html

But this channels are not available. 
If I list all spacewalk common channels there is no one named "rhel". 

Is the documention correct?

Regards,
Artan

Uyuni Release 2023.04

**Comment by sbluhm** [comment]
I got this one:

# /usr/bin/spacewalk-common-channels -l | grep rhel
 rhel7-pool-uyuni:    x86_64, aarch64
 rhel7-uyuni-client:  i386, x86_64, aarch64
 rhel7-uyuni-client-devel: i386, x86_64, aarch64
 rhel8-pool-uyuni:    x86_64, aarch64
 rhel8-uyuni-client:  i386, x86_64, aarch64
 rhel8-uyuni-client-devel: i386, x86_64, aarch64
 rhel9-pool-uyuni:    x86_64, aarch64, ppc64le, s390x
 rhel9-uyuni-client:  i386, x86_64, aarch64, ppc64le, s390x
 rhel9-uyuni-client-devel: i386, x86_64, aarch64, ppc64le, s390x

**Comment by tani-DN** [comment]
Updatet to Version 2023.09. Now rhel channels are available. Thank you.
