### ISSUE TITLE
Salt client "steals" UUID of existing salt client

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#7568]
### Problem description

During "Hardware List Refresh" while onboarding new salt client takes the UUID of an existing client
As part of our onboarding process we generate a new machine-id via the bootstrap script, so this is not a "duplicate" VM ID issue.

### Steps to reproduce

1. Register 1st client
2. Register a 2nd client
3. Note that 2nd client has taken UUID of 1st client
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
If applicable I will gather logs as requested.....
```

### Additional information

```
####### Initial registration of client osa-rocky8-build.lab.tierpoint.com #########
Name:          osa-rocky8-build.lab.tierpoint.com
System ID:     1000010452
UUID:          a9881b42a0ef5cdbea942554a9a30b8b
Locked:        False
Registered:    20230920T14:10:48
Last Checkin:  20230920T14:12:35
OSA Status:    unknown
Last Boot:     20230919T14:58:02
Contact Method:default

Hostname:      osa-rocky8-build.lab.tierpoint.com
IP Address:    10.166.145.111
Kernel:        4.18.0-477.21.1.el8_8.x86_64

Activation Keys
---------------
1-rockylinux8-tp-default-x86_64

Software Channels
-----------------
rl8-x86_64-default-rockylinux8-x86_64
  |-- rl8-x86_64-default-rockylinux8-appstream-x86_64
  |-- rl8-x86_64-default-rockylinux8-tierpoint-custom-x86_64
  |-- rl8-x86_64-default-rockylinux8-el8-uyuni-client-tools-x86_64
  |-- rl8-x86_64-default-rockylinux8-epel-x86_64

Entitlements
------------
salt_entitled

System Groups
-------------

####### After registration of client osa-rl8-lab01.lab.tierpoint.com #########
####### Note osa-rl8-lab01.lab.tierpoint.com now has the UUID of osa-rocky8-build.lab.tierpoint.com
Name:          osa-rl8-lab01.lab.tierpoint.com
System ID:     1000010453
UUID:          a9881b42a0ef5cdbea942554a9a30b8b
Locked:        False
Registered:    20230920T14:57:37
Last Checkin:  20230920T15:24:36
OSA Status:    unknown
Last Boot:     20230910T05:20:26
Contact Method:default

Hostname:      osa-rl8-lab01.lab.tierpoint.com
IP Address:    10.166.145.109
Kernel:        4.18.0-477.21.1.el8_8.x86_64

Activation Keys
---------------
1-rockylinux8-tp-default-x86_64

Software Channels
-----------------
rl8-x86_64-default-rockylinux8-x86_64
  |-- rl8-x86_64-default-rockylinux8-appstream-x86_64
  |-- rl8-x86_64-default-rockylinux8-tierpoint-custom-x86_64
  |-- rl8-x86_64-default-rockylinux8-el8-uyuni-client-tools-x86_64
  |-- rl8-x86_64-default-rockylinux8-epel-x86_64

Entitlements
------------
salt_entitled

System Groups
-------------


####### osa-rocky8-build.lab.tierpoint.com after registration of client osa-rl8-lab01.lab.tierpoint.com #########
####### Note missing UUID after osa-rl8-lab01.lab.tierpoint.com registered
Name:          osa-rocky8-build.lab.tierpoint.com
System ID:     1000010452
Locked:        False
Registered:    20230920T14:10:48
Last Checkin:  20230920T14:12:35
OSA Status:    unknown
Last Boot:     20230919T14:58:02
Contact Method:default

Hostname:      osa-rocky8-build.lab.tierpoint.com
IP Address:    10.166.145.111
Kernel:        4.18.0-477.21.1.el8_8.x86_64

Activation Keys
---------------
1-rockylinux8-tp-default-x86_64

Software Channels
-----------------
rl8-x86_64-default-rockylinux8-x86_64
  |-- rl8-x86_64-default-rockylinux8-appstream-x86_64
  |-- rl8-x86_64-default-rockylinux8-tierpoint-custom-x86_64
  |-- rl8-x86_64-default-rockylinux8-el8-uyuni-client-tools-x86_64
  |-- rl8-x86_64-default-rockylinux8-epel-x86_64

Entitlements
------------
salt_entitled

System Groups
-------------
```

**Comment by gabjef** [comment]
Additional note, I observed that /sys/devices/virtual/dmi/id/product_uuid is the same on these 2 clients, which also happens to be the UUID. Via this command:
```
echo "$(hostname):$(sed s/-//g /sys/devices/virtual/dmi/id/product_uuid):$(cat /etc/machine-id)"
```
osa-rl8-lab01.lab.tierpoint.com:a9881b42a0ef5cdbea942554a9a30b8b:7e2e46c283d2521f395b0ec9650b3d62
osa-rocky8-build.lab.tierpoint.com:a9881b42a0ef5cdbea942554a9a30b8b:8aca98e84bde9a7548dfcd15650b351e

**Comment by gabjef** [comment]
So the more I look at this issue, it appears it may be VMware related regarding the duplicate UUIDs.
Gonna leave this issue open for now and look to resolve via the VMware side if possible....

**Comment by gabjef** [comment]
After some additional research we have concluded this is strictly a VMware issue. More specifically, VMs that are deployed from vApp templates. VMware has acknowledged the the behavior:
[VM BIOS UUIDs are not unique when virtual machines are deployed from vApp templates (2002506)](https://kb.vmware.com/s/article/2002506)

I am going to leave this issue open for the time being for visibility purposes. Maybe this is an item that could be added to the Uyuni documentation, as it kind of falls in the same category as duplicate machine-ids, which is also a condition remediated _outside_ of Uyuni proper.

**Comment by digdilem** [comment]
I'm not a dev, but I've met this and worked around it. 

My solution is to reset the machine-id (EL clients) when cloning or building from template.

This can be included in Uyuni's bootstrap.sh used for onboarding by including this fairly early in the script which regenerates the id before venv-salt-minion is installed.

echo "Clearing machine-id to ensure no dupes"
rm -f /etc/machine-id
systemd-machine-id-setup

**Comment by gabjef** [comment]
> I'm not a dev, but I've met this and worked around it.
> 
> My solution is to reset the machine-id (EL clients) when cloning or building from template.
> 
> This can be included in Uyuni's bootstrap.sh used for onboarding by including this fairly early in the script which regenerates the id before venv-salt-minion is installed.
> 
> echo "Clearing machine-id to ensure no dupes" rm -f /etc/machine-id systemd-machine-id-setup

Thanks for the feedback, but the issue here is not related to the duplicate machine-id issue, this is a VMware level "problem" wherein the BIOS UUID of vApp template does not regenerate a new UUID by default. Please see the VMware KB article link I provided.

**Comment by avshiliaev** [comment]
I believe this issue is related

https://github.com/uyuni-project/uyuni/issues/7217

**Comment by gabjef** [comment]
> I believe this issue is related
> 
> #7217

Ah, I had not seen that formerly reported issue. That does appear to be what we have also observed.

**Comment by gabjef** [comment]
Closing this issue.
The issue is known, but the root cause is hypervisor behavior as opposed to Uyuni itself.
It may warrant a mention in the documentation.
Per [7217](https://github.com/uyuni-project/uyuni/issues/7217) there is a workaround.

**Comment by avshiliaev** [comment]
thanks @gabjef 
the issue is valid though. There's no direct solution from our side yet, but we're definitely taking it into consideration for our coming releases.
