### ISSUE TITLE
API create errata

### ISSUE THREAD

**Issue by benschwarz1982** [uyuni-project/uyuni#7577]
### Problem description

With Uyuni API Version 26 its not posible to create an errata.

### Steps to reproduce

I run the following curl command:

curl -X POST -H "Content-Type: application/json" --cookie "$cookie" "$API/errata/create" -d '{
    "synopsis":"apples are ghood",
    "advisory_name":"qwerty",
    "advisory_release":4,
    "advisory_type":"Bug Fix Advisory",
    "advisory_status":"final",
    "product":"oranges",
    "errataFrom":"none",
    "topic":"abacadaba",
    "description":"rhel9",
    "references":"none",
    "notes":"none",
    "solution":"rhel9",
    "severity":"Critical",
    "bugs":[{"id":2,"summary":"none","url":"none"}],
    "keywords": ["none"],
    "packageIds":[8723],
    "channelLabels":["2023-09-rhel"]
}'

and get always the message: No method exists with the matching parameters.

Other errata methods such as delete working fine.

### Uyuni version

```bash
2023.04-220400.204.4.uyuni2
```

### Useful logs

```bash
I can't provide you any useful log, because in the rhn_web_api.log there is no entry about my call.
```

**Comment by benschwarz1982** [comment]
Human error. Structure was missing in the command.

**Comment by avshiliaev** [comment]
Hey @benschwarz1982,
closing the issue, feel free to reopen.
