### ISSUE TITLE
Add uyuni-proxy-systemd-services for debian

### ISSUE THREAD

**Issue by tanganellilore** [uyuni-project/uyuni#7589]
# Short description

Add/publish Debian package for uyuni-proxy-systemd-services to allow support on Ubuntu machine. 

# Details

Due to the fact that podman can be installed via apt on Ubuntu >=22, it will be interesting have a support for proxy containerized environment also on Debian vm, like Ubuntu. 

On OBS should be possible add .deb package and this allow us to deploy a proxy pod with all container in a Ubuntu. 

For sure some modification is required in .spec file, I'm not Expert but i will try to check if I can submit some modification. 

Let me know What you think.

**Comment by mbussolotto** [comment]
@cbosdo @rjmateus @admd

**Comment by cbosdo** [comment]
In my opinion the [`uyuniadm`](https://github.com/uyuni-project/uyuni-tools) tool should now be used to deploy this services file rather than multiplying the distro-specific packages.

**Comment by tanganellilore** [comment]
I agree, Moreover if uyuni-tools will be availabe in container environment.

Do you think that we can add something called `uyuniproxy` or adding option to manage proxy inside `uyuniadm`?
I'm not a go Expert bu i can try to help you.

Thanks

**Comment by cbosdo** [comment]
> Do you think that we can add something called `uyuniproxy` or adding option to manage proxy inside `uyuniadm`? I'm not a go Expert bu i can try to help you.

Maybe a command like `uyuniadm install proxy podman` that would basically drop the configuration files and the service file in the expected places.

**Comment by tanganellilore** [comment]
I will close this issue in favour on https://github.com/uyuni-project/uyuni-tools/issues/62 becasue to me is better the proposal of @cbosdo .

Thanks for your support
