### ISSUE TITLE
Package dependency error in spacewalk-backend-tools on openSUSE 42.3?

### ISSUE THREAD

**Issue by rpasche** [uyuni-project/uyuni#765]
Just testing improvments for Ubuntu / Debian clients and rebuilt ```spacewalk-backend```, ```spacewalk-config``` and ```susemanager-sls``` packages from ```ubuntu-support``` branch.

Trying to install resulting ```spacewalk-backend-tools-4.0.7``` packages results in dependency error on openSUSE 42.3.

Is this correct?

```
uyuni-test:~/ubuntu-support # rpm -Uvh *.rpm
error: Failed dependencies:
python2-urlgrabber is needed by spacewalk-backend-tools-4.0.7-1.noarch
```

I only got "python-urlgrabber"

```
uyuni-test:~/ubuntu-support # rpm -q --info python-urlgrabber
Name : python-urlgrabber
Version : 3.9.1
Release : 16.4
Architecture: noarch
Install Date: Fri Oct 5 11:33:06 2018
Group : Development/Languages/Python
Size : 304495
License : LGPL-2.1
Signature : RSA/SHA256, Fri May 19 20:32:55 2017, Key ID b88b2fd43dbdc284
Source RPM : python-urlgrabber-3.9.1-16.4.src.rpm
Build Date : Fri May 19 20:32:46 2017
Build Host : cloud103
Relocations : (not relocatable)
Packager : http://bugs.opensuse.org
Vendor : openSUSE
URL : http://urlgrabber.baseurl.org
Summary : A high-level cross-protocol url-grabber
Description :
A high-level cross-protocol url-grabber for python supporting HTTP, FTP
and file locations. Features include keepalive, byte ranges,
throttling, authentication, proxies and more.
Distribution: openSUSE Leap 42.3
```

This change has been introducted in commit a839b867989a4275a0699283de25e82a21ef7af3

Just want to be sure, if this is maybe a mistage within the spec file or if there really is another urlgrabber python package.

**Comment by meaksh** [comment]
Hey @rpasche, thanks for reporting this issue :+1:

We should probably adapt the spec file to require `python-urlgrabber` in case of Leap 42.3

**Comment by juliogonzalez** [comment]
Leap 42.3 is now EoL. Should we close this issue? @meaksh, @rpasche?

**Comment by rpasche** [comment]
Would be ok for me.

⁣sent from my mobile device​


-------- Originale Nachricht --------
Von: "Julio González Gil" <notifications@github.com>
Gesendet: Mon Aug 05 01:00:39 GMT+02:00 2019
An: uyuni-project/uyuni <uyuni@noreply.github.com>
Cc: Robert Paschedag <robert.paschedag@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [uyuni-project/uyuni] Package dependency error in spacewalk-backend-tools on openSUSE 42.3? (#765)

Leap 42.3 is now EoL. Should we close this issue? @meaksh, @rpasche?

**Comment by meaksh** [comment]
Closing since openSUSE Leap 42.3 is EoL.
