### ISSUE TITLE
Portal redirection problem after successful sign it

### ISSUE THREAD

**Issue by szymonsypula** [uyuni-project/uyuni#7650]
### Problem description

Hello

Uyuni release [2023.04] deployed on Azure VM. 
After successful sign in user is not redirected to Uyuni portal. 
Prompt with successful sign in message is being displayed and log in page is refreshed with empty credentials input fields. 
In order to navigate to portal user need to type manually endpoint /rhn/YourRhn.do or click About button to redirect to portal and have access to navbar.

It is a minor issue due workaround exists however is requires to explain users how to proceed in such scenario. 

### Steps to reproduce

1. Navigate to login page 
2. Type valid credentials
3. Hit sign in button

### Uyuni version

```bash
Uyuni release [2023.04] deployed on Azure VM.
```

**Comment by avshiliaev** [comment]
Hey @szymonsypula!
Thanks for your report. While you're signing in, can you open the developer tools in your browser and look if there're any errors in the console or any specific return codes in the network tab?

**Comment by szymonsypula** [comment]
No logs in console tab. Nothing suspicious in NW tab either. 
Attaching NW tab dump. 
![image](https://github.com/uyuni-project/uyuni/assets/39187878/6b362c33-ed4f-49cb-ad13-4953220bc2e6)

**Comment by avshiliaev** [comment]
Thanks @szymonsypula 
Are you using an external auth provider with PAM https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/auth-methods-pam.html?

**Comment by szymonsypula** [comment]
Found the root cause of such behavior.
java.sso = true in /etc/rhn/rhn.conf
However SSO was not fully configured. 

Set java.sso = false & restarted spacewalk-services solved the issue. 

Thank you for suggestions. 
Closing issue.
