### ISSUE TITLE
Does Uyuni Server require a SUSE subscription to register a Uyuni Proxy?

### ISSUE THREAD

**Issue by egrist** [uyuni-project/uyuni#7652]
# Question

Is a SUSE subscription needed to install and setup Uyuni Server and Uyuni Proxy?

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release`='2023.09-230900.207.8.uyuni3' and `zypper info Uyuni-Proxy-release`=2023.09-230900.207.8.uyuni3

**Comment by BerndHelber** [comment]
No you don't need a suse Subscription.
Stick to the Documentation 
https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/uyuni-install-requirements.html
https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/install-proxy-unified.html

**Comment by egrist** [comment]
My apologies, if I understand it correctly my Organization has to be registered in the SCC?

I'm following the steps in the documentation for example here https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/uyuni-server-setup.html#_optional_synchronizing_products_from_suse_customer_center states this step is optional and so I skipped that, but when I get to the https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/uyuni-proxy-registration.html proxy registration I can't seem to do this step it asks for Suse Manager login. I have an account but my Organization isn't there so I can't enter Organization Credentials, I suspect this is what's needed.

**Comment by BerndHelber** [comment]
i assume there's a massive misunderstanding
You set up your Uyuni Server..... you setup a a Uyuni Proxy and register the Proxy to your Uyuni Server.
Logically you have to regiter your Proxy server to the SuSE Manager / Uyuni...  you have to autenticate yourself against the Uyuni Server... with your credentials, i assume you created Credentials.. Username and Password. Make use of those Credentials..

Do you need SuSE  / SLES Products?
If you need SLES Products you need  a SuSE  subscription, if not you dont need a SuSE Subscription. 
Maybe you should have another Look into the Documenation as well cause it is outlined very well.

**Comment by egrist** [comment]
Thank you for the clarification @BerndHelber, it was indeed a massive misunderstanding.
