### ISSUE TITLE
Bootstrap Server in DMZ fail

### ISSUE THREAD

**Issue by TuxOps-lab** [uyuni-project/uyuni#7772]
### Problem description

Hello there,

i have an issue and arn't able to figure out, whats the cause for.
I have an bunch of Servers (Oracle linux 8) within an DMZ. I want to register them to my Uyuni Server via WebUi.
For that i'll check the box which says: "Manage system completely via SSH (will not install an agent)"
But the bootstrap always fails with this message: grep: Terminal: Datei oder Verzeichnis nicht gefunden Error: Unable to download https://myserverdomain:443/pub/repositories/res/8/bootstrap/venv-enabled-x86_64.txt file!

Hope someone can help me here please, to figure out whats the problem.

thx much

### Steps to reproduce

try to get an Oracle Linux 8 Server from an DMZ into the Uyuni server. Uyuni can only communicate via ssh. DMZ itself cant reach the Uyuni Server

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.09-230900.207.8.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.09-230900.207.8.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
rhn_web_ui.log
`grep: Terminal: Datei oder Verzeichnis nicht gefunden
Error: Unable to download [https://myserverdomain:443/pub/repositories/res/8/bootstrap/venv-enabled-x86_64.txt](https://myserverdomain/pub/repositories/res/8/bootstrap/venv-enabled-x86_64.txt) file!
2023-10-23 15:03:15,131 [ajp-nio-127.0.0.1-8009-exec-2] ERROR com.suse.manager.webui.controllers.bootstrap.AbstractMinionBootstrapper - Error during bootstrap: An error has occurred during salt execution: unable to establish ssh connection.

Standard output:
root@oraclelinux8's password:

Standard error:
grep: Terminal: Datei oder Verzeichnis nicht gefunden
Error: Unable to download [https://myserverdomain:443/pub/repositories/res/8/bootstrap/venv-enabled-x86_64.txt](https://myserverdomain/pub/repositories/res/8/bootstrap/venv-enabled-x86_64.txt) file!`
```

### Additional information

What i already could figured out:

-     When i move the Server into the other DMZ, the issue wont exist and the server can be added.
-     Both DMZ have exactly the same configuration, except another networkrange ofc
-     the Uyuni server is allowed to connect via ssh into both dmz
-     in the dmz where adding fails, an try to wget the uyuni server appears, but shouldn't. Cause its ssh only and also wont happen into other dmz (sniffed by firewall log also"
-     newly created servers in the failing dmz also lead to fail of bootstrapping them with the same issue
-     the ssh connection always works

**Comment by vzhestkov** [comment]
Have you tried to request the file with this url from the system you are trying to register directly? For example with `curl ‐i https://imyserverdomain/pub/repositories/res/8/bootstrap/venv-enabled-x86_64.txt`. With the same user you are using for bootstrap. For me looks like the proxy settings are wrong on the system, maybe add the host of the server it's trying to the exceptuon list. But it's better to enaure from the system if request with `curl` works.

**Comment by vzhestkov** [comment]
Then the only possible solution I see is to use `Push via SSH tonnel` contact method with the activation key.
For some reason I can't find the documentation for it, but the steps are the following:
1. Create activation key with `Push via SSH tonnel` contact method selected
2. On the bootstrap page select the created activation key and choose `Manage system completely via SSH (will not install an agent)`.
In this case it should add an extra configuration to bring up the tunnel on each ssh connection, so it will wrap http/https traffic to the server/proxy with SSH.

**Comment by vzhestkov** [comment]
The only way to debug it is to set `salt-api` service on the master to `trace` logging level.
It could be done by creating drop in config for the service `/etc/systemd/system/salt-api.service.d/logging.conf` with the following content:
```
[Service]
ExecStart=
ExecStart=/usr/bin/salt-api --log-file-level=trace
```
Then call:
```
systemctl daemon-reload
systemctl restart salt-api.service
```
We need to ensure which parameters are passed on running `preflight.sh` there should be a port set to something other than `443`, most probably `1233`. You can also copy the original preflight.sh and add there some debugging to check the environment. The idea is to check if the working environment where preflight.sh is running on the client is correct and. In thi case the URL to the `venv-enabled...txt` file should be different. There should be the tunnel port instead an `localhost` instead of real host name of the server/proxy. So the trick here that actually in this case the ssh service is providing this port on the client to get an access to https port from the server. I'm not sure if I can check the same configuration as you have on my testing system. But I'm almost 100% sure I've checked such config when we introduced the preflight script.

**Comment by vzhestkov** [comment]
@Uyunifier it doesn't look like you set up this client as SSH via Tunnel: `/bin/sh '/tmp/preflight.sh' myuyuniserver.local 443 0 1` it shows the port 443 here instead of `1233`

**Comment by vzhestkov** [comment]
You need to create activation key with extra setting specifying that tunnel is required as I described here: https://github.com/uyuni-project/uyuni/issues/7772#issuecomment-1814356642

**Comment by vzhestkov** [comment]
And the other possible workaround is to install `venv-salt-minion` package on the client manually, no need to configure it, the preflight can use it instead of getting the package from the server. But it's a bit hacky way, so it's better to understand what's wrong with 1233 on the client, why it can't be used.

**Comment by vzhestkov** [comment]
1233 is not on the uyuni server side, it's a port open by ssh on the client itself, so for the client it's a port on localhost. Do you reall have such firewall rules to forbid local connections on the client? The port can be reconfigured if needed, but anyway it will stay on the client side.

**Comment by vzhestkov** [comment]
I would suggest to use preflight.sh (don't forget to backup the original) to put any debugging there, just because 1233 is only available during the ssh session open and you cant reproduce it without bringing the connection up from salt-api, so the easiest way is to add `ss -nltp` (or `netstat -nltp`, not sure what is the default in OEL 3) and forward the output to any file to check if the port is opened for listening while the tunnel is up. Can you share the firewall rules from the client?

**Comment by vzhestkov** [comment]
Hmm, just realized that according to the output you show it's trying to connect to the server instead of localhost. But there is a part in the preflight:
```
if [ ${BOOTSTRAP} -eq 1 ] && [ ${REPO_PORT} -ne 443 ]; then
    REPO_HOST="localhost"
fi
```
actually it replaces the actual server host with localhost in case if the bootstrap is running with the port other than 443, but with the bootstrap state it should add an entry to the host pointing the hostname of the server to the localhost. Could you please check `/etc/hosts` if there is such record?

**Comment by vzhestkov** [comment]
And I just noticed that the curl error is from zypper, but not from the preflight itself. So looks like preflight works fine. You can check if there is a directory with the bundle content inside `/var/tmp/venv-salt-minion` if it's full of files the preflight was able to deploy the bundle. Most probably zypper on the system reading some extra configuration maybe proxy settings from the system? In this case you need to add `myuyuniserver.local` (uyuni server host) to the exclude list of the proxy to avoid forward the requests to it through the proxy.

**Comment by vzhestkov** [comment]
Sorry, I have to switch to the other tasks and just not found that I prepared the text, but haven't sent it to you.
...


Oh yes, `dnf`, not `zypper`, but seems it's using curl anyway. So I would suggest to inject at the beggining of the preflight.sh something like this:
```
#!/bin/sh

echo "==========" > /tmp/ssh-debug.txt
ss -nltp >> /tmp/ssh-debug.txt
curl -v https://myuyuniserver.local:1233/rhn/manager/download/oracle-linux-8-prod-ol8-uyuni-client-tools/repodata/repomd.xml >> /tmp/ssh-debug 2>&1
...
```
replace `ss` with `netstat` if `ss` is not present on the OEL client. And check the content of `/tmp/ssh-debug.txt` after an attempt to run salt-ssh session to this client. We need to ensure if 1233 is available in the list and reachable.

**Comment by vzhestkov** [comment]
According to this the tunnel is up:
```
LISTEN 0      128        127.0.0.1:1233      0.0.0.0:*    users:(("sshd",pid=181563,fd=11))
```
And curl output looks correct for me. If `dnf` still reports that it's unable to read the repo, first try to check with adding `ping -c 4 myuyuniserver.local >> /tmp/ssh-debug.txt` and check the file if IP is pointing to localhost there, if not maybe it could require restarting `sshd` on the client, it could be that wrong IP get stuck in the cache of resolved, probably `resolvectl flush-caches` could also help, and maybe try to check if it possible to get any debugging from `dnf`?

**Comment by vzhestkov** [comment]
Mmm, a bit dumb question: are you trying to run `dnf` directly on the client or these errors are the results of pushing dnf from Uyuni server side?

**Comment by vzhestkov** [comment]
@Uyunifier actually the tunnel is up and running only while the ssh session is open for the client for any of the actions from the server and it's not possible to use `dnf` on the client outside of this session as the time gap while the tunnel is up is limited with the amount of time of running the action on the client. So you can't use `dnf` directly on the client :-) Not sure if I explain it really clear, feel free to ask if anything missing in this description.

**Comment by vzhestkov** [comment]
But you can use `mgr-salt-ssh` from the server to run certain commands on the client and this operation will bring up the tunnel first and process all the actions on the client with the tunnel running.

**Comment by vzhestkov** [comment]
Try to run `mgr-salt-ssh mythirdclient state.apply certs` and repeat the steps you with cmd.run, I suppose it should fix the issue

**Comment by vzhestkov** [comment]
Can you try to run `update-ca-certificates -f` on the system and check again?

**Comment by vzhestkov** [comment]
@Uyunifier is it full output of this state? Looks incomplete for me.

**Comment by vzhestkov** [comment]
Please check on the client if `/etc/pki/ca-trust/source/anchors/RHN-ORG-TRUSTED-SSL-CERT` file is present and not empty. For me it looks like the file is deployed but for some some reason it was not included into the trusted CA, but actually it should be done by placing to the proper directory and running `/usr/bin/update-ca-trust extract`

**Comment by vzhestkov** [comment]
Maybe this client has some differences in the config of SSL, not sure, but it looks like the CA of the Uyuni server is not trusted for some reason, it could be missing in the CA bundle or not trusted for some other reason. As a bit hacky way you can compare `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` (not sure if I know the exact path for this OS, but according to some our code adjustments it should be there) of the client having the problem with the other one which doesn't have such issue. If the files are different try to copy it from unaffected client to the client with this issue.
