### ISSUE TITLE
susemanager:channels.repo file is not get creating

### ISSUE THREAD

**Issue by rakeshsujan** [uyuni-project/uyuni#7805]
# Question

_What do you want to know about Uyuni?_

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

**Comment by rakeshsujan** [comment]
Hello All,

When i done with the Bootstrapping some of my Rocky Linux 9.2 machines the susemanager:channels.repo file is not get creating

How to resolve this issue?

**Comment by rakeshsujan** [comment]
I have cleaned up the things from the server and the client end tried to do the bootstrap again facing the same issue. 

Please, help me with this issue.

**Comment by cFabij** [comment]
A little old, but if you still need help, you need to add what you did in more detail.

First and foremost: Execute `salt-key` on your Uyuni server (command line). Do you see your Rocky Linux 9.2 machine in the Accepted Keys?

**Comment by cFabij** [comment]
Okay, great!

Please try on your Uyuni server `salt <minion name as shown in salt-key> state.apply` and if there are any errors, please post the whole output.

**Comment by rakeshsujan** [comment]
@cFabij ,

I have executed the salt state. apply command & please find the below out below.  

**Note: I can't share the FQDN of the server details so I have changed it to xyz.com.**


uyuni:~ #
uyuni:~ # salt s1-transport01.xyz.com state.apply
s1-transport01.xyz.com:
----------
          ID: sync_states
    Function: saltutil.sync_states
      Result: True
     Comment: No updates to sync
     Started: 07:43:32.341596
    Duration: 1209.242 ms
     Changes:
----------
          ID: mgr_absent_ca_package
    Function: pkg.removed
        Name: rhn-org-trusted-ssl-cert
      Result: True
     Comment: All specified packages are already absent
     Started: 07:43:34.756367
    Duration: 8.432 ms
     Changes:
----------
          ID: mgr_ca_cert
    Function: file.managed
        Name: /etc/pki/ca-trust/source/anchors/RHN-ORG-TRUSTED-SSL-CERT
      Result: True
     Comment: File /etc/pki/ca-trust/source/anchors/RHN-ORG-TRUSTED-SSL-CERT is in the correct state
     Started: 07:43:34.767527
    Duration: 367.518 ms
     Changes:
----------
          ID: update-ca-certificates
    Function: cmd.run
        Name: /usr/bin/update-ca-trust extract
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 07:43:35.136717
    Duration: 0.004 ms
     Changes:
----------
          ID: mgr_proxy_ca_cert_symlink
    Function: file.symlink
        Name: /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
      Result: True
     Comment: onlyif condition is false
     Started: 07:43:35.136817
    Duration: 458.812 ms
     Changes:
----------
          ID: mgr_deploy_tools_uyuni_key
    Function: file.managed
        Name: /etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
      Result: True
     Comment: File /etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key is in the correct state
     Started: 07:43:35.595841
    Duration: 214.251 ms
     Changes:
----------
          ID: mgr_deploy_suse_addon_key
    Function: file.managed
        Name: /etc/pki/rpm-gpg/suse-addon-97a636db0bad8ecc.key
      Result: True
     Comment: File /etc/pki/rpm-gpg/suse-addon-97a636db0bad8ecc.key is in the correct state
     Started: 07:43:35.810329
    Duration: 215.036 ms
     Changes:
----------
          ID: mgr_deploy_res_gpg_key
    Function: file.managed
        Name: /etc/pki/rpm-gpg/res-gpg-pubkey-0182b964.key
      Result: True
     Comment: File /etc/pki/rpm-gpg/res-gpg-pubkey-0182b964.key is in the correct state
     Started: 07:43:36.025654
    Duration: 215.065 ms
     Changes:
----------
          ID: mgr_deploy_liberty_v2_gpg_key
    Function: file.managed
        Name: /etc/pki/rpm-gpg/suse-liberty-v2-gpg-pubkey-177086FAB0F9C64F.key
      Result: True
     Comment: File /etc/pki/rpm-gpg/suse-liberty-v2-gpg-pubkey-177086FAB0F9C64F.key is in the correct state
     Started: 07:43:36.240963
    Duration: 216.49 ms
     Changes:
----------
          ID: mgr_deploy_tools_rhel_gpg_key
    Function: file.managed
        Name: /etc/pki/rpm-gpg/el-tools-gpg-pubkey-39db7c82.key
      Result: True
     Comment: File /etc/pki/rpm-gpg/el-tools-gpg-pubkey-39db7c82.key is in the correct state
     Started: 07:43:36.457675
    Duration: 218.461 ms
     Changes:
----------
          ID: mgr_deploy_legacy_tools_rhel_gpg_key
    Function: file.managed
        Name: /etc/pki/rpm-gpg/el6-tools-gpg-pubkey-307e3d54.key
      Result: True
     Comment: File /etc/pki/rpm-gpg/el6-tools-gpg-pubkey-307e3d54.key is in the correct state
     Started: 07:43:36.676468
    Duration: 215.026 ms
     Changes:
----------
          ID: file_///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
    Function: mgrcompat.module_run
        Name: pkg.add_repo_key
      Result: True
     Comment: Module function pkg.add_repo_key executed
     Started: 07:43:36.891715
    Duration: 25.156 ms
     Changes:
              ----------
              ret:
                  True
----------
          ID: file_///etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
    Function: mgrcompat.module_run
        Name: pkg.add_repo_key
      Result: True
     Comment: Module function pkg.add_repo_key executed
     Started: 07:43:36.917153
    Duration: 24.41 ms
     Changes:
              ----------
              ret:
                  True
----------
          ID: mgrchannels_susemanagerplugin_dnf
    Function: file.managed
        Name: /usr/lib/python3.9/site-packages/dnf-plugins/susemanagerplugin.py
      Result: True
     Comment: File /usr/lib/python3.9/site-packages/dnf-plugins/susemanagerplugin.py is in the correct state
     Started: 07:43:36.941817
    Duration: 375.631 ms
     Changes:
----------
          ID: mgrchannels_susemanagerplugin_conf_dnf
    Function: file.managed
        Name: /etc/dnf/plugins/susemanagerplugin.conf
      Result: True
     Comment: File /etc/dnf/plugins/susemanagerplugin.conf is in the correct state
     Started: 07:43:37.317675
    Duration: 368.288 ms
     Changes:
----------
          ID: mgrchannels_enable_dnf_plugins
    Function: file.replace
        Name: /etc/dnf/dnf.conf
      Result: True
     Comment: onlyif condition is false
     Started: 07:43:37.686348
    Duration: 18.663 ms
     Changes:
----------
          ID: mgrchannels_repo
    Function: file.managed
        Name: /etc/yum.repos.d/susemanager:channels.repo
      Result: True
     Comment: File /etc/yum.repos.d/susemanager:channels.repo is in the correct state
     Started: 07:43:37.706016
    Duration: 407.915 ms
     Changes:
----------
          ID: mgrchannels_dnf_clean_all
    Function: cmd.run
        Name: /usr/bin/dnf clean all
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 07:43:38.114571
    Duration: 0.004 ms
     Changes:
----------
          ID: pkg_installed
    Function: pkg.installed
      Result: True
     Comment: No packages to install provided
     Started: 07:43:38.114827
    Duration: 1.118 ms
     Changes:
----------
          ID: pkg_removed
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 07:43:38.116244
    Duration: 8.776 ms
     Changes:
----------
          ID: pkg_latest
    Function: pkg.latest
      Result: True
     Comment: No packages to install provided
     Started: 07:43:38.125326
    Duration: 0.842 ms
     Changes:
----------
          ID: disable_spacewalksd
    Function: service.dead
        Name: rhnsd
      Result: True
     Comment: The named service rhnsd is not available
     Started: 07:43:38.126338
    Duration: 18.13 ms
     Changes:
----------
          ID: disable_spacewalk-update-status
    Function: service.dead
        Name: spacewalk-update-status
      Result: True
     Comment: The named service spacewalk-update-status is not available
     Started: 07:43:38.144674
    Duration: 11.415 ms
     Changes:
----------
          ID: disable_osad
    Function: service.dead
        Name: osad
      Result: True
     Comment: The named service osad is not available
     Started: 07:43:38.156279
    Duration: 11.432 ms
     Changes:
----------
          ID: remove_traditional_stack_all
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 07:43:38.167909
    Duration: 9.644 ms
     Changes:
----------
          ID: remove_traditional_stack
    Function: pkg.removed
      Result: True
     Comment: All specified packages are already absent
     Started: 07:43:38.177729
    Duration: 41.311 ms
     Changes:
----------
          ID: remove_suse_register_info_rh
    Function: pkg.removed
        Name: suseRegisterInfo
      Result: True
     Comment: All specified packages are already absent
     Started: 07:43:38.219297
    Duration: 7.757 ms
     Changes:
----------
          ID: /etc/sysconfig/rhn/systemid
    Function: file.managed
      Result: True
     Comment: File /etc/sysconfig/rhn/systemid exists with proper permissions. No changes made.
     Started: 07:43:38.227239
    Duration: 1.578 ms
     Changes:
----------
          ID: mgr_salt_minion_inst
    Function: pkg.installed
        Name: venv-salt-minion
      Result: True
     Comment: All specified packages are already installed
     Started: 07:43:38.229546
    Duration: 8.388 ms
     Changes:
----------
          ID: /etc/venv-salt-minion/minion.d/susemanager.conf
    Function: file.managed
      Result: True
     Comment: File /etc/venv-salt-minion/minion.d/susemanager.conf is in the correct state
     Started: 07:43:38.238202
    Duration: 397.063 ms
     Changes:
----------
          ID: mgr_salt_minion_run
    Function: service.running
        Name: venv-salt-minion
      Result: True
     Comment: The service venv-salt-minion is already running
     Started: 07:43:38.635552
    Duration: 33.394 ms
     Changes:

Summary for s1-transport01.xyz.com
-------------
Succeeded: 31 (changed=2)
Failed:     0
-------------
Total states run:     31
Total run time:    5.109 s
uyuni:~ #

**Comment by rakeshsujan** [comment]
@cFabij,

Yes after executing this command the /etc/yum.repos.d/susemanager:channels.repo file got created.

Thanks for your support.

May I know what was an issues?

**Comment by rakeshsujan** [comment]
@cFabij ,

Thanks for your support and will close this case.
