### ISSUE TITLE
Extend API call to show whether an errata affects the package management stack.

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#7811]
# Short description

The Uyuni web UI shoes whether a patch affects the management stack:

![grafik](https://github.com/uyuni-project/uyuni/assets/5862725/c82ae2ee-f541-4ddf-940b-71387372258a)

It would be nice if these information could also be gathered using the API - e.g. within the `system.getRelevantErrata` call.

# Details

I'm using the [Uyuni Ansible collection](https://github.com/stdevel/ansible-collection-uyuni) for automating patch installation. Anyhow, from time to time there are regression bugs in openSUSE Leap / SLES that result in a orphaned task during patch installation. As a result, the patch task is still in "Scheduled" or "Picked Up" state, even though some patches might have been installed - or not. It is advised to install all package management stack updates first before installing all remaining patches.

Having this "affects package management stack" information by using the API would make things much easier for me.

**Comment by admd** [comment]
@stdevel this is good one and make sense. We will soon get on to it.

**Comment by cbbayburt** [comment]
Upstream issue: https://github.com/uyuni-project/uyuni/issues/7811

**Comment by mcalmer** [comment]
implemented. Will be part of the next uyuni release
