### ISSUE TITLE
mgr_ssl_cert_setup.py isn't working

### ISSUE THREAD

**Issue by kcote-ncar** [uyuni-project/uyuni#7816]
### Problem description

I am replacing my expiring TLS certificate on my test Uyuni server. I utilize ACME to obtain my certificates so I have my old certificate and a new certificate.

When running:
`mgr-ssl-cert-setup -v -r /root/CAs/root.pem -i /root/CAs/inter.pem -i /root/CAs/inter2.pem -s /etc/letsencrypt/live/server/fullchain.pem -k /etc/letsencrypt/live/server/privkey.pem`

I consistently receive:

> Unknown Private Key type
> 
> ERROR: Unable to read the server key. Is it maybe encrypted?

I have attempted the same replacement with the previous certificate that worked a year ago and I receive that error message as well.
I then pulled the older version of mgr_ssl_cert_setup.py from "https://github.com/uyuni-project/uyuni/blob/Uyuni-2023.04/spacewalk/certs-tools/mgr_ssl_cert_setup.py" and my certificate replacement worked with the older version placed in "/usr/lib/python3.6/site-packages/certs". It seems the updated version isn't working with imported RSA certificates.

### Steps to reproduce

1. Obtain CA and intermediary certificates
2. Obtain a valid RSA certificate
3. Follow the documentation to replace the Uyuni certificate by running " mgr-ssl-cert-setup --root-ca-file=<Path_to_Root_CA_Certificate> --server-cert-file=<Server_Cert_File> --server-key-file=<Server_Key_File>"
4. Receive Unknown Private Key type error
5. Replace "/usr/lib/python3.6/site-packages/certs/mgr_ssl_cert_setup.py" with version from 2023.04

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.09-230900.207.8.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.09-230900.207.8.uyuni3.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Additional information

I haven't tested with ECC but let me know and I can test that certificate type.

Utilizing the --verbose or -v switch with mgr-ssl-cert-setup doesn't provide any addition information when running the command.

**Comment by cbosdo** [comment]
Strangely enough I don't have the issue when running that code with my own letsencrypt key. What is the return code shown with this command?

```
cat /etc/letsencrypt/live/server/privkey.pem | openssl pkey -passin pass:invalid -text -noout
echo "return code: $?"
```

It should be `0`

**Comment by kcote-ncar** [comment]
So I am just using certbot as an ACME client to a Sectigo CA. I have ran that openssl command and it printed out several pieces of information starting with:
`RSA Private-Key: (2048 bit, 2 primes)
modulus:`

The return code of that command does return 0:
`server:~ # echo "return code: $?"
return code: 0`

I could follow the execution flow enough to see mgr-ssl-cert-setup calls mgr_ssl_cert_setup.py. The mgr-ssl-cert-setup command had worked for the previous renewal back on 2022-11-29. I pulled the older older version of mgr_ssl_cert_setup.py and that worked around the "Unknown Private Key type" error that I was receiving.

Let me know if I can provide additional information.

Thanks!

**Comment by mcalmer** [comment]
What is in the logfile? /var/log/rhn/mgr-ssl-cert-setup.log

**Comment by cbosdo** [comment]
> So I am just using certbot as an ACME client to a Sectigo CA. I have ran that openssl command and it printed out several pieces of information starting with: `RSA Private-Key: (2048 bit, 2 primes) modulus:`
> 
> The return code of that command does return 0: `server:~ # echo "return code: $?" return code: 0`

I just realized that you filed the bug before the changes I made in that code has been released. If the above command works for you, could you please upgrade to 2023.10: the code checking the private key is using the command I asked you to run and should solve the issue.
