### ISSUE TITLE
Ubuntu 22.04 minion fails high state while running pkg.installed Salt function

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#7818]
### Problem description

Ubuntu 22.04 minion fails high state while running pkg.installed Salt function trying to install CentOS 7 "Spacewalk Configuration Client Libraries" packages

### Steps to reproduce

1. Bootstrap an Ubuntu 22.04 system
2. Observe that onboarding throws an error about the pkg.installed Salt function failing to find mgr-cfg* packages (Spacewalk Configuration Client Libraries)
3. All subsequent high states on the minion throw the same error and Uyuni sees it as a failure

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.09-230900.207.8.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.09-230900.207.8.uyuni3.src
Summary        : Uyuni Server
```

### Useful logs

```bash
From high state output:
----------
          ID: pkg_installed
    Function: pkg.installed
        Name: pkg_installed
      Result: false
     Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r5254efa130b249ec8116880dd6816924.scope
      E: Unable to locate package mgr-cfg-actions
      E: Unable to locate package mgr-cfg
      E: Unable to locate package mgr-cfg-client
     Started: 22:34:42.542839
    Duration: 750.9
         SLS: packages.packages_788b636844e472a7193c8409654423b9
     Changed: {}
```

### Additional information

mgr-cfg, mgr-cfg-actions and mgr-cfg-client are packages from the centos7-uyuni-client-tools repo.
There are no "Spacewalk Configuration Client Libraries" for Ubuntu in the ubuntu-2204-amd64-uyuni-client repo.
It's unclear why an Ubuntu 22.04 server would need "Spacewalk Configuration Client Libraries". This seems like a fairly significant issue, as it causes setting of high state to throw an error for Ubuntu 22.04 minions _everytime_ it is run, and gets reported as such.

**Comment by mayrstefan** [comment]
From looking at the commit history would say mgr-cfg was removed in september. But https://www.uyuni-project.org/uyuni-docs/en/uyuni/reference/cli-mgrcfg.html still mentions it. So this may be a documentation issue, too.

**Comment by meaksh** [comment]
> From looking at the commit history would say mgr-cfg was removed in september. But https://www.uyuni-project.org/uyuni-docs/en/uyuni/reference/cli-mgrcfg.html still mentions it. So this may be a documentation issue, too.

@mayrstefan Thanks for pointing this out! This is indeed a documentation issue, so I created corresponding issue to tackle it: https://github.com/uyuni-project/uyuni/issues/7889

**Comment by meaksh** [comment]
Thanks for contributing @gabjef !

> ### Useful logs
> ```shell
> From high state output:
> ----------
>           ID: pkg_installed
>     Function: pkg.installed
>         Name: pkg_installed
>       Result: false
>      Comment: Problem encountered installing package(s). Additional info follows:
> 
> errors:
>     - Running scope as unit: run-r5254efa130b249ec8116880dd6816924.scope
>       E: Unable to locate package mgr-cfg-actions
>       E: Unable to locate package mgr-cfg
>       E: Unable to locate package mgr-cfg-client
>      Started: 22:34:42.542839
>     Duration: 750.9
>          SLS: packages.packages_788b636844e472a7193c8409654423b9
>      Changed: {}
> ```

In this case, as we see here, it is this SLS `packages.packages_788b636844e472a7193c8409654423b9` the one that is forcing the installation of this unexisting `mgr-cfg-*` packages.

This is a generated SLS based on the packages that the user has set to be installed via "States -> Packages" page for this system or system group.

So, in this case, it seems the user has defined this packages to be explicite installed via "States -> Packages" for this system or group of systems - not really a Uyuni product issue. They would need to remove these packages from the list of package to install.

Hth!

I'm closing this issue now as this is apparently invalid. Feel free to re-open it if that is not the case. Thanks!
