### ISSUE TITLE
spacewalk-common-channels traceback

### ISSUE THREAD

**Issue by megamaced** [uyuni-project/uyuni#784]
USER@uyuni:~> sudo spacewalk-common-channels -u USER 'opensuse_leap15_0*'
SUSE Manager password: 
Traceback (most recent call last):
  File "/usr/bin/spacewalk-common-channels", line 229, in <module>
    add_channels(channels, section, arch, client)
  File "/usr/bin/spacewalk-common-channels", line 92, in add_channels
    config.get(section, 'base_channels'), 1)
  File "/usr/lib64/python3.6/configparser.py", line 800, in get
    d)
  File "/usr/lib64/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib64/python3.6/configparser.py", line 434, in _interpolate_some
    option, section, rawval, var) from None
configparser.InterpolationMissingOptionError: Bad value substitution: option 'base_channels' in section 'fedora27-updates' contains an interpolation key 'arch' which is not a valid option name. Raw value: 'fedora27-%(arch)s'

**Comment by mcalmer** [comment]
@juliogonzalez @brejoc do we have a typo in the ini file or is there a problem after python3 porting?

**Comment by brejoc** [comment]
@mcalmer Which ini file are we talking about in this case?

**Comment by mcalmer** [comment]
`spacewalk-common-channels.ini`. Installed at /etc/rhn/ in the git available in the /utils/ directory.

**Comment by juliogonzalez** [comment]
We'll, back when we released 4.0.1 I tested syncing the 15.0 Leap channels and it worked fine, and that Fedora line was not modified by me:
https://github.com/uyuni-project/uyuni/blame/master/utils/spacewalk-common-channels.ini#L53

So I'd say this is a problem at `spacewalk-common-channels` script or any of the dependencies.

**Comment by megamaced** [comment]
Works in 4.0.1. It was when I was running master from https://build.opensuse.org/project/show/systemsmanagement:Uyuni:Master

**Comment by juliogonzalez** [comment]
@megamaced thanks a lot. Then it's most probably a problem with the migration to python3 suspected.

Marked now so we have a look to get it fixed for 4.0.2 (this is not covered right now by the testsuite, so we'll need to fix and verify manually).
