### ISSUE TITLE
RHEL7 Bootstrap don't work anymore, changed name

### ISSUE THREAD

**Issue by TuxOps-lab** [uyuni-project/uyuni#7844]
### Problem description

I tried to add RHEL7 to uyuni, but after running mgr-create-bootstrap repo, it wont appear in list.
I think the reason is, the channel names have been changed. They also not correct in documentation ofc.

### Steps to reproduce

1. cmd: spacewalk-common-channels rhel7-pool-uyuni-x86_64 rhel7-uyuni-client-x86_64
2. cmd: spacewalk-repo-sync -p rhel7-pool-uyuni-x86_64
3. cmd: mgr-create-bootstrap-repo
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.09-230900.207.8.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.09-230900.207.8.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Additional information

Changing  line 1303 in `/usr/share/susemanager/mgr_bootstrap_data.py` fixes the problem

`1303 old` 'BASECHANNEL' : 'rhel7-pool-x86_64', 'PKGLIST' : RES7 + RES7_X86,
`1303 new` 'BASECHANNEL' : 'rhel7-pool-uyuni-x86_64', 'PKGLIST' : RES7 + RES7_X86,,

**Comment by avshiliaev** [comment]
Hey @Uyunifier 
Thanks a lot for the report. Seems like a valid problem :smiley:
