### ISSUE TITLE
Content Lifecycle filters dont work if the repo is not AppStream. Uyuni Server 2023.09

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#7849]
### Problem description

Content Lifecycle filers do not work if the modular repo is not a AppStream repo.
Tested on Oracle Linux 8 and 9.
AppStream filters seem to work.
Filter was made with Browse available modules.

### Steps to reproduce

1. Add a modular repo thats not AppStream.
2. Create Content Lifecycle Project.
3. Create filter for Content Lifecycle.
4. Add filter to Content Lifecycle Project. 
5. Build Content Lifecycle Project .
6. Look at the packages in the Content Lifecycle repo if the filter worked.

### Uyuni version

```bash
2023.09
```

### Uyuni proxy version (if used)

```bash
Not used in this case.
```

**Comment by cbbayburt** [comment]
Hi, @j-kihet, can you provide the following details about the issue?

For the CLM project you're having problems with:
- Which OL repos are added as sources
- What exact filters are added?
- What's the actual outcome vs. the expected in the resulting packages

**Comment by j-kihet** [comment]
@cbbayburt Thank you for helping!

For this example i will use OL9 but the same issue is in OL8.

Default OL9 repos are added from common-channels.ini (oraclelinux9, oraclelinux9-appstream, oraclelinux9-addons, oraclelinux9-developer-uek-r7, oraclelinux9-rdma, oraclelinux9-uyuni-client).
Only custom repo is remi-modular for php. https://rpms.remirepo.net/enterprise/9/modular/x86_64/
Every default filter from AppStream is used except php.

The remi php filter was made with Browse available modules.
Filter Name *: php 8.1
Filter Type *: Module (Stream)
Matcher *:equals
Module Name *: php 
Stream: remi-8.1

After building, checking the contents of the built remi repo, it lists php packages that are higher than 8.1. 
The filters that are for the AppStream repo packages seem to work. (not 100% sure about this)
Clients also see this and try to update to a higher version of php.

The repo should have only remi php packages that are 8.1.
This has worked in previous uyuni versions.

**Comment by cbbayburt** [comment]
Hi @j-kihet, thanks for the detailed info.

It seems that the REMI repository uses `bz2` compression for the module metadata file, which is not common in the repositories generally supported by Uyuni. `reposync` can actually decompress it, but does not remove the `.bz2` part in the file extension. Because of that, `mgr-libmod` process still thinks it's compressed and tries to decompress it a second time, which fails.

Fortunately, the fix is quite simple. I'll prepare the fix to be available in the next release.
