### ISSUE TITLE
Ubuntu Pro Patches

### ISSUE THREAD

**Issue by hsh-it** [uyuni-project/uyuni#7897]
I believe that the Unbunt Pro patches "simply" come from the appropriate source list and are applied to systems if it is connected to Ubuntu Pro, if not, then not. 

In Uyuni you could then create a group that has this source. But I don't know if and how Uyuni can download the packages to distribute them from Uyuni Master to the systems.

https://ubuntu.com/server/docs/install/subscription

**Comment by stdevel** [comment]
Good idea. I'd also like to see Ubuntu Pro support. I just saw an Ubuntu Pro systems and saw that, after registration, only public URLs are defined below `/etc/apt/sources.list.d`. So there must be a different way how Canonical ensures that only paid customers retrieve the packages (*maybe using client certificates like the Red Hat CDN*). Will have a look at it.

**Comment by hsh-it** [comment]
I have asked Canonical how this can work. The problem is that the Uyuni server cannot load the packages because the authorization fails. So it should be possible somehow to authorize Suse Linux with the token. I have not found a way yet. In general, there is still very little information on this.

Maybe Canonical has an answer. I'll probably get one in one working day, at least that's what it said on the website after I sent the question :-)

**Comment by hsh-it** [comment]
No answer from Canonical ... @stdevel if you got some informations about that im happy to hear from you

**Comment by stdevel** [comment]
> if you got some informations about that im happy to hear from you

Someone pasted me the following link about airgapped environments: https://github.com/canonical/ubuntu-pro-docs/blob/main/airgapped-setup.rst

Unfortunately you'll need an Ubuntu One account in order to read it. Will have a look at it later.

**Comment by stdevel** [comment]
Update: As suspected, synching Ubuntu Pro packages works if you extract the GPG key and bearer token from a registered system. See the following screenshot:

![uyuni_ubuntu_pro](https://github.com/uyuni-project/uyuni/assets/5862725/6de426bf-0a36-4856-8d92-f7f51e21d3a1)

I also published a write-up here: https://cstan.io/en/post/2024/04/ubuntu-pro-mirror/

So, there are no technical changes required in Uyuni - it could be documented in the docs. I'm just unsure if we should document this detailed as this procedure can lead into misuing the Ubuntu Pro service. On the other hand, Uyuni can also mirror RHEL packages and break the terms of service, too. The user needs to ensure having an  many subscriptions as systems.

What do you think, @mmmmmmpc and @dvosburg?

**Comment by hsh-it** [comment]
Something must be different
```
2024/04/29 12:39:58 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'ubuntu-22.04-pro', '--type', 'deb', '--non-interactive']
2024/04/29 12:39:58 +02:00 Sync of channel started.
2024/04/29 12:40:00 +02:00 Repo URL: https://bearer:<secret>@esm.ubuntu.com/infra/ubuntu/dists/jammy-infra-updates/main/binary-amd64/
2024/04/29 12:40:00 +02:00     Packages in repo:                 1
2024/04/29 12:40:00 +02:00     Packages already synced:          0
2024/04/29 12:40:00 +02:00     Packages to sync:                 1
2024/04/29 12:40:00 +02:00     New packages to download:         1
2024/04/29 12:40:00 +02:00   Downloading packages:
2024/04/29 12:40:01 +02:00     1/1 : hello_2.10-2ubuntu4+esm1_amd64.deb
2024/04/29 12:40:01 +02:00 Filtering packages that failed to download
2024/04/29 12:40:01 +02:00 Importing packages started.
2024/04/29 12:40:01 +02:00 
2024/04/29 12:40:01 +02:00   Importing packages to DB:
2024/04/29 12:40:01 +02:00   Package batch #1 of 1 completed...
2024/04/29 12:40:01 +02:00 Importing packages finished.
2024/04/29 12:40:01 +02:00 
2024/04/29 12:40:01 +02:00   Linking packages to the channel.
2024/04/29 12:40:01 +02:00     1 packages linked
2024/04/29 12:40:01 +02:00 
2024/04/29 12:40:01 +02:00   Patches in repo: 0.
2024/04/29 12:40:01 +02:00   Regenerating bootstrap repositories.
2024/04/29 12:40:02 +02:00 Sync completed.
2024/04/29 12:42:30 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'ubuntu-22.04-pro', '--type', 'deb', '--non-interactive']
2024/04/29 12:42:30 +02:00 Sync of channel started.
2024/04/29 12:42:30 +02:00 Repo URL: https://bearer:<secret>@esm.ubuntu.com/infra/ubuntu/dists/jammy-infra-updates/main/binary-amd64/
2024/04/29 12:42:30 +02:00     Packages in repo:                 1
2024/04/29 12:42:30 +02:00     No new packages to sync.
2024/04/29 12:42:30 +02:00 Filtering packages that failed to download
2024/04/29 12:42:30 +02:00 Importing packages started.
2024/04/29 12:42:30 +02:00 
2024/04/29 12:42:30 +02:00   Importing packages to DB:
2024/04/29 12:42:30 +02:00 Importing packages finished.
2024/04/29 12:42:30 +02:00 
2024/04/29 12:42:30 +02:00   Patches in repo: 0.
2024/04/29 12:42:30 +02:00 Sync completed.
```

![image](https://github.com/uyuni-project/uyuni/assets/150814264/7e06fc29-5ebc-4e2c-9d11-5292aedc6bef)


Cahnnel:
Ubuntu 22.04 ESM Infra 


repo:
![image](https://github.com/uyuni-project/uyuni/assets/150814264/647b6562-c8c0-42c1-abf5-1128bac69884)

**Comment by stdevel** [comment]
There aren't that many infra updates for 22.04 available, yet. Have a look at an older release such as 18.04 - or check-out the apps repository. There are more available packages.

**Comment by stdevel** [comment]
Happy to help!

@mmmmmmpc and @dvosburg - let me know if you want me to document it for Uyuni. I can create a PR if you also find this useful. :)
