### ISSUE TITLE
I have followed the steps and but im not able to see list data of available update , patches , installed package and non compliant data (Ubuntu 22).

### ISSUE THREAD

**Issue by jawahk** [uyuni-project/uyuni#7924]
### Problem description

repo has been created as suggested by uyuni but when we on-board the server we are not able to find any packages

### Steps to reproduce

1.create the repo for ubuntu 22.0 AMD64
2.on-board it via salt minion 
3.unable to see the compliance patches  
...

### Uyuni version

```bash
root@kbsuyunisrv:~# zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by cFabij** [comment]
Hi, just to make sure: Did you follow these steps?

1. Created Ubuntu 22.04 common channels on CLI as detailed here https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-ubuntu.html
2.` spacewalk-repo-sync -p ubuntu-22.04-pool-amd64-uyuni` has synced all channels (can be checked via `/var/log/rhn/reposync.log`)
3. `mgr-create-bootstrap-repo -l` shows `ubuntu-22.04-amd64-uyuni`
4. Created an activation key for Ubuntu 22.04 with the correct base channel (default: Ubuntu 22.04 LTS AMD64 Base for Uyuni) and selected child channels (https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/activation-keys.html)
5. Boostrapped client via Uyuni WebUI

**Comment by agraul** [comment]
@jawahk can you confirm you followed the steps that @cFabij listed in https://github.com/uyuni-project/uyuni/issues/7924#issuecomment-1833269756?

**Comment by jawahk** [comment]
yes we did still same

**Comment by cFabij** [comment]
Could you please post
1. a screenshot from Uyuni web UI Software>Channel List>All, where all Ubuntu 22.04 software channels and the number of their respective packages are shown
2. in Uyuni web UI a screenshot from your onboarded system showing Software>Software Channels 

Thanks!

**Comment by avshiliaev** [comment]
Stale issue. Please feel free to reopen
