### ISSUE TITLE
Minor upgrade from Uyuni on previous version of Leap should not upgrade to 2023.10

### ISSUE THREAD

**Issue by simonflood** [uyuni-project/uyuni#7934]
### Problem description

Expected:

Minor upgrade of 2023.03 would give me 2023.04 which would then need major upgrade to get to 2023.09/10.

Actual:

I had a server running Uyuni 2023.03 on Leap 15.4 which needed upgrading. Since the Upgrade Notes for 2023.09[1] includes

WARNING: This release updates the base OS from openSUSE Leap 15.4 to openSUSE Leap 15.5 and there are special steps required. You need at least Uyuni 2023.04 already installed to perform the upgrade, and you need to follow the [major upgrade procedure for the Server](https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/server-major-upgrade-uyuni.html). More details are also available at the "Update from previous versions of Uyuni Server" section below.

I first did a Minor Upgrade[2] thinking that would get me to Uyuni 2023.04 (still on Leap 15.4) but was surprised to find that Uyuni was upgraded to the latest version 2023.10

uyuni-new:~ # cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.4"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
uyuni-new:~ # rpm -qa uyuni-*
uyuni-docs_en-2023.10-230900.1.1.uyuni3.noarch
uyuni-setup-reportdb-4.4.5-230900.1.1.uyuni3.noarch
uyuni-build-keys-web-2023.04.1-230900.4.1.uyuni3.noarch
uyuni-build-keys-2023.04.1-230900.4.1.uyuni3.noarch
uyuni-reportdb-schema-4.4.5-230900.1.2.uyuni3.noarch
uyuni-docs_en-pdf-2023.10-230900.1.1.uyuni3.noarch
uyuni-base-server-4.4.2-230900.1.1.uyuni3.x86_64
uyuni-base-common-4.4.2-230900.1.1.uyuni3.x86_64
uyuni-new:~ # rpm -q susemanager
susemanager-4.4.9-230900.1.1.uyuni3.x86_64

which was also borne out by the web GUI.

Note zypper in Uyuni-Server-release reported that nothing provided  'product(Leap) >= 15.5' which would be correct for Uyuni-Server-2023.10-0.x86_64 yet 2023.10 had been installed.

Given the warning message in the docs above I didn't think this was supported so post-reboot completed the Major Upgrade[3] to get the OS to match

uyuni-new:~ # zypper up susemanager
Loading repository data...
Reading installed packages...
No update candidate for 'susemanager-4.4.9-230900.1.1.uyuni3.x86_64'. The highest available version is already installed.

The server-migrator.sh script ran without issues and now have Uyuni 2023.10 on Leap 15.5

uyuni-new:~ # cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
uyuni-new:~ # rpm -qa uyuni-*
uyuni-docs_en-2023.10-230900.1.1.uyuni3.noarch
uyuni-setup-reportdb-4.4.5-230900.1.1.uyuni3.noarch
uyuni-build-keys-2023.04.1-230900.4.1.uyuni3.noarch
uyuni-reportdb-schema-4.4.5-230900.1.2.uyuni3.noarch
uyuni-docs_en-pdf-2023.10-230900.1.1.uyuni3.noarch
uyuni-base-server-4.4.2-230900.1.1.uyuni3.x86_64
uyuni-base-common-4.4.2-230900.1.1.uyuni3.x86_64
uyuni-build-keys-web-2023.04.1-230900.4.1.uyuni3.noarch

[1] https://www.uyuni-project.org/doc/2023.10/release-notes-uyuni-server.html#_upgrade_notes
[2] https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/server-minor-upgrade-uyuni.html
[3] https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/server-major-upgrade-uyuni.html

### Steps to reproduce

1. install Leap 15.4
2. add Uyuni 2023.03
3. do minor upgrade expecting to get to 2023.04

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2023.10-230900.209.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.10-230900.209.1.uyuni3.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by m-czernek** [comment]
Thank you for the bug report!

It seems to me like the problem here is that the documentation [1] works for SUSE Manager, but not for Uyuni. 

Uyuni is a rolling release, so after some time, users lose their window to upgrade from one minor version to another (since we roll to a newer package) and IIUIC, after that, users are essentially left with either untested upgrade or reinstalling their Uyuni.

CC the documentation team @jcayouette @keichwa @0rnela for an Uyuni documentation fix;
CC the release engineering team @deneb-alpha @raulillo82 as SMEs.

[1] https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/server-major-upgrade-uyuni.html

**Comment by keichwa** [comment]
Thanks for the report.  With the containerization the mentioned file is removed now and procedure are different.  We now have either migrating from legacy installation (w/o container) to containerization or upgrading the rolling release.
ATM, I work on https://github.com/SUSE/spacewalk/issues/25680 (upgrading the rolling release).  I'd appreciate if you could check https://github.com/uyuni-project/uyuni-docs/pull/3413.
