### ISSUE TITLE
Uyuni 2023.10 | OES 23.4 missing

### ISSUE THREAD

**Issue by CSGRhysHa** [uyuni-project/uyuni#7935]
### Problem description

Product OES 23.4 does show in the 'Products' section of the setup wizard when the product is available for my mirror credentials.

### Steps to reproduce

1. Add organisation credentials
2. Refresh the product catalog
3. Open Enterprise Server 2023.4 missing from list
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.10-230900.209.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2023.10-230900.209.1.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by deneb-alpha** [comment]
@CSGRhysHa thanks for the report.

Actually this isn't a bug. On Uyuni we are ~ready to support this new version but the last final approvals from Microfocus are pending ATM.

Please, see the details in this discussion: https://github.com/uyuni-project/uyuni/discussions/7886.

Feel free to reopen if something else is missing/unclear.
