### ISSUE TITLE
Unable to estabilish tcp mTLS minion-master connection

### ISSUE THREAD

**Issue by szymonsypula** [uyuni-project/uyuni#7959]
### Problem description

Hello

I was following documentation for tcp transport mTLS enablement for salt minion-master communication.
When setting up salt-master configuration - master is producing SSL related Errors coming from python libraries.

---

Also reported in salt-project space, was redirected to uyuni-project to verify dependency issue. 
https://github.com/saltstack/salt/issues/65609

---

Setup
Uyuni VM running on a public cloud

/etc/salt/master.d/ssl.conf

ssl:
keyfile: /var/lib/certs/certificates/key.key
certfile: /var/lib/certs/certificates/cert.crt
ca_certs: /var/lib/certs/certificates/ca_cert.crt
cert_reqs: CERT_REQUIRED
ssl_version: PROTOCOL_TLSv1_2
transport: tcp

### Steps to reproduce

Set up /etc/salt/master.d/ssl.conf
systemctl restart salt-master

### Uyuni version

```bash
Uyuni version 2023.10

---

Versions Report

Salt Version:
Salt: 3006.0

Python Version:
Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]

Dependency Versions:
cffi: 1.13.2
cherrypy: 18.3.0
dateutil: 2.8.1
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
Jinja2: 2.10.1
libgit2: 1.3.0
looseversion: 1.0.2
M2Crypto: 0.38.0
Mako: Not Installed
msgpack: 0.5.6
msgpack-pure: Not Installed
mysql-python: Not Installed
packaging: 21.3
pycparser: 2.17
pycrypto: 3.9.0
pycryptodome: Not Installed
pygit2: 1.7.0
python-gnupg: Not Installed
PyYAML: 5.4.1
PyZMQ: 17.1.2
relenv: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.2.3

System Versions:
dist: opensuse-leap 15.5
locale: UTF-8
machine: x86_64
release: 5.14.21-150500.55.19-default
system: Linux
version: openSUSE Leap 15.5
```

### Useful logs

```bash
Errors are produced in loop.

2023-11-24 14:41:07,180 [tornado.general :1333][WARNING ][22216] SSL Error on 82 ('x.x.x.x', 24861): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)

2023-11-24 14:41:09,663 [tornado.general :555 ][ERROR ][22201] Uncaught exception, closing connection.
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/ext/tornado/iostream.py", line 520, in _handle_events
self._handle_read()
File "/usr/lib/python3.6/site-packages/salt/ext/tornado/iostream.py", line 1396, in _handle_read
self._do_ssl_handshake()
File "/usr/lib/python3.6/site-packages/salt/ext/tornado/iostream.py", line 1316, in _do_ssl_handshake
self.socket.do_handshake()
File "/usr/lib64/python3.6/ssl.py", line 1106, in do_handshake
self._sslobj.do_handshake()
File "/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

### Additional information

Expected behavior
After setting up tcp transport and ssl options - salt master is ready to establish connection with minions.

**Comment by lukasraska** [comment]
Ad "[Errno 0] Error" - https://github.com/saltstack/salt/issues/62047 (the error is caused by https://bugs.python.org/issue31122 and should be fixed in Python 3.7+), but it's a Red herring.


The actual error
```
2023-11-24 14:41:07,180 [tornado.general :1333][WARNING ][22216] SSL Error on 82 ('x.x.x.x', 24861): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)
```
is what you should probably focus on. How are the minions configured? You need to match the minion config with what the master expect, otherwise this error will be logged (e.g. minion connecting via plain connection (either TCP or ZeroMQ) instead of TLS)

**Comment by szymonsypula** [comment]
Error is produced on salt-master even if there are no minions / keys at all.

Output from salt-key command: 
![image](https://github.com/uyuni-project/uyuni/assets/39187878/3db76800-7554-4ffc-944f-dcced829f8ca)

**Comment by lukasraska** [comment]
@szymonsypula Are you sure you don't have salt-minion running on the same server are the salt-master? It won't show up in keys if it can't properly connect, so you can i.e. run tcpdump for the port tcp/4506 to check if there are any connection tries towards that port. And the log message `SSL Error on 82 ('x.x.x.x', 24861)` shows exactly what source IP is trying to connect

**Comment by szymonsypula** [comment]
Thank you @lukasraska for support. Traffic was generated from load balancer health monitor.  

Error is gone after full restart on spacewalk-services, not only salt-master component after tcp transport and ssl options introduced.
