### ISSUE TITLE
Actions stuck, cannot delete systems

### ISSUE THREAD

**Issue by megamaced** [uyuni-project/uyuni#801]
Hi, Somehow ended up with actions getting stuck and cannot delete systems.

Package lists for systems don't show in the Web UI

```
spacecmd {SSM:0}> system_list
system1.domain.co.uk : 1000010000
system2.domain.co.uk : 1000010003
system5.domain.co.uk : 1000010001
```

```
spacecmd {SSM:0}> system_delete -c 'FORCE_DELETE' system5.domain.co.uk
Profile                   System ID
------------------------  ---------
system5.domain.co.uk  1000010001

Delete these systems [y/N]: y
INFO: 1 system(s) scheduled for removal
```

```
spacecmd {SSM:0}> system_list
system1.domain.co.uk : 1000010000
system2.domain.co.uk : 1000010003
system5.domain.co.uk : 1000010001
```

```
spacecmd {SSM:0}> schedule_listpending
ID      Date                 C    F    P     Action
--      ----                ---  ---  ---    ------
32      20190404T10:16:04     0    0    1    Package List Refresh scheduled by (unknown)
31      20190404T10:15:55     0    0    1    Package List Refresh scheduled by (unknown)
30      20190404T10:15:51     0    0    1    Package List Refresh scheduled by (unknown)
29      20190404T09:33:16     0    0    1    Package List Refresh scheduled by (unknown)
27      20190404T09:26:56     0    0    1    Package List Refresh scheduled by (unknown)
26      20190404T09:24:25     0    0    1    Package List Refresh scheduled by (unknown)
24      20190404T09:23:30     0    0    1    Package List Refresh scheduled by (unknown)
21      20190403T17:56:40     0    0    1    Package List Refresh scheduled by (unknown)
20      20190403T17:56:33     0    0    1    Apply highstate scheduled by (unknown)
19      20190403T17:56:31     0    0    1    Apply states [certs, channels, channels.disablelocalrepos, packages, services.salt-minion] scheduled by (unknown)
18      20190403T17:56:24     0    0    1    Hardware List Refresh scheduled by (unknown)
12      20190403T16:57:45     0    0    1    Package List Refresh scheduled by (unknown)
11      20190403T16:57:43     0    0    1    Package List Refresh scheduled by (unknown)
```

```
spacecmd {SSM:0}> schedule_details 11
ID:        11
Action:    Package List Refresh scheduled by (unknown)
User:      None
Date:      20190403T16:57:43

Completed:   0
Failed:      0
Pending:     1

Pending Systems
---------------
system5.domain.co.uk
```

```
spacecmd {SSM:0}> schedule_cancel 11
ERROR: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: Cannot cancel actions in PICKED UP state, aborting...
```

From rhn_taskomatic_daemon.log

`INFO   | jvm 1    | 2019/04/04 09:00:00 | 2019-04-04 09:00:00,524 [DefaultQuartzScheduler_Worker-5] ERROR com.suse.manager.webui.utils.MinionActionUtils - JsonParsingError("Minion did not return. [No response]", Expected BEGIN_ARRAY but was STRING at path $)`

**Comment by megamaced** [comment]
But salt-minions are still working and can run a highstate successfully

**Comment by juliogonzalez** [comment]
Please provide details about the minions:
- OS (i.e. openSUSE Leap 15.0)
- salt version at the minion (rpm -qa|grep salt)

**Comment by megamaced** [comment]
```
MINION:~ cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

```
MINION:~ # rpm -q salt-minion
salt-minion-2018.3.0-lp150.3.24.1.x86_64

```

**Comment by megamaced** [comment]
system5.domain.co.uk was decommissioned. The machine no longer exists. But I cannot remove it from Uyuni either by the Web UI or by spacecmd

The above minion output is from system2.domain.co.uk. This also has stuck tasks:

```
spacecmd {SSM:0}> schedule_details 18
ID:        18
Action:    Hardware List Refresh scheduled by (unknown)
User:      None
Date:      20190403T17:56:24

Completed:   0
Failed:      0
Pending:     1

Pending Systems
---------------
system2.domain.co.uk
```

```
spacecmd {SSM:0}> schedule_cancel 18
ERROR: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: Cannot cancel actions in PICKED UP state, aborting...
```

**Comment by admd** [comment]
@megamaced 
This error indicates that action is already in picked up state and can't be deleted, that makes sense but why it is not completed/failed is hard to tell with the given information.

2nd issue that you mentioned about removing the system from spacecmd, may be that is just caching issue. Spacecmd maintains cache and you have to invalidate it with `clear_cache` method. 

Now if that is not caching issue then I can't tell why it cannot delete without looking into the logs. But if you really want to remove the system and you can neither from spacecmd nor from uyuni UI then, unfortunately, you have not many options other than running this `delete_server` stored procedure. Something like this should do the trick. This function will take care of all the cleaning part.

`echo "select delete_server(1000010001)" | spacewalk-sql --select-mode -
`

**Comment by megamaced** [comment]
Thanks for the spacewalk-sql tip, I'll bank that one.

In the end I just restored from the backup I had just before I added any systems.

I think what went wrong is the systems I joined were not clean, i.e they were previously joined to a different Uyuni server.

I moved them by stopping the salt-minion service, deleting /etc/salt/pki/minion/minion_master.pub, pointing the minion at the new Uyuni server in /etc/salt/minion.d/susemanager.conf and restarting the service.

I guess this wasn't enough.

What I did on the next attempt (which works fine now), is:

stop salt-minion
zypper rm salt salt-minion
rm -rf /etc/zypp/credentials.d/* /etc/zypp/services.d/* /etc/zypp/repos.d/* /etc/sysconfig/rhn/{osad-auth.conf,systemid} /etc/machine-id /var/lib/dbus/machine-id /etc/salt /var/cache/salt
dbus-uuidgen --ensure=/etc/machine-id
ln -s /etc/machine-id /var/lib/dbus/

Then run the bootstrap.sh script

No problems after that method

**Comment by admd** [comment]
Happy to help and glad to know you have your setup back in working condition. If there is nothing else to do here, can you please close the issue.
