### ISSUE TITLE
Changes in web.xml are not persisted in Uyuni Container

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni#8030]
### Problem description

Currently documentation describes how to change web.xml to adjust web UI login timeout https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/troubleshooting/tshoot-logintimeout.html . The correct path `/usr/share/susemanager/www/tomcat/webapps/rhn/WEB-INF/web.xml` will be fixed by
https://github.com/uyuni-project/uyuni-docs/pull/2682 but in uyuni container this value woud not be persisted. 

We need to find a new way to override values in web.xml

### Steps to reproduce

See description

### Uyuni version

```bash
2023.10
```

**Comment by aaannz** [comment]
Is this still valid? I noticed that we also have web.xml in /etc/tomcat which is persisted in volume.
