### ISSUE TITLE
Uyuni can't be used on EL7 partly due to Zypper

### ISSUE THREAD

**Issue by Conan-Kudo** [uyuni-project/uyuni#804]
As I had mentioned some time ago in the [uyuni-devel mailing list](https://lists.opensuse.org/uyuni-devel/2019-01/msg00000.html), I have been working on adapting the Uyuni server to run on CentOS and Fedora.

Unfortunately, with the move to Zypper in #527, this broke for me. For this and other reasons, I've filed https://github.com/uyuni-project/uyuni-rfc/pull/4 to propose moving from Zypper to DNF to fix this.

**Comment by douglasawh** [comment]
@Conan-Kudo are there issues for the other pieces that need adapting other than DNF? I am going to be giving a presentation on Uyuni to a largely CentOS-oriented audience. I plan on pointing them to any issues. For now, it's just this one, I think, but it doesn't give much detail on what needs to happen, other than a PR that has already been merged. Thanks!

**Comment by Conan-Kudo** [comment]
Nope, that's pretty much it. It's the blocker for that and for getting Uyuni to run on CentOS.

**Comment by Conan-Kudo** [comment]
@douglasawh That's pretty much it. There's some code from Spacewalk that has made this change in git master that can be used as a reference for how to implement it for Uyuni, so it's just a matter of actually writing that code and switching Uyuni over to it. Such a switch won't break Uyuni on SUSE systems since DNF is available there too.

**Comment by mcalmer** [comment]
@douglasawh 
Well, I think in addition there is a lot of packaging work to be done. Especially when it comes to java packaging i can think of 2 ways - the easy way and the hard way.

In the easy way, you just take the java packages we provide for SUSE and re-build them for CentOS.
In the hard way, you try to build these packages in the Fedora/RedHat way which is different and maybe more time consuming.

Finally I would like to make a strong recommendation: when you have a working version of Uyuni on CentOS, please integrate it in our testsuite. If you do not do this, it will likely take only a few hours until somebody commit something which break it again.
Give others a chance to see their mistakes, provide an environment where it is easy to test on an OS they do not know and give them the chance to fix the problem.
If not, you will do it again and again.

**Comment by Conan-Kudo** [comment]
> Finally I would like to make a strong recommendation: when you have a working version of Uyuni on CentOS, please integrate it in our testsuite. If you do not do this, it will likely take only a few hours until somebody commit something which break it again.

There is literally no way I'm going to do this _without_ getting it integrated into the test apparatus. I don't want it to break all the time, either. I want CentOS/Fedora to be a fully supported server option for Uyuni.

**Comment by astauntonie** [comment]
@Conan-Kudo - I just stumbled across this issue now I wondered if I may be of help. I have no idea how the packages are currently built but have created rpm's using gradle and maven in the past and I am also looking to implement Uyuni on a CentOS 7 server.

**Comment by Conan-Kudo** [comment]
I'm hoping to spend some time next week on making some basic patches to Uyuni to fix this, we'll see how that goes. 😉 

Mostly what would be helpful would be members joining the Fedora Java SIG and helping to add and support Java software packages there. https://fedoraproject.org/wiki/SIGs/Java

**Comment by astauntonie** [comment]
anything in particular, for Uyuni, that need packaging? (better to start with something that is needed than focus on adding java libraries that are not relevant :))

**Comment by mattboston** [comment]
@Conan-Kudo were you able to get Uyuni Server to install on CentOS?  Do you have steps you used?  I'd be interested in helping too.

**Comment by sbluhm** [comment]
@mattboston, @astauntonie  Check the instructions here: [https://www.bluhm-de.com/content/os-tools/en/applications/uyuni/installing-uyuni-on-centos-8.html](https://www.bluhm-de.com/content/os-tools/en/applications/uyuni/installing-uyuni-on-centos-8.html)
You can help by:
- fixing open issues with the tag "centos8 port",
- testing and fixing,
- raising new issues,
- porting packages from [home:sbluhm:systemsmanagement:Uyuni:Other:EL8](https://build.opensuse.org/project/monitor/home:sbluhm:systemsmanagement:Uyuni:Other:EL8) to the [OBS Master:Other](https://build.opensuse.org/project/show/systemsmanagement:Uyuni:Master)

Working: Installation, reposync
To be tested: everything, especially client registration, then configuration management and seeing if the client status updates. Pretty much everything that is also important to you.
Not working: kickstart via cobbler, [my issue list](https://github.com/sbluhm/uyuni/issues)

Salt related features are not looked at yet so they might work somewhat or not at all.

**Comment by sbluhm** [comment]
I found this thread a bit too late...
What do we do about [uyuni-project/uyuni-rfc/#4](https://github.com/uyuni-project/uyuni-rfc/pull/4) ?
What are the closure criteria for this ticket? The headline issue is solved by #3136 .

**Comment by Conan-Kudo** [comment]
@sbluhm It's very minor work on top of yours to complete the implementation of that RFC. I'll take a look at finishing things off for that in the coming weeks.

**Comment by sbluhm** [comment]
@Conan-Kudo , what needs to be implemented? Maybe I can assist.

**Comment by Conan-Kudo** [comment]
I think this is mostly done now. At this point, the only thing left is to make it possible to use DNF on openSUSE when DNF is available while allowing Zypp to be used when it isn't.

**Comment by sbluhm** [comment]
Whilst doing some house keeping, I noticed that I have a change that uses dnf over zypper when available on the server. Is this (still) wanted? If yes, I would submit it.
@mcalmer / @juliogonzalez

**Comment by juliogonzalez** [comment]
Closing then :-)
