### ISSUE TITLE
two system entries for containerized proxy

### ISSUE THREAD

**Issue by jmozd** [uyuni-project/uyuni#8053]
# Question

We've made our first steps transitioning from classic Proxies (Salt-based Linux system with installed & configured proxy packages) to containerized proxies.

We installed a Leap 15.4 host, registered it as a Salt minion to our SUSE Manager and then created a Proxy configuration via spacecmd. After transferring the configuration to the Leap host and starting the systemd service unit, the Proxy became operational and we could successfully change the connection path of a test client to point to that (containerized) proxy. Tests on the client (Salt, fetching packages and updates) were successful. When checking SUSE Manager, the proxy was known, albeit as an "External"-type system.

Today we were pointed at the fact that the SUSE Manager has *two* entries for the new proxy - one with system type "Salt" (which seems to be the "host", reporting all hardware etc correctly) and the "external" system, the latter being the Proxy, according to the SUSE Manager.

When looking around, we also noticed that when trying to change the connection path of systems, we're no longer presented with *any* Proxy - there simply is no selection box anymore in /rhn/systems/details/Connection.do?sid=....

Something worth mentioning is that the Linux host running the container is known by the same hostname and DNS name as the "Proxy" (in fact, it was a classic system, before deleting it from SUSE Manager and re-installing it as a container proxy host).

I checked the docs, but found no mentioning of what to expect with regards to SUSE Manager system entries for containerized Proxies. Should we see only a single entry, or are the two entries expected?

## Version of Uyuni Server and Proxy (if used)

SUSE Manager 4.3.10

containerized proxy:
registry.suse.com/suse/manager/4.3/proxy-salt-broker:latest
registry.suse.com/suse/manager/4.3/proxy-tftpd:latest
registry.suse.com/suse/manager/4.3/proxy-squid:latest
registry.suse.com/suse/manager/4.3/proxy-httpd:latest
registry.suse.com/suse/manager/4.3/proxy-ssh:latest

registry.suse.com/suse/manager/4.3/proxy-httpd        latest            298b90834557  3 days ago  250 MB
registry.suse.com/suse/manager/4.3/proxy-salt-broker  latest            b74b6ecaedfb  3 days ago  174 MB
registry.suse.com/suse/manager/4.3/proxy-tftpd        latest            d23923a0ef11  3 days ago  188 MB
registry.suse.com/suse/manager/4.3/proxy-squid        latest            655029f5a925  4 days ago  185 MB
registry.suse.com/suse/manager/4.3/proxy-ssh          latest            6d4e0c78a314  4 days ago  177 MB

**Comment by rjmateus** [comment]
We would need to know the uyuni version where this is happening.

**Comment by jmozd** [comment]
it was "latest" as of two weeks ago, hence the container mage ids in the version report above. If you need a specific other information, please let me know.

The server is a SUSE Manager Server, v4.3.10 (also mentioned above).

**Comment by jmozd** [comment]
Per information received from developers & fellow Uyuni (power) users:

- having two entries in the Manager (one for the container host, typee "salt"; one for the Proxy instance, type "foreign" is expected and working as designed

- using the same name for the container host and the Proxy instance is not causing harm, but likely confusing. I do recommend to use separate names (and when it comes to K8s instances, the "container hosts" will be completely different anyhow)

- not seeing any Proxy entries when trying to switch a minion client via Manager web UI (system - connection - change - "new proxy") was likely a glitch that resovled itself. Current tests no longer show this behaviour, the Proxies are correctly listed and selectable.

So other than the suggestion to add the information on the "system type: foreign" entry to the documentation on containerized Proxies, everything turned out fine, and my questions were answered.

Thank you all involved!
