### ISSUE TITLE
Content Lifecycle Management do not present module packages as regular packages anymore...

### ISSUE THREAD

**Issue by marmau06** [uyuni-project/uyuni#8086]
### Problem description

CLM are supposed to allow access to packages included in modules (RHEL8, RHEL9), outside of appstreams and module stuff. It seemd to work. Now, Uyuni 2023-10 does this:

on uyuni gui, a RHEL8 server, attached to a CLM, indicates that it has some package selected for upgrade.
For example:
![image](https://github.com/uyuni-project/uyuni/assets/96834047/44bc2783-e706-4565-a87f-ad8855c75160)

This package "perl-Carp" is available in and out of CLM's:

![image](https://github.com/uyuni-project/uyuni/assets/96834047/c1e6ff05-0623-4a71-92af-50b333e8392f)

But on server side, when we try to update, it seems that last vesion of package is masked:

![image](https://github.com/uyuni-project/uyuni/assets/96834047/48eda5e2-afd1-40d3-9c25-3d07c73db6ac)

![image](https://github.com/uyuni-project/uyuni/assets/96834047/cbffa3a8-2f84-413c-b4c6-660f40abd9d2)

Any new settings to introduce ?

Thanks, and happy new year !

### Steps to reproduce

1.
2.
3.
...
Described in object

### Uyuni version

```bash
Informations sur paquet Uyuni-Server-release :
----------------------------------------------
Dépôt                     : Uyuni Server Stable
Nom                       : Uyuni-Server-release
Version                   : 2023.10-230900.209.1.uyuni3
Architecture              : x86_64
Fabricant                 : obs://build.opensuse.org/systemsmanagement:Uyuni
Niveau de support         : Niveau 3
Taille une fois installé  : 1,4 KiB
Installé                  : Oui (automatiquement)
État                      : pas à jour (version 2023.09-230900.207.8.uyuni3 installée)
Paquet source             : Uyuni-Server-release-2023.10-230900.209.1.uyuni3.src
Résumé                    : Uyuni Server
Description               : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
None
```

**Comment by avshiliaev** [comment]
Hey @marmau06 
thanks for the report. Does this issue seem relevant to your problem? 
* https://github.com/uyuni-project/uyuni/issues/7618

**Comment by ZsBT** [comment]
> Hey @marmau06 thanks for the report. Does this issue seem relevant to your problem?
> 
> * [RHEL 8 Appstream Modules Issues #7618](https://github.com/uyuni-project/uyuni/issues/7618)

Seems to be the same as #7618 , Almalinux 8 is affected as well.

**Comment by avshiliaev** [comment]
Alright, closing in favor of the https://github.com/uyuni-project/uyuni/issues/7618
