### ISSUE TITLE
unable to registered rhel7 with uyuni webui 

### ISSUE THREAD

**Issue by FurqanBuksh** [uyuni-project/uyuni#8095]
### Problem description

currently i am using opensuse 15.5 with uyuni latest. I am unable to register rhel7 with Uyuni webui and I am using CDN to register redhat 7

mgr-bootstrap-repo -l 
no product available 

I have added rhel7 pool channel using the following command 
spacewalk-common-channel -a x86_64  rhel7-pool-Uyuni

I have already followed the documentation of Uyuni but I am unable to register the client from Webui directly so I have manually installed all the dependencies in the Redhat client and then registered the client using Push via Salt SSH method.

Can anyone help me out by providing the details.

### Steps to reproduce

1.Redhat client registration details needed
2.
3.
...

### Uyuni version

```bash
latest
```

### Uyuni proxy version (if used)

```bash
no
```

### Useful logs

```bash
mgr-bootstrap-repo -l 
no product available
```

**Comment by avshiliaev** [comment]
Hey @FurqanBuksh 
have you followed [this docs page here](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-rh-cdn.html)? 
Have you also added the tools channel as written [in this section](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-rh-cdn.html#_add_software_channels)?

**Comment by FurqanBuksh** [comment]
Hi

Yes I have followed all the instructions that are mentioned in
documentation the only thing when I use bootstrapping from uyuni gui it's
unable to registered redhat client but when I installed all the packages
manually on client and then registered client with salt option it's working
fine. Please share any solution to resolve the issue.

**Comment by avshiliaev** [comment]
Alright, do you have anything related to the issue in the logs?

`/var/log/rhn/rhn_web_ui.log`
`/var/log/rhn/rhn_taskomatic_daemon.log`
`/var/log/salt/`

**Comment by avshiliaev** [comment]
Stale for now, feel free to reopen
