### ISSUE TITLE
Apply state failed with rocky 9 registering on a EPEL 9 channel (salt minion client)  

### ISSUE THREAD

**Issue by teonitro** [uyuni-project/uyuni#8140]
### Problem description

Hello, 

When a Rocky9 client is registering on Uyuni 2023.12 server with Rocky 9 and EPEL 9 channels, the apply state failed with following error : 

----------
          ID: https_//download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    Function: mgrcompat.run
        Name: pkg.add_repo_key
      Result: false
     Comment: Module function pkg.add_repo_key threw an exception. Exception: Error: [Errno -2] Name or service not known reading /pub/epel/RPM-GPG-KEY-EPEL-9
     Started: 14:20:42.327781
    Duration: 4913.19
         SLS: channels.gpg-keys
     Changed: {}
----------

on client logs in /var/log/message : 

----------
Jan 11 13:20:41 localhost salt-minion[207836]: /usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/x509.py:212: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
Jan 11 13:20:41 localhost salt-minion[207836]:  salt.utils.versions.warn_until(
Jan 11 13:20:42 localhost salt-minion[207836]: /usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/ext/tornado/netutil.py:493: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
Jan 11 13:20:42 localhost salt-minion[207836]:  context = ssl.SSLContext(
Jan 11 13:20:47 localhost salt-minion[207836]: [ERROR   ] Module function pkg.add_repo_key threw an exception. Exception: Error: [Errno -2] Name or service not known reading /pub/epel/RPM-GPG-KEY-EPEL-9
Jan 11 13:20:48 localhost salt-minion[207836]: /usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/x509.py:212: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
Jan 11 13:20:48 localhost salt-minion[207836]:  salt.utils.versions.warn_until(
Jan 11 13:20:57 localhost salt-minion[208289]: /usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/x509.py:212: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
Jan 11 13:20:57 localhost salt-minion[208289]:  salt.utils.versions.warn_until(
Jan 11 13:20:57 localhost salt-minion[208289]: /usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/ext/tornado/netutil.py:493: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
Jan 11 13:20:57 localhost salt-minion[208289]:  context = ssl.SSLContext(
Jan 11 13:21:02 localhost salt-minion[208988]: /usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/x509.py:212: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
Jan 11 13:21:02 localhost salt-minion[208988]:  salt.utils.versions.warn_until(
Jan 11 13:21:40 localhost salt-minion[209433]: /usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/x509.py:212: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
Jan 11 13:21:40 localhost salt-minion[209433]:  salt.utils.versions.warn_until(
----------

### Steps to reproduce

1.install uyuni 2023.12 or upgrade from 2023.09
2.register client rocky 9 with salt client using EPEL9 channel like below : 
![image](https://github.com/uyuni-project/uyuni/assets/24687391/7eb0eb1d-7db5-4ab2-bf46-e64520cbd5d7)

3.after registering on the client check events for apply state 
![image](https://github.com/uyuni-project/uyuni/assets/24687391/d1a95453-b7b5-45c6-ad1d-833ced314b84)
4. After manual apply highstate we have the same result 
![image](https://github.com/uyuni-project/uyuni/assets/24687391/839033d6-d4ad-4f23-a0b2-cd9b816235bf)

### Uyuni version

```bash
uyuni 2023.12-230900 on server
venv-salt-minion-3006.0-22.1.uyuni.x86_64 on client
```

**Comment by teonitro** [comment]
hello @avshiliaev 

i can resolve without problem the host download.fedoraproject.org 
```
[root@vlb-supinflux-p01 yum.repos.d]# host download.fedoraproject.org
download.fedoraproject.org is an alias for wildcard.fedoraproject.org.
wildcard.fedoraproject.org has address 18.192.40.85
wildcard.fedoraproject.org has address 18.159.254.57
wildcard.fedoraproject.org has address 38.145.60.20
wildcard.fedoraproject.org has address 85.236.55.6
wildcard.fedoraproject.org has address 185.141.165.254
wildcard.fedoraproject.org has address 18.133.140.134
wildcard.fedoraproject.org has address 38.145.60.21
wildcard.fedoraproject.org has address 152.19.134.198
wildcard.fedoraproject.org has address 152.19.134.142
wildcard.fedoraproject.org has IPv6 address 2604:1580:fe00:0:dead:beef:cafe:fed1
wildcard.fedoraproject.org has IPv6 address 2605:bc80:3010:600:dead:beef:cafe:fed9
wildcard.fedoraproject.org has IPv6 address 2001:4178:2:1269::fed2
wildcard.fedoraproject.org has IPv6 address 2a05:d01c:c6a:cc01:269:da52:9ae1:43e6
wildcard.fedoraproject.org has IPv6 address 2a05:d014:10:7803:f774:4d7c:e277:a457
wildcard.fedoraproject.org has IPv6 address 2600:2701:4000:5211:dead:beef:fe:fed3
[root@vlb-supinflux-p01 yum.repos.d]#
```

**Comment by teonitro** [comment]
i think there is a issue in fedora web site : 
```
[root@vlb-supinflux-p01 ~]# curl -O https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[root@vlb-supinflux-p01 ~]# ll
total 8
-rw-r--r--. 1 root root    0 Jan 16 18:08 RPM-GPG-KEY-EPEL-9
-rw-------. 1 root root 5936 May 13  2023 original-ks.cfg
[root@vlb-supinflux-p01 ~]#
```
the file RPM-GPG-KEY-EPEL-9 is empty

**Comment by teonitro** [comment]
I have change in the channel with our local EPEL repository and now i have no issue to get the certificate. 

i note with the curl with fedora url that we have a 302 redirection : 
```
HTTP/2 302
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: same-origin
location: https://mirrors.ukfast.co.uk/sites/dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
content-type: text/plain
content-length: 0
date: Tue, 16 Jan 2024 17:27:56 GMT
apptime: D=10560
x-fedora-proxyserver: proxy01.iad2.fedoraproject.org
x-fedora-requestid: Zaa8nE3XRSR3CB9nU9GdIQAESQc
server: Apache
```

Can minion client follow the 302 HTTP redirection ? 

also if i use -L in curl, we have the certificate : 
[root@vlb-supinflux-p01 ~]# curl -L https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9 --output RPM-GPG-KEY-EPEL-9
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1656  100  1656    0     0   5538      0 --:--:-- --:--:-- --:--:--  5538
[root@vlb-supinflux-p01 ~]# ll
total 12
-rw-r--r--. 1 root root 1656 Jan 16 18:30 RPM-GPG-KEY-EPEL-9
-rw-------. 1 root root 5936 May 13  2023 original-ks.cfg
[root@vlb-supinflux-p01 ~]# vi RPM-GPG-KEY-EPEL-9
[root@vlb-supinflux-p01 ~]#

**Comment by meaksh** [comment]
Is the "state.apply" already failing today? I was able to successfully apply the `pkg.add_repo_key` state for this EPEL9 repo in my Rocky Linux 9. No issues found even if I get a 302 redirections.

The initial error sounds definetely as there was some hickup in the network or with EPEL9 repository mirrors:

```
Exception: Error: [Errno -2] Name or service not known reading /pub/epel/RPM-GPG-KEY-EPEL-9
```

I did some tests against EPEL9 repo and I'm getting ramdom stuck requests when doing:

```console
[root@rocky9 ~]# for i in $(seq 30); do curl -vvv https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9; done
```

So this smells to some problem on EPEL9 repo mirror, and not really an Uyuni issue.

If your state failing all the times you try to apply it?

**Comment by teonitro** [comment]
now the highapply state return no issue with https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
![image](https://github.com/uyuni-project/uyuni/assets/24687391/550b2e82-321d-4510-a797-de99ed8ae373)

Probably the issue is localized on Fedora Mirrors

But a multiple retry when this issue occurs in Minion client (for example 5 times) could resolve this issue ?
