### ISSUE TITLE
Create new API endpoint getRelevantErrata that takes an array of sid as parameter

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni#8183]
# Short description

Create a new endpoint like
https://www.uyuni-project.org/uyuni-docs-api/uyuni/api/system.html#apidoc-system-getRelevantErrata-loggedInUser-sid
but instead of take just a sid as parameter, user can provide an array of sid.

**Comment by HoussemNasri** [comment]
@mbussolotto I think this should be closed now that #8203 is merged?
