### ISSUE TITLE
product migration from SLES-SAP15 SP4 to SP5 is not available

### ISSUE THREAD

**Issue by jawahk** [uyuni-project/uyuni#8296]
### Problem description

we tried to upgrade service pack on suse sap15 sp4 to sp5 but on uyuni we are not able to find the option. 

### Steps to reproduce

on board SAP variant SUSE and check on product miration
cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
VARIANT_ID="sles-sap"
root@gplvdbabd:~#

![image](https://github.com/uyuni-project/uyuni/assets/145043441/55a884c6-484f-441c-8383-7ebd7a7d536a)

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.09-230900.207.8.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2023.04-220400.204.2.uyuni2 installed)
Source package : Uyuni-Server-release-2023.09-230900.207.8.uyuni3.src
Summary        : Uyuni Server
```

**Comment by jawahk** [comment]
its not helping , any other option apart from this , because the regular SLES version is working fine but i am facing issues only with SAP variant .
on board SAP variant SUSE and check on product miration
cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
VARIANT_ID="sles-sap"

**Comment by mayrstefan** [comment]
The SUSE channels usually come with a release package that gets installed for this "product" when you assign the channels. As long as those incompatible  products are installed the SP migration is also blocked

**Comment by mayrstefan** [comment]
Examples for such packages
- sle-ha-release from SUSE Linux Enterprise High Availability Extension
- sle-module-sap-applications-release from SAP Applications Module
- sle-module-server-applications-release from Server Applications Module
- sles-release from SUSE Linux Enterprise Server

and so on.

You should find them with `rpm -qa | grep "sle.*-release" | sort`. I'm not 100% sure if this pattern applies to all of those packages. When you uninstall such a package you need to do a package refresh in Uyuni before you can try a SP migration.

**Comment by mcalmer** [comment]
Maybe you can update uyuni to 2024.02. It has some logging added in this case.
Try to reproduce it and check the rhn_web_ui.log if it give you a hint why it does not show a migration target

**Comment by EthanB11** [comment]
I remember running into this issue myself with SLES for SAP. I'm pretty sure I ended up removing a channel from my lifecycle that is no longer included and that resolved it.

**Comment by mcalmer** [comment]
no response anymore so I think it is working now
