### ISSUE TITLE
Unable re-add packages after repo re-create

### ISSUE THREAD

**Issue by krakazyabra** [uyuni-project/uyuni#8320]
### Problem description

Cannot sync repos after deletion and re-creation of repo

### Steps to reproduce

1. Create repo
2. Create channel
3. Add repo to channel
4. Sync repo (At this step Uyuni will add packages info to DB)
5. Delete repo
6. Delete channel
7. Delete all packages (after this step you will be unable too see packages in WebUI)
8. Run cleaning
```
spacewalk-data-fsck -r -S -C -O
```
9. Create same repo again
10. Create channel
11. Add repo to channel
12. Sync repo

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.01-230900.212.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.01-230900.212.1.uyuni3.src
Summary        : Uyuni Server
Description    :
```

### Useful logs

```bash
18:06:39 ======================================
18:06:39 | Channel: ubuntu-22-04-main-repo
18:06:39 ======================================
18:06:39 Sync of channel started.
18:06:42 Repo URL: http://archive.ubuntu.com/ubuntu/dists/jammy/main/binary-amd64/
18:06:42     Packages in repo:              6090
18:06:42     No new packages to sync.
18:06:42 Filtering packages that failed to download
18:06:42
18:06:42   Importing packages to DB:
18:06:42
18:06:42   Patches in repo: 0.
18:06:42 Sync completed.
```
```


### Additional information

I expected that Uyuni will clean all info about all packages from removed repos and then scan and add packages again. 
But nothing happens instead.

**Comment by cFabij** [comment]
Your log indicates that the sync worked but there were no new packages to sync and thus nothing to do. I assume something about your deletion process went wrong (but from your description I cannot pinpoint what exactly went wrong).

You could to different checks to confirm that /var/spacewalk (this is where packages get synced) still uses a lot of space even after your deletion process.

I use `spacewalk-remove-channel -a <parent channel>` to delete channels and it works as expected (see https://www.uyuni-project.org/uyuni-docs/en/uyuni/common-workflows/workflow-removing-channel.html#removing-channel). Possibly you have to delete repositories by hand via web UI afterwards.

**Comment by krakazyabra** [comment]
Hello. I reinstalled Uyuni-server from scratch :)

**Comment by krakazyabra** [comment]
Hello Artem. Yes, that was test installation without any active target systems. 
That's true, I've removed repo first.

**Comment by krakazyabra** [comment]
I think we can close this repo, cos after another installation I could not reproduce this error anymore..
