### ISSUE TITLE
CurveZMQ support 

### ISSUE THREAD

**Issue by werwaznadn** [uyuni-project/uyuni#8447]
# Question

Does uyuni support CurveZMQ protocol? 

If not -  is there any specific reason why?
If yes - from which version of uyuni? Where can I find some details about it?

**Comment by admd** [comment]
Hey @werwaznadn Uyuni uses salt which uses zeromq underneath. I am not sure if salt make use of CurveZMQ or if they have their own security layer.  So the actual question would be if salt make use of CurveZMQ.

@meaksh @agraul any input here on this one?

**Comment by meaksh** [comment]
Salt does not use CurveZMQ, but implements its own Security layer on top of ZeroMQ, using crypto libraries.

I see back in the early Salt days, there was a discussion upstream about this: https://github.com/saltstack/salt/issues/5913

Hth!
