### ISSUE TITLE
cannot bootstrap more clients but one

### ISSUE THREAD

**Issue by curinos2023** [uyuni-project/uyuni#8449]
### Problem description

I cannot bootstrap one more clients that created from the same template(image)
First, i create multiple VMs from the same template image, there is no problem to bootstrap one VM client. after that other VM clients
will not be listed at system list even though the WEB UI says i have bootstrap successfully.

### Steps to reproduce

version 2024.02

### Uyuni version

```bash
2024.02
```

### Useful logs

```bash
==> rhn_web_ui.log <==
2024-03-13 06:23:21,049 [ajp-nio-127.0.0.1-8009-exec-3] WARN  com.suse.manager.reactor.messaging.RegisterMinionEventMessageAction - Minion 'dc-dlb01' already registered, updating profile to 'dc-dlb02' [bcab8c57099b4afaaac385027d0de7f7]

2 servers are complately different IP, dns but were created from same template.
```

**Comment by gabjef** [comment]
@curinos2023 This could be your issue: [Troubleshooting Registering Cloned Clients](https://uyuni-linux-mgmt.tierpoint.com/docs/en/uyuni/administration/troubleshooting/tshoot-registerclones.html)

**Comment by avshiliaev** [comment]
Seems to be solved for now, please feel free to reopen if the problem reappears :smiley:
