### ISSUE TITLE
Uyuni don't show patch for Ubuntu client

### ISSUE THREAD

**Issue by akupreev** [uyuni-project/uyuni#8480]
### Problem description

When I try to see what patches I have on my system, I see zero results.
![image](https://github.com/uyuni-project/uyuni/assets/81261370/10d84828-e9d5-4e8f-98fc-08c6c1c2b13c)

CVE audit also stopped working:
![image](https://github.com/uyuni-project/uyuni/assets/81261370/e35fc759-ceba-45a3-9337-10cf67ae4c4a)

Client virtual machines are connected as salt minion and manage system completely via SSH (will not install an agent)
About a couple of versions ago, everything worked stably. Tell me, what could be the problem, what should I pay attention to?

### Steps to reproduce

1. 
2.
3.
...

### Uyuni version

```bash
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.02-230900.213.1.uyuni3
Arch           : x86_64
```

### Uyuni proxy version (if used)

```bash
No used
```

### Useful logs

```bash
no
```

### Additional information

How can I get information about system vulnerabilities and fix them?

Previously this functionality worked without problems.

**Comment by mcalmer** [comment]
I think this is a duplicate of https://github.com/uyuni-project/uyuni/issues/8134
This should be fixed in the next Uyuni release

**Comment by akupreev** [comment]
Thanks for your reply. We are waiting for a new release
