### ISSUE TITLE
"mgrpxy install kubernetes" assumes being run from Kubernetes cluster node, fails on non-cluster node

### ISSUE THREAD

**Issue by jmozd** [uyuni-project/uyuni#8507]
# Short description
Trying to install Uyuni proxy on a Kubernetes (RKE / K3s) cluster fails if running the installer command from a non-cluster node, despite having a functional KUBECONFIG setup.

# Details
Infrastructure information:
- one Rancher server
- multiple Kubernetes clusters (RKE-, K3s-based) managed via Rancher
- in addition to Rancher Server WebUI, there's a "Linux admin node" with KUBECONFIG setups to be able to use CLI tools to access any of the clusters

Steps to install:
- provide "mgrpxy" command for the Linux admin node.
- "kubectl get nodes" reports all nodes of the target cluster (any other kubectl call will work towards that cluster, too)
- tried to install uyuni-proxy via  [the command given for the K3s installation](https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/proxy-container-k3s-installation.html):

```
rancheradm@rancher-admin:~/clusters/rancher.customer.com/kube> mgrpxy install kubernetes ~/uyuniproxy.config.5-0-0.tar.gz --logLevel=debug
7:09PM INF mgrpxy/cmd/cmd.go:40 > Welcome to mgrpxy
7:09PM INF mgrpxy/cmd/cmd.go:41 > Executing command: kubernetes
7:09PM DBG shared/utils/tar.go:61 > Extracting file /tmp/mgrpxy-1922755939/config.yaml
7:09PM DBG shared/utils/tar.go:61 > Extracting file /tmp/mgrpxy-1922755939/httpd.yaml
7:09PM DBG shared/utils/tar.go:61 > Extracting file /tmp/mgrpxy-1922755939/ssh.yaml
7:09PM DBG shared/utils/exec.go:49 > Running: kubectl get node -o jsonpath={.status.nodeInfo.kubeletVersion} rancher-admin
7:09PM DBG shared/utils/exec.go:49 > Running: kubectl get node -o jsonpath={.status.nodeInfo.kubeletVersion} rancher-admin
7:09PM FTL shared/kubernetes/kubernetes.go:54 > Failed to get kubelet version for node rancher-admin error="exit status 1"
rancheradm@rancher-admin:~/clusters/rancher.customer.com/kube>
```
As you can see from the debug, mgrpry assumes the local host to be a member of the cluster (to be fair, the docs start with the installation of K3s on "the container host machine" and never changes away from that host). But as the Kubernetes environment is a multi-node cluster, a better approach could be to only rely on having the proper KUBECONFIG setup, running mgrpxy from any machine with such KUBECONFIG.

**Comment by mbussolotto** [comment]
@cbosdo

**Comment by mbussolotto** [comment]
I saw some discussion about this issue here: https://github.com/uyuni-project/uyuni/issues/8258 . IIUC this issue can be closed, right?

**Comment by cbosdo** [comment]
Fixed with https://github.com/uyuni-project/uyuni-tools/pull/213
