### ISSUE TITLE
Unable to bootstrap 

### ISSUE THREAD

**Issue by rakeshsujan** [uyuni-project/uyuni#8547]
Hello,

When adding a new Linux machine it gives a below error. 

![image](https://github.com/uyuni-project/uyuni/assets/50227412/4968e56b-7b5e-48f2-9f20-65e8b43cccbd)

![image](https://github.com/uyuni-project/uyuni/assets/50227412/cbeb8d98-438f-40a2-8b77-dc9141dcf0ad)

**Comment by cFabij** [comment]
Hi!

Could you add some more information?

1. Which distribution are you trying to onboard?
2. How is your activation key setup?

**Comment by cFabij** [comment]
Okay, thank you!

Maybe check this out first: https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/troubleshooting/tshoot-mounting-tmp-with-noexec.html

Some more questions:

1. Is the correct Base Channel and all necessary child channels linked in this activation key? (see the necessary channels here: https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-rocky.html)
2. Have all Rocky channels finished syncing before you tried to onboard?
- check first if `mgr-create-bootstrap-repo -l` lists Rocky Linux 9
- if not check `/var/log/rhn/reposync/rockylinux9-uyuni-client.log` for the last messages

**Comment by rakeshsujan** [comment]
@cFabij 

The client-server /var FS was mounted with noexec permission after changing the permission to exec I can able to bootstrapping the client-servers.

Thanks for your support.
