### ISSUE TITLE
About > API section links are broken

### ISSUE THREAD

**Issue by bisht-richa** [uyuni-project/uyuni#8574]
### Problem description

From the login page when you navigate to `About > API`, it shows a `Page Not Found` error. 

### Steps to reproduce

From the login page :
1. Click on the `About` link  
2. Got to API sub-section
3. All the sections under `API` show the same error.

**API Overview page**

<img width="1919" alt="Screenshot 2024-04-08 at 17 07 06" src="https://github.com/uyuni-project/uyuni/assets/18264463/6045472a-4771-4b4d-ba54-0bcd60f04959">

**API > FAQ page**

<img width="1918" alt="Screenshot 2024-04-08 at 17 09 00" src="https://github.com/uyuni-project/uyuni/assets/18264463/cb5206ac-fa73-452b-8398-5373d1057385">

### Uyuni version

```bash
2024.02
```

**Comment by cFabij** [comment]
I cannot replicate this issue.

It works fine on my 2024.02 version.

You could check the files in `/usr/share/susemanager/www` (API documents are found in tomcat folder). Maybe the installation was incomplete?

**Comment by avshiliaev** [comment]
Closing as stale. Please feel free to reopen if the problem persists :smiley:
