### ISSUE TITLE
Uyuni does not sync patches from channels

### ISSUE THREAD

**Issue by akupreev** [uyuni-project/uyuni#8586]
### Problem description

Hi all.
Recently I noticed that the added virtual machines do not have security patches.
Until recently, I applied security patches to virtual machines of the Ubuntu 18/20/22 family without any problems. After looking at the logs /var/log/rhn/reposync/ubuntu-2004-amd64-main-security-uyuni.log, I noticed the entry Patches in repo: 0.
Help, how can I download patches for my channels?

### Steps to reproduce

1.
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.02-230900.213.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.02-230900.213.1.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
No used
```

### Additional information

NAME="openSUSE Leap"
VERSION="15.5"

**Comment by cFabij** [comment]
This should be fixed in the next release.

See: https://github.com/uyuni-project/uyuni/issues/8134

**Comment by akupreev** [comment]
> Это должно быть исправлено в следующем выпуске.
> 
> См.: [#8134.](https://github.com/uyuni-project/uyuni/issues/8134)

Thank you!
