### ISSUE TITLE
Import gpg key failed on uyuni container

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni#8633]
### Problem description

Import a gpg key using `mgradm` command when no suma key are present

Key is not imported. 

### Steps to reproduce

1. `mgradm gpg add https://download.videolan.org/pub/SuSE/Tumbleweed/repodata/repomd.xml.key --force`

### Uyuni version

```bash
2023.04
```

### Useful logs

```bash
`mgrctl exec systemctl status uyuni-update-config`


Apr 22 10:04:55 uyuni-server.mgr.internal uyuni-update-config[4319]: Skipping 'sync' as it was already executed on this container
Apr 22 10:04:55 uyuni-server.mgr.internal uyuni-update-config[4319]: Failed to import SUSE Manager Build Keys
Apr 22 10:04:55 uyuni-server.mgr.internal uyuni-update-config[4319]: importing SUSE Manager build key to rpm keyring... gpg: WARNING: nothing exported
Apr 22 10:04:55 uyuni-server.mgr.internal uyuni-update-config[4319]: gpg: no valid OpenPGP data found.
Apr 22 10:04:55 uyuni-server.mgr.internal uyuni-update-config[4319]: importing the key from the file /usr/lib/susemanager/susemanager-build-keys.gpg
Apr 22 10:04:55 uyuni-server.mgr.internal uyuni-update-config[4319]: returned an error. This should not happen. It may not be possible
Apr 22 10:04:55 uyuni-server.mgr.internal uyuni-update-config[4319]: to properly verify the authenticity of rpm packages from SUSE sources.
````
```


### Additional information

_No response_

**Comment by mbussolotto** [comment]
@mcalmer  This is the code that fails https://github.com/uyuni-project/uyuni/blob/adb79190318c5b0914d78a093304634d60c84b44/spacewalk/admin/import-suma-build-keys#L29-L42 and I assume it's right that /usr/lib/susemanager/susemanager-build-keys.gpg is missing in uyuni. I'm not sure if we should simply skip the check the return code of  SUSERING import, since it 's used also after in the code...any suggestion?

**Comment by mcalmer** [comment]
@mbussolotto hmm, that file might be named different.

```
$> rpm -qpl uyuni-build-keys-2024.01.1-230900.2.1.uyuni3.noarch.rpm
/usr/lib/uyuni
/usr/lib/uyuni/uyuni-build-keys.gpg
...
```

We need to handle this

**Comment by mbussolotto** [comment]
fixed
