### ISSUE TITLE
servers are failed to checkin with uyuni post 2 days

### ISSUE THREAD

**Issue by jawahk** [uyuni-project/uyuni#8645]
### Problem description

we have on-boarded AWS and ubuntu servers to uuyuni and added th4e required repo for the same but servers are failed to checking post 2 days automatically, need suggestions for the same. 

### Steps to reproduce

1.just and on-board and add the repo
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.09-230900.207.8.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2023.04-220400.204.2.uyuni2 installed)
Source package : Uyuni-Server-release-2023.09-230900.207.8.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by cFabij** [comment]
Your Uyuni version 2023.09 is very old.

I'd recommend first to update to the recent version. After that please post the `/var/log/venv-salt-minion` logs from the failed machines.

**Comment by jawahk** [comment]
hope this would help 

root@bpawsaigp08:/var/log# cat messages | grep salt
Apr 22 09:43:23 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:43:25 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/minor/3007.0.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:43:26 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum install salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:43:52 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl stop salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:43:52 bpawsaigp08 salt-minion: The Salt Minion is shutdown. Minion received a SIGTERM. Exited.
Apr 22 09:43:58 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum remove salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:00 bpawsaigp08 yum[3196]: Erased: salt-minion-3007.0-0.x86_64
Apr 22 09:44:02 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=rm -rf /etc/salt/ _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:03 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=sudo sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:04 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/3007.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:05 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum install salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:12 bpawsaigp08 yum[3475]: Installed: salt-minion-3007.0-0.x86_64
Apr 22 09:44:50 bpawsaigp08 ansible-ansible.legacy.stat: Invoked with path=/etc/salt/minion.d/uyuni.conf follow=False get_checksum=True checksum_algorithm=sha1 get_md5=False get_mime=True get_attributes=True
Apr 22 09:44:51 bpawsaigp08 ansible-ansible.legacy.copy: Invoked with src=/root/.ansible/tmp/ansible-tmp-1713779090.4094822-2112365-190201219797938/source dest=/etc/salt/minion.d/uyuni.conf _original_basename=uyuni.conf follow=False checksum=3ecbf9a3c520604390b6876a328e1f61b98f19e0 backup=False force=True unsafe_writes=False content=NOT_LOGGING_PARAMETER validate=None directory_mode=None remote_src=None local_follow=None mode=None owner=None group=None seuser=None serole=None selevel=None setype=None attributes=None
Apr 22 09:46:01 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl enable salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:46:03 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl start salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:46:24 bpawsaigp08 systemd: salt-minion.service: main process exited, code=exited, status=77/n/a
Apr 22 09:46:24 bpawsaigp08 systemd: Unit salt-minion.service entered failed state.
Apr 22 09:46:24 bpawsaigp08 systemd: salt-minion.service failed.
Apr 22 09:46:52 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl enable salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:46:52 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl start salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 23 11:48:22 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl stop salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 23 11:48:22 bpawsaigp08 salt-minion: The Salt Minion is shutdown. Minion received a SIGTERM. Exited.
Apr 23 11:48:27 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum remove salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 23 11:48:30 bpawsaigp08 yum[21707]: Erased: salt-minion-3007.0-0.x86_64
Apr 23 11:48:38 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=rm -rf /etc/salt/ _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 23 11:48:39 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=sudo sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 23 11:48:42 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/3007.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 23 11:48:50 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum install salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 23 11:48:53 bpawsaigp08 yum[22954]: Installed: salt-minion-3007.0-0.x86_64
Apr 23 11:51:32 bpawsaigp08 ansible-ansible.legacy.stat: Invoked with path=/etc/salt/minion.d/uyuni.conf follow=False get_checksum=True checksum_algorithm=sha1 get_md5=False get_mime=True get_attributes=True
Apr 23 11:51:33 bpawsaigp08 ansible-ansible.legacy.copy: Invoked with src=/root/.ansible/tmp/ansible-tmp-1713873091.6411636-3046636-185191758297053/source dest=/etc/salt/minion.d/uyuni.conf _original_basename=uyuni.conf follow=False checksum=3ecbf9a3c520604390b6876a328e1f61b98f19e0 backup=False force=True unsafe_writes=False content=NOT_LOGGING_PARAMETER validate=None directory_mode=None remote_src=None local_follow=None mode=None owner=None group=None seuser=None serole=None selevel=None setype=None attributes=None
Apr 23 11:52:21 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl enable salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 23 11:52:23 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl start salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
root@bpawsaigp08:/var/log# root@bpawsaigp08:/var/log# cat messages | grep salt
Apr 22 09:43:23 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:43:25 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/minor/3007.0.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:43:26 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum install salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:43:52 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl stop salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:43:52 bpawsaigp08 salt-minion: The Salt Minion is shutdown. Minion received a SIGTERM. Exited.
Apr 22 09:43:58 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum remove salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:00 bpawsaigp08 yum[3196]: Erased: salt-minion-3007.0-0.x86_64
Apr 22 09:44:02 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=rm -rf /etc/salt/ _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:03 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=sudo sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:04 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/3007.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Apr 22 09:44:05 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum install salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: root@bpawsaigp08:/var/log#: No such file or directory
Apr 22 09:44:12 bpawsaigp08 yum[3475]: Installed: salt-minion-3007.0-0.x86_64
Apr 22 09:44:50 bpawsaigp08 ansible-ansible.legacy.stat: Invoked with path=/etc/salt/minion.d/uyuni.conf follow=False get_checksum=True checksum_algorithm=sha1 get_md5=False get_mime=True get_attributes=True
Apr 22 09:44:51 bpawsaigp08 ansible-ansible.legacy.copy: Invoked with src=/root/.ansible/tmp/ansible-tmp-1713779090.4094822-2112365-190201219797938/source dest=/etc/salt/minion.d/uyuni.conf _original_basename=uyuni.conf follow=False checksum=3ecbf9a3c520604390b6876a328e1f61b98f19e0 backup=False force=True unsafe_writes=False content=NOT_LOGGING_PARAMETER validate=None directory_mode=None remote_src=None local_follow=None mode=None owner=None group=None seuser=None serole=None selevel=None setype=None attributes=None
Apr 22 09:46:01 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl enable salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
root@bpawsaigp08:/var/log# Apr 22 09:43:23 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:43:25 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/minor/3007.0.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
 -bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:43:26 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum install salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
22 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:43:52 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl stop salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:43:52 bpawsaigp08 salt-minion: The Salt Minion is shutdown. Minion received a SIGTERM. Exited.
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:43:58 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum remove salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:44:00 bpawsaigp08 yum[3196]: Erased: salt-minion-3007.0-0.x86_64
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:44:02 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=rm -rf /etc/salt/ _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:44:03 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=sudo sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:44:04 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/3007.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:44:05 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum install salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:44:12 bpawsaigp08 yum[3475]: Installed: salt-minion-3007.0-0.x86_64
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:44:50 bpawsaigp08 ansible-ansible.legacy.stat: Invoked with path=/etc/salt/minion.d/uyuni.conf follow=False get_checksum=True checksum_algorithm=sha1 get_md5=False get_mime=True get_attributes=True
le/tmp-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:44:51 bpawsaigp08 ansible-ansible.legacy.copy: Invoked with src=/root/.ansible/tmp/ansible-tmp-1713779090.4094822-2112365-190201219797938/source dest=/etc/salt/minion.d/uyuni.conf _original_basename=uyuni.conf follow=False checksum=3ecbf9a3c520604390b6876a328e1f61b98f19e0 backup=False force=True unsafe_writes=False content=NOT_LOGGING_PARAMETER validate=None directory_mode=None remote_src=None local_follow=None mode=None owner=None group=None seuser=None serole=None selevel=None setype=None attributes=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:46:01 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl enable salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:46:03 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl start salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:46:24 bpawsaigp08 systemd: salt-minion.service: main process exited, code=exited, status=77/n/a
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:46:24 bpawsaigp08 systemd: Unit salt-minion.service entered failed state.
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:46:24 bpawsaigp08 systemd: salt-minion.service failed.
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:46:52 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl enable salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 22 09:46:52 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl start salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:22 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl stop salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:22 bpawsaigp08 salt-minion: The Salt Minion is shutdown. Minion received a SIGTERM. Exited.
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:27 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum remove salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:30 bpawsaigp08 yum[21707]: Erased: salt-minion-3007.0-0.x86_64
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:38 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=rm -rf /etc/salt/ _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:39 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=sudo sudo rpm --import https://repo.saltproject.io/salt/py3/amazon/2/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:42 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=curl -fsSL https://repo.saltproject.io/salt/py3/amazon/2/x86_64/3007.repo | sudo tee /etc/yum.repos.d/salt-amzn.repo _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:50 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=yum install salt-minion -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:48:53 bpawsaigp08 yum[22954]: Installed: salt-minion-3007.0-0.x86_64
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:51:32 bpawsaigp08 ansible-ansible.legacy.stat: Invoked with path=/etc/salt/minion.d/uyuni.conf follow=False get_checksum=True checksum_algorithm=sha1 get_md5=False get_mime=True get_attributes=True
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:51:33 bpawsaigp08 ansible-ansible.legacy.copy: Invoked with src=/root/.ansible/tmp/ansible-tmp-1713873091.6411636-3046636-185191758297053/source dest=/etc/salt/minion.d/uyuni.conf _original_basename=uyuni.conf follow=False checksum=3ecbf9a3c520604390b6876a328e1f61b98f19e0 backup=False force=True unsafe_writes=False content=NOT_LOGGING_PARAMETER validate=None directory_mode=None remote_src=None local_follow=None mode=None owner=None group=None seuser=None serole=None selevel=None setype=None attributes=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:52:21 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl enable salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log# Apr 23 11:52:23 bpawsaigp08 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl start salt-minion _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
-bash: Apr: command not found
root@bpawsaigp08:/var/log#

**Comment by cFabij** [comment]
There is an Ansible script running (and failing). It does not install the "normal" venv-salt-minion package.

- How do you onboard the Uyuni clients?
- Why don't you use the bootstrap function in Uyuni web UI? (Via Systems > Bootstrapping)

**Comment by jawahk** [comment]
we are running ansible script to install salt and put the conf. file
also using below link to enable the repo for salt
https://docs.saltproject.io/
please help me where I can download the right package

**Comment by cFabij** [comment]
On Uyuni server you need to sync predefined channels, depending on the OS of your potential Uyuni clients: See https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-overview.html

By syncing these common channels Uyuni will create a bootstrap repository with the correct venv-salt-minion package for the respective OS.

After that you can onboard the Uyuni clients, either by using the web UI (https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-webui.html) or with the bootstrap script if you want to automate things (https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-bootstrap.html).

This ensures that the correct conf will be installed and the correct repositories will be linked (note: onboarding with bootstrap script requires manual adaptations).

**Comment by jawahk** [comment]
Hello @avshiliaev , 

thank you for the information, we are uyuni CLI method of on-boarding which is better for us on mass on-boarding by running the ansible script on multiple hosts. also we found that master has 3006 salt and we installed the same minion version and tested , still the issue is same , any suggestion , I am happy if you get on a call and discuss the same.

**Comment by mcalmer** [comment]
no response anymore since a long time. I assume the problems are solved. If there are still problems, please open a new issue and use an up to date software version of Uyuni. Than we can see if we can help.
