### ISSUE TITLE
Activation Key not changed by using "Software Migration" in UYUNI

### ISSUE THREAD

**Issue by Ripper66Six** [uyuni-project/uyuni#8682]
**# Current fact**
We offline upgrade Servers from SLES12 SP5 to SLES15 SP3. After the process we saw that the Activation Key will not be changed when the servers are bootstraped into UYUNI SLES15 SP3. After the bootstrap into UYUNI we use the function Software Migration to upgrade first to SLES15 SP4 and then to SP5.
In this case we found out that all servers we have bootstraped during using UYUNI was still left in the Activation Keys they got at the bootstrap process.

e.g.: on Activation Key SLES12-SP4 (Registered in January 2019) are registered 3 servers which are upgraded to SLES15-SP5 in the meantime.

After all we have no problems because all servers are set to the correct channels and configurations. Acoording the documentation of UYUNI the Activation Key are used to register systems. Systems registered with an activation key will inherit the characteristics defined by that key.

**# Question**
Is there any problem when we delete old Activation Keys when there are registered systems we have upgraded in the meantime?

## Version of Uyuni Server

zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.03-230900.214.6.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.03-230900.214.6.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Version of Uyuni Proxy

zypper info Uyuni-Proxy-release
Retrieving repository 'openSUSE-SLE-15.5-Updates for x86_64' metadata ................................................................................................................................................[done]
Building repository 'openSUSE-SLE-15.5-Updates for x86_64' cache .....................................................................................................................................................[done]
Loading repository data...
Reading installed packages...

Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.5 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2024.03-230900.214.6.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Proxy-release-2024.03-230900.214.6.uyuni3.src
Summary        : Uyuni Proxy
Description    :
    Uyuni Proxies extend large and/or geographically
    dispersed Uyuni environments to reduce load on the Uyuni
    Server, lower bandwidth needs, and provide faster local
    updates.

Thanks in advance and kind regards

**Comment by rjmateus** [comment]
The activation key is only used during the registration process. After that, the link to activation key is only informative, to know which one was used during bootstrap.
You can remove the activation key which will not have any impact on already registered minions. 
As you can see, this link can cause some misunderstanding when a system is upgraded to a newer OS version (or even SP)

**Comment by Ripper66Six** [comment]
Hello @rjmateus ,

many thanks for the answer :)

In this case we close this question.


Kind regards
