### ISSUE TITLE
Review and fix SSM subpages on the updated theme

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8726]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

We need to review https://localhost:8080/rhn/manager/systems/ssm and any subpages for visual inconsistencies on the updated theme.  There are many subpages with small layout bugs on the updated theme:  

<img width="516" alt="Screenshot 2024-05-15 at 15 17 32" src="https://github.com/uyuni-project/uyuni/assets/3171718/a115e3db-5965-4b6d-b969-a5628ef40e72">
<img width="676" alt="Screenshot 2024-05-15 at 15 17 36" src="https://github.com/uyuni-project/uyuni/assets/3171718/655b63e2-fcf4-4447-8abc-aba72940014a">
<img width="1275" alt="Screenshot 2024-05-15 at 15 17 45" src="https://github.com/uyuni-project/uyuni/assets/3171718/9f7fd32e-5b36-4052-b618-d07e11913ba2">
<img width="1255" alt="Screenshot 2024-05-15 at 15 17 52" src="https://github.com/uyuni-project/uyuni/assets/3171718/30e24c3d-be49-44bf-8422-d656decbdf55">

**Definition of done**

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8899
