### ISSUE TITLE
Missing icons on removable packages page

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8728]
See e.g. https://localhost:8080/rhn/systems/details/packages/PackageList.do?sid=1000010006&

<img width="797" alt="Screenshot 2024-05-15 at 15 30 26" src="https://github.com/uyuni-project/uyuni/assets/3171718/11ba67f7-e7aa-41b6-a33b-394a85cc782a">

**Comment by Etheryte** [comment]
The same issue is also present in https://localhost:8080/rhn/errata/RelevantErrata.do

**Comment by admd** [comment]
and here 
![image (12)](https://github.com/uyuni-project/uyuni/assets/12951268/80ee2d17-1740-4b52-8698-6d31894243a6)

**Comment by avshiliaev** [comment]
@Etheryte should be closed? :smiley:

**Comment by Etheryte** [comment]
Yes, ty for the heads up.
