### ISSUE TITLE
`btn-info` inconsistent between the new and the old theme

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8730]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

See e.g. https://localhost:8080/rhn/systems/details/kickstart/PowerManagement.do?sid=1000010006&

Old theme:

<img width="1104" alt="Screenshot 2024-05-15 at 15 36 42" src="https://github.com/uyuni-project/uyuni/assets/3171718/6577f2be-3f29-46fb-9e8b-977221393963">

New theme:

<img width="1090" alt="Screenshot 2024-05-15 at 15 36 47" src="https://github.com/uyuni-project/uyuni/assets/3171718/1c79a9d8-6667-48c8-b5b7-4ba7ec953cfa">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8907
