### ISSUE TITLE
Fix system highstate page layout

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8731]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

See e.g. https://localhost:8080/rhn/manager/systems/details/highstate?sid=1000010006&

For this page, it's hard to say whether the old page or new page should be the baseline for fixing as they're both a bit broken.  
I think it would be reasonable to just fix the page to a reasonably good state in the new theme, ignore the old theme part, and add the page to the updated page list.

<img width="1641" alt="Screenshot 2024-05-15 at 15 39 27" src="https://github.com/uyuni-project/uyuni/assets/3171718/f360185a-a8ce-494c-84d3-47a7e930400a">
<img width="1630" alt="Screenshot 2024-05-15 at 15 39 33" src="https://github.com/uyuni-project/uyuni/assets/3171718/db0b38d1-1ba2-4206-a138-a707cd062aa6">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8933
