### ISSUE TITLE
Clean up system formulas configuration layout

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8733]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

See e.g. https://localhost:8080/rhn/manager/systems/details/formulas?sid=1000010006&

The updated page has better contrast, while the layout on the old page is slightly different. It would be nice to find good middle ground and fix the layout up here.

<img width="1616" alt="Screenshot 2024-05-15 at 15 43 28" src="https://github.com/uyuni-project/uyuni/assets/3171718/1c0900a5-d382-4efa-9083-5577eee96653">
<img width="1619" alt="Screenshot 2024-05-15 at 15 43 35" src="https://github.com/uyuni-project/uyuni/assets/3171718/28d2842b-3a75-4e13-846e-863b590beef9">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8919
