### ISSUE TITLE
Make salt keys page consistent with other pages in the updated theme

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8734]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

Old theme:

<img width="1620" alt="Screenshot 2024-05-15 at 15 45 53" src="https://github.com/uyuni-project/uyuni/assets/3171718/2abc0faf-8f37-44f0-831a-1e6354c609ef">

New theme:

<img width="1648" alt="Screenshot 2024-05-15 at 15 45 59" src="https://github.com/uyuni-project/uyuni/assets/3171718/91bbe0b5-aa71-4808-a10b-813e24637c1c">

Imo the new theme is fine as-is, but we need to confirm that this change is fine.

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by Etheryte** [comment]
Cc @bisht-richa, this probably ties in with the work you're doing on standardizing checkboxes etc.

**Comment by Etheryte** [comment]
@admd is it fine if we drop the green badges in this list?

**Comment by admd** [comment]
@Etheryte I am not so sure about this one. Would we not end up with the a long list of pending/accepted with no badges and that could get bit tricky for the user to see. 

With clear color distinction for the accepted and pending keys, it was easy for the user to see. We don't have any filtering on the page either so having same color will not help. If we could add some filtering on this page for pending(default)/accepted keys, then we can get rid of these badges.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8936
