### ISSUE TITLE
Missing table or panel footer border in updated theme

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8737]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

See e.g. https://localhost:8080/rhn/manager/cm/imagestores

Old theme:

<img width="607" alt="Screenshot 2024-05-15 at 15 53 35" src="https://github.com/uyuni-project/uyuni/assets/3171718/c9e2b423-687a-4acc-a8a8-8a2e8071cd06">

New theme:

<img width="754" alt="Screenshot 2024-05-15 at 15 53 41" src="https://github.com/uyuni-project/uyuni/assets/3171718/c1f623e9-9bde-479c-8f55-441e5d18075e">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed:  #8925
