### ISSUE TITLE
Clean up advanced package search layout on the new theme

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8739]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

https://localhost:8080/rhn/errata/Search.do

Both the old theme and the new theme have some layout issues on this page, it would make most sense to fix it on the new one and add the page to the migration list.

Old theme:

<img width="1657" alt="Screenshot 2024-05-15 at 16 08 54" src="https://github.com/uyuni-project/uyuni/assets/3171718/65d1ebad-97a2-4a55-99c2-3c94b4b55e71">

New theme:

<img width="1630" alt="Screenshot 2024-05-15 at 16 09 00" src="https://github.com/uyuni-project/uyuni/assets/3171718/4c36aab7-60bc-498d-a6c5-ed6716a72ed0">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8956
