### ISSUE TITLE
Bugged input addon in package search

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8755]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

https://localhost:8080/rhn/channels/software/Search.do

This is actually bugged in both the old theme and the new one. It makes sense to just fix the new theme and add the page to the migration list.

<img width="1279" alt="Screenshot 2024-05-16 at 17 26 56" src="https://github.com/uyuni-project/uyuni/assets/3171718/9070f23d-7503-4a41-bcc3-08d4aeaf84de">
<img width="1279" alt="Screenshot 2024-05-16 at 17 27 02" src="https://github.com/uyuni-project/uyuni/assets/3171718/fd66bd47-1930-4b34-b9e3-f4bb37204a88">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by admd** [comment]
PR was merged! Closing the issue!
