### ISSUE TITLE
Missing margins in CVE audit

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8758]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

https://localhost:8080/rhn/manager/audit/cve

This page looks pretty okay otherwise, but some of the margins are missing so it ends up too cramped.

Old theme:

<img width="1115" alt="Screenshot 2024-05-16 at 17 42 29" src="https://github.com/uyuni-project/uyuni/assets/3171718/b6006f0b-f626-4cf0-8ec7-9040018b8f23">

New theme:

<img width="1169" alt="Screenshot 2024-05-16 at 17 42 34" src="https://github.com/uyuni-project/uyuni/assets/3171718/2cfb58a3-25d9-4431-acfd-1993eaec19a8">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8947
