### ISSUE TITLE
Broken form layout in OpenSCAP search

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8760]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

https://localhost:8080/rhn/audit/scap/Search.do

This page could use some love in both the old theme and the new, for now let's just fix the obvious broken parts and migrate the page.

<img width="1644" alt="Screenshot 2024-05-16 at 17 47 04" src="https://github.com/uyuni-project/uyuni/assets/3171718/ea9f4d27-fb97-4df5-ad84-5f7728145cdf">

<img width="1637" alt="Screenshot 2024-05-16 at 17 47 10" src="https://github.com/uyuni-project/uyuni/assets/3171718/c15ed468-b3d1-4c99-86c6-596f2557353d">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8960
