### ISSUE TITLE
Double padding in recurring actions

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8761]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

https://localhost:8080/rhn/manager/schedule/recurring-actions

This page has two panels unnecessarily wrapped in one another, honestly imo we can remove both of them and just make it a regular page with a table like many other such pages.

<img width="1681" alt="Screenshot 2024-05-16 at 17 50 14" src="https://github.com/uyuni-project/uyuni/assets/3171718/11543790-1805-421d-9479-3e9faed81262">
<img width="1664" alt="Screenshot 2024-05-16 at 17 50 19" src="https://github.com/uyuni-project/uyuni/assets/3171718/472ed212-e853-49b0-9f3c-58d6bc781898">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by Etheryte** [comment]
Same bug in https://localhost:8080/rhn/manager/schedule/maintenance/calendars

**Comment by Etheryte** [comment]
Same bug in https://localhost:8080/rhn/manager/multiorg/recurring-actions?oid=1

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8947
