### ISSUE TITLE
Missing margins in create maintenance schedule

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8762]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

https://localhost:8080/rhn/manager/schedule/maintenance/schedules#/create

Could be related to the other margin bug.

<img width="1657" alt="Screenshot 2024-05-16 at 17 53 13" src="https://github.com/uyuni-project/uyuni/assets/3171718/a1e505c5-c46a-4acf-bf0d-b6a776459142">
<img width="1657" alt="Screenshot 2024-05-16 at 17 53 20" src="https://github.com/uyuni-project/uyuni/assets/3171718/f198b8ef-8102-45b0-88e1-752e8ecb5080">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8976

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8976
