### ISSUE TITLE
Incorrect capitalization for organization deleting

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8765]
See e.g. https://localhost:8080/rhn/manager/multiorg/recurring-actions?oid=1

<img width="196" alt="Screenshot 2024-05-16 at 18 08 42" src="https://github.com/uyuni-project/uyuni/assets/3171718/be605b4e-7155-47b8-a180-49af644b7658">

The first letter should be capitalized.

**Comment by avshiliaev** [comment]
@Etheryte is it solved yet? :smiley:

**Comment by bisht-richa** [comment]
> @Etheryte is it solved yet? 😃

Yes this is fixed

**Comment by bisht-richa** [comment]
This is fixed : https://github.com/uyuni-project/uyuni/pull/8770
