### ISSUE TITLE
Hidden section not hidden on the new theme

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8766]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

https://localhost:8080/rhn/admin/config/GeneralConfig.do

The last option should be hidden, but is not on the new theme.

Old theme:

<img width="867" alt="Screenshot 2024-05-16 at 18 11 07" src="https://github.com/uyuni-project/uyuni/assets/3171718/ffec18fa-c3ae-49a1-a3b6-c5be5edd9364">

New theme:

<img width="778" alt="Screenshot 2024-05-16 at 18 11 14" src="https://github.com/uyuni-project/uyuni/assets/3171718/7728bff2-1d63-49f7-8364-6d194a038202">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8987
