### ISSUE TITLE
Broken layout elements in monitoring

### ISSUE THREAD

**Issue by Etheryte** [uyuni-project/uyuni#8768]
Part of https://github.com/SUSE/spacewalk/issues/18940

All urls below are specified as the dev proxy (`yarn proxy https://...`), since that's the most convenient way to work on these issues.

To switch between the new theme and the old theme in the console: `debugUtils.toggleUpdatedTheme()`  
To switch between the Suma theme and the Uyuni theme: `debugUtils.toggleTheme()`   

<hr>

https://localhost:8080/rhn/manager/admin/config/monitoring

Probably related to the column bug we're already fixing under another ticket, but good to track this separately just in case.

<img width="1156" alt="Screenshot 2024-05-16 at 18 12 33" src="https://github.com/uyuni-project/uyuni/assets/3171718/bf3b1014-5fcf-4dda-a461-bc25c64ca0b4">
<img width="938" alt="Screenshot 2024-05-16 at 18 12 39" src="https://github.com/uyuni-project/uyuni/assets/3171718/3ae7d5a5-c502-46f4-9a81-fc3e58922d0b">

**Definition of done**  

The updated theme has no visual bugs, all related page urls are added to `ViewHelper.java` and `view-helper.ts`.

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8977
