### ISSUE TITLE
Webui: Missing page and broken sub menu item - "Bare Metal Systems"

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#8794]
### Problem description

Affecting 2024 05 and possibly earlier versions. 

**Description**
In webui, navigate to Admin -> Manager Configuration. 

The page menu shows these options:

![image](https://github.com/uyuni-project/uyuni/assets/4052275/489fbbc8-b723-43c7-85ed-a4e17b3d5a6f)

Now, select Monitoring, and an additional menu item appears

![image](https://github.com/uyuni-project/uyuni/assets/4052275/0bb3f5de-8958-4464-8949-ad8ce0a26373)

This "Bare Metal Systems" link takes me to https://HOSTNAME/rhn/admin/config/BootstrapSystems.do - which does not appear

![image](https://github.com/uyuni-project/uyuni/assets/4052275/e9da1060-b88e-4141-a429-4ef5e8922154)

**Expected behaviour:** 
All the items on the sub-menu should provide the same sub-menu. 

**Guessed reason**
Something in the code for the Monitoring sub-menu has old code relating to a now deprecated link page.

**Guessed solution**
Remove that old deprecated code and remove this link to "Bare metal systems"

**Extra info**
I don't have any configuration for images and don't use Uyuni to provision new servers, if that's relevent. (Perhaps this link is only supposed to appear for users who do distinguish bare metal systems)

### Steps to reproduce

As above

### Uyuni version

```bash
2024 05, upgraded this morning
```

**Comment by avshiliaev** [comment]
Thanks! This is indeed a real problem. It's on the radar and is going to be fixed soon :smiley:

**Comment by mcalmer** [comment]
Seems it was fixed
