### ISSUE TITLE
Missing/bad pagination icons in Schedule lists. (Cosmetic)

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#8810]
### Problem description

The icons at the top of the list (where there are more than the defined number of events to display) are missing or corrupted.

**Page:** https://HOSTNAME/rhn/schedule/FailedActions.do

Chrome:
![image](https://github.com/uyuni-project/uyuni/assets/4052275/f3dd539d-5297-4e8c-91df-bdd3203b1e57)

Firefox:
![image](https://github.com/uyuni-project/uyuni/assets/4052275/8fdf8cc2-f7aa-4f07-88b3-e66636e08da6)

Hovering over each of these four in turn brings up the title popup:

"Null"  (And red no entry icon)
"Null"  (And red no entry icon)
"Next Page" 
"Last Page"

The first two do nothing.

The last two do work when clicked as described, but are showing no image. 

Looking at the page source, it's possible that fontawesome is being used but for some reason this is not displaying.

### Steps to reproduce

As above

### Uyuni version

```bash
2024 05
```

**Comment by Etheryte** [comment]
This looks like a duplicate of https://github.com/uyuni-project/uyuni/issues/8728.

**Comment by digdilem** [comment]
You're right - it does. Closing this, thanks.
