### ISSUE TITLE
venv-salt-minion gets disabled during recent package update, causing machines to stop communicating. (EL)

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#8841]
### Problem description

Several machines stopped reporting in after recent OS patching (Rocky 8, Rocky 9)

On investigation, it turned out that the service `venv-salt-minion` was _disabled_ and not running. 

Temp fix: "systemctl enable --now venv-salt-minion" got each machine talking to Uyuni again, but that took quite a while as it involved manually sshing in to each vm. Luckily we spotted it when only 30-odd machines were affected. The update otherwise seemed to go okay, and the service runs normally - ONCE it's re-enabled.

### Steps to reproduce

The Uyuni Tools repo is fetched directly from the vm at `https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/EL9-Uyuni-Client-Tools/EL_9/`

To verify, I updated an unpatched machine. 

From this, it looks like the post-upgrade scriptlet for `venv-salt-minion-3006.0-30.2.uyuni.x86_64` is explicitly disabling the service. It is not re-enabled after this.

Unrelated package details removed from log:

```
# systemctl status venv-salt-minion
● venv-salt-minion.service - The venvjailed Salt Minion
     Loaded: loaded (/usr/lib/systemd/system/venv-salt-minion.service; enabled; preset: disabled)
     
# yum update
..
Upgrading:
 venv-salt-minion                          x86_64                       3006.0-30.2.uyuni                             direct-uyuni-tools-el9                        32 M
..

 Running scriptlet: venv-salt-minion-3006.0-30.2.uyuni.x86_64            
Removed "/etc/systemd/system/multi-user.target.wants/venv-salt-minion.service".

# systemctl status venv-salt-minion
● venv-salt-minion.service - The venvjailed Salt Minion
     Loaded: loaded (/usr/lib/systemd/system/venv-salt-minion.service; disabled; preset: disabled)
```
     

### Uyuni version

```bash
2024 05
```

### Useful logs

```bash
As a (hopefully temporary) workaround, I have added a script to /etc/cron.hourly on my machines that runs
`systemctl enable --now venv-salt-minion` to avoid us having to manually ssh into another 200+ vms to fix this.
```

**Comment by digdilem** [comment]
Update: Another round of updates here, and another number of vms had venv-salt-minion disabled during its package upgrade. 

This time, the upgrade package is `venv-salt-minion-3006.0-31.2.uyuni.x86_64` so it looks like this issue also affects that. 

Fortunately (for us) the mitigations I'd put in place by deploying a script that checks and re-enables the service automatically brought these vms back into contact a short time later.

**Comment by rjmateus** [comment]
@meaksh is this issue known? @avshiliaev this should had a look from bug boar I think

**Comment by m-czernek** [comment]
Not a known issue, I reproduced this even on OpenSUSE. Taking a closer look.

**Comment by m-czernek** [comment]
Thank you for the bug report!

Fixed in:

- https://build.opensuse.org/request/show/1181346
- https://build.opensuse.org/request/show/1181345

The issue was that our new RPM scriptlet (`%posttrans`) was mixing with the `%post` scriptlet. This should get into our next venv-salt-minion release.

**Comment by digdilem** [comment]
Thanks for the fix, glad it's sorted.
