### ISSUE TITLE
Alignment of radio buttons / labels when scheduling playbook execution

### ISSUE THREAD

**Issue by renner** [uyuni-project/uyuni#8874]
### Problem description

This report is about the Ansible integration: when scheduling a playbook execution, radio buttons are not aligned vertically and they seem to be too close to the labels as you can see from the screenshot. We might also want to vertically align the "Inventory Path" select with the other input fields.

![Screenshot from 2024-05-17 12-35-25](https://github.com/uyuni-project/uyuni/assets/729454/6b2b31d0-ce28-4ff4-839f-c73894777919)

This seems to be the current state with the old theme (as you can see in the screenshot), but switching to the new theme did not change the alignment either.

### Steps to reproduce

1. Register a client and turn it into Ansible Control Node (via "Edit System Details")
2. Prepare an inventory (in e.g. `/etc/ansible/hosts`) and playbook (in e.g. `/srv/playbooks`) on the Ansible Control Node
3. From the systems list, click on the control node system and go to the "Ansible" tab
4. Switch to the "Playbooks" tab and click one of the playbooks there to see the scheduling screen

### Uyuni version

```bash
2024.05
```

**Comment by bisht-richa** [comment]
Fixed: https://github.com/uyuni-project/uyuni/pull/8996
