### ISSUE TITLE
Mentions of jabberd in 5.0

### ISSUE THREAD

**Issue by Bischoff** [uyuni-project/uyuni#8906]
### Problem description

In installation-and-upgrade/pages/proxy-setup.adoc, one reads
```
[command]``configure-proxy.sh`` activates services required by {productname} Proxy, such as
[systemitem]``squid``, [systemitem]``apache2``, [systemitem]``salt-broker``,
and [systemitem]``jabberd``.
```

Isn't `jabberd` a part of the traditional stack that has been removed?

By the way, this is in a paragraph about `configure-proxy.sh`. Do we still have this script? If I am not wrong, this script is for traditional proxy only, not for containerized proxy. To be checked.

There might be other occurrences of `jabberd` and `configure-proxy.sh` in the doc.

### Steps to reproduce

1. see description

### Uyuni version

```bash
5.0 RC
```

**Comment by rjmateus** [comment]
@jcayouette @admd for awareness

**Comment by jcayouette** [comment]
This file is legacy. Removing. Thank you.
