### ISSUE TITLE
New native Appstream support doesn't seem to be working properly with RHEL 8 and Rocky 8

### ISSUE THREAD

**Issue by ppanon2022** [uyuni-project/uyuni#8937]
### Problem description

We've got two Uyuni installations that have been updated to 2024.05. On one, we've got a set of Rocky 8 channels and a Rocky LCM project that was being used to filter modules. On the other we've got Rocky 8, RHEL 8, and RHEL 9 channels and LCM projects.
We're trying to switch these over to the native Appstream support. 

For the first Uyuni install with just the Rocky 8 channels and repos, we've removed the filters from the LCM project, created a new version, and promoted it to the first test environment. The Rocky channels used as a base for the LCM projects have separate channels for the Base (Primary) and AppStream (child) repos. The child Rocky Appstream channel used as a base for the LCM project shows an Appstream tab listing all the expected modules. The LCM channels derived from the Appstream channel also show an Appstream tab with a full module list. 

However our test client in that LCM sandbox environment shows the Appstream tab, but the Appstream tab doesn't list any available modules for that client. There are some package dependency issues that are causing conflicts with the perl module, some requiring the 5.26 interpreter package and some requiring the 5.30 package. Not sure how we got there and maybe if we manage to fix those dependencies it will clear up the Appstream list, but it's not clear how we got here, how to fix it, whether it will actually fix the Appstream module display. I'm working with dnf module command on the client to enable specific modules for now but I don't know how effective that is.

Then, on the second Uyuni instance, we're trying to experiment with the RHEL8 channels and project. For that instance, the RHEL 8 Primary channel is linked to both the RHEL Base and Appstream channels and it shows the Appstream tab with the module list. When we did something similar to what was done on the first server (remove module filters, build a new version and promote it to the sandbox LCM environment), the client assigned to the LCM channels show no Appstream tab in the Software menu. In addition, the sandbox LCM channel corresponding to the master channel with the two repos doesn't show the Appstream tab or the module list.

### Steps to reproduce

I'm not sure how you would reproduce the first issue due to not being sure of how we got into the condition of conflicting dependencies. For the second issue, I think you would :

1. set up a rhel 8 channel / repository set with the Primary channel including both the Base and Appstream repos
2. create an LCM project based on that channel set
3. build an LCM version with no module filters.
...

### Uyuni version

```bash
For both systems the result is the same

#zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.05-230900.217.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.05-230900.217.1.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
Not relevant since we're testing without and intermediary proxy
```

### Useful logs

```bash
For the first case (empty Appstream tab) I see no errors in either rhn_web_frontend.log or rhn_web_ui.log, so I'm guessing that the issue is more likely to be some database query returning no data but not being reported.

I'm not sure what to look for, or if an error would even be generated in the LCM build process for the second case.
```

**Comment by cbbayburt** [comment]
Hi @ppanon2022, we had another similar report recently. The problem was that the `spacewalk-backend` package was not upgraded after the latest update. Can you please check if this package is up-to-date?

After that, you need to make sure to run a repo-sync so the new module metadata is imported. With this, you should be able to see the list of modules in the system's appstreams page.

Also, please note that Channel > AppStreams page has a different source to show the module list so it's not related to the new appstreams.

**Comment by ppanon2022** [comment]
carmd-nv-uyuni1:/var/log/rhn # rpm  -q -i spacewalk-backend-5.0.4-230900.1.3.uyuni3.noarch
Name        : spacewalk-backend
Version     : 5.0.4
Release     : 230900.1.3.uyuni3
Architecture: noarch
Install Date: Wed Mar  6 16:30:28 2024
Group       : System/Management
Size        : 299393
License     : GPL-2.0-only
Signature   : RSA/SHA256, Thu Feb 15 04:11:51 2024, Key ID 972e5d6c0d20833e
Source RPM  : spacewalk-backend-5.0.4-230900.1.3.uyuni3.src.rpm
Build Date  : Thu Feb 15 04:11:39 2024
Build Host  : i02-ch1d
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : obs://build.opensuse.org/systemsmanagement:Uyuni
URL         : https://github.com/uyuni-project/uyuni
Summary     : Common programs needed to be installed on the Spacewalk servers/proxies
Description :
Generic program files needed by the Spacewalk server machines.
This package includes the common code required by all servers/proxies.
Distribution: systemsmanagement:Uyuni:Master / openSUSE_Leap_15.5

Hmm. Looks like you are right since the build date is Feb 15, but I had done a zypper refresh && zypper update. I didn't notice that a second cycle showed that the spacewalk-backend packages were being held back.

zypper update
Loading repository data...
Reading installed packages...

The following item is locked and will not be changed by any action:
 Installed:
  html2text

The following 16 package updates will NOT be installed:
  byte-buddy html2text spacewalk-backend spacewalk-backend-app spacewalk-backend-applet spacewalk-backend-iss spacewalk-backend-iss-export
  spacewalk-backend-package-push-server spacewalk-backend-server spacewalk-backend-sql spacewalk-backend-sql-postgresql spacewalk-backend-tools
  spacewalk-backend-xml-export-libs spacewalk-backend-xmlrpc susemanager uyuni-setup-reportdb

The following 91 packages are going to be upgraded:
  WebKitGTK-4.0-lang aaa_base aaa_base-extras apache2 apache2-prefork apache2-utils chrony chrony-pool-openSUSE cups cups-client cups-config dom4j dwz fdupes
  glibc glibc-devel glibc-extra glibc-lang glibc-locale glibc-locale-base gstreamer-plugins-base gstreamer-plugins-base-lang guava iputils jaxen jdom
  jitterentropy-devel libaom3 libavcodec58_134 libavutil56_70 libcups2 libcupscgi1 libcupsimage2 libcupsmime1 libcupsppdc1 libgstallocators-1_0-0
  libgstapp-1_0-0 libgstaudio-1_0-0 libgstfft-1_0-0 libgstgl-1_0-0 libgstpbutils-1_0-0 libgstriff-1_0-0 libgstrtp-1_0-0 libgstrtsp-1_0-0 libgstsdp-1_0-0
  libgsttag-1_0-0 libgstvideo-1_0-0 libjavascriptcoregtk-4_0-18 libjitterentropy3 libnfsidmap-sss libopenssl-1_1-devel libopenssl1_1 libpoppler-cpp0
  libpoppler126 libpython2_7-1_0 libsss_certmap0 libsss_idmap0 libsss_nss_idmap0 libsss_simpleifp0 libswresample3_9 libtiff5 libvirt-client libvirt-libs
  libwebkit2gtk-4_0-37 nano nano-lang nscd objectweb-asm openssl-1_1 osc perl-DBD-SQLite poppler-tools python python-base python-curses python-xml
  python3-Jinja2 python3-requests python3-sssd-config sssd sssd-ad sssd-common sssd-krb5-common sssd-ldap sssd-tools supportutils suse-module-tools
  webkit2gtk-4_0-injected-bundles xom yast2-country yast2-country-data

The following NEW package is going to be installed:
  git-lfs

91 packages to upgrade, 1 new.
Overall download size: 94.6 MiB. Already cached: 0 B. After the operation, additional 7.6 MiB will be used.

I take it I need to do a zypper install for those held back packages?

**Comment by ppanon2022** [comment]
I wound up picking options that resulted in removing spacewalk-backend-config-files-common, spacewalk-backend-config-files-tool, and spacewalk-backend-config-files. That seemed to be safe since those files no longer seem to be in either the noarch or x86_64 folders of the repo.

However I've got two packages that are still being held back susemanager and uyuni-setup-reportdb.
Trying to upgrade susemanager results in 

carmd-nv-uyuni1:/var/log/rhn # zypper install susemanager
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: 1: the to be installed susemanager-5.0.6-230900.1.1.uyuni3.x86_64 requires 'spacewalk-db-virtual', but this requirement cannot be provided
not installable providers: spacewalk-postgresql-5.0.2-230900.1.1.uyuni3.noarch[uyuni-server-stable]

 Solution 1: Following actions will be done:
  deinstallation of postgresql15-contrib-15.7-150200.5.27.1.x86_64
  deinstallation of postgresql15-15.7-150200.5.27.1.x86_64
  deinstallation of postgresql15-server-15.7-150200.5.27.1.x86_64
  deinstallation of postgresql15-llvmjit-15.7-150200.5.27.1.x86_64
 Solution 2: do not install susemanager-5.0.6-230900.1.1.uyuni3.x86_64
 Solution 3: break susemanager-5.0.6-230900.1.1.uyuni3.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c/d/?] (c):

and trying to upgrade uyuni-setup-reportdb results in 
carmd-nv-uyuni1:/var/log/rhn # zypper install uyuni-setup-reportdb
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: 1: the to be installed uyuni-setup-reportdb-5.0.3-230900.1.1.uyuni3.noarch conflicts with 'postgresql-server-implementation > 15' provided by the installed postgresql15-server-15.7-150200.5.27.1.x86_64
 Solution 1: Following actions will be done:
  deinstallation of postgresql15-server-15.7-150200.5.27.1.x86_64
  deinstallation of postgresql15-contrib-15.7-150200.5.27.1.x86_64
  deinstallation of postgresql15-llvmjit-15.7-150200.5.27.1.x86_64
 Solution 2: do not install uyuni-setup-reportdb-5.0.3-230900.1.1.uyuni3.noarch

Choose from above solutions by number or cancel [1/2/c/d/?] (c): c

susemanager 4.4.8 seems to be mainly postgresql migration/upgrade scripts for older versions of postscript, so I guess it could just be removed.

Similarly, we have a reportdb set up, so perhaps uyuni-setup-reportdb is no longer needed, but the complaint that postgresql-server-implementation > 15 seems to be a bug, since 
 # rpm -q --provides postgresql15-server
libpqwalreceiver.so()(64bit)
postgresql-server-implementation = 15.7-150200.5.27.1
postgresql15-server = 15.7-150200.5.27.1
postgresql15-server(x86-64) = 15.7-150200.5.27.1
is a newer version of 15, and removing postgresql15-server is a non-starter.

So should I just remove those two packages? Leave them as is so that newer releases with fixed dependencies can update them later?
I'm just surprised I haven't seen anybody else bring this up. Did I skip a step in the installation notes that said to remove them?

**Comment by mcalmer** [comment]
Seems you have an inconsistant system. You should switch to the container with the next uyuni release. With a container this cannot happen anymore

**Comment by ppanon2022** [comment]
One more item of concern. Currently, we prefer to use separate disks to isolate the package repositories in /var/spacewalk and the postgresql database in /var/lib/pgsql from the O/S root filesystem. It also lets us track how much storage is being used by the DB and repos. Can that still work in a container environment? Does your container keep that data internal to the overlay or mapped to filesystem storage outside the container?

**Comment by mbussolotto** [comment]
> One more item of concern. Currently, we prefer to use separate disks to isolate the package repositories in /var/spacewalk and the postgresql database in /var/lib/pgsql from the O/S root filesystem. It also lets us track how much storage is being used by the DB and repos. Can that still work in a container environment? Does your container keep that data internal to the overlay or mapped to filesystem storage outside the container?

yes, you should use `mgr-storage-server` for it https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/container-deployment/uyuni/server-deployment-uyuni.html#_configure_custom_persistent_storage

**Comment by ppanon2022** [comment]
> > One more item of concern. Currently, we prefer to use separate disks to isolate the package repositories in /var/spacewalk and the postgresql database in /var/lib/pgsql from the O/S root filesystem. It also lets us track how much storage is being used by the DB and repos. Can that still work in a container environment? Does your container keep that data internal to the overlay or mapped to filesystem storage outside the container?
> 
> yes, you should use `mgr-storage-server` for it https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/container-deployment/uyuni/server-deployment-uyuni.html#_configure_custom_persistent_storage

Thanks, I had since seen that mentioned since my June post. That doc page could be a little clearer on that, though the --help option helped fill in the holes in my understanding. But eventually I figured out that the parameters are the two devices that the script partitions, formats, and mounts for the (package) data and (Postgresql) database persistent volumes, in that order.

I'm still having a problem after that though. I've set up the authorized-keys ssh settings on the legacy Uyuni server, tested that it works to ssh directly to root from the container server but, when trying to do a trial run, I now get

# mgradm migrate podman --prepare --logLevel debug <legacy_uyuni.fqdn>
8:07PM INF mgradm/cmd/cmd.go:67 > Welcome to mgradm
8:07PM INF mgradm/cmd/cmd.go:68 > Executing command: podman
8:07PM INF shared/utils/utils.go:200 > Computed image name is registry.opensuse.org/uyuni/server:latest
8:07PM DBG shared/utils/inspector.go:51 > Generating inspect script in /tmp/mgradm-1406773444/inspect.sh
8:07PM DBG shared/utils/exec.go:50 > Running: /tmp/mgradm-1406773444/inspect.sh
8:07PM DBG shared/utils/inspector.go:80 > Trying to read /tmp/mgradm-1406773444/data
8:07PM INF shared/podman/images.go:44 > Pull Policy is always. Presence of RPM image will be checked and if it's not present it will be pulled from registry
8:07PM DBG shared/podman/images.go:112 > Looking for installed RPM package containing registry.opensuse.org/uyuni/server:latest image
8:07PM DBG shared/podman/images.go:118 > Cannot read directory /usr/share/suse-docker-images/native/ error="open /usr/share/suse-docker-images/native/: no such file or directory"
8:07PM INF shared/podman/images.go:60 > Cannot find RPM image for registry.opensuse.org/uyuni/server:latest
8:07PM DBG shared/podman/images.go:64 > Pulling image registry.opensuse.org/uyuni/server:latest because it is missing and pull policy is not 'never'
8:07PM INF shared/podman/images.go:210 > Running podman pull registry.opensuse.org/uyuni/server:latest
8:07PM DBG shared/utils/exec.go:50 > Running: podman pull registry.opensuse.org/uyuni/server:latest
Trying to pull registry.opensuse.org/uyuni/server:latest...
Getting image source signatures
Copying blob 0a5f8240e04b skipped: already exists
Copying blob 3e004aa9a8af skipped: already exists
Copying blob 4dcdc701cb4a skipped: already exists
Copying config 1b794a1eb8 done   |
Writing manifest to image destination
1b794a1eb81cf14fe337f9bf243e0cd56f81c4af9bc3e1bb259396f702a6f49e
8:07PM INF mgradm/shared/podman/podman.go:196 > Migrating server
8:07PM DBG shared/utils/exec.go:50 > Running: podman run --name uyuni-migration --rm --cap-add NET_RAW --tmpfs /run -v cgroup:/sys/fs/cgroup:rw --security-opt label=disable -e SSH_AUTH_SOCK -v /tmp/ssh-XXXXXXavM1nX:/tmp/ssh-XXXXXXavM1nX -v /tmp/mgradm-3425645276:/var/lib/uyuni-tools/ -v /root/.ssh/known_hosts:/etc/ssh/ssh_known_hosts -v var-cobbler:/var/lib/cobbler -v var-salt:/var/lib/salt -v var-cache:/var/cache -v var-spacewalk:/var/spacewalk -v var-log:/var/log -v srv-salt:/srv/salt -v srv-www:/srv/www/ -v srv-tftpboot:/srv/tftpboot -v srv-formulametadata:/srv/formula_metadata -v srv-pillar:/srv/pillar -v srv-susemanager:/srv/susemanager -v srv-spacewalk:/srv/spacewalk -v root:/root -v ca-cert:/etc/pki/trust/anchors -v etc-tls:/etc/pki/tls -v var-pgsql:/var/lib/pgsql -v etc-rhn:/etc/rhn -v tls-key:/etc/pki/spacewalk-tls -v etc-apache2:/etc/apache2 -v etc-systemd-multi:/etc/systemd/system/multi-user.target.wants -v etc-systemd-sockets:/etc/systemd/system/sockets.target.wants -v etc-salt:/etc/salt -v etc-rhn:/etc/rhn -v etc-tomcat:/etc/tomcat -v etc-cobbler:/etc/cobbler -v etc-sysconfig:/etc/sysconfig -v etc-postfix:/etc/postfix -v etc-sssd:/etc/sssd registry.opensuse.org/uyuni/server:latest /var/lib/uyuni-tools/migrate.sh
Preparing migration...
Permission denied, please try again.
Permission denied, please try again.
Received disconnect from 10.1.11.155 port 22:2: Too many authentication failures
Disconnected from 10.1.11.155 port 22
Error: cannot run migration script: cannot run uyuni migration container: failed to run uyuni-migration container: exit status 255

Why is it getting ssh connections denied when I've tested it successfully prior?
If I look at the legacy server's audit log, when log in with ssh I just see lines with res=success, including some 
type=CRYPTO_KEY_USER lines.
When I run the mgradm command, I see a bunch of failing type=USER_AUTH line failures, then a couple of successful type=CRYPTO_KEY_USER lines, but with a failing type=USER_ERR between them and a failing type=USER_LOGIN afterwards.

So I'm guessing the mgradm command is failing because of the USER_AUTH (op=PAM:authentication and op=challenge-response ) failures are superceding the later ssh key successes, but I don't understand why mgradm is trying to do challenge-response when the ssh client doesn't.

**Comment by mbussolotto** [comment]
> Why is it getting ssh connections denied when I've tested it successfully prior?

Please be sure you followed this step:
- in host system, you should have you ssh key (if not `ssh-keygen` ) for your <user>
- copy your ssh in the legacy system ( `ssh-copy-id <user>@legacy_uyuni`)
- start an ssh-agent ( `eval $(ssh-agent)` )
- add your ssh key to the agent (`ssh-add` )

> I think there was another discussion that was more migration focused. I'll see if I can ask there too. I thought this was it.

yes please, we're going out of topic with this thread, if you can close this issue we can continue on other one, so it would be  more helpful to reach out information in the future. Thanks

**Comment by ppanon2022** [comment]
Hmm. Because I had rebooted, I had rerun the agent but didn't realize I needed to redo the ssh-add. It's working now, thank you.

**Comment by mbussolotto** [comment]
is there any other problem or you can close this issue? @ppanon2022

**Comment by ppanon2022** [comment]
I've got another question, but it's not related to this issue. I'll close it and post that other question in the migration discussion.
