### ISSUE TITLE
Source file salt://certs/RHN-ORG-TRUSTED-SSL-CERT not found in saltenv 'base'

### ISSUE THREAD

**Issue by gabardyne** [uyuni-project/uyuni#9007]
### Problem description

When I try to apply highstate on Oracle Linux 7/8, I have the error below:

          ID: mgr_ca_cert
    Function: file.managed
        Name: /etc/pki/ca-trust/source/anchors/RHN-ORG-TRUSTED-SSL-CERT
      Result: False
     Comment: Source file salt://certs/RHN-ORG-TRUSTED-SSL-CERT not found in saltenv 'base'
     Started: 14:48:17.678083
    Duration: 120.395 ms
     Changes:

I haven't this problem on Rocky 8/9 or CentOS 7.

I have try this command "venv-salt-call state.apply certs" but same error.

The file /etc/pki/ca-trust/source/anchors/RHN-ORG-TRUSTED-SSL-CERT is existing on the server though.

Any Ideas?

Regards

### Steps to reproduce

1.Apply Highstate on a Oracle Linux System

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.05-230900.217.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.05-230900.217.1.uyuni3.src
Summary        : Uyuni Server
```

**Comment by rusnazip** [comment]
try create hardlink
mv /usr/share/susemanager/salt/certs/RHN-ORG-TRUSTED-SSL-CERT{,.original}
ln /srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT /usr/share/susemanager/salt/certs/RHN-ORG-TRUSTED-SSL-CERT

**Comment by gabardyne** [comment]
Hello,
Thanks for the quick answer. 
Its working! Thank you!
Regards
