### ISSUE TITLE
Run scripts outside of /tmp

### ISSUE THREAD

**Issue by BoBBer446** [uyuni-project/uyuni#9064]
Hi guys, I have added “noexec” to the /tmp partition in the fstab of my system. This prevents me from running scripts on the systems.

How can I change the destination folder where scripts are executed? 

i use venv-salt-minion 
this dindt work:
https://www.suse.com/support/kb/doc/?id=000019376

because venv-salt-minion config had no point there

**Comment by roelandjansen** [comment]
I agree @BoBBer446 !

Same here too, noexec, nosuid, nodev for security reasons on /tmp and /var/tmp.
I think /tmp or /var/tmp is not the right place to execute anything.

**Comment by BoBBer446** [comment]
Hey There, i found a solution for that. should be an posting on docs. Would be healpful.
Here is the Solution:
`sudo mkdir -p /etc/systemd/system/venv-salt-minion.service.d/ && echo -e "[Service]\nEnvironment=TMPDIR=/var/tmp" | sudo tee /etc/systemd/system/venv-salt-minion.service.d/10-TMPDIR.conf > /dev/null && sudo systemctl daemon-reload && sudo systemctl restart venv-salt-minion.service`

Now Salt / Uyuni is using a different Folder for the running scripts.
It is working smooth :)

**Comment by rjmateus** [comment]
This is documented in the uyuni documentation: https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/troubleshooting/tshoot-mounting-tmp-with-noexec.html
