### ISSUE TITLE
After migrating to podman Schedule Actions pages time out.

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#9072]
### Problem description

After migrating to podman the Schedule Actions pages do not load. The loading bar runs at the top of the page for a while and after that the "Request has timed out , please reload the page" pops up.
Actions/tasks still run even scheduled ones but I cant see the results well. The home page also shows them.
update:
Failed, complete and archived actions open sometimes very slowly.
### Steps to reproduce

1. Migrate to podman
2. Try to open the action pages.

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.05-230900.217.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.05-230900.217.1.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
no proxy
```

### Useful logs

```bash
Nothing in /var/log/rhn/rhn_web_ui.log
```

### Additional information

Also had this issue when migrating to podman. Removed the same parameters.
https://github.com/uyuni-project/uyuni/issues/9026

**Comment by avshiliaev** [comment]
Hey @j-kihet 
thanks for the report. Could you please:
1. Update to 2024.07
2. Verify if you have podman >=4.5.0

**Comment by j-kihet** [comment]
Hi @avshiliaev , thank you for the fast reply!
1. Will try it next week.
2. podman version is 4.9.4

**Comment by j-kihet** [comment]
Upgraded to 2024.07 , pages still time out.
The issue does go away after a while, so I cant tell what is causing it.

**Comment by j-kihet** [comment]
On version 2024.08 it still loads for a minute but its not t that bad.
