### ISSUE TITLE
CentOS7 venv-salt-minion beacon error "needs-restarting"  error remains

### ISSUE THREAD

**Issue by riverhawk02** [uyuni-project/uyuni#9077]
### Problem description

After upgrading to Uyuni 2024.07, CentOS7 clients are still unable to update the package lists for accurate count.  The latest venv-salt-minion client is outputting errors every ten seconds.  

### Steps to reproduce

1.  Upgraded Uyuni Server to 2024.07 without issue or errors.
2.  Upgraded CentOS7 client to latest venv-salt-minion 
3.  Errors start immediately (see log)
4.  Related to previously closed bug
5. Client Update Package List through GUI which generates error message

System History Event
Summary:Package List Refresh
Details:This action will be executed after 7/19/24 6:37:54 PM GMT
This action's status is: Failed.
The client completed this action on 7/19/24 6:38:02 PM GMT
Client execution returned
An unexpected error has occurred. Please check the server logs.
(code -1)
...

### Uyuni version

```bash
zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Useful logs

```bash
Key Entry:  

Jul 19 18:38:48    salt-minion[11230]: salt.exceptions.CommandExecutionError: Unable to run command '['needs-restarting', '-r']' with the context '{'cwd': '/root', 'shell': False, 'env': {'SALT_CONFIG_DIR': '/etc/venv-salt-minion', 'LD_LIBRARY_PATH': '/usr/lib/venv-salt-minion/lib', 'CPATH': '/usr/lib/venv-salt-minion/usr/include/python3.11', 'VIRTUAL_ENV': '/usr/lib/venv-salt-minion', 'PATH': '/usr/lib/venv-salt-minion/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '0', 'VENV_PIP_TARGET': '/var/lib/venv-salt-minion/local', 'SALT_MINION_CONFIG': '/etc/venv-salt-minion/minion', 'LC_CTYPE': 'C', 'LC_NUMERIC': 'C', 'LC_TIME': 'C', 'LC_COLLATE': 'C', 'LC_MONETARY': 'C', 'LC_MESSAGES': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'LC_ADDRESS': 'C', 'LC_TELEPHONE': 'C', 'LC_MEASUREMENT': 'C', 'LC_IDENTIFICATION': 'C', 'LANGUAGE': 'C'}, 'stdin': None, 'stdout': -1, 'stderr': -1, 'with_communicate': True, 'timeout': None, 'bg': False, 'close_fds': True}', reason: [Errno 2] No such file or directory: 'needs-restarting'


Full Output: 

Jul 19 18:38:48    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:38:48    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1249, in _run_as
Jul 19 18:38:48    salt-minion[11230]: return _func_or_method(*args, **kwargs)
Jul 19 18:38:48    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:38:48    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 2329, in run_all
Jul 19 18:38:48    salt-minion[11230]: ret = _run(
Jul 19 18:38:48    salt-minion[11230]: ^^^^^
Jul 19 18:38:48    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 753, in _run
Jul 19 18:38:48    salt-minion[11230]: raise CommandExecutionError(msg)
Jul 19 18:38:48    salt-minion[11230]: salt.exceptions.CommandExecutionError: Unable to run command '['needs-restarting', '-r']' with the context '{'cwd': '/root', 'shell': False, 'env': {'SALT_CONFIG_DIR': '/etc/venv-salt-minion', 'LD_LIBRARY_PATH': '/usr/lib/venv-salt-minion/lib', 'CPATH': '/usr/lib/venv-salt-minion/usr/include/python3.11', 'VIRTUAL_ENV': '/usr/lib/venv-salt-minion', 'PATH': '/usr/lib/venv-salt-minion/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '0', 'VENV_PIP_TARGET': '/var/lib/venv-salt-minion/local', 'SALT_MINION_CONFIG': '/etc/venv-salt-minion/minion', 'LC_CTYPE': 'C', 'LC_NUMERIC': 'C', 'LC_TIME': 'C', 'LC_COLLATE': 'C', 'LC_MONETARY': 'C', 'LC_MESSAGES': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'LC_ADDRESS': 'C', 'LC_TELEPHONE': 'C', 'LC_MEASUREMENT': 'C', 'LC_IDENTIFICATION': 'C', 'LANGUAGE': 'C'}, 'stdin': None, 'stdout': -1, 'stderr': -1, 'with_communicate': True, 'timeout': None, 'bg': False, 'close_fds': True}', reason: [Errno 2] No such file or directory: 'needs-restarting'
[root@   ~]# journalctl -xeu venv-salt-minion.service
Jul 19 18:39:08    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1249, in _run_as
Jul 19 18:39:08    salt-minion[11230]: return _func_or_method(*args, **kwargs)
Jul 19 18:39:08    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:08    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 2329, in run_all
Jul 19 18:39:08    salt-minion[11230]: ret = _run(
Jul 19 18:39:08    salt-minion[11230]: ^^^^^
Jul 19 18:39:08    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 753, in _run
Jul 19 18:39:08    salt-minion[11230]: raise CommandExecutionError(msg)
Jul 19 18:39:08    salt-minion[11230]: salt.exceptions.CommandExecutionError: Unable to run command '['needs-restarting', '-r']' with the context '{'cwd': '/root', 'shell': False, 'env': {'SALT_CONFIG_DIR': '/et
Jul 19 18:39:18    salt-minion[11230]: [ERROR   ] Error while executing 'reboot_info.reboot_required': Unable to run command '['needs-restarting', '-r']' with the context '{'cwd': '/root', 'shell': False, 'env':
Jul 19 18:39:18    salt-minion[11230]: Traceback (most recent call last):
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 746, in _run
Jul 19 18:39:18    salt-minion[11230]: proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/utils/timed_subprocess.py", line 53, in __init__
Jul 19 18:39:18    salt-minion[11230]: self.process = subprocess.Popen(args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/subprocess.py", line 1026, in __init__
Jul 19 18:39:18    salt-minion[11230]: self._execute_child(args, executable, preexec_fn, close_fds,
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/subprocess.py", line 1955, in _execute_child
Jul 19 18:39:18    salt-minion[11230]: raise child_exception_type(errno_num, err_msg, err_filename)
Jul 19 18:39:18    salt-minion[11230]: FileNotFoundError: [Errno 2] No such file or directory: 'needs-restarting'
Jul 19 18:39:18    salt-minion[11230]: During handling of the above exception, another exception occurred:
Jul 19 18:39:18    salt-minion[11230]: Traceback (most recent call last):
Jul 19 18:39:18    salt-minion[11230]: File "/var/cache/venv-salt-minion/minion/extmods/beacons/reboot_info.py", line 55, in beacon
Jul 19 18:39:18    salt-minion[11230]: result = __salt__["reboot_info.reboot_required"]()
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 149, in __call__
Jul 19 18:39:18    salt-minion[11230]: return self.loader.run(run_func, *args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1234, in run
Jul 19 18:39:18    salt-minion[11230]: return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1249, in _run_as
Jul 19 18:39:18    salt-minion[11230]: return _func_or_method(*args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/var/cache/venv-salt-minion/minion/extmods/modules/reboot_info.py", line 57, in reboot_required
Jul 19 18:39:18    salt-minion[11230]: result = _check_cmd_exit_code(cmd, 1)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/var/cache/venv-salt-minion/minion/extmods/modules/reboot_info.py", line 24, in _check_cmd_exit_code
Jul 19 18:39:18    salt-minion[11230]: output = __salt__["cmd.run_all"](cmd, ignore_retcode=True)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 149, in __call__
Jul 19 18:39:18    salt-minion[11230]: return self.loader.run(run_func, *args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1234, in run
Jul 19 18:39:18    salt-minion[11230]: return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1249, in _run_as
Jul 19 18:39:18    salt-minion[11230]: return _func_or_method(*args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 2329, in run_all
Jul 19 18:39:18    salt-minion[11230]: ret = _run(
Jul 19 18:39:18    salt-minion[11230]: ^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 753, in _run
Jul 19 18:39:18    salt-minion[11230]: raise CommandExecutionError(msg)
```

### Additional information

[root~]# rpm -q venv-salt-minion
venv-salt-minion-3006.0-33.1.uyuni.x86_64

[root~]# journalctl -xeu venv-salt-minion.service
Jul 19 18:39:08    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1249, in _run_as
Jul 19 18:39:08    salt-minion[11230]: return _func_or_method(*args, **kwargs)
Jul 19 18:39:08    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:08    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 2329, in run_all
Jul 19 18:39:08    salt-minion[11230]: ret = _run(
Jul 19 18:39:08    salt-minion[11230]: ^^^^^
Jul 19 18:39:08    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 753, in _run
Jul 19 18:39:08    salt-minion[11230]: raise CommandExecutionError(msg)
Jul 19 18:39:08    salt-minion[11230]: salt.exceptions.CommandExecutionError: Unable to run command '['needs-restarting', '-r']' with the context '{'cwd': '/root', 'shell': False, 'env': {'SALT_CONFIG_DIR': '/et
Jul 19 18:39:18    salt-minion[11230]: [ERROR   ] Error while executing 'reboot_info.reboot_required': Unable to run command '['needs-restarting', '-r']' with the context '{'cwd': '/root', 'shell': False, 'env':
Jul 19 18:39:18    salt-minion[11230]: Traceback (most recent call last):
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 746, in _run
Jul 19 18:39:18    salt-minion[11230]: proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/utils/timed_subprocess.py", line 53, in __init__
Jul 19 18:39:18    salt-minion[11230]: self.process = subprocess.Popen(args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/subprocess.py", line 1026, in __init__
Jul 19 18:39:18    salt-minion[11230]: self._execute_child(args, executable, preexec_fn, close_fds,
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/subprocess.py", line 1955, in _execute_child
Jul 19 18:39:18    salt-minion[11230]: raise child_exception_type(errno_num, err_msg, err_filename)
Jul 19 18:39:18    salt-minion[11230]: FileNotFoundError: [Errno 2] No such file or directory: 'needs-restarting'
Jul 19 18:39:18    salt-minion[11230]: During handling of the above exception, another exception occurred:
Jul 19 18:39:18    salt-minion[11230]: Traceback (most recent call last):
Jul 19 18:39:18    salt-minion[11230]: File "/var/cache/venv-salt-minion/minion/extmods/beacons/reboot_info.py", line 55, in beacon
Jul 19 18:39:18    salt-minion[11230]: result = __salt__["reboot_info.reboot_required"]()
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 149, in __call__
Jul 19 18:39:18    salt-minion[11230]: return self.loader.run(run_func, *args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1234, in run
Jul 19 18:39:18    salt-minion[11230]: return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1249, in _run_as
Jul 19 18:39:18    salt-minion[11230]: return _func_or_method(*args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/var/cache/venv-salt-minion/minion/extmods/modules/reboot_info.py", line 57, in reboot_required
Jul 19 18:39:18    salt-minion[11230]: result = _check_cmd_exit_code(cmd, 1)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/var/cache/venv-salt-minion/minion/extmods/modules/reboot_info.py", line 24, in _check_cmd_exit_code
Jul 19 18:39:18    salt-minion[11230]: output = __salt__["cmd.run_all"](cmd, ignore_retcode=True)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 149, in __call__
Jul 19 18:39:18    salt-minion[11230]: return self.loader.run(run_func, *args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1234, in run
Jul 19 18:39:18    salt-minion[11230]: return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib64/python3.11/site-packages/salt/loader/lazy.py", line 1249, in _run_as
Jul 19 18:39:18    salt-minion[11230]: return _func_or_method(*args, **kwargs)
Jul 19 18:39:18    salt-minion[11230]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 2329, in run_all
Jul 19 18:39:18    salt-minion[11230]: ret = _run(
Jul 19 18:39:18    salt-minion[11230]: ^^^^^
Jul 19 18:39:18    salt-minion[11230]: File "/usr/lib/venv-salt-minion/lib/python3.11/site-packages/salt/modules/cmdmod.py", line 753, in _run
Jul 19 18:39:18    salt-minion[11230]: raise CommandExecutionError(msg)ls

**Comment by rjmateus** [comment]
can you try to install the package `yum-utils` on that host and see if it still fails?
This issue will be solved in a future release.

**Comment by riverhawk02** [comment]
@rjmateus :   Yes, pushing the yum-utils package coupled with updating the venv-salt-minion has dramatically improved the situation.   Package List is now updated and I'm starting to see accurate Errata counts in the reporting.   I'll keep an eye on it for the test of the day.   Thank you!

**Comment by mbussolotto** [comment]
closing
