### ISSUE TITLE
SLES15 SP3 bootstrapping problem: ERROR: package 'python3-looseversion' not found

### ISSUE THREAD

**Issue by kurzandras** [uyuni-project/uyuni#9115]
### Problem description

Hi all,

for some reason the bootstrapping has stopped working in my Uyuni setup.

I have tried to bootstrap using the UI, but it was failing with the error:

Error: Unable to download
[https://uyuni01.at:443/pub/repositories/sle/15/3/bootstrap/venv-enabled-x86_64.txt](https://uyuni01.at/pub/repositories/sle/15/3/bootstrap/venv-enabled-x86_64.txt)
file!

I have checked the bootstrap repositories and tried to recreate the one for sles15sp3, but there was an error:

uyuni01:~ # mgr-create-bootstrap-repo -c SLE-15-SP3-x86_64 --with-custom-channels --with-parent-channel=sle-product-sles15-sp3-pool-x86_64

Creating bootstrap repo for SLE-15-SP3-x86_64
copy 'gio-branding-SLE-15-150300.19.3.1.noarch'
copy 'hostname-3.16-2.22.x86_64'
copy 'iproute2-5.3-5.5.1.x86_64'
copy 'libmnl0-1.0.4-1.25.x86_64'
copy 'libxtables12-1.8.7-1.1.x86_64'
copy 'libpgm-5_2-0-5.2.122-5.3.1.x86_64'
copy 'libpython3_6m1_0-3.6.15-150300.10.37.2.x86_64'
copy 'libsodium23-1.0.18-150000.4.6.1.x86_64'
copy 'libzmq5-4.2.3-3.15.4.x86_64'
copy 'logrotate-3.13.0-150000.4.7.1.x86_64'
copy 'net-tools-2.0+git20170221.479bb4a-3.11.x86_64'
copy 'openssl-1.1.1d-1.46.noarch'
copy 'python3-3.6.15-150300.10.37.2.x86_64'
copy 'python3-base-3.6.15-150300.10.37.2.x86_64'
copy 'python3-appdirs-1.4.3-1.21.noarch'
copy 'python3-asn1crypto-0.24.0-3.2.1.noarch'
copy 'python3-Babel-2.8.0-3.3.1.noarch'
copy 'python3-certifi-2018.1.18-1.18.noarch'
copy 'python3-cffi-1.13.2-3.2.5.x86_64'
copy 'python3-chardet-3.0.4-3.23.noarch'
copy 'python3-cryptography-2.9.2-150200.13.1.x86_64'
copy 'python3-distro-1.5.0-3.5.1.noarch'
copy 'python3-idna-2.6-1.20.noarch'
copy 'python3-Jinja2-2.10.1-3.10.2.noarch'
copy 'python3-MarkupSafe-1.0-1.29.x86_64'
copy 'python3-M2Crypto-0.35.2-150000.3.14.1.x86_64'
copy 'python3-msgpack-0.5.6-150100.3.3.1.x86_64'
Optional package 'python3-ordered-set' not found
copy 'python3-packaging-20.3-1.9.noarch'
copy 'python3-psutil-5.8.0-150300.3.3.2.x86_64'
copy 'python3-py-1.10.0-150000.5.9.2.noarch'
copy 'python3-pyasn1-0.4.2-3.2.1.noarch'
copy 'python3-pycparser-2.17-3.2.1.noarch'
copy 'python3-pyparsing-2.4.7-1.24.noarch'
copy 'python3-pytz-2022.1-150300.3.6.1.noarch'
copy 'python3-pyOpenSSL-19.0.0-1.31.noarch'
copy 'python3-PyYAML-5.4.1-1.1.x86_64'
copy 'python3-pyzmq-17.1.2-3.3.1.x86_64'
copy 'python3-requests-2.24.0-1.24.noarch'
copy 'python3-rpm-4.14.3-150300.52.1.x86_64'
copy 'python3-setuptools-40.5.0-6.3.1.noarch'
copy 'python3-simplejson-3.17.2-1.10.x86_64'
copy 'python3-six-1.14.0-12.1.noarch'
copy 'python3-urllib3-1.25.10-4.3.1.noarch'
copy 'python3-immutables-0.11-150000.1.3.1.x86_64'
copy 'python3-contextvars-2.4-150000.1.3.1.noarch'
copy 'python3-zypp-plugin-0.6.3-150000.4.2.1.noarch'
copy 'timezone-2022g-150000.75.18.1.x86_64'
copy 'salt-3004-150300.53.33.6.x86_64'
copy 'python3-salt-3004-150300.53.33.6.x86_64'
copy 'salt-minion-3004-150300.53.33.6.x86_64'
copy 'python3-apipkg-1.4-150000.3.4.1.noarch'
copy 'python3-iniconfig-1.1.1-150000.1.9.1.noarch'
copy 'python3-jmespath-0.9.3-1.21.noarch'
copy 'xz-5.2.3-150000.4.7.1.x86_64'
copy 'venv-salt-minion-3006.0-32.1.uyuni.x86_64'
copy 'dmidecode-3.2-9.11.1.x86_64'
copy 'libunwind-1.5.0-4.5.1.x86_64'
Directory walk started
Directory walk done - 169 packages
Temporary output repo path: /srv/www/htdocs/pub/repositories/sle/15/3/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
ERROR: package 'python3-looseversion' not found

Suggestions:
mgr-create-bootstrap-repo uses the locally synchronized versions of files
from the Tools repository, and uses the locally synchronized pool channel
for dependency resolution.
Both should be fully synced before running the mgr-create-bootstrap-repo script.

The Uyuni client tools is already added:
![image](https://github.com/user-attachments/assets/a33d8144-b926-4b0d-be44-78018445a211)

The strange thing is that it was working until now, something might have happened in the background. I have been searching for the package python3-looseversion but there is no SLES15SP3 version. Could you please help me with this? Thank you very much in advance!

### Steps to reproduce

1.
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.12-230900.210.2.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2023.10-230900.209.1.uyuni3 installed)
Source package : Uyuni-Server-release-2023.12-230900.210.2.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by kurzandras** [comment]
Might be related to: https://github.com/uyuni-project/uyuni/issues/9062

I have the "Uyuni Client Tools for SLES15 SP3 x86_64" added and synchronized.

**Comment by deneb-alpha** [comment]
hi @kurzandras 

> Might be related to: #9062

Ubuntu 18.04 reported in #9062 is EOL.

> 
> I have the "Uyuni Client Tools for SLES15 SP3 x86_64" added and synchronized.

the  Uyuni version you are using is extremely old (2023.12).
Do you have any chance to update to the current stable 2024.07?

**Comment by kurzandras** [comment]
I have tried it with the newest version as well, its still the same :-(

**Comment by kurzandras** [comment]
Since I need the bootstrapping functionality urgently I decided to quickly remove the python3-looseversion entries from /usr/share/susemanager/mgr_bootstrap_data.py even though there is a warning at the beginning of the file "DO NOT EDIT THIS FILE".

Now that I have removed these entries the boostrapping repository has been created successfully. I have read somewhere that this package is not being used at all in case of venv-salt-bundle client setups. Could someone please confirm this? I plan to move forward with the bootstrapping with this setup and I can just hope that it will not have an impact on the functionality. 

Please if you have any other solutions or suggestions let me know. Thank you in advance!

**Comment by kurzandras** [comment]
Hi @rjmateus 

Thanks for your message. Unfortunately it did not work even with the force option.

**Comment by mcalmer** [comment]
I think 15 SP3 require LTSS subscription to get the missing package. Seems you found a workaround.
