### ISSUE TITLE
containerized proxy: using wrong servername for autoyast.xml

### ISSUE THREAD

**Issue by jmozd** [uyuni-project/uyuni#9137]
### Problem description

Tried to bare-metal install a new system via containerized Uyuni proxy. PXE works fine, the URLs in the grub files are modified to point to the Uyuni proxy's DNS name.
When the contents of the autoyast xml file are parsed, the client reports to be unable to access the repositories - which seems plausible, as the URL points to the podman-internal host name: http://uyuni-proxy-pod/ks/dist/child/...

I've tried to identify where the actual replacement takes place in the httpd container (WSGI scripts), but so far found only a reference to env[ "SERVER_NAME"]. The Apache configuration does have a "ServerName" item stating the correct DNS name of the proxy, so it should be part of the WSGI environment.

Searching for "uyuni-proxy-pod" did find no occurances in uyuni-proxy-httpd's /etc/apache2 directory tree, so it seems to be actually derived from the container's host name at runtime.

### Steps to reproduce

1. create cobbler autoinstallation distro, profile, system
2. retrieve profile via containerized Uyuni proxy: 
    curl -L http://uyuniproxy.company.com/cblr/svc/op/autoinstall/system/client.company.com
3. check <media_url>: http://uyuni-proxy-pod/ks/dist/child/... , where it should be "http://uyuniproxy.company.com/ks/dist/child/...

### Uyuni version

```bash
SUSE Manager 4.3.13
```

### Uyuni proxy version (if used)

Uyuni containerized proxy (latest as of time of report) running via podman on a Raspi 4:

```bash
"org.opensuse.uyuni.proxy-httpd.created": "2024-07-19T10:03:07.780873440Z",
                    "org.opensuse.uyuni.proxy-httpd.description": "Image contains a Uyuni proxy component to serve http requests",
                    "org.opensuse.uyuni.proxy-httpd.disturl": "obs://build.opensuse.org/systemsmanagement:Uyuni:Master/containers/7c91f1005206871994b405502fab5897-proxy-httpd-image",
                    "org.opensuse.uyuni.proxy-httpd.name": "proxy-httpd-image",
                    "org.opensuse.uyuni.proxy-httpd.reference": "registry.opensuse.org/uyuni/proxy-httpd:2024.07.87.1.uyuni3",
                    "org.opensuse.uyuni.proxy-httpd.title": "Uyuni proxy httpd container",
                    "org.opensuse.uyuni.proxy-httpd.url": "https://www.uyuni-project.org/",
                    "org.opensuse.uyuni.proxy-httpd.vendor": "Uyuni project",
                    "org.opensuse.uyuni.proxy-httpd.version": "5.0.6",
                    "org.uyuni.version": "2024.07"

"Version": "24.0.7-ce",
          "Author": "",
          "Architecture": "arm64",
          "Os": "linux",
```

### Additional information

The server running the containerized proxy in question is on

```
# cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

**Comment by aaannz** [comment]
Content of autoyast files is not changed on the fly, but rather by cobbler. It replaces `$redhat_management_server` variable to the proxy or server and that is happening on the server side.
What is the fqdn your proxy is registered under on the SUMA?

**Comment by mcalmer** [comment]
Maybe this is solved already as the question was not answered. Closing

**Comment by jmozd** [comment]
The issue was closed by https://github.com/uyuni-project/uyuni/pull/9265 so it was correct to close the issue
