### ISSUE TITLE
Migrating from legacy to podman PostgreSQL configuration does not transfer.

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#9142]
### Problem description

The migration updates PostgreSQL from 14 to 16 but the configuration gets reset or overwritten.
Had issues where the connections were limited to 100 by default among other tunings.
This caused issues with a bigger amount of clients.
PostgreSQL was configured using fine tuning documentation
https://www.uyuni-project.org/uyuni-docs/en/uyuni/specialized-guides/large-deployments/tuning.html

### Steps to reproduce

1. Migrate legacy to podman.
2. Check PostgreSQL configuration file

### Uyuni version

```bash
2024.07
```

### Uyuni proxy version (if used)

```bash
not used
```

**Comment by mbussolotto** [comment]
Just to be sure, which is the command that you're running?
Can you please provide:
- `uyuni-tools.log`
- `/etc/rhn/rhn.conf`
- `/var/lib/pgsql/data/postgresql.conf`

also, if you can re-run the `mgradm` command with `--logLevel=debug`, it would be really helpful. Thanks
