### ISSUE TITLE
Ability to exclude custom channels from automatic sync

### ISSUE THREAD

**Issue by fd-SR** [uyuni-project/uyuni#9157]
# Short description

Add a switch/attribute on a custom channel that excludes it from the unified sync.

# Details

While the change to unify the sync of custom channels removed a lot of micro-managing schedules, it does not allow disabling the sync for a custom channel anymore (at least as I understand it). 
Sometimes a source might be faulty or even discontinued, but one might still want to keep the custom channel. 
There is of course the possibility to disable the unified sync altogether via _java.unify_custom_channel_management_ but that brings back the micro-managing of the sync schedules for all custom channels. 
And just be clear I don't mean being able to add custom schedules in addition to the unified schedules.
I just mean the ability to mark a custom channel to be excluded from the automatic sync.

**Comment by gabjef** [comment]
+1 vote for this enhancement

**Comment by fd-SR** [comment]
As an update, I worked around this by just deselecting the repository in the Repositories page of the Channel Management. 
I had somehow been under the impression that the packages were linked through the repository to the channel and not directly associated to the channels, that's why I hadn't tried this before. 
So I don't think this feature is really necessary.
