### ISSUE TITLE
Patches disappeared after moving to container

### ISSUE THREAD

**Issue by akupreev** [uyuni-project/uyuni#9190]
### Problem description

Colleagues, good afternoon.
After moving Uyuni from the rpm version to the container, I noticed that all the patches from the channels disappeared. When trying to re-sync the channels, the patches do not appear.
Tell me, what could be the error?

### Steps to reproduce

1.
2.
3.
...

### Uyuni version

```bash
Uyuni release 2024.07
```

### Uyuni proxy version (if used)

```bash
-
```

**Comment by mbussolotto** [comment]
Hi @akupreev ,
Do you still have the problem? Can you try to run "update package list" on you minion (`Software -> Packages`)

**Comment by akupreev** [comment]
@mbussolotto 
Hello, my friend.
I installed the container version on a new server and manually transferred the client machines.

**Comment by mbussolotto** [comment]
> I installed the container version on a new server and manually transferred the client machines.
It might explain the problem. Please use `mgradm migrate` https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/container-deployment/uyuni/migrate-uyuni-to-a-container.html

**Comment by mcalmer** [comment]
no more responses. So I think the problem was solved after using migrate

**Comment by akupreev** [comment]
Good day.
The problem is solved.
