### ISSUE TITLE
Where is the documentation for upgrade podman version of Uyuni?

### ISSUE THREAD

**Issue by JoWe112** [uyuni-project/uyuni#9238]
Documentation for upgrading the podman version of Uyuni from 2024.07 -> 2024.08 is not avalible.

`mgradm upgrade podman` seems to be the way to do it. It then use the tag latest as default.
I prefer that the docs clearly describe how to upgrade and than also use the --tag option.

**Comment by mbussolotto** [comment]
right, doc is missing and it's required. Be

> mgradm upgrade podman seems to be the way to do it. It then use the tag latest as default.

correct, this is the procedure to do it.

cc @jcayouette

**Comment by simonflood** [comment]
I had previously submitted an issue for this against the Uyuni docs - please see https://github.com/uyuni-project/uyuni-docs/issues/3227 - although I didn't call out the --tag option.

**Comment by mbussolotto** [comment]
> although I didn't call out the --tag option.
`--tag` flag might be set  but it's `latest` by default, because this is the best option for a rolling software as uyuni. Anyway any other tag ( greater than the current one), can be provided. 

> I had previously submitted an issue for this against the Uyuni docs - please see https://github.com/uyuni-project/uyuni-docs/issues/3227

Thanks for pointing it out. Maybe this one can be closed as duplicated

**Comment by Etheryte** [comment]
Closing as tracked under another ticket.
