### ISSUE TITLE
how to sync extended life cycle rpm's for RHLE7ELS

### ISSUE THREAD

**Issue by jawahk** [uyuni-project/uyuni#9254]
### Problem description

i got the cdn url for ELS for RHEL7 but unable to sync the packages with uyuni. could some one help on it
---------
need help on import the certificates

### Steps to reproduce

sync the repo.
---
2024/09/09 12:05:15 -00:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'sapservers7.6', '--type', 'yum', '--non-interactive']
2024/09/09 12:05:15 -00:00 Sync of channel started.
Preparing custom SSL CAPATH at /var/cache/rhn/reposync/.ssl-certs/1
2024/09/09 12:05:18 -00:00 RepoMDError: Cannot access repository.
Repository 'sapservers7.6' is invalid.
[sapservers7.6|https://cdn.redhat.com/content/els/rhel/server/7/7Server/x86_64/os?ssl_capath=/var/cache/rhn/reposync/.ssl-certs/1&ssl_clientcert=/var/cache/rhn/reposync/.ssl-certs/1/Entitlement-Cert-31-Jul-2024.pem&ssl_clientkey=/var/cache/rhn/reposync/.ssl-certs/1/Entitlement-key-31-Jul-2024.pem] Valid metadata not found at specified URL
History:
 - [|] Error trying to read from 'https://cdn.redhat.com/content/els/rhel/server/7/7Server/x86_64/os?ssl_capath=/var/cache/rhn/reposync/.ssl-certs/1&ssl_clientcert=/var/cache/rhn/reposync/.ssl-certs/1/Entitlement-Cert-31-Jul-2024.pem&ssl_clientkey=/var/cache/rhn/reposync/.ssl-certs/1/Entitlement-key-31-Jul-2024.pem'
 - Permission to access 'https://cdn.redhat.com/content/els/rhel/server/7/7Server/x86_64/os/content?ssl_capath=/var/cache/rhn/reposync/.ssl-certs/1&ssl_clientcert=/var/cache/rhn/reposync/.ssl-certs/1/Entitlement-Cert-31-Jul-2024.pem&ssl_clientkey=/var/cache/rhn/reposync/.ssl-certs/1/Entitlement-key-31-Jul-2024.pem' denied.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'sapservers7.6' because of the above error.
Could not refresh the repositories because of errors.

### Uyuni version

```bash
2024.07
```

**Comment by mbussolotto** [comment]
please have a look here and let us know if it helps https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/troubleshooting/tshoot-rh-cdn-channel-and-multiple-certs.html

**Comment by mcalmer** [comment]
Seems it solved the problem
