### ISSUE TITLE
Migration to Podman: PostgreSQL authentication errors

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#9268]
### Problem description

Had multiple errors trying to migrate to podman. I've solved several but this one has me stuck. 
Original is a traditional install of 2024.08

NEW server: Rocky 9, podman installed. nftables turned off

Prepare completes:
`mgradm migrate podman --prepare --logLevel debug oldserver.fqdn`

Trying actual migration (above, without --prepare) runs for a while, the errors out with the following. 

This appears to be an auth issue with Postgres. 

What can I do now?

```

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
DONE
10:38AM DBG shared/utils/exec.go:50 > Running: podman run --name uyuni-finalize-pgsql --rm --cap-add NET_RAW --tmpfs /run -v cgroup:/sys/fs/cgroup:rw -v /tmp/mgradm-2219903869:/var/lib/uyuni-tools/ --security-opt label=disable -v var-cobbler:/var/lib/cobbler -v var-salt:/var/lib/salt -v var-cache:/var/cache -v var-spacewalk:/var/spacewalk -v var-log:/var/log -v srv-salt:/srv/salt -v srv-www:/srv/www/ -v srv-tftpboot:/srv/tftpboot -v srv-formulametadata:/srv/formula_metadata -v srv-pillar:/srv/pillar -v srv-susemanager:/srv/susemanager -v srv-spacewalk:/srv/spacewalk -v root:/root -v ca-cert:/etc/pki/trust/anchors -v etc-tls:/etc/pki/tls -v var-pgsql:/var/lib/pgsql -v etc-rhn:/etc/rhn -v tls-key:/etc/pki/spacewalk-tls -v etc-apache2:/etc/apache2 -v etc-systemd-multi:/etc/systemd/system/multi-user.target.wants -v etc-systemd-sockets:/etc/systemd/system/sockets.target.wants -v etc-salt:/etc/salt -v etc-rhn:/etc/rhn -v etc-tomcat:/etc/tomcat -v etc-cobbler:/etc/cobbler -v etc-sysconfig:/etc/sysconfig -v etc-postfix:/etc/postfix -v etc-sssd:/etc/sssd registry.opensuse.org/uyuni/server:latest /var/lib/uyuni-tools/pgsqlFinalize.sh
Adding database access for other containers...
Running smdba system-check autotuning...
Backend error:
        Access denied to UID 'postgres' via sudo.

Starting Postgresql...
===============================================================================
!
! This shell operates within a container environment, meaning that not all
! modifications will be permanently saved in volumes.
!
! Please exercise caution when making changes, as some alterations may not
! persist beyond the current session.
!
===============================================================================
2024-09-12 10:38:28.057 BST   [52]LOG:  redirecting log output to logging collector process
2024-09-12 10:38:28.057 BST   [52]HINT:  Future log output will appear in directory "log".
Reindexing database. This may take a while, please do not cancel it!
REINDEX
Schema update...
report_db_host = localhost
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
Your database schema already matches the schema package version [susemanager-schema-5.0.11-230900.1.5.uyuni3].
Schema upgrade: [susemanager-schema-5.0.11-230900.1.5.uyuni3] -> [susemanager-schema-5.0.11-230900.1.5.uyuni3]
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
Connect to database was not successful.
Report Database schema upgrade failed. Please check the logs.
Error: cannot run PostgreSQL finalize script: failed to run uyuni-finalize-pgsql container: exit status 1

```

### Steps to reproduce

As above. 

### Uyuni version

```bash
2024.08 rpm to podman
```

**Comment by mbussolotto** [comment]
looks like something is misconfigured in your original system:
- please make sure that `/var/lib/pgsql/data/pg_hba.conf` is:
```
local   reportdb        postgres        peer
local   reportdb        all     scram-sha-256
host    reportdb        all     ::/0    scram-sha-256
host    reportdb        all     0.0.0.0/0       scram-sha-256
host    reportdb        all     ::1/128 scram-sha-256
host    reportdb        all     127.0.0.1/32    scram-sha-256
local   susemanager     postgres        peer
local   susemanager     spacewalk       scram-sha-256
host    susemanager     spacewalk       127.0.0.1/32    scram-sha-256
host    susemanager     spacewalk       ::1/128 scram-sha-256
local   replication     all     peer
host    replication     all     ::1/128 ident
host    replication     all     127.0.0.1/32    ident
local   all     all     peer
host    all     all     ::1/128 ident
host    all     all     127.0.0.1/32    ident
local   replication     postgres        peer
``` 
- run `su - postgres` and check if you can access with `postgres` user. Thanks

**Comment by digdilem** [comment]
Thanks for the answer, @mbussolotto - this allowed me to locate the file I needed to change. 

My version of that file is completely different to yours. It's not something I've changed previously, so possibly multiple versions exist out there.

My fix was to use your version, which also failed as well as stop Uyuni working, but then replace every auth section with "trust" to essentially disable authentication. 

That allowed things to progress, but I've had four other show-stopping failures on this migration script so far, and each one requires me to delete the /var/lib/containers/storage directory on the new host because the script won't over-write some existing files. 

This has taken all afternoon, and I now need to get uyuni back into service so I'm stopping it here for now. 

I may start from scratch with a new Opensuse host - whilst in theory it may be possible to run containerised Uyuni on any host, the migration script very much expects the new host to be opensuse. (Example, it breaks because update-ca-certificates  doesn't exist. That's called update-ca-trust on EL machines)    I've worked around several such bugs but starting to lose the will to live now...

**Comment by SSchott** [comment]
I got the same problem, trying to migrate from 2024.07. Everything works up until the last step:
```
The database schema was upgraded to version [susemanager-schema-5.0.11-230900.1.5.uyuni3].
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
Connect to database was not successful.
Report Database schema upgrade failed. Please check the logs.
Error: cannot run PostgreSQL finalize script: failed to run uyuni-finalize-pgsql container: exit status 1
```
This is my `/var/lib/pgsql/data/pg_hba.conf` in the old host, owned and readable by user postgres:
```
local   uyuni   uyuni   scram-sha-256
host    uyuni   uyuni   127.0.0.1/8     scram-sha-256
host    uyuni   uyuni   ::1/128 scram-sha-256
local   uyuni   admin   scram-sha-256
host    uyuni   admin   127.0.0.1/8     scram-sha-256
host    uyuni   admin   ::1/128 scram-sha-256
local   all     all     peer
host    all     all     127.0.0.1/32    ident
host    all     all     ::1/128 ident
local   replication     all     peer
host    replication     all     127.0.0.1/32    ident
host    replication     all     ::1/128 ident
local   replication     postgres        peer
local   reportdb        all     scram-sha-256
host    reportdb        all     127.0.0.1/32    scram-sha-256
host    reportdb        all     ::1/128 scram-sha-256
host    reportdb        all     0.0.0.0/0       scram-sha-256
host    reportdb        all     ::/0    scram-sha-256
```

Not sure what would be the best way to fix this.

**Comment by mbussolotto** [comment]
> local   reportdb        postgres        peer
> local   reportdb        all     scram-sha-256
> host    reportdb        all     ::/0    scram-sha-256
> host    reportdb        all     0.0.0.0/0       scram-sha-256
> host    reportdb        all     ::1/128 scram-sha-256
> host    reportdb        all     127.0.0.1/32    scram-sha-256
> local   susemanager     postgres        peer
> local   susemanager     spacewalk       scram-sha-256
> host    susemanager     spacewalk       127.0.0.1/32    scram-sha-256
> host    susemanager     spacewalk       ::1/128 scram-sha-256
> local   replication     all     peer
> host    replication     all     ::1/128 ident
> host    replication     all     127.0.0.1/32    ident
> local   all     all     peer
> host    all     all     ::1/128 ident
> host    all     all     127.0.0.1/32    ident
> local   replication     postgres        peer

you can copy/paste the one here https://github.com/uyuni-project/uyuni/issues/9268#issuecomment-2346285199 . 
Or  wait next version of uyuni-tools where the problem is fixed https://github.com/uyuni-project/uyuni-tools/pull/461 (it will automatically fix the broken system when running `mgradm upgrade` and prevent the issue running `mgradm migrate`)

**Comment by SSchott** [comment]
@mbussolotto Thanks for the prompt reply! Just tried copying your file, and got:

```
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  Ident authentication failed for user "uyuni"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  Ident authentication failed for user "uyuni"
Error: cannot run migration script: cannot run uyuni migration container: failed to run uyuni-migration container: exit status 2
```
Any ideas?

**Comment by mbussolotto** [comment]
did you run `mgadm restart` ?

If the problem persists, I'd wait for the next `mgradm` version with the fix (the only affected version is the one shipped with 2024.08, the one with 2024.07 should not have this bug). Otherwise you can try with the solution provided by https://github.com/uyuni-project/uyuni/issues/9268#issuecomment-2346430116

**Comment by SSchott** [comment]
So, if I just change the file in the old host, as suggested, it fails, because the admin names in your file and mine are different. Recovering the file to my old one, restarting and stopping pgsql and spacewalk-service allows to continue further, but I end where I was before. So:

Using my file, gets to almost the end, but fails with `psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"`

Using your file, fails at the beginning, when "stopping pgsql" with `psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  Ident authentication failed for user "uyuni"`

**Comment by SSchott** [comment]
> did you run `mgadm restart` ?
I don't really reach to the stage where I can run commands from mgradm beyond migrate.

**Comment by SSchott** [comment]
While `pgsqlFinalize.sh` is running, the file looks like:
```
local   uyuni   uyuni   scram-sha-256
host    uyuni   uyuni   127.0.0.1/8     scram-sha-256
host    uyuni   uyuni   ::1/128 scram-sha-256
local   uyuni   admin   scram-sha-256
host    uyuni   admin   127.0.0.1/8     scram-sha-256
host    uyuni   admin   ::1/128 scram-sha-256
local   all     all     peer
host    all     all     127.0.0.1/32    ident
host    all     all     ::1/128 ident
local   replication     all     peer
host    replication     all     127.0.0.1/32    ident
host    replication     all     ::1/128 ident
local   replication     postgres        peer
local   reportdb        all     scram-sha-256
host    reportdb        all     127.0.0.1/32    scram-sha-256
host    reportdb        all     ::1/128 scram-sha-256
host    reportdb        all     0.0.0.0/0       scram-sha-256
host    reportdb        all     ::/0    scram-sha-256
host uyuni uyuni 10.88.0.18/16 scram-sha-256
```

Which is already what was being added in your new version https://github.com/uyuni-project/uyuni-tools/pull/461 @mbussolotto ?

If you mention this should not happen on 2024.07, I am not sure where to go from here.

**Comment by mbussolotto** [comment]
> If you mention this should not happen on 2024.07

I think you're using latest version, 2024.08, am I right? 

If you want to retry migration, remember to uninstall everything before using `mgradm uninstall -f --purge-volumes`

**Comment by SSchott** [comment]
Hi,

I am using 2024.07. Output from zypper:
```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

It might be that I will have to go hands on and mod things manually to see what is going on with the pythia user. I noticed that if I delete the `data-pg14`  folder I can restart the migration script, but still it fails at the same spot.

I copied the `pgsqlFinalize.sh` script, and want to start an interactive podman container with the options listed in `ps aux` to see what happens in the step it fails. Does that make sense?

**Comment by mbussolotto** [comment]
My bad, I meant `uyuni-tools` version, not `uyuni`. Moreover after I double checked I found that I was wrong, the issue was fixed in > 2024.07. So shortly:
```
mgradm --version
mgradm version 0.1.21 (HEAD f7fc013)
```
or above. When you re-run `migrate`, remember to uninstall everything as I mentioned here https://github.com/uyuni-project/uyuni/issues/9268#issuecomment-2401569403 .

> I copied the pgsqlFinalize.sh script, and want to start an interactive podman container with the options listed in ps aux to see what happens in the step it fails. Does that make sense?

Yes, this is how these issues are debugged :)  just remember to mount all the volumes required.

**Comment by SSchott** [comment]
The version was indeed 0.1.21. I checked the reportdb state in the original host server, and it was also not accessible there. I had a similar issue years ago (found myself while googling... https://github.com/uyuni-project/uyuni/issues/5149), where the db was unaccessible for, still, unclear reasons; I haven't touched anything on those lines, neither that time, not now. I scratched the reportdb and pythia user, and regenerated it before running the migration, and now it went through. I will now check if it actually runs. 

Thanks for the replies though.

**Comment by stdevel** [comment]
I was upgrading from Uyuni 2024.08 (RPM) to 2024.10 (Podman) today and had the same issue. Beside a broken `pg_hba.conf` (was able to use to one from https://github.com/uyuni-project/uyuni/issues/9268#issuecomment-2400234123 but had to change the IP subnet - mine was 10.89.0.0/16) I figured out that there seems to be another error in the migration process.

First, the database on the source system is stopped and files are copied. After reindexing the freshly converted database, the process tries to access the database on the source system again - and fails because it is stopped.

❗  So, when the reindexing is running, head to the source system and immediately run `smdba db-start` ❗

I ran `mgradm migrate podman --prepare` first and `mgradm migrate podman` afterwards - don't know whether this helps troueblshooting.

**Comment by digdilem-work** [comment]
My fix for this was to manually edit `/var/lib/pgsql/data/pg_hba.conf` and disable security for each of the referenced accounts by replacing the auth method with 'trust'.

I can't say that I recommend this from a security perspective, but it did allow me to complete the migration.   It may be possible to revert this after migration.  Obviously make your backups of the original...

Here's what mine looked like before a successful migration to podman.

```
local   reportdb        postgres        trust
local   reportdb        all     trust
host    reportdb        all     ::/0    trust
host    reportdb        all     0.0.0.0/0       trust
host    reportdb        all     ::1/128 trust
host    reportdb        all     127.0.0.1/32    trust
local   susemanager     postgres        trust
local   susemanager     spacewalk       trust
host    susemanager     spacewalk       127.0.0.1/32    trust
host    susemanager     spacewalk       ::1/128 trust
local   replication     all     trust
host    replication     all     ::1/128 trust
host    replication     all     127.0.0.1/32    trust
local   all     all     trust
host    all     all     ::1/128 trust
host    all     all     127.0.0.1/32    trust
local   replication     postgres        trust
host    uyuni   uyuni   all     scram-sha-256
local   replication     postgres        peer
```

**Comment by bjin01** [comment]
@digdilem thanks a lot. I found similar solution as you stated.
I corrected or extended the pg_hba.conf on old Uyuni Server to the following to allow pythia_susemanager login using peer mode. ```
uyuni-server:/ # cat /var/lib/pgsql/data/pg_hba.conf
# Local connections for pythia_susemanager to reportdb using trust
local   reportdb        pythia_susemanager      trust

# IPv4 connections to reportdb for pythia_susemanager with scram-sha-256 (use md5 if you prefer password)
host    reportdb        pythia_susemanager      127.0.0.1/32            scram-sha-256

# IPv6 connections to reportdb for pythia_susemanager with scram-sha-256 (use md5 if you prefer password)
host    reportdb        pythia_susemanager      ::1/128                 scram-sha-256

```
Then did the migration again. Now it works.

**Comment by mbussolotto** [comment]
> First, the database on the source system is stopped and files are copied. After reindexing the freshly converted database, the process tries to access the database on the source system again - and fails because it is stopped.

> ❗ So, when the reindexing is running, head to the source system and immediately run smdba db-start 

@cbosdo I remember some recent discussion about when run re-index and `smdba db-start`, are you aware of this ^^ ?

**Comment by bjin01** [comment]
Now when I want to add ubuntu 24-04 channels I get this error:
```
uyuni-server:~ # spacewalk-common-channels -a amd64-deb "ubuntu-2404-amd64-main-uyuni"
SUSE Manager username: api-user
SUSE Manager password:
SUSE Manager password:
ERROR: ubuntu-24.04-pool-amd64-uyuni could not be found at the server
ERROR: ubuntu-2404-amd64-main-uyuni: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: User 2 does not have access to channel ubuntu-24.04-pool-amd64-uyuni or the channel does not exist
```

**Comment by cbosdo** [comment]
> First, the database on the source system is stopped and files are copied. After reindexing the freshly converted database, the process tries to access the database on the source system again - and fails because it is stopped.

Are you sure of this? The [migration script](https://github.com/uyuni-project/uyuni-tools/blob/main/mgradm/shared/templates/migrateScriptTemplate.go) is the only one running in a container with SSH agent and config mounted. Reindexing happens in the [finalization script](https://github.com/uyuni-project/uyuni-tools/blob/main/mgradm/shared/templates/pgsqlFinalizeScriptTemplate.go)...

The [migration](https://github.com/uyuni-project/uyuni-tools/blob/main/mgradm/cmd/migrate/podman/utils.go) happens in several phases each running in a separate container:
1. The copying phase with the migration script
2. The conversion to postgresql 16 if needed
3. The DB finalization script, running the schema update and the reindexing
4. Post migration operations

After this the final systemd service is prepared and the final container started.

**Comment by stdevel** [comment]
Hi @cbosdo,
yes, I was also confused when I stumbled upon this - but I was able to reproduce this on multiple Uyuni installations.
Didn't try it with fresh (old) Uyuni installations though.
