### ISSUE TITLE
Migration to Podman: Fatal errors

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni#9270]
### Problem description

After spending a day, I've now abandoned trying to migrate Uyuni to Podman on Rocky and am now following the "tested" method of using Leap Micro 5.5

Things definitely went smoother, but still errored out without completing, leaving a broken new host.

Process: New vm. 150Gb dis, 16G ram, 4x cpus. Installed Leap-Micro-5.5

Follow this guide: https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/container-deployment/uyuni/migrate-uyuni-to-a-container.html

Setup ssh etc, all good.

Run prepare: `mgradm migrate podman --prepare --logLevel debug oldserver.fqdn`

This completes without errors first go. Feeling confident. 

It tells me to run again without --prepare, so I do so. 

It then exits after ten minutes or so with:

# Error 1:

`Error: cannot generate systemd service file: failed to generate systemd service unit file: /etc/systemd/system/uyuni-server.service file already present, not overwriting`

I move this file out of the way and re-run. 

# Error 2

The script then stops here. 

```
Checking cluster versions                                     ok
pg_controldata: fatal: could not open file "/var/lib/pgsql/data-pg14/global/pg_control" for reading: No such file or directory

could not get control data using "/usr/lib/postgresql14/bin/pg_controldata" "/var/lib/pgsql/data-pg14": child process exited with exit code 1
Failure, exiting
Error: cannot run PostgreSQL version upgrade script: failed to run uyuni-upgrade-pgsql container: exit status 1
```

Has this migration script been tested recently? It seems very fragile.

### Steps to reproduce

As above

### Uyuni version

```bash
Uyuni 2024-08
```

**Comment by digdilem** [comment]
Update:

I removed the various systemd files and all of /var/lib/container/storage on the new host and then re-ran the migration command WITHOUT --prepare. 

This time it ran through without error. 

So it looks like running --prepare before migration causes the errors in this ticket. 

Closing as I've self-resolved the issue

**Comment by rjmateus** [comment]
Thank for the feedback on this one. Looks like the prepare command is creating the systems file, and then running the migrate is not expecting it already exists.

Prepare flag should not create any systems files, and only start the copy.
@cbosdo @admd for awareness

**Comment by cbosdo** [comment]
The first error should be fixed in `master`. I can't recall having seen the other one...
