### ISSUE TITLE
PAYG mode when we register RHUI client Error getting instance data: timeout: socket is not established

### ISSUE THREAD

**Issue by jawahk** [uyuni-project/uyuni#9274]
### Problem description

when we tried to add latest method of adding RHUI client we are getting below error message 
 timeout: socket is not established

![image](https://github.com/user-attachments/assets/1cc19fa8-8892-4ac9-aad8-94f048cb3921)

could you someone help me steps how to configure AWS RHUI repo on older way(manual way) since i missed the steps.

also request to help to fix this issue 

### Steps to reproduce

image contains the ref. 

### Uyuni version

```bash
2024.07
```

**Comment by mbussolotto** [comment]
cc @mcalmer

**Comment by mcalmer** [comment]
Socket timeout means that the ssh connection could not be established. 
Have you tried manual with "ssh ...." from the Uyuni Server to connect to the RHUI instance? 
You should see the same error and can maybe easier debug it

**Comment by mcalmer** [comment]
No response. So I think the problem is gone
