### ISSUE TITLE
Package install/upgrade fails after migration to containerized podman

### ISSUE THREAD

**Issue by Autoflow** [uyuni-project/uyuni#9318]
Hello everybody,

after migrating to the containerized version of Uyuni (Server Version 2024.08, Podman) and when trying to install/upgrade packages I get errors for all selected hosts. Here an example error for one host: 

`saltutil_|-sync_states_|-sync_states_|-sync_states: name: sync_states changes: { } result: true comment: No updates to sync __sls__: util.syncstates __run_num__: 0.0 start_time: '13:27:44.306941' duration: 437.706 __id__: sync_states pkg_|-mgr_absent_ca_package_|-rhn-org-trusted-ssl-cert_|-removed: name: rhn-org-trusted-ssl-cert changes: { } result: true comment: All specified packages are already absent __sls__: certs __run_num__: 1.0 start_time: '13:27:45.471310' duration: 0.957 __id__: mgr_absent_ca_package file_|-mgr_ca_cert_|-/usr/local/share/ca-certificates/susemanager/RHN-ORG-TRUSTED-SSL-CERT.crt_|-managed: changes: { } comment: File /usr/local/share/ca-certificates/susemanager/RHN-ORG-TRUSTED-SSL-CERT.crt is in the correct state name: /usr/local/share/ca-certificates/susemanager/RHN-ORG-TRUSTED-SSL-CERT.crt result: true __sls__: certs __run_num__: 2.0 start_time: '13:27:45.474321' duration: 54.955 __id__: mgr_ca_cert cmd_|-mgr_update_ca_certs_|-/usr/sbin/update-ca-certificates_|-run: changes: { } result: true duration: 0.003 start_time: '13:27:45.530254' comment: State was not run because none of the onchanges reqs changed __state_ran__: false __run_num__: 3.0 __sls__: certs __id__: mgr_update_ca_certs name: /usr/sbin/update-ca-certificates file_|-mgr_proxy_ca_cert_symlink_|-/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT_|-symlink: result: true name: /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT changes: { } comment: onlyif condition is false __sls__: certs __id__: mgr_proxy_ca_cert_symlink skip_watch: true __run_num__: 4.0 start_time: '13:27:45.530333' duration: 415.715 file_|-mgr_deploy_tools_uyuni_key_|-/etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key_|-managed: changes: { } comment: File /etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key is in the correct state name: /etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key result: true __sls__: channels.gpg-keys __run_num__: 5.0 start_time: '13:27:45.946168' duration: 27.245 __id__: mgr_deploy_tools_uyuni_key file_|-mgr_deploy_suse_addon_key_|-/etc/pki/rpm-gpg/suse-addon-97a636db0bad8ecc.key_|-managed: changes: { } comment: File /etc/pki/rpm-gpg/suse-addon-97a636db0bad8ecc.key is in the correct state name: /etc/pki/rpm-gpg/suse-addon-97a636db0bad8ecc.key result: true __sls__: channels.gpg-keys __run_num__: 6.0 start_time: '13:27:45.973548' duration: 25.823 __id__: mgr_deploy_suse_addon_key file_|-mgrchannels_repo_|-/etc/apt/sources.list.d/susemanager:channels.list_|-managed: changes: { } comment: File /etc/apt/sources.list.d/susemanager:channels.list is in the correct state name: /etc/apt/sources.list.d/susemanager:channels.list result: true __sls__: channels __run_num__: 7.0 start_time: '13:27:45.999580' duration: 107.493 __id__: mgrchannels_repo file_|-aptauth_conf_|-/etc/apt/auth.conf.d/susemanager.conf_|-managed: changes: { } comment: File /etc/apt/auth.conf.d/susemanager.conf is in the correct state name: /etc/apt/auth.conf.d/susemanager.conf result: true __sls__: channels __run_num__: 8.0 start_time: '13:27:46.107211' duration: 71.226 __id__: aptauth_conf pkg_|-install_gnupg_debian_|-install_gnupg_debian_|-installed: name: install_gnupg_debian changes: { } result: true comment: All specified packages are already installed __sls__: channels __run_num__: 9.0 start_time: '13:27:46.178595' duration: 0.75 __id__: install_gnupg_debian pkg_|-pkg_installed_|-pkg_installed_|-installed: name: pkg_installed result: false changes: { } comment: |- Problem encountered installing package(s). Additional info follows: errors: - Running scope as unit: run-r21f0053febac4d88bb23a5dfcbbefb09.scope E: Unable to correct problems, you have held broken packages. __sls__: packages.pkginstall __run_num__: 10.0 start_time: '13:27:46.179582' duration: 1094.638 __id__: pkg_installed

Can someone please point me out what's going wrong and in case tell me if I missed something during migration?

**Comment by Autoflow** [comment]
All minions reside on Debian Hosts, there's no zypper.log for them ...
All I can send is zypper.log of the Uyuni Server.
Interestingly today all worked fine again.
I am relieved to hear that in your opinion it seems not to be a Uyuni problem.

**Comment by mbussolotto** [comment]
closed since it cannot be reproduced. Feel free to re-open it if it happens again
