### ISSUE TITLE
API call create new ssl KEY

### ISSUE THREAD

**Issue by fritz0011** [uyuni-project/uyuni#9361]
# Question

uYUNI 2024.08

We have an ansible role that gets the gets the entitlement from access.redhat.com and store the key to a file called "rh-ent.key"
and certificates to "rh-certs.pem"

We'd like to do an api call to uyuni to create 2 new ssl entries... So far the API documentation is missing to  describe anything related to...

**Comment by mcalmer** [comment]
Look for `kickstart.keys` .
These keys belong to the spacewalk kickstart feature

**Comment by fritz0011** [comment]
solved !! :)
