### ISSUE TITLE
Support for Leap Micro 6.0

### ISSUE THREAD

**Issue by SSchott** [uyuni-project/uyuni#9385]
# Question

Would the latest version work with Leap Micro 6.0? _I know the documentation says Leap Micro 5.5_. I am testing a migrated server, but now transactional-updates break the machine by not being able to mount /etc properly with overlayfs. There might be an obvious reason why Uyuni does not play good with Leap Micro 6.0.

## Version of Uyuni Server and Proxy (if used)

`mgradm version 0.1.21`

**Comment by PorteBannana** [comment]
This working for me.

As we can't download 5.5 i doing a 6.0 and i don't have problems for your information.
The only thing I noticed is that the mgrct and mgradm bash-completion packages are missing

**Comment by stdevel** [comment]
Hi @PorteBannana,
you can find the latest Leap Micro 5.5 ISO here: https://mirror.de.leaseweb.net/opensuse/distribution/leap-micro/5.5/appliances/iso/openSUSE-Leap-Micro.x86_64-Default-SelfInstall.iso

**Comment by PorteBannana** [comment]
> Hi @PorteBannana,
> 
> you can find the latest Leap Micro 5.5 ISO here: https://mirror.de.leaseweb.net/opensuse/distribution/leap-micro/5.5/appliances/iso/openSUSE-Leap-Micro.x86_64-Default-SelfInstall.iso

> Hi @stdevel,
> 
> Thanks for information. I think I don't use this because my uyuni is up and I don't have a problems.

**Comment by SSchott** [comment]
Thanks for the reply. I also managed to make it work, by undoing done of the transactional updates. It seems at some point an upgrade broke the system. Might have been because I added the uyuni repo before the first update? Not sure. In any case, it works now.
