### ISSUE TITLE
When attempting to edit an existing Custom State the page exhibits uncontrollable scrolling and disappearing content in the frame

### ISSUE THREAD

**Issue by gabjef** [uyuni-project/uyuni#9394]
### Problem description

When attempting to edit a custom state page, scrolling control is misbehaving and frame content disappears.
Not able to add states or change the execution order.
The issue occurs with Chrome, Edge and Firefox.

### Steps to reproduce

1. Go to "Recurring Actions" for an org, group or minion
2. Under "Actions", choose to edit an **existing** "Custom state" (assumes existing custom state(s))
3. Trying paging down and then up, you will see the web page state to start act strangely.
4. Once it starts "malfunctioning", you not able to reliably add additional states to the existing custom state nor change the execution order.

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2024.08-230900.221.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.08-230900.221.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
```

### Uyuni proxy version (if used)

```bash
N/A
```

### Additional information

I would post some screen shots if I felt it would help.
But all you have to do is try to edit an existing recurring custom state to see the issue.

**Comment by mcalmer** [comment]
I think this is fixed and should be available with the next Uyuni release.
Possible fix could be https://github.com/uyuni-project/uyuni/pull/9286
@Etheryte ?

**Comment by Etheryte** [comment]
Yeah this sounds like the same issue, please let me know if the problem persists after the next version is out.

**Comment by mcalmer** [comment]
closing as fixed
