### ISSUE TITLE
/usr/bin/spacewalk-watch-channel-sync.sh is missing on 2024.10

### ISSUE THREAD

**Issue by rkoktan** [uyuni-project/uyuni#9403]
### Problem description

I just patched to 2024.10 and discovered /usr/bin/spacewalk-watch-channel-sync.sh is missing.

### Steps to reproduce

1. Attempted to launch /usr/bin/spacewalk-watch-channel-sync.sh from inside the Uyuni container (mgrctl term)
2. /usr/bin/spacewalk-watch-channel-sync.sh
bash: /usr/bin/spacewalk-watch-channel-sync.sh: No such file or directory
3. Looked in /usr/bin/ and spacewalk-watch-channel-sync.sh is not present.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.10-241000.224.1.uyuni5
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : unknown
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.10-241000.224.1.uyuni5.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by rjmateus** [comment]
We have removed it from the container by mistake with this PR: https://github.com/uyuni-project/uyuni/pull/9251/commits
I will revert this part in a new PR next week. Thank you for noticing it.

**Comment by mcalmer** [comment]
I think a simple `tail -f /...../*.log` is doing the same.
It was moved to a contrib repository
