### ISSUE TITLE
Bootstraping problem via ssh

### ISSUE THREAD

**Issue by barborek** [uyuni-project/uyuni#9415]
# Question

Hi, I tried to bootstrap Ubuntu clients, but the systems mixed when I added a second client, as you can see in the screenshot. 

First I added IP 45,222 and secondly IP 45,170. But there is only one system in the system list. Here is the overview of these systems:

**Comment by mcalmer** [comment]
Just guessing. Is this a cloned VM?
https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/troubleshooting/tshoot-registerclones.html

**Comment by barborek** [comment]
Thank you this worked!

**Comment by barborek** [comment]
In cloned Linux VMs, the /etc/machine-id file can have the same value. For this reason, re-generating the machine-id value solves the problem.
