### ISSUE TITLE
Is committing changes to a image necessary on changes to uyuni-server?

### ISSUE THREAD

**Issue by rhar78** [uyuni-project/uyuni#9444]
# Question

_What do you want to know about Uyuni?_

I apologize if these questions are a little ignorant of me but I am not familiar with podman and how it interacts with your product.  

Is committing changes to a image necessary after making the following changes to the uyuni-server container?  

The changes we want to make include (what I gather is typical of a standard Uyuni server build) :
- setup of sssd (so you can auth via pam onto the UI)
- setup/import your certificates for Channels you create.
- run bootstrap modifications (create custom bootstrap files)
- run updates against repositories (sync/resync as needed) 

Or is this now handled by writing out contents to all the following locations under /var/lib/containers/storage/volumes/?
 
```
# ls /var/lib/containers/storage/volumes/
ca-cert/             etc-postfix/         etc-sysconfig/       etc-tomcat/          srv-salt/            srv-www/             var-log/
cgroup/              etc-rhn/             etc-systemd-multi/   root/                srv-spacewalk/       tls-key/             var-pgsql/
etc-apache2/         etc-salt/            etc-systemd-sockets/ srv-formulametadata/ srv-susemanager/     var-cache/           var-salt/
etc-cobbler/         etc-sssd/            etc-tls/             srv-pillar/          srv-tftpboot/        var-cobbler/         var-spacewalk/
```

For example if we make changes inside the container it suggests not all modifications will be permanently saved in volume:

```
# podman ps
CONTAINER ID  IMAGE                                                        COMMAND           CREATED            STATUS        PORTS                   NAMES
041da310ff9d  registry.opensuse.org/uyuni/server:latest  /usr/lib/systemd/...  59 minutes ago  Up 59 minutes (healthy) ... ...
# podman exec -it 041da310ff9d sh
uyuni-server:/ #
uyuni-server:/ #
```

If we then make the changes described above then when done do we need to run this?

```
uyuni-server:/ # logout
# podman commit 041da310ff9d registry.opensuse.org/uyuni/server:latest
```
or is this podman commit redundant?

Also, if updates are made to the release version do we need to review the above?

I'm happy to add more detail if this helps explain the question better.

Thanks.

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : official-uyuni-server
Name           : Uyuni-Server-release
Version        : 2024.10-241000.224.1.uyuni5
Arch           : x86_64
Vendor         : openSUSE
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.10-241000.224.1.uyuni5.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by aaannz** [comment]
> setup of sssd (so you can auth via pam onto the UI)

changes to the sssd (assuming you are using `/etc/sssd` directory) are persisted in etc-sssd volume

> setup/import your certificates for Channels you create.

stored at var-spacewalk volume

> run bootstrap modifications (create custom bootstrap files)

stored at srv-www volume

> run updates against repositories (sync/resync as needed)

if you mean reposync, it is again stored at var-spacewalk volume

Generally uyuni containers are not designed (yet?) for modifying them in any way (building custom image or by committing changes to them)

**Comment by rhar78** [comment]
Thankyou for your feedback.
