### ISSUE TITLE
apart from SUSE , all other supported clients (Redhat, Amazon linux) kicking out from uyuni due to salt 3006.9 version.

### ISSUE THREAD

**Issue by jawahk** [uyuni-project/uyuni#9446]
### Problem description

since salt decom 3005 version, we are forced to use 3006 and latest version to bootsrap the servers but unfortunately uyuni master salt has 3006.0 version. due to version mismatch, servers failed to check in with uyuni post 2 days of on-boarding. 

request permanent fix for this. 

### Steps to reproduce

tried all 3 methods. 
webUI bootstrap, bootsrap script and CLI method
 all 3 methods failed to check in post 2 days

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.10-241000.224.1.uyuni5
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : unknown
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.10-241000.224.1.uyuni5.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by m-czernek** [comment]
Can you provide more information about:

- The system you're trying to onboard (`cat /etc/os-release`)
- The salt version on that system (e.g. `rpm -qi salt`)
- The error message you're seeing (ideally both from client and server side)

Note that you can also use the `venv-salt-minion` package from client tools to have the exact Salt client on the minion as on the master server. This is also known as the Salt Bundle package.

You can either use the `spacewalk-common-channels` tool to synchronize the Salt Bundle channel for your particular minion OS (see `spacewalk-common-channels -l | grep uyuni-client` for a list of channels), or you can check [0] for the repository URLs. For example, [1] points to the RHEL9 client repository, which contains the `venv-salt-minion` RPMs.

[0] https://github.com/uyuni-project/uyuni/blob/master/utils/spacewalk-common-channels.ini
[1] https://github.com/uyuni-project/uyuni/blob/master/utils/spacewalk-common-channels.ini#L2097

**Comment by mcalmer** [comment]
Please use the packages provided by Uuyni Client Tools Repositories. We have a lot of patches on top of standard salt. Only they will really work anyway.
