### ISSUE TITLE
The problem of not being able to bootstrap cloned vms due to machine id

### ISSUE THREAD

**Issue by barborek** [uyuni-project/uyuni#9453]
Hello,

I have a lot of Linux machines in prod in my environment. I want to manage these machines with uyuni. But all of these machines have the same machine id. Since the machines are in prod, I don't want to change the machine id value. Changing the machine id value on machines in prod that have a lot of services running on them can cause other problems that I can't foresee. In this case, I can't bootstrap the machines. Is there an alternative method?

I reviewed the uyuni scripts to read the machine_id value from somewhere else instead of the /etc/machine-id file, but I couldn't make any progress.

Can you support me on this issue?

**Comment by rjmateus** [comment]
you can use this registration method: https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-cli.html

And then you can also set the minion id on the file `/etc/venv-salt-minion/minion_id` file

**Comment by barborek** [comment]
Main problem is same machine-id.  Minion_id value is not same anyway. @rjmateus, doesn't this method use machine-id value ? I do no understand :( 


![Screenshot 2024-11-08 at 20 21 56](https://github.com/user-attachments/assets/e1f49b98-de35-4c52-8283-7a9d7b3d964d)

**Comment by aric89** [comment]
I used two methods for the machine-id issue on Ubuntu.

First method was that I added some lines of code to regenerate the machine-id into the bootstrap scripts and the second method was to run it as an ansible playbook and then run the bootstrap script. Here is the code I used.

`    ansible.builtin.shell: |
      
      rm -f /etc/machine-id
      dbus-uuidgen --ensure=/etc/machine-id
      rm /var/lib/dbus/machine-id
      dbus-uuidgen --ensure
      dhclient -r
`

**Comment by barborek** [comment]
@aric89 thanks yor support but I know this methods. But I can not change machine-id. This wıykd be risky for prod environment. 

It can affect most services. In my research, I saw that changing the machine-id value is risky. Because of that, I want to anathor value instead of machine-id. Of course, if this is possible.

**Comment by barborek** [comment]
Yes, sama macihne-id is problem but changing this in the production environment is risky. We solved this by adding the following lines to the /etc/venv-salt-minion/minion file:

```
grains:
  machine_id: "test01"
```

Thus, the machine with the same machine-id was enrolled to the uyuni server without any problems.

Thanks for your support 🙏
