### ISSUE TITLE
Something broken with --ca / --cert / --key option on spacecmd repo_create command.

### ISSUE THREAD

**Issue by RenownTwiz** [uyuni-project/uyuni#9509]
### Problem description

Since upgrading to 2024.10 we're seeing the below command using RHEL certs fail:

spacecmd repo_create -- -n "External - RedHat CodeReady Linux Builder for RHEL 8 x86_64 RPMs" -u "https://cdn.redhat.com/content/dist/rhel8/8/x86_64/codeready-builder/os" --ca "redhat-uep" --cert "RHEL-Entitlement-Cert-20240301" --key "RHEL-Entitlement-Key-20240301"

It was working in prior versions.  Other spacecmd repo_create commands that do not have certs/keys work just fine.

### Steps to reproduce

1. Add UEP/Key/Cert to Uyuni
2. From command line run:  spacecmd repo_create -- -n "External - RedHat CodeReady Linux Builder for RHEL 8 x86_64 RPMs" -u "https://cdn.redhat.com/content/dist/rhel8/8/x86_64/codeready-builder/os" --ca "redhat-uep" --cert "RHEL-Entitlement-Cert-20240301" --key "RHEL-Entitlement-Key-20240301"

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.10-241000.224.1.uyuni5
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : unknown
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.10-241000.224.1.uyuni5.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by RenownTwiz** [comment]
I can produce logs, which ones would you want to see?

**Comment by rjmateus** [comment]
Server logs at /var/logs/rhn/*
You should see an error or exception in one of the log files in that location.

**Comment by RenownTwiz** [comment]
I think this is the log entry you're looking for, from rhn_web_api.log:

[2024-11-11 20:37:03,307] INFO  - REQUESTED FROM: ::1 CALL: channel.software.createRepo(sslCliKey=******, sslCliCert=RHEL-Entitlement-Cert-20241104, label=External - RedHat CodeReady Linux Builder for RHEL 8 x86_64 RPMs, loggedInUser=admin, type=yum, url=https://cdn.redhat.com/content/dist/rhel8/8/x86_64/codeready-builder/os, sslCaCert=redhat-uep) CALLER: (admin) TIME: 0.009 seconds
redstone.xmlrpc.XmlRpcFault: Invalid crypto key description: no key with such description - RHEL-Entitlement-Key-20241104

**Comment by RenownTwiz** [comment]
I went in post getting the error on the API and manually via the GUI setup the repo and it works fine.

![image](https://github.com/user-attachments/assets/1d74ed7c-4c4b-48d8-aa85-3ca80493a862)

**Comment by RenownTwiz** [comment]
humm Noticing a "k" vs "K" in "key" the log verses the screen grab.  This could have been a typo issue on my side..  I can stand up a sandbox and test through this again.  You might want to put a pin in it until I do that.

**Comment by RenownTwiz** [comment]
ya this can be closed.  It looks like a typo/case issue on the user side.  The test system I have setup already has this repo setup but when I fix the case on the key name the API returns a more normal error of "ERROR: redstone.xmlrpc.XmlRpcFault: There's already a defined repository with given url, please reuse it.".
