### ISSUE TITLE
salt 3006 version not support and servers are failed to checkin with uyuni in a day or 2

### ISSUE THREAD

**Issue by jawahk** [uyuni-project/uyuni#9578]
### Problem description

When using Salt version 3006.X on RHEL 7 and 8 servers, these systems are being removed from Uyuni within a day or two, necessitating a downgrade to Salt 3005, which is unfortunately no longer supported. Additionally, there is no default repository available for RHEL 7 and 8 to install Salt 3005. Our analysis revealed that the Uyuni master is running Salt version 3006 from SUSE, with no option to upgrade to the latest Salt version, 3007. This issue persists even though we are operating on the latest stable Uyuni version, 2024.10. The complication arises further during script bootstrap, SSH, and CLI methods, as they all require a Salt client, underscoring the need for a local repo or alternative solution to address this compatibility issue.

### Steps to reproduce

try to on-board rhel7 or rhel8 servers to uyuni with 3006.9 version it will failed to check in with uyuni in a day or 2

### Uyuni version

```bash
uyuni-server:/ # zypper info Uyuni-Server-release
Refreshing service 'container-suseconnect-zypp'.
Retrieving repository 'SLE_BCI' metadata .....................................................................................................................................................................[done]
Building repository 'SLE_BCI' cache ..........................................................................................................................................................................[done]
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.10-241000.224.1.uyuni5
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : unknown
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.10-241000.224.1.uyuni5.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
```

**Comment by jawahk** [comment]
if anyone using rhel7 and rhel8 by using salt3006.9 version please let me know how to keep it stable during on-boarding

**Comment by rjmateus** [comment]
You should use the salt minion version provided by the uyuni client tools, that is tested and is supported

**Comment by mcalmer** [comment]
Use spacewalk-common-channels to mirror the Uyuni Client Tools channels for RHEL7. There you will get venv-salt-minion packages which work with Uyuni. Upstream might not work at all as they miss a lot of fixes
