### ISSUE TITLE
Should spacewalk-common-channels add scheduled syncing and be synced when added?

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/uyuni#958]
Either by default (as adding SCC channels do), or at least with a parameter.

In my opinion, yes. Custom channels created by `spacewalk-common-channels` should behave in the same way channels from SCC do.

It would be convenient for users and it would be coherent.

**Comment by paususe** [comment]
I'd say for *any* custom channel, not only for the ones created by `spacewalk-common-channels`.

**Comment by juliogonzalez** [comment]
> I'd say for any custom channel, not only for the ones created by spacewalk-common-channels.

Then I in this case it's "per repository", as if you don't use `spacewalk-common-channels` you need to add repositories first (where the sync is done and autosync is configured), and then you add the repositories to the channels.

**Comment by paususe** [comment]
This issue is superseded by #10330, closing
